### ISSUE TITLE
Solaar error on Wayland

### ISSUE THREAD

**Issue by borkra** [pwr-Solaar/Solaar#1006]
Solar: 1.0.4-22-gf42ff35
Kernel 5.9.8

Dump:
```
Nov 19 16:49:15 xxx solaar.desktop[4106058]:  * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
Nov 19 16:49:15 xxx solaar.desktop[4106058]: Try one of the following resolutions:
Nov 19 16:49:15 xxx solaar.desktop[4106058]: ImportError: this platform is not supported: ('failed to acquire X connection: Can\'t connect to display ":0": b\'No protocol specifie>
Nov 19 16:49:15 xxx solaar.desktop[4106058]:     raise ImportError('this platform is not supported: {}'.format(
Nov 19 16:49:15 xxx solaar.desktop[4106058]:   File "/usr/local/lib/python3.8/dist-packages/pynput/_util/__init__.py", line 76, in backend
Nov 19 16:49:15 xxx solaar.desktop[4106058]:     backend = backend(__name__)
Nov 19 16:49:15 xxx solaar.desktop[4106058]:   File "/usr/local/lib/python3.8/dist-packages/pynput/keyboard/__init__.py", line 31, in <module>
Nov 19 16:49:15 xxx solaar.desktop[4106058]:     from . import keyboard
Nov 19 16:49:15 xxx solaar.desktop[4106058]:   File "/usr/local/lib/python3.8/dist-packages/pynput/__init__.py", line 40, in <module>
Nov 19 16:49:15 xxx solaar.desktop[4106058]:     from pynput import keyboard as _keyboard
Nov 19 16:49:15 xxx solaar.desktop[4106058]:   File "/usr/local/lib/python3.8/dist-packages/logitech_receiver/diversion.py", line 30, in <module>
Nov 19 16:49:15 xxx solaar.desktop[4106058]:     from . import diversion as _diversion
Nov 19 16:49:15 xxx solaar.desktop[4106058]:   File "/usr/local/lib/python3.8/dist-packages/logitech_receiver/notifications.py", line 30, in <module>
Nov 19 16:49:15 xxx solaar.desktop[4106058]:     from logitech_receiver import notifications as _notifications
Nov 19 16:49:15 xxx solaar.desktop[4106058]:   File "/usr/local/lib/python3.8/dist-packages/solaar/listener.py", line 32, in <module>
Nov 19 16:49:15 xxx solaar.desktop[4106058]:     import solaar.listener as listener
Nov 19 16:49:15 xxx solaar.desktop[4106058]:   File "/usr/local/lib/python3.8/dist-packages/solaar/gtk.py", line 153, in main
Nov 19 16:49:15 xxx solaar.desktop[4106058]: solaar: error: Traceback (most recent call last):
```

**Comment by pfps** [comment]
Yeah, the notification rule code requires X11.   I'll make it conditional.

**Comment by pfps** [comment]
PR #1007 makes rule processing conditional on X11.  Please try out this PR.  If you run `bin/solaar -d` you should see a warning stating that rule processing is not available but everything else should work.





To clone and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1007, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1007/head:pull_1007
git checkout pull_1007
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1007
git fetch origin pull/1007/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
If anyone knows how to find out the modifier key status and simulate input in Wayland without needing root access please comment here.

**Comment by borkra** [comment]
As far as I know both X11 and Wayland are using libinput to handle events. So seems you could use it too. There is python-libinput module as well.

**Comment by pfps** [comment]
That requires special privileges, unfortunately.  Fortunately full root access is not needed, so this is a possibility.

What is needed for rule processing is a way of obtaining the state of the keyboard modifier flags on a seat basis (which is used as a condition in rules) and a way of simulating keyboard and mouse input.  It looks as if libinput doesn't provide either.

**Comment by pfps** [comment]
The solution for now is going to be to not have rules under Wayland.  If anyone can figure out a replacement for Xtest in Wayland that can be done without root access please speak up.
