### ISSUE TITLE
Unpair device => select parent receiver?

### ISSUE THREAD

**Issue by Noughtnaut** [pwr-Solaar/Solaar#1011]
**Information**
- Solaar version (`solaar --version` and `git describe --tags`): 1.0.1
- Distribution: Ubuntu MATE 20.04
- Kernel version (ex. `uname -srmo`): Linux 5.4.0-54-generic x86_64 GNU/Linux

**Is your feature request related to a problem? Please describe.**
I find that, of the times where I'm fiddling with Solaar, I often have the need to unpair and re-pair a device. Mind you, not because of a software problem, but perhaps I've brought a paired mouse with me somewhere else, _paired it there_, and upon my return the mouse then needs to be re-paired to the former receiver.

**Describe the solution you'd like**
In those cases, it would be a tiny convenience if unpairing a device would mean that its receiver would be selected in the device list, rather than (as now) whatever random other device might be listed right above the newly unpaired device.

**Describe alternatives you've considered**
Applying local manual labour

**Additional context**
I really hope this is a 5-minute job, [otherwise](https://xkcd.com/1205/) I suppose I'll manage to make one _whole_ extra mouse click myself.

**Comment by pfps** [comment]
Unfortunately the selection of a device after unpairing is an asynchronous action done by GTK in response to trying to show the unpaired device.   Modifying what is selected is non-trivial.

**Comment by Noughtnaut** [comment]
What a shame. All right, I appreciate the speedy answer. Thank you.
