### ISSUE TITLE
Solaar not finding 535 mouse on Fedora 33

### ISSUE THREAD

**Issue by tuxedotje** [pwr-Solaar/Solaar#1015]
fresh install: 
error message:
$ solaar show
/usr/lib/python3.9/site-packages/solaar/ui/__init__.py:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Gtk
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/solaar/cli/__init__.py", line 195, in run
    raise Exception('No devices found')
Exception: No devices found

What todo now?

**Comment by pfps** [comment]
Which version of Solaar are you running?  The M535 uses bluetooth, which is only supported in version 1.0.4 and above.

**Comment by tuxedotje** [comment]
Running 1.0.4 Did remove and re-install  Now it works.
