### ISSUE TITLE
Harmony Companion (remote control device for HUB) support and thanks...... shows as 20+

### ISSUE THREAD

**Issue by frankk74** [pwr-Solaar/Solaar#1019]
Hi,

Thank you to all the guys that are keeping this project running!!!

Seems Solaar 90% supports the Harmony "Companion" Remove control. :-)

One minor "issue" it calls it a "Harmony 20+" but I think it should report it as a "Harmony Companion Remote"

https://www.logitech.com/en-ca/products/harmony/harmony-companion.915-000239.html

--- snip snip official request below -----------------------------------------------------------

**Information**

- Solaar version (`solaar --version` and `git describe --tags`):

solaar --version
solaar 1.0.4

From Fedora 33 repo...
Installed Packages
Name         : solaar
Version      : 1.0.4
Release      : 2.fc33
Architecture : noarch
Size         : 1.1 M
Source       : solaar-1.0.4-2.fc33.src.rpm
Repository   : @System
From repo    : updates
Summary      : Device manager for a wide range of Logitech devices
URL          : https://github.com/pwr/Solaar
License      : GPLv2
Description  : Solaar is a device manager for Logitech's Unifying Receiver
             : peripherals. It is able to pair/unpair devices to the receiver
             : and, for most devices, read battery status.
             : 
             : gtk3 is recommended.  Without it, you can run solaar commands to
             : view the configuration of the devices and pair/unpair peripherals
             : but you cannot use the graphical interface.

- Distribution:

Fedora 33

- Kernel version (ex. `uname -srmo`):

Linux 5.9.8-200.fc33.x86_64 x86_64 GNU/Linux

- Output of `solaar show` for the target device (if applicable):
```
OUTPUT HERE

  2: Remote Control Harmony 20+
     Device path  : None
     WPID         : 401E
     Codename     : Harmony 20+
     Kind         : ?
     Protocol     : HID++ 2.0
     Polling rate : 40 ms (25Hz)
     Serial number: AF6AD886
     Model ID:      000000000000
     Unit ID:       00000000
          Firmware: RQK 46.00.B000B
     Supports 20 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: FEATURE INFO           {0002}   
         3: DEVICE FW VERSION      {0003}   
            Firmware: Firmware RQK 46.00.B000B 401E
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         4: DEVICE NAME            {0005}   
            Name: Remote Control Harmony 20+
            Kind: keyboard
         5: BATTERY STATUS         {1000}   
            Battery: 70%, discharging, next level 20%.
         6: unknown:1820           {1820}   internal, hidden
         7: REPROG CONTROLS        {1B00}   
         8: REPROG CONTROLS V2     {1B01}   
         9: WIRELESS DEVICE STATUS {1D4B}   
        10: REMAINING PAIRING      {1DF0}   hidden
        11: unknown:1DF3           {1DF3}   hidden
        12: ENCRYPTION             {4100}   
        13: KEYBOARD LAYOUT        {4520}   
        14: unknown:1E00           {1E00}   hidden
        15: unknown:1830           {1830}   internal, hidden
        16: unknown:1860           {1860}   internal, hidden
        17: unknown:1890           {1890}   internal, hidden
        18: unknown:1E90           {1E90}   internal, hidden
        19: unknown:18B0           {18B0}   internal, hidden
     Has 12 reprogrammable keys:
         0: unknown:0000               => unknown:0000                  
         1: unknown:0000               => unknown:0000                  
         2: unknown:0000               => unknown:0000                  
         3: unknown:0000               => unknown:0000                  
         4: unknown:0000               => unknown:0000                  
         5: unknown:0000               => unknown:0000                  
         6: unknown:0000               => unknown:0000                  
         7: unknown:0000               => unknown:0000                  
         8: unknown:0000               => unknown:0000                  
         9: unknown:0000               => unknown:0000                  
        10: unknown:0000               => unknown:0000                  
        11: unknown:0000               => unknown:0000                  
     Battery: 70%, discharging, next level 20%.



```

**Is your feature request related to a problem? Please describe.**

One minor "issue" it calls it a "Harmony 20+" but I think it should report it as a "Harmony Companion Remote"
https://www.logitech.com/en-ca/products/harmony/harmony-companion.915-000239.html

It seems all the controls work...

**Describe the solution you'd like**

Rename Harmony 20+ to Harmony Companion Remote and document in devices and change kind from "Keyboard" to "remote"

**Describe alternatives you've considered**
I looked through code quickly and could not find "Harmony 20+"

**Additional context**
![image](https://user-images.githubusercontent.com/16901967/100535555-07ebce00-31e8-11eb-9560-f4e9607b8f66.png)

**Comment by pfps** [comment]
The name, codename, and kind (keyboard) all come from what the device reports.  I don't think there is a need to put in a special description for this device into Solaar.

There is, however, a glitch in Solaar that is showing up in your output - the first kind shown.  Can you run `solaar -dd show` when your device is active and provide the output?
This device has a useful feature that Solaar does not support - REPROG_CONTROLS_V2.  If you are interested in changing how keys work and can test new version of Solaar it may be possible to add this capability to Solaar.

**Comment by frankk74** [comment]
The remote seems to power itself off fairly quickly... so the cli output and gui output are at different times..

As another (sorry) feature request is to show firmware versions in qui? of usb and devices?

My reason for using Solaar was more to diagnose if the remote was working because the hub seems to forget it ...

[debug-remote.txt](https://github.com/pwr-Solaar/Solaar/files/5614042/debug-remote.txt)

**Comment by pfps** [comment]
The device does not report its kind consistently.  One interface responds as remote control and the other as keyboard.  I'm putting in a PR to handle the first interface better.

Solaar shows firmware information in `solaar show`.   It's not worthwhile to show in the GUI.

**Comment by frankk74** [comment]
Many thanks!!!!
