### ISSUE TITLE
solaar still failing on Wayland

### ISSUE THREAD

**Issue by borkra** [pwr-Solaar/Solaar#1023]
Issue #1006 has not been fixed completely:

Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:   File "/usr/local/lib/python3.8/dist-packages/solaar/ui/diversion_rules.py", line 28, in <module>
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:   File "/usr/local/lib/python3.8/dist-packages/solaar/ui/window.py", line 40, in <module>
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:   File "/usr/local/lib/python3.8/dist-packages/solaar/ui/tray.py", line 35, in <module>
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:   File "/usr/local/lib/python3.8/dist-packages/solaar/ui/__init__.py", line 96, in <module>
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:     import solaar.ui as ui
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:   File "/usr/local/lib/python3.8/dist-packages/solaar/gtk.py", line 152, in main
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]: solaar: error: Traceback (most recent call last):

**Comment by pfps** [comment]
Please provide more of the error output.    I don't see what the error is.

**Comment by borkra** [comment]
Syslog does not have anything else ...

**Comment by borkra** [comment]
Found it:

Dec 02 07:16:21 boris-ubuntu gnome-shell[2650]: Errors from xkbcomp are not fatal to the X server
Dec 02 07:16:21 boris-ubuntu gnome-shell[2650]: > Internal error:   Could not resolve keysym Invalid
Dec 02 07:16:21 boris-ubuntu gnome-shell[2650]: >                   X11 cannot support keycodes above 255.
Dec 02 07:16:21 boris-ubuntu gnome-shell[2650]: > Warning:          Unsupported maximum keycode 569, clipping.
Dec 02 07:16:21 boris-ubuntu gnome-shell[2650]: The XKEYBOARD keymap compiler (xkbcomp) reports:
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]: Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n'
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:     raise error.DisplayConnectionError(self.display_name, r.reason)
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:   File "/usr/local/lib/python3.8/dist-packages/Xlib/protocol/display.py", line 166, in __init__
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:     protocol_display.Display.__init__(self, *args, **keys)
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:   File "/usr/local/lib/python3.8/dist-packages/Xlib/display.py", line 71, in __init__
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:     self.display = _BaseDisplay(display)
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:   File "/usr/local/lib/python3.8/dist-packages/Xlib/display.py", line 89, in __init__
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:     disp_prog = Display()
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:   File "/usr/local/lib/python3.8/dist-packages/logitech_receiver/diversion.py", line 58, in <module>
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:     from logitech_receiver import diversion as _DIV
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:   File "/usr/local/lib/python3.8/dist-packages/solaar/ui/diversion_rules.py", line 28, in <module>
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:     from .diversion_rules import show_window as _show_diversion_window
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:   File "/usr/local/lib/python3.8/dist-packages/solaar/ui/window.py", line 40, in <module>
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:     from .window import popup as _window_popup
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:   File "/usr/local/lib/python3.8/dist-packages/solaar/ui/tray.py", line 35, in <module>
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:     from . import notify, tray, window  # isort:skip  # noqa: E402
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:   File "/usr/local/lib/python3.8/dist-packages/solaar/ui/__init__.py", line 96, in <module>
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:     import solaar.ui as ui
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]:   File "/usr/local/lib/python3.8/dist-packages/solaar/gtk.py", line 152, in main
Dec 02 07:16:21 boris-ubuntu solaar.desktop[2459]: solaar: error: Traceback (most recent call last):

**Comment by pfps** [comment]
OK, I see the problem.

**Comment by pfps** [comment]
Please give PR #1024 a try.  To get error messages run `bin/solaar -d` or `bin/solaar -dd`.

To download and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1024, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1024/head:pull_1024
git checkout pull_1024
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1024
git fetch origin pull/1024/head
git reset --hard FETCH_HEAD
```

**Comment by borkra** [comment]
BTW, regarding previous discussion, after some reading  it looks like Wayland using xkb as well, so if you use xkb directly not through X11, you might be able to create code that operate on both  X11 and Wayland.

**Comment by borkra** [comment]
It works now

**Comment by pfps** [comment]
OK, I'll merge the PR in.
