### ISSUE TITLE
Add N600 Laptouch Desk support

### ISSUE THREAD

**Issue by frankk74** [pwr-Solaar/Solaar#1029]
Thx again!!

Didn't use git version but N600 not currently defined.

**Information**
- Solaar version:
solaar 1.0.4
- Distribution: Fedora 33 (Workstation)
- Kernel version:
Linux 5.9.12-200.fc33.x86_64 x86_64 GNU/Linux
- Output of `solaar show` for the target device:

```
 3: Lapdesk Touch N600
     Device path  : None
     WPID         : 4006
     Codename     : N600
     Kind         : touchpad
     Protocol     : HID++ 2.0
     Polling rate : 8 ms (125Hz)
     Serial number: E83C57A8
     Model ID:      000000000000
     Unit ID:       00000000
          Firmware: RQM 31.01.B0062
        Bootloader: BL  02.00.B0018
          Hardware: 72
     The power switch is located on the top right corner.
     Supports 19 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: FEATURE INFO           {0002}   
         3: DEVICE FW VERSION      {0003}   
            Firmware: Firmware RQM 31.01.B0062 4006
            Firmware: Bootloader BL  02.00.B0018 4006
            Firmware: Hardware  72 
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         4: DEVICE NAME            {0005}   
            Name: Lapdesk Touch N600
            Kind: touchpad
         5: BATTERY STATUS         {1000}   
            Battery: 90%, discharging, next level 50%.
         6: WIRELESS DEVICE STATUS {1D4B}   
         7: unknown:1DF3           {1DF3}   hidden
         8: REPROG CONTROLS        {1B00}   
         9: unknown:1F03           {1F03}   hidden
        10: VERTICAL SCROLLING     {2100}   
            Roller type: normal touch pad
            Ratchet per turn: 18
            Scroll lines: 0
        11: HI RES SCROLLING       {2120}   
            Hi-res scrolling disabled
            Hi-res scrolling multiplier: 8
            Scroll Wheel High Resolution: False
        12: MOUSE POINTER          {2200}   
            DPI: 1000
            Acceleration: low
            Override OS ballistics
            No vertical tuning, standard mice
        13: DFUCONTROL LEGACY      {00C0}   
        14: unknown:1E80           {1E80}   hidden
        15: TOUCHPAD RAW XY        {6100}   hidden
        16: TOUCHPAD FW ITEMS      {6010}   
        17: TOUCHPAD SW ITEMS      {6011}   
        18: unknown:1E00           {1E00}   hidden
     Has 6 reprogrammable keys:
         0: Left Button                => Left Click                    mse
         1: Right Button               => Right Click                   mse
         2: Volume Up                  => Volume Up                     mse
         3: Volume Down                => Volume Down                   mse
         4: Mute                       => Mute                          mse
         5: MY HOME                    => HomePage                      mse, reprogrammable
     Battery: 90%, discharging, next level 50%.
```

**Is your feature request related to a problem? Please describe.**
N600 doesn't function without update to descriptor.py

**Additional context**

Tested update to file discriptor.py

``_D('Lapdesk Touchpad N600', codename='laptouch', protocol=2.0, wpid='4006')``

Kernel whining from dmesg:

[ 8716.453402] logitech-hidpp-device 0003:046D:4006.0007: item fetching failed at offset 0/0
[ 8716.453426] logitech-hidpp-device 0003:046D:4006.0007: hidpp_probe:parse failed
[ 8716.453442] logitech-hidpp-device: probe of 0003:046D:4006.0007 failed with error -22

**Comment by pfps** [comment]
Devices that use HID++ 2.0 should not need a description in descriptor.py.  What doesn't work if the description is not there?

The kernel messages are not from Solaar, I believe, so changes to Solaar should not affect them.

**Comment by frankk74** [comment]
Hi,

Ahh right sorry. When I paired which was successful it didn't work right away. I undid the changes and un/repaired it did the same. But when I unplugged the receiver it started to work. So my mistake it does work. But how come for this device the receiver need to be unplugged? Please close unless an enhancement is required to trigger HID++2.0 re-reading?

Thx guys!!!!

**Comment by pfps** [comment]
There are a few things that could have happened.   The most likely is that the hidraw device node was not readable by Solaar because an old udev rule was in place when the device was last connected.  Unplugging and replugging causes udev rules to be rerun so that could have  fixed the problem. 
I'm closing this for now.  If you run into this problem later, just reopen this issue.
