### ISSUE TITLE
Mouse "forgets" settings

### ISSUE THREAD

**Issue by WhyNotHugo** [pwr-Solaar/Solaar#1031]
I've a Logitech MX Vertical. I'm connecting it via bluetooth.

The DPI on it is too high. I can run `solaar`, and set the DPI to 800. However, when I restart the computer, the DPI is back to the default.

Is there a way to make the mouse "remember" the DPI setting, or is this a hardware limitation?

If it's not possible, is there a way to run solaar in a "oneshot" mode (e.g.: start, configure the mouse, exit).

**Comment by pfps** [comment]
Most device settings do not persist so Solaar pushes them to the device whenever Solaar thinks this might be needed.   There were bugs in how this worked so you may have to use the most recent version of Solaar to have it work correctly.

**Comment by pfps** [comment]
`solaar config Vertical dpi 800` should set yourmouse dpi to 800.
