### ISSUE TITLE
Command line to activate specific option

### ISSUE THREAD

**Issue by ZacharieALES** [pwr-Solaar/Solaar#1032]
It is more a question than a feature request (but I don't know where to ask).

I know how to set the value of parameter "fn-lock" with a command: `~/Solaar/bin/solaar config 1 fn-swap 0`
 
However, I can't find how to fix "Natural scrolling" or "Zoom with two fingers" using a command. I found that "Natural scrolling corresponds to the parameter of id 45 in parameter gesture2-gestures but I did not find how to set it. 

Less important questions:
- how does "Tap and drag" works? After several tests I was not able to drag anything (I am using the last version of Solaar with a keyboard logitech K400+ on Ubuntu 20.04.1) ;
- what does "Swipe from the left edge" do? It does not seem to change anything when I activate it.

Thank you for this great tool!

**Comment by pfps** [comment]
The Solaar config command only works for simple settings.  Extending it should not be too hard, but it's not being worked on.
The gestures probably send some HID (or maybe HID++) message.  If your driver/OS/DM doesn't do anything with the message then there will not be any visible effect from turning the gesture on.

**Comment by ZacharieALES** [comment]
Ok thank you for the quick answer!

**Comment by viniciusbm** [comment]
> how does "Tap and drag" works? After several tests I was not able to drag anything (I am using the last version of Solaar with a keyboard logitech K400+ on Ubuntu 20.04.1) ;

When the cursor is hovering over something that can be dragged, tap twice on the touchpad, but keep the finger pressed after the second tap; then, moving the cursor should drag the item. 


> what does "Swipe from the left edge" do? It does not seem to change anything when I activate it.

I'm not sure if this works the same way across different models, but my K400+ sends the following useless combinations (`F23` can be interpreted as `XF86TouchPadOff`).

```
LeftEdgeSwipe1Finger2   =>  Ctrl + Super + Backspace
RightEdgeSwipe1Finger2  =>   Alt + Super + F23
TopEdgeSwipe1Finger2    =>  Ctrl + Super + F23
```

**Comment by pfps** [comment]
PR #1080 adds capabilities to `solaar config` and should address this issue.

To run PR #1080, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1080/head:pull_1080
git checkout pull_1080
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1080
git fetch origin pull/1080/head
git reset --hard FETCH_HEAD
```
