### ISSUE TITLE
K830 mouse pad not working

### ISSUE THREAD

**Issue by Pontan666** [pwr-Solaar/Solaar#1034]
My K830 keyboard is working but the mouse pad isn't. It is mentioned in the support devices list but is there something I'm missing?

**Comment by pfps** [comment]
I'm assuming that you mean the trackpad that is part of the K830.

Solaar only supports some of the features Logitech devices, so it is entirely possible that Solaar currently does something useful only for the keyboard parts of the K830.  Also, recent versions of Solaar support more features than older versions, so it may be worthwhile to run Solaar from this repository.  For example, support for touchpad gestures was recently added to Solaar.

If there are things that are not working usefully you will need to say what you think is not working and provide more information on the device.  The output of `solaar show` is part of the needed information.

**Comment by Pontan666** [comment]
Thanks for fast response. Yes, you are right, the track pad. My version is 1.0.1 and that is the latest version as far as I know. I'm absolutely new (one day now) to Ubuntu and the linux world. Can you please help me out by guide me how to get the output of Solaar show? Thanks again!

**Comment by pfps** [comment]
Version1.0.1 is rather old and won't do much with the trackpad.   The packages in Ubuntu tend to be old.  Look at https://github.com/pwr-Solaar/Solaar and see whether you can use the Ubuntu stable or git packages.  Alternatively you should be able to install Solaar using pip.  For more information see https://pwr-solaar.github.io/Solaar/installation

To use the current version of Solaar you need to open a shell window and enter
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
bin/solaar
```
This will not install Solaar as a normal command.  

You should be able just enter `solaar show`in a shell window to get reasonable `show` output.  But

**Comment by Pontan666** [comment]
3: Illuminated Living-Room Keyboard K830
     Codename     : K830
     Kind         : keyboard
     Wireless PID : 404C
     Protocol     : HID++ 4.1
     Polling rate : 8 ms (125Hz)
     Serial number: 6FA297E4
        Bootloader: BOT 21.00.B0005
          Firmware: RQK 62.00.B0010
          Firmware: RBK 40.00.B0010
             Other: 
     The power switch is located on the edge of top right corner.
     Supports 28 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
         7: BACKLIGHT              {1981}   
         8: unknown:1A20           {1A20}   internal, hidden
         9: REPROG CONTROLS V4     {1B04}   
        10: SWAP BUTTON            {2005}   
        11: NEW FN INVERSION       {40A2}   
        12: ENCRYPTION             {4100}   
        13: KEYBOARD DISABLE       {4521}   
        14: TOUCHPAD RAW XY        {6100}   hidden
        15: GESTURE 2              {6501}   
        16: DFUCONTROL 2           {00C1}   
        17: unknown:1811           {1811}   internal, hidden
        18: unknown:1830           {1830}   internal, hidden
        19: unknown:1890           {1890}   internal, hidden
        20: unknown:1891           {1891}   internal, hidden
        21: unknown:18A0           {18A0}   internal, hidden
        22: unknown:1DF3           {1DF3}   internal, hidden
        23: unknown:1E00           {1E00}   hidden
        24: unknown:1EB0           {1EB0}   internal, hidden
        25: unknown:1861           {1861}   internal, hidden
        26: unknown:18B0           {18B0}   internal, hidden
        27: unknown:1F07           {1F07}   internal, hidden
     Has 19 reprogrammable keys:
         0: unknown:00B8              , default: LeftClick                   => unknown:00B8              
             mse, divertable, pos:0, group:0, gmask:0
         1: BACK AS HID               , default: BackEx                      => BACK AS HID               
             is FN, FN sensitive, reprogrammable, divertable, pos:2, group:0, gmask:0
         2: MY HOME                   , default: HomePage                    => MY HOME                   
             is FN, FN sensitive, reprogrammable, divertable, pos:3, group:0, gmask:0
         3: Application Switcher      , default: Application Switcher        => Application Switcher      
             is FN, FN sensitive, reprogrammable, divertable, pos:4, group:0, gmask:0
         4: CONTEXTUAL MENU           , default: RightClick                  => CONTEXTUAL MENU           
             is FN, FN sensitive, reprogrammable, divertable, pos:5, group:0, gmask:0
         5: SEARCH                    , default: SearchForFiles              => SEARCH                    
             is FN, FN sensitive, reprogrammable, divertable, pos:6, group:0, gmask:0
         6: SHOW DESKTOP              , default: ShowDesktop                 => SHOW DESKTOP              
             is FN, FN sensitive, reprogrammable, divertable, pos:7, group:0, gmask:0
         7: WIN7 MAXIMIZE AS WIN ARROW, default: unknown:0095                => WIN7 MAXIMIZE AS WIN ARROW
             is FN, FN sensitive, reprogrammable, divertable, pos:8, group:0, gmask:0
         8: MEDIA PLAYER              , default: Music                       => MEDIA PLAYER              
             is FN, FN sensitive, reprogrammable, divertable, pos:9, group:0, gmask:0
         9: Previous                  , default: Previous                    => Previous                  
             is FN, FN sensitive, divertable, pos:10, group:0, gmask:0
        10: Play/Pause                , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, divertable, pos:11, group:0, gmask:0
        11: Next                      , default: Next                        => Next                      
             is FN, FN sensitive, divertable, pos:12, group:0, gmask:0
        12: SLEEP                     , default: Sleep                       => SLEEP                     
             reprogrammable, divertable, pos:0, group:0, gmask:0
        13: Mute                      , default: Mute                        => Mute                      
             nonstandard, divertable, pos:0, group:0, gmask:0
        14: Volume Down               , default: Volume Down                 => Volume Down               
             nonstandard, divertable, pos:0, group:0, gmask:0
        15: Volume Up                 , default: Volume Up                   => Volume Up                 
             nonstandard, divertable, pos:0, group:0, gmask:0
        16: unknown:00B7              , default: ShowUI                      => unknown:00B7              
             divertable, pos:0, group:0, gmask:0
        17: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
             mse, pos:0, group:0, gmask:0
        18: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
             mse, pos:0, group:0, gmask:0
     Battery: 50%, discharging.

**Comment by pfps** [comment]
So your device has the GESTURE 2 feature, which is implemented in version 1.0.4.   I think that your best bet is to install using pip.   See https://pwr-solaar.github.io/Solaar/installation for more information.

**Comment by pfps** [comment]
Is there anything more that should be done?

**Comment by Pontan666** [comment]
Hi, now I'm trying to find a way to install the 1.0.4 version. As I
said before, newbie to this so I need practice and study. I got great
support from you! Thanks!

Den mån 21 dec. 2020 kl 03:47 skrev Peter F. Patel-Schneider <
notifications@github.com>:

**Comment by pfps** [comment]
This appears to be OK now so I'm closing the issue.
