### ISSUE TITLE
Fix a warning message which occurs since updating to 1.0.4 from 1.0.2

### ISSUE THREAD

**Issue by MR-Diamond** [pwr-Solaar/Solaar#1035]
**Information**
- Solaar version 1.0.4
- Distribution: Manjaro Linux
- Kernel version  `Linux 4.14.209-1-MANJARO x86_64 GNU/Linux`

**Describe the bug**

This is a ticket to explain a fix for a warning message which has started to occurred after the update of solaar to 1.0.4 from 1.0.2; I don't know if maintainers are aware of this, and so I report here instead to submit a PR.

I updated solaar from 1.0.2 to 1.0.4
As I executed it in terminal, now I get the following warning:

```
/usr/lib/python3.8/site-packages/solaar/ui/__init__.py:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Gtk
```

So I edited `/usr/lib/python3.8/site-packages/solaar/ui/__init__.py` by putting `gi.require_version('Gtk', '3.0')` at the line 26 under `import gi` (and removed from line 31).
and in this way, the warning went away.

**Comment by pfps** [comment]
Thanks for the report.  This problem has already been fixed by PR #982
