### ISSUE TITLE
Depends: python-psutil  but it is not installable

### ISSUE THREAD

**Issue by BaronKrause** [pwr-Solaar/Solaar#1036]
Using the latest GIT from the repo (1.0.4+git1261-aa4456e-202012201017~ubuntu20.10.1) on Pop OS 20.10  I noticed it hasn't been loading recently and after uninstalling and trying to reinstall im getting this error:

solaar:
 Depends: python-psutil  but it is not installable

There is no python-psutil in the repos (normal Python is just a transitional package for Python2) but Python3 is installed along with python3-psutil.

**Comment by pfps** [comment]
How are you installing?  This sort of dependency appears to come from  a system package.

**Comment by BaronKrause** [comment]
> How are you installing? This sort of dependency appears to come from a system package.

Using this PPA: http://ppa.launchpad.net/solaar-unifying/ppa/ubuntu/
I don't see it now but I remember it being on the main github page when I added it.

**Comment by pfps** [comment]
That's a problem in the repo, that needs to be fixed by @muzena 
The implementation of HID++ rules added some dependencies to Solaar and they are still being worked out in the repos.  That said, there was a change in the repo this weekend that I think should have fixed this problem but maybe more work needs to b done.
For more information see issue #1004, near the end.

**Comment by muzena** [comment]
@BaronKrause 
Try now.

**Comment by pfps** [comment]
@muzena  It looks as if the builds are working now.  Is this correct?

**Comment by BaronKrause** [comment]
> @BaronKrause
> Try now.

Works!

Though I noticed after reinstall that it no longer auto starts. In the past it due and I thought I remember a Solaar entry in the gnome auto start applications list.

**Comment by pfps** [comment]
It may be that some package set up Solaar to autostart but the one you are using doesn't. You may have to set that up yourself.
