### ISSUE TITLE
Error with started solaar

### ISSUE THREAD

**Issue by Madaspe** [pwr-Solaar/Solaar#1037]
I have error

`solaar
/usr/lib/python2.7/site-packages/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)

(python:14803): Gtk-WARNING **: 16:08:32.637: Theme parsing error: colors.css:71:44: Invalid number for color value

(python:14803): Gtk-WARNING **: 16:08:32.637: Theme parsing error: colors.css:72:44: Invalid number for color value

(python:14803): Gtk-WARNING **: 16:08:32.637: Theme parsing error: colors.css:74:53: Invalid number for color value

(python:14803): Gtk-WARNING **: 16:08:32.637: Theme parsing error: colors.css:75:53: Invalid number for color value

(python:14803): Gtk-WARNING **: 16:08:32.637: Theme parsing error: colors.css:76:56: Invalid number for color value

(python:14803): Gtk-WARNING **: 16:08:32.637: Theme parsing error: colors.css:77:65: Invalid number for color value
solaar: error: GObject.__init__() takes exactly 0 arguments (4 given)
`

OS: openSuse Leap 15.2
I install this version: https://software.opensuse.org/package/solaar (For openSUSE Leap 15.2)

**Comment by pfps** [comment]
That package for Solaar appears to be very, very old.  You need to install a newer version of Solaar.  See https://pwr-solaar.github.io/Solaar/installation for more information.  I suggest installing via `pip` and manual installation of the Solaar udev rule.

I have removed the information about the SUSE package from the Solaar main page to prevent this problem in the future.

**Comment by pfps** [comment]
You could also clone and install from this repository.
