### ISSUE TITLE
Use default Solaar icon for system tray

### ISSUE THREAD

**Issue by janvlug** [pwr-Solaar/Solaar#1042]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.0.4
- Distribution:  Fedora

**Describe the bug**
The current icon for Solaar in the system tray is a battery. This is slightly confusing, and moreover, the regular Solaar icon looks way better. I suggest to use the standard Solaar icon as the icon for the system tray.

See also [this issue](https://github.com/pwr-Solaar/Solaar/issues/918#issuecomment-673839905).

**Additional information**
The [Top Indicator App](https://extensions.gnome.org/extension/3681/top-indicator-app/) GNOME extension has to be installed on Fedora 33 GNOME Wayland to make the icon visible.

**Comment by pfps** [comment]
Solaar is reporting battery information for the Logitech devices.  This is a feature of Solaar.  There is an option for Solaar to use symbolic icons that might be more suitable for you.

One possible enhancement would be to add another value for this option to not use battery icons - `solaar --battery-icons none`.  Would that be useful?  It would not be the default.

**Comment by janvlug** [comment]
@pfps I tested Solaar with the `--battery-icons` options. When Solaar is started, I first see briefly the Solaar icon in the tray, instead of the battery icon. That is actually the icon that I would like to see (preferably even in monochrome, but in colour is fine too). I prefer the Solaar icon because I think that Solaar does more that just showing the battery information.
I would also like the `none` option.

**Comment by pfps** [comment]
PR #1042 adds an option to not use battery icons for the tray icon.
To use this option run `bin/solaar --battery-icons solaar`

To download and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1042, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1042/head:pull_1042
git checkout pull_1042
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1042
git fetch origin pull/1042/head
git reset --hard FETCH_HEAD
```

**Comment by janvlug** [comment]
I tested the PR (note it is pull [#1043](https://github.com/pwr-Solaar/Solaar/pull/1043)). This looks really good now with `./solaar -b solaar`. Thanks!
