### ISSUE TITLE
The german translation does not work on Fedora 33

### ISSUE THREAD

**Issue by MrReSc** [pwr-Solaar/Solaar#1049]
**Information**
- Solaar version: `1.0.4`
- Distribution: `Fedora 33`
- Kernel version: `Linux 5.10.6-200.fc33.x86_64 x86_64 GNU/Linux`

**Describe the bug**
The german translation does not work. All texts are displayed in english.

**To Reproduce**
1. `sudo dnf install solaar`
2. Launching Solaar on a german Fedora 33 with Gnome

**Screenshots**
![grafik](https://user-images.githubusercontent.com/24952268/104798602-861c2800-57c8-11eb-8ecc-29f11f7bc246.png)
![grafik](https://user-images.githubusercontent.com/24952268/104798617-a0560600-57c8-11eb-9cf3-085655bc7bd2.png)

**Additional context**
I have tested it with Ubuntu 20.10 set to German. The translation works there.

**Comment by pfps** [comment]
@robbat2  Can you investigate?

**Comment by rathann** [comment]
Guys, I think this is on me. The Fedora package doesn't ship any translations. I haven't noticed because I'm running with UK locale. I'll fix this soon. Please copy me on all Fedora issues in the future for faster response (or file bugs at https://bugzilla.redhat.com product **Fedora**, component **solaar**).

**Comment by rathann** [comment]
Ok, correction. Debian/Ubuntu package calls [`tools/po-compile.sh`](https://github.com/pwr-Solaar/Solaar/blob/master/tools/po-compile.sh) before `python3 setup.py install`. The Fedora package didn't, so it didn't include the translations. I've just fixed it by doing the same, but ideally, this should be fixed here and have `setup.py` call `tools/po-compile.sh` or equivalent.

**Comment by rathann** [comment]
@MrReSc please check the following Fedora update: https://bodhi.fedoraproject.org/updates/FEDORA-2021-4684724f39 (and provide feedback if it work for you).

**Comment by pfps** [comment]
Works for me.  I downloaded the RPM from koji and installed it directly.

However, the German translation that was used was missing quite a few strings.  There is a very recent update to the German translation.   

I'll try to get 1.0.5 out in the near future.

**Comment by rathann** [comment]
@pfps Thanks for testing! Having a new release would be great, too. I guess this can be closed now.

**Comment by MrReSc** [comment]
@rathann Works for me too.
