### ISSUE TITLE
Package for Alpine Linux

### ISSUE THREAD

**Issue by antonialoytorrens** [pwr-Solaar/Solaar#1054]
Hi,
I want to add proper packaging for Alpine Linux. I'll upload it to Aports repository (in testing, at the moment) with your permission.
Thank you in advance.

P.S.: I can test newer versions because I have an MX Anywhere 2, but unfortunately I lack coding knowledge.

**Comment by pfps** [comment]
Go ahead.

**Comment by pfps** [comment]
Report back when the package is available and working and how it can be used.   If repository is not a standard one for Alpine Linux information about the package can be added to the Solaar documentation.

**Comment by antonialoytorrens** [comment]
Review pending. 
I'll notify you when the package is available or if some problem occurs.

https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/17384

**Comment by antonialoytorrens** [comment]
The package has been merged into testing! Closing this issue.
https://pkgs.alpinelinux.org/packages?name=solaar&branch=edge
