### ISSUE TITLE
Wireless G915 keyboard partially supported

### ISSUE THREAD

**Issue by bwanaaa** [pwr-Solaar/Solaar#1064]
G915 keyboard uses lightspeed receiver
**Information**
solaar 1.01
Ubuntu 20.04 Linux x86_64 GNU/Linux
kernel Linux 5.8.0-41-generic x86_64 GNU/Linux

```
solaar show
solaar: error: Logitech receiver not found

```

**Comment by pfps** [comment]
It is likely that Solaar does not have information on this receiver.   To help fix the problem, please provide output of `lsusb` and `lsusb -v -s b:d` where b and d are the bus and device number for the receiver.

**Comment by bwanaaa** [comment]
lsusb

`Bus 005 Device 002: ID 046d:c541 Logitech, Inc. USB Receiver`

lsusb -v -s 005:002
```

Bus 005 Device 002: ID 046d:c541 Logitech, Inc. USB Receiver
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x046d Logitech, Inc.
  idProduct          0xc541 
  bcdDevice            1.01
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          4 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower               98mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      67
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     123
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      54
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1

```

**Comment by bwanaaa** [comment]
even after
```
sudo add-apt-repository ppa:solaar-unifying/stable
sudo apt-get update

```
and then
`
sudo apt-get install solaar`

I got solaar 1.0.3
and it still does find the receiver.

**Comment by bwanaaa** [comment]
Well I installed solaar manually according to the procedure and now it sees the keyboard. But I cannot change any keybindings/colors or anything

**Comment by pfps** [comment]
This receiver was added to Solaar in August, which means, I think, that you need 1.0.4.  It's a bit surprising that that repository only has 1.0.3.
You should be able to install 1.0.4 using pip.  See the installation page for more information.  You might have to install the Solaar udev rule.  You should be able to use this repository (as long as all the required system packages are loaded).

But you might also be having problems with the python version you are using.   Run `python --version` and `find /usr -name psutil`.   The directory that psutil is under should match the python version.  (On Fedora 33 I see Python 3.9.1 and /usr/lib64/python3.9/site-packages/psutil.)

**Comment by pfps** [comment]
This keyboard might not have features that Solaar supports.  Please provide output of `solaar show`, which will print all the features that the keyboard has.  For features that Solaar supports some information on the feature will likely be printed as well.

**Comment by bwanaaa** [comment]
python3 --version
Python 3.8.5

find /usr -name psutil
/usr/lib/python3/dist-packages/psutil

solaar show
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 171, in run
    raise Exception('Logitech receiver not found')
Exception: Logitech receiver not found

/usr/bin/solaar

gives me solaar 1.0.3

I downloaded the repo and ran bin/solaar from a terminal started in Solaar-master and that gives me 1.0.4 which does see the receiver and the keyboard. but not much I can do-cant reassign keys/colors,etc

**Comment by bwanaaa** [comment]
I tried to install solaar-master with /release.sh 

and got
```

./release.sh: line 46: git: command not found
Error: Failed current branch
```

**Comment by pfps** [comment]
You use pip to install from the clone directory (via `pip install --user .` or something like that).   release.sh is used to create new releases (like 1.0.4).  You shouldn't need to do that.

**Comment by bwanaaa** [comment]
pip install --user .

put solaar into 

/root/.local/bin/solaar

I did 

sudo cp /root/.local/bin/solaar  ~/.local/bin/solaar

and now I can run 

solaar

and get 
![Screenshot from 2021-02-01 19-09-39](https://user-images.githubusercontent.com/4876720/106534067-43916580-64c1-11eb-9c03-6857597ac1bd.png)

clicking 'rules' gives

![Screenshot from 2021-02-01 19-09-52](https://user-images.githubusercontent.com/4876720/106534088-4f7d2780-64c1-11eb-8f99-4c17e2428879.png)

![Screenshot from 2021-02-01 19-10-04](https://user-images.githubusercontent.com/4876720/106534106-5441db80-64c1-11eb-8bd0-a7c71b7291a3.png)

but I wouldnt know how to add my  own. nor change the colors.

**Comment by pfps** [comment]
Changing colors is likely some other feature - so you need to provide output from `bin/solaar show`.

Writing rules is not for the faint of heart.  As I don't have a gaming keyboard I can't even check out whether a rule works.  But a rule like
```
 Rule
  Key G3
  Execute emacs
```
should have the G3 key start emacs.

**Comment by pfps** [comment]
Is there anything else that needs to be done on this issue?

**Comment by bwanaaa** [comment]
nothing more. thank you for your help. I wish my office was as helpful
