### ISSUE TITLE
Switch both keyboard and mouse when pressing keyboard buttons (option)

### ISSUE THREAD

**Issue by dmgeurts** [pwr-Solaar/Solaar#1067]
- Solaar version: 1.0.4
- Distribution: Ubuntu 20.04 LTS
- Kernel version: Linux 5.8.0-38-generic x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable): N/A

**Is your feature request related to a problem? Please describe.**
On Windows when using flow users can switch both mouse and keyboard at the same time. The keyboard buttons are easily accessible, but the mouse needs to be lifted to press the buttons on the bottom. 

**Describe the solution you'd like**
Some debug information is available here about the signals used to switch both devices at the same time: [logi_craft_sdk on Github](https://github.com/Logitech/logi_craft_sdk/issues/28)
It would be great to add the option of also switching the mouse when switching the keyboard. I realised for those like me who use Linux and Windows that this will potentially be a one-sided affair. But useful even then. I do believe this should be an option so people who prefer to continue to switch individual devices can continue doing so.

**Describe alternatives you've considered**
1) Incorporate "flow" device switching for seamless full compatibility with Windows and Mac machines.
2) Continue working on my carpal tunnel syndrome...

**Additional context**
N/A

**Comment by dmgeurts** [comment]
Have just seen another request for a very similar feature request. I guess I should've done a search before posting.

@barolo suggested running some code. Which I've tested on the command line and works, thank you! Now I'm looking at remapping the host selector key on my MX Keys to run this command to switch both keyboard and mouse at the same time.

Is this possible?
![image](https://user-images.githubusercontent.com/2071992/107526351-aa90d780-6baf-11eb-9ea0-37735a47ed3f.png)

Am I doing it the right way or is this not how the rule editor is meant to be used?

**Comment by pfps** [comment]
Implementing "flow" is almost certainly not possible as it would require adding inter-machine communication capabilities to Solaar as well as reverse-engineering the "flow" protocol.  Implementing "double switch" is not going to be easy either, but might be possible.

What has been done (but you'll have to search for it in previous Solaar issues) is to create a "hot corner" feature that responds to mouse movement to a corner of the screen by issuing Solaar commands to switch the mouse and keyboard to a different connection.

**Comment by dmgeurts** [comment]
I was happily surprised to find the CLI option. Would be nice to trigger this from the keyboard though by reassigning the respective host switch key.

**Comment by dmgeurts** [comment]
> Implementing "flow" is almost certainly not possible as it would require adding inter-machine communication capabilities to Solaar as well as reverse-engineering the "flow" protocol. Implementing "double switch" is not going to be easy either, but might be possible.

This was my expectation indeed, and there are other solutions available. It was more tongue in cheek...

**Comment by pfps** [comment]
I think you might be on the right track.  You do need to divert the host switch key so that Solaar will notice that the key has been pressed.  Use the Key/Button Diversion setting for this.  Also, I suggest you use two Execute actions.
Report back on how this all works, please.

**Comment by pfps** [comment]
I tested all this out and it seems to work fine, with one glitch.   If you have devices that are currently connected via BT but also paired with a plugged-in receiver, the config call doesn't work because it tries to control the device via the receiver.
I'm working on a fix for that.

**Comment by pfps** [comment]
My rule is
```
- Key: Host Switch Channel 3
- Execute: [solaar, config, Craft, change-host, '0']
- Execute: [solaar, config, MX, change-host, '0']
```

I'm closing this issue as there is a good workaround.

**Comment by dmgeurts** [comment]
> My rule is
> 
> ```
> - Key: Host Switch Channel 3
> - Execute: [solaar, config, Craft, change-host, '0']
> - Execute: [solaar, config, MX, change-host, '0']
> ```
> 
> I'm closing this issue as there is a good workaround.

That works indeed, I had the whole string as one argument, splitting each 'word' into a separate argument works perfectly. Thank you!

**Comment by nirinarakotobe** [comment]
@dmgeurts , @pfps It's not working for me, can you please help me to correct what's wrong?
![image](https://user-images.githubusercontent.com/70261187/217641206-585fbab3-beac-4920-83ed-00c984870662.png)

**Comment by pfps** [comment]
It looks as if you have several levels of quotes around the 0 and 1 
arguments.  These should not be there.


peter

**Comment by nirinarakotobe** [comment]
@pfps @dmgeurts  sorry to have disturbed you, I thought I had deleted the comment. actually, I was able to solve the problem thanks to your other thread (https://github.com/pwr-Solaar/Solaar/issues/1070)
thank you very much!
