### ISSUE TITLE
Thanks for Solaar!

### ISSUE THREAD

**Issue by msoos** [pwr-Solaar/Solaar#1069]
I just updated my distro and Solaar is so much better now, yay! Is there a way for me to support you all? Maybe a link in the Readme could be nice. I'd be happy to throw 5 EUR into the bowl :)

Cheers,

Mate

**Comment by pfps** [comment]
The best way to support Solaar is to help update it.  :-)

You could also help test out changes to Solaar.  That doesn't require programming.  Instead you have to respond to mentions and follow instructions in the PRs.  You do have to be able to clone the Solaar repository (using git) and be able to run Solaar from the clone directory.

**Comment by msoos** [comment]
Thanks so much! I'll check some PRs later! I can code, I maintain https://github.com/msoos/cryptominisat :)

**Comment by pfps** [comment]
PRs that need testing are marked as Ready for Testing and usually have instructions on what needs to be done.
Cloning and using the cloned version of Solaar is covered in https://pwr-solaar.github.io/Solaar/installation
