### ISSUE TITLE
Take keyboard group into account in rule Key action

### ISSUE THREAD

**Issue by scottcove** [pwr-Solaar/Solaar#1071]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): solaar 1.0.4
- Distribution: Ubuntu 20.04.2 LTS
- Kernel version (ex. `uname -srmo`): Linux 5.8.0-43-generic x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable):
<details>

```
$ solaar show
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : 20B7915A
    Firmware   : 24.11.B0036
    Bootloader : 02.09
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=156

  1: M720 Triathlon Multi-Device Mouse
     Device path  : /dev/hidraw1
     WPID         : 405E
     Codename     : M720 Triathlon
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 53FEE654
     Model ID:      B015405E0000
     Unit ID:       C8108484
        Bootloader: BOT 34.01.B0005
          Firmware: MPM 04.10.B0013
             Other: 
     The power switch is located on the base.
     Supports 36 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 34.01.B0005 000000A96719
            Firmware: Firmware MPM 04.10.B0013 405E00A96719
            Firmware: Other   
            Unit ID: C8108484  Model ID: B015405E0000  Transport IDs: {'btleid': 'B015', 'wpid': '405E'}
         3: DEVICE NAME            {0005}   
            Name: M720 Triathlon Multi-Device Mouse
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: CRYPTO ID              {0021}   
         7: DEVICE FRIENDLY NAME   {0007}   
         8: BATTERY STATUS         {1000}   
            Battery: 50%, discharging, next level 20%.
         9: CHANGE HOST            {1814}   
            Change Host: 2:ace-rimmer
        10: HOSTS INFO             {1815}   
            Host 0 (paired): SCOTT-LAPTOP
            Host 1 (paired): 
            Host 2 (paired): ace-rimmer.littlecoves
        11: REPROG CONTROLS V4     {1B04}   
            Key/Button Actions: {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '91': 91, '93': 93, '208': 208}
            Key/Button Diversion: {'82': 0, '83': 1, '86': 1, '91': 1, '93': 1, '208': 1, '215': 1}
        12: PERSISTENT REMAPPABLE ACTION {1C00}   
        13: POINTER SPEED          {2205}   
            Pointer Speed: 1.0
            Sensitivity (Pointer Speed): 256
        14: VERTICAL SCROLLING     {2100}   
            Roller type: 3G
            Ratchet per turn: 24
            Scroll lines: 0
        15: DFUCONTROL UNSIGNED    {00C1}   
        16: DFUCONTROL SIGNED      {00C2}   
        17: DEVICE RESET           {1802}   internal, hidden
        18: unknown:1803           {1803}   internal, hidden
        19: CONFIG DEVICE PROPS    {1806}   internal, hidden
        20: OOBSTATE               {1805}   internal, hidden
        21: unknown:1813           {1813}   internal, hidden
        22: unknown:1830           {1830}   internal, hidden
        23: unknown:1861           {1861}   internal, hidden
        24: unknown:1890           {1890}   internal, hidden
        25: unknown:1891           {1891}   internal, hidden
        26: unknown:18A1           {18A1}   internal, hidden
        27: unknown:1DF3           {1DF3}   internal, hidden
        28: unknown:1E00           {1E00}   hidden
        29: unknown:1EB0           {1EB0}   internal, hidden
        30: unknown:18B1           {18B1}   internal, hidden
        31: unknown:1850           {1850}   internal, hidden
        32: unknown:1E22           {1E22}   
        33: unknown:1F03           {1F03}   internal, hidden
        34: unknown:18C0           {18C0}   internal, hidden
        35: HIRES WHEEL            {2121}   
            Multiplier: 8
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            High resolution mode
            HID notification
            Scroll Wheel Direction: False
            Scroll Wheel Resolution: True
     Has 9 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, reprogrammable, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, reprogrammable, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: diverted
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: diverted
         5: Left Tilt                 , default: Mouse Scroll Left Button    => Mouse Scroll Left Button  
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: diverted
         6: Right Tilt                , default: Mouse Scroll Right Button   => Mouse Scroll Right Button 
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: diverted
         7: MultiPlatform Gesture Button, default: Multiplatform Gesture Button => Multiplatform Gesture Button
             mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: diverted
         8: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:3, group mask:empty
             reporting: diverted
     Battery: 50%, discharging, next level 20%.

Lightspeed Receiver
  Device path  : /dev/hidraw6
  USB id       : 046d:C53D
  Serial       : 330E2E8C
    Firmware   : 43.01.B0009
    Bootloader : 02.10
    Other      : AA.D2
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

  1: G613 Wireless Mechanical Gaming Keyboard
     Device path  : None
     WPID         : 4065
     Codename     : G613
     Kind         : keyboard
     Protocol     : HID++ 4.2
     Polling rate : 1 ms (1000Hz)
     Serial number: 381EA9BC
     Model ID:      B34F40650000
     Unit ID:       6E4E8357
        Bootloader: BOT 46.00.B0006
          Firmware: MPK 05.02.B0021
             Other: 
     Supports 32 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 46.00.B0006 00006E86A7BD
            Firmware: Firmware MPK 05.02.B0021 40656E86A7BD
            Firmware: Other   
            Unit ID: 6E4E8357  Model ID: B34F40650000  Transport IDs: {'btleid': 'B34F', 'wpid': '4065'}
         3: DEVICE NAME            {0005}   
            Name: G613 Wireless Mechanical Gaming Keyboard
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: DEVICE FRIENDLY NAME   {0007}   
         7: BATTERY STATUS         {1000}   
            Battery: 80%, discharging, next level 50%.
         8: CHANGE HOST            {1814}   
            Change Host: 1:ace-rimmer
         9: HOSTS INFO             {1815}   
            Host 0 (paired): 
            Host 1 (unpaired): 
        10: REPROG CONTROLS V4     {1B04}   
            Key/Button Diversion: {'209': 0, '210': 0}
        11: REPORT HID USAGE       {1BC0}   
        12: ENCRYPTION             {4100}   
        13: KEYBOARD DISABLE BY USAGE {4522}   
        14: KEYBOARD LAYOUT 2      {4540}   
        15: GKEY                   {8010}   
            Divert G Keys: True
        16: REPORT RATE            {8060}   
            Polling Rate (ms): 1
        17: DFUCONTROL SIGNED      {00C2}   
        18: DEVICE RESET           {1802}   internal, hidden
        19: unknown:1803           {1803}   internal, hidden
        20: CONFIG DEVICE PROPS    {1806}   internal, hidden
        21: unknown:1813           {1813}   internal, hidden
        22: OOBSTATE               {1805}   internal, hidden
        23: unknown:1830           {1830}   internal, hidden
        24: unknown:1890           {1890}   internal, hidden
        25: unknown:1891           {1891}   internal, hidden
        26: unknown:18A1           {18A1}   internal, hidden
        27: unknown:1DF3           {1DF3}   internal, hidden
        28: unknown:1E00           {1E00}   hidden
        29: unknown:1EB0           {1EB0}   internal, hidden
        30: unknown:1861           {1861}   internal, hidden
        31: unknown:18B1           {18B1}   internal, hidden
     Has 2 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             divertable, persistently divertable, pos:1, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             divertable, persistently divertable, pos:2, group:0, group mask:empty
             reporting: default
     Battery: 80%, discharging, next level 50%.
```
</details>

First of all, thanks for a wonderful app, that finally allows the use of the macro keys of the M720, and G613!

**Is your feature request related to a problem? Please describe.**
I use a non-standard keyboard layout (Dvorak), and am finding that the UI is interpreting the keystrokes being input fine, but when the rules are being interpreted, they seem to be sending the keycode, rather than the keysym to the operating system, resulting in the key printed on the QWERTY layout being sent, and the incorrect macros being run.

A good example of this is Copy and Paste.  I can set the following rules:
```
---
- Process: termius-app
- Rule:
  - Key: Left Tilt
  - KeyPress: [Control_L, Shift_L, C]
- Rule:
  - Key: Right Tilt
  - KeyPress: [Control_L, Shift_L, V]
...
---
- Rule:
  - Key: Left Tilt
  - KeyPress: [Control_L, C]
- Rule:
  - Key: Right Tilt
  - KeyPress: [Control_L, V]
...
---
```
This works fine if i'm using QWERTY, but if I'm in any other layouts the incorrect key is pushed.  I'm guessing that this is because the keycode is being sent, rather than the keysym.  In the examples above, V appears to be sent as keycode 55, rather than the keysym 0x76.  This results in the incorrect key K (keysym 0x6b) being pushed, as it is mapped to keycode 55.

I have considered working around this by setting the correct physical keys in the rules, but this is further complicated by the fact that in my line of work I am often in customer VMs or in RDP (or team viewer) sessions that I cannot change the keyboard layout for, and adding exceptions to the rules could get very unwieldy very fast.

**Describe the solution you'd like**
Instead of the keycode being sent, resulting in incorrect keypresses being sent, the rules should instead send the layout-agnostic keysym.

**Describe alternatives you've considered**
An alternative here could be to detect the layout currently in use, and adapt to it, though this is complicated by the above-mentioned scenario whereby you are in an RDS session, or VM that the host reports the input method incorrectly because the guest is using a different layout that the host is unaware of.

**Additional context**
If the keymaps are hardcoded into solaar, and you do need listings of the available keysyms, these can be found under the files `/usr/include/X11/keysymdef.h` (global), and `/usr/include/X11/XF86keysym.h` (vendor specific).  The package `x11proto-core-dev` is required for these to be present on an Ubuntu machine.

**Comment by pfps** [comment]
Solaar simulates key presses using the xtest extension to X11, which requires keycodes.

The code that turns characters into keycodes is 
```
displayt.keysym_to_keycode(Xlib.XK.string_to_keysym(s))
```
where displayt is an Xlib display.  This is all Xlib code.
This should turn a character into a keycode for that produces the character in X11.

I'm not sure why you are not getting the character back.

**Comment by scottcove** [comment]
Thanks for clarifying that.  This does seem to be an upstream issue.

The main issue here is that the `keysym_to_keycode()` always returns the first keycode in the index, as per the [documentation](https://python-xlib.github.io/python-xlib_15.html#Display)  Thus, as my primary keyboard is *technically* US QWERTY, it will always return, and push that keycode, even though X somehow remaps that key.

This can be seen as below:
```
>>> print(Xlib.XK.string_to_keysym('v'))
118
>>> print(display.keysym_to_keycode(118))
55
>>> print(display.keysym_to_keycodes(118))
[(55, 0), (60, 2), (55, 4), (55, 8)]
```
As you can see in the example above, the 'v' key is keycode 55 in QWERTY, and Colmak, while it is remapped to keycode 60 (. in QWERTY) for the Dvorak layout.  Thus when the `Xlib.ext.xtest.fake_input(displayt, X.KeyPress, k)` sends keycode 55 as it would on the qwerty layout, it is actually sending the letter 'k', as that is what is mapped to keycode 55 on dvorak.

As for reliably figuring out which of those "indexes" above is in use - that seems to be more difficult.
The following will reliably tell you which layouts I have installed (Colemak is just for testing in this case), but not which one is actually selected in X:

```
$ localectl status
   System Locale: LANG=en_AU.UTF-8
                  LANGUAGE=en_AU:en
       VC Keymap: us
      X11 Layout: us,us,us
     X11 Variant: ,dvorak,colemak
scott@ace-rimmer:~$ cat /etc/default/locale
#  File generated by update-locale
LANG="en_AU.UTF-8"
LANGUAGE="en_AU:en"
scott@ace-rimmer:~$ cat /etc/default/keyboard
XKBLAYOUT=us,us,us
XKBVARIANT=,dvorak,colemak
BACKSPACE=guess
scott@ace-rimmer:~$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us,us,us,us
variant:    ,dvorak,colemak,
```

There does seem to be a `get_keyboard_mapping ( first_keycode, count )` function, but it goes well beyond my (very) limited Python ability, and it may even be a red herring, as it does not appear to be of any use.

This might well be a question for Xlib themselves, unless you can make any sense of this?

**Comment by pfps** [comment]
It appears that your setup uses X indexes (used for shifting keys) to get different keyboard layouts.  In effect, you have the ALT GRID key down all the time, which moves you to index 2 and 3 instead of 1 and 2. Or at least that's what I can figure out.

I can't think of a reliable way to get the effect you want.   Anything I can think of would have problems if, for example, the shift key was down at the time Solaar tried to figure out which index to use.  

My suggestion is to ask on some Xlib channel.  The question would be something like "How to send reliably send a key symbol even when using alternative keyboard layouts".

PS:  How do you select the dvorak layout?

**Comment by scottcove** [comment]
> It appears that your setup uses X indexes (used for shifting keys) to get different keyboard layouts.

Yeah, looking into it, that looks to be exactly what is happening here.

Output of `xset -q` seems to confirm this, too:

With the "primary" keyboard layout selected:
```
$ xset -q
Keyboard Control:
  auto repeat:  on    key click percent:  0    LED mask:  00000002
  XKB indicators:
    00: Caps Lock:   off    01: Num Lock:    on     02: Scroll Lock: off
    03: Compose:     off    04: Kana:        off    05: Sleep:       off
    06: Suspend:     off    07: Mute:        off    08: Misc:        off
    09: Mail:        off    10: Charging:    off    11: Shift Lock:  off
    12: Group 2:     off    13: Mouse Keys:  off
  ```
With any other layout selected:
```
$ xset -q
Keyboard Control:
  auto repeat:  on    key click percent:  0    LED mask:  00001002
  XKB indicators:
    00: Caps Lock:   off    01: Num Lock:    on     02: Scroll Lock: off
    03: Compose:     off    04: Kana:        off    05: Sleep:       off
    06: Suspend:     off    07: Mute:        off    08: Misc:        off
    09: Mail:        off    10: Charging:    off    11: Shift Lock:  off
    12: Group 2:     on     13: Mouse Keys:  off
```
As you can see, the LED indicator and "Group 2" options both change, but both of these are identical whether in the second, third, or any other consecutive layout, so is not reliable either.

> for example, the shift key was down at the time Solaar tried to figure out which index to use.
The Shift key does work in the combinations when using `fake_input`, but I can certainly see the issue here, too.  While the Shift key is down, it is using index 2, and thus, index 4 would need to be used.

> How do you select the dvorak layout?
I personally use the Hotkeys in Gnome `Super+Space`, which rotates through them.  Which gives me an idea in which I think you may have had, too.  That is for any key combinations involving letters, breifly switch to the "primary" layout, carry out the hotkey and switch back.  This though, has the same issue.  If I'm in qwerty for some reason or another, it should not go back to dvorak.



I'll reach out to the folks over at the Xlib project, and see what they might have (or if they might be able to support keysyms too), and see what they might be able to come up with.  Thanks for that. :+1:

**Comment by pfps** [comment]
A way to send keysyms is to use an unused keycode and switch it to the keysym.   This seems hacky, though.  I'm going to give it a try.  It'll need good testing.

**Comment by pfps** [comment]
If someone has a good way of doing this in Python, please respond here.

**Comment by pfps** [comment]
@scottcove I've been looking at this issue a bit for other reasons.  Can you provide the output of `xmodmap -pk`?  The reason that I ask is that the way that I can easily switch to Dvorak keyboard doesn't end up with the problem you are experiencing, but I sometimes experience similar problems with accented characters.

**Comment by pfps** [comment]
@scotcove What happens when you use pynput to simulate keyboard input?  (You can install pynput with pip.)

**Comment by pfps** [comment]
It would be useful to have an example of some code that does this correctly.   As far as I can tell most code that simulates input, e.g., pynput, depends on assumptions that are not always correct.

**Comment by pfps** [comment]
@scottcove So close, but yet so far.  The approaches I have seen to determine the keyboard group don't work in Python because some library calls are missing.

**Comment by pfps** [comment]
PR #1438 has a new way of determining which keycode to use.  It is based on XKB libraries.  

@scottcove Please give it a try.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1438, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1438/head:pull_1438
git checkout pull_1438
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1438
git fetch origin pull/1438/head
git reset --hard FETCH_HEAD
```
