### ISSUE TITLE
gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

### ISSUE THREAD

**Issue by mattdm** [pwr-Solaar/Solaar#1072]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository):
- Distribution:
- Kernel version (ex. `uname -srmo`): `KERNEL VERSION HERE`
- Output of `solaar show`:
```
- Solaar version: 1.0.4 
- Distribution: Fedora (Fedora package `solaar-1.0.4-3.fc33.noarch`)
- Kernel version (ex. `uname -srmo`): `Linux 5.10.13-200.fc33.x86_64 x86_64 GNU/Linux`
- Output of `solaar show`: `AttributeError: 'gi.repository.Gtk' object has no attribute 'Container'` and a traceback

```

**Describe the bug**

It's a warning: 

````
(solaar:330070): Gtk-CRITICAL **: 12:12:28.088: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(solaar:330070): Gtk-CRITICAL **: 12:12:28.088: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(solaar:330070): Gtk-CRITICAL **: 12:12:29.376: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
````

**To Reproduce**
1. run `solaar` from the command line in Fedora Workstation 33
2. Observe "Gtk-CRITICAL" errors on standard error

**Screenshots**

![image](https://user-images.githubusercontent.com/123367/107883660-2fd10080-6ebe-11eb-9e38-ec94ab740a12.png)

**Additional context**

From my point of view this is largely cosmetic, but maybe there actually is some underlying problem to fix? Not sure. Reporting just in case.

**Comment by pfps** [comment]
I tried to find out why GTK is complaining and failed.  There doesn't seem to be any problem from the message so I'm just letting it be.
