### ISSUE TITLE
Information about releases

### ISSUE THREAD

**Issue by pfps** [pwr-Solaar/Solaar#1075]
This issue is a place to put information about releases, both upcoming and ongoing.

**Comment by pfps** [comment]
Release 1.0.5 should be coming out soon.   This is a good time to update translations and check to see if your distribution needs changes, particularly as the new rule mechanism in Solaar adds new dependencies.

**Comment by pfps** [comment]
I just made release 1.0.5rc2

**Comment by pfps** [comment]
@rathann @muzena I'll try to use this issue for discussion of releases.   If you follow it you will be able to easily see about upcoming releases.

**Comment by rathann** [comment]
@pfps Thanks. I added solaar to [release-monitoring.org](https://release-monitoring.org/project/11338/) so I get bugzilla tickets created whenever there's a new release on github anyway.

**Comment by pfps** [comment]
Release 1.0.5 just done.

**Comment by pfps** [comment]
Release 1.0.6 should be coming soon, starting with a PR version, so if you are interested in translations now is a good time to translate the new strings.

**Comment by pfps** [comment]
Release 1.0.6rc1 was just sent out.

**Comment by pfps** [comment]
Release 1.0.6 just done

**Comment by sidevesh** [comment]
@pfps Looks loke 1.0.6 doesn't show up on github as the latest release (which is still 1.0.5) and neither does the stable ppa provide 1.0.6, is this intended ?

**Comment by pfps** [comment]
I'm seeing tag 1.0.6 in github.  I'm not creating branches for the releases as there is no attempt to backport to old releases.  As far as I know packagers have to do something for new releases to show up.  The only exception I know of is the Ubuntu git ppa which is regenerated each day that there is a change to the master branch.

**Comment by pfps** [comment]
@muzena Can you update the stable ppa to version 1.0.6?

**Comment by muzena** [comment]
@sidevesh 
Try now.
https://code.launchpad.net/~solaar-unifying/+recipe/solaar-unifying-stable

**Comment by pfps** [comment]
Release 1.0.7 should be coming soon.  
There is a small but far-reaching change for devices connected via USB and bluetooth.   If you have such a device, please update to the version of Solaar here and see if there are problems.  If so, please comment on PR #1234

**Comment by pfps** [comment]
Release 1.0.7rc2 just done.

**Comment by pfps** [comment]
Release 1.0.7rc3 just done, incorporating a few small fixes.

**Comment by pfps** [comment]
Release 1.0.7 just done

**Comment by pfps** [comment]
Release 1.1.0 just out.

**Comment by pfps** [comment]
Release 1.1.1rc1 just out.  This release was done mostly to check that the release process works with Markdown changelog.  Expect 1.1.1rc2 in a day or so.

**Comment by pfps** [comment]
Release 1.1.1rc2 just out

**Comment by pfps** [comment]
Release 1.1.1 just out

**Comment by pfps** [comment]
@rathann PR #1783 identifies HID++ devices by examining report descriptors.  It uses a pip-distributed package hid-tools for this.  How much trouble is it to have this package available in the rpm distribution?
An alternative would be to copy part of the package into Solaar.

**Comment by rathann** [comment]
@pfps Fedora has only the [hidapi](https://pypi.org/project/hidapi/) python module packaged, so if that's not an option, I'd need to package hid-tools. hidapi seems to be actively maintained while hid-tools has only one release in 2019 listed on PyPI. Maybe it'd be better to use an actively maintained module instead?

**Comment by pfps** [comment]
I don't think that hidapi has the interface to process report descriptors.   But I've found a smallish bit of code that does the trick.  As it does not appear to be packaged, I've just copied the code.

**Comment by rathann** [comment]
Ok, on second look, it seems hid-tools is pretty active upstream (https://gitlab.freedesktop.org/libevdev/hid-tools), just not posting new releases on PyPI. 0.3 was released a month ago (https://gitlab.freedesktop.org/libevdev/hid-tools/-/releases/0.3). They're warning against using their module, though: https://gitlab.freedesktop.org/libevdev/hid-tools#hidtools-python-module . The code that you copied (https://github.com/usb-tools/python-hid-parser) doesn't seem to be actively maintained, either (last commit almost a year ago).

**Comment by rathann** [comment]
And I've just found you've asked about external usage already: https://gitlab.freedesktop.org/libevdev/hid-tools/-/issues/40 .

**Comment by rathann** [comment]
FWIW, I posted hidtools for review and inclusion in Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=2133456 .

**Comment by pfps** [comment]
OK.  I'm still undecided as to which route to go.  hidtools looks acceptable, but I will be using an internal interface and I wonder whether it will be in other distributions.  The code that I copied does only the task that I need but. as you say, it hasn't been updated for a while.

**Comment by pfps** [comment]
I've decided to use a submodule, which doesn't require that the other project be packaged.

**Comment by pfps** [comment]
@rathann @muzena  I just merged in PR #1783, which uses a submodule and a symbolic link to the code of the submodule.   I've created 1.1.6rc4 so this is a good time to see what, if anything, new has to be done to get out a release and whether I need to change anything to support distribution.

**Comment by muzena** [comment]
@pfps 
Yes, see [build.log](https://launchpadlibrarian.net/629462073/buildlog_ubuntu-kinetic-amd64.solaar_1.1.6rc4+git1866-c6b8c0b~ubuntu22.10.1_BUILDING.txt.gz)
This mean that further PPA building will not be possible.
Solution for this is to make something like this in [Devolutionx packaging](https://github.com/diasurgical/devilutionX/blob/master/tools/make_src_dist.py).
It makes dir with all or neded dependencies, then I can add it in manually in build recepies with [nest-part  option](https://code.launchpad.net/~devilutionx/+recipe/devilutionx-git)

**Comment by muzena** [comment]
@muzena 
Problem is that **Launchpad PPA build system** doesn't allow cloning/downloads outside **Launchpad PPA build system**.
So eg. wget, curl, git clone do not work in build process.

**Comment by pfps** [comment]
@muzena So how is the Solaar code downloaded to start the build process?

**Comment by muzena** [comment]
@pfps 
When build starts through **build recepies** first start to make [tar.xz archive](https://launchpadlibrarian.net/630259527/buildlog.txt.gz) from [launchpad mirror of git repository](https://git.launchpad.net/~trebelnik-stefina/cinnamon-test/+git/devilutionx-packaging/tree/), it removes all dirs/files with **.** (.gitignore, .github, .gitattributes, .editorconfig, .circleci, .bettercodehub.yml), make patching if neded and nesting neded [dependencies](https://git.launchpad.net/~trebelnik-stefina/cinnamon-test/+git/devilutionx-packaging/tree/dist?h=debian_build_arm64_aarch64) and [debian packaging](https://git.launchpad.net/~trebelnik-stefina/cinnamon-test/+git/devilutionx-packaging/tree/Packaging/debian?h=build_arm64_aarch64_new).
Then uploads **tar.xz** archive to [PPA](https://code.launchpad.net/~devilutionx/+archive/ubuntu/dev/+packages) and [building proces is started](https://launchpadlibrarian.net/630196141/buildlog_ubuntu-kinetic-amd64.devilutionx_1.4.0+git6137-b3be4ab65-202210240047~ubuntu22.10.1_BUILDING.txt.gz).
But problem is when build process starts, this build system does not have Internet access, so inside build process you can't use wget, curl or similar programs.
git command not working because there is no Internet access and git dirs with dot **.** are removed.
It is like you are trying to start Solaar build in your PC with disconnected Ethernet Or Wi -Fi (without Internet access).

**Comment by pfps** [comment]
@muzena But how is the launchpad mirror of the git repository created?  Can't that initial step be modified to include the submodule?

**Comment by muzena** [comment]
@pfps 

> launchpad mirror of the git repository

And Launchpad build system, this is two different things.
**git repository** normally works, like in github, 
**build system** has disabled network access, there is somewhere in Launchpad Bug/Feature request about this problem.
Only solution for this is **to make dir with all or neded dependencies like in Devolution**X or to make debian packages for this submodule/dependendies and install it on system.

In this Bug report they said, that they have disabled network access for security reasons.

**Comment by pfps** [comment]
So is the solution to make hid-parser a dependenncy of Solaar?  This requires that distributions package hid-parser.

**Comment by dvzrv** [comment]
We add new packages because they are required by updates to existing packages all the time.
Adding hid-parser as a git submodule is not the right solution.

**Comment by pfps** [comment]
So is the right solution to make hid-parser a dependency of Solaar and depend on it being packaged?

**Comment by rathann** [comment]
As mentioned in https://github.com/pwr-Solaar/Solaar/issues/1075#issuecomment-1273153330 , I'd rather you used an actively maintained library. I'll make sure it's available in Fedora from my side.

**Comment by dvzrv** [comment]
> So is the right solution to make hid-parser a dependency of Solaar and depend on it being packaged?

Absolutely. That is how all downstream packaging is supposed to work at least :)

> As mentioned in https://github.com/pwr-Solaar/Solaar/issues/1075#issuecomment-1273153330 , I'd rather you used an actively maintained library. I'll make sure it's available in Fedora from my side.

Yeah, hid-parser looks a bit unmaintained atm. but I don't think hid-tools is much better (especially in regards to stability guarantees and not publishing to pypi.org, which is an issue for any non-distribution packaging purpose).

**Comment by pfps** [comment]
I looked around for a commonly-available Python package that parsed HID report descriptors, but there doesn't appear to be one.  There are several packages on github that can do the job, however.  The current one used in Solaar has the advantage of having the best interface as far as Solaar is concerned.  The package only needs to be able to detect report descriptors for HID++ reporting, which it does.

One thing that can be done to Solaar is to make Solaar work with or without the hid parser package.  This is already done for desktop notifications.  

Another way forward is to include the hid-parser code in Solaar instead of using a submodule.

**Comment by dvzrv** [comment]
It's fine to use hid-parser as a dependency. Dealing with its upstream so that there will be further releases can be done separately from all of this.

**Comment by pfps** [comment]
PR #1808 makes hid-parser an optional dependency and documents it in setup.py with
```
     extras_require = {
        'report-descriptor': [ 'hid-parser' ],
        'desktop-notifications': [ 'Notify (>= 0.7)' ],
    },
```

If hid-parser is not available, Solaar will not pick up as many unknown devices.

Does this sound like a reasonable solution?   Distributions can package hid-parser, but do not have to.

**Comment by dvzrv** [comment]
Yep, to me this sounds like a great solution. Thank you!

**Comment by dvzrv** [comment]
A new release with the submodule removed and the PR merged would be very helpful! :)

**Comment by pfps** [comment]
I'll produce a release that is a candidate release so that the approach can be tested, probably in a day or so.

**Comment by pfps** [comment]
@muzena Why is the Ubuntu build failing?

**Comment by muzena** [comment]
@pfps 
Fixed.

**Comment by pfps** [comment]
@dvzrv @rathann @muzena 
I just created release 1.1.7rc1.  This release should work fine without hid-parser, https://pypi.org/project/hid-parser/, but will use hid-parser if available to discover some devices that it would not discover otherwise.  hid-parser is only needed to parse report-descriptors well enough to determine whether the device supports HID++, and it appears to work fine for this purpose.

**Comment by pfps** [comment]
@rathann Is there a good way of sending a message to anyone interested in new releases?

**Comment by rathann** [comment]
> @rathann Is there a good way of sending a message to anyone interested in new releases?

Do you mean "when a new release is made" or "before a new release is made"? If the former, then just tagging a new release will trigger notifications to everyone subscribed to https://release-monitoring.org/project/11338/ . If the latter, then... I don't know.

**Comment by pfps** [comment]
The latter - to warn packagers of upcoming changes.
