### ISSUE TITLE
pypi.org not found?

### ISSUE THREAD

**Issue by K2AAE** [pwr-Solaar/Solaar#1079]
Installed the git, installed the python and gtk modules, got issues with missing py parts
 sudo pip3 install python3-gi python3-gobject
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting python3-gi
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/python3-gi/

This is on Raspberry Buster ...
Good work on this, my new K860 and MX Master 3 would love to have Flow on Linux....

**Comment by pfps** [comment]
System packages are not python (pip) packages.   If you need to install the system packages use dnf or apt, as appropriate.   Perhaps the easiest way to find out whether you need to install system packages is to install solaar with pip and then run it.   Solaar should complain if system packages are missing.

**Comment by pfps** [comment]
I'm closing this issue, as the above comment should be the right solution.  If it is not, just reopen.
