### ISSUE TITLE
Ansible Playbook

### ISSUE THREAD

**Issue by thdesy** [pwr-Solaar/Solaar#1088]
Hi,

I wrote an Ansible playbook to install Solaar on my Fedora 33
https://github.com/thdesy/ansible-playbooks/blob/main/Solaar.pb/Logitech_solaar.yaml

while it is currently somewhat bound to RedHat/Fedora ( due to `dnf`),  it could maybe be useful for others?

Cheers and many thanks for Solaar ,
  Thomas

**Comment by pfps** [comment]
Thanks.   I'm not sure whether there should be a pointer to this file from Solaar documentation, particularly as it is specific to distributions that use dnf.

**Comment by pfps** [comment]
I'm going to close this issue as I don't see a place for this functionality to exist in this repository as it downloads the repository itself.

People will still be able to find it with Google (probably) so if someone wants to install Solaar externally they could use this.
