### ISSUE TITLE
Logitech Cordless Desktop LX 710 Laser keyboard + mouse: receiver not recognized

### ISSUE THREAD

**Issue by MagicFab** [pwr-Solaar/Solaar#109]
I got a "Cordless Desktop LX 710 Laser" mouse + keyboard combo from Logitech: http://www.logitech.com/en-us/support/147

I am not sure if this could/should be managed via Solaar, but thought this report would at least document it.

The keyboard and mouse are properly recognized and work fine in GNU/Linux (Debian 7), but the receiver isn't recognized (nor keyboard / mouse) in Solaar 0.9.2.

This uses an older "Mini receiver" (not the unifying receiver) which is identified as USB device  046d:c517 (see below for details). There is a hardware power button on the bottom of the mouse.

Output of `solaar-cli show -v`:

```
$ solaar-cli show
solaar-cli: error: Logitech receiver not found
```

Output of `lsusb`:

```
 # lsusb -v -d  046d:c517


Bus 003 Device 003: ID 046d:c517 Logitech, Inc. LX710 Cordless Desktop Laser
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x046d Logitech, Inc.
  idProduct          0xc517 LX710 Cordless Desktop Laser
  bcdDevice           38.10
  iManufacturer           1 Logitech
  iProduct                2 USB Receiver
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           59
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower               98mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      59
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              10
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     177
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              10
Device Status:     0x0000
  (Bus Powered)
```

**Comment by jdorenbush** [comment]
This is old, but I'm hoping someone can shed some light on this issue. I'm experiencing the same issue with my LX710 mouse/keyboard. Currently running Ubuntu 16.04.

**Comment by jrbenito** [comment]
@jdorenbush ,

Latest master branch has entries for C517 nano receiver. Can you please try run solaar from latest commit and report if solaar recognize the receiver?

thanks

**Comment by Lekensteyn** [comment]
It always have been there (since 2013), not sure if LX 710 is specfically supported though

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of solaar -V and solaar show and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by MagicFab** [comment]
I don't have this hardware anymore.

**Comment by pfps** [comment]
OK, closing.
