### ISSUE TITLE
Add MX Vertical to Supported Devices

### ISSUE THREAD

**Issue by alan-barzilay** [pwr-Solaar/Solaar#1090]
Hello, first of all thank you for this amazing project!

I've stumbled on the [Supported Devices](https://pwr-solaar.github.io/Solaar/devices) page and noticed that the MX Vertical is not listed as a supported device. I'm currently using a MX Vertical mouse and it seems to work correctly with Solaar.

Is there some sort of procedure or test suite to determine if a device is working correctly with Solaar in order to add it to the list of supported devices? Please let me know if there is anything I can do to help with this or with expanding support for the MX Vertical.

**Comment by alan-barzilay** [comment]
I did some digging after re-reading the Supported Devices page and it seems there is already and entry for the MX Vertical on [lib/logitech-receiver/descriptors.py](https://github.com/pwr-Solaar/Solaar/blob/69df28c15595363589c81fb0028bb140c9102057/lib/logitech_receiver/descriptors.py#L532). Is it actually already supported and the supported devices page only outdated?

**Comment by pfps** [comment]
This mouse is indeed supported.  The supported devices page is a bit historical.  Many new devices need little or no new code or data in Solaar.  The best way to see if a device is supported is to install and run Solaar.   Supported devices should show up in the Solaar main window.

If you feel inclined you could update the supported devices pages, via a PR, but right at the beginning of the page there is a note that it only has a partial list of supported devices.
