### ISSUE TITLE
Dynamic Scroll Rate

### ISSUE THREAD

**Issue by thx1111** [pwr-Solaar/Solaar#1091]
On Logitech mice that support high resolution scrolling, the pressure required to activate the middle mouse button is much higher than the pressure required to activate the left and right buttons.  This seems to be a fundamental design fault, and difficult to physically modify.  Or perhaps, on mice having a "tilt wheel", which provides additional button functions, with left and right "tilt" of the scroll wheel, someone shortsightedly thought that a "stiff" middle button would prevent accidental "tilt", instead of middle button, presses.

Whatever the source of this unfortunate scroll wheel design, when operating in high resolution mode, it is difficult to activate the middle button without also rotating the scroll wheel some small amount.  When performing cut and paste, this can cause the window content to "jump around" vertically when pasting content.  Even worse, if the paste is performed at the cursor's instantaneous position, then it can be very difficult to paste content to the desired location, as the cursor moves while trying to press the scroll wheel.

In contrast, the cursor position is much more stable when pressing the scroll wheel when the scroll wheel is in low resolution mode.  And so, there arises the idea of a dynamic scroll rate for the mouse wheel.

A timer on scroll wheel events, in the tens of milliseconds range, to measure the rate of scroll events, could distinguish rapid continuous scrolling, to select the high scroll rate, and very slow scrolling, indicating an attempt by the user to position the cursor precisely, or to not move the cursor at all, which would select the low scroll rate.  Essentially, this would act like a differentiator followed by a threshold detector, adjusting the scroll rate - two or more scroll events during the timer period: high scroll rate, zero or one scroll events in the timer period: slow scroll rate.

This could be implemented with a counter, incremented by scroll wheel events, which is polled and then zeroed at a fixed rate, determined by the timer.  Additionally, a flag could hold the immediately previous polled state, to compare with the just polled state, to determine a change of state.  A change of state from slow to fast would set high scroll rate, and from fast to slow, would set low scroll rate.

This is basically the same idea as cursor acceleration, except for the scroll wheel.  Sadly, I can find no similar mechanism available for the scroll wheel.

BTW, for entertainment value, read here [https://bugs.freedesktop.org/show_bug.cgi?id=29905](url):

> Albert Zeyer 2010-08-31 06:15:03 UTC
Description
It would be nice to have acceleration for the mouse wheel.
...
 Peter Hutterer 2016-09-23 12:20:38 UTC
Comment 13
i guess the only update is a WONTFIX, given that this has been languishing for 6 years now. input stuff like this is moving to libinput anyway, and I don't think I'll implement mouse wheel acceleration there either.

You can read additional comments, as Peter continues to rebuff all pleadings.

Of course, the forcing of Policy by Mechanism, whether that mechanism be libinput, or user tools, or the lack thereof, is a fundamental violation of the "Unix Way".

**Comment by pfps** [comment]
Solaar isn't a general input driver.   Normal input events are not processed by Solaar.   Solaar does process some diverted input events, but Solaar is just a regular user program.   So Solaar is very likely to add considerable lag - which isn't going to make for a good scrolling experience.
I view this as out of scope for Solaar.

**Comment by thx1111** [comment]
> Solaar isn't a general input driver.

Uhm - you seem to have missed the point, that libinput fails to be a proper input driver, and a work-around is being sought.

As I understand, from reading at #1061, solaar *already* must perform a scroll rate set *every* time the mouse comes online, which seems to imply that solaar must also constantly monitor whether the mouse is, or is not, currently online.  Or is that not the case?  If so, then your statement that "Normal input events are not processed by Solaar" is nonsense.

Do you have actual numbers, showing the solaar response time to input events?

The solaar response time does not have to actually be in the tens of milliseconds range to be very useful for *changing* the scroll rate.  The rate of change of the scroll rate is a completely different thing from the rate of mouse scroll events.  Scroll rate changes could occur over a period of perhaps a second and still be very practical.   All that is necessary is to choose the relationship between the polling period and the scroll event threshold number appropriately.

You closed this thread with no discussion, allowing no time for anyone else to read it or comment, and seemingly with very little thought, insight, or appreciation of the issue.

**Comment by pfps** [comment]
Feel free to implement this feature yourself in your cloned copy of Solaar.   You can then submit a PR that might be included in Solaar.
