### ISSUE TITLE
How to change scrolling speed of Logitech Pebble?

### ISSUE THREAD

**Issue by Mennaruuk** [pwr-Solaar/Solaar#1103]
Is there a way to change scrolling speed of Logitech Pebble, either via GUI or CLI?

Also, when I enable the HID++ option, scrolling is disabled. Is this a bug?

**Comment by pfps** [comment]
When an HID++ setting is turned on the feature (here scrolling) uses HID++ messages, which are generally ignored by Linux input drivers.   So this is a feature, not a bug.

Many Logitech mice can change scrolling speed (generally either very slow or normal).   For example, my MX Master 3 has his setting, called Scroll Wheel Resolution.   Be warned, however, that you probably don't want to fiddle with this setting, as Linux input drivers may modify it and you can end up with Solaar and the driver competing to change the setting.  I am not aware of any Solaar setting that can be used to vary scrolling speed in any other way.

In general, Solaar lets you fiddle with low-level settings of devices and this fiddling can cause abnormal behaviour.

**Comment by Mennaruuk** [comment]
I definitely understand. I'll stay wary of fiddling with these settings, then. Hope that at some point in the future, there'll be a native setting to change scrolling speed, and it can resolve this problem. Thank you for your assistance.

**Comment by pfps** [comment]
Solaar generally only does what the hardware does.   If the hardware doesn't allow modifying the scrolling speed in small increments then Solaar probably isn't the right tool to adjust scrolling speeds.
