### ISSUE TITLE
 MX Ergo Multi-Device Trackball  stopped functioning - no path defined

### ISSUE THREAD

**Issue by mheieis** [pwr-Solaar/Solaar#1134]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository):
- Distribution: solaar 1.0.5
- Kernel version (ex. `uname -srmo`): Linux 5.11.11-200.fc33.x86_64 x86_64 GNU/Linux 
- Output of `solaar show`:

<details>

```
Unifying Receiver
Device path  : /dev/hidraw0
USB id       : 046d:C52B
Serial       : DF4C9B6C
Firmware   : 12.11.B0032
Bootloader : 04.16
Other      : AA.AA
Has 2 paired device(s) out of a maximum of 6.
Notifications: wireless, software present (0x000900)
Device activity counters: 1=179, 2=6

1: MX Ergo Multi-Device Trackball 
Device path  : None
WPID         : 406F
Codename     : MX Ergo
Kind         : trackball
Protocol     : HID++ 4.5
Polling rate : 8 ms (125Hz)
Serial number: FF3FC38E
Model ID:      B01D406F0000
Unit ID:       44364368
Bootloader: BOT 49.00.B0001
Firmware: MPM 06.02.B0018
Other: 
The power switch is located on the base.
Supports 36 HID++ 2.0 features:
0: ROOT                   {0000}   
1: FEATURE SET            {0001}   
2: DEVICE FW VERSION      {0003}   
Firmware: Bootloader BOT 49.00.B0001 0000022AA87F01
Firmware: Firmware MPM 06.02.B0018 406F022AA87F01
Firmware: Other   
Unit ID: 44364368  Model ID: B01D406F0000  Transport IDs: {'btleid': 'B01D', 'wpid': '406F'}
3: DEVICE NAME            {0005}   
Name: MX Ergo Multi-Device Trackball 
Kind: trackball
4: WIRELESS DEVICE STATUS {1D4B}   
5: DEVICE FRIENDLY NAME   {0007}   
6: RESET                  {0020}   
7: CRYPTO ID              {0021}   
8: BATTERY STATUS         {1000}   
Battery: 90%, discharging, next level 50%.
9: LED CONTROL            {1300}   
10: REPROG CONTROLS V4     {1B04}   
Key/Button Actions: {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '237': 237, '91': 91, '93': 93}
Key/Button Diversion: {'82': 0, '83': 0, '86': 0, '237': 0, '91': 0, '93': 0, '215': 0}
11: PERSISTENT REMAPPABLE ACTION {1C00}   
12: POINTER AXIS ORIENTATION {2006}   
13: POINTER SPEED          {2205}   
Pointer Speed: 1.0
Sensitivity (Pointer Speed): 256
14: VERTICAL SCROLLING     {2100}   
Roller type: standard
Ratchet per turn: 18
Scroll lines: 0
15: DFUCONTROL SIGNED      {00C2}   
16: DEVICE RESET           {1802}   internal, hidden
17: unknown:1803           {1803}   internal, hidden
18: CONFIG DEVICE PROPS    {1806}   internal, hidden
19: OOBSTATE               {1805}   internal, hidden
20: unknown:1813           {1813}   internal, hidden
21: CHANGE HOST            {1814}   
Change Host: 2:copernicus
22: HOSTS INFO             {1815}   
Host 0 (paired): 
Host 1 (paired): 
Host 2 (unpaired): 
23: unknown:1830           {1830}   internal, hidden
24: unknown:1861           {1861}   internal, hidden
25: unknown:1890           {1890}   internal, hidden
26: unknown:1891           {1891}   internal, hidden
27: unknown:18A1           {18A1}   internal, hidden
28: unknown:1DF3           {1DF3}   internal, hidden
29: unknown:1E00           {1E00}   hidden
30: unknown:1EB0           {1EB0}   internal, hidden
31: unknown:18B1           {18B1}   internal, hidden
32: unknown:1850           {1850}   internal, hidden
33: unknown:1F03           {1F03}   internal, hidden
34: unknown:18C0           {18C0}   internal, hidden
35: LOWRES WHEEL           {2130}   
Wheel Reports: HID
Scroll Wheel HID++ Scrolling: False
Has 9 reprogrammable keys:
0: Left Button               , default: Left Click                  => Left Click                
mse, reprogrammable, pos:0, group:1, group mask:g1
reporting: default
1: Right Button              , default: Right Click                 => Right Click               
mse, reprogrammable, pos:0, group:1, group mask:g1
reporting: default
2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
reporting: default
3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
reporting: default
4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
reporting: default
5: DPI Change                , default: DPI Change                  => DPI Change                
mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
reporting: default
6: Left Tilt                 , default: Mouse Scroll Left Button    => Mouse Scroll Left Button  
mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
reporting: default
7: Right Tilt                , default: Mouse Scroll Right Button   => Mouse Scroll Right Button 
mse, reprogrammable, divertable, persistently divertable, raw XY, pos:0, group:2, group mask:g1,g2
reporting: default
8: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
divertable, virtual, raw XY, force raw XY, pos:0, group:3, group mask:empty
reporting: default
Battery: 90%, discharging, next level 50%.

2: Wireless Mobile Mouse MX Anywhere 2S
Device path  : /dev/hidraw1
WPID         : 406A
Codename     : MX Anywhere 2S
Kind         : mouse
Protocol     : HID++ 4.5
Polling rate : 8 ms (125Hz)
Serial number: 0104EC80
Model ID:      B01A406A0000
Unit ID:       0FB8312B
Bootloader: BOT 57.00.B0003
Firmware: MPM 13.00.B0003
Firmware: MPM 13.00.B0003
Other: 
The power switch is located on the base.
Supports 28 HID++ 2.0 features:
0: ROOT                   {0000}   
1: FEATURE SET            {0001}   
2: DEVICE FW VERSION      {0003}   
Firmware: Bootloader BOT 57.00.B0003 406AD22DCF4D01
Firmware: Firmware MPM 13.00.B0003 B01AD22DCF4D01
Firmware: Firmware MPM 13.00.B0003 406AD22DCF4D01
Firmware: Other   
Unit ID: 0FB8312B  Model ID: B01A406A0000  Transport IDs: {'btleid': 'B01A', 'wpid': '406A'}
3: DEVICE NAME            {0005}   
Name: Wireless Mobile Mouse MX Anywhere 2S
Kind: mouse
4: WIRELESS DEVICE STATUS {1D4B}   
5: RESET                  {0020}   
6: BATTERY STATUS         {1000}   
Battery: 50%, discharging, next level 20%.
7: CONFIG DEVICE PROPS    {1806}   internal, hidden
8: CHANGE HOST            {1814}   
Change Host: 3:copernicus
9: REPROG CONTROLS V4     {1B04}   
Key/Button Actions: {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '91': 91, '93': 93}
Key/Button Diversion: {'82': 0, '83': 0, '86': 0, '91': 0, '93': 0, '215': 0}
10: ADJUSTABLE DPI         {2201}   
Sensitivity (DPI): 950
11: VERTICAL SCROLLING     {2100}   
Roller type: 3G
Ratchet per turn: 24
Scroll lines: 0
12: HIRES WHEEL            {2121}   
Multiplier: 8
Has invert: Normal wheel motion
Has ratchet switch: Normal wheel mode
High resolution mode
HID notification
Scroll Wheel Direction: False
Scroll Wheel Resolution: True
13: DFUCONTROL UNSIGNED    {00C1}   
14: DFUCONTROL SIGNED      {00C2}   
15: unknown:1813           {1813}   internal, hidden
16: unknown:1830           {1830}   internal, hidden
17: unknown:1890           {1890}   internal, hidden
18: unknown:1891           {1891}   internal, hidden
19: unknown:18A1           {18A1}   internal, hidden
20: unknown:18C0           {18C0}   internal, hidden
21: unknown:1DF3           {1DF3}   internal, hidden
22: unknown:1E00           {1E00}   hidden
23: unknown:1EB0           {1EB0}   internal, hidden
24: unknown:1803           {1803}   internal, hidden
25: unknown:1861           {1861}   internal, hidden
26: unknown:9001           {9001}   internal, hidden
27: OOBSTATE               {1805}   internal, hidden
Has 8 reprogrammable keys:
0: Left Button               , default: Left Click                  => Left Click                
mse, pos:0, group:1, group mask:g1
reporting: default
1: Right Button              , default: Right Click                 => Right Click
mse, pos:0, group:1, group mask:g1
reporting: default
2: Middle Button             , default: Gesture Button Navigation   => Gesture Button Navigation
mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2,g4
reporting: default
3: Back Button               , default: Mouse Back Button           => Mouse Back Button
mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3,g4
reporting: default
4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button
mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3,g4
reporting: default
5: Left Tilt                 , default: Mouse Scroll Left Button    => Mouse Scroll Left Button
mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3,g4
reporting: default
6: Right Tilt                , default: Mouse Scroll Right Button   => Mouse Scroll Right Button
mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3,g4
reporting: default
7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button
divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
reporting: default
Battery: 50%, discharging, next level 20%.
```
</details>

Suddenly, my track ball mice no longer function, which up until very recently worked perfectly (days ago, maybe longer). I have two trackballs and tested them both on 2 separate machines. They work fine on a windows machine and when using bluetooth. The Wireless Mobile Mouse MX Anywhere 2S that I have works flawlessly on both target (fedora 32 & 33) machines.
**Describe the bug**
Using the Unifying Receiver, the systems recognize the mice and know that they have been powered on, Other than that, they are unresponsive. 

Looking at the solaar status, i note that the path for the track balls is empty, where as the MX has it specified to /dev/hidraw1

Question is why all of a sudden, when reconfiguring the track balls there is no path specification, in addition to not functioning. 

Thanks.

**To Reproduce**
delete and add new device

**Screenshots**

**Additional context**
Was there an upgrade of third party packages that may have affected the functioning? 
Can I manually add the path to the configuration to test whether that is the problem?

**Comment by pfps** [comment]
This is not likely a Solaar bug.  Instead it looks as if the trackball is not being set up correctly.  I'm not actually sure what part of Linux is responsible for setting up or what exactly went wrong.

The problem might be in setting up the /dev/hidraw* nodes.   If you do `ls -l /dev/hidraw*` you should see three relevant entries in it - one for the receiver and one for each device - all with a + after the permission bits, signifying that there are special access controls for them.  You can find out more about each of these nodes by running `udevadm info -n /dev/hidrawN`  for each node number N.   The output for the trackball should show the Wireless PID for the trackball (in the P and E values). The output for the receiver should show the USB id for the receiver (in the P and E lines) and not show WPID value there.  If none show the trackball WPID then the problem is not in Solaar.

Another thing to check is to see whether the device shows up in xinput.  If not, then the problem is not in Solaar.

**Comment by mheieis** [comment]
Hi,
    Thanks for the quick response. 
    
    It seems that the ERGOs do not show up in any /dev/hidraw or
      xinput. The only thing that I can see different is hidraw
      permissions.
    Where to next? rules.d config issue?
    
    Thanks.
    
    On 2021-04-08 10 h 31, Peter F.
      Patel-Schneider wrote:
    
    
      
      This is not likely a Solaar bug. Instead it looks as if the
        trackball is not being set up correctly. I'm not actually sure
        what part of Linux is responsible for setting up or what exactly
        went wrong.
      The problem might be in setting up the /dev/hidraw* nodes. If
        you do ls -l /dev/hidraw* you should see three
        relevant entries in it - one for the receiver and one for each
        device - all with a + after the permission bits, signifying that
        there are special access controls for them.
    
    $ ls -l /dev/hidraw*
    crw-rw----+ 1 root root 242, 0 2021-04-07 18:23:14 /dev/hidraw0
    crw-rw----+ 1 root root 242, 1 2021-04-07 18:23:14 /dev/hidraw1
    crw-------. 1 root root 242, 2 2021-04-07 18:23:14 /dev/hidraw2
    crw-------. 1 root root 242, 3 2021-04-08 10:25:52 /dev/hidraw3
    crw-------. 1 root root 242, 4 2021-04-07 18:23:14 /dev/hidraw4
    So is this a permissions problem. Should hidraw[2-4] also have
      rw---*? 
    
    
    
    
      You can find out more about each of these nodes by running udevadm
          info -n /dev/hidrawN for each node number N. The output
        for the trackball should show the Wireless PID for the trackball
        (in the P and E values). The output for the receiver should show
        the USB id for the receiver (in the P and E lines) and not show
        WPID value there. If none show the trackball WPID then the
        problem is not in Solaar.
    
    ERGO PID 406F S# FF3FC3BE
    MX PID 4 406A S# 0104E80
    I see that the ERGO PID does not come up.
    
    $ udevadm info -n /dev/hidraw?
    P:
/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.2/0003:046D:C52B.0003/hidraw/hidraw0
    N: hidraw0
    L: 0
    E:
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.2/0003:046D:C52B.0003/hidraw/hidraw0
    E: DEVNAME=/dev/hidraw0
    E: MAJOR=242
    E: MINOR=0
    E: SUBSYSTEM=hidraw
    E: USEC_INITIALIZED=5375072
    E: ID_PATH=pci-0000:00:14.0-usb-0:3:1.2
    E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_3_1_2
    E: ID_FOR_SEAT=hidraw-pci-0000_00_14_0-usb-0_3_1_2
    E: TAGS=:seat:uaccess:
    
    P:
/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.2/0003:046D:C52B.0003/0003:046D:406A.0004/hidraw/hidraw1
    N: hidraw1
    L: 0
    E:
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.2/0003:046D:C52B.0003/0003:046D:406A.0004/hidraw/hidraw1
    E: DEVNAME=/dev/hidraw1
    E: MAJOR=242
    E: MINOR=1
    E: SUBSYSTEM=hidraw
    E: USEC_INITIALIZED=5384473
    E: ID_PATH=pci-0000:00:14.0-usb-0:3:1.2
    E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_3_1_2
    E: ID_FOR_SEAT=hidraw-pci-0000_00_14_0-usb-0_3_1_2
    E: TAGS=:seat:uaccess:
    
    P:
/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/0003:413C:2003.0005/hidraw/hidraw2
    N: hidraw2
    L: 0
    E:
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/0003:413C:2003.0005/hidraw/hidraw2
    E: DEVNAME=/dev/hidraw2
    E: MAJOR=242
    E: MINOR=2
    E: SUBSYSTEM=hidraw
    
    P:
/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.0/0003:0644:8038.000A/hidraw/hidraw3
    N: hidraw3
    L: 0
    E:
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-8/1-8:1.0/0003:0644:8038.000A/hidraw/hidraw3
    E: DEVNAME=/dev/hidraw3
    E: MAJOR=242
    E: MINOR=3
    E: SUBSYSTEM=hidraw
    
    P:
/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4.4/1-4.4:1.0/0003:0461:4D81.0007/hidraw/hidraw4
    N: hidraw4
    L: 0
    E:
DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4.4/1-4.4:1.0/0003:0461:4D81.0007/hidraw/hidraw4
    E: DEVNAME=/dev/hidraw4
    E: MAJOR=242
    E: MINOR=4
    E: SUBSYSTEM=hidraw
    
      Another thing to check is to see whether the device shows up in
        xinput. If not, then the problem is not in Solaar.
    
    $ xinput
    ⎡ Virtual core pointer                          id=2    [master
    pointer  (3)]
    ⎜   ↳ Virtual core XTEST pointer                id=4    [slave 
    pointer  (2)]
    ⎜   ↳ Logitech MX Anywhere 2S                   id=9    [slave 
    pointer  (2)]
    ⎜   ↳ USB Optical Mouse                         id=10   [slave 
    pointer  (2)]
    ⎣ Virtual core keyboard                         id=3    [master
    keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard
    (3)]
    ↳ Power Button                              id=6    [slave  keyboard
    (3)]
    ↳ Power Button                              id=7    [slave  keyboard
    (3)]
    ↳ Sleep Button                              id=8    [slave  keyboard
    (3)]
    ↳ Dell Dell USB Keyboard                    id=11   [slave  keyboard
    (3)]
    ↳ Eee PC WMI hotkeys                        id=12   [slave  keyboard
    (3)]
    ↳ Logitech MX Anywhere 2S                   id=13   [slave  keyboard
    (3)]
    
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/pwr-Solaar/Solaar/issues/1134#issuecomment-816007182",
"url": "https://github.com/pwr-Solaar/Solaar/issues/1134#issuecomment-816007182",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by pfps** [comment]
The problem is completely outside of Solaar.  

Solaar has a udev rule that sets up special access permissions for hidraw nodes that correspond to Logitech devices.  Other nodes do not need these special permissions.

For some reason your trackball is not being recognized.  That's either a problem with the drivers you have installed or with the udev rules you have installed.  I'm not sure who to complain to to get this problem solved but probably your first move would be to file a bug report against your Linux distribution.
