### ISSUE TITLE
change host with thumb button

### ISSUE THREAD

**Issue by Cherkah** [pwr-Solaar/Solaar#1149]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): solaar 1.0.5
- Distribution: 5.11.10-1-MANJARO

**Is your feature request related to a problem? Please describe.**
if the actual solaar's version accept to create rules to change host via thumb button.
I want just be able to switch the mouse without the keyboard between my pc
i tried already different kind of rules without success

**Describe alternatives you've considered**
before to try using LOGID to set up my MX master 3

**Comment by pfps** [comment]
I use the host switch keys on my Craft for this purpose.  First the key has to be diverted.  Then you have to add a rule that triggers on the diverted key and action that executes solaar config MX change-host N where N is the host you want to change to.

To make this work for the thumb wheel you first have to set Thumb Wheel HID++ Scrolling so that the thumb wheel is diverted.  Then add a rule with test thumb_wheel_up or thumb_wheel_down and the desired action.  A good way to see whether a notification is being sent to the rule system is to execute notify-send with an appropriate message.  

If you are still having problems you will need to provide the output of `solaar show`.

Note that this depends on Solaar rules, which requires X11.

**Comment by Cherkah** [comment]
thanks pfps for your answer.

but i'm trying to use the "thumb button" no the "thumb wheel" which is actually used to scroll horizontally.
I'm already using the "the host switch keys" to alternate easily the combo mouse/keyboard between my laptops.

so does a trick exist so as to use the thumb button to only switch my mouse to my differents pc?

**Comment by pfps** [comment]
In any case the solution would be similar.  First divert the button then write a rule.  There are three buttons that you could use - back, forward, and gesture.   Use the Key/Button Diversion setting to divert the key.  Create a Solaar rule with a key test for the key and an execute action that switches just your mouse.

**Comment by Cherkah** [comment]
ok i tried without success.
that is what i got following your explanations:

```
Rule
Test         Back_Button
Execute   /home/sagitarius/GiTest/Solaar/bin/solaar  config  MX Master 3  config   1
```
solaar show ouput: 
```
1: MX Master 3 Wireless Mouse
Device path  : /dev/hidraw3
USB id       : 046d:B023
Codename     : MX Master 3
Kind         : mouse
Protocol     : HID++ 4.5
Serial number: ?
Model ID:      B02340820000
Unit ID:       836D4B84
Bootloader: BOT 95.01.B0015
Firmware: MPM 19.01.B0015
Other: 
Supports 31 HID++ 2.0 features:
0: ROOT                   {0000}   
1: FEATURE SET            {0001}   
2: DEVICE FW VERSION      {0003}   
Firmware: Bootloader BOT 95.01.B0015 00006A9CA89D
Firmware: Firmware MPM 19.01.B0015 B0236A9CA89D
Firmware: Other   
Unit ID: 836D4B84  Model ID: B02340820000  Transport IDs: {'btleid': 'B023', 'wpid': '4082'}
3: DEVICE NAME            {0005}   
Name: Wireless Mouse MX Master 3
Kind: mouse
4: WIRELESS DEVICE STATUS {1D4B}   
5: RESET                  {0020}   
6: CRYPTO ID              {0021}   
7: DEVICE FRIENDLY NAME   {0007}   
8: BATTERY STATUS         {1000}   
Battery: 100%, discharging, next level 50%.
9: REPROG CONTROLS V4     {1B04}   
Key/Button Actions: {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '195': 195, '196': 196}
Key/Button Diversion: {'82': 0, '83': 1, '86': 0, '195': 0, '196': 0, '215': 0}
10: CHANGE HOST            {1814}   
Change Host: 2:legiontux
11: unknown:2250           {2250}   
12: ADJUSTABLE DPI         {2201}   
Sensitivity (DPI): 1000
13: SMART SHIFT            {2110}   
Scroll Wheel Rachet: 10
14: HIRES WHEEL            {2121}   
Multiplier: 15
Has invert: Normal wheel motion
Has ratchet switch: Normal wheel mode
High resolution mode
HID notification
Scroll Wheel Direction: False
Scroll Wheel Resolution: True
15: THUMB WHEEL            {2150}   
Thumb Wheel HID++ Scrolling: False
Thumb Wheel Direction: False
16: unknown:2251           {2251}   
17: DFUCONTROL SIGNED      {00C2}   
18: DEVICE RESET           {1802}   internal, hidden
19: unknown:1803           {1803}   internal, hidden
20: CONFIG DEVICE PROPS    {1806}   internal, hidden
21: unknown:1813           {1813}   internal, hidden
22: OOBSTATE               {1805}   internal, hidden
23: unknown:1830           {1830}   internal, hidden
24: unknown:18A1           {18A1}   internal, hidden
25: unknown:1E00           {1E00}   hidden
26: unknown:1EB0           {1EB0}   internal, hidden
27: unknown:1861           {1861}   internal, hidden
28: unknown:9300           {9300}   internal, hidden
29: unknown:9001           {9001}   internal, hidden
30: unknown:9205           {9205}   internal, hidden
Has 8 reprogrammable keys:
0: Left Button               , default: Left Click                  => Left Click                
mse, analytics key events, pos:0, group:1, group mask:g1
reporting: default
1: Right Button              , default: Right Click                 => Right Click               
mse, analytics key events, pos:0, group:1, group mask:g1
reporting: default
2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
reporting: default
3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
reporting: diverted
4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
reporting: default
5: App Switch Gesture        , default: Gesture Button Navigation   => Gesture Button Navigation 
mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
reporting: default
6: Smart Shift               , default: Smart Shift                 => Smart Shift               
mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
reporting: default
7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
reporting: default
Battery: 100%, discharging, next level 50%.
....
```

**Comment by Cherkah** [comment]
i used the "back button" because i didn't see the "thumb button" in the Key/button Diversion field.
in the drop list from key test, i didn't see back button so, i extrapolate the Back_Button key on the the others

**Comment by pfps** [comment]
It looks as if the second-last argument for your execute command is wrong.  It should be change-host.

I set up something similar, including a little testing action.

![Screenshot_2021-04-17_10-09-07](https://user-images.githubusercontent.com/6618235/115116117-f6704c00-9f65-11eb-89a8-317d3098715a.png)

![Screenshot_2021-04-17_10-14-10](https://user-images.githubusercontent.com/6618235/115116120-fc662d00-9f65-11eb-86e0-6d9e5cb06604.png)

**Comment by Cherkah** [comment]
once again thx pfps
your images had helped me (i hade created a key test & not a simple key)

you should let this post as an how-to, numerous guy are looking for this feature with their logitech combo

**Comment by pfps** [comment]
I added the example to the Solaar documentation.
