### ISSUE TITLE
Win10 command to switch simultaneously a mouse and a keyboard

### ISSUE THREAD

**Issue by dnlw07** [pwr-Solaar/Solaar#1154]
Hello,
since the solaar is not supported on windows and WSL2 I am struggling to create a script or a command to switch simultaneously a mouse and a keyboard to my second computer.
I followed your conversation and I have noticed that you guys were able to successfully implement a solution to switch mouse and keyboard to different computer. 
Therefore I would like if any of you guys would be able to help me write a simple script on windows which would allow me to perform similar action?

To connect to receiver I am trying to use a tool called `hidapitester`.
I am able to successfully connect to the Logitech Receiver and send the output, however the command seems to not work.

The command I am trying to send:

```
hidapitester --vidpid 046D:C52B --open --length 7 --send-output 0x10,0x03,0x09,0x1c,0x01,0x00,0x00
```

The output I receive:

```
Opening device, vid/pid: 0x046D/0xC52B
Writing output report of 7-bytes...wrote -1 bytes:
 10 03 41 04 71 8A 40
Closing device
```

I also wrote a python script, but with similar result:

```
import hid
import time


# try opening a device, then perform write and read
try:
    # print("\nOpening the device:")

    h = hid.device()
    h.open(0x046D, 0xC52B) # VendorID/ProductID

    print("Manufacturer: %s" % h.get_manufacturer_string())
    print("Product: %s" % h.get_product_string())
    # print("Serial No: %s" % h.get_serial_number_string())

    # enable non-blocking mode
    h.set_nonblocking(1)

    # write some data to the device
    print("\nWrite the data")

    code = [10, 3, 41, 4, 71, 61, 40]

    h.write(code)

    # wait
    time.sleep(0.05)

    # read back the answer
    print("\nRead the data:")
    while True:
        d = h.read(64)
        # d = h.read(20)
        if d:
            print(d)
        else:
            break

    print("Closing the device")
    h.close()

except IOError as ex:
    print(ex)
```

**Comment by pfps** [comment]
It looks as if your python code has the wrong numbers - you need hex, not decimal.
It looks as if hidapitester is providing the input from the receiver, which is neither the command you sent nor the response from your mouse.  Instead it is a disconnect notification from the receiver, probably saying that the device is no longer connected.

Note that some Logitech devices will reconnect if there is other machine to connect to.


I have my MX Master 3 connected via Bluetooth, which requires long HID++ commands.
If your mouse is connected via a receiver you may be able to use a short command.

The command that Solaar uses to switch to the third host is

11000A1802000000000000000000000000000000

11 long command
00 first device (all bluetooth devices have this number)
0A Feature index 0xA (look at solaar show to find out for your mouse and connection)
1  Command 1 (set current host)
8  Command identifier (can be anything, maybe except 0)
02 Third host (0-origin, Solaar adds one to this number when showing to users)
000000000000000000000000000000  Filler

**Comment by dnlw07** [comment]
thank you for the answer @pfps.
I cannot place hex values in my python script because I receive an error:
```
'str' object cannot be interpreted as an integer
```
so that I believe I need to keep it decimal values 🤔 

The command value you have provided is specific only for MX Master 3 connected via bluetooth, right?

**Comment by pfps** [comment]
I don't have the resources to debug your python program.


From your original description it appears that your use of hidapitester is correct.  The response indicates that the mouse switched to a different host.  As stated above, note that some mice will switch back to the original connection if they are unable to connect to the new host.

A way to find out the command to switch to a host is to use the CLI of Solaar as in,
```
solaar -dd config MX change-host 3
```
The last line of output from this program will be the HIPP2.0 command that Solaar sends to switch to host 3 for the device whose name contains MX.   For me the last few lines are:
```
Setting change-host of MX Master 3 Wireless Mouse to 3
14:59:51,902    DEBUG [MainThread] logitech_receiver.settings: change-host: settings write NamedInt(2, '3') to <Device(1,4082,MX Master 3 Wireless Mouse,198E3EB8)>
14:59:51,902    DEBUG [MainThread] logitech_receiver.settings: change-host: settings prepare write(3) => b'\x02'
14:59:51,902    DEBUG [MainThread] logitech_receiver.base: (16) <= w[11 01 0A1E 02000000000000000000000000000000]
```
indicating a command (in hex) of 
```
11 01 0A 1E 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

As stated above, the second byte of this command depends on how the device is connected.

**Comment by altvnv** [comment]
@pfps big thanks to you.

Can I ask you to send a command (in hex) for the MX Keys change-host feature?

**Comment by pfps** [comment]
The easiest way to find this out is given in my previous comment - run `solaar config` to get most of the command and then modify the device number as needed.   The command is different for different devices and different ways of connecting and different hosts to connect to.  See my first comment on what the different parts of the command are for.
