### ISSUE TITLE
K520 battery status not reported when udev rule is missing

### ISSUE THREAD

**Issue by Odysseos** [pwr-Solaar/Solaar#1157]
**Information**
- Solaar version (`solaar --version` and `git describe --tags`): solaar 1.05
- Distribution: Ubuntu 20.04
- Kernel version (ex. `uname -srmo`): Linux 5.4.0-73-generic x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable):

<details>

```
Nano Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:C525
  Serial       : 0D3C0772
    Firmware   : 02.00.B0020
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: wireless (0x000100)

  1: MX Air
     Device path  : None
     WPID         : 100E
     Codename     : MX Air
     Kind         : mouse
     Protocol     : HID++ 1.0
     Serial number: 0D3C0772
     The power switch is located on the (неизвестно).
     Battery status unavailable.

Unifying Receiver
  Device path  : /dev/hidraw2
  USB id       : 046d:C52B
  Serial       : 4E8697E3
    Firmware   : 24.10.B0036
    Bootloader : 00.06
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 2=37

  2: Wireless Keyboard K520
     Device path  : /dev/hidraw3
     WPID         : 2011
     Codename     : K520
     Kind         : keyboard
     Protocol     : HID++ 1.0
     Polling rate : 20 ms (50Hz)
     Serial number: A08F4044
     The power switch is located on the top case.
     Battery status unavailable.
```
</details>

**Is your feature request related to a problem? Please describe.**
I can not see battery status of my Logitech Wireless Keyboard K520 in solaar.

**Describe the solution you'd like**
I want to see battery status of my Logitech Wireless Keyboard K520 in solaar here:

![изображение](https://user-images.githubusercontent.com/4698546/115442013-352e2c80-a21a-11eb-8552-5bec3b1ac667.png)

**Describe alternatives you've considered**
-

**Comment by pfps** [comment]
The warning icon next to the Swap Fx function setting indicates that there are other problems.   
My K520 is working fine under 1.0.6rc1 so I suspect that there is something wrong overall, not just the battery problem.

Please attach output of `solaar -dd` until the K520 is shown on the main window.

**Comment by pfps** [comment]
I suspect that this is also a missing udev file.
