### ISSUE TITLE
Hidpp errors in logs

### ISSUE THREAD

**Issue by Talisker69** [pwr-Solaar/Solaar#1161]
Hi Guys

Just to clarify, this is not a bug for Solaar. 
I have some hidpp errors on my logs (dmesg) from my unify dongle.
I'm using a wireless mouse Logitech M560 on a Linux Mint 20.1 Ulyssa (Latest Version) with a Kernel version 5.4 (Linux 5.4.0-72-generic x86_64 GNU/Linux). My mouse works pretty well except two buttons on the side.
My question is : Do you think, that i need to install solaar to remove these errors ? or they will stay anyway ?
Thanks in advance for your help.

<details>

```
dmesg |grep logitech
[    7.692736] logitech-djreceiver 0003:046D:C52B.0006: hiddev0,hidraw3: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:00:14.0-4.3/input2
[    7.910715] logitech-hidpp-device 0003:046D:402D.0007: hidraw4: USB HID v1.11 Keyboard [Logitech M560] on usb-0000:00:14.0-4.3/input2:1
[   35.196552] logitech-hidpp-device 0003:046D:402D.0007: error in parameter
[   35.198547] logitech-hidpp-device 0003:046D:402D.0007: error in parameter
[   35.202655] logitech-hidpp-device 0003:046D:402D.0007: error in parameter
[   35.218670] logitech-hidpp-device 0003:046D:402D.0007: error in parameter
[   35.226685] logitech-hidpp-device 0003:046D:402D.0007: HID++ 2.0 device connected.
[   35.234649] logitech-hidpp-device 0003:046D:402D.0007: error in parameter
[   35.250649] logitech-hidpp-device 0003:046D:402D.0007: error in parameter
[   35.266637] logitech-hidpp-device 0003:046D:402D.0007: error in parameter
[   35.280625] logitech-hidpp-device 0003:046D:402D.0007: error in parameter
[   35.296477] logitech-hidpp-device 0003:046D:402D.0007: error in parameter
[   35.312472] logitech-hidpp-device 0003:046D:402D.0007: error in parameter
[   35.328526] logitech-hidpp-device 0003:046D:402D.0007: error in parameter
[   35.344483] logitech-hidpp-device 0003:046D:402D.0007: error in parameter
[   35.358560] logitech-hidpp-device 0003:046D:402D.0007: error in parameter
[   35.374496] logitech-hidpp-device 0003:046D:402D.0007: error in parameter
[   35.390499] logitech-hidpp-device 0003:046D:402D.0007: error in parameter
```
</details>
I reproduce these errors from two different computer with this dongle.

**Comment by pfps** [comment]
Solaar is not a device driver and should not change this behaviour at all.

The two side buttons should be button 8 and button 9.   These buttons do nothing for many Linux programs.  Firefox (and maybe other web browsers) use them as next and back buttons.

The error messages are very unspecific so it is unknown what is causing them.  They may go away if you upgrade to a newer kernel, but that may not be an option for you.

**Comment by Talisker69** [comment]
Thanks you for your answer
