### ISSUE TITLE
Indicator for caps lock, num lock etc

### ISSUE THREAD

**Issue by sidevesh** [pwr-Solaar/Solaar#1168]
**Information**
Many logitech keyboards don't have indicator lights for Caps lock, scroll lock, num lock etc,
logitech Options shows a menubar icon if any of these are enabled to fill the gap,
would be good if Solaar implements something similar.

We can change the icon of the indicator or something like that for this purpose,
or a notification would be better maybe given indicators have been deprecated by many DEs.

**Comment by pfps** [comment]
This is not specific to Logitech devices.  A separate application that shows this status would be preferable to implementing this feature in Solaar.
