### ISSUE TITLE
Mouse does not work even though the device shows up in `solaar show`

### ISSUE THREAD

**Issue by minhduc0711** [pwr-Solaar/Solaar#1169]
**Information**

- Solaar version: solaar 1.0.6
- Distribution: Arch Linux
- Kernel version (ex. `uname -srmo`): `Linux 5.11.16-arch1-1 x86_64 GNU/Linux`
- Output of `solaar show`:

<details>

```
Nano Receiver
  Device path  : /dev/hidraw2
  USB id       : 046d:C52F
  Serial       : 9F6B4AB8
    Firmware   : 30.00.B0009
  Has 1 paired device(s) out of a maximum of 1.
  Has 39 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)

  1: Wireless Mouse B330/M330/M331
     Device path  : /dev/hidraw6
     WPID         : 4057
     Codename     : B330/M330/M3
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 9F6B4AB8
     Model ID:      405700000000
     Unit ID:       9F6B4AB8
          Firmware: RQM 55.06.B0025
     The power switch is located on the base.
     Supports 22 HID++ 2.0 features:
         0: ROOT                   {0000}
         1: FEATURE SET            {0001}
         2: DEVICE FW VERSION      {0003}
            Firmware: Firmware RQM 55.06.B0025 4057
            Unit ID: 9F6B4AB8  Model ID: 405700000000  Transport IDs: {'wpid': '4057'}
         3: DEVICE NAME            {0005}
            Name: Wireless Mouse B330/M330/M331
            Kind: mouse
         4: RESET                  {0020}
         5: BATTERY STATUS         {1000}
            Battery: 70%, discharging, next level 5%.
         6: unknown:1810           {1810}   internal, hidden
         7: unknown:1830           {1830}   internal, hidden
         8: DEVICE RESET           {1802}   internal, hidden
         9: unknown:1862           {1862}   internal, hidden
        10: unknown:1890           {1890}   internal, hidden
        11: unknown:18A0           {18A0}   internal, hidden
        12: unknown:18B1           {18B1}   internal, hidden
        13: REPROG CONTROLS V4     {1B04}
            Key/Button Actions (saved): {'80': 80, '81': 81, '82': 82}
            Key/Button Actions        : {'80': 80, '81': 81, '82': 82}
        14: WIRELESS DEVICE STATUS {1D4B}
        15: REMAINING PAIRING      {1DF0}   hidden
            Remaining Pairings: 138
        16: unknown:1DF3           {1DF3}   internal, hidden
        17: unknown:1E00           {1E00}   hidden
        18: unknown:1E22           {1E22}   internal, hidden
        19: unknown:1EB0           {1EB0}   internal, hidden
        20: LOWRES WHEEL           {2130}
            Wheel Reports: HID
            Scroll Wheel HID++ Scrolling (saved): False
            Scroll Wheel HID++ Scrolling        : False
        21: POINTER SPEED          {2205}
            Pointer Speed: 1.0
            Sensitivity (Pointer Speed) (saved): 256
            Sensitivity (Pointer Speed)        : 256
     Has 3 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click
             mse, divertable, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click
             mse, divertable, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
     Battery: 70%, discharging, next level 5%.
```
</details>

**Describe the bug**
Although my mouse seems to be paired successfully, it does not function at all.
I can not unpair the device either:
```
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/solaar/cli/__init__.py", line 207, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/lib/python3.9/site-packages/solaar/cli/unpair.py", line 43, in run
    raise e
  File "/usr/lib/python3.9/site-packages/solaar/cli/unpair.py", line 40, in run
    dev.receiver._unpair_device(number, True)  # force an unpair
  File "/usr/lib/python3.9/site-packages/logitech_receiver/receiver.py", line 247, in _unpair_device
    raise Exception('failed to unpair device %s: %s' % (dev.name, key))
Exception: failed to unpair device B330/M330/M3: 1
```

**Comment by pfps** [comment]
From https://pwr-solaar.github.io/Solaar/usage

> When a device is selected you can unpair the device if your receiver supports unpairing. To unpair the device, just click on the “Unpair” button and confirm in the window that pops up.

From https://pwr-solaar.github.io/Solaar/capabilities

> Even something as fundamental as pairing works differently for different receivers. For Unifying receivers, pairing adds a new paired device, but only if there is an open slot on the receiver. So these receivers need to be able to unpair devices that they have been paired with or else they will not have any open slots for pairing. Some other receivers, like the Nano receiver with USB ID 046d:c534, can only pair with particular kinds of devices and pairing a new device replaces whatever device of that kind was previously paired to the receiver. These receivers cannot unpair. Further, some receivers can pair an unlimited number of times but others can only pair a limited number of times.

The Solaar GUI has code that heuristically tries to determine whether a receiver can unpair.  The Solaar CLI just tries to unpair and if that fails Solaar produces an error.  So it appears that your receiver, like most or all Nano receivers, can't unpair.  From the output of `Solaar show` it also appears that your receiver has a limited number of pairings remaining.

If you cannot try to unpair with the Solaar GUI (i.e., the `Unpair` button is greyed out) then Solaar is acting correctly for your receiver.   If the `Unpair` button is not greyed out, then a small change needs to be made to Solaar to correctly handle your receiver.  Please respond as to which of these is the case.

**Comment by pfps** [comment]
Also, Solaar should have nothing to do with whether your mouse works.  If your mouse does not work when Solaar is not running, it is very unlikely that Solaar can fix the problem.

So please respond whether your mouse works when Solaar is not running.

**Comment by minhduc0711** [comment]
>  If your mouse does not work when Solaar is not running, it is very unlikely that Solaar can fix the problem.

@pfps You are right, I suppose my mouse is broken. Thanks for the answer though!

**Comment by pfps** [comment]
Your mouse isn't completely broken, of course.   You might be able to figure out whether your mouse is correctly communicating with your receiver.   Run `solaar -dd` and look a the output.  When you move your mouse there should be a lot of output.  If so, your mouse is communicating with your receiver.  If not, your mouse is likely not communicating with your receiver either because your mouse is broken (likely the movement sensor is broken) or your  mouse battery is low (although Solaar reports a decent level for your battery).

**Comment by minhduc0711** [comment]
`solaar -dd` produces no output when moving the mouse, but the thing is that my mouse works perfectly fine on Windows. So I'm a bit clueless about what's happening on Linux.

**Comment by pfps** [comment]
If your mouse doesn't work at all on Linux then there is some driver issue.  

You could ask in an Arch LInux Q/A forum (but I don't use Arch Linux so I don't know where to ask).   @FFY00 might be able to provide some information.
