### ISSUE TITLE
Gesture button

### ISSUE THREAD

**Issue by instagendleg** [pwr-Solaar/Solaar#1176]
**Is your feature request related to a problem? Please describe.**

It would really be nice to have a kind of gesture button like the official Logitech software has.

**Describe the solution you'd like**

Option to press a user-defined button on the mouse then execute various actions depending on mouse movements (left, right, up, down).

**Describe alternatives you've considered**

Assign an action to the button.

**Comment by pfps** [comment]
Mouse gestures are in 1.0.6.

See issue #1108

Documentation is in https://pwr-solaar.github.io/Solaar/capabilities
