### ISSUE TITLE
Anywhere 2s, wheel tilt to control volume

### ISSUE THREAD

**Issue by psyhonut** [pwr-Solaar/Solaar#1180]
Hi!
I use solaar version 1.0.6 and I want to ask if I can somehow to change mouse wheel tilti action from horizontal scrolling to volume level changing?
That's only options that I have:
![Screenshot from 2021-06-01 22-49-30](https://user-images.githubusercontent.com/1383457/120382484-5eb79900-c32c-11eb-9bb5-d1ff34f0ce0a.jpg)

**Comment by pfps** [comment]
You can divert the Left Tilt and then write a rule to execute an action.

**Comment by psyhonut** [comment]
And how to do this?
I make this and nothin happened:
![image](https://user-images.githubusercontent.com/1383457/121256493-4b20ab00-c8b5-11eb-8269-0a7b493d169f.png)
![image](https://user-images.githubusercontent.com/1383457/121256540-583d9a00-c8b5-11eb-86f6-ed73663b8a8a.png)

**Comment by psyhonut** [comment]
Ok, I tried this and I have similar debug messages in terminal:
`00:32:03,311    DEBUG [ReceiverListener:hidraw4] logitech_receiver.notifications: <Device(2,406A,Wireless Mobile Mouse MX Anywhere 2S,EDAE0776)>: diverted controls pressed: 91, 0, 0, 0
00:32:03,311    DEBUG [ReceiverListener:hidraw4] logitech_receiver.diversion: KeyPress action: ['XF86_AudioLowerVolume'], modifiers 0 ['0x7a']
00:32:03,314    DEBUG [ReceiverListener:hidraw4] logitech_receiver.notifications: <Device(2,406A,Wireless Mobile Mouse MX Anywhere 2S,EDAE0776)>: notification for feature NamedInt(6916, 'REPROG CONTROLS V4'), report 0, data 005B0000000000000000000000000000
00:32:03,471    DEBUG [ReceiverListener:hidraw4] logitech_receiver.base: (20) => r[11 02 0900 00000000000000000000000000000000]
00:32:03,471    DEBUG [ReceiverListener:hidraw4] logitech_receiver.notifications: <Device(2,406A,Wireless Mobile Mouse MX Anywhere 2S,EDAE0776)>: diverted controls pressed: 0, 0, 0, 0
00:32:03,471    DEBUG [ReceiverListener:hidraw4] logitech_receiver.notifications: <Device(2,406A,Wireless Mobile Mouse MX Anywhere 2S,EDAE0776)>: notification for feature NamedInt(6916, 'REPROG CONTROLS V4'), report 0, data 00000000000000000000000000000000
00:32:04,611    DEBUG [ReceiverListener:hidraw4] logitech_receiver.base: (20) => r[11 02 0900 005D0000000000000000000000000000]
00:32:04,611    DEBUG [ReceiverListener:hidraw4] logitech_receiver.notifications: <Device(2,406A,Wireless Mobile Mouse MX Anywhere 2S,EDAE0776)>: diverted controls pressed: 93, 0, 0, 0
00:32:04,611    DEBUG [ReceiverListener:hidraw4] logitech_receiver.diversion: KeyPress action: ['XF86_AudioRaiseVolume'], modifiers 16 ['0x7b']
00:32:04,613    DEBUG [ReceiverListener:hidraw4] logitech_receiver.notifications: <Device(2,406A,Wireless Mobile Mouse MX Anywhere 2S,EDAE0776)>: notification for feature NamedInt(6916, 'REPROG CONTROLS V4'), report 0, data 005D0000000000000000000000000000
00:32:04,781    DEBUG [ReceiverListener:hidraw4] logitech_receiver.base: (20) => r[11 02 0900 00000000000000000000000000000000]
00:32:04,781    DEBUG [ReceiverListener:hidraw4] logitech_receiver.notifications: <Device(2,406A,Wireless Mobile Mouse MX Anywhere 2S,EDAE0776)>: diverted controls pressed: 0, 0, 0, 0
00:32:04,781    DEBUG [ReceiverListener:hidraw4] logitech_receiver.notifications: <Device(2,406A,Wireless Mobile Mouse MX Anywhere 2S,EDAE0776)>: notification for feature NamedInt(6916, 'REPROG CONTROLS V4'), report 0, data 00000000000000000000000000000000
`

But no volume control in my Ubuntu 21.04.

Also I change Key Press action to "Control_L" + "Backspace" for Left tilt and tried this in my text editor. It works.
![image](https://user-images.githubusercontent.com/1383457/121260855-8f627a00-c8ba-11eb-90ee-d956d20d80c5.png)

So I've remaped Volume down shortcut to this combination, and when I use my keyboard's Control+Backspace buttons, volume goes down, but not with my Left Tilt :(

![image](https://user-images.githubusercontent.com/1383457/121260988-be78eb80-c8ba-11eb-8065-21b696de08d3.png)

So it's something about Ubuntu, but I don't know how to solve this.

**Comment by psyhonut** [comment]
Also I use solaar -dd to look what's happening when I use multimedia keys from my Logi K360 keyboard.
So, volume down, key down and key up:
```00:43:37,570    DEBUG [ReceiverListener:hidraw4] logitech_receiver.base: (20) => r[20 03 03EA 0000000000000000000000]
00:43:38,070    DEBUG [ReceiverListener:hidraw4] logitech_receiver.base: (20) => r[20 03 0300 0000000000000000000000]
```
volume up, key down and key up:
```00:43:38,578    DEBUG [ReceiverListener:hidraw4] logitech_receiver.base: (20) => r[20 03 03E9 0000000000000000000000]
00:43:39,024    DEBUG [ReceiverListener:hidraw4] logitech_receiver.base: (20) => r[20 03 0300 0000000000000000000000]
```

Also I found names to XF86 buttons little bit different in solaar and ubuntu config:
Ubuntu, volume down XF86 key name:
![image](https://user-images.githubusercontent.com/1383457/121261896-faf91700-c8bb-11eb-8e44-32ff3225c1e8.png)

Same key in solaar:
![image](https://user-images.githubusercontent.com/1383457/121261934-0e0be700-c8bc-11eb-8681-2f79354b603e.png)

Maybe this can help?

**Comment by psyhonut** [comment]
@pfps can you explain how to write execute commands correctly?
I tried to write  like this and still nothing happend:
![image](https://user-images.githubusercontent.com/1383457/121338169-ebaeb380-c925-11eb-9383-b23da0169458.png)

**Comment by pfps** [comment]
Execute takes several parameters (arguments).  The first is the command, the rest are the arguments to the command.   It appears that you are using one parameter so you are trying to execute the command names 'amixer -D pulse ...'  which is not the name of an executable file.  What I do for testing purposes is to insert an execute action on /usr/sbin/notify-send with parameter some debug message.

**Comment by pfps** [comment]
@psyhonut  Is this working for you now?

**Comment by pfps** [comment]
Closing due to no response from submitter
