### ISSUE TITLE
G502 (wired) mouse support

### ISSUE THREAD

**Issue by AdamTmHun** [pwr-Solaar/Solaar#1183]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): 1.0.6
- Distribution: ElementaryOS
- Kernel version (ex. `uname -srmo`): Linux 5.4.0-74-generic x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable): 

<details>

```
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 203, in run
    raise Exception('No devices found')
Exception: No devices found
```
</details>

**Description**
I've just switched to linux, and thought there is a GHub for it, but it turned out there isn't. I have posted my problem on their reddit, and someone told me to check out solaar. I have downloaded it, but it looks like there is no support for G502 Hero mouse (wired).

**Describe the solution you'd like**
Add support for G502 Hero mouse

P.S.: I hope it is possible :)

**Comment by pfps** [comment]
I have a G502 and it is working fine.  Run `lsusb`.  There should be a line like:
```
Bus ... Device ...: ID 046d:c539 Logitech, Inc. USB Receiver
```
The c539 is the id number for the G502's receiver.  If you don't  have this line then you might have a newer or older receiver than I have.   Please post the output of `lsusb`

**Comment by AdamTmHun** [comment]
Bus 001 Device 008: ID 046d:c08b Logitech, Inc.

**Comment by pfps** [comment]
Oh, you have your mouse wired.  When my 502 is wired I see
```
Bus 003 Device 006: ID 046d:c08d Logitech, Inc. G502 LIGHTSPEED Wireless Gaming Mouse
```
It looks as if you have a slightly different mouse.

It appears that the problem is that you are running an old version of Linux that does not fully recognize your mouse when it is wired.  Solaar doesn't need information on Logitech devices that connect directly via wireless but they do need to be fully recognized by the OS.

If your mouse can connect via a wireless receiver try that.  Otherwise it is very likely that the only way to have Solaar work for your mouse is to upgrade your OS.   Linux 5.4 is old - I run 5.11 and will be switching to 5.12 soon.

**Comment by AdamTmHun** [comment]
Sorry, I am confused. What do you mean when your 502 is wired? Since I think you have the wireless version. Also, I have the G502 Hero, not the G502, and that could have inner changes.

Regarding the OS update: I have elementaryOS, and I think I've heard that it updates when a new elementary version comes out. Not sure, but currently I don't see any available system updates for the OS.

**Comment by pfps** [comment]
I have a G502 that can be either connected via a USB cable or communicate wirelessly to a special USB dongle, called a receiver.   You may have a different version that can only be connected via a USB cable.

Elementary OS is a distribution for Linux.  It appears to not be updated very often, or purposely stick with older versions of the Linux kernel.  Other distributions (Fedora, in particular) update to newer versions of the Linux kernel shortly after they come out.  Thus they get the benefits of newer capabilities, drivers, etc., at the cost of more rapid change and maybe exposure to bugs.

**Comment by pfps** [comment]
@AdamTmHun Have you been able to address your issue?

**Comment by AdamTmHun** [comment]
Hey,

Actually, thanks for reminding. I just switched to Ubuntu, since other stuff like Unity wasn't working properly on Elementary. Let me check if it works now

**Comment by AdamTmHun** [comment]
It didn't solve the issue.

Except, I see for some reason, it installs the 1.0.1 version instead of the 1.0.6, and I don't know why. In the command line, it says it is installing the 1.0.6, but its not.

Terminal:
```
adam@adam-pc:~$ sudo apt install solaar
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  gir1.2-appindicator3-0.1 python3-psutil python3-pyudev python3-xlib
Suggested packages:
  python-psutil-doc
The following NEW packages will be installed:
  gir1.2-appindicator3-0.1 python3-psutil python3-pyudev python3-xlib solaar
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 460 kB/497 kB of archives.
After this operation, 2.997 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://hu.archive.ubuntu.com/ubuntu focal/main amd64 gir1.2-appindicator3-0.1 amd64 12.10.1+20.04.20200408.1-0ubuntu1 [3.448 B]
Get:2 http://hu.archive.ubuntu.com/ubuntu focal/main amd64 python3-psutil amd64 5.5.1-1ubuntu4 [141 kB]
Get:3 http://hu.archive.ubuntu.com/ubuntu focal/universe amd64 python3-xlib all 0.23-2build1 [112 kB]
Get:4 http://ppa.launchpad.net/solaar-unifying/ppa/ubuntu focal/main amd64 solaar all 1.0.6+git1363-8854ca6-202106160734~ubuntu20.04.1 [203 kB]
Fetched 460 kB in 0s (1.561 kB/s)                   
Preconfiguring packages ...
Selecting previously unselected package gir1.2-appindicator3-0.1.
(Reading database ... 177357 files and directories currently installed.)
Preparing to unpack .../gir1.2-appindicator3-0.1_12.10.1+20.04.20200408.1-0ubunt
u1_amd64.deb ...
Unpacking gir1.2-appindicator3-0.1 (12.10.1+20.04.20200408.1-0ubuntu1) ...
Selecting previously unselected package python3-psutil.
Preparing to unpack .../python3-psutil_5.5.1-1ubuntu4_amd64.deb ...
Unpacking python3-psutil (5.5.1-1ubuntu4) ...
Selecting previously unselected package python3-pyudev.
Preparing to unpack .../python3-pyudev_0.21.0-3ubuntu1_all.deb ...
Unpacking python3-pyudev (0.21.0-3ubuntu1) ...
Selecting previously unselected package python3-xlib.
Preparing to unpack .../python3-xlib_0.23-2build1_all.deb ...
Unpacking python3-xlib (0.23-2build1) ...
Selecting previously unselected package solaar.
Preparing to unpack .../solaar_1.0.6+git1363-8854ca6-202106160734~ubuntu20.04.1_
all.deb ...
Unpacking solaar (1.0.6+git1363-8854ca6-202106160734~ubuntu20.04.1) ...
Setting up python3-xlib (0.23-2build1) ...
Setting up python3-psutil (5.5.1-1ubuntu4) ...
Setting up gir1.2-appindicator3-0.1 (12.10.1+20.04.20200408.1-0ubuntu1) ...
Setting up python3-pyudev (0.21.0-3ubuntu1) ...
Setting up solaar (1.0.6+git1363-8854ca6-202106160734~ubuntu20.04.1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu2) ...
Rebuilding /usr/share/applications/bamf-2.index...
```

But in the application, it says 1.0.1

If the version isn't the problem, then it still isn't working for some reason.

**Comment by AdamTmHun** [comment]
`lsusb` result: 
```
Bus 001 Device 002: ID 046d:c08b Logitech, Inc. G502 HERO Gaming Mouse
```

**Comment by AdamTmHun** [comment]
Running Solaar from the terminal with cmd `solaar` instead of from the app list, it shows it needs `udve`, but it was already installed when installing solaar.

**Comment by pfps** [comment]
The output from lsusb indicates that a modern version of Solaar should work for your mouse.

The issue that you are seeing with versions is probably due to the fact that the Solaar GUI starts up by looking for any already-running programs that provide a Solaar GUI and quickly quitting if there is one.  So if Solaar 1.0.1 is already running (as a startup program or whatever) the only thing that will happen if you try to run `solaar` is that the main window of the already-running Solaar will be shown.  To get around this you need to find and kill this program, e.g., via `killall solaar`.

**Comment by AdamTmHun** [comment]
This worked, now its 1.0.6, but the mouse is still not showing up.

**Comment by pfps** [comment]
I expect that the problem is that permissions are not being set up for the mouse.  You should run `ls -l /dev/hidraw*`, then disconnect and reconnect your mouse, then run `ls -l /dev/hidraw*` again.  There should be a change in the output, with at least one line starting with `crw-rw----+`.  The '+' indicates that special permissions have been set up.  If there is no change then you may have to reboot.  If there is still no change then I'll have to figure out what the problem is.

Then run Solaar.   The mouse should show up, but the main window will very likely look a bit wrong - the short name for the mouse is likely to be something like '?? (C08B)'.   Let me know what shows up there and also the long name at the top of the right-hand side of the main window.

**Comment by AdamTmHun** [comment]
Nope, no mouse is shown. Also, running `ls -l /dev/hidraw*` showed two line starting with `crw-rw----+`, both for the first and the second time.

**Comment by pfps** [comment]
Hmm.  Are any devices or receivers shown on your Solaar main window?  If so, click on them and then on the little light bulb icon (towards the bottom, sort of in the middle).   What is the path given for each of them?  What is the output of `ls -l /dev/hidraw*`?  What is the output of `udevadm info -n /dev/hidraw*`?

Another possibility is that your mouse uses a different interface than modern Logitech devices that connect via USB.   This is probably fixable.  But try the above first.

The bad possibility is that your mouse doesn't talk the HID++ protocol that Solaar needs.  This would not be fixable.

**Comment by pfps** [comment]
Are you still having the problem?

**Comment by Libra12** [comment]
I have the same problem, same mouse too :/

**Comment by pfps** [comment]
What USB id does this mouse have?   Provide output of lsusb with the mouse connected.   Does the mouse show up at all in Solaar?

**Comment by Libra12** [comment]
> What USB id does this mouse have? Provide output of lsusb with the mouse connected. Does the mouse show up at all in Solaar?

Bus 001 Device 003: ID 046d:c08b Logitech, Inc. G502 HERO Gaming Mouse

No it doesn't show :/

**Comment by pfps** [comment]
Is is likely that this device uses a different USB interface so Solaar needs to know which one.  

Look at output of `lsusb` to find ID of device or receiver, which you already have done.
Provide output of `lsusb -vv -d xxxx:yyyy` where xxxx:yyyy is ID of device or receiver.

Look at output of `grep -H . /sys/class/hidraw/hidraw*/device/uevent` to find directory for the device or receiver, e.g., `/sys/class/hidraw/hidraw3/device/uevent:HID_NAME=Logitech USB Receiver`.
Provide contents of the file `/sys/class/hidraw/hidrawN/device/report_descriptor` where N was found above.  You will have to copy the contents to a file with txt extension before attaching it.
Or, better, install hidrd-convert and provide output of `hidrd-convert -o spec /sys/class/hidraw/hidrawN/device/report_descriptor`.

**Comment by pfps** [comment]
Can you provide the information requested?

**Comment by pfps** [comment]
Closing due to no response.

**Comment by pfps** [comment]
PR #1481 should support your mouse.  Try it out and see.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1481, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1481/head:pull_1481
git checkout pull_1481
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1481
git fetch origin pull/1481/head
git reset --hard FETCH_HEAD
```

**Comment by zawata** [comment]
![image](https://user-images.githubusercontent.com/6119870/157336692-89c58655-b5c8-40cd-bb5e-94e4922dbcb5.png)

It appears to be working now! DPI changes take effect when changed. I'm glad the issue was as simple as adding a new descriptor.

**Comment by SleepingPanda** [comment]
Will there be support for the non-hero version? The output of my lsusb is as follows:
```
lsusb | grep Logitech
Bus 003 Device 003: ID 046d:c07d Logitech, Inc. G502 Mouse
```

**Comment by pfps** [comment]
PR #1601 should fix your issue.  

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1601, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1601/head:pull_1601
git checkout pull_1601
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1601
git fetch origin pull/1601/head
git reset --hard FETCH_HEAD
```

**Comment by SleepingPanda** [comment]
Thanks! It works I think. Here's what the gui looks like:
![image](https://user-images.githubusercontent.com/5846561/167843559-7745e2e5-62cc-4038-8f43-43508443facd.png)

**Comment by pfps** [comment]
Solaar can only do whatever the device supports.  Solaar is not an input driver and cannot modify regular input  from devices.  As the G502 does not support any remapping of its keys, this feature is not available for it.

**Comment by cubitman** [comment]
> Solaar can only do whatever the device supports. Solaar is not an input driver and cannot modify regular input from devices. As the G502 does not support any remapping of its keys, this feature is not available for it.

ah thats unfortunate, i was really banking on it being able to. i cant seem to find any that can remap g502

**Comment by pfps** [comment]
You could use the remapping facilities in X, or Wayland if it has any.

**Comment by UnconnectedBedna** [comment]
Ehm... Time to reopen I guess, or not, depends on you.

I just found out about solaar and figured I'd try it out, and my mose is nowhere to be found.
I don't actually mind, I dont need the tweaking but for your sake you might be interested to fix it once again.
`Bus 009 Device 003: ID 046d:c08b Logitech, Inc. G502 SE HERO Gaming Mouse`

...On arch linux...

But before I start spitting out huge amounts of logs, do you want me to?
As I said, I was fine before finding the software, but I always love to help out anyway if I can in any project. :heart:

**Comment by pfps** [comment]
The current version of Solaar generally doesn't  need any information to be able to correctly handle recent Logitech devices.  Older versions need the help of an external module to handle some recent devices.

If you are running version 1.1.12 and your device doesn't show up then please open a new issue for the problem.
