### ISSUE TITLE
(Option to) Disable notifications on mouse connection

### ISSUE THREAD

**Issue by rugk** [pwr-Solaar/Solaar#1185]
**Is your feature request related to a problem? Please describe.**

When the computer wakes up from standby or my mouse gets connected (it’s a mouse that can use different devices, i.e. M720), I get a useless notification that my mouse is now powered on.

![image](https://user-images.githubusercontent.com/11966684/122740473-48925e00-d284-11eb-8be4-e4a48cc74e80.png)

In addition to the “battery warning” I also _always_ get although my mouse still works and has 20% – these are two notifications that I just constantly (need to) click away.

**Describe the solution you'd like**
This information is of no value. I know, when I move my mouse that it is connected.

**Describe alternatives you've considered**
If you can, maybe set a very low timeout as an alternative? So the message disappears and does not annoy me.

Or find other ways of notifying the user? E.g. the bottom rectangle GNOME displays when you e.g. change your backlight. (It automatically disappears and is not so disruptive as this notification.)

**Additional context**
N/A

**Comment by pfps** [comment]
Solaar uses standard notifications.  A good window manager should have a method for turning off notifications on a per-application basis.  In XFCE there is a nice GUI that does this under Settings->Notifications.

**Comment by mrtimdog** [comment]
Hi, admittedly, I have changed the source to remove this notification too. I also use XFCE and have never got the blocking of solaar notifications to work - it maybe that it doesn't work for any app on my system though!

**Comment by pfps** [comment]
In XFCE go to the main menu, then Settings -> Notifications.  Open the Applications tab and scroll down to the Solaar entry and turn it off.

This won't turn off the notifications that come from xfce4-power-manager.  These have to be turned off separately in the Notifications app.

**Comment by rugk** [comment]
Well… I could now say that a good application should only send notifications when something is really noteworthy.
And IMHO "mouse connected" is not interesting at all.

So then why don't remove that by default?

**Comment by rugk** [comment]
Really, I would ask you to reconsider this decision. If people already patch the source code to remove it… :sweat_smile: 

Or, otherwise, could you please explain what value a "this mouse is connected" notification has?

If it hbas one, maybe make an option to disable it/make it optional, at least.

**Comment by pfps** [comment]
See PR #1359 
This PR is waiting for confirmation that it doesn't cause other problems.

**Comment by rugk** [comment]
Awesome!

BTW, one can disable all notifications in GNOME for an app, however, I of course want some notifications from Solaar:

![image](https://user-images.githubusercontent.com/11966684/145640968-0b9a815b-6358-4373-9e8c-3824b09fbd09.png)

**Comment by pfps** [comment]
Let me know whether this version of Solaar solves your issue.

**Comment by pfps** [comment]
@rugk I need an explicit response that this PR has been used and is working.

**Comment by rugk** [comment]
Ah iot's Python, so I can easily tets it, okay, did so and commented there.
