### ISSUE TITLE
a rule condition like Process that matches the program the cursor is over, not the program that is focused

### ISSUE THREAD

**Issue by ohsix** [pwr-Solaar/Solaar#1188]
hello!

there's quite a few gestures on linux that you can send to windows that are under the cursor but not focused, like scrolling over the volume widget. process based rules can that change scrolling behavior interfere with them

a match that works with the process name under the cursor at the time avoids this

thanks,
  josh

**Comment by pfps** [comment]
I'm a bit confused as to what the problem is.  

Solaar should not be interfering with things like scrolling over the volume widget.  Of course, if you divert scrolling and the Solaar rule doesn't emit a scroll then you won't get this behaviour, but something like using Solaar rules to change scrolling speed should still trigger any special processing of scrolling.  If this is not the case then the behaviour either needs to be documented in Solaar or fixed.  Please let me know if this is the case.

If all you want to do is to let Solaar rules have access to the program under the cursor then this might be possible, depending on whether X11 provides access to this information.

**Comment by ohsix** [comment]
that was only an example. the information required is the same as used in the process rules, it's just based on focus and not what's currently under the cursor

I scroll a lot of things that aren't in focus and the rules I added for chrome change the behavior of scrolling when it is focused but not the target of scroll events

**Comment by pfps** [comment]
My take on this request is to add a new rule condition for the process of the window that the cursor is over.

**Comment by pfps** [comment]
PR #1214 adds MouseProcess that works like Process but for the window that the mouse is over not the focus window.  Please give it a try.


To download and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1214, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1214/head:pull_1214
git checkout pull_1214
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1214
git fetch origin pull/1214/head
git reset --hard FETCH_HEAD
```

**Comment by ohsix** [comment]
hello! thank you for this.

the MouseProcess rule works but "Key press" events only send them to the focused window. needs a corresponding "send to window under cursor" event

**Comment by pfps** [comment]
Key presses go to the focused window because that's how keyboard input works.  There is a way to send any event to any window, but that uses a different interface and many programs reject such input.   If this feature was added to Solaar I expect that much confusion would result.

If this is what you need I suggest executing xdotool, maybe in a shell script.

**Comment by ohsix** [comment]
but they don't (reject the input) and the ultimate issue is rules that send input to the wrong window already. scrolling events work over most windows where they make sense, like volume controls or lists whether they're focused or not

just to restate the issue: if I have a rule for chrome that uses the scroll events it breaks other uses of the scroll events to these "passive listeners", primarily the volume control. ultimate consequence being that I can't have rules for chrome because they'll change how every other window works if it happens to have focus

thank you for looking into this, I will find some references as to how gtk and chrome use the passive events. they are definitely not ignored

**Comment by pfps** [comment]
Currently rules send keyboard keys and mouse clicks using Xtest, which injects the events into the X11 system as regular events. Sending these events to a particular window uses another API, which some programs reject.

A good solution to this would be welcome.

**Comment by ohsix** [comment]
right right. i see where i was confused about the thing

button and motion events are a different class than key events with different rules

gtk uses xinput and doesn't seem to mind xtest particularly as an event source

kind of lost the thread of context from the original bug, not used to people responding to bugs (!!!). should have reread it. in my brain i'm thinking "key" i wanna send a 'key" when i'm over the volume control, but the key i want to send is the mute button which works no matter where it is sent.

when i tested the patch for MouseProcess i noticed the focus thing as a problem and didn't really think too carefully about it

the issue now is that tackling the "chrome eats the rules" rule means an inverted MouseProcess to check everything else before chrome, moving the consideration for chrome into one big rule instead of into a rule just for say, audacious where i want MouseProcess and a hypothetical KeyInputOver to send s to toggle shuffle, or z and b to go back and forth

with KeyInputOver the rule for chrome and audacious are simple and don't depend on each other
