### ISSUE TITLE
Scrolling speed issue

### ISSUE THREAD

**Issue by fchabouis** [pwr-Solaar/Solaar#1192]
Hello,
I think my problem is listed in your FAQ : my scrolling becomes many times a day very slow, and I have to unplug/plug the receiver to fix the problem. Unfortunately I don't understand the solution explained in the documentation. It says "To fix this problem click on the icon at the right edge of the setting to set it to “Ignore this setting”.

Does it mean that I have to switch off Smooth Scrolling in the settings ? Like this :
![image](https://user-images.githubusercontent.com/15341118/123933910-17f0a980-d993-11eb-8750-f38878194cf9.png)

But I doubt it, it seems the setting we are talking about is "Scroll Wheel Resolution", but I don't see it mentionned anywhere in Solaar.

Thanks for your help !

**Comment by pfps** [comment]
Which version of Solaar are you running?

**Comment by fchabouis** [comment]
1.0.1

(Ubuntu 20.04)

**Comment by pfps** [comment]
1.0.1 is old.  It has different names for the settings and doesn't have the ability to ignore settings.  You should upgrade to 1.0.6 using either of the PPAs listed in
https://github.com/pwr-Solaar/Solaar

**Comment by pfps** [comment]
Closing as fixed in current version of Solaar.

**Comment by fchabouis** [comment]
Thank you for your answer, I have updated my package and will see if it works better.

For your information, I read in the documentation `Solaar has progressed beyond version 1.0 but some distros or repositories provide version 0.9.2, which is very old. Installing the current version will provide significant improvements.` and `Ubuntu/Kubuntu 16.04+: use the solaar package from universe repository`.

Being on Ubuntu 20.04, I considered I was above 16.04 (`16.04+`), checked the version number from the universe repository, saw that it was beyond 1.0, and thus understood that I had the correct version installed for my system.

I explain what happend in my head in case it can help you clarify the documentation :)

Thanks for your assistance.
