### ISSUE TITLE
Battery icon incorrect in Pop OS default theme

### ISSUE THREAD

**Issue by BaronKrause** [pwr-Solaar/Solaar#1193]
This is a followup to an old issue https://github.com/pwr-Solaar/Solaar/issues/768 from last year.

The Pop OS default theme seems to only have the "empty, caution, low, good, full" icons as "symbolic" variants (like "battery-full-symbolic.svg"), everything else in the theme is just "battery.png" and they all look like 20% full batteries (like a picture of a duracell battery).

There was a fix to the issue merged and it was closed, but it still has the same issue on Pop OS with the current GIT version of Solaar using the default Pop OS GTK theme (custom themes are fine).

Thanks!

**Comment by pfps** [comment]
Icon themes that don't have the usual set of battery icons don't work well with Solaar.  The solution is to get the theme updated or choose a different theme.

The option --battery-icons=symbolic can be used to prefer symbolic options if they are better supported, but anything beyond that is out of scope.

**Comment by BaronKrause** [comment]
> Icon themes that don't have the usual set of battery icons don't work well with Solaar. The solution is to get the theme updated or choose a different theme.
> 
> The option --battery-icons=symbolic can be used to prefer symbolic options if they are better supported, but anything beyond that is out of scope.

Ahh that a shame, thanks anyway. With that command it fixes the old school looking battery in on inside solar but it still uses a static non symbolic icon in the system tray.

**Comment by pfps** [comment]
What the option should do is use symbolic battery icons everywhere.
It this is not the case then there might be a bug in Solaar or the icon theme might be messed up or your system tray might have a problem.  Solaar doesn't do anything to change themes but your system tray might.
What you can do is look at the icons available in your current theme using gtk3-icon-browser.  The battery icons are in "Other".  There should be at least ten in both normal and symbolic.

**Comment by BaronKrause** [comment]
> What the option should do is use symbolic battery icons everywhere.
> It this is not the case then there might be a bug in Solaar or the icon theme might be messed up or your system tray might have a problem. Solaar doesn't do anything to change themes but your system tray might.
> What you can do is look at the icons available in your current theme using gtk3-icon-browser. The battery icons are in "Other". There should be at least ten in both normal and symbolic.

Just checked with the stock Pop Icon theme and Papirus which works as expected with the battery icon.

They both seem to have the same amount of battery icons in both normal and symbolic, though the Pop theme shows them as all the same full battery icon thumbnail in the viewer (but clicking on them shows the actual icons they should be in the various sizes).

With the pop theme however even when using symbolic, which is reflected by the battery icon in the actual program changing, the system tray continues to the the 16x16 battery png inside the themes devices folder. I tested it by drawing an x on it, it uses that 1 icon for all battery states. I cant figure out why it isn't using the symbolic battery icons for the system tray with this distros theme.

As far as I can tell its been like this since they updated their theme a few years back and I did all my recent testing on a fresh 21.04 install. The theme the distro uses is on Github if anyone is willing to take a look at it https://github.com/pop-os/icon-theme

Thank you again

**Comment by pfps** [comment]
This looks like there is a problem with the system tray.  I use XFCE and a recent change there caused the tray icon to be very small (maybe 16x16).   The menu that comes up when clicking on the system tray icon uses the same icon names so if that is OK then my view is that Solaar is definitely using the right icons.

**Comment by BaronKrause** [comment]
> This looks like there is a problem with the system tray. I use XFCE and a recent change there caused the tray icon to be very small (maybe 16x16). The menu that comes up when clicking on the system tray icon uses the same icon names so if that is OK then my view is that Solaar is definitely using the right icons.

Thats so weird, could the symbolic icons be set in a way that Solaar wouldn't think their usable for the tray and defaulting back to the normal battery.png for everything? Since it works perfect in other themes, symbolic and non symbolic depending on command switch. it had to be the theme right?

**Comment by pfps** [comment]
I sure looks as if something is messed up in the theme.  
It may be that the system tray is getting the icons for a size that is messed up but in other places the icons are fine.  Tools like gtk3-icon-browser may use a larger size or may use scalable icons whereas the system tray may use a particular size.  In XFCE spent some time trying to figure out why the system tray icon was so small and came up with the conclusion that Solaar wasn't doing anything wrong.
