### ISSUE TITLE
Problem with running newest version (+ M500s support)

### ISSUE THREAD

**Issue by bbutler3** [pwr-Solaar/Solaar#1197]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): `1.0.6` (`1.0.1` from apt runs fine)
- Distribution: `Ubuntu 20.04`
- Kernel version (ex. `uname -srmo`): `Linux 5.8.0-59-generic x86_64 GNU/Linux`
- Output of `solaar show`: N/A

**Describe the bug**
When I run `~/.local/bin/solaar` (running just `solaar` gives `bash: /usr/bin/solaar: No such file or directory`), I get `Solaar: missing required system package gir1.2-gtk-3.0`. However, I've confirmed that this package is installed. When trying to install it with `apt`, I got `gir1.2-gtk-3.0 is already the newest version (3.24.20-0ubuntu1).` I don't understand what's going on here. I installed via `pip install --user solaar` and it appeared to install `v1.0.6`.

**To Reproduce**
1. `~/.local/bin/solaar`

**Additional context**
I have a Logitech M500s which I bought quite recently. It's wired, and I'd like to change its DPI. I was originally able to use `~v1.0.1` through `apt`, and run it that way. It did not recognize my mouse. I tried to figure out how to add it, but the web page about doing that didn't quite make it clear how to get that done. It also seemed to imply that basically any device should be recognized to some degree. But Solaar shows no devices. That's why I've tried to upgrade to the latest version. I don't see that my mouse is supported in the list, though. I'm happy to add it myself if told how. Its ID is `046d:c093`.

**Comment by pfps** [comment]
I'm not sure what the problem with the missing repository is. 
What the code is doing is trying to load the Gtk bindings for python, as in the following code:
```
#!/usr/bin/python3
import importlib
gi = importlib.import_module('gi')
gi.require_version('Gtk', '3.0')
```
Create an executable file sgtk.py with these contents and try to run it.  If that fails then try to run it as
```
python2 ./sgtk.py
```
If that succeeds then the problem is that the bindings are installed for python2 but not python3.  I don't know how to ensure that the python3 bindings are installed in Ubuntu.

**Comment by bbutler3** [comment]
Ok, thanks for the testing advice. I found that the issue had to do with the fact that I use python through Anaconda. I needed to install a gtk package through conda:
```
conda install -c conda-forge gtk3
```
However, upon doing that and trying to run Solaar again, a new error appears:
```
(solaar:85208): Gtk-WARNING **: 13:52:16.435: Found an icon but could not load it. Most likely gdk-pixbuf does not provide SVG support.
Traceback (most recent call last):
  File "/home/bbutler3/.local/lib/python3.8/site-packages/solaar/ui/__init__.py", line 159, in <lambda>
    application.connect('startup', lambda app, startup_hook: _startup(app, startup_hook, use_tray, show_window), startup_hook)
  File "/home/bbutler3/.local/lib/python3.8/site-packages/solaar/ui/__init__.py", line 117, in _startup
    window.init(show_window, use_tray)
  File "/home/bbutler3/.local/lib/python3.8/site-packages/solaar/ui/window.py", line 832, in init
    Gtk.Window.set_default_icon_from_file(_icons.icon_file(NAME.lower()))
TypeError: Argument 0 does not allow None as a value
Traceback (most recent call last):
  File "/home/bbutler3/.local/lib/python3.8/site-packages/solaar/ui/__init__.py", line 128, in _activate
    app.add_window(window._window)
TypeError: Argument 1 does not allow None as a value
```

I'd appreciate further advice. Thanks again for your time!

**Comment by pfps** [comment]
That is truly weird.   The Solaar icon is an SVG file but I have not heard of any problems about not being able to load it.  It looks as if your GDK installation is missing the SVG loader, but I have no idea how to fix that.  The only other possibility that I can think of is that the Solaar icon cannot be read - maybe because Solaar was installed as root (via `sudo pip install --user solaar`?) but root's default file permissions meant that the file can only be read by root.  To check this you will have to find where Solaar is installed and look for the permissions of the Solaar icons (probably in ~/.local/share/solaar/icons).

**Comment by bbutler3** [comment]
Very weird indeed. I did not install as root. I also confirmed that the icons can all be read by any user.

I tried 
```
gdk-pixbuf-query-loaders --update-cache
```
as I read [here](https://github.com/dino/dino/issues/1024) that it might solve the issue, but it didn't. Then I tried installing `librsvg2-bin`, but that didn't help either. 

I would note that v1.0.1 loaded fine with an icon (just didn't recognize my device). Maybe a comparison between the versions might help. Since this appears to be such a niche problem, though, I understand if we can't find a fix (or if it isn't worth the time). `ratbagctl` seems to allow me to set the dpi relatively consistently (but isn't totally reliable), so I am not desperate. Just seems like Solaar is a much nicer option.

**Comment by pfps** [comment]
The message strongly indicates that the icon file was found but could not be loaded.  The only things that I could think of that might cause that is permissions and a missing loaders.  I suppose that it might be possible that the icon file is corrupt.  Did you try to open the icon file in a graphics program like gimp?  Another option would be to replace the Solaar icon files with known-good icon files.

**Comment by bbutler3** [comment]
All the `.svg` files open fine with Image Viewer from the file explorer. However, I do get permission denied when trying with GIMP. I did `chmod 777` on all the image files in the `icons` directory, but I *still* can't open them in GIMP? That includes the `.png`s though as well. I'm confused. Also, still the same Solaar error after changing the permissions. I tried the same process inside the directory where I cloned Solaar from git instead. I can open the icon files in GIMP from there. But running that version of Solaar throws **the same errors**.

**Comment by pfps** [comment]
This now sounds like a missing component in gdk, but I've never seen this problem before and I don't know how to fix it.

**Comment by bbutler3** [comment]
That's alright. I still really appreciate your time. If I end up looking further and finding anything useful, I'll return here with the info in case anyone else ever runs into this.

**Comment by pfps** [comment]
OK
