### ISSUE TITLE
Battery Reporting Mouse M510

### ISSUE THREAD

**Issue by cmesoar** [pwr-Solaar/Solaar#1198]
Mouse M510 with Logitech unifying receiver reports 70% (with warning exclamation) even with new batteries installed.

**Comment by pfps** [comment]
Many Logitech devices only have several battery levels, either numeric or symbollic.  which Solaar then reports.  So the M510 may never report full.
Solaar turns these levels into a battery icon name,  in this case battery-good, which should result in a reasonable icon.  Some themes, however, use inappropriate icons, and sometimes only for some images sizes.
To fully investigate why your are seeing a warning icon you would have to determine which icon files are being used.  That depends on your distribution and theme.

So Solaar is doing the best it can.

**Comment by cmesoar** [comment]
Wonderful thank you and thank you for the work of building such a useful
app!

**Comment by ohsix** [comment]
this is close to a feature request i was about to file

can a device (like the m510) without CHARGING_CONTROL use its' absence to infer the battery takes a really long time to discharge?

spurious 5% reporting causes a notification & every time it'll jump back to 70% when i cycle the power

next time it happens i'll see if there's a software way to ask the mouse to think again about the battery level

ideal situation is reporting it after the mouse has been kicked and responded with "yes it's definitely low", an alternative is an option to disable charge notification

the batteries in the mouse right now are carbon zinc (bleh!) and have a 2012 date code on them, they last a long time :)

**Comment by pfps** [comment]
Different mice have different battery characteristics. For many mice Solaar only gets to the a few battery levels.  Solaar also doesn't get to see when battery are replaced.  So Solaar is pretty much stuck with only reporting what it gets from the device.

**Comment by ohsix** [comment]
right, i don't have any devices with CHARGING_CONTROL and i'm assuming only devices with rechargeable batteries support it. basically the mouse can't report an actionable battery state and that last 5 percent could last years on this mouse

if devices without chargers have fixed batteries the notification priority could change or not be sent at all

**Comment by ohsix** [comment]
forgot upower tries to do this and the kernel adds a power_supply class for hidpp devices. it doesn't get it right or change anything but i thought it useful to add what it shows here

```
[ohsix@pro ~]☁️ upower -d
Device: /org/freedesktop/UPower/devices/mouse_hidpp_battery_8
  native-path:          hidpp_battery_8
  model:                Wireless Mouse M510
  serial:               4051-7d-55-ed-57
  power supply:         no
  updated:              Sat 21 Aug 2021 03:37:32 AM PDT (92 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    battery-level:       normal
    percentage:          55% (should be ignored)
    icon-name:          'battery-low-symbolic'
```
```
[ohsix@pro ~]⛈️ grep -sre "" /sys/class/power_supply/hidpp_battery_8/
/sys/class/power_supply/hidpp_battery_8/uevent:POWER_SUPPLY_NAME=hidpp_battery_8
/sys/class/power_supply/hidpp_battery_8/uevent:POWER_SUPPLY_TYPE=Battery
/sys/class/power_supply/hidpp_battery_8/uevent:POWER_SUPPLY_ONLINE=1
/sys/class/power_supply/hidpp_battery_8/uevent:POWER_SUPPLY_STATUS=Discharging
/sys/class/power_supply/hidpp_battery_8/uevent:POWER_SUPPLY_SCOPE=Device
/sys/class/power_supply/hidpp_battery_8/uevent:POWER_SUPPLY_MODEL_NAME=Wireless Mouse M510
/sys/class/power_supply/hidpp_battery_8/uevent:POWER_SUPPLY_MANUFACTURER=Logitech
/sys/class/power_supply/hidpp_battery_8/uevent:POWER_SUPPLY_SERIAL_NUMBER=4051-7d-55-ed-57
/sys/class/power_supply/hidpp_battery_8/uevent:POWER_SUPPLY_CAPACITY_LEVEL=Normal
/sys/class/power_supply/hidpp_battery_8/serial_number:4051-7d-55-ed-57
/sys/class/power_supply/hidpp_battery_8/power/runtime_active_time:0
/sys/class/power_supply/hidpp_battery_8/power/wakeup:enabled
/sys/class/power_supply/hidpp_battery_8/power/wakeup_count:0
/sys/class/power_supply/hidpp_battery_8/power/wakeup_abort_count:0
/sys/class/power_supply/hidpp_battery_8/power/wakeup_expire_count:0
/sys/class/power_supply/hidpp_battery_8/power/wakeup_total_time_ms:0
/sys/class/power_supply/hidpp_battery_8/power/wakeup_active_count:2
/sys/class/power_supply/hidpp_battery_8/power/runtime_status:unsupported
/sys/class/power_supply/hidpp_battery_8/power/runtime_suspended_time:0
/sys/class/power_supply/hidpp_battery_8/power/wakeup_max_time_ms:0
/sys/class/power_supply/hidpp_battery_8/power/wakeup_active:0
/sys/class/power_supply/hidpp_battery_8/power/control:auto
/sys/class/power_supply/hidpp_battery_8/power/wakeup_last_time_ms:861685101
/sys/class/power_supply/hidpp_battery_8/hwmon4/power/runtime_active_time:0
/sys/class/power_supply/hidpp_battery_8/hwmon4/power/runtime_status:unsupported
/sys/class/power_supply/hidpp_battery_8/hwmon4/power/runtime_suspended_time:0
/sys/class/power_supply/hidpp_battery_8/hwmon4/power/control:auto
/sys/class/power_supply/hidpp_battery_8/hwmon4/name:hidpp_battery_8
/sys/class/power_supply/hidpp_battery_8/manufacturer:Logitech
/sys/class/power_supply/hidpp_battery_8/online:1
/sys/class/power_supply/hidpp_battery_8/type:Battery
/sys/class/power_supply/hidpp_battery_8/scope:Device
/sys/class/power_supply/hidpp_battery_8/wakeup27/event_count:2
/sys/class/power_supply/hidpp_battery_8/wakeup27/max_time_ms:0
/sys/class/power_supply/hidpp_battery_8/wakeup27/wakeup_count:0
/sys/class/power_supply/hidpp_battery_8/wakeup27/total_time_ms:0
/sys/class/power_supply/hidpp_battery_8/wakeup27/expire_count:0
/sys/class/power_supply/hidpp_battery_8/wakeup27/active_count:2
/sys/class/power_supply/hidpp_battery_8/wakeup27/last_change_ms:861685101
/sys/class/power_supply/hidpp_battery_8/wakeup27/prevent_suspend_time_ms:0
/sys/class/power_supply/hidpp_battery_8/wakeup27/name:hidpp_battery_8
/sys/class/power_supply/hidpp_battery_8/wakeup27/active_time_ms:0
/sys/class/power_supply/hidpp_battery_8/status:Discharging
/sys/class/power_supply/hidpp_battery_8/model_name:Wireless Mouse M510
/sys/class/power_supply/hidpp_battery_8/capacity_level:Normal
```

data available from upower shows the spurious low battery event and when the battery was replaced:
![Screenshot from 2021-08-21 03-42-40](https://user-images.githubusercontent.com/3180944/130319312-71659959-0142-487f-b1d9-dc6dd12e5056.png)
