### ISSUE TITLE
Solaar Not Working With Logid

### ISSUE THREAD

**Issue by andrew0530** [pwr-Solaar/Solaar#1199]
**Information**

- Solaar version - 1.0.6
- Distribution - Linux Mint 20.1 MATE
- Kernel version - 5.8.0-59-generic

**Describe the bug**
Key/Button diversion stops working when logid is (re)booted
(I have been able to use logid and solar simultaneously, both diversions and logid gestures working. But not anymore)

**To Reproduce**
1. boot/open solaar   (diversions work, but logid gestures stop working)
2. Reboot logid   (logid gestures work, but diversions stop working)

**Screenshots**
This is just a screenshot of Solaar that sees 3 mxkeys. 
![Selection_003](https://user-images.githubusercontent.com/77707239/124549257-07549d80-de83-11eb-818c-0d3c0508da37.jpg)

**Comment by pfps** [comment]
Having two programs modify how input keys work is not recommended. 
 
Solaar changes what happens on the device, here causing a key to produce a special report that Solaar can act on with its rules.
If logid modifies how the device works then this may interfere with what Solaar does.  If, instead, logid uses something like X11 key bindings then these will not work with diverted keys.
Your behaviour may change depending on the order in which the changes end up being performed.
