### ISSUE TITLE
auto-hide the application window after a timeout, if it was shown by the Solaar button

### ISSUE THREAD

**Issue by pwr** [pwr-Solaar/Solaar#12]

**Comment by Klap-in** [comment]
Why adding an auto-hide? If you request the window, you as user had a purpose for it. So auto-hiding feels as contradiction to that. For example, you were interrupted, and subsequently your window is gone..

**Comment by pfps** [comment]
Yes, this doesn't seem like something that should be provided, so I'm going to close this issue.
