### ISSUE TITLE
How to prevent Solaar from autostart at boot?

### ISSUE THREAD

**Issue by Futureknows** [pwr-Solaar/Solaar#1229]
Hi, I've configured my logitech and no longer need Solaar to autostart at every boot. Where can I disable it? I can't find it in autostart or system services on Fedora.

**Comment by pfps** [comment]
@rathann How does your packaging of Solaar set up autostart?  How can autostart be disabled?

@Futureknows Depending on what you have set up Solaar to do you may need Solaar to continue to autostart.  Most settings that Solaar sets up do not persist when the device turns off or goes into power saving mode so Solaar needs to push them to the device when the device reconnects to your computer.

**Comment by pfps** [comment]
As far as I can tell, the Solaar autostart file in the Fedora distribution is /etc/xdg/autostart/solaar.desktop
I run XFCE and I can turn this off in Settings -> Session and Startup -> Application Autostart.  Other window managers should have similar facilities.  Or you can just delete the autostart file as rool, although I expect it will come back when Solaar is updated.

**Comment by rathann** [comment]
> @rathann How does your packaging of Solaar set up autostart? How can autostart be disabled?

Indeed. The Fedora package places the [desktop](https://github.com/pwr-Solaar/Solaar/blob/master/share/autostart/solaar.desktop) file in `/etc/xdg/autostart`. Users can disable it individually in their desktop preferences.

**Comment by rathann** [comment]
@Futureknows it's still useful after configuration. It shows you which devices are connected and their battery status, for example. If you don't need it, you can also simply uninstall it.

**Comment by mikoducky** [comment]
> > [@rathann](https://github.com/rathann) How does your packaging of Solaar set up autostart? How can autostart be disabled?
> 
> Indeed. The Fedora package places the [desktop](https://github.com/pwr-Solaar/Solaar/blob/master/share/autostart/solaar.desktop) file in `/etc/xdg/autostart`. Users can disable it individually in their desktop preferences.

This was great info! I went into terminal and:

`cd /etc/xdg/autostart
sudo mv solaar.desktop solaar.desktop.bak`

That way, I can just re-enable if there's an issue.
