### ISSUE TITLE
cli config can't read current values

### ISSUE THREAD

**Issue by tomyri** [pwr-Solaar/Solaar#123]
I can't read current values in console, but I can set them if I use exact values. But for DPI, higher or lower doesn't change anything. GUI seems to read the value right.

tomi@ArchAlly ~> solaar config 1
Performance Mouse MX (Performance MX) [101A:8D4A1FDC]

Sensitivity (DPI)
solaar: error: 'NoneType' object has no attribute 'replace'

Using master branch. 
Python 3.3.2, ArchLinux

**Comment by BenjaminHae** [comment]
I have the same error, but for me setting DPI with exact values doesn't work.
GUI is unaffected.

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
