### ISSUE TITLE
Can I change the builtin rules?

### ISSUE THREAD

**Issue by dev-gm** [pwr-Solaar/Solaar#1230]
My mouse has two buttons on the side, which are both automatically tied (for firefox) to go forwards and backwards in history. I want it to instead switch back and forth between tabs. The app doesn't let me edit it, is there a specific file I can edit to change these rules? Thanks in advance.

**Comment by pfps** [comment]
There are currently four built-in rules, which cannot be changed except by editing the Solaar code.  They probably should be removed, except for the one for Brightness keys.  But none of the built-in rules should be sensitive to mouse buttons, at least not in the current version of Solaar.
You should also be able to override built-in rules by defining your own

**Comment by dev-gm** [comment]
I overrided the built-in rules successfully, so that the new rules are visible in the app, but the actual behavior doesn't change. Maybe I'm misunderstanding what the buttons are supposed to be. What is "crown_right_ratchet" and "crown_pressed"? Thanks

**Comment by pfps** [comment]
These are actions of the crown of certain Logitech keyboards, not mouse buttons.  Mouse buttons are handled by the Key condition, which takes names of special keyboard keys (e.g., Volume Up) and mouse buttons (e.g., Forward Button). To find the names for the buttons on your mouse look in the Key/Button Diversion setting.  You have to divert the button before it can trigger a rule.

**Comment by dev-gm** [comment]
Oh, I see. I guess I just misunderstood it. Sorry for taking your time.
