### ISSUE TITLE
MX Revo bluetooth (RCL124) not detected as hidpp device

### ISSUE THREAD

**Issue by ohsix** [pwr-Solaar/Solaar#1232]
solaar 1.0.6
fedora 34

```
Aug 18 18:20:36 pro kernel: hid-generic 0005:046D:B007.0017: input,hidraw0: BLUETOOTH HID v0.19 Mouse [Logitech MX Revolution Mouse] on 00:27:13:xx:xx:xx
```
```
[ohsix@pro ~]☁️ solaar show
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/solaar/cli/__init__.py", line 203, in run
    raise Exception('No devices found')
Exception: No devices found
```

this is really just a question about whether it is sufficient to change the check at https://github.com/pwr-Solaar/Solaar/blob/a1874c572baa356548c749a57d0a01edfece14b4/lib/logitech_receiver/base_usb.py#L208 to handle the lower product id (B007) or if the kernel has to say it's a logitech hidpp device

ty

**Comment by pfps** [comment]
If the kernel doesn't think the device talks HID++ then it is quite likely that it doesn't.  But the kernel might be wrong, so try changing the limit but be prepared for failure.

If you know that the mouse talks HID++ then you could file a bug against the hidpp driver.

**Comment by ohsix** [comment]
some things other than the kernel suggest it might be a hidpp device but reading reports also fails, so probably not

kernel doesn't have a quirk for it or anything and their regular detection code path that tries to read a report probably passes it over

**Comment by pfps** [comment]
See #2131
