### ISSUE TITLE
"Show Applications" icons won't scroll

### ISSUE THREAD

**Issue by HorseboxHeaven** [pwr-Solaar/Solaar#1239]
Any chance Solaar could have anything to do with the fact that my application icons won't scroll?

Path         : /dev/hidraw1
Index        : 1
Wireless PID : 406F
Protocol     : HID++ 4.5
Polling rate : 8 ms (125Hz)
Serial       : B851EBC1
Unit ID      : EDF2CBC7
  Bootloader : BOT 49.00.B0001
  Firmware   : MPM 06.03.B0022

Path         : /dev/hidraw2
Index        : 2
Wireless PID : 4088
Protocol     : HID++ 4.5
Polling rate : 20 ms (50Hz)
Serial       : 305B1714
  Bootloader : BL1 09.00.B0010
  Firmware   : MPK 10.00.B0010

**Comment by pfps** [comment]
I'm not sure what the issue is, but I don't see how Solaar could affect scrolling in your window manager as all it does is control devices.

**Comment by HorseboxHeaven** [comment]
I guess my point was to query whether the "control" was a possibility when it came to scrolling application icons in the "show applications" window.
