### ISSUE TITLE
Solaar stoped detect my K480 keyboard after update

### ISSUE THREAD

**Issue by Samuckadf** [pwr-Solaar/Solaar#1242]
**Information**

- Solaar version: 1.0.6+git1388-3f33d06~ubuntu20.04.1
- Distribution: Linux Lite 5.4 (Ubuntu 20.04.1 LTS based)
- Kernel version (ex. `uname -srmo`): Linux 5.8.5-050805-generic x86_64 GNU/Linux
- Output of `solaar show`: 

```
  Wired Devices
  1: ?? (B33D)
     Device path  : /dev/hidraw2
     USB id       : 046d:B33D
     Codename     : ?? (B33D)
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 207, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 292, in run
    _print_device(d, num=dev_num)
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 101, in _print_device
    print('     Kind         :', dev.kind)
  File "/usr/share/solaar/lib/logitech_receiver/device.py", line 260, in kind
    self._kind = KIND_MAP[_hidpp20.get_kind(self)]
KeyError: None
```

- 

<details>

```
OUTPUT HERE
```
</details>

**Describe the bug**
After a few updates from apt, Solaar won't detect my K480 Keyboard anymore. I turned off, and turned on again, and won't works...

I also have a M535 mouse, Solaar is working with it like a charm.

Thanks in advance,
Samuel. (samuckadf)

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by pfps** [comment]
I think I know what might be going on.  Please provide output from `solaar -dd show` so that I can see the interaction with the device.

**Comment by pfps** [comment]
Also try with PR #1243

To download and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1243, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1243/head:pull_1243
git checkout pull_1243
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1243
git fetch origin pull/1243/head
git reset --hard FETCH_HEAD
```

**Comment by Samuckadf** [comment]
> Also try with PR #1243
> 
> To download and work with Solar
> 
> ```
> git clone https://github.com/pwr-Solaar/Solaar.git
> cd Solaar
> ```
> 
> Run Solaar as bin/solaar from this directory.
> 
> To run PR #1243, first clone Solaar if you have not already done so and cd to the clone directory. The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
> 
> ```
> git fetch origin pull/1243/head:pull_1243
> git checkout pull_1243
> ```
> 
> To download a new version of the pull request, fetch it and then set your pull branch
> to the new fetch, as in:
> 
> ```
> git checkout pull_1243
> git fetch origin pull/1243/head
> git reset --hard FETCH_HEAD
> ```

I wrote those lines (260 and 261) and commented the original line 260.

Look how the keyboard shows in solaar panel:
![image](https://user-images.githubusercontent.com/87533468/130825681-9f5e7b13-f8a4-4f89-afcc-383c58716031.png)
The first mouse, with battery indicator, is my M535.
The second one may refer my K480 Keyboard. When i turned off the kb it disappears and when i turn on it appears again.

**Comment by Samuckadf** [comment]
> Hmm. The problem is not what I thought it was. You are connecting via bluetooth on both devices, right?
> 
> I do think I see the problem but it will require some thought to fix.

Yep, both devices on bt... This is weird, before updates (i can't figure out when exactly), worked like a charm.

**Comment by Samuckadf** [comment]
> Not so much thought. Try the current version of PR #1243

Amazing! Thank you so much! It worked!
