### ISSUE TITLE
Solaar uses 100% of one logical CPU

### ISSUE THREAD

**Issue by validatedev** [pwr-Solaar/Solaar#1249]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): solaar 1.0.6
- Distribution: Fedora 34
- Kernel version (ex. `uname -srmo`): `Linux 5.13.12-200.fc34.x86_64 x86_64 GNU/Linux`
- Output of `solaar show`:

<details>

```
Nano Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:C534
  Serial       : None
    Firmware   : 29.01.B0016
  Has 1 paired device(s) out of a maximum of 2.
  Has 19 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)

  2: Wireless Mouse M185 new
     Device path  : /dev/hidraw4
     WPID         : 4054
     Codename     : M185n
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: E01641EF
     Model ID:      000000000000
     Unit ID:       00000000
          Firmware: RQM 64.00.B0008
     The power switch is located on the base.
     Supports 20 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Firmware RQM 64.00.B0008 4054
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         3: DEVICE NAME            {0005}   
            Name: Wireless Mouse  
            Kind: mouse
         4: RESET                  {0020}   
         5: REPROG CONTROLS V4     {1B04}   
            Key/Button Actions (saved): {'80': 80, '81': 81, '82': 82}
            Key/Button Actions        : {'80': 80, '81': 81, '82': 82}
         6: WIRELESS DEVICE STATUS {1D4B}   
         7: LOWRES WHEEL           {2130}   
            Wheel Reports: HID
            Scroll Wheel HID++ Scrolling (saved): False
            Scroll Wheel HID++ Scrolling        : False
         8: POINTER SPEED          {2205}   
            Pointer Speed: 1.0
            Sensitivity (Pointer Speed) (saved): 256
            Sensitivity (Pointer Speed)        : 256
         9: DEVICE RESET           {1802}   internal, hidden
        10: unknown:1810           {1810}   internal, hidden
        11: unknown:1830           {1830}   internal, hidden
        12: unknown:1850           {1850}   internal, hidden
        13: unknown:1869           {1869}   internal, hidden
        14: unknown:1890           {1890}   internal, hidden
        15: unknown:18B1           {18B1}   internal, hidden
        16: unknown:1DF3           {1DF3}   internal, hidden
        17: unknown:1E00           {1E00}   hidden
        18: unknown:1F03           {1F03}   internal, hidden
        19: unknown:1E80           {1E80}   internal, hidden
     Has 3 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, reprogrammable, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, reprogrammable, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
     Battery status unavailable.
```
</details>

**Describe the bug**
Likely the same problem with https://github.com/pwr-Solaar/Solaar/issues/99. After sometime, `solaar` uses one core of the CPU 90-100% and never stops. Replugging does not work.

**To Reproduce**
1. Open `solaar`
2. Wait for a uncertain time

**Screenshots**
![solaar](https://user-images.githubusercontent.com/29679552/131417767-2ddcc052-ab01-47c5-bc6a-0c490bd2580c.png)

**Additional context**

**Comment by pfps** [comment]
Bug #99 is very old so it is not certain that this is the same bug.

It would be helpful if you could trigger a backtrace to show where Solaar is when it is consuming CPU.    Run Solaar as `solaar -d` from a terminal (after quitting any running Solaar).  Enter control-C when Solaar is consuming CPU.  It make take a few times to pinpoint what is going wrong.

**Comment by pfps** [comment]
Also, does Solaar continue to consume CPU if all Logitech devices are turned off or unplugged?

**Comment by pfps** [comment]
Bug #833 is the closest one, but I thought that it had been solved.

**Comment by validatedev** [comment]
> Also, does Solaar continue to consume CPU if all Logitech devices are turned off or unplugged?

Yes, unplugging or turning off didn’t affect the CPU usage. Will share the traces as soon as I encounter the problem again. Thanks for your interest!

**Comment by validatedev** [comment]
It started to do like that with `solaar -dd`:
[solaar-log1.txt](https://github.com/pwr-Solaar/Solaar/files/7080307/solaar-log1.txt)

**Comment by pfps** [comment]
OK, I see that Solaar is in a loop thinking that the mouse status is changing.  But I'm not sure why.  The output from just before the loop might be useful.  Also what trigger the loop - were you working with the mouse - was the computer resuming from suspend - had the mouse been unused for a while?

I have the same hardware and I'm not seeing the looping.

**Comment by validatedev** [comment]
[solaar-log2.txt](https://github.com/pwr-Solaar/Solaar/files/7082513/solaar-log2.txt)
It's happening after waiting for a time while the mouse is unused. Simply I locked the laptop with CTRL-L in GNOME (not suspending) and went to sleep. Then I unlocked, moved the mouse and that happened. I'm going to try replugging the receiver while debugging and pass the output there.

**Comment by pfps** [comment]
I just reproduced the problem so I should be able to investigate it.  It seems to be #833 again, which I thought was fixed.  On resume from suspend there is some loop condition.

**Comment by validatedev** [comment]
Perfect! Also want to add that I use TLP with `USB_AUTOSUSPEND=1`.  It may work for you. Waiting for a custom build then.

**Comment by pfps** [comment]
When devices change status Solaar tells the UI to redisplay them.  However, there was a bug for devices that do not provide battery status at all where Solaar was telling the UI to redisplay the device when the battery changed from None to None.  Part of the UI redisplay caused the battery information to be re-determined, which then changed the battery to None from None, which caused the loop.

Please try PR #1255.


To download and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1255, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1255/head:pull_1255
git checkout pull_1255
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1255
git fetch origin pull/1255/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
@validatedev Have you had a chance to checkout the PR?

**Comment by eduardo4jesus** [comment]
I am facing the same problem. Was this ever fixed?

![Image](https://github.com/user-attachments/assets/56283a11-41e2-45dc-bd1d-ca8036db6121)

**Comment by eduardo4jesus** [comment]
@pfps

**Comment by pfps** [comment]
I've never seen this happen.  But Solaar 1.1.1 is ancient and you should update to the most recent version.
