### ISSUE TITLE
Question: mouse being recognized as keyboard

### ISSUE THREAD

**Issue by lobomfz** [pwr-Solaar/Solaar#1251]
I apologize if this is not the correct place, if there's anywhere else to get help please let me know.

Recently my logitech g pro wireless receiver stopped working, so i bought some replacement from aliexpress, solaar detects it as a lightspeed receiver as always, and after pairing it shows info such as battery normally just like before and works on the UEFI bios, however it seems to be recognized as a keyboard on kernel logs and it's not working on linux, here's the output of dmesg:

> [  851.064749] usb 3-2: new full-speed USB device number 56 using xhci_hcd
[  851.196358] usb 3-2: New USB device found, idVendor=046d, idProduct=c539, bcdDevice=39.06
[  851.196366] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  851.196369] usb 3-2: Product: USB Receiver
[  851.196371] usb 3-2: Manufacturer: Logitech
[  851.201883] logitech-djreceiver 0003:046D:C539.0079: hidraw0: USB HID v1.11 Keyboard [Logitech USB Receiver] on usb-0000:00:14.0-2/input0
[  851.256854] logitech-djreceiver 0003:046D:C539.007A: unknown main item tag 0x0
[  851.256865] logitech-djreceiver 0003:046D:C539.007A: unknown main item tag 0x0
[  851.256872] logitech-djreceiver 0003:046D:C539.007A: unknown main item tag 0x0
[  851.256879] logitech-djreceiver 0003:046D:C539.007A: unbalanced collection at end of report description
[  851.256893] logitech-djreceiver 0003:046D:C539.007A: logi_dj_probe: parse failed
[  851.256899] logitech-djreceiver: probe of 0003:046D:C539.007A failed with error -22
[  851.259816] logitech-djreceiver 0003:046D:C539.007B: hiddev96,hidraw1: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:00:14.0-2/input2
[  851.313088] logitech-djreceiver 0003:046D:C539.007B: device of type eQUAD Lightspeed 1 (0x0c) connected on slot 1
[  851.318268] input: Logitech G Pro as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.2/0003:046D:C539.007B/0003:046D:4079.007C/input/input54
[  851.318624] logitech-hidpp-device 0003:046D:4079.007C: input,hidraw7: USB HID v1.11 Keyboard [Logitech G Pro] on usb-0000:00:14.0-2/input2:1
[  852.746401] logitech-hidpp-device 0003:046D:4079.007C: HID++ 4.2 device connected.

As i mentioned it does work on the BIOS, this is on a laptop (NP550XDA-KF1BR I believe) which seems to be a bit funky regarding USB. If there's any insight into what the problem may be i'd appreciate some help, thanks.

**Comment by pfps** [comment]
Solaar doesn't get involved at this level.  You might be able to ask whoever is responsible for the logitech-djreceiver driver.
