### ISSUE TITLE
How do you start this thing?

### ISSUE THREAD

**Issue by MalikRumi** [pwr-Solaar/Solaar#1256]
I looked at the instructions on https://pwr-solaar.github.io/Solaar/usage. As you will see below, they don't work. 
2nd, I got this from Ubuntu Software, but it is version 1.01, whereas your github says you are up to 1.06. Is there an update or do I need to manually install the new version - assuming I can make it start, of course. 

malikarumi@Tetuoan2:$ solaar ---window=show
usage: solaar [-h] [-d] [-D PATH] [--restart-on-wake-up] [-V] [--help-actions]
              ...
solaar: error: unrecognized arguments: ---window=show
malikarumi@Tetuoan2:$ solaar -V
solaar 1.0.1
malikarumi@Tetuoan2:$ solaar --help-actions
usage: solaar {show,config,pair,unpair} ...

actions:
  {show,config,pair,unpair}
                        optional action to perform
    show                show information about devices
    config              read/write device-specific settings
    pair                pair a new device
    unpair              unpair a device

For details on individual actions, run `solaar <action> --help`.
malikarumi@Tetuoan2:$ solaar update
usage: solaar {show,config,pair,unpair} ...
solaar: error: invalid choice: 'update' (choose from 'show', 'config', 'pair', 'unpair')
malikarumi@Tetuoan2:$ solaar show
Solaar: error: [Errno 13] Permission denied: '/dev/hidraw0'
malikarumi@Tetuoan2:$ solaar --show
usage: solaar [-h] [-d] [-D PATH] [--restart-on-wake-up] [-V] [--help-actions]
              ...
solaar: error: unrecognized arguments: --show
malikarumi@Tetuoan2:$ solaar -show
usage: solaar [-h] [-d] [-D PATH] [--restart-on-wake-up] [-V] [--help-actions]
              ...
solaar: error: unrecognized arguments: -show
malikarumi@Tetuoan2:$ solaar-show
solaar-show: command not found
malikarumi@Tetuoan2:$ solaar-h
solaar-h: command not found
malikarumi@Tetuoan2:$ solaar -h
usage: solaar [-h] [-d] [-D PATH] [--restart-on-wake-up] [-V] [--help-actions]
              ...

positional arguments:
  {show,config,pair,unpair}
                        optional actions to perform

optional arguments:
  -h, --help            show this help message and exit
  -d, --debug           print logging messages, for debugging purposes (may be
                        repeated for extra verbosity)
  -D PATH, --hidraw PATH
                        unifying receiver to use; the first detected receiver
                        if unspecified. Example: /dev/hidraw2
  --restart-on-wake-up  restart Solaar on sleep wake-up (experimental)
  -V, --version         show program's version number and exit
  --help-actions        print help for the optional actions
malikarumi@Tetuoan2:$ solaar show --help
usage: solaar show [-h] [device]

positional arguments:
  device      device to show information about; may be a device number (1..6),
              a serial, a substring of a device's name, or "all" (the default)

optional arguments:
  -h, --help  show this help message and exit
malikarumi@Tetuoan2:$ solaar show -h
usage: solaar show [-h] [device]

positional arguments:
  device      device to show information about; may be a device number (1..6),
              a serial, a substring of a device's name, or "all" (the default)

optional arguments:
  -h, --help  show this help message and exit
malikarumi@Tetuoan2:$ solaar show -h all
usage: solaar show [-h] [device]

positional arguments:
  device      device to show information about; may be a device number (1..6),
              a serial, a substring of a device's name, or "all" (the default)

optional arguments:
  -h, --help  show this help message and exit

**Comment by pfps** [comment]
Version 1.0.1 is old. Document here is for 1.0.6.  I suggest you install using one of the Ubuntu PPAs as described in https://github.com/pwr-Solaar/Solaar

If all you want to do is to start Solaar you don't need to use any arguments.
