### ISSUE TITLE
config_panel.py:535:_get_failed_spinner_control:AttributeError: 'VBox' object has no attribute '_failed'

### ISSUE THREAD

**Issue by rathann** [pwr-Solaar/Solaar#1263]
**Information**
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): **1.0.6**
- Distribution: **Fedora 34**
- Kernel version (ex. `uname -srmo`): `5.13.13-200.fc34.x86_64`
- Output of `solaar show`:

<details>

```
N/A at this time, will update when original reporter provides it
```
</details>

**Describe the bug**
When clicking unlock/lock "disable keys" for keyboard "mx keys", solaar throws an `AttributeError` exception.

**To Reproduce**
1. Go to Keyboard settings panel.
2. Click on lock/unlock icon for keyboard "mx keys".
3. `AttributeError` exception is thrown.

**Screenshots**
N/A

**Additional context**
This was reported downstream in Fedora bugzilla as bug [#2003483](https://bugzilla.redhat.com/show_bug.cgi?id=2003483).
Python backtrace:
```
config_panel.py:535:_get_failed_spinner_control:AttributeError: 'VBox' object has no attribute '_failed'

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/solaar/ui/config_panel.py", line 382, in _change_click
    _write_async(setting, persisted, control.get_parent())
  File "/usr/lib/python3.9/site-packages/solaar/ui/config_panel.py", line 44, in _write_async
    failed, spinner, control = _get_failed_spinner_control(sbox)
  File "/usr/lib/python3.9/site-packages/solaar/ui/config_panel.py", line 535, in _get_failed_spinner_control
    return sbox._failed, sbox._spinner, sbox._control
AttributeError: 'VBox' object has no attribute '_failed'

Local variables in innermost frame:
sbox: <Gtk.VBox object at 0x7f3f98d64a80 (GtkVBox at 0x559008a74f90)>
```

**Comment by pfps** [comment]
I can reproduce this bug.  Expect a patch soon.

**Comment by pfps** [comment]
PR #1264 should fix this issue.
