### ISSUE TITLE
Not propper working on 3.11 kernel

### ISSUE THREAD

**Issue by madmanidze** [pwr-Solaar/Solaar#127]
Hello,

I using solaar on 3.11.1-031101-generic kernel from http://kernel.ubuntu.com/~kernel-ppa/mainline/v3.11.1-saucy/, and they not working when running first time, no see any devices. But when i run solaar-cli show, i have output:
Unifying Receiver [/dev/hidraw1:0BEF9E00] with 2 devices
1: Wireless Solar Keyboard K750 [K750:71E91FD4]
2: Performance Mouse MX [Performance MX:3897D1E1]
i remove ~/.config/solaar/config.json, then trying start solaar. from 3-4 times - solaar start and see all devices.

Please check.

Thank you.

**Comment by madmanidze** [comment]
Still not working proper :(

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to age and inactivity.
