### ISSUE TITLE
Switch back from android 

### ISSUE THREAD

**Issue by jaroslawZawila** [pwr-Solaar/Solaar#1275]
My use case is very simple I would like to change host from my linux machine to my android tablet. 

It works very well from the linux machine running solaar to the table. But it does not work from the tablet to the solar. 

Do you know if there is the way of achieving that?

- Solaar version (`solaar --version` and `git describe --tags`):
solaar 1.0.6

- Distribution: Manjaro

**Comment by pfps** [comment]
You would need Solaar to run under Android to do that.  When a device is connected to a computer no other computer can talk to the device.

**Comment by pramodhrachuri** [comment]
I doubt if all Android devices will support it. According to the following line, Solaar probably needs kernel 5.2+
https://github.com/pwr-Solaar/Solaar/blob/cfe67d4f30c4707747a792904512b131ec04cf48/ChangeLog#L158
And vendors like Samsung still continue to use 4.x Linux kernel.
