### ISSUE TITLE
solaar setup on ubuntu - systemd vs plugdev group

### ISSUE THREAD

**Issue by chaim1221** [pwr-Solaar/Solaar#1294]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.0.7

- Distribution: Ubuntu 21.10

- Kernel version (ex. `uname -srmo`):  5.13.0-19-generic

- Output of `solaar show`:
```
celiyah@yoda-720:~$ solaar show
Solaar: error: [Errno 13] Permission denied: '/dev/hidraw2'
# `sudo solaar show` lists logi devices
```

**Describe the bug**
```
# dpkg-reconfigure solaar
 │ Please specify how non-root users should be given access to the Logitech    
 │ receiver devices.                                                           
 │                                                                             
 │ If systemd or consolekit are in use, they can apply ACLs to make them       
 │ accessible via Solaar for the user logged in on the current seat. Right     
 │ now, NEITHER daemon is running.    
```
pas...
```
celiyah@yoda-720:~$ ps --no-headers -o comm 1
systemd
celiyah@yoda-720:~$ ps 1
    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:01 /sbin/init splash
celiyah@yoda-720:~$ file /sbin/init 
/sbin/init: symbolic link to /lib/systemd/systemd
```
:yuno:

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by cheshirekow** [comment]
Hi @pfps I'm a first time user here and I just installed solaar on ubuntu 21.10. During the package post-install hook I'm prompted with a pop-up that has the warning indicated in the bug report. I understand the original reporter didn't follow up, so perhaps I can provide additional info. 

Based on the tags, it sounds like perhaps this pop-up comes from a debian or ubuntu maintainer, and is not provided by the solaar project itself? Is that correct? 

FWIW, I ended up here because I wanted to know what the "correct" answer is. I'll try answering "No" because obviously systemd is running and see what happens. 

![Screenshot from 2022-01-22 21-08-17](https://user-images.githubusercontent.com/1309820/150665888-42001b24-f871-4421-859d-0a17f4b02662.png)

**Comment by cheshirekow** [comment]
Ok, for others coming here for the same reason. I answered "No", then started solaar and saw the following:
![Screenshot from 2022-01-22 21-12-53](https://user-images.githubusercontent.com/1309820/150665975-fcf887cb-13a9-492c-82eb-c418a933901b.png)

I unplugged and-replugged as suggested and it detected my receiver and my mouse. So I guess the (a?) correct answer on ubuntu 21.10 is "no".

**Comment by pfps** [comment]
The post-install hook comes from the package.  This is not part of Solaar anymore, and should be changed by the maintainer of the package.  I suspect that the script has an incorrect test for udev presence.

@muzena Can you see what has gone wrong?

**Comment by muzena** [comment]
@cheshirekow 
From where did you install Solaar?

**Comment by cheshirekow** [comment]
@muzena I installed from canonical's apt repository (`apt I stall solaar`). I can let you know which one specifically when I'm back at my computer, but I suspect that was what you were looking for.

**Comment by muzena** [comment]
@cheshirekow 
Try instaii from [PPA](https://launchpad.net/~solaar-unifying/+archive/ubuntu/ppa)

**Comment by pfps** [comment]
@cheshirekow Any updates?

**Comment by thatwill** [comment]
Can confirm the plugdev prompt still appears in the solaar stable ppa for v1.1.1. The prompt appears to be present in a .deb package script located at solaar_1.1.1~ubuntu22.04.1_all.deb\control.tar.zst\.\config

Like you say though, this is down to the package maintainer rather than you however.

**Comment by muzena** [comment]
@thatwill 
sudo dpkg-reconfigure solaar

Use plugdev group?
Yes

**Comment by cheshirekow** [comment]
Same as @thatwill, I enabled the ppa, upgraded solaar and got `1.1.1+git1580-f938d34~ubuntu21.10.1`. Then `sudo dpkg-reconfigure solaar` and I am presented with the prompt again. 

Incidentally, I answered "No" but it works anyway (it seems @muzena  that you are recommending "yes")? FWIW my user is already a member of `plugdev` so if that is what answering "yes" does then that might be why "no" works for me.

**Comment by muzena** [comment]
@cheshirekow 

> my user is already a member of plugdev so if that is what answering "yes" does then that might be why "no" works for me.

Yes

**Comment by pfps** [comment]
Is there anything that needs to be done in Solaar on this?

**Comment by cheshirekow** [comment]
It doesn't sound like there's anything to be done here. You might consider updating the Readme with a note. It looks like I'm not the only one who ended up on GitHub looking for an answer. I think that would be nice, but not necessary.

**Comment by pfps** [comment]
I'll fix up the title of this issue to make it easier to find.
