### ISSUE TITLE
MxMaster 3 thumb/gesture button does it work?

### ISSUE THREAD

**Issue by riekusr** [pwr-Solaar/Solaar#1295]
Hi guys, recently switched from windows to fedora so excuse my lack of knowledge. 

Tried Piper but can't get it to work. Solaar seems to work but I dont really understand the rule editor (yet)

Can't find any videos on YT expaining the basics. So before I start diving in, can I program the tumb with mouse gestures with solaar on fedora? 

I want to use the thumb button and go left/right to switch work spaces. 

I tried these rules to test if the gesture button is responsive and it doesn't do anything, when I set mouse gestures to 'off' in the menu the gesture button works as alt-tab 
![image](https://user-images.githubusercontent.com/34796052/137883561-9311c31a-5750-4d1e-8680-350392545a5b.png)

**Comment by pfps** [comment]
The gesture button turns mouse movements and mouse key presses into notifications that can trigger rules.  I don't think you can combine it with scrolling.

What you can do is to set up rules to trigger on Gesture Button press then move mouse to the right (or up or down or left)  then Gesture Button release.

**Comment by pfps** [comment]
Is this working for you?
