### ISSUE TITLE
Support for m500s mouse

### ISSUE THREAD

**Issue by m500s** [pwr-Solaar/Solaar#1299]
**Information**

- Solaar version 1.0.7
- Distribution: Fedora 34
- Kernel version: Linux 5.14.13-200.fc34.x86_64 x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable):

**Is your feature request related to a problem? Please describe.**
The Logitech m500s mouse is not detected.
**Describe the solution you'd like**
The ability to adjust the dpi primarily, but any other available features would be nice.
**Additional context**
Here is some output based off the information requested in issue 1225. My logitech mx master 2 works fine and was unplugged for this output. The hidraw appears to give the correct rw permissions when the mouse is plugged and unplugged.
```
lsusb
Bus 001 Device 005: ID 046d:c093 Logitech, Inc. Advanced Corded Mouse M500s

ls -l /dev/hidraw*
crw-------. 1 root root 240, 2 Oct 23 13:44 /dev/hidraw2
crw-------. 1 root root 240, 3 Oct 23 13:24 /dev/hidraw3
crw-------. 1 root root 240, 4 Oct 23 13:24 /dev/hidraw4
crw-rw----+ 1 root root 240, 5 Oct 23 14:28 /dev/hidraw5
crw-rw----+ 1 root root 240, 6 Oct 23 14:28 /dev/hidraw6

solaar -dd show
14:38:09,697    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Down"
14:38:09,697    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Up"
14:38:09,698    DEBUG [MainThread] solaar.ui.tray: using AppIndicator3
14:38:09,708    DEBUG [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C093 INTERFACE 0 FILTER 2
14:38:09,709    DEBUG [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C093 INTERFACE 1 FILTER 2
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/solaar/cli/__init__.py", line 203, in run
    raise Exception('No devices found')
Exception: No devices found
```
Please let me know if there is any additional information needed. Thank you.

**Comment by pfps** [comment]
For unknown devices Solaar guesses that the USB interface to use is interface 2.  The M500S appears to not have that interface so it needs to be explicitly listed in descriptors.py.    PR #1301 should have the needed information.

To download and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1301, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1301/head:pull_1301
git checkout pull_1301
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1301
git fetch origin pull/1301/head
git reset --hard FETCH_HEAD
```
