### ISSUE TITLE
Additional models supported

### ISSUE THREAD

**Issue by robhoare** [pwr-Solaar/Solaar#130]
The MK320 keyboard/mouse combo consists of a K330 keyboard, and an M215 mouse.  Both these were found, paired, and work fine with Solaar, thanks for producing such a useful and clear piece of software!  They don't appear to be listed in your compatibility list, yet.

Battery levels work for both items, no function key switch is shown for the K330.

Details:

M215 2nd Gen

Index        : 2
Wireless PID : 401B
Protocol     : HID++ 2.0
Polling rate : 8 ms (125Hz)
Serial       : 606E....
  Firmware   : RQM 27.02.B0028

K330

Index        : 3
Wireless PID : 4016
Protocol     : HID++ 2.0
Polling rate : 20 ms (50Hz)
Serial       : 2451....
  Firmware   : RQK 45.00.B000

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
