### ISSUE TITLE
compute battery remaining percentage from voltage

### ISSUE THREAD

**Issue by Hubro** [pwr-Solaar/Solaar#1303]
**Information**

- Solaar version: `1.0.7rc2.r0.ge82457f`
- Distribution: Arch Linux
- Kernel version: Linux 5.14.14-arch1-1 x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable):

<details>

```
➜ solaar show "G900"
  1: G900 Chaos Spectrum Gaming Mouse
     Device path  : /dev/hidraw16
     WPID         : 4053
     Codename     : G900
     Kind         : mouse
     Protocol     : HID++ 4.2
     Polling rate : 2 ms (500Hz)
     Serial number: 5BFEBB5F
     Model ID:      C08100000000
     Unit ID:       5BFEBB5F
          Firmware: MPM 01.05.B0023
        Bootloader: BOT 20.02.B0020
             Other:
     The power switch is located on the base.
     Supports 25 HID++ 2.0 features:
         0: ROOT                   {0000}
         1: FEATURE SET            {0001}
         2: DEVICE FW VERSION      {0003}
            Firmware: Firmware MPM 01.05.B0023 C081
            Firmware: Bootloader BOT 20.02.B0020 AABA
            Firmware: Other
            Unit ID: 5BFEBB5F  Model ID: C08100000000  Transport IDs: {'usbid': 'C081'}
         3: DEVICE NAME            {0005}
            Name: Gaming Mouse G900
            Kind: mouse
         4: BATTERY VOLTAGE        {1001}
            Battery: 4158mV, discharging, average.
         5: unknown:1863           {1863}   internal, hidden
         6: unknown:18A1           {18A1}   internal, hidden
         7: unknown:1E00           {1E00}   hidden
         8: unknown:1E20           {1E20}
         9: unknown:1EB0           {1EB0}   internal, hidden
        10: ADJUSTABLE DPI         {2201}
            Sensitivity (DPI) (saved): 1000
            Sensitivity (DPI)        : 1000
        11: ANGLE SNAPPING         {2230}
        12: SURFACE TUNING         {2240}
        13: REPORT RATE            {8060}
            Polling Rate (ms): 2
            Polling Rate (ms) (saved): 2
            Polling Rate (ms)        : 2
        14: ONBOARD PROFILES       {8100}
            Device Mode: Host
        15: MOUSE BUTTON SPY       {8110}
        16: unknown:1850           {1850}   internal, hidden
        17: DFUCONTROL SIGNED      {00C2}
        18: unknown:1801           {1801}   internal, hidden
        19: DEVICE RESET           {1802}   internal, hidden
        20: unknown:1890           {1890}   internal, hidden
        21: unknown:1811           {1811}   internal, hidden
        22: LATENCY MONITORING     {8111}
        23: COLOR LED EFFECTS      {8070}
        24: LED CONTROL            {1300}
     Battery: 4158mV, discharging, average.
```

```
➜ solaar show "G915 TKL"
  1: G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard
     Device path  : None
     WPID         : 408E
     Codename     : G915 TKL
     Kind         : keyboard
     Protocol     : HID++ 4.2
     Polling rate : 1 ms (1000Hz)
     Serial number: E39C9BCF
     Model ID:      B35F408EC343
     Unit ID:       E39C9BCF
        Bootloader: BL1 12.00.B0017
             Other:
          Firmware: MPK 14.00.B0017
             Other:
             Other:
     The power switch is located on the top left corner.
     Supports 38 HID++ 2.0 features:
         0: ROOT                   {0000}
         1: FEATURE SET            {0001}
         2: DEVICE FW VERSION      {0003}
            Firmware: Bootloader BL1 12.00.B0017 00008B79E978
            Firmware: Other
            Firmware: Firmware MPK 14.00.B0017 408E8B79E978
            Firmware: Other
            Firmware: Other
            Unit ID: E39C9BCF  Model ID: B35F408EC343  Transport IDs: {'btleid': 'B35F', 'wpid': '408E', 'usbid': 'C343'}
         3: DEVICE NAME            {0005}
            Name: G915 TKL LIGHTSPEED Wireless RGB Mechanical Gaming Keyboard
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}
         5: RESET                  {0020}
         6: DEVICE FRIENDLY NAME   {0007}
            Friendly Name: G915 TKL
         7: BATTERY VOLTAGE        {1001}
            Battery: 4174mV, discharging, average.
         8: CHANGE HOST            {1814}
            Change Host        : 1:aura
         9: HOSTS INFO             {1815}
            Host 0 (paired): aura
            Host 1 (unpaired):
        10: RGB EFFECTS            {8071}
        11: PER KEY LIGHTING V2    {8081}
        12: REPROG CONTROLS V4     {1B04}
        13: REPORT HID USAGE       {1BC0}
        14: ENCRYPTION             {4100}
        15: KEYBOARD DISABLE BY USAGE {4522}
        16: KEYBOARD LAYOUT 2      {4540}
        17: GKEY                   {8010}
            Divert G Keys (saved): False
            Divert G Keys        : False
        18: MKEYS                  {8020}
        19: MR                     {8030}
        20: BRIGHTNESS CONTROL     {8040}
        21: ONBOARD PROFILES       {8100}
            Device Mode: On-Board
        22: REPORT RATE            {8060}
            Polling Rate (ms): 1
        23: DFUCONTROL SIGNED      {00C2}
        24: DFU                    {00D0}
        25: DEVICE RESET           {1802}   internal, hidden
        26: unknown:1803           {1803}   internal, hidden
        27: CONFIG DEVICE PROPS    {1806}   internal, hidden
        28: unknown:1813           {1813}   internal, hidden
        29: OOBSTATE               {1805}   internal, hidden
        30: unknown:1830           {1830}   internal, hidden
        31: unknown:1890           {1890}   internal, hidden
        32: unknown:1891           {1891}   internal, hidden
        33: unknown:18A1           {18A1}   internal, hidden
        34: unknown:1E00           {1E00}   hidden
        35: unknown:1EB0           {1EB0}   internal, hidden
        36: unknown:1861           {1861}   internal, hidden
        37: unknown:18B0           {18B0}   internal, hidden
     Has 2 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1
             divertable, persistently divertable, pos:1, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2
             divertable, persistently divertable, pos:2, group:0, group mask:empty
             reporting: default
     Battery: 4174mV, discharging, average.
```
</details>

**Is your feature request related to a problem? Please describe.**

I have a gaming mouse and keyboard from Logitech, G900 and G915 TKL respectively. Their battery level is reported in "mV", which doesn't really tell me anything about how long I should expect to be able to use the device before I have to charge it.

**Describe the solution you'd like**

I would love it if it was possible to display their estimated battery percentage instead.

**Describe alternatives you've considered**

I have read the README file, I've read the `--help` output and I've looked through the existing issues, and I haven't found any mention of "mV" 🤷

**Additional context**

Screenshot:

![image](https://user-images.githubusercontent.com/597206/138719920-ceb8c613-695d-4038-a2de-487c06d9fabd.png)

**Comment by pfps** [comment]
I have a table showing voltage to capacity for the battery in some Logitech device.  I'll put together a PR for this change.  Can you test it out on your devices to determine whether the mapping makes sense?

**Comment by pfps** [comment]
PR #1379 should display percentages (mostly rounded to tenths) as well as or instead of the voltage.  Give it a try and see whether this works for you.


To download and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1379, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1379/head:pull_1379
git checkout pull_1379
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1379
git fetch origin pull/1379/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
@Hubro Can you check out PR #1379?

**Comment by Hubro** [comment]
@pfps I've installed the patch now, and it seems to be working fine:

![image](https://user-images.githubusercontent.com/597206/146792083-45518cb0-65ac-4c7f-a1ba-8b861b5bfcdc.png)

How accurate are you expecting the percentages to be? I don't know much about how battery voltages correlate to charge, or how that changes when the battery gets older.

Should I expect that my mouse might die at 30%?

**Comment by pfps** [comment]
The battery information I have is for a particular battery but it does seem that at least the upper end is close to what the battery on my mouse does.   If you are running a power manager you should be able to see battery information on it.  On my system power manager shows 96% while Solaar shows 90%.  I made the decision to show only deciles, as the main reason for computing this is to give users an idea of when to recharge their mice.

I don't know how accurate the low end is.   I'm going to try running my G502 mouse down and try to check the low end with it.  I expect that the very low end - under 10% - might not be very accurate, but I think 30% should be safe.

**Comment by pfps** [comment]
I'm probably going to put out a new version of Solaar in a few days.  Hopefully I'll have some good calibration by then, but I think the information is good enough for now.

**Comment by Hubro** [comment]
Battery percentage is completely on point on the G900 Chaos Spectrum :+1: 

The battery on the G915 TKL keyboard lasts a lot longer so I'm still waiting :smile:

**Comment by Hubro** [comment]
The percentages were not as accurate for the G915 TKL keyboard. The battery percentage reached "0%" at around 3577 mV (although it could have been sooner and I simply missed it), but the keyboard kept trucking until around 3436 mV, which was several hours of intense gaming later.

![image](https://user-images.githubusercontent.com/597206/147479808-f8ce4184-90c1-4223-b076-0baf8d95d24e.png)

![image](https://user-images.githubusercontent.com/597206/147479813-2304b17e-7ea2-4bf1-8e79-8fb47670d16c.png)

![image](https://user-images.githubusercontent.com/597206/147479818-b557cd9e-2d24-426d-ac4e-f0067f5e96a2.png)

Still though, way better than nothing!

**Comment by pfps** [comment]
Each battery is likely different, and different models of batteries are certainly different.  I don't think that much more than this can be done without actually recording timings between voltages, and even these are likely to change as the battery ages.

**Comment by Hubro** [comment]
> Each battery is likely different, and different models of batteries are certainly different. I don't think that much more than this can be done without actually recording timings between voltages, and even these are likely to change as the battery ages.

Well, likely Logitech has a mapping of voltages to battery percentages for each model of battery. If you had that, the battery percentage displayed in Solaar would likely be just as accurate as the one in their own software 😄 I doubt they've bothered making their software advanced enough to track the min/max voltages of each individual battery and learning from them over time.

I assume those mappings aren't publicly available though. Would it be possible to extract them from the official software?

**Comment by pfps** [comment]
If someone wants to go through the executable of the Logitech software and post results then it may be possible to add the information to Solaar.
