### ISSUE TITLE
support Logitech Bolt receivers

### ISSUE THREAD

**Issue by pfps** [pwr-Solaar/Solaar#1315]
Logitech has a new receiver and devices that connect to it.   The Bolt receiver behaves differently than the Unifying receiver, particularly when pairing and unpairing.  Solaar should support this receiver.

**Comment by pfps** [comment]
PR #1316 supports Bolt receivers except for pairing and unpairing.

**Comment by pfps** [comment]
If anyone has a Bolt receiver and would like to test it in Solaar, please reply here.

**Comment by luca-martino** [comment]
> If anyone has a Bolt receiver and would like to test it in Solaar, please reply here.

Here I'm ... Bolt receiver ready.

OS: Fedora release 34 (Thirty Four) x86_64 
Kernel: 5.14.16-201.fc34.x86_64
Host: HP 350 G2
Solaar: 1.0.7

**Comment by pfps** [comment]
If you download and run PR #1316 Solaar should show Bolt receivers and devices connected to them and manipulate their settings.  Testing this part of the PR should be safe.  Solaar should also be able to unpair and pair devices connected to Bolt receivers.  Testing this part of the PR isn't quite safe because if you unpair and can't pair again the device might only work on Bluetooth.  Bolt pairing is quite similar to Bluetooth pairing - you start the Bolt receiver pairing using Solaar, then you press a pairing button on the device, then you authenticate the device by entering some digits or clicking some buttons matching a prompt given by Solaar, and if this is done correctly the device pairs with the Bolt receiver.


To download and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1316, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1316/head:pull_1316
git checkout pull_1316
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1316
git fetch origin pull/1316/head
git reset --hard FETCH_HEAD
```

**Comment by luca-martino** [comment]
> bin/solaar

![immagine](https://user-images.githubusercontent.com/17565704/141152746-b49e0bfe-1880-4be1-835b-5ea86c6fb654.png)

**Comment by pfps** [comment]
That looks as I expected, and matches what I see for my MX Keys for Business.  Do you think that anything that is showing is incorrect?

**Comment by pfps** [comment]
Could you try with the `-d` switch and see if there are any warnings shown?

**Comment by luca-martino** [comment]
> That looks as I expected, and matches what I see for my MX Keys for Business. Do you think that anything that is showing is incorrect?
Missing serial number, firmware, etc
![immagine](https://user-images.githubusercontent.com/17565704/141157032-3bea8c38-097a-4975-b021-7f8f0afb1a2f.png)

**Comment by luca-martino** [comment]
> Could you try with the `-d` switch and see if there are any warnings shown?

![immagine](https://user-images.githubusercontent.com/17565704/141157601-277cc770-4bb9-4e67-9b62-2ae1ea6b6025.png)

**Comment by pfps** [comment]
Bolt receivers are different from Unifying receivers and don't have serial numbers and their firmware is identified differently so this change is acceptable, I think.

**Comment by dulex123** [comment]
I just get Found a Logitech Receiver (/dev/hidraw1) but did not have the permission to open it. If you've just installed Solaar, try removing the receiver and plugging it back in.

I have tried re-inserting it but it shows the same message. Thoughts?

**Comment by pfps** [comment]
Solaar needs permissions to send commands to the receiver.  This is done using a udev file that adds access control lists to Unifying receivers and devices.  To see what is going on, run `ls -l /dev/hidraw*`.  The entry for /dev/hidraw1 should have a + after the permissions bits.  if not either the udev rule is not installed or udev is not running.  The usual location for the udev rule is /etc/udev/rules.d/42-logitech-unify-permissions.rules so you can check for the presence of this rule.

**Comment by pfps** [comment]
Also, if you were running an old version of Solaar the udev rule might not trigger on Bolt receivers so you might need to update the rule.

**Comment by dulex123** [comment]
@pfps Is this a required manual step on Ubuntu?

**Comment by pfps** [comment]
If you install Solaar from the Ubuntu git PPA then the udev rule will be automatically installed.  Otherwise you can follow the instructions in https://pwr-solaar.github.io/Solaar/installation under `Installing Solaar's udev rule`, once you have a cloned copy of Solaar.

**Comment by dulex123** [comment]
@pfps thanks!
