### ISSUE TITLE
About box hidden by main window

### ISSUE THREAD

**Issue by genright** [pwr-Solaar/Solaar#132]
I'm running solaar 0.9.2, under kubuntu 12.04

When the main solaar window is open, I can click the about button. But nothing seems to happen. 

Moving the main window reveals the about box hiding behind it. I am unable to raise that above the main window.

Looks like a line in lib/solaar/ui/window.py that forces it to be on top, perhaps that is not the best way?

``` python
def _create():
    ...
    window.set_keep_above(True)
```

I'm not seeing any special reason the main window _has_ to be the top window. If there is, the about button should behave differently or not be there.

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
I think this behaviour occurs because the solaar window is created as a keep-above window.  I have an issue https://github.com/pwr-Solaar/Solaar/issues/617 and pull request https://github.com/pwr-Solaar/Solaar/pull/618

**Comment by pfps** [comment]
Should be fixed by #618, closing.  If the problem persists, please reopen this issue.
