### ISSUE TITLE
PPA Linux Mint 20 (Ubuntu Focal)

### ISSUE THREAD

**Issue by Timu57** [pwr-Solaar/Solaar#1321]
**Describe the bug**
After adding the PPA Stable (Same error occurs with the git ppa) I get the following error when updating with apt.

I tried my best to translate the error.
```
Error:22 http://ppa.launchpad.net/solaar-unifying/stable/ubuntu focal InRelease
  The following signature could not be verified, because the public key is not available: NO_PUBKEY 2303D595EE907473

W: GPG-Error: http://ppa.launchpad.net/solaar-unifying/stable/ubuntu focal InRelease: The following signature could not be verified, because the public key is not available: NO_PUBKEY 2303D595EE907473
E: The depot »http://ppa.launchpad.net/solaar-unifying/stable/ubuntu focal InRelease« is not signed.
N: Updates from such depots can not be done in a secure way, that's why it's deactivated by default.
```

**To Reproduce**
1. Execute `sudo add-apt-repository ppa:solaar-unifying/stable` on Linux Mint 20
2. Execute `sudo apt-get update`

**Screenshots**
![Bildschirmfoto vom 2021-11-13 04-30-34](https://user-images.githubusercontent.com/28825283/141604148-1756194e-342a-4254-af32-d7048bd328c3.png)

It would be awesome if someone could help me.

**Comment by pfps** [comment]
@muzena Any ideas about what is going on here?

**Comment by pfps** [comment]
It looks to me as if you need to set some flag to allow unsigned depots.

**Comment by Timu57** [comment]
I tried the following:
Using the following commands like described in https://superuser.com/a/1331948:

```
sudo apt update --allow-unauthenticated
```
```
sudo apt update --allow-insecure-repositories
```

Both commands result in the same error as above.

I also tried to update the /etc/apt/sources.list file like so:
```
deb [trusted=yes] http://ppa.launchpad.net/solaar-unifying/stable/ubuntu focal main
deb-src [trusted=yes] http://ppa.launchpad.net/solaar-unifying/stable/ubuntu focal main
```
After executing `sudo apt update` I get the following error/warning:
```
W: GPG-Error: http://ppa.launchpad.net/solaar-unifying/stable/ubuntu focal InRelease: The following signature could not be verified, because your public key is not available: NO_PUBKEY 2303D595EE907473
```
![Bildschirmfoto vom 2021-11-13 04-57-19](https://user-images.githubusercontent.com/28825283/141604810-88651ba9-0180-477e-a1a9-0c9728d1ec99.png)

**Comment by muzena** [comment]
@Timu57 
I don't know why this happened, I don't have such problem.
Try to import PPA key manully from terminal:

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 643FF34AF9151DC814DD3A1B2303D595EE907473`

`sudo apt update`

**Comment by Timu57** [comment]
Hi @muzena 
After executing the following command:
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 643FF34AF9151DC814DD3A1B2303D595EE907473
```
I get the following errors:
```
Executing: /tmp/apt-key-gpghome.1fVBc3wr8L/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 643FF34AF9151DC814DD3A1B2303D595EE907473
gpg: Key 2303D595EE907473: Public Key "Launchpad PPA for Solaar" imported
gpg: Total number of keys processed: 1
gpg:               imported: 1
gpg: invalid key resource URL '/tmp/apt-key-gpghome.1fVBc3wr8L/home:manuelschneid3r.asc.gpg'
gpg: Key block tools `(null)': General Error
gpg: key 1488EB46E192A257: 1 Authentication not checked due to missing key
gpg: key 7721F63BD38B4796: 2 Authentication not checked due to missing key
gpg: key 1488EB46E192A257: 1 Authentication not checked due to missing key
gpg: key A6616109451BBBF2: 12 Authentication not checked due to missing key
gpg: key 3B4FE6ACC0B21F32: 3 Authentication not checked due to missing key
gpg: key D94AA3F0EFE21092: 3 Authentication not checked due to missing key
gpg: key C8CAB6595FDFF622: 2 Authentication not checked due to missing key
gpg: key 871920D1991BC93C: 1 Authentication not checked due to missing key
gpg: Total number of keys processed: 19
gpg:       ignored new keys: 19
```

When I now add the ppa with:
```
sudo add-apt-repository ppa:solaar-unifying/stable
```

I get the following message:
```
Executing: /tmp/apt-key-gpghome.ZXDhmWmNH2/gpg.1.sh --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys 643FF34AF9151DC814DD3A1B2303D595EE907473
gpg: Key 2303D595EE907473: Public key "Launchpad PPA for Solaar" imported
gpg: Total number of keys processed: 1
gpg:               imported: 1
gpg: invalid key resource URL '/tmp/apt-key-gpghome.ZXDhmWmNH2/home:manuelschneid3r.asc.gpg'
gpg: Key block tools`(null)': General error
gpg: key 1488EB46E192A257: 1 Authentication not checked due to missing key
gpg: key 7721F63BD38B4796: 2 Authentication not checked due to missing key
gpg: key 1488EB46E192A257: 1 Authentication not checked due to missing key
gpg: key A6616109451BBBF2: 12 Authentication not checked due to missing key
gpg: key 3B4FE6ACC0B21F32: 3 Authentication not checked due to missing key
gpg: key D94AA3F0EFE21092: 3 Authentication not checked due to missing key
gpg: key C8CAB6595FDFF622: 2 Authentication not checked due to missing key
gpg: key 871920D1991BC93C: 1 Authentication not checked due to missing key
gpg: Total number of keys processed: 19
gpg:       ignored new keys: 19
```

And `sudo apt-get update` throws the same error as before:

```
Error:21 http://ppa.launchpad.net/solaar-unifying/stable/ubuntu focal InRelease
  The following signature could not be checked, because the public key is not available: NO_PUBKEY 2303D595EE907473

W: GPG-Error: http://ppa.launchpad.net/solaar-unifying/stable/ubuntu focal InRelease: The following signature could not be checked, because the public key is not available: NO_PUBKEY 2303D595EE907473
E: The Depot »http://ppa.launchpad.net/solaar-unifying/stable/ubuntu focal InRelease« is not signed.
N: Updates from such depots can not be done in a save way, that's why it is deactivated by default.
```

**Comment by Timu57** [comment]
Hi
Thank you for your time and afford for trying to fix my problem.
I also thank you for this awesome project. Keep up the great work :blush: 

I managed to fix the problem.
It seems like something was wrong with my apt trusted .asc files.

In more than seven years of using linux as my main operating system I hadn't had such problems :roll_eyes: 

After I deleted a file within the `/etc/apt/trusted.gpg.d/` folder, everything works fine now.

I got the hint here: https://unix.stackexchange.com/a/595462

I am not sure why I had this issue but to fix the problem I needed to execute the following command:

```
sudo rm /etc/apt/trusted.gpg.d/home\:manuelschneid3r.asc
```

**Comment by muzena** [comment]
@Timu57 
This is not problem in Solaar or PPA repository, you have some problem in your system key managment.
You have in Linux Mint in Update manager -> Software Sources -> Maintenance -> Add missing keys option
OR
Update manager -> Software Sources -> Authentication keys -> Import, option for manually importing keys
OR
Install this [deb file](https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8/+files/launchpad-getkeys_0.3.3-1~webupd8~2_all.deb) and start from terminal:

`sudo launchpad-getkeys`
