### ISSUE TITLE
Allow direct device configuration changes through action in rules

### ISSUE THREAD

**Issue by stlhrt** [pwr-Solaar/Solaar#1327]
**Information**
- Solaar version: 1.0.7
- Distribution: Mint & Pop!_OS
- Kernel version: 5.4.0 & 5.13.0
- Output of `solaar show` for the target device (if applicable): N/A

**Is your feature request related to a problem? Please describe.**
Binding config changes is only possible through binding key press to execution of Solaar cli, which requires spawning new processes etc. while could be handled internally within the diversions engine.

**Describe the solution you'd like**
Add new action type Config, which would act just like command line and maybe allow choosing device to act on and config option to change from dropdown.

**Comment by pfps** [comment]
This is probably going to require some work.

**Comment by pfps** [comment]
The GUI editor for this action should require that the setting name be acceptable.  It would even be better to have the possible names be the GUI names, which would require even more work.

The device names should not be as free as in the CLI.  Probably the only possibilities should be a full device name or a device serial number.  If device names are allowed, though, what if there are two devices with the same name?

There is also a potential problem with setting keys and subkeys.  How can these be validated?  Is it even possible to validate them?

**Comment by pfps** [comment]
PR #1410 is an initial implementation of the Set rule action, which allows modifying device settings directly.  
All kinds of settings are supported except gesture parameters.  The modified setting is written to config.json.  The modified setting shows up in the Solaar main window.  There is no GUI for these actions as of yet.  There is no documentation as of yet.  Set actions take the serial number or unit ID of a device (which can be found in the details pane in the Solaar main window), or null for the device that generated the notification followed by the internal name of a setting (which can be found from `solaar config <device>`).  For simple settings there is one extra argument which is the new value (or `~` to toggle a boolean setting).  For keyed settings there are two extra arguments - the key and the value.  If the key of a keyed setting is a key or button then the Logitech name of the key is used, as shown in the Solaar main window.  If the key of a keyed setting is a gesture, then the internal name of the gesture is used (which can be found in the GESTURE2_GESTURES_LABELS structure in lib/logitech_receiver/settings_templates).

Please test out this PR by modifying your ~/.config/solaar/rules.yaml file.  Here is what I am using for testing:
```
---
- Key: [Brightness Down, pressed]
- Execute: [notify-send, HI]
- Set: [null, backlight, '~']
- Set: [944BBC72, fn-swap, false]
- Set: [944BBC72, disable-keyboard-keys, 'Caps Lock', true]
- Set: [944BBC72, gesture2-gestures, Tap1Finger, true]
- Set: [944BBC72, gesture2-gestures, DoubleTap1Finger, false]
- Set: [944BBC72, gesture2-gestures, DoubleTap1FingerX, false]
- Set: [944BBC72, gesture2-gestures, DoubleTap1Finger, falseX]
- Set: [944BBC72, backlightX, false]
- Set: [43DAF041, backlight, false]
- Set: [43DAF041, backlightX, false]
- Set: [43DAF041, backlight, 3]
- Set: [43DAF041, multiplatform, MacOS]
- Set: [43DAF041, multiplatform, MacOSX]
- Set: [43DAF041, divert-keys, 'Backlight Up', 'Diverted']
- Set: [43DAF041, divert-keys, 'Backlight UpX', 'Diverted']
- Set: [43DAF041, divert-keys, 'Backlight Up', 'DivertedX']
- Set: [43DAF041, divert-keys, 226, 1]
- Set: [43DAF041, disable-keyboard-keys, 'Caps LockY', true]
- Set: [43DAF041, disable-keyboard-keys, 'Caps LockX', true]
- Set: [43DAF041, disable-keyboard-keys, 'Caps Lock', 3]
- Set: [198E3EB8, hires-smooth-invert, true]
- Set: [198E3EB8, smart-shift, 27]
- Set: [198E3EB8, smart-shift, 99]
- Set: [198E3EB8, dpi, 1800]
- Set: [198E3EB8, dpi, 1801]
- Set: [944BBC72, gesture2-params, ScaleFactor, 55] # can't set gesture parameters
- Execute: [notify-send, BYE]
...
```

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1410, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1410/head:pull_1410
git checkout pull_1410
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1410
git fetch origin pull/1410/head
git reset --hard FETCH_HEAD
```
