### ISSUE TITLE
Solaar is empty

### ISSUE THREAD

**Issue by Penguinz-777** [pwr-Solaar/Solaar#1346]
Hello, I'm new to linux and I am running solaar on Debian 10, and solaar is empty and it can't detect my device, when I run solaar -d it says
/usr/share/solaar/lib/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
16:35:08,403     INFO [MainThread] root: language en_US (UTF-8), translations path None
16:35:08,413     INFO [MainThread] solaar.ui: application /io/github/pwr/solaar, registered True
solaar: error: already running

**Comment by pfps** [comment]
Which version of Solaar are you running?  To find out type `solaar --version`.

You should also provide the other information requested for Solaar bug reports.

**Comment by Penguinz-777** [comment]
version 0.9.2

**Comment by Penguinz-777** [comment]
Sorry, my version is too old let me update it.

**Comment by Penguinz-777** [comment]
I can't seem to update it says it is on the newest version.

**Comment by pfps** [comment]
Please read https://github.com/pwr-Solaar/Solaar on how to install a newer version of Solaar on Ubuntu-based systems.

**Comment by pfps** [comment]
Closed because of use of ancient version of Solaar.
