### ISSUE TITLE
Solaar gui fails to load on first invocation, but not second

### ISSUE THREAD

**Issue by Brian-K-Smith** [pwr-Solaar/Solaar#135]
The first time I start solaar it fails to load with this stack trace and hangs:

```
brian@splap066:~$ uname -a
Linux splap066 3.2.0-55-generic #85-Ubuntu SMP Wed Oct 2 12:29:27 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
brian@splap066:~$ solaar --version
solaar 0.9.2
brian@splap066:~$ solaar
Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/ui/__init__.py", line 176, in _status_changed
    window.update(device, need_popup)
  File "/usr/share/solaar/lib/solaar/ui/window.py", line 780, in update
    _model.set_value(item, _COLUMN.STATUS_ICON, 'network-wireless' if is_pairing else None)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 1237, in set_value
    Gtk.TreeStore.set_value(self, treeiter, column, value)
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
TypeError: Argument 3 does not allow None as a value
Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/ui/__init__.py", line 176, in _status_changed
    window.update(device, need_popup)
  File "/usr/share/solaar/lib/solaar/ui/window.py", line 780, in update
    _model.set_value(item, _COLUMN.STATUS_ICON, 'network-wireless' if is_pairing else None)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 1237, in set_value
    Gtk.TreeStore.set_value(self, treeiter, column, value)
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
TypeError: Argument 3 does not allow None as a value
```

If I run it again from a new terminal, I get:

```
brian@splap066:~$ solaar
solaar: error: already running
```

![image](https://f.cloud.github.com/assets/5714685/1383622/946ce3a6-3b40-11e3-9bcc-70b71f68a36f.png)

I think this instance is missing the ability to configure the device?

**Comment by sitilge** [comment]
Same problem here. `uname -r  => 4.8.13-1-ARCH` solaar -v 0.9.2'

**Comment by Lekensteyn** [comment]
@sitilge That warning should have been fixed long time ago. Can you try the version from git master (solaar-git package in AUR)?

**Comment by sitilge** [comment]
@Lekensteyn 

Sending the output
`
/usr/lib/python3.6/site-packages/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
/usr/lib/python3.6/site-packages/solaar/ui/notify.py:33: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
`

**Comment by Petross404** [comment]
Same problem (?) here too. When first run, only the applet is shown. I don't know it is a bug or a feature, kinda got used to it.

**Comment by sitilge** [comment]
@Petross404 I'm not even getting the window.

**Comment by gpborges** [comment]
Also seeing an error here on RHEL 7.3. I safisfied all dependencies, installed the udev rule and trying to launch it but don't get any window:

```
$ uname -a 
Linux gpborges.br.ibm.com 3.10.0-514.16.1.el7.x86_64 #1 SMP Fri Mar 10 13:12:32 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ solaar --version

(solaar:21980): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1985:23: Missing name of pseudo-class

(solaar:21980): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3304:8: Missing name of pseudo-class

(solaar:21980): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3308:8: Missing name of pseudo-class

(solaar:21980): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3311:8: Missing name of pseudo-class

(solaar:21980): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:3315:8: Missing name of pseudo-class
solaar 0.9.2


```

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from submitter.

**Comment by karanvivekbhargava** [comment]
I faced this issue on 18.04 LTS with the apt install of solar.
Resolved it by running it as @pfps suggested above by cloning the git repo `git clone https://github.com/pwr-Solaar/Solaar.git ~/Solaar`
Then running the solaar application with `~/Solaar/bin/solaar`. You may have to resolve some python dependencies like `psutil`.
Just keep pip installing the packages with `python3 -m pip install <package_name>` till solaar runs correctly.
Hope this helps. Thanks for developing this tool! :)

**Comment by pfps** [comment]
You could probably also use pip to install Solaar itself, as mentioned in the Solaar installation document.

**Comment by Lew-Rockwell-Fan** [comment]
18.04 here also.  I just wrapped solaar in a script:
#!/bin/dash

# work-around for bug in solaar. The first instance won't show the gui but if you call it again while it is already running, it will.

nohup solaar &
sleep 1
solaar

# But that leaves a the first process behind. So, we wait for the window to close.
while [ "$(wmctrl -l|grep " Solaar$")" != '' ]; do
	sleep 1
done
# Then kill it.
killall solaar

# A ten year old bug. Lame, Ubuntu. Seriously.
