### ISSUE TITLE
'No changes allowed'

### ISSUE THREAD

**Issue by atomic-ozzy-original** [pwr-Solaar/Solaar#1355]
**Information**
Latest Version (Official)
Manjaro GNOME
Logitech MX Master 1

<details>
Solaar tells me that there are no changes allowed, not sure if this is a bug, but the program also worked fine for me on Pop! OS GNOME
</details>

**Comment by pfps** [comment]
More information is needed.  What were you trying to do?  A screenshot would be useful.

**Comment by atomic-ozzy-original** [comment]
Oh, I've figured it out, I just double clicked the padlock icons aside the options and it worked. I don't know what this strange behavior is since this has worked perfectly fine on other distros and I have not encountered this issue. Anyway, here is a screenshot before me clicking the padlocks twice. If you can then please explain why this happened because I'm interested.
![image](https://user-images.githubusercontent.com/74189145/144296847-0c29282e-0437-4f1c-a205-f96922e27480.png)

**Comment by pfps** [comment]
The locking behaviour is a recent addition to Solaar, added so that users don't accidentally change settings that they don't want to.
