### ISSUE TITLE
Does not work on certain distros?

### ISSUE THREAD

**Issue by atomic-ozzy-original** [pwr-Solaar/Solaar#1356]
**Information**
Latest Solar Version
Linux Mint

<details>
I have installed mint multiple times now and solaar just will not work but every time I've installed pop os it has.
</details>

**Describe the bug**
Solaar will not detect any devices on certain distros.

**Comment by pfps** [comment]
How did you install Solaar?  The debug output from Solaar (`solaar -dd`) would help determine what is going wrong.

**Comment by atomic-ozzy-original** [comment]
> How did you install Solaar? The debug output from Solaar (`solaar -dd`) would help determine what is going wrong.

I installed it via the command line with pacman. How do I get the debug output?

**Comment by atomic-ozzy-original** [comment]
> How did you install Solaar? The debug output from Solaar (`solaar -dd`) would help determine what is going wrong.

I installed on it on mint with the terminal with apt install.

**Comment by atomic-ozzy-original** [comment]
Also, how do I find the debug output?

**Comment by pfps** [comment]
If you installed from the Ubuntu/Mint repository you likely have a very old version.  Use one of the PPAs listed in https://github.com/pwr-Solaar/Solaar

You can run Solaar from the command line and running it as `solaar -dd` should produce lots of debugging output.  You do, however, need to quit any running Solaar before doing this.

**Comment by pfps** [comment]
Closing due to no response from submitter.
