### ISSUE TITLE
Logitech dongle not detected

### ISSUE THREAD

**Issue by cnxsoft** [pwr-Solaar/Solaar#1360]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 
 solaar 1.1.0
- Distribution: Ubuntu 21.04.3 LTS
- Kernel version (ex. `uname -srmo`): `Linux 5.11.0-41-generic x86_64 GNU/Linux`
- Output of `solaar show`:
With new Logitech dongle:

solaar show
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 200, in run
    raise Exception('No devices found')
Exception: No devices found

With old Logitech dongle:
 solaar show
Nano Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:C534
  Serial       : None
    Firmware   : 29.00.B0015
  Has 2 paired device(s) out of a maximum of 2.
  Has 13 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)

  1: Wireless Keyboard MK270
     Device path  : /dev/hidraw4
     WPID         : 4023
     Codename     : MK270
     Kind         : keyboard
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: 72EC039D
     Model ID:      000000000000
     Unit ID:       00000000
          Firmware: RQK 49.00.B0029
     Supports 18 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Firmware RQK 49.00.B0029 4023
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         3: DEVICE NAME            {0005}   
            Name: Wireless Keyboard  
            Kind: keyboard
         4: BATTERY STATUS         {1000}   
            Battery: 30%, discharging, next level 5%.
         5: REPROG CONTROLS        {1B00}   
         6: WIRELESS DEVICE STATUS {1D4B}   
         7: FN INVERSION           {40A0}   
            Swap Fx function (saved): False
            Swap Fx function        : False
         8: ENCRYPTION             {4100}   
         9: KEYBOARD LAYOUT        {4520}   
        10: unknown:1810           {1810}   internal, hidden
        11: unknown:1830           {1830}   internal, hidden
        12: unknown:1890           {1890}   internal, hidden
        13: unknown:18A0           {18A0}   internal, hidden
        14: unknown:18B0           {18B0}   internal, hidden
        15: unknown:1DF3           {1DF3}   internal, hidden
        16: unknown:1E00           {1E00}   hidden
        17: unknown:1868           {1868}   internal, hidden
     Has 11 reprogrammable keys:
         0: My Home                    => HomePage                      is FN, FN sensitive, reprogrammable
         1: Mail                       => Email                         is FN, FN sensitive, reprogrammable
         2: Search                     => Search                        is FN, FN sensitive, reprogrammable
         3: Calculator                 => Calculator                    is FN, FN sensitive, reprogrammable
         4: Media Player               => Music                         is FN, FN sensitive, reprogrammable
         5: Previous                   => Previous                      is FN, FN sensitive
         6: Play/Pause                 => Play/Pause                    is FN, FN sensitive
         7: Next                       => Next                          is FN, FN sensitive
         8: Mute                       => Mute                          is FN, FN sensitive
         9: Volume Down                => Volume Down                   is FN, FN sensitive
        10: Volume Up                  => Volume Up                     is FN, FN sensitive
     Battery: 30%, discharging, next level 5%.

  2: Wireless Mouse M185/M235/M310
     Device path  : /dev/hidraw5
     WPID         : 4055
     Codename     : M185/M235/M310
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: E806AD0E
     The power switch is located on the base.
     Battery: unknown (device is offline).

<details>

```
This is the kernel output for the new dongle after I insert it:
[ 1649.492885] usb 3-2: new full-speed USB device number 9 using xhci_hcd
[ 1649.657460] usb 3-2: New USB device found, idVendor=046d, idProduct=c542, bcdDevice= 3.02
[ 1649.657466] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 1649.657469] usb 3-2: Product: Wireless Receiver
[ 1649.657471] usb 3-2: Manufacturer: Logitech
[ 1649.671915] input: Logitech Wireless Receiver Mouse as /devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb3/3-2/3-2:1.0/0003:046D:C542.0019/input/input48
[ 1649.672078] hid-generic 0003:046D:C542.0019: input,hidraw1: USB HID v1.11 Mouse [Logitech Wireless Receiver] on usb-0000:04:00.4-2/input0
```

**Describe the bug**
The new dongle is not detected at all by Solaar.
I cannot pair the new mouse with the old dongle either. 
I suppose it might be a new variant?

**To Reproduce**
1. Insert the dongle
2. Run solaar in the command line
3. The dongle is not detected

**Screenshots**

**Additional context**

**Comment by pfps** [comment]
This is a receiver that came with an M185 mouse?

It appears that this mouse and receiver use a different protocol than other Logitech hardware.  Solaar does not support this receiver and mouse and may never be able to do so.

For more information see issue #1350

**Comment by cnxsoft** [comment]
Yes, I've just bought a Logitech M185 mouse online. It looks very similar to my previous M185 which I bought over 5 years ago, but the design has changed. Maybe it's just a clone then.

**Comment by pfps** [comment]
Logitech has this habit of using model numbers to signify the physical appearance of a device.  New devices with the same physical appearance and thus model number may have different software or even different internal hardware.  I guess Logitech thinks that as long as the advertised behaviour is the same then the internals don't matter.  I can actually see some rationale for this.

It is entirely possible that Solaar can do more with some Logitech devices than Logitech software does.  We can't complain much if this undocumented and unsupported behaviour changes.

This is not to say that I agree with keeping model numbers the same while changing some aspects of the device.
