### ISSUE TITLE
Rule Editor not working?

### ISSUE THREAD

**Issue by Maciej-Zwolinski** [pwr-Solaar/Solaar#1361]
**Information**

- Solaar version 1.1.0-6-ga45f11f
- Distribution: Kubuntu 20.04
- Kernel version: Linux 5.11.0-41-generic x86_64 GNU/Linux

<details>

```
Traceback (most recent call last):
  File "/home/maciej/Solaar/lib/solaar/ui/diversion_rules.py", line 387, in _event_button_released
    wrapped = m[it][0]
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 844, in __getitem__
    aiter = self._getiter(key)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 832, in _getiter
    aiter = self.get_iter(key)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 866, in get_iter
    path = self._coerce_path(path)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 841, in _coerce_path
    return TreePath(path)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1201, in __new__
    path = ":".join(str(val) for val in path)
TypeError: 'NoneType' object is not iterable

```
</details>

**Describe the bug**
This bug seems to have nothing to do with the keyboard I'm using, rather it seems a configuration issue. When running `sudo /bin/solaar` and opening "Rule Editor" screen for my G613 I'm greeted by unresponsive empty screen, and the above console output shows when right-clicking anywhere on the screen. All I did is to clone the repo and run `sudo /bin/solaar` from the repo location. Based on what I read about Solaar there should be `~/.config/solaar` directory with some basic rules, but it is missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/46869207/144642983-54578832-da2c-4a3a-bf0a-b4d2215751b7.png)
![image](https://user-images.githubusercontent.com/46869207/144643467-c2676cb8-139d-4aa8-979a-0ac4eb8abab8.png)

**Comment by pfps** [comment]
I don't see the same behaviour when I run Solaar as root.  But you shouldn't be running Solaar as root anyway, because the configuration information will end up in root's home directory.

It may be that in your distribution root doesn't have a home directory and this is causing problems.

The first thing to do, then, is to set up Solaar so that it can be run as you, by installing the Solaar udev rule.  Then run Solaar without sudo and see if the problem persists.

**Comment by Maciej-Zwolinski** [comment]
I copied supplied `rules.d` content into `/etc/udev/rules.d`. Solaar can be run without `sudo` prefix (and doesn't throw permission denied anymore), but the core issue persists - even system reboot.

**Comment by pfps** [comment]
What should happen is that when you open up the rule editor you should see at least the built-in rules.  Try running solaar with the `-d` flag and post any unusual output.  If there is none, try with `-dd`.

**Comment by Maciej-Zwolinski** [comment]
ok, it works. I was missing Xlib. Sorry for the commotion.
