### ISSUE TITLE
Symbolic icons do not work with certain icon themes

### ISSUE THREAD

**Issue by Oober** [pwr-Solaar/Solaar#1363]
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.0
- Distribution: Mint 20.2
- Kernel version (ex. `uname -srmo`): Linux 5.4.0-91-generic x86_64 GNU/Linux
- Output of `solaar show`:

<details>
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : 4241987C
    Firmware   : 12.01.B0019
    Bootloader : 02.14
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 2=160

  2: Illuminated Living-Room Keyboard K830
     Device path  : /dev/hidraw1
     WPID         : 4032
     Codename     : K830
     Kind         : keyboard
     Protocol     : HID++ 4.1
     Polling rate : 8 ms (125Hz)
     Serial number: C99590BF
     Model ID:      000000000000
     Unit ID:       00000000
          Firmware: RQK 56.00.B0020
     The power switch is located on the edge of top right corner.
     Supports 27 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Firmware RQK 56.00.B0020 4032E27164
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         3: DEVICE NAME            {0005}   
            Name: Illuminated Living-Room Keyboard K830
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
            Battery: 90%, discharging, next level 50%.
         7: BACKLIGHT              {1981}   
         8: REPROG CONTROLS V4     {1B04}   
         9: SWAP BUTTON CANCEL     {2005}   
        10: NEW FN INVERSION       {40A2}   
            Fn-swap: disabled
            Fn-swap default: enabled
            Swap Fx function (saved): False
            Swap Fx function        : False
        11: ENCRYPTION             {4100}   
        12: KEYBOARD DISABLE KEYS  {4521}   
            Disable keys (saved): {'1': False, '16': False, '4': False, '8': False}
            Disable keys        : {'1': False, '4': False, '8': False, '16': False}
        13: TOUCHPAD RAW XY        {6100}   hidden
        14: GESTURE 2              {6501}   
            Gestures (saved): {'1': True, '10': True, '2': True, '30': True, '34': False, '42': True, '43': True, '45': False, '64': True, '65': True, '67': True, '84': True}
            Gestures        : {'1': True, '2': True, '30': True, '10': True, '45': False, '42': True, '43': True, '64': True, '65': True, '67': True, '84': True, '34': False}
            Gesture params (saved): {'4': {'scale': 256}}
            Gesture params        : {'4': {'scale': 256}}
        15: DFUCONTROL UNSIGNED    {00C1}   
        16: unknown:1811           {1811}   internal, hidden
        17: unknown:1830           {1830}   internal, hidden
        18: unknown:1890           {1890}   internal, hidden
        19: unknown:18A0           {18A0}   internal, hidden
        20: unknown:1DF3           {1DF3}   internal, hidden
        21: unknown:1E00           {1E00}   hidden
        22: unknown:1EB0           {1EB0}   internal, hidden
        23: unknown:1861           {1861}   internal, hidden
        24: unknown:1A20           {1A20}   internal, hidden
        25: unknown:18B0           {18B0}   internal, hidden
        26: unknown:1F07           {1F07}   internal, hidden
     Has 20 reprogrammable keys:
         0: Second Left Click         , default: Left Click                  => Left Click                
             mse, divertable, pos:0, group:0, group mask:empty
             reporting: default
         1: Minimize Window           , default: Minimize Window             => Minimize Window           
             is FN, FN sensitive, reprogrammable, divertable, pos:2, group:0, group mask:empty
             reporting: default
         2: Maximize Window           , default: Maximize Window             => Maximize Window           
             is FN, FN sensitive, reprogrammable, divertable, pos:3, group:0, group mask:empty
             reporting: default
         3: Close                     , default: Close Application           => Close Application         
             is FN, FN sensitive, reprogrammable, divertable, pos:4, group:0, group mask:empty
             reporting: default
         4: Switch Screen             , default: Switch Presentation/Switch Screen => Switch Presentation/Switch Screen
             is FN, FN sensitive, reprogrammable, divertable, pos:5, group:0, group mask:empty
             reporting: default
         5: Show Desktop              , default: Show Desktop                => Show Desktop              
             is FN, FN sensitive, reprogrammable, divertable, pos:6, group:0, group mask:empty
             reporting: default
         6: Search                    , default: Search Files                => Search Files              
             is FN, FN sensitive, reprogrammable, divertable, pos:7, group:0, group mask:empty
             reporting: default
         7: My Home                   , default: HomePage                    => HomePage                  
             is FN, FN sensitive, reprogrammable, divertable, pos:8, group:0, group mask:empty
             reporting: default
         8: Media Player              , default: Music                       => Music                     
             is FN, FN sensitive, reprogrammable, divertable, pos:9, group:0, group mask:empty
             reporting: default
         9: Previous                  , default: Previous                    => Previous                  
             is FN, FN sensitive, divertable, pos:10, group:0, group mask:empty
             reporting: default
        10: Play/Pause                , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, divertable, pos:11, group:0, group mask:empty
             reporting: default
        11: Next                      , default: Next                        => Next                      
             is FN, FN sensitive, divertable, pos:12, group:0, group mask:empty
             reporting: default
        12: Application Switcher      , default: Application Switcher        => Application Switcher      
             is FN, reprogrammable, divertable, pos:13, group:0, group mask:empty
             reporting: default
        13: Sleep                     , default: Sleep                       => Sleep                     
             is FN, reprogrammable, divertable, pos:14, group:0, group mask:empty
             reporting: default
        14: Mute                      , default: Mute                        => Mute                      
             nonstandard, divertable, pos:0, group:0, group mask:empty
             reporting: default
        15: Volume Down               , default: Volume Down                 => Volume Down               
             nonstandard, divertable, pos:0, group:0, group mask:empty
             reporting: default
        16: Volume Up                 , default: Volume Up                   => Volume Up                 
             nonstandard, divertable, pos:0, group:0, group mask:empty
             reporting: default
        17: Fn Left Click             , default: ShowUI                      => ShowUI                    
             divertable, pos:0, group:0, group mask:empty
             reporting: default
        18: Left Button               , default: Left Click                  => Left Click                
             mse, pos:0, group:0, group mask:empty
             reporting: default
        19: Right Button              , default: Right Click                 => Right Click               
             mse, pos:0, group:0, group mask:empty
             reporting: default
     Has 17 gesture(s), 1 param(s) and 4 spec(s):
        Track1Finger               Enabled (None): None
        TapGestures                Enabled (None): None
        Tap1Finger                 Enabled (   0): True
        Tap2Finger                 Enabled (   1): True
        TapDrag1Finger             Enabled (   2): True
        DoubleTap1Finger           Enabled (   3): True
        Scroll2FingerStateless     Enabled (None): None
        NaturalScrolling           Enabled (   4): False
        Scroll2FingerHoriz         Enabled (   5): True
        Scroll2FingerVert          Enabled (   6): True
        LeftEdgeSwipe1Finger2      Enabled (   7): True
        RightEdgeSwipe1Finger2     Enabled (   8): True
        TopEdgeSwipe1Finger2       Enabled (   9): True
        Zoom2FingerStateless       Enabled (  10): True
        FnClickGestureSuppression  Enabled (  11): False
        TwoFingersPresent          Enabled (None): None
        DeviceSpecificRawData      Enabled (None): None
        ScaleFactor                Value   (   0): 256 [Default: 256]
        period unit                Spec    (   3): 72
        DVI field width            Spec    (   1): 8
        field widths               Spec    (   2): 8
        resolution                 Spec    (   4): 4
     Battery: 90%, discharging, next level 50%.
</details>

**Describe the bug**
Running solaar with '--battery-icons=symbolic' does not show any panel icon.

**To Reproduce**
I am using Suru++ icon theme from [here](https://www.opendesktop.org/p/1247483/#files-panel) for my Cinnamon desktop. However, when using 'symbolic' battery icons, the panel icon disappears. When using regular icons, the panel icon works (but showing _green).

**Additional context**
I can give some futher assistance if you tell me, where does Solaar take the symbolic battery icons.

**Comment by pfps** [comment]
The way the system tray (panel) icons are handled has changed in Solaar 1.1.0.  This may have exposed some shortcomings in the system tray implementation you are using.
What Solaar 1.1.0 does is turn the icon name into a file name and use this file name for the system tray icon.  This was done to get around a bug in some system tray implementations.  But it appears to have exposed several shortcomings in some system tray icons.
One way forward for you would be to install Solaar from this repository as it reverts back to the older way but has a new flag to use the new way.
If this doesn't work you could try running Solaar with `-d` to see whether there are any warnings or errors, or Solaar with `-dd`, which will output a lot of information on what Solaar is doing.

**Comment by Oober** [comment]
Actually I investigated this a little bit. Solaar takes its regular tray icons from status/48 folder of the icon theme folder. I replaced those with respective icons from status/symbolic folder and I am running solaar with 'battery-icons=regular' suffix without any problems.

**Comment by pfps** [comment]
So either the icons in this folder had problems or the system tray implementation on your system couldn't handle them.   
If you install Solaar from this repository it should work without having to do the icon replacement.

**Comment by Oober** [comment]
Confirm, no issues after installing git version from ppa.
