### ISSUE TITLE
Battery icons hardly visible in dark display scheme

### ISSUE THREAD

**Issue by gerhard-s** [pwr-Solaar/Solaar#1370]
- Solaar version: solaar 1.1.0
- Distribution: openSUSE Tumbleweed 20211207
- Kernel version: Linux 5.14.14-3-default x86_64 GNU/Linux
- Output of `solaar show`: possibly irrelevant here

I'm using breeze dark display scheme on KDE Plasma 5.23.4. Solaar's battery icon in the main Solaar window and in the system tray is now black and hard to see. In the previous release, it was white as all other tray icons.

![Screenshot_20211210_104121](https://user-images.githubusercontent.com/95910446/145552672-79ba3499-462e-45dd-93ca-c483d15cc126.png)
![Screenshot_20211210_104100](https://user-images.githubusercontent.com/95910446/145552694-5af07f27-8ee7-4c62-9dca-6bf8ba6428b1.png)

**Comment by pfps** [comment]
This may be a consequence of using explicit icon files, which is done to get around bugs in some system tray implementations.  This change caused other problems and a new way of doing the system tray icons is in the Solaar in this repository.  So please clone this repository and see if it works for you.

**Comment by LeoniePhiline** [comment]
Hi!
I got the same issue.

> So please clone this repository and see if it works for you.

Do you mean to maintain a fork?

**Comment by pfps** [comment]
You don't need your own fork.  Just clone this repository to your machine and run Solaar as `bin/solaar` from your clone.  

You only need to create a github fork if you want to contribute to Solaar.

**Comment by gerhard-s** [comment]
As an update of this issue, I just upgraded KDE Frameworks from 5.88 to 5.89 and KDE gears from 21.08.03 to 21.12.0 (same KDE Plasma version 5.23.4) and the problem is gone! The battery icons are white as they should.

**Comment by pfps** [comment]
Good to know.

**Comment by pfps** [comment]
@LeoniePhiline Are you still having the problem?

**Comment by LeoniePhiline** [comment]
@pfps I haven't had the chance to upgrade KDE yet, due to far too much work just before the holidays. I will let you know, probably later this week!

**Comment by LeoniePhiline** [comment]
@pfps It's fixed also for me!

**Comment by pfps** [comment]
Excellent.

Looks like there was a bug somewhere that was fixed.  Either that or some icon files had issues.
