### ISSUE TITLE
Import and Export ability in the rule editor

### ISSUE THREAD

**Issue by VandrerenErik** [pwr-Solaar/Solaar#1373]
Hello,

I think the title is self explanatory, but just to elaborate a little bit. I think it would be great to have this feature. I do fresh installs quite often and I also have several computers, this would be a killer feature.

**Comment by pfps** [comment]
Solaar already has what I think you want.  The Solaar rules are stored in a yaml file, ~/.config/solaar/rules/yaml. To move a full set of rules around just copy the file.  To move a single rule around use part of the file.

**Comment by VandrerenErik** [comment]
I assumed the file would be somewhere but I never bothered to search for it haha. Thanks for telling me where it is
