### ISSUE TITLE
Lock Animation on Wireless Mouse settings broken on Ubuntu 21.10

### ISSUE THREAD

**Issue by concept10** [pwr-Solaar/Solaar#1375]
**Information**

- Solaar version 1.1.0 flatpak and git latest (`solaar --version` or `git describe --tags` if cloned from this repository):
- Distribution: Ubuntu
- Kernel version (ex. `uname -srmo`): `KERNEL VERSION HERE`
- Output of `solaar show`:

<details>

```
OUTPUT HERE
```
</details>

**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by concept10** [comment]
Okay, I never seen an icon pattern with three states.  Clever.  May need animation or easing though.

**Comment by pfps** [comment]
I'm not sure what problem you are encountering.  Can you expand your description?

**Comment by concept10** [comment]
Will expand on the issue shortly.  Thanks for the response.
