### ISSUE TITLE
Change motion required before is considered one unit of scroll

### ISSUE THREAD

**Issue by mdbetancourt** [pwr-Solaar/Solaar#1377]
My mouse is a Logitech MX Master 3 but i have a problem when i have enabled rachet mode my scroll is too sensitive (scroll before feel the change of position) so i wanna configured it to be high sensitive (as now) for free spin but have a little dead gap for rachet mode between every scroll unit

**Comment by pfps** [comment]
I don't think that this is possible, even if Solaar is modified, as the mouse doesn't have the ability to set up dead modes.

**Comment by pfps** [comment]
I'm closing this for now.  If some information surfaces that it is possible to get the mouse to have dead zones, this issue can be reopened.

**Comment by mdbetancourt** [comment]
do you know a way to disable high resolution for ratched mode and enable it for freespin mode? this could allow what i want

**Comment by pfps** [comment]
I don't think this is possible.
