### ISSUE TITLE
Is a Docker or AppImage version of Solaar possible?

### ISSUE THREAD

**Issue by pippim** [pwr-Solaar/Solaar#1382]
I have a new MX Master 2S mouse with a new USB receiver.

I still have the old K800 keyboard with it's own USB receiver. The old MX mouse on this receiver had died.

It would be nice to be able to quickly run the latest Solaar without having to setup correct python versions and library dependencies to pair both HID's to a single USB receiver and unplug the extra receiver. Solaar would only be required for this one time configuration. Now the only option is to dual boot into Windows and run Logitech's software to make the configuration change.

***Is it practical or feasible to make a Docker or AppImage distribution of Solaar for AMD64?***

Even if a mainstream kernel version had to be installed, it would be worthwhile for folks who would rather not boot into Windows. Perhaps they don't even have Windows installed.

**Comment by pfps** [comment]
Solaar needs special privileges on nodes in /dev/hidraw* so setting up Docker is not going to be easy.  Installing via pip should be easy.  Fedora provides Solaar in a standard repository.  For Ubuntu there is are repositories for Solaar.

If someone wants to try to create a different distribution mechanism for Solaar go ahead.
