### ISSUE TITLE
There is no option for MX Anywhere 3 and uknown battery

### ISSUE THREAD

**Issue by lephnut** [pwr-Solaar/Solaar#1385]
I manual installed Solaar 1.1.1rc2. After executing Solaar, there is no option available for MX Anywhere 3 and with unknown battery.

![image](https://user-images.githubusercontent.com/46984555/147038438-d1f0eba7-db7d-4984-81b6-ce92c5a6fe4d.png)

- Solaar version: 1.1.1rc2
- Distribution: Ubuntu 18.04
- Kernel version: 5.4.0-91-generic
- Output of solaar -dd show

> $ solaar -dd show
> 12:35:26,311    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Down"
> 12:35:26,311    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Up"
> 12:35:26,315    DEBUG [MainThread] solaar.ui.tray: using StatusIcon
> 12:35:26,339    DEBUG [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C52B INTERFACE 2 FILTER 2
> 12:35:26,339     INFO [MainThread] logitech_receiver.base: New lock 10
> 12:35:26,340    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 83B5 030000]
> 12:35:26,343    DEBUG [MainThread] logitech_receiver.base: (10) => r[11 FF 83B5 0333C199571406080000000000000000]
> 12:35:26,343    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 80B2 000000]
> 12:35:26,345    DEBUG [MainThread] logitech_receiver.base: (10) => r[20 01 4101 9040040000000400000000]
> 12:35:26,347    DEBUG [MainThread] logitech_receiver.base: (10) => r[20 00 4102 0000000000000000000000]
> 12:35:26,349    DEBUG [MainThread] logitech_receiver.base: (10) => r[10 FF 8F80 B20300]
> 12:35:26,349    DEBUG [MainThread] logitech_receiver.base: (10) device 0xFF error on request {80B2}: 3 = invalid value
> 12:35:26,349    DEBUG [MainThread] solaar.cli: [/dev/hidraw0] => <UnifyingReceiver(/dev/hidraw0,10)>
> 12:35:26,354    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8102 000000]
> 12:35:26,355    DEBUG [MainThread] logitech_receiver.base: (10) => r[10 FF 8102 000100]
> Unifying Receiver
>   Device path  : /dev/hidraw0
>   USB id       : 046d:C52B
>   Serial       : 33C19957
> 12:35:26,355    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 81F1 010000]
> 12:35:26,357    DEBUG [MainThread] logitech_receiver.base: (10) => r[10 FF 81F1 012411]
> 12:35:26,357    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 81F1 020000]
> 12:35:26,359    DEBUG [MainThread] logitech_receiver.base: (10) => r[10 FF 81F1 020036]
> 12:35:26,359    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 81F1 040000]
> 12:35:26,361    DEBUG [MainThread] logitech_receiver.base: (10) => r[10 FF 81F1 040209]
> 12:35:26,361    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 81F1 030000]
> 12:35:26,363    DEBUG [MainThread] logitech_receiver.base: (10) => r[10 FF 81F1 03AAAC]
>     Firmware   : 24.11.B0036
>     Bootloader : 02.09
>     Other      : AA.AC
>   Has 1 paired device(s) out of a maximum of 6.
> 12:35:26,363    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8102 000000]
> 12:35:26,365    DEBUG [MainThread] logitech_receiver.base: (10) => r[10 FF 8102 000100]
> 12:35:26,365    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8100 000000]
> 12:35:26,367    DEBUG [MainThread] logitech_receiver.base: (10) => r[10 FF 8100 000100]
>   Notifications: wireless (0x000100)
> 12:35:26,367    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 83B3 000000]
> 12:35:26,369    DEBUG [MainThread] logitech_receiver.base: (10) => r[11 FF 83B3 35000000000000000000000000000000]
>   Device activity counters: 1=53
> 12:35:26,369    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 8102 000000]
> 12:35:26,371    DEBUG [MainThread] logitech_receiver.base: (10) => r[10 FF 8102 000100]
> 12:35:26,371    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 83B5 200000]
> 12:35:26,373    DEBUG [MainThread] logitech_receiver.base: (10) => r[11 FF 83B5 20080840900402020600000000000000]
> 12:35:26,375    DEBUG [MainThread] logitech_receiver.base: (10) <= w[10 FF 83B5 400000]
> 12:35:26,377    DEBUG [MainThread] logitech_receiver.base: (10) => r[11 FF 83B5 400D4D5820416E797768657265203300]
> 12:35:26,377     INFO [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,10)>: found new device 1 (4090)
> 
> solaar: error: Traceback (most recent call last):
>   File "/home/abel/.local/lib/python3.6/site-packages/solaar/cli/__init__.py", line 204, in run
>     m.run(c, args, _find_receiver, _find_device)
>   File "/home/abel/.local/lib/python3.6/site-packages/solaar/cli/show.py", line 285, in run
>     _print_device(dev)
>   File "/home/abel/.local/lib/python3.6/site-packages/solaar/cli/show.py", line 89, in _print_device
>     dev.ping()
>   File "/home/abel/.local/lib/python3.6/site-packages/logitech_receiver/device.py", line 401, in ping
>     self.handle or self.receiver.handle, self.number, long_message=self.bluetooth or self._protocol >= 2.0
> TypeError: '>=' not supported between instances of 'NoneType' and 'float'

**Comment by pfps** [comment]
The problem with `solaar show` is obvious.  I expect that the same problem is affecting the Solaar gui.  Could you try running Solaar as `solaar -dd` and post the output here?

**Comment by pfps** [comment]
PR #1387 should fix the problem in `solaar show` and likely fixes the main problem.  Try it out and see if it fixes the problem.  If not, run `solaar -dd` and post the output.

To download and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1387, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1387/head:pull_1387
git checkout pull_1387
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1387
git fetch origin pull/1387/head
git reset --hard FETCH_HEAD
```

**Comment by lephnut** [comment]
After I checkout pull_1387 branch, and do "pip install --user ." again. The GUI status is the same, but there is no error log in terminal.

The output of `solaar -dd`:

> $ solaar -dd
> 08:24:46,932     INFO [MainThread] root: language zh_TW (UTF-8), translations path None
> 08:24:47,148    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Down"
> 08:24:47,148    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Up"
> 08:24:47,152    DEBUG [MainThread] solaar.ui.traAbout Solaary: using StatusIcon
> 08:24:47,161     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events

By the way, is the version always shown 0.9.2 version after `About Solaar` pressed?

![image](https://user-images.githubusercontent.com/46984555/147169910-acf5b30f-682d-47ba-b6b6-d3dcdd414ac8.png)

**Comment by pfps** [comment]
If you are seeing 0.9.2 you are running a very old version of Solaar.   It might be that Solaar is autostarted in a situation where the Solaar you are installing is not in the PATH.  The old version of Solaar might not support your device very well.

Try going to the directory where you cloned Solaar and running `bin/solar -dd` from there.  This should run the current version.

**Comment by lephnut** [comment]
I execute from the git code base with `bin/solar -dd`, but got the same log and GUI.

> ~/Solaar/bin $ ./solaar -dd
> 09:52:39,265     INFO [MainThread] root: language zh_TW (UTF-8), translations path None
> 09:52:39,459    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Down"
> 09:52:39,460    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Up"
> 09:52:39,464    DEBUG [MainThread] solaar.ui.tray: using StatusIcon
> 09:52:39,473     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
>

**Comment by pfps** [comment]
If Solaar is already running, then running it again will not result in a second Solaar.  Instead the reinvocation will terminate and the old version's main window will be shown.  So first kill any Solaar that is running first.

**Comment by lephnut** [comment]
I am sorry for my neglection, the old solaar is running. After kill the service, the GUI work fine, many thanks for your help.

![image](https://user-images.githubusercontent.com/46984555/147176304-d238abdf-2601-4cd3-9fd8-e8a88dcadb5d.png)

**Comment by pfps** [comment]
OK, I'm closing this issue.
