### ISSUE TITLE
Mouse (MX Master 3) is registering scroll movement before a 'click' has been made since version 1.2.0 of `xf86-input-libinput`.

### ISSUE THREAD

**Issue by Pistrie** [pwr-Solaar/Solaar#1386]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.1rc2
- Distribution: Arch
- Kernel version (ex. `uname -srmo`): `5.15.10-zen1-1-zen`
- Output of `solaar show`:

<details>

```
Unifying Receiver
  Device path  : /dev/hidraw7
  USB id       : 046d:C52B
  Serial       : 63929489
    Firmware   : 12.11.B0032
    Bootloader : 04.16
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=254

  1: MX Master 3 Wireless Mouse
     Device path  : /dev/hidraw8
     WPID         : 4082
     Codename     : MX Master 3
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: D3E955BB
     Model ID:      B02340820000
     Unit ID:       D3E955BB
        Bootloader: BOT 95.01.B0015
          Firmware: MPM 19.01.B0015
             Other:
     The power switch is located on the base.
     Supports 35 HID++ 2.0 features:
         0: ROOT                   {0000}
         1: FEATURE SET            {0001}
         2: DEVICE FW VERSION      {0003}
            Firmware: Bootloader BOT 95.01.B0015 00006A9CA89D
            Firmware: Firmware MPM 19.01.B0015 40826A9CA89D
            Firmware: Other
            Unit ID: D3E955BB  Model ID: B02340820000  Transport IDs: {'btleid': 'B023', 'wpid': '4082'}
         3: DEVICE NAME            {0005}
            Name: Wireless Mouse MX Master 3
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}
         5: RESET                  {0020}
         6: CRYPTO ID              {0021}
         7: DEVICE FRIENDLY NAME   {0007}
            Friendly Name: MX Master 3
         8: BATTERY STATUS         {1000}
            Battery: 100%, discharging, next level 50%.
         9: REPROG CONTROLS V4     {1B04}
            Key/Button Actions (saved): {'195': 195, '196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}
            Key/Button Actions        : {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '195': 195, '196': 196}
            Key/Button Diversion (saved): {'195': 1, '196': 0, '82': 0, '83': 0, '86': 0}
            Key/Button Diversion        : {'82': 0, '83': 0, '86': 0, '195': 1, '196': 0}
        10: CHANGE HOST            {1814}
            Change Host        : 1:icarus
        11: XY STATS               {2250}
        12: ADJUSTABLE DPI         {2201}
            Sensitivity (DPI) (saved): 800
            Sensitivity (DPI)        : 800
        13: SMART SHIFT            {2110}
            Scroll Wheel Rachet (saved): 20
            Scroll Wheel Rachet        : 20
        14: HIRES WHEEL            {2121}
            Multiplier: 15
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            High resolution mode
            HID notification
            Scroll Wheel Direction (saved): False
            Scroll Wheel Direction        : False
            Scroll Wheel Resolution (saved): True
            Scroll Wheel Resolution        : True
        15: THUMB WHEEL            {2150}
            Thumb Wheel Diversion (saved): False
            Thumb Wheel Diversion        : False
            Thumb Wheel Direction (saved): False
            Thumb Wheel Direction        : False
        16: WHEEL STATS            {2251}
        17: DFUCONTROL SIGNED      {00C2}
        18: DEVICE RESET           {1802}   internal, hidden
        19: unknown:1803           {1803}   internal, hidden
        20: CONFIG DEVICE PROPS    {1806}   internal, hidden
        21: unknown:1813           {1813}   internal, hidden
        22: OOBSTATE               {1805}   internal, hidden
        23: unknown:1830           {1830}   internal, hidden
        24: unknown:1890           {1890}   internal, hidden
        25: unknown:1891           {1891}   internal, hidden
        26: unknown:18A1           {18A1}   internal, hidden
        27: unknown:1DF3           {1DF3}   internal, hidden
        28: unknown:1E00           {1E00}   hidden
        29: unknown:1EB0           {1EB0}   internal, hidden
        30: unknown:1861           {1861}   internal, hidden
        31: unknown:9001           {9001}   internal, hidden
        32: unknown:9203           {9203}   internal, hidden
        33: unknown:9205           {9205}   internal, hidden
        34: unknown:9300           {9300}   internal, hidden
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Mouse Gesture Button      , default: Gesture Button Navigation   => Gesture Button Navigation
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: diverted, raw XY diverted
         6: Smart Shift               , default: Smart Shift                 => Smart Shift
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Battery: 100%, discharging, next level 50%.
```
</details>

**Describe the bug**
Scrolling the mouse wheel will cause motion before a real 'click' has been made.

**To Reproduce**
1. Use the latest version of `xf86-input-libinput`
2. Scroll a page with 'scroll wheel resolution' enabled

**Additional context**
This problem also exists in logid, where I also created an [issue](https://github.com/PixlOne/logiops/issues/285). The source of the problem is the latest version of `xf86-input-libinput` as described in [this thread](https://gitlab.freedesktop.org/xorg/driver/xf86-input-libinput/-/issues/39).

**Comment by pfps** [comment]
See #1377 

I don't think there is anything much that Solaar can do here, except that you should set Scroll Wheel Resolution to ignore, so that Solaar and the libinput don't fight over setting the resolution.

**Comment by Pistrie** [comment]
When I do that I can barely scroll a webpage since it's so slow. Is there a way to fix the scroll speed in that case?

**Comment by pfps** [comment]
Turning your mouse off and on may and removing and inserting the receiver may fix the problem  If not, your input driver is really confused and you may have to reboot your system.

What is happening is the Solaar and the input driver are reading and setting the sroll wheel resolution to different values and the last one wins, leading to either too fast or too slow scrolling if the input driver's setting is overwritten unexpectedly.   But some people are running systems with old drivers so the Solaar setting is useful for them.

**Comment by Pistrie** [comment]
I will reboot just in case. Also, do you spot anything that should be different in case it doesn't work? Is there a way to reset the settings to some sort of default?
![image](https://user-images.githubusercontent.com/39904003/147102946-cb64f92b-d88d-4ec0-91a8-665bfaed147b.png)

**Comment by pfps** [comment]
Everything looks correct.

**Comment by Pistrie** [comment]
Okay, I have rebooted, but I can still scroll this webpage by slightly turning the mouse wheel (before a real 'click' has been made). I double-checked and logid is not running, so it's not caused by that.

**Comment by Pistrie** [comment]
One sec while I gather some info. Will edit with the result

**Comment by pfps** [comment]
Under Fedora, my MX Master 3 is definitely put into high resolution scroll mode by the input driver.  But Firefox and emacs and Thunderbird still scroll line-by-line even when the ratchet is off.

**Comment by Pistrie** [comment]
> One sec while I gather some info. Will edit with the result

I've went through some of the stuff on my toolbar and this is the result:

Weird scrolling
- All browsers (and electron software)
- All KDE software
- GTK software

Ratchet scrolling (but with this weird thing where it skips the first ratchet, but works fine if you keep scrolling)
- Steam
- Emacs
- Kitty (terminal)

So some of the software works good, while other stuff doesn't

**Comment by pfps** [comment]
OK.  Strangely for me both Firefox and Emacs scroll on the first ratchet.  So this still appears to be a driver issue.   To check for sure you could reboot without Solaar running, making sure to turn off your mouse during the reboot.  This will remove any changes made to the mouse settings and Solaar will not be running so it will not make changes to the mouse settings.

**Comment by Pistrie** [comment]
> without Solaar running
How exactly do I do that? Is there a background process? I went through my active processes, and I don't see Solaar in there when the GUI is closed.

**Comment by pfps** [comment]
When you close the Solaar main window Solaar normally continues to run.  If you have a system tray then there should be an icon in the system tray that you can use to open the Solaar main window.  If you quit Solaar from the main window then Solaar will completely stop. 

Running at system startup is different.  If Solaar starts up when you reboot then there is some autostart file that is starting it.  Where this file is depends on your distribution and window system, but there should be some sort of startup setting where Solaar will show up and you should be able to turn this off.
If you have to manually start Solaar after a reboot then there is nothing you need to do.  Solaar does not have a separate daemon that is started automagically.

**Comment by Pistrie** [comment]
I have rebooted with the mouse turned off and Solaar not running (to be clear, Solaar wasn't running on boot before, so the only difference was that the mouse was turned off during boot and login this time), but there is no difference. Emacs and other software with ratchet scrolling still skip the first ratchet, however, this isn't the biggest deal in the world. My main concern is the scrolling between ratchets, but since you have the same issue then I'm guessing that this can't be solved, correct?

**Comment by pfps** [comment]
This is not a Solaar issue, and fixing it can't be done in Solaar.  The problem is in the input drivers.

**Comment by Pistrie** [comment]
Do you perhaps know where I can start fixing it? I have no clue where to start

**Comment by pfps** [comment]
The thread on libinput seems to indicate that this will not be an easy problem to fix.  I haven't worked on this area at all so I have no idea where to start either.
