### ISSUE TITLE
Battery Icon Incorrect on Pop OS Icon Theme usin GIT Version (Stable works as expected).

### ISSUE THREAD

**Issue by BaronKrause** [pwr-Solaar/Solaar#1390]
In the past I had an issue with the App Indicator icon not showing correctly using Pop OS's Default Icon theme using the Git version. It worked for a period of around 1-2 months (October-November) and then the bug was back again.

![144693662-0a78acb0-173b-4e5b-9ce5-9acc9317051e](https://user-images.githubusercontent.com/16513453/147290541-4b8577b2-0a20-4098-a493-3e2c403830e0.png)

On Pop OS using the default icon theme the app indicator always looks like that copper top icon regardless of battery level or normal or symbolic icons being used (using -b symbolic), but as you can see from the actual Solaar window, the icons Do show correctly inside it (and change between normal and symbolic when you use the flag). Its just the system tray.

I did a fresh test install on another machine this time using 20.04 LTS instead of my current 21.04/21.10 systems and then installed the Stable version from the Stable PPA. The icons worked perfectly, showing the normal or symbolic in the tray depending on the flag used.

I then installed the Git PPA and updated and the problem immediately returned.

So whatever is causing this issue is something that is different from the current Stable PPA and Git PPA.

If it helps at all I did another test install on manjaro and installed Solaar 1.1.0 from the main repo and then downloaded the newest Pop OS icon theme and loaded it, it did Not have this issue. But this version of Solaar is almost the same version as the stable PPA branch on Ubuntu so its not entirely surprising.

If you need any other information I would be happy to help/test, I will keep the test system around too.

**Comment by pfps** [comment]
There have been several changes in how Solaar selects the icon to show in the system tray.  Ideally Solaar should just be able to use an icon name, like battery-good, and the system tray implementation would choose the right icon.  But this often goes wrong, with icons ending up too small, too big, light-on-light, dark-on-dark, or some other problem.

Without any flags, Solaar does the simple thing, which works in most cases.  To force icon style use the `--battery-icons` flag.  To force a particular size use the `--tray-icon-size` flag.  I expect that what you need to use the `--tray-icon-size=NN` flag because that is what Solaar was using a couple of months ago.  Pick a number like 32 or so for NN.

**Comment by BaronKrause** [comment]
That was absolutely it. Using the size flag makes it work!!!

For symbolic (the only ones that look good in the pop icon theme) using 31 and under makes it use the same icon as the laptop battery as seen in the above image in the original post. Using 32 like you suggested makes it use the more squared off icon like in the actual Solaar program window in that picture (what it used in the Stable version) and anything above that is back to the System battery icon. I'm not sure which looks better but it works!

Since regardless of the size chosen, they all display as the same size in the tray, does it mater? Or just use whatever gives you the icon you want like 32?

**Comment by pfps** [comment]
What is happening is that the size parameter is used to pick a particular icon file (the one with close to that size).  Then the filename of that file is sent to the system tray implementation.  Some implementations will not change the size of the icon, some will shrink a too-large icon, some will grow a too-small icon, some will both shrink and grow wrong-size icons.  There may also be other things that are taken into account by the system tray implementation.

It might be that your icon theme has problems.  Try `gtk3-icon-browser`, then search for `battery`.  Clicking on any of the icons should show the available files for that icon name.  If they don't all look the same then there is something wrong with your icon theme.

**Comment by BaronKrause** [comment]
I see whats happening to some extent. On this theme the "main" icon in both normal and symbolic for battery use the exact same (for lack of a better word) icon for the thumbnail. Its like all values icons thumbnails are the same but when you click them you see the full range. All the normal icons used that copper top icon but had unique icons when clicked. Its like not specifying a size just make it use the thumbnail version.

Don't know whats going on with symbolic though, even when specified in the launch flag, it would still use the thumbnail of the normal icons unless you specified a size.

Other themes use the same icon thumbnail as whats in the icon when clicked.
![Screenshot from 2021-12-23 17-04-26](https://user-images.githubusercontent.com/16513453/147295592-9e400a87-4a41-4e53-bc49-86a037eb46f6.png)
![Screenshot from 2021-12-23 17-05-35](https://user-images.githubusercontent.com/16513453/147295593-e88fdd6d-bfe5-40ec-aa4c-360099bcae72.png)
![Screenshot from 2021-12-23 17-06-19](https://user-images.githubusercontent.com/16513453/147295595-104d37a4-09bc-4533-a7e6-43c42b437c04.png)
![Screenshot from 2021-12-23 17-06-44](https://user-images.githubusercontent.com/16513453/147295596-e8587841-e2b4-4add-ab16-557d108d36cf.png)

**Comment by pfps** [comment]
Something appears to be messed up in your icon theme, but that's not anything that Solaar can fix.   You'll have to figure out how to get help for that elsewhere.
