### ISSUE TITLE
Solaar 1.1.1 - symbolic tray icon 

### ISSUE THREAD

**Issue by thekomer** [pwr-Solaar/Solaar#1395]
When using Solaar 1.1.1  symbolic tray battery icon is dark on my dark panel. (Unreadable)
On earlier version (1.1.0) it was white as it should be .

Also there is some error while launching app from terminal:

`` $ ./solaar -w hide -b regular ``
`` (solaar:21396): Gdk-CRITICAL **: 10:51:30.799: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed ``

My OS: MX Linux 19.3 - Xfce 4.14

**Comment by pfps** [comment]
The error you are seeing is something weird from GDK.  It doesn't appear to have an effect and it is unknown why it is being produced.

For the icon issue, see #1390

**Comment by thekomer** [comment]
Thank you. By using ``solaar -w hide -b symbolic --tray-icon-size NN`` (where NN is some size available in my icon pack) regular (colored) icon is displayed. It only works properly when I put 32.

Icon pack in use is Papirus-Dark icon pack. It's one of the best out there.

**Comment by pfps** [comment]
The tray icon stuff should "just work" in all cases, but  there are quite a few combinations of system tray implementations and icon themes that need help to work right.
