### ISSUE TITLE
Add G512 keyboard and G402 mouse

### ISSUE THREAD

**Issue by Blakeinstein** [pwr-Solaar/Solaar#1400]
**Information**
I am on a clean arch install and installed solaar, but it fails to either of my devices (A g512 Keyboard and a g402 mouse).
- Solaar version: `solaar 1.1.1` 
- Distribution: Arch Linux
- Kernel version: `Linux 5.15.11-arch2-1 x86_64 GNU/Linux`
- Output of `solaar show`:

<details>

```
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/solaar/cli/__init__.py", line 200, in run
    raise Exception('No devices found')
Exception: No devices found

```
</details>

**Describe the bug**
I have the following devices connected, 
```
$ lsusb | grep Logitech
Bus 001 Device 008: ID 046d:c33c Logitech, Inc. G512 RGB MECHANICAL GAMING KEYBOARD
Bus 001 Device 010: ID 046d:c07e Logitech, Inc. G402 Gaming Mouse
```

But solaar still throws an error that no devices were found. I installed solaar via `yay` and am unsure if there are extra requirements

**Comment by pfps** [comment]
I would expect these devices to work, but maybe they use a different USB interface ID than Solaar expects.  

But first, check whether permissions have been set up correctly by running `ls -l /dev/hidraw*`.  You should see a `+` after the permisisons bits in at least two of the lines.  If not, the udev rule is not working correctly.

If that is not the problem, run `solaar -dd show` and post the output.

**Comment by Blakeinstein** [comment]
> `ls -l /dev/hidraw*` returns the following for me
```
crw-rw----+ 1 root root 237, 0 Dec 28 11:08 /dev/hidraw0
crw-rw----+ 1 root root 237, 1 Dec 28 11:08 /dev/hidraw1
crw-rw----+ 1 root root 237, 2 Dec 28 11:08 /dev/hidraw2
crw-rw----+ 1 root root 237, 3 Dec 28 11:08 /dev/hidraw3
crw-------  1 root root 237, 4 Dec 28 11:08 /dev/hidraw4
crw-------  1 root root 237, 5 Dec 28 11:08 /dev/hidraw5
```

and `solar -dd show` returns no devices found as well
```
11:15:50,649    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Down"
11:15:50,650    DEBUG [MainThread] logitech_receiver.diversion: rule Key assuming action "pressed" for "Brightness Up"
11:15:50,653    DEBUG [MainThread] solaar.ui.tray: using StatusIcon
11:15:50,669    DEBUG [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C07E INTERFACE 0 FILTER 2
11:15:50,669    DEBUG [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C07E INTERFACE 1 FILTER 2
11:15:50,670    DEBUG [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C33C INTERFACE 0 FILTER 2
11:15:50,670    DEBUG [MainThread] hidapi.udev: Found device BID 0003 VID 0000046D PID 0000C33C INTERFACE 1 FILTER 2
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/solaar/cli/__init__.py", line 200, in run
    raise Exception('No devices found')
Exception: No devices found
```

**Comment by pfps** [comment]
The problem is that these two devices probably use a different USB interface number than Solaar expects.  To handle them will require a slight addition to the Solaar code.

**Comment by pfps** [comment]
PR #1403 should fix this issue.  Please clone Solaar and test out this PR.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1403, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1403/head:pull_1403
git checkout pull_1403
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1403
git fetch origin pull/1403/head
git reset --hard FETCH_HEAD
```

**Comment by Blakeinstein** [comment]
![Screenshot_2021-12-28-11-08-51_1920x1080](https://user-images.githubusercontent.com/42214598/147592551-8924583d-7e63-45b8-9442-71e366ab1574.png)

Awesome it works!
