### ISSUE TITLE
Battery Gauge

### ISSUE THREAD

**Issue by jkilgus** [pwr-Solaar/Solaar#1406]
Hello gentlemen,

I'm using a wireless keyboard and the battery life is displayed in the task bar. When the double A batteries that this keyboard came with ran out I replaced them with rechargeable batteries. Unfortunately rechargeable batteries have a lower peak voltage than normal batteries. So now even though the batteries are fully charged, it is displaying the red "batteries almost dead" gauge in the taskbar. It would be super cool if there was some way to set an option that took into account the lower peak voltage of rechargeable batteries so that my battery meter could look full and not empty and red.

Thank you very much!

**Comment by Klap-in** [comment]
Please share some detail about your device. You could use: `solaar show`

**Comment by jkilgus** [comment]
Logitech K400+
----------------
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 956F9970
    Firmware   : 24.10
    Bootloader : 01.08
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=90

  1: Wireless Touch Keyboard K400 Plus
     Codename     : K400 Plus
     Kind         : keyboard
     Wireless PID : 404D
     Protocol     : HID++ 4.1
     Polling rate : 8 ms (125Hz)
     Serial number: F2DDB8D4
        Bootloader: BOT 22.02.B0002
          Firmware: RQK 63.02.B0016
             Other: 
     The power switch is located on the top edge.
     Supports 24 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
         7: REPROG CONTROLS V4     {1B04}   
         8: SWAP BUTTON            {2005}   
         9: NEW FN INVERSION       {40A2}   
        10: ENCRYPTION             {4100}   
        11: KEYBOARD DISABLE       {4521}   
        12: TOUCHPAD RAW XY        {6100}   
        13: GESTURE 2              {6501}   
        14: DFUCONTROL 2           {00C1}   
        15: unknown:1811           {1811}   internal, hidden
        16: unknown:1830           {1830}   internal, hidden
        17: unknown:1890           {1890}   internal, hidden
        18: unknown:1DF3           {1DF3}   internal, hidden
        19: unknown:1E00           {1E00}   hidden
        20: unknown:1EB0           {1EB0}   internal, hidden
        21: unknown:1861           {1861}   internal, hidden
        22: unknown:18B0           {18B0}   internal, hidden
        23: unknown:1F11           {1F11}   internal, hidden
     Has 20 reprogrammable keys:
         0: unknown:00B8              , default: LeftClick                   => unknown:00B8              
             mse, divertable, pos:0, group:0, gmask:0
         1: BACK AS HID               , default: BackEx                      => BACK AS HID               
             is FN, FN sensitive, reprogrammable, divertable, pos:1, group:0, gmask:0
         2: MY HOME                   , default: HomePage                    => MY HOME                   
             is FN, FN sensitive, reprogrammable, divertable, pos:2, group:0, gmask:0
         3: Application Switcher      , default: Application Switcher        => Application Switcher      
             is FN, FN sensitive, reprogrammable, divertable, pos:3, group:0, gmask:0
         4: CONTEXTUAL MENU           , default: RightClick                  => CONTEXTUAL MENU           
             is FN, FN sensitive, reprogrammable, divertable, pos:4, group:0, gmask:0
         5: SEARCH                    , default: SearchForFiles              => SEARCH                    
             is FN, FN sensitive, reprogrammable, divertable, pos:5, group:0, gmask:0
         6: SHOW DESKTOP              , default: ShowDesktop                 => SHOW DESKTOP              
             is FN, FN sensitive, reprogrammable, divertable, pos:6, group:0, gmask:0
         7: WIN7 MAXIMIZE AS WIN ARROW, default: unknown:0095                => WIN7 MAXIMIZE AS WIN ARROW
             is FN, FN sensitive, reprogrammable, divertable, pos:7, group:0, gmask:0
         8: WIN7 SHOW PRESENTATION MODE, default: unknown:0093                => WIN7 SHOW PRESENTATION MODE
             is FN, FN sensitive, reprogrammable, divertable, pos:8, group:0, gmask:0
         9: MEDIA PLAYER              , default: Music                       => MEDIA PLAYER              
             is FN, FN sensitive, reprogrammable, divertable, pos:9, group:0, gmask:0
        10: Previous                  , default: Previous                    => Previous                  
             is FN, FN sensitive, divertable, pos:10, group:0, gmask:0
        11: Play/Pause                , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, divertable, pos:11, group:0, gmask:0
        12: Next                      , default: Next                        => Next                      
             is FN, FN sensitive, divertable, pos:12, group:0, gmask:0
        13: unknown:00B7              , default: ShowUI                      => unknown:00B7              
             divertable, pos:0, group:0, gmask:0
        14: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
             mse, pos:0, group:0, gmask:0
        15: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
             mse, pos:0, group:0, gmask:0
        16: Mute                      , default: Mute                        => Mute                      
             nonstandard, divertable, pos:0, group:0, gmask:0
        17: Volume Up                 , default: Volume Up                   => Volume Up                 
             nonstandard, divertable, pos:0, group:0, gmask:0
        18: Volume Down               , default: Volume Down                 => Volume Down               
             nonstandard, divertable, pos:0, group:0, gmask:0
        19: SLEEP                     , default: Sleep                       => SLEEP                     
             reprogrammable, divertable, pos:0, group:0, gmask:0
     Battery: 50%, discharging.

**Comment by pfps** [comment]
Solaar is reporting 50% for your battery, which is what your device reports.  If there is something that is reporting an empty battery then either it is not Solaar or the icon for the icon name (battery-good or battery-good-symbolic) is messed up in your icon theme.

Batteries vary.  The reporting of battery levels by Logitech devices is primitive.  Don't expect precision from battery levels.

**Comment by jkilgus** [comment]
I just recharged the batteries and now it's showing full so.... problem solved? I guess we can delete this sorry about that xD Solaar is pretty nice btw :)
