### ISSUE TITLE
MX Keys For Mac - missing OSes

### ISSUE THREAD

**Issue by kamil-karkus** [pwr-Solaar/Solaar#1411]
I don't know if it's possible but it'd be great if I could choose windows/linux OS for mx keys for mac.
Right now there's only possibility for choosing iOS/MacOS.
I have no idea if it's firmware related, however ergo k860 have both windows and macOS option under OS select.

**Comment by pfps** [comment]
Solaar is just providing what the keyboard allows, so this does not appear to be possible for your keyboard.
