### ISSUE TITLE
Solaar Icon not visible in system tray

### ISSUE THREAD

**Issue by Inf166** [pwr-Solaar/Solaar#1413]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.1
- Distribution: Garuda Linux (Arch)
- Kernel version (ex. `uname -srmo`): DINISO_2010

**Describe the bug**
I used solaar on my pop os ubuntu based distro and the solaar quick overview showed up in my gnome top bar (also read its called system tray?). But on my new Distro(also DE Gnome but different version) its not visible... I am not sure if I have to manually configure something?

**Additional context**
Theme: WhiteSur-light [GTK2/3]
OS: Garuda Linux x86_64 
Installed over AUR

**Comment by pfps** [comment]
There are many system tray implementations, some of which may need some setup.   That's not something that is part of Solaar however.
There are also potential problems with icons not being available or showing up poorly.  This is also not something that is part of Solaar.
You will probably have to dig deeper yourself to figure out what is going wrong.

**Comment by pfps** [comment]
You could try using one of the Solaar options to control which icons to use:

```
  -b {regular,symbolic,solaar}, --battery-icons {regular,symbolic,solaar}
                        prefer regular battery / symbolic battery / solaar icons
  --tray-icon-size TRAY_ICON_SIZE
                        explicit size for tray icons
```

**Comment by Inf166** [comment]
I am not sure what these parameters are supposed to do, but neither in my gnome top bar or in my solaar app, did I noticed any difference...
But thank you for the tip, I noticed while debuggin, that although my solaar installations works perfectly, I do not have a solaar.desktop file in my autostart... I configured it my self, also nothing to see in the gnome top panel.

**Comment by Inf166** [comment]
For completeness I found this Issue #1116 and it seams that this was the root of my problem. I probably had something like the appindicator installed on my last distro - because discord and other applications were shown in my top panel as well but now they are not. Thank you very much :)
