### ISSUE TITLE
Cannot tie thumb wheel with gnome shortcuts

### ISSUE THREAD

**Issue by plameniliev** [pwr-Solaar/Solaar#1416]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): solaar 1.1.1
- Distribution: Oracle Linux 8
- Kernel version (ex. `uname -srmo`): Linux 4.18.0-348.7.1.el8_5.x86_64 x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable):

<details>

```
OUTPUT HERE
```
</details>

**Is your feature request related to a problem? Please describe.**
I am unable to to create a User-defined rule that would eventually trigger gnome keyboard shortcut. It appears as if Gnome is ignoring those key strokes.

**Describe the solution you'd like**
I would like to trigger Gnome Workspace change shortcut (Super + Page Up)

**Describe alternatives you've considered**
N/A

**Additional context**
Rules definition:
%YAML 1.3
---
- Feature: THUMB WHEEL
- Rule:
  - Test: thumb_wheel_up
  - KeyPress: [Super_L, Page_Down]
- Rule:
  - Test: thumb_wheel_down
  - KeyPress: [Super_L, Page_Up]
...

**Comment by plameniliev** [comment]
sorry browsing through the issues, it appears this is a known issue already

**Comment by plameniliev** [comment]
eventually i did it invoking xdotool command

**Comment by pfps** [comment]
I believe that the issue here is that on some mice the thumb wheel produces gestures.  Solaar does not have the ability to divert gestures and have them trigger rules.   If there is no Thumb Wheel Diversion setting for your mouse then Solaar cannot divert it and cannot use it to trigger rules.
