### ISSUE TITLE
Too high PyYAML and psutil version requirements for RHEL/CentOS 8 base OS

### ISSUE THREAD

**Issue by rathann** [pwr-Solaar/Solaar#1418]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): **1.1.1**
- Distribution: **RHEL 8.5**
- Kernel version (ex. `uname -srmo`): `Linux 4.18.0-348.7.1.el8_5.x86_64 x86_64 GNU/Linux`
- Output of `solaar show` for the target device (if applicable): **N/A**

**Is your feature request related to a problem? Please describe.**
[setup.py](https://github.com/pwr-Solaar/Solaar/blob/master/setup.py#L63) lists requirements for PyYAML >= 5.1 and psutil >= 5.6.0. Unfortunately, RHEL8 and derivatives carry PyYAML 3.12 and psutil 5.4.3 built for the default python 3.6 in the base OS repository. Consequently, solaar is not installable without installing `python38` or `python39` stack (called module in RHEL/Fedora) that carry newer versions of these two. I've had a request from RHEL8 user to provide a package for RHEL8 in Fedora EPEL, hence this issue.

**Describe the solution you'd like**
If there's no specific reason for the higher versions, I'd like the requirements to be lowered to the versions listed above. I will provide a patch if agreed. I made a build for RHEL8 with these dependencies patched to lower versions and a user tested it and confirmed it seems to be working fine for him.

**Describe alternatives you've considered**
Regular packages in Fedora/EPEL may not depend on modular packages, only base OS. I considered maintaining solaar as a modular package, but this seems very complicated and I don't really have time for this. On the other hand, building it as a regular package adds minimal overhead to my Fedora package maintenance.

**Comment by rathann** [comment]
By the way, the PyYAML and psutil dependencies were introduced in 0427e5607e483bf9ef9f46a51c40129401cdb994 and then the psutil requirement was lowered to 5.6.0 in 7d0402a97f349c5285103f715af26c36fb1f8ef7 without mentioning a specific reason.

**Comment by pfps** [comment]
Some dependencies simply come from what was current in Fedora at the time.  If the versions of the dependent packages can be reduced without problem, then let's try to do so.
