### ISSUE TITLE
Add support for g733 lightspeed headphones

### ISSUE THREAD

**Issue by chrisbeardy** [pwr-Solaar/Solaar#1419]
It would be great to support the g733 lightspeed headphones. I have a pair of these so can help gather any information required to display stuff such as battery life etc. Not sure where to start adding support myself though...

**Comment by pfps** [comment]
If these headphones use HID++ then it should be possible to support them.  

To start the process of support:

Look at output of `lsusb` to find ID of device or receiver.
Provide output of `lsusb -vv -d xxxx:yyyy` where xxxx:yyyy is ID of device or receiver.

Look at output of `grep -H . /sys/class/hidraw/hidraw*/device/uevent` to find directory for the device or receiver, e.g., `/sys/class/hidraw/hidraw3/device/uevent:HID_NAME=Logitech USB Receiver`.
Provide contents of the file `/sys/class/hidraw/hidrawN/device/report_descriptor` where N was found above.  You will have to copy the contents to a file with txt extension before attaching it.
Or, better, install hidrd-convert and provide output of `hidrd-convert -o spec /sys/class/hidraw/hidrawN/device/report_descriptor`.

Here is an example of a report_descriptor

[report_descriptor.txt](https://github.com/pwr-Solaar/Solaar/files/7864687/report_descriptor.txt)
.

**Comment by chrisbeardy** [comment]
[lsusb.txt](https://github.com/pwr-Solaar/Solaar/files/7877519/lsusb.txt)

[report_descriptor.txt](https://github.com/pwr-Solaar/Solaar/files/7877540/report_descriptor.txt)

**Comment by chrisbeardy** [comment]
[hidrd.txt](https://github.com/pwr-Solaar/Solaar/files/7877544/hidrd.txt)

**Comment by pfps** [comment]
Looks good.  PR #1425 should support the headset, although there are likely some useful features of the headset that Solaar does not currently support (but might support soon if documentation for them can be obtained).   Please try out this PR.  Run `bin/solaar show` and post the output here.  This will list the features that the headset has to make it more likely that Solaar will support them.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1425, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1425/head:pull_1425
git checkout pull_1425
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1425
git fetch origin pull/1425/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
Does this PR fix your issue?

**Comment by chrisbeardy** [comment]
![image](https://user-images.githubusercontent.com/20585410/150415022-df6990c2-110d-4d8e-82c2-0a56957d823b.png)
[show.txt](https://github.com/pwr-Solaar/Solaar/files/7908251/show.txt)

Looks like it's there, nice quick work. Unfortunately from the show output, my interpretation is it looks like the battery info is not available, and it doesn't show as having a lightspeed receiver. Slighty annoying.

**Comment by pfps** [comment]
Yes, it looks like no battery information is reportable.   It might be possible to implement the last three features if I can get documentation on them and there are useful settings in these features.

The PR will likely be merged in after some other in-the-works PR.

**Comment by Klap-in** [comment]
Could it be that voltage info is part of the ADC measurements?

**Comment by pfps** [comment]
Unknown, as of now.

**Comment by chrisbeardy** [comment]
I would suspect the ADC measurement would be more for the headphone amplifiers.

**Comment by Possibly-Matt** [comment]
There's another Logitech based project which integrates a lot of information about a lot of Logitech headphones, might be worth a look at the repo to see what they're doing regarding battery and sidetone. 

https://github.com/Sapd/HeadsetControl

**Comment by pfps** [comment]
Thanks.  I took a look at it.  It hard-wires quite a bit of the information that can be derived from the device itself.  The code does seem to indicate that ADC MEASUREMENT contains battery information.

**Comment by Klap-in** [comment]
In some kernel code, there are also mentions of battery info in ADC measurement
https://lists.openwall.net/linux-kernel/2020/07/04/13 (random hit from some searching)
