### ISSUE TITLE
Autodetect or option to disable XTEST extension

### ISSUE THREAD

**Issue by benkibbey** [pwr-Solaar/Solaar#1426]
Some users like myself may not have the XTEST X11 extension enabled for one reason or another. A command line option or auto-detection of whether the extension is enabled or not would be nice. As it is now, I have to exit X11 then enable the extension in xorg.conf, then start X11, runt solaar to do whatever, then exit X11, disable XTEST again, then start X11 again. I realize that some functionality would be lost without the extension, but previous versions of solaar didn't have this requirement and worked fine for me.

**Comment by pfps** [comment]
That's a good idea.  

What happens if you run Solaar without the extension?

**Comment by benkibbey** [comment]
On Sun, Jan 16, 2022 at 04:36:50PM -0800, Peter F. Patel-Schneider wrote:
> That's a good idea.  
> 
> What happens if you run Solaar without the extension?

solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 224, in __getattr__
    function = self.display_extension_methods[attr]
KeyError: 'record_create_context'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/gtk.py", line 151, in main
    import solaar.ui as ui
  File "/usr/share/solaar/lib/solaar/ui/__init__.py", line 99, in <module>
    from . import notify, tray, window  # isort:skip  # noqa: E402
  File "/usr/share/solaar/lib/solaar/ui/tray.py", line 35, in <module>
    from .window import popup as _window_popup
  File "/usr/share/solaar/lib/solaar/ui/window.py", line 37, in <module>
    from .diversion_rules import show_window as _show_diversion_window
  File "/usr/share/solaar/lib/solaar/ui/diversion_rules.py", line 25, in <module>
    from logitech_receiver import diversion as _DIV
  File "/usr/share/solaar/lib/logitech_receiver/diversion.py", line 67, in <module>
    context = display.record_create_context(
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 227, in __getattr__
    raise AttributeError(attr)
AttributeError: record_create_context

**Comment by pfps** [comment]
Thanks.  I didn't realize that that code needed xtest enabled.

**Comment by pfps** [comment]
PR #1427 might solve this problem.  It tries to recover from the error by disabling part of rules processing.  Please run this PR with both xtest turned of and turned on and see whether you encounter any problems.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1427, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1427/head:pull_1427
git checkout pull_1427
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1427
git fetch origin pull/1427/head
git reset --hard FETCH_HEAD
```

**Comment by benkibbey** [comment]
Yeah, the pull request works fine. Thank you.

**Comment by pfps** [comment]
Excellent.
