### ISSUE TITLE
Option monochrome indicator or autostart enable / disable

### ISSUE THREAD

**Issue by hyphone** [pwr-Solaar/Solaar#1428]
Hello and good day,

first and foremost thank you very much for this wonderful application.

As a GNOME Shell user I would like to see a monochrome indicator icon or alternatively an option to disable the autostart feature.

![grafik](https://user-images.githubusercontent.com/6410852/149958194-8d840366-7689-4ed8-b1bb-b8ba8a98a1f2.png)

Currently it's the only coloured icon in my bar and it really does not blend well. I would therefore either prefer a monochrome icon or an option to hide it.

Thank you for reading and all the best

**Comment by pfps** [comment]
The Solaar autostart is either something that you set up or that is set up by the package you used to install Solaar.   So Solaar autostarting is not something that is part of Solaar. 

A symbolic version of the Solaar icons might be useful.

**Comment by hyphone** [comment]
Got it, might be the Fedora specific package then.

Thank you for the quick response!

**Comment by pfps** [comment]
PR #1430 uses a grey icon with option --battery-icons=symbolic
Please try it out.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1429, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1429/head:pull_1429
git checkout pull_1429
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1429
git fetch origin pull/1429/head
git reset --hard FETCH_HEAD
```

**Comment by hyphone** [comment]
Looks nice, thank you for the quick implementation!

![grafik](https://user-images.githubusercontent.com/6410852/149984614-a904cace-3736-41c1-94e5-513916dc112a.png)

Sidenote: I have just launched it without `--battery-icons=symbolic` and it still uses the icon by default it seems. Not sure if that's intended.

**Comment by pfps** [comment]
You mean it still uses the grey icon even without the option?  If there are no devices, then the grey icon has always been used.  The colored icon is mostly used when there is a device but there is no battery information.
