### ISSUE TITLE
Soloor gives a blank screen

### ISSUE THREAD

**Issue by zaax-uk** [pwr-Solaar/Solaar#1442]
After changing the batteries in my Logitech k270 keyboard it refused to connect to my laptop, yet the mouse does. I have tried
Solaar but it gives blank screen .

Ubuntu 20.04

NB i am not a coder, just a user who does not like M$

**Comment by pfps** [comment]
Please fill out the information requested in the bug report form.  Also please provide a screenshot of the Solaar main window.

**Comment by pfps** [comment]
Closing due to no response from submitter. 
If you are still experiencing the problem, you can reopen this issue.
