### ISSUE TITLE
How to contribute to the development?

### ISSUE THREAD

**Issue by MicaelJarniac** [pwr-Solaar/Solaar#1446]
Hi!

Solaar is amazing, and without it, using Logitech devices on Linux would be an absolute nightmare.

I wanted to know how one can contribute to the development, by means such as donations.

Logitech devices aren't necessarily cheap, and we're essentially paying Logitech not only for their hardware but also for their software, while getting none of their software for us to use.

It'd be more than fair to then help the developers of Solaar for providing us with the means for using those devices on Linux.

I usually struggle with free time, so contributing with code would be tricky for me, but I do usually have some spare money that I'd gladly use for helping to keep this amazing software alive.

I've read on #1297 that Solaar isn't currently accepting donations. Is that still the case? And if so, why?

**Comment by pfps** [comment]
I'm currently the main Solaar developer and I have a day job.   This makes it difficult for me to accept donations.  If someone wants to handle donations to help others contribute to Solaar that could be useful but I don't know whether other developers need any donations.   
What is currently needed more than anything else is someone who would be willing to take over being the main developer at some time in the future.

**Comment by SlySven** [comment]
:thinking: Would an alternative be for people to agree to source and donate specific instances of Logitech hardware to you or other developers to aide in getting the beasties to play nicely with Solaar? You could end up as a curator/keeper of a "development/testing" zoo...! :wink:

**Comment by pfps** [comment]
For current devices it is possible to get them from Logitech when they are needed to implement new features.   That was used, for example, for Bolt receivers and devices.

The situation is different for devices that are no longer being made.  Sending in older devices can be useful, except that it is unclear how many people are using old devices in Solaar.  Generally it is possible to get people who have these devices to help debug problems with them, but having more people sign up for this would be useful.

Signing up to test new features is also useful.  There are a few people who are asked to do this regularly but having more is always useful.  Generally what is required is to download and test new features every few months or so.  It is possible that this testing can damage the already-installed version of Solaar (by making changes to configuration files) or even, in very unusual circumstances, to damage devices.   The former has happened but the later has not so far (except that testing out pairing does use up non-volatile memory on some older devices).
