### ISSUE TITLE
Solaar did not detect icon theme

### ISSUE THREAD

**Issue by teissler** [pwr-Solaar/Solaar#145]
Solaar installed on my arch system with kde did not detect my oxygen theme.

Solaar version: 0.9.2

Here is the log of solaar started with debugging from the cli

$ solaar -ddd
15:57:47,404     INFO [MainThread] root: language de_DE (UTF-8), translations path None
15:57:47,409     INFO [MainThread] solaar.ui: application /io/github/pwr/solaar, registered True
15:57:47,412    DEBUG [MainThread] solaar.ui.icons: sys.path[0] = /usr/bin
15:57:47,412    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/icons
15:57:47,412    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
15:57:47,412    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/teissler/.local/share/solaar/icons
15:57:47,412    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
15:57:47,412    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
15:57:47,413    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/local/share/solaar/icons
15:57:47,413    DEBUG [MainThread] solaar.ui.icons: icon theme paths: ['/usr/share/solaar/icons', '/usr/share/solaar/icons', '/usr/share/solaar/icons', '/home/teissler/.local/share/icons', '/home/teissler/.icons', '/usr/share/icons', '/usr/share/icons', '/usr/local/share/icons', '/usr/share/pixmaps', '/usr/share/pixmaps', '/usr/local/share/pixmaps']
15:57:47,417    DEBUG [MainThread] solaar.ui.icons: detected icon sets: gpm False, oxygen False, gnome False, elementary False
15:57:47,417  WARNING [MainThread] solaar.ui.icons: failed to detect a known icon set
15:57:47,447    ERROR [MainThread] root: Could not find any typelib for AppIndicator3
15:57:47,447     INFO [MainThread] solaar.ui.tray: using StatusIcon
15:57:47,447     INFO [MainThread] solaar.ui.notify: starting desktop notifications
15:57:47,479  WARNING [MainThread] solaar.upower: failed to register suspend/resume callbacks
15:57:47,479     INFO [MainThread] solaar.listener: starting receiver listening threads

$ ls -al /usr/share/icons/oxygen/48x48/status/battery-*
-rw-r--r-- 1 root root 1784 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-040.png
-rw-r--r-- 1 root root 1929 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-060.png
-rw-r--r-- 1 root root 2065 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-080.png
-rw-r--r-- 1 root root 2056 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-100.png
-rw-r--r-- 1 root root 1676 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-caution.png
-rw-r--r-- 1 root root 3041 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-charging-040.png
-rw-r--r-- 1 root root 3227 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-charging-060.png
-rw-r--r-- 1 root root 3374 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-charging-080.png
-rw-r--r-- 1 root root 2973 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-charging-caution.png
-rw-r--r-- 1 root root 3014 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-charging-low.png
-rw-r--r-- 1 root root 3399 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-charging.png
-rw-r--r-- 1 root root 1671 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-low.png
-rw-r--r-- 1 root root 2813 22. Nov 2010  /usr/share/icons/oxygen/48x48/status/battery-missing.png

If you need more informations just let me know.

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original poster.
