### ISSUE TITLE
Help to get latest version on Debian 11

### ISSUE THREAD

**Issue by jokay** [pwr-Solaar/Solaar#1452]
**Information**

- Solaar version: 1.0.4
- Distribution: Debian 11
- Kernel version (ex. `uname -srmo`): Linux 5.10.0-11-amd64 x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable):

<details>
```
/usr/share/solaar/lib/solaar/ui/__init__.py:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Gtk
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 195, in run
    raise Exception('No devices found')
Exception: No devices found
```
</details>

**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Latest version on Debian **11** *(to have Logi Bolt support)*.

**Describe alternatives you've considered**

None.

**Additional context**

Tried the Ubuntu PPA for **impish** without success.

```sh
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  solaar
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
19 not fully installed or removed.
Need to get 0 B/243 kB of archives.
After this operation, 331 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
dpkg-deb: error: archive '/var/cache/apt/archives/solaar_1.1.1~ubuntu21.10.1_all.deb' uses unknown compression for member 'control.tar.zst', giving up
Traceback (most recent call last):
  File "/usr/share/apt-listchanges/DebianFiles.py", line 124, in readdeb
    output = subprocess.check_output(command)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dpkg-deb', '-f', '/var/cache/apt/archives/solaar_1.1.1~ubuntu21.10.1_all.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/apt-listchanges", line 323, in <module>
    main(config)
  File "/usr/bin/apt-listchanges", line 104, in main
    pkg = DebianFiles.Package(deb)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 358, in __init__
    parser.readdeb(self.path)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 127, in readdeb
    raise RuntimeError(_("Error processing '%(what)s': %(errmsg)s") %
RuntimeError: Error processing '/var/cache/apt/archives/solaar_1.1.1~ubuntu21.10.1_all.deb': Command '['dpkg-deb', '-f', '/var/cache/apt/archives/solaar_1.1.1~ubuntu21.10.1_all.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.
Preconfiguring packages ...
dpkg-deb: error: archive '/var/cache/apt/archives/solaar_1.1.1~ubuntu21.10.1_all
.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/solaar_1.1.1~ubuntu21.10.
1_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/solaar_1.1.1~ubuntu21.10.1_all.deb
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

This may be due to the usage of the unsupported **zst** compression, see [here](https://unix.stackexchange.com/a/669008).

**Comment by pfps** [comment]
This is a problem with the distribution, not Solaar per se.   @muzena Can you investigate?

You should be able to install using pip.   See https://pwr-solaar.github.io/Solaar/installation for more information.

**Comment by jokay** [comment]
> This is a problem with the distribution, not Solaar per se.

Yes, this is why I added "help" to the title :wink:

> You should be able to install using pip.   See https://pwr-solaar.github.io/Solaar/installation for more information.

Thx, will give it a try :+1:

**Comment by jokay** [comment]
Using `pip` *(and or `pip3`)* I get the same error as described in issue https://github.com/pwr-Solaar/Solaar/issues/782.

**Comment by pfps** [comment]
Installing using pip sometimes requires first installing some system packages.  Try installing this package using `apt`.

**Comment by jokay** [comment]
@pfps `python3-pyudev` is already installed.

```sh
$ sudo apt install python3-pyudev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pyudev is already the newest version (0.22.0-2).
The following package was automatically installed and is no longer required:
  python3-xlib
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by pfps** [comment]
Somehow Solaar can't find that package.  Try executing the following program

```
#!/usr/bin/env python3
import pyudev
```

**Comment by jokay** [comment]
Seems to work without showing any errors 🤷🏼‍♂️

**Comment by pfps** [comment]
Hmm.  Try running it as a command.  First make it executable and then `./test.py`.

**Comment by jokay** [comment]
```sh
$ chmod +x test.py 
$ ./test.py 
$
```

**Comment by pfps** [comment]
Hmm.  Let's try something closer to what Solaar does:

```
#!/usr/bin/env python3
import importlib
print (importlib.import_module('pyudev'))
```

**Comment by jokay** [comment]
```sh
$ ./test.py 
<module 'pyudev' from '/usr/lib/python3/dist-packages/pyudev/__init__.py'>
```

**Comment by jokay** [comment]
```sh
$ pip3 install --user pyudev
Requirement already satisfied: pyudev in /home/system/.local/lib/python3.7/site-packages (0.23.2)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from pyudev) (1.12.0)
```

**Comment by pfps** [comment]
Yes, this is very likely a version mismatch.  Python packages are different for each minor version of Python, so Solaar (which uses /usr/bin/env python3) is probably looking for 3.9 versions of the packages but the packages are installed for 3.7.

I think that to install pyudev for Python 3.9 you can run `python3.9 -m pip install pyudev` but you may have to first install the 3.9 version of pip and then use that.

**Comment by jokay** [comment]
```sh
$ python3.9 -m pip install pyudev
Requirement already satisfied: pyudev in /usr/lib/python3/dist-packages (0.22.0)
```

**Comment by jokay** [comment]
Ok, I tried now on a newly installed Debian ...

```sh
sudo apt install python3-venv python3-pip
pip3 install --user solaar
.local/bin/solaar
```

... and guess what, it works.

![image](https://user-images.githubusercontent.com/18613935/154535124-1dd47165-3153-4a34-b6eb-42608bd7fa47.png)

**Comment by jokay** [comment]
I guess we can close the issue :wink:

**Comment by pfps** [comment]
Good.  

The way Python finds packages is quite complex and failures are hard to figure out.

Just make sure that Solaar can talk to your devices (by installing the udev rule if necessary).

**Comment by jokay** [comment]
> This is ppa for Ubuntu not for Debian.

Sure, but I've seen other PPA for Ubuntu which works for Debian like the one for www.signal.im Desktop messenger :wink:
