### ISSUE TITLE
High activity (CPU usage) with K380 keyboard

### ISSUE THREAD

**Issue by markonius** [pwr-Solaar/Solaar#1455]
**Information**

- Solaar version 1.1.1:
- Distribution: Fedora 35
- Kernel version (ex. `uname -srmo`): `Linux 5.16.8-xm1.0.fc35.x86_64 x86_64 GNU/Linux`
- Output of `solaar show`:

<details>

```
Solaar version 1.1.1

USB and Bluetooth Devices

  1: Bluetooth Multi-Device Keyboard K380
     Device path  : /dev/hidraw12
     USB id       : 046d:B342
     Codename     : Keyboard K380
     Kind         : ?
     Protocol     : HID++ 4.5
     Serial number: ?
     Model ID:      B34200000000
     Unit ID:       A1000000
          Firmware: RBK 42.01.B0017
          Hardware: 72
     Supports 15 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Firmware RBK 42.01.B0017 B342C18DBFDD
            Firmware: Hardware  72 
            Unit ID: A1000000  Model ID: B34200000000  Transport IDs: {'btid': 'B342'}
         3: DEVICE NAME            {0005}   
            Name: Bluetooth Multi-Device Keyboard K380
            Kind: keyboard
         4: DEVICE FRIENDLY NAME   {0007}   
            Friendly Name: Keyboard K380
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
            Battery: 50%, discharging, next level 20%.
         7: CHANGE HOST            {1814}   
            Change Host        : 1:kiwi
         8: HOSTS INFO             {1815}   
            Host 0 (paired): kiwi
            Host 1 (paired): LAPTOP-F5P0R7SG
            Host 2 (paired): ib-mbaksic-l
         9: REPROG CONTROLS V4     {1B04}   
            Key/Button Diversion (saved): {'1': 0, '186': 0, '187': 0, '188': 0, '189': 0, '190': 0, '191': 0, '192': 0, '193': 0, '194': 0, '2': 0, '3': 0, '4': 0, '5': 0, '6': 0, '62': 0}
            Key/Button Diversion        : {'187': 0, '186': 0, '188': 0, '189': 0, '6': 0, '4': 0, '5': 0, '3': 0, '2': 0, '1': 0, '190': 0, '193': 0, '192': 0, '191': 0, '62': 0, '194': 0}
        10: unknown:1E00           {1E00}   hidden
        11: NEW FN INVERSION       {40A2}   
            Fn-swap: disabled
            Fn-swap default: enabled
            Swap Fx function (saved): False
            Swap Fx function        : False
        12: LOCK KEY STATE         {4220}   
        13: KEYBOARD DISABLE KEYS  {4521}   
            Disable keys (saved): {'1': False, '16': False, '4': False, '8': False}
            Disable keys        : {'1': False, '4': False, '8': False, '16': False}
        14: MULTIPLATFORM          {4531}   
            Set OS (saved): 1
            Set OS        : Linux
     Has 16 reprogrammable keys:
         0: Multiplatform Home        , default: MultiPlatform Home          => MultiPlatform Home        
             is FN, FN sensitive, reprogrammable, divertable, pos:4, group:0, group mask:empty
             reporting: default
         1: Multiplatform App Switch  , default: MultiPlatform App Switch    => MultiPlatform App Switch  
             is FN, FN sensitive, reprogrammable, divertable, pos:5, group:0, group mask:empty
             reporting: default
         2: Multiplatform Menu        , default: MultiPlatform Menu          => MultiPlatform Menu        
             is FN, FN sensitive, reprogrammable, divertable, pos:6, group:0, group mask:empty
             reporting: default
         3: Multiplatform Back        , default: MultiPlatform Back          => MultiPlatform Back        
             is FN, FN sensitive, reprogrammable, divertable, pos:7, group:0, group mask:empty
             reporting: default
         4: Previous                  , default: Previous                    => Previous                  
             is FN, FN sensitive, divertable, pos:8, group:0, group mask:empty
             reporting: default
         5: Play/Pause                , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, divertable, pos:9, group:0, group mask:empty
             reporting: default
         6: Next                      , default: Next                        => Next                      
             is FN, FN sensitive, divertable, pos:10, group:0, group mask:empty
             reporting: default
         7: Mute                      , default: Mute                        => Mute                      
             is FN, FN sensitive, divertable, pos:11, group:0, group mask:empty
             reporting: default
         8: Volume Down               , default: Volume Down                 => Volume Down               
             is FN, FN sensitive, divertable, pos:12, group:0, group mask:empty
             reporting: default
         9: Volume Up                 , default: Volume Up                   => Volume Up                 
             is FN, FN sensitive, divertable, pos:0, group:0, group mask:empty
             reporting: default
        10: Multiplatform Insert      , default: Switch Language             => Switch Language           
             FN sensitive, reprogrammable, divertable, pos:0, group:0, group mask:empty
             reporting: default
        11: Fn Up                     , default: unknown:0070                => unknown:0070              
             is FN, divertable, pos:0, group:0, group mask:empty
             reporting: default
        12: Fn Down                   , default: unknown:006F                => unknown:006F              
             is FN, divertable, pos:0, group:0, group mask:empty
             reporting: default
        13: Screen Capture/Print Screen, default: Screen Capture              => Screen Capture            
             is FN, reprogrammable, divertable, pos:0, group:0, group mask:empty
             reporting: default
        14: Search                    , default: Search Files                => Search Files              
             is FN, reprogrammable, divertable, pos:0, group:0, group mask:empty
             reporting: default
        15: Multiplatform Lock        , default: WindowsLock                 => WindowsLock               
             is FN, reprogrammable, divertable, pos:0, group:0, group mask:empty
             reporting: default
     Battery: 50%, discharging, next level 20%.

```
</details>

**Describe the bug**
When Logitech K380 is connected (via bluetooth), the CPU hovers around 4% of one logical core. Sometimes, the CPU gets slammed to 100% of one logical core.

I've run solaar -ddd, and the output is a constant stream of something. If I turn the keyboard off,  the constant output stops and the CPU usage drops to ~0%. If I turn the keyboard back on, the previous behaviour continues.

The output is here: [solaar.log](https://github.com/pwr-Solaar/Solaar/files/8102753/solaar.log).
The jump between 18:14:29 to 18:14:46 is the time the keyboard is off.

**Comment by pfps** [comment]
The keyboard is producing many no-op messages.  Does this continue for a long time, i.e., for several minutes?

**Comment by pfps** [comment]
PR #1456 should fix this issue as it should reduce the processing performed on these no-op notifications.   However, Solaar still needs to read and do a small amount of processing on the notifications so if the device sends a lot of no-op notifications Solaar will consume some resources.  Turning debugging to high (`-ddd`) will cause Solaar to consume more resources printing the notifications.

To test, run Solaar with the `-ddd` option and make sure that it works as before, even when the no-op notifications appear.  (Lines with `=> r[10 FF 0000 000000]` are indicative of these no-op notifications.)  Then run without the option and see whether Solaar is consuming too much CPU.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1456, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1456/head:pull_1456
git checkout pull_1456
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1456
git fetch origin pull/1456/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
@markonius Have you had any chance to test this PR?

**Comment by markonius** [comment]
Hi sorry, I wanted to run with `-ddd` for a while to catch that rare case when 100% of one core, but then I got busy with other things and kinda forgot. Sorry...
Yeah, the CPU usage got halved with this PR.

I assume the case when the CPU gets slammed to 100% would be a separate issue, then? I can open a separate issue about that if and when I manage to catch it. Thank you for the quick fix!

Side note, do you have any idea why my keyboard would be spamming no-ops? Could you point me in some direction to investigate? This happens on both Fedora 35 and Pop!_OS 20.4.

**Comment by pfps** [comment]
CPU at 100% may be the same problem or a different one.   I think, though, that creating a new issue for 100% usage should be a new issue.   If you run Solaar as `solaar -dd` you can quit from Solaar when it is consuming 100% CPU and get a backtrace report showing what it is doing at the time of the problem.

**Comment by markonius** [comment]
Yup, that was my plan, thanks!

**Comment by pfps** [comment]
There is some Logitech documentation saying that these notifications help the device respond quickly when it actually has information to send or things to do.  I have no idea why this should be the case, however.  Maybe the notifications are supposed to keep the Bluetooth connection active.

**Comment by markonius** [comment]
Oh, so, it's expecetd behaviour? In that case, should Solaar be expected to consume even less CPU processing these messages?

**Comment by pfps** [comment]
The messages are allowable, and are supposed to be somehow helpful.  Solaar does have to process them, and with PR #1456 Solaar did a lot of processing on these messages.  PR #1456 should cut this down to a minimum but Solaar still has to do a fair amount of processing on the messages and with all the overhead involved this could amount to 2% or so of a CPU.

If Solaar is consuming 100% because of these, or similar, messages then this is a problem with Solaar unless the device is spewing a lot of messages, which should cause added kernel time to be used.  (That is unless this additional kernel time ends up being allocated to Solaar, which just might be possible.)

**Comment by markonius** [comment]
OK thank you, once again. I consider this issue fixed.
