### ISSUE TITLE
diverting G keys causes Python exceptions when pressing M-keys

### ISSUE THREAD

**Issue by gregopet** [pwr-Solaar/Solaar#1463]
**Information**
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): `solaar 1.1.1`
- Distribution: Arch
- Kernel version (ex. `uname -srmo`): `Linux 5.16.2-arch1-1 x86_64 GNU/Linux`
- Output of `solaar show`:

<details>

```
Solaar version 1.1.1

USB and Bluetooth Devices

  1: G815 Mechanical Keyboard
     Device path  : /dev/hidraw1
     USB id       : 046d:C33F
     Codename     : G815
     Kind         : keyboard
     Protocol     : HID++ 4.2
     Polling rate : 1 ms (1000Hz)
     Serial number: 
     Model ID:      C33F00000000
     Unit ID:       34304708
        Bootloader: BOT 84.00.B0003
          Firmware: U1  31.02.B0018
             Other: 
             Other: 
             Other: 
     Supports 24 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 84.00.B0003 AAEA
            Firmware: Firmware U1  31.02.B0018 C33F
            Firmware: Other   
            Firmware: Other   
            Firmware: Other   
            Unit ID: 34304708  Model ID: C33F00000000  Transport IDs: {'usbid': 'C33F'}
         3: DEVICE NAME            {0005}   
            Name: G815 RGB MECHANICAL GAMING KEYBOARD
            Kind: keyboard
         4: RESET                  {0020}   
         5: DFUCONTROL SIGNED      {00C2}   
         6: DFU                    {00D0}   
         7: REPORT HID USAGE       {1BC0}   
         8: KEYBOARD DISABLE BY USAGE {4522}   
         9: KEYBOARD LAYOUT 2      {4540}   
        10: GKEY                   {8010}   
            Divert G Keys (saved): True
            Divert G Keys        : False
        11: MKEYS                  {8020}   
        12: MR                     {8030}   
        13: BRIGHTNESS CONTROL     {8040}   
        14: REPORT RATE            {8060}   
            Polling Rate (ms): 1
            Polling Rate (ms) (saved): 1
            Polling Rate (ms)        : 1
        15: RGB EFFECTS            {8071}   
        16: PER KEY LIGHTING V2    {8081}   
        17: ONBOARD PROFILES       {8100}   
            Device Mode: Host
        18: unknown:1801           {1801}   internal, hidden
        19: DEVICE RESET           {1802}   internal, hidden
        20: CONFIG DEVICE PROPS    {1806}   internal, hidden
        21: unknown:18B0           {18B0}   internal, hidden
        22: unknown:1E00           {1E00}   hidden
        23: unknown:1EB0           {1EB0}   internal, hidden
     Battery status unavailable.
```
</details>

**Describe the bug**
I cannot bind keys M1 through M3. When running Solaar with the -dd flag I get the following exception logged for both keyup and keydown:

```
11:59:30,798    ERROR [ReceiverListener:hidraw1] logitech_receiver.listener: processing Notification(11,255,0B,00,01000000000000000000000000000000)
Traceback (most recent call last):
  File "/home/gregor/src/Solaar/lib/logitech_receiver/listener.py", line 190, in run
    self._notifications_callback(n)
  File "/home/gregor/src/Solaar/lib/solaar/listener.py", line 192, in _notifications_handler
    _notifications.process(self.receiver, n)
  File "/home/gregor/src/Solaar/lib/logitech_receiver/notifications.py", line 60, in process
    return _process_device_notification(device, status, notification)
  File "/home/gregor/src/Solaar/lib/logitech_receiver/notifications.py", line 197, in _process_device_notification
    return _process_feature_notification(device, status, n, feature)
  File "/home/gregor/src/Solaar/lib/logitech_receiver/notifications.py", line 432, in _process_feature_notification
    _diversion.process_notification(device, status, n, feature)
  File "/home/gregor/src/Solaar/lib/logitech_receiver/diversion.py", line 850, in process_notification
    if new_m_keys_down & (0x01 << (i - 1)) and not m_keys_down & (0x01 << (i - 1)):
TypeError: unsupported operand type(s) for &: 'tuple' and 'int'
```

In addition, the MR key produces no exception, but I cannot bind it either.

**Comment by pfps** [comment]
There was a bug in unpacking the notifications.  Try PR #1464 


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1464, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1464/head:pull_1464
git checkout pull_1464
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1464
git fetch origin pull/1464/head
git reset --hard FETCH_HEAD
```

**Comment by gregopet** [comment]
The error has changed now:

```
14:13:12,720    ERROR [ReceiverListener:hidraw1] logitech_receiver.listener: processing Notification(11,255,0B,00,01000000000000000000000000000000)
Traceback (most recent call last):
  File "/home/gregor/src/Solaar/lib/logitech_receiver/listener.py", line 190, in run
    self._notifications_callback(n)
  File "/home/gregor/src/Solaar/lib/solaar/listener.py", line 192, in _notifications_handler
    _notifications.process(self.receiver, n)
  File "/home/gregor/src/Solaar/lib/logitech_receiver/notifications.py", line 60, in process
    return _process_device_notification(device, status, notification)
  File "/home/gregor/src/Solaar/lib/logitech_receiver/notifications.py", line 197, in _process_device_notification
    return _process_feature_notification(device, status, n, feature)
  File "/home/gregor/src/Solaar/lib/logitech_receiver/notifications.py", line 432, in _process_feature_notification
    _diversion.process_notification(device, status, n, feature)
  File "/home/gregor/src/Solaar/lib/logitech_receiver/diversion.py", line 851, in process_notification
    key_down = _CONTROL['M' + str(i + 8 * byte_idx)]
UnboundLocalError: local variable 'byte_idx' referenced before assignment
```

**Comment by pfps** [comment]
Yuck.  Another stupid bug.  As you can see, this code has never been exercised.
Please download the PR and try again.

**Comment by pfps** [comment]
By the way, what happens when the M keys are pressed but the G keys are not diverted?

**Comment by gregopet** [comment]
Yeah, it's frustrating writing code without being able to run it :disappointed: 

It works now after the second patch! I can map M1 through M4, as well as MR. If I turn off the "Divert G Keys" option, nothing happens. No message in the Solaar window (I've tried running it with `-dddd`), and nothing in `xev` either.

Out of curiousity, would it be possible to control which M key is lit up (by sending an event to the keyboard)? A bonus would be being able to poll this setting, too (but that can be simulated, more or less).

**Comment by gregopet** [comment]
I would be willing to test it, sure. If you point me to the relevant parts of the code I can also try various things - I am a programmer, admittedly with very limited Python experience, but trying a range of constants and so on is definitely something I could do.

**Comment by pfps** [comment]
OK try the PR again.  There should be a new setting for your keyboard - M-Key LEDs - with three bit settings in it, one for each M-Key.  Try toggling them and seeing whether the LEDs toggle.  Also try `bin/solaar show` and see whether the information for the MKEY feature looks reasonable.  Also try `bin/solaar config G815 m-key-leds M1 toggle` and see whether the M1 LED toggles.

Provide the output of `bin/solaar show`.

**Comment by pfps** [comment]
By the way, the code for this new setting is in lib/logitech_receiver/settings_templates.py class MKeyLEDs

**Comment by gregopet** [comment]
Great work!

- all the visual toggles work
- `bin/solaar config G815 m-key-leds M1 toggle` works (toggles the light on / off), for all three M
- output of `bin/solaar show` correctly shows the current state of LEDs

What doesn't work is the toggle for MR, which I _assume_ should also be possible to turn on (but have never managed to because the MR functionality doesn't work without Logitech's non-Linux software).

Output of `bin/solaar show`:

```
MKEYS CHOICES UNIVERSE NamedInts(NamedInt(1, 'M1'), NamedInt(2, 'M2'), NamedInt(4, 'M3'), NamedInt(8, 'M4'), NamedInt(16, 'M5'), NamedInt(32, 'M6'), NamedInt(64, 'M7'), NamedInt(128, 'M8')) {NamedInt(1, 'M1'): (None, 'Lights up the M1 key.'), NamedInt(2, 'M2'): (None, 'Lights up the M2 key.'), NamedInt(4, 'M3'): (None, 'Lights up the M3 key.'), NamedInt(8, 'M4'): (None, 'Lights up the M4 key.'), NamedInt(16, 'M5'): (None, 'Lights up the M5 key.'), NamedInt(32, 'M6'): (None, 'Lights up the M6 key.'), NamedInt(64, 'M7'): (None, 'Lights up the M7 key.'), NamedInt(128, 'M8'): (None, 'Lights up the M8 key.')}
Solaar version 1.1.1

USB and Bluetooth Devices

  1: G815 Mechanical Keyboard
     Device path  : /dev/hidraw1
     USB id       : 046d:C33F
     Codename     : G815
     Kind         : keyboard
     Protocol     : HID++ 4.2
     Polling rate : 1 ms (1000Hz)
     Serial number: 
     Model ID:      C33F00000000
     Unit ID:       34304708
        Bootloader: BOT 84.00.B0003
          Firmware: U1  31.02.B0018
             Other: 
             Other: 
             Other: 
     Supports 24 HID++ 2.0 features:
NUMBER OF MKEYS 3 [NamedInt(1, 'M1'), NamedInt(2, 'M2'), NamedInt(4, 'M3')]
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 84.00.B0003 AAEA
            Firmware: Firmware U1  31.02.B0018 C33F
            Firmware: Other   
            Firmware: Other   
            Firmware: Other   
            Unit ID: 34304708  Model ID: C33F00000000  Transport IDs: {'usbid': 'C33F'}
         3: DEVICE NAME            {0005}   
            Name: G815 RGB MECHANICAL GAMING KEYBOARD
            Kind: keyboard
         4: RESET                  {0020}   
         5: DFUCONTROL SIGNED      {00C2}   
         6: DFU                    {00D0}   
         7: REPORT HID USAGE       {1BC0}   
         8: KEYBOARD DISABLE BY USAGE {4522}   
         9: KEYBOARD LAYOUT 2      {4540}   
        10: GKEY                   {8010}   
            Divert G Keys (saved): True
            Divert G Keys        : False
        11: MKEYS                  {8020}   
            M-Key LEDs (saved): {M1:True, M2:False, M3:False}
            M-Key LEDs        : {M1:False, M2:False, M3:False}
        12: MR                     {8030}   
        13: BRIGHTNESS CONTROL     {8040}   
        14: REPORT RATE            {8060}   
            Polling Rate (ms): 1
            Polling Rate (ms) (saved): 1
            Polling Rate (ms)        : 1
        15: RGB EFFECTS            {8071}   
        16: PER KEY LIGHTING V2    {8081}   
        17: ONBOARD PROFILES       {8100}   
            Device Mode: Host
        18: unknown:1801           {1801}   internal, hidden
        19: DEVICE RESET           {1802}   internal, hidden
        20: CONFIG DEVICE PROPS    {1806}   internal, hidden
        21: unknown:18B0           {18B0}   internal, hidden
        22: unknown:1E00           {1E00}   hidden
        23: unknown:1EB0           {1EB0}   internal, hidden
     Battery status unavailable.
```

**Comment by pfps** [comment]
The MR key is a separate Logitech feature, which requires a separate implementation.

**Comment by gregopet** [comment]
The setting works :+1: 

All I would need now is a way to set & poll these settings via the rules. I could try taking some time over the weekend to implement this, if it helps?

**Comment by pfps** [comment]
What are you trying to do with the rules?

**Comment by gregopet** [comment]
Something like the Logitech software supports - having the G-keys change functions depending on what M-key is active (the M-keys act like radio buttons, only can be active at the same time). Should be quite possible to implement using Solaar rules, as long as I can set them in actions & poll the M-button states in conditions.

I'll use them depending on the context I am working in. I currently set up the G-keys for my most common scenario, coding - one button brings up my IDE, another the plain text editor, one brings up my GIT GUI and one the browser. But other times I'm mainly working on a DB or administering remote systems so I'd set up those contexts on other M profiles. Come to think of it, I could already achieve this with external scripts, but it would be hackish and having the M-states in Solaar would serve others as well (I took the keyboard home with me for the weekend but I'm not sure how much coding time I will manage to squeeze in - regardless, there will be other weekends if any contribution of mine would be welcome :smile: ).

As for the MR key, it is supposed to enable on-the-fly macro reassignment, but I don't need that if I'm scripting my keys manually anyway (I can imagine how it could be simulated of course, could be a fun task but I don't know if there's any demand from people who use Linux & Solaar). I'll use it for something else instead, muting the microphone. The LED is red (I've actually seen its color for the first time after your patch :laughing: ), so it should serve perfectly as a "recording" switch :smile: Since every video conferencing software decides to use their own keys for muting oneself, an on-keyboard button (with indicator!) should prove quite handy.

**Comment by pfps** [comment]
It looks like this requires that rules can access device state, which isn't currently possible but it might be possible to add this capability.

**Comment by pfps** [comment]
Try PR #1465, which adds Setting rule condition.  Comment in that PR, not here, please.

You should be able to create a rule like:
---
- Key: [G1, pressed]
- Setting: [null, m-key-leds,1,true]
- KeyPress: XF86_AudioLowerVolume
...
