### ISSUE TITLE
Help: How do I create rules for the M keys?

### ISSUE THREAD

**Issue by Hubro** [pwr-Solaar/Solaar#1482]
I have enabled "Divert G-keys" and launched Solaar with `-dd`. When I press my M1, M2, M3 and MR keys, respectively, I see this output in the terminal:

<pre>
10:34:01,784    DEBUG [ReceiverListener:hidraw17] logitech_receiver.base: (23) => r[11 01 1200 01000000000000000000000000000000]
10:34:01,784    DEBUG [ReceiverListener:hidraw17] logitech_receiver.notifications: <Device(1,407C,G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD,460DF756)>: notification for feature MKEYS, report 1, data 01000000000000000000000000000000
10:34:01,965    DEBUG [ReceiverListener:hidraw17] logitech_receiver.base: (23) => r[11 01 1200 00000000000000000000000000000000]
10:34:01,965    DEBUG [ReceiverListener:hidraw17] logitech_receiver.notifications: <Device(1,407C,G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD,460DF756)>: notification for feature MKEYS, report 1, data 00000000000000000000000000000000
10:34:03,438    DEBUG [ReceiverListener:hidraw17] logitech_receiver.base: (23) => r[11 01 1200 02000000000000000000000000000000]
10:34:03,438    DEBUG [ReceiverListener:hidraw17] logitech_receiver.notifications: <Device(1,407C,G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD,460DF756)>: notification for feature MKEYS, report 1, data 02000000000000000000000000000000
10:34:03,593    DEBUG [ReceiverListener:hidraw17] logitech_receiver.base: (23) => r[11 01 1200 00000000000000000000000000000000]
10:34:03,593    DEBUG [ReceiverListener:hidraw17] logitech_receiver.notifications: <Device(1,407C,G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD,460DF756)>: notification for feature MKEYS, report 1, data 00000000000000000000000000000000
10:34:04,141    DEBUG [ReceiverListener:hidraw17] logitech_receiver.base: (23) => r[11 01 1200 04000000000000000000000000000000]
10:34:04,141    DEBUG [ReceiverListener:hidraw17] logitech_receiver.notifications: <Device(1,407C,G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD,460DF756)>: notification for feature MKEYS, report 1, data 04000000000000000000000000000000
10:34:04,239    DEBUG [ReceiverListener:hidraw17] logitech_receiver.base: (23) => r[11 01 1200 00000000000000000000000000000000]
10:34:04,239    DEBUG [ReceiverListener:hidraw17] logitech_receiver.notifications: <Device(1,407C,G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD,460DF756)>: notification for feature MKEYS, report 1, data 00000000000000000000000000000000
10:34:05,172    DEBUG [ReceiverListener:hidraw17] logitech_receiver.base: (23) => r[11 01 1300 01000000000000000000000000000000]
10:34:05,172    DEBUG [ReceiverListener:hidraw17] logitech_receiver.notifications: <Device(1,407C,G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD,460DF756)>: notification for feature MR, report 1, data 01000000000000000000000000000000
10:34:05,310    DEBUG [ReceiverListener:hidraw17] logitech_receiver.base: (23) => r[11 01 1300 00000000000000000000000000000000]
10:34:05,310    DEBUG [ReceiverListener:hidraw17] logitech_receiver.notifications: <Device(1,407C,G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD,460DF756)>: notification for feature MR, report 1, data 00000000000000000000000000000000
</pre>

There are 6 notifications in total, the first being the key-down for M1, the second being the key-up for M1, the third being key-down for M2 and so on.

So it seems like all the information is here, I just need to know how to write the rule.

Reading the docs, it seems like I need to write a "Test" condition for this, but unfortunately the documentation for that is brief and had no examples:

> Test conditions consisting of a sequence of three or four integers use the first two to select bytes of the notification data. Writing this kind of test condition is not trivial. Three-element test conditions are true if the selected bytes bit-wise anded with its third element is non-zero. The value of these test conditions is the result of the and. Four-element test conditions are true if the selected bytes form a signed integer between the third and fourth elements. The value of these test condition is the signed value of the selected bytes if that is non-zero otherwise True.

After reading this, I barely have any more of a clue how to write this rule than I did before reading it. I need to write a sequence of 3 or 4 integers. Are they comma separated? Space separated? Are they formatted as decimal numbers? Binary numbers? No matter what I write in this box I get the error "Test string argument not name of a test". The first 2 numbers selects the bytes from the notification. How exactly? These docs are sorely missing a couple of examples to clarify these questions.

So I'm guessing I need to write an "And" rule like this:

- And
  - Feature: MKEYS(8020)
  - Test: `<first byte> <first byte> 01/02/04`

But how do I write the test?

**Comment by Hubro** [comment]
Alright I figured it out, but I had to dig around in [the source code](https://github.com/pwr-Solaar/Solaar/blob/94ff454aceb0899e4bca1bf0ec4a63600a9d9231/lib/logitech_receiver/diversion.py#L543) for a while. Fortunately it was Python.

Apparently lists of numbers can't be entered via the GUI, so I have to edit the rules file (`$HOME/.config/solaar/rules.yaml`).

The byte selection is apparently done by passing the first two numbers to a Python list slice, so selecting the first byte is done by passing 0 and 1 as the first two numbers. The selected byte(s) are AND-ed with the third number if only 3 numbers are passed, so if I want to match an exact number I need to pass 4 numbers. My final working rules for M1-3 are:

```yang
- And:
  - Feature: MKEYS
  - Test: [0, 1, 1, 1]
- Execute: [notify-send, M1 KEY PRESSED!]
...
---
- And:
  - Feature: MKEYS
  - Test: [0, 1, 2, 2]
- Execute: [notify-send, M2 KEY PRESSED!]
...
---
- And:
  - Feature: MKEYS
  - Test: [0, 1, 4, 4]
- Execute: [notify-send, M3 KEY PRESSED!]
...
```

The huge, massive bummer here is that, apparently, when I edit any other rules using the GUI, all the arrays I created in the config file are converted to strings, i.e. `- Test: '[0, 1, 1, 1]'`, which breaks the test...

**Comment by pfps** [comment]
The GUI should not be creating incorrect rules.  Can you provide before and after contents of your rules.yaml file?

**Comment by pfps** [comment]
Your rules will do the trick but there is an easier way to be sensitive to M and MR key presses - you can write Key conditions for these keys, just like Key conditions for diverted regular and G keys.   This requires using Solaar from the GitHub repository as this ability has not yet been in a release of Solaar.  The documentation has been updated to mention this and includes an example of a rule for these keys.

**Comment by Hubro** [comment]
```
➜ cat rules.yaml
%YAML 1.3
---
- And:
  - Feature: MKEYS
  - Test: [0, 1, 1, 1]
- Execute: [notify-send, M1 KEY PRESSED!]
...
---
- And:
  - Feature: MKEYS
  - Test: [0, 1, 2, 2]
- Execute: [notify-send, M2 KEY PRESSED!]
...
---
- And:
  - Feature: MKEYS
  - Test: [0, 1, 4, 4]
- Execute: [notify-send, M3 KEY PRESSED!]
...
---
- Feature: MR
- Execute: [notify-send, MR PRESSED!]
...
---
- Key: [G1, pressed]
- Execute: [notify-send, test]
...
---
- Key: [G5, pressed]
- KeyPress: [Control_L, Shift_L, M]
...
---
- Key: [G5, released]
- KeyPress: [Control_L, Shift_L, M]
...
```

Then I open the rules editor GUI and save changes (without actually making any changes).

```
➜ cat rules.yaml
%YAML 1.3
---
- And:
  - Feature: MKEYS
  - Test: '[0, 1, 1, 1]'
- Execute: [notify-send, M1 KEY PRESSED!]
...
---
- And:
  - Feature: MKEYS
  - Test: '[0, 1, 2, 2]'
- Execute: [notify-send, M2 KEY PRESSED!]
...
---
- And:
  - Feature: MKEYS
  - Test: '[0, 1, 4, 4]'
- Execute: [notify-send, M3 KEY PRESSED!]
...
---
- Feature: MR
- Execute: [notify-send, MR PRESSED!]
...
---
- Key: [G1, pressed]
- Execute: [notify-send, test]
...
---
- Key: [G5, pressed]
- KeyPress: [Control_L, Shift_L, M]
...
---
- Key: [G5, released]
- KeyPress: [Control_L, Shift_L, M]
...
```

As you see the arrays are not strings instead, and the rules no longer work.

**Comment by pfps** [comment]
Yes, that's a bug in the rule editor.   See Issue #1486

I'm assuming that the Key condition is working for you so I'm closing this issue.
