### ISSUE TITLE
error in SpeedChange setting template

### ISSUE THREAD

**Issue by pfps** [pwr-Solaar/Solaar#1484]
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository):  current 
- Distribution: Fedora

**Describe the bug**

Error in check_feature for feature speed-change

```
     INFO [ReceiverListener:hidraw2] logitech_receiver.settings_templates: check_feature dpi-sliding [REPROG CONTROLS V4] detected None
    ERROR [ReceiverListener:hidraw2] logitech_receiver.settings_templates: check_feature speed-change [POINTER SPEED] error Traceback (most recent call last):
e/[user]/src/Solaar/lib/logitech_receiver/settings_templates.py", line 1116, in check_feature
 = sclass.build(device)
e/[user]/src/Solaar/lib/logitech_receiver/settings.py", line 222, in build
class(cls.feature if cls.feature else cls.register, **cls.rw_options)
eatureRW.__init__() got an unexpected keyword argument 'name'
```

**Comment by pfps** [comment]
PR #1485 should fix this bug.

To test, first kill any running Solaar processes.  Then edit ~/.config/solaar/config.json and remove any information about 'speed-change'.  Then run Solaar as `bin/solaar -ddd`.   The above error should not appear and the mouse should have a setting for "Sensitivity Switching".

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1485, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1485/head:pull_1485
git checkout pull_1485
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1485
git fetch origin pull/1485/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
Sorry, there was a stupid typo.  It's hard to do good testing without having hardware that has the feature.  Please download the current version of the PR and try again (after removing "speed-change" from "_absent".

**Comment by adatum** [comment]
`bin/solaar -ddd` output from pull_1485 (1.1.1-117-ge271c09) after removing "speed-change" from ~/.config/solaar/config.json: https://gist.github.com/adatum/a6beee786a61fa8f3b26eb440f4f7bac

Again there are some errors, and I do not yet see a "Sensitivity Switching" option in Solaar.

**Comment by pfps** [comment]
@adatum The first error is probably because of bad data.  See the persistent remappable key issue for what do to.  The second error is a problem with a setting on your keyboard.  See issue #1487 for that.

**Comment by pfps** [comment]
@adatum  It looks as if your mouse doesn't have a dedicated DPI Change button, which is why there is no "Sensitivity Switching" setting.  There is also no other button that has the capabilities needed to support this setting.  So all is (now) working as expected, and thanks for helping to run down the bug in this setting.
