### ISSUE TITLE
Great Software

### ISSUE THREAD

**Issue by anathonous** [pwr-Solaar/Solaar#1488]
I don't have any issues. That's kinda the point. I don't want to leave any remarks about issues I am having or any negative comments.
I wanted to say Thank you. The software was super easy to use on Gentoo. app-misc/solaar installed with no issues. Was able to pair straight out of box. I would almost say it's easier to pair on linux than it probably is on windows or mac. Solid. 

I have a MX Master 2 mouse and a MX Keys mini. With a unify and bolt adapter. Both were recognized out of box.

Thanks.

-Nate

**Comment by pfps** [comment]
Thanks.  Bolt pairing was recently added and the interface is different from the interface in the Logitech software.  If you have any problems or requests pleases file an issue here or chime in on an existing issue.
