### ISSUE TITLE
M-Keys LEDs not working because of on-board profiles

### ISSUE THREAD

**Issue by Svenum** [pwr-Solaar/Solaar#1494]
Distro: Manjaro
Kernel: 5.16.2-2-rt19-MANJARO

If I Enable the LED for the M-Keys they will not glow until i enable the polling rate option.
If I enable the polling rate option, then the hole backlight except the M-Keys does not work.

**Comment by pfps** [comment]
That's a feature of the keyboard, as far as I can tell.   The keyboard has on-board profiles, which change how it behaves.  The only thing that Solaar does with on-board profiles is disable them so that the report rate can be changed.

**Comment by Svenum** [comment]
I know that already but the backlights do not only stay the same, they go out completely. They do not light at all.

**Comment by pfps** [comment]
I expect that the on-board profile also controls the backlight.
Can you provide the output of `solaar show` for the keyboard?

**Comment by Svenum** [comment]
The onboard Profile works but it does not autoload one.

Polling-Rate off:
```
Lightspeed Receiver
  Device path  : /dev/hidraw9
  USB id       : 046d:C541
  Serial       : DEE9CA1E
    Firmware   : 01.02.B0028
    Bootloader : 01.27
    Other      : 75.25
  Has 1 paired device(s) out of a maximum of 2.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=44

  1: G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD
     Device path  : None
     WPID         : 407C
     Codename     : G915 KEYBOARD
     Kind         : keyboard
     Protocol     : HID++ 4.2
     Polling rate : 8 ms (125Hz)
     Serial number: A502B0E1
     Model ID:      B354407CC33E
     Unit ID:       A502B0E1
        Bootloader: BOT 77.02.B0039
             Other: 
          Firmware: MPK 09.03.B0041
             Other: 
             Other: 
     The power switch is located on the top left corner.
     Supports 38 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 77.02.B0039 0000EC44D534
            Firmware: Other   
            Firmware: Firmware MPK 09.03.B0041 407C3791543D
            Firmware: Other   
            Firmware: Other   
            Unit ID: A502B0E1  Model ID: B354407CC33E  Transport IDs: {'btleid': 'B354', 'wpid': '407C', 'usbid': 'C33E'}
         3: DEVICE NAME            {0005}   
            Name: G915 WIRELESS RGB MECHANICAL GAMING KEYBOARD
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: DEVICE FRIENDLY NAME   {0007}   
            Friendly Name: G915 KEYBOARD
         7: BATTERY VOLTAGE        {1001}   
            Battery: 4118mV, discharging, 90.
         8: CHANGE HOST            {1814}   
            Change Host        : 1:Ni
         9: HOSTS INFO             {1815}   
            Host 0 (paired): Ni
            Host 1 (paired): 
        10: RGB EFFECTS            {8071}   
        11: PER KEY LIGHTING V2    {8081}   
        12: REPROG CONTROLS V4     {1B04}   
            Key/Button Diversion (saved): {Host Switch Channel 1:Regular, Host Switch Channel 2:Regular}
            Key/Button Diversion        : {Host Switch Channel 1:Regular, Host Switch Channel 2:Regular}
        13: REPORT HID USAGE       {1BC0}   
        14: ENCRYPTION             {4100}   
        15: KEYBOARD DISABLE BY USAGE {4522}   
        16: KEYBOARD LAYOUT 2      {4540}   
        17: GKEY                   {8010}   
            Divert G Keys (saved): True
            Divert G Keys        : False
        18: MKEYS                  {8020}   
            M-Key LEDs (saved): {M1:True, M2:False, M3:False}
            M-Key LEDs        : {M1:False, M2:False, M3:False}
        19: MR                     {8030}   
            MR-Key LED (saved): False
            MR-Key LED        : False
        20: BRIGHTNESS CONTROL     {8040}   
        21: ONBOARD PROFILES       {8100}   
            Device Mode: Host
        22: REPORT RATE            {8060}   
            Polling Rate (ms): 1
            Polling Rate (ms) (saved): 1
            Polling Rate (ms)        : 1
        23: DFUCONTROL SIGNED      {00C2}   
        24: DFU                    {00D0}   
        25: DEVICE RESET           {1802}   internal, hidden
        26: unknown:1803           {1803}   internal, hidden
        27: CONFIG DEVICE PROPS    {1806}   internal, hidden
        28: unknown:1813           {1813}   internal, hidden
        29: OOBSTATE               {1805}   internal, hidden
        30: unknown:1830           {1830}   internal, hidden
        31: unknown:1890           {1890}   internal, hidden
        32: unknown:1891           {1891}   internal, hidden
        33: unknown:18A1           {18A1}   internal, hidden
        34: unknown:1E00           {1E00}   hidden
        35: unknown:1EB0           {1EB0}   internal, hidden
        36: unknown:1861           {1861}   internal, hidden
        37: unknown:18B0           {18B0}   internal, hidden
     Has 2 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             divertable, persistently divertable, pos:1, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             divertable, persistently divertable, pos:2, group:0, group mask:empty
             reporting: default
     Battery: 4118mV, discharging, 90.

```

**Comment by pfps** [comment]
It looks as if this keyboard has complex lighting features, none of which are supported by Solaar.

**Comment by pfps** [comment]
@Svenum PR #1497 changes the Polling Rate setting so that it no longer disable onboard profiles.  Instead there is a new Onboard Profiles setting to explicitly disable onboard profiles.  Could you test out this PR on your keyboard to see whether it works correctly?  What should happen is that when you run this PR your rules no longer change the M-key LEDs unless you disable Onboard Profiles.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1497, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1497/head:pull_1497
git checkout pull_1497
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1497
git fetch origin pull/1497/head
git reset --hard FETCH_HEAD
```

**Comment by Svenum** [comment]
The Backlight now still works if you enable polling rate but the M-Keys does not work at all

**Comment by pfps** [comment]
Oops, there should have been a new setting - Onboard Profiles - but that wasn't added to the list of settings to check.  So please download the PR again and run Solaar as `bin/solaar -dd`.  The new setting should now show up.  If not, there is a bug and there should be an error message in the output from Solaar.

What is probably going to happen is that when Onboard Profiles are enabled, the M key LED setting doesn't do anything and neither does Polling Rate but the keyboard lighting still works.  When Onboard Profiles are disabled, both settings work but keyboard lighting doesn't.

**Comment by Svenum** [comment]
Ok, now is the setting there.
If "Onboard Profiles" is enabled the M-Keys does not work, but the backlights.
If instead "Onboard Profiles" is disabled the M-Keys does work, but the backlight does not.

**Comment by pfps** [comment]
That is as expected.  If you want to be able to control the M-key LEDs then you will have to live with the backlighting not working.  It may be possible for Solaar to control the backlighting for your keyboard but that is going to require an enhancement.

**Comment by Svenum** [comment]
Ok, should I wirte an enhancement or can you split this issue?

**Comment by pfps** [comment]
You should write an enhancement issue.
