### ISSUE TITLE
Support for K810

### ISSUE THREAD

**Issue by Jerther** [pwr-Solaar/Solaar#1500]
Hi!! :)

**Information**
- Solaar version 1.1.1.1
- Distribution: Fedora
- Kernel version: Linux 5.15.18-200.fc35.x86_64 x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable):

**Describe the solution you'd like**
When pairing a Logitech K810, I'd like it to appear in Solaar, just like the K380 does, so I can at least easily swap the function keys.

**Describe alternatives you've considered**
I use [another project](https://github.com/themech/k810_k811_fkeys) to swap the function keys. It works well, but I'd rather have that functionnality built in Solaar which I already use for other logitech devices.

**Additional context**
I have both the K810 and the K380 at hand. I wouldn't mind giving technical information and do some testing.

**Comment by pfps** [comment]
The 810 appears to be directly connected via a USB cable.   

To start the process of support:

Look at output of `lsusb` to find ID of device or receiver.
Provide output of `lsusb -vv -d xxxx:yyyy` where xxxx:yyyy is ID of device or receiver.

Look at output of `grep -H . /sys/class/hidraw/hidraw*/device/uevent` to find directory for the device or receiver, e.g., `/sys/class/hidraw/hidraw3/device/uevent:HID_NAME=Logitech USB Receiver`.
Provide contents of the file `/sys/class/hidraw/hidrawN/device/report_descriptor` where N was found above.  You will have to copy the contents to a file with txt extension before attaching it.
Or, better, install hidrd-convert and provide output of 
`hidrd-convert -o spec /sys/class/hidraw/hidrawN/device/report_descriptor`

**Comment by Jerther** [comment]
Yep, it's bluetooth! The K810 does have a USB port but it's only for charging as the keyboard has an internal battery (which is annoying and I already had to replace once...). I don't think the USB port registers as a device.

**Comment by pfps** [comment]
To start the process of support for a Logitech receiver or device:

Make sure the receiver or device is connected and active.

Look at output of `grep -H . /sys/class/hidraw/hidraw*/device/uevent` to find where information about the device is kept.
You are looking for a line like `/sys/class/hidraw/hidraw3/device/uevent:HID_NAME=<NAME>` where `<NAME>` is the name of your receiver or device.

Provide the contents of the file `/sys/class/hidraw/hidrawN/device/uevent` where N was found above.

Also attach contents of the file `/sys/class/hidraw/hidrawN/device/report_descriptor`.  You will have to copy the contents to a file with txt extension before attaching it.
Or, better, install hidrd-convert and provide output of `hidrd-convert -o spec /sys/class/hidraw/hidrawN/device/report_descriptor`

If your device can connect in multiple ways (via a receiver, via a USB cable, via Bluetooth) do this for each way it can connect.

**Comment by pfps** [comment]
Based on this code in https://github.com/themech/k810_k811_fkeys, it may be that the only problem is that the Bluetooth product IDs are outside of the range that Solaar looks for.
```
#define LOGITECH_VENDOR (__u32)0x046d
#define PRODUCT_K810 (__s16)0xb319
#define PRODUCT_K811 (__s16)0xb317
```
If you have Solaar cloned you could trying changing the line in lib/logitech_receiver/base_usb.py very near the end from
```
        if (product_id >= 0xB012 and product_id <= 0xB0FF or product_id >= 0xB317 and product_id <= 0xB3FF):
```
to
```
        if (product_id >= 0xB012 and product_id <= 0xB0FF or product_id >= 0xB32A and product_id <= 0xB3FF):
```

Then run solaar as `bin/Solaar -ddd` and see whether your keyboard is recognized and there are no errors.

**Comment by viniciusbm** [comment]
Correct me if I'm wrong, but it looks like "from" and "to" are swapped.

**Comment by pfps** [comment]
Yes.  I edited the wrong bit of the message.  The change should be *to* 0xB317.

**Comment by Jerther** [comment]
Ok so here are the files.
[uevent.txt](https://github.com/pwr-Solaar/Solaar/files/8279723/uevent.txt)
[report_descriptor.txt](https://github.com/pwr-Solaar/Solaar/files/8279731/report_descriptor.txt)  <-- this one has binary data

hidrd-convert fails:
```
$ hidrd-convert -o spec /sys/class/hidraw/hidraw3/device/report_descriptor
Failed to read input item at offset 319:
invalid item encountered
```

I'll try to run Solaar from the source

**Comment by pfps** [comment]
hidrd-convert fails for me also.  I wonder what the problem is.
Given that there is a program that sends HID++ commands to the keyboard, it must be an HID++ device so Solaar should pick it up if the product ID range is expanded.

**Comment by Jerther** [comment]
Alright, I made the modification to `base_usb.py` and ran `solaar -ddd`. (I had to run as sudo though)

Solaar recognizes my keyboard, and "Swap Fx function" seems to work well. The backlight option roller never goes away.

![image](https://user-images.githubusercontent.com/5856745/158718766-96f62079-0747-4f27-906a-83d8065a1197.png)

(I still love my M305. I just had to clean the tactile switches inside two times ;) )

**Comment by pfps** [comment]
The Backlight problem has been seen in another case.  See Issue #1487.

Please provide output of `sudo bin/solaar -ddd show`.

To be able to run Solaar without sudo you need to install the Solaar udev rule as described in the Solaar installation instructions.  Or you can install Solaar using dnf, which will install the rule.

**Comment by Jerther** [comment]
solaar is already installed with dnf.

Here are the results of `sudo bin/solaar -ddd show > debug_output_stdout.txt 2> debug_output_stderr.txt`

[debug_output_stdout.txt](https://github.com/pwr-Solaar/Solaar/files/8279899/debug_output_stdout.txt)
[debug_output_stderr.txt](https://github.com/pwr-Solaar/Solaar/files/8279902/debug_output_stderr.txt)

**Comment by pfps** [comment]
If the Solaar udev rule is installed, you shouldn't have to use sudo to run Solaar.   Please provide output of `ls -l /dev/hidraw*`.

**Comment by Jerther** [comment]
Here:

```
$ ls -l /dev/hidraw*
crw-rw----+ 1 root root 240, 0 Mar 16 21:05 /dev/hidraw0
crw-rw----+ 1 root root 240, 1 Mar 16 21:05 /dev/hidraw1
crw-rw----+ 1 root root 240, 2 Mar 16 21:05 /dev/hidraw2
crw-rw----+ 1 root root 240, 3 Mar 16 21:05 /dev/hidraw3
```

I meant I have to run the repo binary with sudo. The dnf installed version runs fine without sudo. I don't mind, really, as this is just for testing.

**Comment by pfps** [comment]
You shouldn't have to run the repo version of Solaar with sudo.   What error do you get if you don't use sudo?

**Comment by Jerther** [comment]
[no_sudo_debug_output_stderr.txt](https://github.com/pwr-Solaar/Solaar/files/8280000/no_sudo_debug_output_stderr.txt)
[no_sudo_debug_output_stdout.txt](https://github.com/pwr-Solaar/Solaar/files/8280001/no_sudo_debug_output_stdout.txt)

**Comment by pfps** [comment]
That's the same error that you would get running with sudo.   So you don't need to use sudo.

**Comment by Jerther** [comment]
I'm sorry, I just noticed the problem arises when I run solaar without the `show` argument. So `bin/solaar -ddd > no_sudo_no_show_debug_output_stdout.txt 2> no_sudo_no_show_debug_output_stderr.txt`

[no_sudo_no_show_debug_output_stderr.txt](https://github.com/pwr-Solaar/Solaar/files/8280469/no_sudo_no_show_debug_output_stderr.txt)
no_sudo_no_show_debug_output_stdout.txt is empty

**Comment by pfps** [comment]
Solaar wasn't expecting the value for the backlight that your keyboard produced.   The fix is simple.

**Comment by pfps** [comment]
I think you are running to Solaar programs.   The second one is trying to communicate with the first one, but the first one is an older version and can't handle the message from the second one.

The solution is to kill the running Solaar and only then run Solaar from your clone of the repo.

**Comment by Jerther** [comment]
Yep! That was it :)

**Comment by pfps** [comment]
PR #1502 has the fix to base_usb.py and also a fix for the backlight setting.  Please download and try it.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1502, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1502/head:pull_1502
git checkout pull_1502
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1502
git fetch origin pull/1502/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
Try `bin/solaar -dd show` with PR #1502 and provide the output (ideally with stdout and stderr together).  Then try `bin/solaar -dd` and provide its output.

**Comment by pfps** [comment]
Then try to change the value for Backlight and report what happens.

**Comment by Jerther** [comment]
Oh and by the way, to get the PR, I just `git reset --hard` then I used the command provided in the "code button" of the PR: `gh pr checkout 1502`

**Comment by pfps** [comment]
I'm seeing what looks like the same problem with Backlight as before.
Could you post the combined output from `bin/solaar -ddd`.  That shows the communication with the keyboard.

**Comment by Jerther** [comment]
`bin/solaar -ddd > 1502_ddd_output.txt 2>&1`
[1502_ddd_output.txt](https://github.com/pwr-Solaar/Solaar/files/8295298/1502_ddd_output.txt)

**Comment by pfps** [comment]
Thanks.  It might take a while to figure out just what is going wrong with Backlight.  I'll continue this in Issue #1487

**Comment by Jerther** [comment]
The support for the k810 has been working very well for a while. I've recently noticed a small regression though:

![image](https://github.com/pwr-Solaar/Solaar/assets/5856745/827971b8-078f-428a-9b8d-1896bd2bddf6)

I'm not sure when this started. I remember it used to display Illuminated Keyboard K810 or something, not "?? (B319)"

**Comment by pfps** [comment]
Please provide output of `solaar show` with the keyboard active.

**Comment by Jerther** [comment]
Here:

```
$ solaar show
solaar version 1.1.9

USB and Bluetooth Devices

  1: Illuminated Keyboard K810
     Device path  : /dev/hidraw4
     USB id       : 046d:B319
     Codename     : Illuminated
     Kind         : ?
     Protocol     : HID++ 2.0
     Serial number: 
     Model ID:      000000000000
     Unit ID:       00000000
          Firmware: RBK 12.02.B0025
          Hardware: 72
     Supports 12 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: FEATURE INFO           {0002} V0     
         3: DEVICE FW VERSION      {0003} V0     
            Firmware: Firmware RBK 12.02.B0025 
            Firmware: Hardware  72 
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         4: DEVICE NAME            {0005} V0     
            Name: Illuminated Keyboard K810
            Kind: keyboard
         5: FN INVERSION           {40A0} V0     
            Swap Fx function (saved): False
            Swap Fx function        : False
         6: NEW FN INVERSION       {40A2} V0     
            Fn-swap: disabled
            Fn-swap default: enabled
         7: BATTERY STATUS         {1000} V0     
            Battery: 50%, discharging, next level 20%.
         8: BACKLIGHT              {1981} V0     
         9: REPROG CONTROLS        {1B00} V0     
        10: REPROG CONTROLS V3     {1B03} V0     
        11: KEYBOARD LAYOUT        {4520} V0     
     Battery: 50%, discharging, next level 20%.
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : 0FC696D6
    Firmware   : 24.10.B0036
    Bootloader : 00.06
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=6

  1: Wireless Mouse M325
     Device path  : /dev/hidraw1
     WPID         : 400A
     Codename     : M325
     Kind         : mouse
     Protocol     : HID++ 2.0
     Polling rate : 8 ms (125Hz)
     Serial number: D72D97E9
     Model ID:      000000000000
     Unit ID:       00000000
          Firmware: RQM 40.01.B0018
     The power switch is located on the base.
     Supports 22 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V0     
            Firmware: Firmware RQM 40.01.B0018 400A
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         3: DEVICE NAME            {0005} V0     
            Name: Wireless Mouse M325
            Kind: mouse
         4: BATTERY STATUS         {1000} V0     
            Battery: 70%, discharging, next level 5%.
         5: unknown:1830           {1830} V0    internal, hidden 
         6: unknown:1850           {1850} V0    internal, hidden 
         7: unknown:1860           {1860} V0    internal, hidden 
         8: unknown:1890           {1890} V0    internal, hidden 
         9: unknown:18A0           {18A0} V0    internal, hidden 
        10: unknown:18C0           {18C0} V0    internal, hidden 
        11: WIRELESS DEVICE STATUS {1D4B} V0     
        12: unknown:1DF3           {1DF3} V0    internal, hidden 
        13: REPROG CONTROLS        {1B00} V0     
        14: REMAINING PAIRING      {1DF0} V0    hidden 
            Remaining Pairings: 118
        15: unknown:1E00           {1E00} V0    hidden 
        16: unknown:1E80           {1E80} V0    internal, hidden 
        17: unknown:1E90           {1E90} V0    internal, hidden 
        18: unknown:1F03           {1F03} V0    internal, hidden 
        19: VERTICAL SCROLLING     {2100} V0     
            Roller type: micro
            Ratchet per turn: 36
            Scroll lines: 0
        20: MOUSE POINTER          {2200} V0     
            DPI: 800
            Acceleration: low
            Override OS ballistics
            No vertical tuning, standard mice
        21: unknown:18B0           {18B0} V0    internal, hidden 
     Battery: 70%, discharging, next level 5%.


```

**Comment by pfps** [comment]
It appears that there is some race condition in determining the codename.   I think you will have to live  with it for now.
