### ISSUE TITLE
Allow scrolling over tray icon to switch between icons when there are fewer than 4 devices

### ISSUE THREAD

**Issue by p-himik** [pwr-Solaar/Solaar#1503]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): solaar 1.1.1, 1.1.1-135-gd115ade

**Is your feature request related to a problem? Please describe.**
It would be useful for me to be able to switch between which device the tray icon shows, even though I have only two devices.
[This commit](https://github.com/pwr-Solaar/Solaar/commit/6a66370ffe54a6b08f6f4b0e6fc76b0da2a23d30) has introduced such an ability, but for some reason it doesn't enable it for people with fewer than 4 devices.
Specifically, this is the block that does the check and where I think `4` should be replaced with `2` (or `3` if the receiver itself is in that list as well, although ideally those should probably be filtered out before the check):
https://github.com/pwr-Solaar/Solaar/blob/1ace3ef4f4cc90520d5607fde073e6cd1b66d56a/lib/solaar/ui/tray.py#L87-L90

**Comment by pfps** [comment]
Yes, that does seem silly.  Solaar should be able to scroll between two devices.  I'll fix the code.

On my system, this scrolling seems to be broken, with all scrolling coming out as scrolling up.   That's probably a bug in the system tray code, not something that can be fixed in Solaar.

**Comment by pfps** [comment]
PR #1504 should fix your problem.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1504, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1504/head:pull_1504
git checkout pull_1504
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1504
git fetch origin pull/1504/head
git reset --hard FETCH_HEAD
```

**Comment by p-himik** [comment]
> On my system, this scrolling seems to be broken, with all scrolling coming out as scrolling up

Yeah, noticed the same. Didn't think much of it since I have quite an unusual setup.

> PR https://github.com/pwr-Solaar/Solaar/pull/1504 should fix your problem.

Great, thanks!

**Comment by pfps** [comment]
I'm running XFCE, so not so unusual.  The system tray implementation has other problems as well.

Please try out PR #1504 and see whether it works for you.
