### ISSUE TITLE
I have a k400 plus but only the keyboard works but not its trackpad?  any ideas? thx also any to adjust double click speed in solaar? thx

### ISSUE THREAD

**Issue by kocoman1** [pwr-Solaar/Solaar#1510]
I have a k400 plus but only the keyboard works but not its trackpad?  any ideas? thx

also any to adjust double click speed in solaar? thx

**Comment by kocoman1** [comment]
Solaar does not process normal input from devices. It is thus unable to fix problems that arise from incorrect handling of mouse movements or keycodes by Linux drivers or other software.

how to diagnoise ?? thx

**Comment by pfps** [comment]
Something is gong wrong in how Linux is setting up your device, I guess, but I have no knowledge of how this happens.

**Comment by xaeiougit** [comment]
> how to diagnoise ?? thx
I had this problem and ran "xinput" and noticed the trackpad showed up as a virtual core pointer device.  So I unplugged the USB receiver and plugged it back in and the trackpad started working.  Others have reported a reboot also helps, but first see what "xinput" reports on your system and go from there...

**Comment by kocoman1** [comment]
a unplug and replug of the usb dongle fixed it.. should make a note on the app gui about that for keyboard/trackpad combo

**Comment by cargocultprogramming** [comment]
> a unplug and replug of the usb dongle fixed it.. should make a note on the app gui about that for keyboard/trackpad combo

Just bumping this comment. Had the same issue and this solved it.
