### ISSUE TITLE
Add key down and key up to rule actions

### ISSUE THREAD

**Issue by BrandonR541** [pwr-Solaar/Solaar#1517]
- Solaar version: 1.1.2
- Distribution: Manjaro KDE
- Kernel version: Linux 5.14.2.21.realtime1-1-rt x86_64 GNU/Linux

When using the rule editor, It would be great to add key up/down parameters to Actions as well as to Conditions key presses.

For example, being able to press and hold a G key to use alt+tab, but be able to release tab while holding down alt until the G key is released such that you can scroll through windows instead of just switching back and forth between the most recent windows.

Thanks for the great software!

**Comment by pfps** [comment]
That's possible, but a capability like this is going require more thought, as it is easy to run into problems with auto-repeating keys.

**Comment by pfps** [comment]
See also Issue #1625

**Comment by pfps** [comment]
PR #1626 partially adds this capability.  You currently have to edit your rules.yaml file directly as there is no support in the rule editor.   The KeyPress rule action can take a two-element list with the first element being a list of the key names and the second element being 'click', 'depress', or 'release'.    These three names are subject to change.  Suggestions for better naming are welcome.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1626, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1626/head:pull_1626
git checkout pull_1626
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1626
git fetch origin pull/1626/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
The current version of PR #1626 now has all that is needed for click, depress, and release options for KeyPress.  Please try it out.
