### ISSUE TITLE
Permission denied with 1.1.2

### ISSUE THREAD

**Issue by conraid** [pwr-Solaar/Solaar#1518]
Solaar version: 1.1.2
    Distribution: Slackware 
    Kernel version: Linux 5.17.0 x86_64 GNU/Linux
    KDE: 5.92
    PLASMA: 5.24.3

<details>

$:~ LANG=en_US solaar show
Solaar: error: [Errno 13] Permesso negato: '/dev/hidraw0'

</details>

Version 1.1.2 says that I don't have permissions to /dev/hidraw* (I have mouse MX Vertical and keyboard ERGO K860), and that if it's the first time it starts up take the receiver off and on. In fact this is how it works, but from this problem every reboot. 
Until a few days ago it worked, but with 1.1.0. Only try now 1.1.0 doesn't work either. What can it be?

I'm sorry fpr my bad english

Denug output:

`11:02:41,887    ERROR [MainThread] logitech_receiver.receiver: open DeviceInfo(path='/dev/hidraw0', vendor_id='046D', product_id='C52B', serial=None, release=None, manufacturer=None, product=None, interface=2, driver='logitech-djreceiver', bus_id=3, isDevice=None)
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/logitech_receiver/receiver.py", line 389, in open
    handle = _base.open_path(device_info.path)
  File "/usr/lib64/python3.9/site-packages/logitech_receiver/base.py", line 161, in open_path
    return _hid.open_path(path)
  File "/usr/lib64/python3.9/site-packages/hidapi/udev.py", line 294, in open_path
    return _os.open(device_path, _os.O_RDWR | _os.O_SYNC)
PermissionError: [Errno 13] Permesso negato: '/dev/hidraw0'
11:02:41,896    ERROR [MainThread] logitech_receiver.receiver: open DeviceInfo(path='/dev/hidraw2', vendor_id='046D', product_id='C52B', serial=None, release=None, manufacturer=None, product=None, interface=2, driver='logitech-djreceiver', bus_id=3, isDevice=None)
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/logitech_receiver/receiver.py", line 389, in open
    handle = _base.open_path(device_info.path)
  File "/usr/lib64/python3.9/site-packages/logitech_receiver/base.py", line 161, in open_path
    return _hid.open_path(path)
  File "/usr/lib64/python3.9/site-packages/hidapi/udev.py", line 294, in open_path
    return _os.open(device_path, _os.O_RDWR | _os.O_SYNC)
PermissionError: [Errno 13] Permesso negato: '/dev/hidraw2'
11:02:41,911    ERROR [MainThread] solaar.ui: error: permissions /dev/hidraw0
11:02:41,947    ERROR [MainThread] solaar.ui: error: permissions /dev/hidraw2
`

**Comment by conraid** [comment]
I solved it by uncommenting this line

# Grant members of the "plugdev" group access to receiver (useful for SSH users)
MODE="0660", GROUP="plugdev"

**Comment by conraid** [comment]
I solved it by uncommenting this line

`MODE="0660", GROUP="plugdev"`

**Comment by conraid** [comment]
I solved it by uncommenting the line
`
MODE="0660", GROUP="plugdev"`

**Comment by pfps** [comment]
It appears that something is going wrong in the Solaar udev rule in Slackware.  

Did you uninstall 1.1.2, install 1.1.0, and then reboot to check whether 1.1.0 works?  If not, the 1.1.0 Solaar udev rule might not have taken effect..

Can you provide a diff between the 1.1.2 and 1.1.0 udev rules that you see?

**Comment by conraid** [comment]
> It appears that something is going wrong in the Solaar udev rule in Slackware.
> 
> Did you uninstall 1.1.2, install 1.1.0, and then reboot to check whether 1.1.0 works? If not, the 1.1.0 Solaar udev rule might not have taken effect..
> 
> Can you provide a diff between the 1.1.2 and 1.1.0 udev rules that you see?


I did that test, and it didn't work. So I thought about udev (I had to think about it before, sorry) and I found the problem, as written before. We need to uncomment the line that gives permissions to plugdev

**Comment by pfps** [comment]
Was there any difference between the udev rule in 1.1.0 and 1.1.2?  As far as I can tell, the plugdev part of the rule has been commented out since 2013.

**Comment by conraid** [comment]
> Was there any difference between the udev rule in 1.1.0 and 1.1.2? As far as I can tell, the plugdev part of the rule has been commented out since 2013.

no, it's the same.
I use Slacware current, we can define it rolling release, probably for some coincidence, something has changed in the same period that I have updated solaar.
I'm sorry.
