### ISSUE TITLE
Current GIT version in PPA fails to start

### ISSUE THREAD

**Issue by mfraser** [pwr-Solaar/Solaar#1531]
Noticed that the Solaar icon was no longer visible in the system tray, so went to start it from within Konsole:

solaar 
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/gtk.py", line 151, in main
    import solaar.ui as ui
  File "/usr/share/solaar/lib/solaar/ui/__init__.py", line 101, in <module>
    from . import diversion_rules, notify, tray, window  # isort:skip  # noqa: E402
  File "/usr/share/solaar/lib/solaar/ui/diversion_rules.py", line 30, in <module>
    from logitech_receiver import diversion as _DIV
  File "/usr/share/solaar/lib/logitech_receiver/diversion.py", line 28, in <module>
    import evdev
ModuleNotFoundError: No module named 'evdev'

Had to install the package python3-evdev and now it works again.

**Comment by mthunter2** [comment]
Stable PPA too (v1.1.2-202204011859~ubuntu21.10.1)
Can confirm installing python3-evdev works

**Comment by pfps** [comment]
A dependency on evdev was added to Solaar about a month ago but wasn't reflected to the documentation or setup.py.   These were added recently.  Hopefully installing from the GIT PPA should again work without any measures.   The stable PPA may have to have a patch installed (by the person responsible for the distribution).

**Comment by S3NTYN3L** [comment]
I'm on Mint 20.3 (Ubuntu 20.04 focal) and seeing similar output when trying to change setting in the CLI.
I'm unable to change settings in the CLI but changing in GUI seems to work.
Running off of latest git PPA right now, but stable produces identical output.

IDK if this helps any but here's the CLI output:

```
$ solaar -dd config 1 fn-swap 0
16:39:28,471     INFO [MainThread] logitech_receiver.base: New lock 3
16:39:28,573     INFO [MainThread] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,3)>: found new device 1 (404D)
16:39:28,573     INFO [MainThread] logitech_receiver.base: New lock 11
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 205, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/share/solaar/lib/solaar/cli/config.py", line 174, in run
    setting = _settings_templates.check_feature_setting(dev, setting_name)
  File "/usr/share/solaar/lib/logitech_receiver/settings_templates.py", line 1227, in check_feature_setting
    feature = check_feature(device, setting)
  File "/usr/share/solaar/lib/logitech_receiver/settings_templates.py", line 1186, in check_feature
    if sclass.feature not in device.features:
  File "/usr/share/solaar/lib/logitech_receiver/hidpp20.py", line 316, in __contains__
    ivalue = int(featureId)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

```

**Comment by pfps** [comment]
@S3NTYN3L Your problem appears to be different.  Please file a separate bug report.

**Comment by pfps** [comment]
@muzena Is there anything that needs to be done to fix up the PPAs?

**Comment by muzena** [comment]
I update dependencies before 2 days
https://github.com/muzena/Solaar/blob/python3-new1/packaging/debian/control

**Comment by pfps** [comment]
OK, I'll close this issue then.
