### ISSUE TITLE
M705(406D) scroll too fast or too slow -- no middle of the road

### ISSUE THREAD

**Issue by pfortin** [pwr-Solaar/Solaar#1533]
This is the 2nd M705 I just bought; returned the first. Identical issue with scrolling.  On Mageia Linux Cauldron (pre-Mageia9), this mouse's scroll wheel is hard to control (using ksudoku as an example -- hard to describe problem using other apps):
ksudoku: scrolling through the numbers 1-9...
Scroll Wheel Resolution = on
  freewheel: extremely sensitive; but can make it move one number at a time
  click-mode: jumps 5 at a time (1>5, 9>4, etc)
Scroll Wheel Resolution = off
  freewheel: scrolls nicely through the numbers; general scrolling is SLOW
  click-mode: needs 4-5 clicks to scroll one number; general scrolling is VERY SLOW
No idea if it's possible; but it seems as though Scroll Wheel Resolution needs to be a slider, like Sensitivity (Pointer Speed)...

**Comment by pfps** [comment]
This is most likely the known issue documented in https://github.com/pwr-Solaar/Solaar:

- Some Linux drivers view or modify the setting Scroll Wheel Resolution to implement smooth scrolling. If Solaar changes this setting after the driver is set up scrolling can be either very fast or very slow. To fix this problem click on the icon at the right edge of the setting to set it to "Ignore this setting". The mouse has to be reset (e.g., by turning it off and on again) before this fix will take effect.

The driver in question is https://github.com/torvalds/linux/blob/master/drivers/hid/hid-logitech-hidpp.c   It has some other problems as well.  If there are problems when Solaar is not running I suggest you file a kernel bug.  It appears to me that there may be a race condition where a different message from the mouse is interpreted as the mouse's multiplication factor for hi-res scrolling.

Scroll Wheel Resolution is a binary setting, so there is no way for Solaar to do anything else.

**Comment by pfortin** [comment]
Thanks for the quick feedback...  Looks like I need to pass this on to the kernel folk.  It was a problem, only with this particular mouse before I installed Solaar; was hoping that could work around the problem. I suspected a binary setting; but never hurts to ask.  At least the ability to pair multiple devices on one UR is a bonus. Great work!  Thanks again!
