### ISSUE TITLE
Full support for Logitech MX Anywhere 3

### ISSUE THREAD

**Issue by BierDav** [pwr-Solaar/Solaar#1534]
Names of the other paired devices are missing.

**Comment by pfps** [comment]
Please provide output of `solaar show`.  That will show what is possible for the device.

**Comment by BierDav** [comment]
Oh I've installed it from the Ubuntu Store. This was an old version. Is fixed now

**Comment by BierDav** [comment]
Never mind, the hostnames are not present either

**Comment by pfps** [comment]
The MX Anywhere 3 does not have the HOSTS INFO feature, which is where the names of other hosts are recorded.
