### ISSUE TITLE
diversion.py:403:x11_focus_prog:AttributeError: 'int' object has no attribute 'get_full_property'

### ISSUE THREAD

**Issue by rathann** [pwr-Solaar/Solaar#1537]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): `1.1.2`
- Distribution: `Fedora 35 and 36`
- Kernel version (ex. `uname -srmo`): `5.16.18-200.fc35.x86_64` and `5.17.1-300.fc36.x86_64`
- Output of `solaar show`: `N/A`, I'll add it once reporters provide it.

<details>

```

```
</details>

**Describe the bug**
I've got multiple users reporting that solaar is crashing after logging in to GNOME session on both Fedora 35 and 36.

**To Reproduce**
1. Install solaar-1.1.2
2. Log out and log in to GNOME session
3. solaar crashes with the following backtrace:

<details>

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/logitech_receiver/diversion.py", line 317, in evaluate
    result = component.evaluate(feature, notification, device, status, result)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/diversion.py", line 317, in evaluate
    result = component.evaluate(feature, notification, device, status, result)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/diversion.py", line 317, in evaluate
    result = component.evaluate(feature, notification, device, status, result)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/diversion.py", line 443, in evaluate
    focus = x11_focus_prog() if x11 else None
  File "/usr/lib/python3.10/site-packages/logitech_receiver/diversion.py", line 403, in x11_focus_prog
    pid = window.get_full_property(NET_WM_PID, 0)
AttributeError: 'int' object has no attribute 'get_full_property'

Local variables in innermost frame:
pid: None
wm_class: None
window: 1
```

</details>

**Additional context**
Downstream bug reports:
* [Fedora 35 bug #2070753](https://bugzilla.redhat.com/show_bug.cgi?id=2070753)
* [Fedora 36 bug #2071252](https://bugzilla.redhat.com/show_bug.cgi?id=2071252)

**Comment by pfps** [comment]
Only the first bug report is public.
This appears to be a problem with the recent update to try to partly implement rules under Wayland.  But the code made the assumption that if the X11 libraries are available then it is possible to navigate through windows, which is not correct if Wayland is installed with X11 libraries being available.

An upgrade of rule processing in Wayland is almost done so expect a PR soon.  

In the meantime Solaar could be patched by removing the built-in rules by changing line 947 in diversion.py to 
```
if False:
```

**Comment by pfps** [comment]
PR #1530 should fix this problem.  To test download and run the PR and then run `bin/solaar -dd`.  There should be no crashes on Solaar startup and no warnings except maybe for a warning about uinput not being available.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1530, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1530/head:pull_1530
git checkout pull_1530
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1530
git fetch origin pull/1530/head
git reset --hard FETCH_HEAD
```
