### ISSUE TITLE
MX Master 3 - Thumb button function override

### ISSUE THREAD

**Issue by SmilerOnline** [pwr-Solaar/Solaar#1549]
- Solaar version: 1.1.2;
- Distribution: Manjaro;
- Kernel version: Linux 5.17.2-1-MANJARO x86_64 GNU/Linux;

I'm interested in the possibility of overriding the thumb/gesture button on my MX Master 3 to behave as a 'ctrl' key personally.
The goal would be to enable the possibility of achieving quick access to functionality such as zoom (ctrl+mouse wheel).

I find myself rarely ever using the thumb button in its current form as I find alt+tab to be rather annoying most of the time, though 'ctrl+mouse wheel' alone is something I can see myself using quite frequently, additional functions such as 'ctrl+other mouse buttons' I could imagine would extend the overall functionality of the mouse.

Though I'm aware that there is the gesture functionality feature, I find myself quickly turning that off to be honest as I'm not a big fan of physically moving my mouse around to simulate button presses and picking up the mouse, moving it back a bit and pushing it in the same direction again to repeat the task gets a little bit annoying eventually in my honest opinion.

**Comment by pfps** [comment]
This looks like a special case of PR #1517.  One problem with key down actions is that it is very possible to make your system inoperable by leaving the control (or some other) key down making it impossible to perform left-click actions.

**Comment by pfps** [comment]
Closing.  Functionality would be incorporated in #1517, although that enhancement might not be implemented.
