### ISSUE TITLE
Showing GUI when system start up

### ISSUE THREAD

**Issue by kylefelipe** [pwr-Solaar/Solaar#1556]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.1
- Distribution: Debian SID 
- Kernel version: Linux 5.16.0-6-amd64 x86_64 GNU/Linux
- Output of `solaar show`:

<details>

```
N/A
```
</details>

**Describe the bug**
Keeps showing GUI at system startup even with `--window=hide` flag at solaar.desktop

**To Reproduce**  
N/A

**Screenshots**  
N/A

**Additional context**  
N/A

**Comment by pfps** [comment]
If Solaar is already running, running it again will just open up the window of the already-running Solaar.  If you run Solaar from a terminal and the command you run quickly terminates this is what is happening.

**Comment by pfps** [comment]
I suspect that you are starting up Solaar in two different ways at startup.  Determining what is going on would be more difficult here.  Try disabling a way that you know about and see whether Solaar still starts.  (It also might be that the way you know about is being invoked twice, so you might have to add some sort of debugging method, like using -dd and sending stderr to a file - just make sure that the file name changes for each invokation.)

**Comment by kylefelipe** [comment]
Thx @pfps,  found a second configuration to start solaar,
