### ISSUE TITLE
documentation: double readme file and outdated list of translations

### ISSUE THREAD

**Issue by Danfro** [pwr-Solaar/Solaar#1573]
1. The main folder contains a [README](https://github.com/pwr-Solaar/Solaar/blob/master/README) and a [README.md](https://github.com/pwr-Solaar/Solaar/blob/master/README.md) file. I would guess the first one should be deleted, right?
2. The doc for translations [i18n.md](https://github.com/pwr-Solaar/Solaar/blob/master/docs/i18n.md#supported-languages) does list a few languages as "supported". But the list of ._po_ [files](https://github.com/pwr-Solaar/Solaar/tree/master/po) is much longer. I assume this list is outdated? Maybe drop the list since maintaining it may be a lot of manual work and rather link to the _/po_ folder of the repo for supported languages? I know, that would drop the reference of the translators. Maybe a link to [contributors](https://github.com/pwr-Solaar/Solaar/graphs/contributors) might cover that to some extend?

**Comment by pfps** [comment]
The two READMEs are a bit of a historical artifact. Removing README should be possible.

docs/i18n.md can be simply changed to list those as some of the translations.

**Comment by Danfro** [comment]
Hmm, when preparing another [PR](https://github.com/pwr-Solaar/Solaar/pull/1574), changes I made in README.md did end up as changes to index.md. 
So just to be sure, regarding 1 is this some magic I just don't know how the docs are set up here? :angel:

**Comment by pfps** [comment]
There are symbolic links involved.

**Comment by pfps** [comment]
Fixed by PR #1573
