### ISSUE TITLE
Smooth scrolling absurdly fast for Performance MX

### ISSUE THREAD

**Issue by AlicesReflexion** [pwr-Solaar/Solaar#158]
Right now, the option to use Logitech's Stepless/Smooth scrolling is available in Solaar, but it's not particularly useful because everything scrolls at an unusably fast speed.

An ideal solution would probably be to let the user set scroll sensitivity.

**Comment by w-shackleton** [comment]
Currently working on getting smooth scrolling working properly as it does in the windows implementation (smooth when wheel in smooth mode, non-smooth otherwise)

**Comment by vivin** [comment]
I'm using a PerformanceMouse MX. I added the PPA above and installed `xserver-xorg-input-evdev`, but `xinput` still doesn't show the `"Evdev Scrolling Distance"` property. I'm wondering if I'm missing something or perhaps haven't set up something right?

**Comment by vivin** [comment]
This is working now. I just had to log out and log back in.

**Comment by MagicFab** [comment]
This also worked in Debian 8:
- Install the xinput package
- Issue this command:
xinput (shows my mouse as device #13)
xinput set-prop 13 "Evdev Scrolling Distance" 8 1 1 # for smooth scroll

Scrolling now works at expected usable speeds.

**Comment by w-shackleton** [comment]
FWIW `xinput set-prop "Logitech Performance MX" "Evdev Scrolling Distance" -8 1 1` also works :smile:

**Comment by strelec** [comment]
How to do that on wayland?

**Comment by metopa** [comment]
Works perfect to me as well (Kubuntu 15.04). Thank you!

**Comment by vootey** [comment]
Any news on this?
Setting xinput set-prop <devnum> "Evdev Scrolling Distance" 8 1 1 seems to fix scrolling in firefox, but breaks scrolling completely in e.g. dolphin.
When I do a logout/login the original setting is restored, i.e. 1 1 1.

What do I do wrong?

**Comment by w-shackleton** [comment]
Lots of programs don't support updating smooth scrolling on the fly - try closing and re-opening Dolphin.

The X server doesn't remember parameters like that - you'll need to get that command to run every time you log in.

**Comment by vootey** [comment]
Ah, thanks for answering.
Hm, restarting dolphin doesn't help. I suspect this is a problem within dolphin, since other applications behave fine.

**Comment by carewolf** [comment]
That works great with Qt5 applications too. Still wish the solaar commands would make it into either xinput or the kernel though

**Comment by w-shackleton** [comment]
So the real place to solve this would be in the kernel / in X11 (I'm not quite sure which one). This is something I'd like to do at some point, time permitting.

Basically, this mouse has a mode (incorrectly labelled "side scrolling" in Solaar) that switches it into "I'm being controlled by a Logitech driver, not just a mouse driver" mode (the off setting in Solaar). In this mode the mouse gives more raw outputs rather than those a normal mouse would.

The main difference is that the scroll wheel lock switch gets reported as a mouse button. This allows the driver to determine if it is in smooth or clicky mode. The other difference is that in smooth scrolling mode (ie. the smooth scrolling switch in Solaar) the left/right side scrolling outputs output really, really fast.

Such a Linux driver could enable the smooth scrolling flag on the mouse if and only if the hardware scroll lock is disabled. In this mode it could then adjust the xinput2 scroll rate (currently set using `xinput set-prop`) on the vertical _and_ horizontal axes such that when disabled the mouse smoothly scrolls in both directions, but when the scroll lock is engaged it acts as a classic scroll wheel. This is what the windows driver does with the exception that it only goes into smooth mode if it knows the application can support it. Due to the design of the Linux input system this would be true for all apps, simplifying the task.

This is something I'd love to have a go at writing but I'm currently far too busy with university. Perhaps I'll have a stab over the summer (when I might buy an MX master too).

**Comment by haarp** [comment]
@w-shackleton 

> Basically, this mouse has a mode (incorrectly labelled "side scrolling" in Solaar) that switches it into "I'm being controlled by a Logitech driver, not just a mouse driver" mode (the off setting in Solaar). In this mode the mouse gives more raw outputs rather than those a normal mouse would.

Correct. And I think this really needs to be relabelled.

(It can also break left-clicking when the mode is enabled and the wheel clutch disengaged. No idea what's happening there)

> Such a Linux driver could enable the smooth scrolling flag on the mouse if and only if the hardware scroll lock is disabled. In this mode it could then adjust the xinput2 scroll rate (currently set using xinput set-prop) on the vertical and horizontal axes such that when disabled the mouse smoothly scrolls in both directions, but when the scroll lock is engaged it acts as a classic scroll wheel. This is what the windows driver does with the exception that it only goes into smooth mode if it knows the application can support it. Due to the design of the Linux input system this would be true for all apps, simplifying the task.

> This is something I'd love to have a go at writing but I'm currently far too busy with university. Perhaps I'll have a stab over the summer (when I might buy an MX master too).

This would be a great feature to have! Sometimes it's the little things that subtly improve the experience and feel of software :)

For a good reference, you could have a look at the (currently not yet merged) patch that enables smooth scrolling for Evdev's wheel emulation: https://lists.x.org/archives/xorg-devel/2014-January/039892.html

Do Logitech mice use evdev? I don't really know how to check.

**Comment by w-shackleton** [comment]
`xinput list-props <devnum>` reveals my Performance MX uses evdev on Ubuntu 16.04.

Smooth scrolling on Linux seems to have become my life mission.. I've recently got code [accepted into Chromium](https://codereview.chromium.org/688253002/) to support it too.

**Comment by heynnema** [comment]
Check out the add-on Smoothwheel. I works in Thunderbird and Firefox. Makes you scroll wheel nice and smooth.

Cheers, Al

**Comment by heynnema** [comment]
It works in...

**Comment by hyperair** [comment]
@strelec Not sure if you're still looking for a wayland solution but here's mine which also works with the libinput driver for X11 on the M705:

`/etc/udev/hwdb.d/99-m705-click-angle.hwdb`:
```
mouse:*:name:Logitech M705:                             
 MOUSE_DPI=800@166                                      
 MOUSE_WHEEL_CLICK_ANGLE=3 
```

**Comment by RomuloPBenedetti** [comment]
Is this solved? I still get steppy scrolling everywhere with "Wheel Resolution" enabled, and still an absurd sensitivity, even a middle click in a link is pretty much impossible.

**Comment by haarp** [comment]
It seems libinput does not yet have the API to change ```MOUSE_WHEEL_CLICK_ANGLE``` on-the-fly. See the last comments in ths bug:

https://bugs.freedesktop.org/show_bug.cgi?id=92772

I doubt they will be implemented anytime soon. Maybe a new freedesktop bug should be opened, as this one is closed already.

**Comment by RomuloPBenedetti** [comment]
@hyperair I've tried your solution with no success

    mouse:*:name:Logitech MX Master 2S:                             
      MOUSE_DPI=4000@125                                      
      MOUSE_WHEEL_CLICK_ANGLE=3 

and also tried to match with

    evdev:input:*:name:Logitech MX Master 2S:   
and
    
    libinput:name:Logitech MX Master 2S:

**Comment by arooni** [comment]
On ubuntu 18.04 I already have xserver-xorg-input-evdev but can't get access to the evdev value.  

solarr is great but i can't really use my scroll wheel grr.. 

0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
[I]  ~/D/Calibre Library  install xserver-xorg-input-evdev
Reading package lists... Done
Building dependency tree
Reading state information... Done
xserver-xorg-input-evdev is already the newest version (1:2.10.5-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
[I]  ~/D/Calibre Library  xinput list-props 18
Device 'Logitech Anywhere MX':
        Device Enabled (141):   1
        Coordinate Transformation Matrix (143): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
        libinput Natural Scrolling Enabled (276):       0
        libinput Natural Scrolling Enabled Default (277):       0
        libinput Scroll Methods Available (278):        0, 0, 1
        libinput Scroll Method Enabled (279):   0, 0, 0
        libinput Scroll Method Enabled Default (280):   0, 0, 0
        libinput Button Scrolling Button (281): 2
        libinput Button Scrolling Button Default (282): 2
        libinput Middle Emulation Enabled (283):        0
        libinput Middle Emulation Enabled Default (284):        0
        libinput Accel Speed (285):     -0.165468
        libinput Accel Speed Default (286):     0.000000
        libinput Accel Profiles Available (287):        1, 1
        libinput Accel Profile Enabled (288):   1, 0
        libinput Accel Profile Enabled Default (289):   1, 0
        libinput Left Handed Enabled (290):     0
        libinput Left Handed Enabled Default (291):     0
        libinput Send Events Modes Available (261):     1, 0
        libinput Send Events Mode Enabled (262):        0, 0
        libinput Send Events Mode Enabled Default (263):        0, 0
        Device Node (264):      "/dev/input/event5"
        Device Product ID (265):        1133, 4119
        libinput Drag Lock Buttons (292):       <no items>
        libinput Horizontal Scroll Enabled (293):       1
[I]  ~/D/Calibre Library  cd ../P2P\ Downloads/^C
[I]  ~/D/Calibre Library  xinput set-prop 18 'Evdev Scrolling Distance' 3 1 1
property 'Evdev Scrolling Distance' doesn't exist, you need to specify its type and format
[I]  ✘  ~/D/Calibre Library 

**Comment by hyperair** [comment]
You're using libinput, not evdev (note all the libinput properties). You'll need to do some udev tweaks like I described in https://github.com/pwr/Solaar/issues/158#issuecomment-333737178 and https://github.com/pwr/Solaar/issues/158#issuecomment-385874082

**Comment by jturcotte** [comment]
For those like me wondering why this doesn't work out of the box when touchpads already have smooth scrolling, here is what seems to be the proper solution, still pending in libinput: https://gitlab.freedesktop.org/libinput/libinput/merge_requests/139

**Comment by pfps** [comment]
It looks to me as if this enhancement request is out of scope for Solaar.

**Comment by markonius** [comment]
@hyperair Hi! I can't get this to work on Fedora 31. 
I've got in  /etc/udev/hwdb.d/99-mxanywhere2-wheel-angle.hwdb:
```
mouse:*:name:Logitech MX Anywhere 2:                             
 MOUSE_WHEEL_CLICK_ANGLE=3
```

`udevadm info --query=all --name=/dev/input/event8` reports`E: MOUSE_WHEEL_CLICK_ANGLE=3
`

But the mouse scrolling speed is still very fast. Do you have any ideas?

**Comment by hyperair** [comment]
@markonius Try upgrading your kernel and libinput -- the kernel now reports the scroll tick multiplier (you can see it in `dmesg` when you connect your mouse), and libinput probably no longer reads `MOUSE_WHEEL_CLICK_ANGLE`.

**Comment by markonius** [comment]
@hyperair Thanks for your efforts!

**Comment by pfps** [comment]
Closing as out of scope

**Comment by sibblegp** [comment]
I just spent hours trying to fix this and turned the mouse off and back on and it worked.

**Comment by pfps** [comment]
See Known Issues in https://github.com/pwr-Solaar/Solaar
