### ISSUE TITLE
RFE: move to pytest

### ISSUE THREAD

**Issue by kloczek** [pwr-Solaar/Solaar#1581]
Looks like solaar still is using `setup.py test` as test suite.
This is already marked as deprecated which is printed on calling test suite:
```console
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
/usr/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.17.1-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
```
The best would be move all test units to pytest.

**Comment by pfps** [comment]
What is triggering this as a test?

**Comment by pfps** [comment]
OK, but what was the command that generated the above messages?

**Comment by kloczek** [comment]
`python setup.py test`

**Comment by pfps** [comment]
There aren't any tests in setup.py, and as far as I know there is nothing in Solaar that uses this command.  So I don't see that there is anything to be done here.

Note that this is separate from actually having a test suite for Solaar which indeed should use pytest.

**Comment by pfps** [comment]
As setup.py doesn't actually have any tests, I'm closing this issue.  If there is something specific that should be done to indicate that setup.py isn't to be used for tests, the issue can be reopened with a description of what should be done
