### ISSUE TITLE
Solaar displaying AttributeErrors in Fedora 20

### ISSUE THREAD

**Issue by karlitos** [pwr-Solaar/Solaar#159]
If I start Solaar from the commnad line in Fedora 20 with --debug parameter it prints AttributeError messages on every mouse movement:

<pre><code>
$ solaar --debug
11:49:11,528     INFO [MainThread] root: language cs_CZ (UTF-8), translations path None
11:49:11,533     INFO [MainThread] solaar.ui: application /io/github/pwr/solaar, registered True
11:49:11,567    ERROR [MainThread] root: Could not find any typelib for AppIndicator3
11:49:11,567     INFO [MainThread] solaar.ui.tray: using StatusIcon
11:49:11,567     INFO [MainThread] solaar.ui.notify: starting desktop notifications
11:49:11,606     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
11:49:11,607     INFO [MainThread] solaar.listener: starting receiver listening threads
11:49:11,609     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path=u'/dev/hidraw0', vendor_id=u'046d', product_id=u'c52b', serial=None, release='1201', manufacturer='Logitech', product='USB Receiver', interface=2, driver=u'logitech-djreceiver')
11:49:11,614     INFO [ReceiverListener:hidraw0] logitech_receiver.listener: started with <UnifyingReceiver(/dev/hidraw0,11)> (11)
11:49:11,614     INFO [ReceiverListener:hidraw0] solaar.listener: <UnifyingReceiver(/dev/hidraw0,11)>: notifications listener has started (11)
11:49:11,618     INFO [ReceiverListener:hidraw0] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,11)>: receiver notifications enabled => ('wireless', 'software present')
11:49:11,624     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw0,11)>: present, No paired devices. (0) 
11:49:11,624     INFO [ReceiverListener:hidraw0] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,11)>: found new device 1 (400E)
11:49:11,624     INFO [ReceiverListener:hidraw0] solaar.listener: Notification(1,41,04,310E40) triggered new device <PairedDevice(1,400E,K400)> (keyboard)
11:49:11,628     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw0,11)>: present, 1 paired device. (0) 
11:49:13,032     INFO [ReceiverListener:hidraw0] solaar.configuration: saved {u'101A:D48FF295': {u'side-scroll': False, u'smooth-scroll': False, u'dpi': u'1500', u'_name': u'Performance Mouse MX'}, u'200A:3D2042AE': {u'_name': u'Wireless Keyboard K350'}, u'101B:914AC83D': {u'side-scroll': False, u'smooth-scroll': False, u'_name': u'Marathon Mouse M705'}, u'400E:54307274': {u'_name': u'Wireless Touch Keyboard K400'}, u'_version': u'0.9.2'} to /home/gabinka/.config/solaar/config.json
11:49:14,014     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <PairedDevice(1,400E,K400)>: paired online, Battery: 90% (discharging) (1) 
11:49:14,016     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <PairedDevice(1,400E,K400)>: paired online, Battery: 90% (discharging) (0) 
11:49:14,019     INFO [ReceiverListener:hidraw0] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw0,11)>: found new device 2 (101A)
11:49:14,019     INFO [ReceiverListener:hidraw0] solaar.listener: Notification(2,41,04,121A10) triggered new device <PairedDevice(2,101A,Performance MX)> (mouse)
11:49:14,022     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw0,11)>: present, 2 paired devices. (0) 
11:49:14,086     INFO [ReceiverListener:hidraw0] logitech_receiver.receiver: <PairedDevice(2,101A,Performance MX)>: device notifications enabled ('battery status',)
11:49:14,087     INFO [ReceiverListener:hidraw0] solaar.configuration: saved {u'101A:D48FF295': {u'side-scroll': False, u'smooth-scroll': False, u'dpi': u'1500', u'_name': u'Performance Mouse MX'}, u'200A:3D2042AE': {u'_name': u'Wireless Keyboard K350'}, u'101B:914AC83D': {u'side-scroll': False, u'smooth-scroll': False, u'_name': u'Marathon Mouse M705'}, u'400E:54307274': {u'_name': u'Wireless Touch Keyboard K400'}, u'_version': u'0.9.2'} to /home/gabinka/.config/solaar/config.json
11:49:14,177     INFO [ReceiverListener:hidraw0] solaar.configuration: saved {u'101A:D48FF295': {u'side-scroll': False, u'smooth-scroll': False, u'dpi': u'1500', u'_name': u'Performance Mouse MX'}, u'200A:3D2042AE': {u'_name': u'Wireless Keyboard K350'}, u'101B:914AC83D': {u'side-scroll': False, u'smooth-scroll': False, u'_name': u'Marathon Mouse M705'}, u'400E:54307274': {u'_name': u'Wireless Touch Keyboard K400'}, u'_version': u'0.9.2'} to /home/gabinka/.config/solaar/config.json
11:49:14,281     INFO [ReceiverListener:hidraw0] solaar.configuration: saved {u'101A:D48FF295': {u'side-scroll': False, u'smooth-scroll': False, u'dpi': u'1500', u'_name': u'Performance Mouse MX'}, u'200A:3D2042AE': {u'_name': u'Wireless Keyboard K350'}, u'101B:914AC83D': {u'side-scroll': False, u'smooth-scroll': False, u'_name': u'Marathon Mouse M705'}, u'400E:54307274': {u'_name': u'Wireless Touch Keyboard K400'}, u'_version': u'0.9.2'} to /home/gabinka/.config/solaar/config.json
11:49:14,507     INFO [AsyncUI] solaar.configuration: saved {u'101A:D48FF295': {u'side-scroll': False, u'smooth-scroll': False, u'dpi': u'1500', u'_name': u'Performance Mouse MX'}, u'200A:3D2042AE': {u'_name': u'Wireless Keyboard K350'}, u'101B:914AC83D': {u'side-scroll': False, u'smooth-scroll': False, u'_name': u'Marathon Mouse M705'}, u'400E:54307274': {u'_name': u'Wireless Touch Keyboard K400'}, u'_version': u'0.9.2'} to /home/gabinka/.config/solaar/config.json
11:49:14,594     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <PairedDevice(2,101A,Performance MX)>: paired online, Battery: full (discharging) (1) 
11:49:14,595     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <PairedDevice(2,101A,Performance MX)>: paired online, Battery: full (discharging) (0) 
11:49:16,216    ERROR [ReceiverListener:hidraw0] logitech_receiver.listener: processing Notification(2,02,00,8000100000000000000000)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/usr/lib/python2.7/site-packages/solaar/listener.py", line 207, in _notifications_handler
    _notifications.process(dev, n)
  File "/usr/lib/python2.7/site-packages/logitech_receiver/notifications.py", line 54, in process
    return _process_device_notification(device, status, notification)
  File "/usr/lib/python2.7/site-packages/logitech_receiver/notifications.py", line 105, in _process_device_notification
    return _process_hidpp10_custom_notification(device, status, n)
  File "/usr/lib/python2.7/site-packages/logitech_receiver/notifications.py", line 130, in _process_hidpp10_custom_notificatio
    if n.sub_id == _R.illumination:
</code></pre>

I Use Logitech Performance MX mouse and Logitech K400 Keyboard.
![solaar ok1](https://cloud.githubusercontent.com/assets/3693437/2983080/9ad60096-dc1d-11e3-9618-3f0ae3ed584b.png)
![solaar ok2](https://cloud.githubusercontent.com/assets/3693437/2983081/9ad8a904-dc1d-11e3-9fb1-b76c4e4fbef3.png)
![solaar ok3](https://cloud.githubusercontent.com/assets/3693437/2983082/9adb8c5a-dc1d-11e3-8bad-b8e65b601a95.png)

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
