### ISSUE TITLE
Mouse Gesture Button in Rules Editor is not working as expected

### ISSUE THREAD

**Issue by BierDav** [pwr-Solaar/Solaar#1593]
I really don't now how it is intendet to be, but I want to make a condition for the gesture button clicked without a gesture performed. As you can do in Logitech Options.

![image](https://user-images.githubusercontent.com/46626041/166098733-29795a69-3337-4acf-a8c8-868ec6327d7a.png)

I've thought that this is how you do it, but sadly it doesn't work. Is this already supported? If so how to achive this?

**Comment by pfps** [comment]
If you are not using mouse gestures then this should work, as long as the button is diverted.
If you are using mouse gestures then you should instead use a mouse gestures condition with no movement.

**Comment by BierDav** [comment]
Thanks
