### ISSUE TITLE
Rule editor not excuting properly after restart

### ISSUE THREAD

**Issue by ArtemisiosG** [pwr-Solaar/Solaar#1603]
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.3
- Distribution: Fedora Linux 36
- Kernel version (ex. `uname -srmo`): 5.17.6-300.fc36.x86_64
- Output of `solaar show`: 

**Describe the bug**
I added a user specific rule for MX Master 3 such that the Forward button would be rebinded to be super_L and Back button to be Escape and it worked the first time i used the rule editor but after a restart, it stopped working even after removing and adding the same rule again afterwards.

**Screenshots**
![image](https://user-images.githubusercontent.com/105563752/168445686-329c8084-612e-4c33-bdec-f550060ac983.png)

**Additional context**

**Comment by pfps** [comment]
Please provide output of Solaar show both when the mouse is working as expected and when it is not.  Also provide contents of ~/.config/solaar/config.yaml

Also kill any running instances of solaar and run as `solaar -ddd`.   Provide output when the mouse is not working as expected.

**Comment by dannycoulombe** [comment]
Thanks to @pfps comment, I got the following error message on my Logitech MX 2:

```
16:56:38,678  WARNING [MainThread] logitech_receiver.diversion: no way to simulate key input
16:56:38,679  WARNING [MainThread] logitech_receiver.diversion: cannot create uinput device: "/dev/uinput" cannot be opened for writing
```

So I tried running Solaar as sudo and it works. Also, a solution by @parkerlreed worked for me:
https://github.com/chrippa/ds4drv/issues/93#issuecomment-265300511

**Comment by pfps** [comment]
@ArtemisiosG Is this still a problem for you?

**Comment by ArtemisiosG** [comment]
@pfps not anymore, not after i have ran the command @dannycoulombe quoted 

thanks for the help
