### ISSUE TITLE
question - solaar vs logiops?

### ISSUE THREAD

**Issue by alan-barzilay** [pwr-Solaar/Solaar#1604]
Hi, probably a stupid question, but what is the difference between solaar and logiops?  Should they be used together? If so, how do they compliment each other? thanks!

**Comment by pfps** [comment]
As far as I can tell both Solaar and logiops try to set aspects of various features of Logitech HID++ devices.  Running them both at the same time is thus not a good idea as the actions of one may interfere with the actions of the other.  This is likely to result in some unpredictable state for the device.

Solaar runs as a single program implementing the UI and the device controller.   This is not the best way to go and Solaar should be reimplemented to separate the two parts.  Logiops appears to be implemented as a small daemon program controlled by a DBus interface, which is a better way to go.

**Comment by alan-barzilay** [comment]
Thanks for the reply! Has there ever been a comparison between solaar and logiops to see which one works best or something like that?
