### ISSUE TITLE
Add feature: firmware updates for connected devices (if applicable) and unifying receivers

### ISSUE THREAD

**Issue by hamishmb** [pwr-Solaar/Solaar#1613]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): 1.1.2
- Distribution: Linux Mint 20.2
- Kernel version (ex. `uname -srmo`): Linux 5.13.0-41-generic x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable): N/A

**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
It'd be nice if firmware updates could somehow be done by Solaar.

**Describe alternatives you've considered**
The only alternative I know is when Logitech release a utility for Windows to do this. Not that they publicise these very well, so it's not easy to know if there is an update that should be done eg for security.

**Additional context**
None.

**Comment by pfps** [comment]
Do you want something more than fwupdmgr?  How would it get better access to the updates?

Doing firmware updates as a part of Solaar seems dangerous.  A firmware updater should be a small program to reduce the chance of something going wrong.

**Comment by hamishmb** [comment]
Are logitech updates managed by fwupdmgr? I wasn't aware of that.

**Comment by pfps** [comment]
It lists my Unifying Receiver, but doesn't have any updates for it.

**Comment by hamishmb** [comment]
Okay, I think this is probably irrelevant as an issue then.
