### ISSUE TITLE
ALT_L + F4 on SmartShift key through rule not always working

### ISSUE THREAD

**Issue by mvanthoor** [pwr-Solaar/Solaar#1619]
Specs:
- Running the latest version of Solaar (1.1.3) installed manualy
- Debian 11 Stable, Bullseye
- Logitech MX Master 3

I have set a rule to issue the keystroke ALT_L + F4 when the SmartShift button is pressed. Most of the time this works, but sometimes it doesn't; in that case, the SmartShift button has to be pressed again. In an attempt to see what is happening I opened and closed KWrite many times, in the hope that something would be printed in the editor. This worked: when clicking the SmartShift button and the rule is not working, the capital letter S is issued instead of ALT_L + F4. This is what I've been able to observe in KWrite; either the editor closes (edit: which is the intended behavior of ALT_L + F4 of course), or the capital S appears (which means the rule doesn't work correctly).

As of yet I've been unable to determine if there is specific situation or action on my part that triggers this problem.

**Comment by pfps** [comment]
I have seen a similar problem sometimes, but where the first key of a multi-key KeyPress action does not show up.  I was going to further investigate but when I made some changes the problem did not recur.   So I suggest downloading and using the current version of Solaar from this repository and see whether the problem recurs.

**Comment by mvanthoor** [comment]
> I have seen a similar problem sometimes, but where the first key of a multi-key KeyPress action does not show up. I was going to further investigate but when I made some changes the problem did not recur. So I suggest downloading and using the current version of Solaar from this repository and see whether the problem recurs.

Thanks for replying. My version of Solaar already is at the current latest version; or are you suggesting I should run straight from the repository source?

**Comment by pfps** [comment]
Yes, there have been changes since 1.1.3 that affect the KeyPress rule acction so running the version from this repository might help you.

**Comment by mvanthoor** [comment]
> Yes, there have been changes since 1.1.3 that affect the KeyPress rule acction so running the version from this repository might help you.

I've replaced the release version with the one from master. I'll report back if I notice any differences.

**Comment by mvanthoor** [comment]
> Please report back if you encounter the problem with the repository version of Solaar. If you do, try running `bin/solaar -ddd` and report the output from around the time that the problem re-occurs.

Here you go. I used "script" to dump Solaar's debug output to a file. When the problem occurred I immediately quit Solaar and opened the log. Scrolling backward from the shutdown notification this is what I found:

[code]
17:25:16,372    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (13) => r[20 01 0200 0000F0FF00000000000000]
17:25:16,390    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (13) => r[20 01 0200 00FFFFFF00000000000000]
17:25:17,196    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (13) => r[20 01 0201 0000000000000000000000]
17:25:17,300    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (13) => r[20 01 0200 0000000000000000000000]
17:25:21,188    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (13) => r[11 01 0900 00C40000000000000000000000000000]
17:25:21,189    DEBUG [ReceiverListener:hidraw0] logitech_receiver.notifications: <Device(1,4082,MX Master 3 Wireless Mouse,EAAD58BE)>: notification for feature REPROG CONTROLS V4, report 0, data 00C40000000000000000000000000000
17:25:21,189    DEBUG [ReceiverListener:hidraw0] logitech_receiver.notifications: <Device(1,4082,MX Master 3 Wireless Mouse,EAAD58BE)>: diverted controls pressed: 0xc4, 0x0, 0x0, 0x0
17:25:21,316    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (13) => r[11 01 0900 00000000000000000000000000000000]
17:25:21,317    DEBUG [ReceiverListener:hidraw0] logitech_receiver.notifications: <Device(1,4082,MX Master 3 Wireless Mouse,EAAD58BE)>: notification for feature REPROG CONTROLS V4, report 0, data 00000000000000000000000000000000
17:25:21,317    DEBUG [ReceiverListener:hidraw0] logitech_receiver.notifications: <Device(1,4082,MX Master 3 Wireless Mouse,EAAD58BE)>: diverted controls pressed: 0x0, 0x0, 0x0, 0x0
17:25:21,320  WARNING [MainThread] logitech_receiver.diversion: XKB display not available - rules cannot access keyboard group: %s
Traceback (most recent call last):
  File "/home/marcel/.local/lib/python3.9/site-packages/logitech_receiver/diversion.py", line 147, in xkb_setup
    X11Lib = _ctypes.cdll.LoadLibrary('libX11.so')
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libX11.so: cannot open shared object file: No such file or directory
17:25:21,321     INFO [MainThread] logitech_receiver.diversion: KeyPress action: ['Alt_L', 'F4'], group None, modifiers 16
17:25:21,357     INFO [MainThread] logitech_receiver.diversion: X11 library loaded and display set up
17:25:21,358    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f8b9c0a6c70> 2 64
17:25:21,368    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f8b9c0a6c70> 2 70
17:25:21,369    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f8b9c0a6c70> 3 70
17:25:21,369    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f8b9c0a6c70> 3 64
17:25:23,368    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (13) => r[20 01 0200 0001000000000000000000]
17:25:23,376    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (13) => r[20 01 0200 0001000000000000000000]
17:25:23,384    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (13) => r[20 01 0200 0001000000000000000000]
17:25:23,392    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (13) => r[20 01 0200 0002100000000000000000]
17:25:23,400    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (13) => r[20 01 0200 0003000000000000000000]
[/code]

(I have only one diverted button, which is SmartShift.)

I can provide the entire log if you want. It's 252 kB (with most of the text being pointer movements, probably).

**Comment by pfps** [comment]
Solaar is not finding libX11, but all that means is that it can't determine your current keyboard group.  If you are not using keyboard groups then there should be no problem.  It appears here that there is no problem here as Solaar appears to be sending the correct XTest commands for the normal keycodes and the two keys you are trying to send usually don't depend on the keyboard group.

```
17:25:21,358    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f8b9c0a6c70> 2 64
17:25:21,368    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f8b9c0a6c70> 2 70
17:25:21,369    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f8b9c0a6c70> 3 70
17:25:21,369    DEBUG [MainThread] logitech_receiver.diversion: xtest simulated input <Xlib.display.Display object at 0x7f8b9c0a6c70> 3 64
```

What could be going wrong is that there needs to be some time between setting up the X11 display and using XTest.  Does your problem always occur for the first time you have the rule run?

**Comment by mvanthoor** [comment]
> What could be going wrong is that there needs to be some time between setting up the X11 display and using XTest. Does your problem always occur for the first time you have the rule run?

It seems to occur randomly. Sometimes I'm using the computer for half an hour and everything works, and then suddenly a window won't close. When I click again, it closes.

**Comment by mvanthoor** [comment]
> From https://pwr-solaar.github.io/Solaar/installation:
> 
> Solaar also uses the X11 library to access the XKB extension, which requires installation of the X11 development package. (In Fedora this is libX11-devel. In other distributions it may be libX11-dev.)
> 
> Do you have this package loaded?

I didn't. I may have missed that library if it's in the dependency list. I've now installed it. In Debian, it's libx11-dev.

**Comment by pfps** [comment]
Does the problem occur other than the first time you have the rule run?  The fact that running the rule again does not cause the problem seems to indicate that it is somehow timing related and the only thing that I can think of that is timing related is that the first time Solaar tries to simulate keyboard input it does some setup things.

If so, try to capture the output of `bin/solaar -dd` when the problem occurs other than the first time the rule runs.

**Comment by mvanthoor** [comment]
> Does the problem occur other than the first time you have the rule run? The fact that running the rule again does not cause the problem seems to indicate that it is somehow timing related and the only thing that I can think of that is timing related is that the first time Solaar tries to simulate keyboard input it does some setup things.
> 
> If so, try to capture the output of `bin/solaar -dd` when the problem occurs other than the first time the rule runs.

Sometimes it fails when I try to close a window using this rule for the very first time.

However, it also sometimes fails after that time. However, I have to take into account that I have a monitor with a built-in KVM-switch, and I switch back-and-forth between computers during the day. It could be that there are many "first runs", because the mouse (and keyboard) get disconnected and reconnected during the switch. I'll keep an eye out.

**Comment by mvanthoor** [comment]
> From https://pwr-solaar.github.io/Solaar/installation:
> 
> Solaar also uses the X11 library to access the XKB extension, which requires installation of the X11 development package. (In Fedora this is libX11-devel. In other distributions it may be libX11-dev.)
> 
> Do you have this package loaded?

It seems the installation of this package (maybe, also in combination with running the latest version from the repo) solved this problem. I see the x11-dev package is mentioned on the manual install page; I didn't have it installed. I might have missed it when I read that page. Sorry for the bug report if this was the solution. I'll keep an eye out if I encounter this problem again and report back in a few days.

**Comment by mvanthoor** [comment]
@pfps 

I've monitored the situation for some time; I installed the last dependency libx11-dev, and at first the problem seemed to be solved, but it came back the day after. Since then this has been an issue again; sometimes the ALT_L + F4 key stroke (made through a rule for the SmartSwitch button) doesn't come through. Clicking again does close the window.

**Comment by pfps** [comment]
As far as I can tell, Solaar is doing everything right.   Try running with `-ddd` and collect output around the time of the problem.  Also say whether this is the first time the rule has run after booting or resuming your system.
