### ISSUE TITLE
Unable to use with evdev-1.5.0

### ISSUE THREAD

**Issue by voncloft** [pwr-Solaar/Solaar#1623]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository):
- Distribution:
- Kernel version (ex. `uname -srmo`): `5.4.85`
- Output of `solaar show`:

<details>

```
solaar: error: Traceback (most recent call last):
  File "/home/von/.local/lib/python3.10/site-packages/solaar/gtk.py", line 158, in main
    import solaar.ui as ui
  File "/home/von/.local/lib/python3.10/site-packages/solaar/ui/__init__.py", line 101, in <module>
    from . import diversion_rules, notify, tray, window  # isort:skip  # noqa: E402
  File "/home/von/.local/lib/python3.10/site-packages/solaar/ui/diversion_rules.py", line 30, in <module>
    from logitech_receiver import diversion as _DIV
  File "/home/von/.local/lib/python3.10/site-packages/logitech_receiver/diversion.py", line 181, in <module>
    [evdev.ecodes.REL_WHEEL, evdev.ecodes.REL_HWHEEL, evdev.ecodes.REL_WHEEL_HI_RES, evdev.ecodes.REL_HWHEEL_HI_RES]
AttributeError: module 'evdev.ecodes' has no attribute 'REL_WHEEL_HI_RES'

```
</details>

- Errors or warrnings from Solaar:

**Comment by pfps** [comment]
Strange.  I have evdev 1.5.0-1.

In any case, the HI_RES members aren't used, so it should be possible to just remove them.  Stay tuned.

**Comment by pfps** [comment]
PR #1624 should fix your issue.  Please try it out.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1624, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1624/head:pull_1624
git checkout pull_1624
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1624
git fetch origin pull/1624/head
git reset --hard FETCH_HEAD
```
