### ISSUE TITLE
Mouse side buttons as modifier keys

### ISSUE THREAD

**Issue by ItMeCorban** [pwr-Solaar/Solaar#1625]
- Solaar version (`solaar --version` and `git describe --tags`):
solaar 1.1.3
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
- Distribution:
Arch
- Kernel version (ex. `uname -srmo`):
5.18.1
- Output of `solaar show` for the target device (if applicable):

<details>
Solaar version 1.1.3

USB and Bluetooth Devices

  1: MX Master 3 Wireless Mouse
     Device path  : /dev/hidraw1
     USB id       : 046d:B023
     Codename     : MX Master 3
     Kind         : mouse
     Protocol     : HID++ 4.5
     Serial number: 
     Model ID:      B02340820000
     Unit ID:       B001CB47
        Bootloader: BOT 95.01.B0015
          Firmware: MPM 19.01.B0015
             Other: 
     Supports 31 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 95.01.B0015 00006A9CA89D
            Firmware: Firmware MPM 19.01.B0015 B0236A9CA89D
            Firmware: Other   
            Unit ID: B001CB47  Model ID: B02340820000  Transport IDs: {'btleid': 'B023', 'wpid': '4082'}
         3: DEVICE NAME            {0005}   
            Name: Wireless Mouse MX Master 3
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: CRYPTO ID              {0021}   
         7: DEVICE FRIENDLY NAME   {0007}   
            Friendly Name: MX Master 3
         8: BATTERY STATUS         {1000}   
            Battery: 100%, discharging, next level 50%.
         9: REPROG CONTROLS V4     {1B04}   
            DPI Sliding Adjustment (saved): Off
            DPI Sliding Adjustment        : Off
            Mouse Gestures (saved): 195
            Mouse Gestures        : Off
            Key/Button Actions (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Actions        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Key/Button Diversion (saved): {Middle Button:Regular, Back Button:Diverted, Forward Button:Diverted, Mouse Gesture Button:Diverted, Smart Shift:Regular}
            Key/Button Diversion        : {Middle Button:Regular, Back Button:Diverted, Forward Button:Diverted, Mouse Gesture Button:Diverted, Smart Shift:Regular}
        10: CHANGE HOST            {1814}   
            Change Host        : 2:LTTTOP
        11: XY STATS               {2250}   
        12: ADJUSTABLE DPI         {2201}   
            Sensitivity (DPI) (saved): 1000
            Sensitivity (DPI)        : 1000
        13: SMART SHIFT            {2110}   
            Scroll Wheel Rachet (saved): 10
            Scroll Wheel Rachet        : 10
        14: HIRES WHEEL            {2121}   
            Multiplier: 15
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            High resolution mode
            HID notification
            Scroll Wheel Direction (saved): False
            Scroll Wheel Direction        : False
            Scroll Wheel Resolution (saved): True
            Scroll Wheel Resolution        : True
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
        15: THUMB WHEEL            {2150}   
            Thumb Wheel Diversion (saved): False
            Thumb Wheel Diversion        : False
            Thumb Wheel Direction (saved): False
            Thumb Wheel Direction        : False
        16: WHEEL STATS            {2251}   
        17: DFUCONTROL SIGNED      {00C2}   
        18: DEVICE RESET           {1802}   internal, hidden
        19: unknown:1803           {1803}   internal, hidden
        20: CONFIG DEVICE PROPS    {1806}   internal, hidden
        21: unknown:1813           {1813}   internal, hidden
        22: OOBSTATE               {1805}   internal, hidden
        23: unknown:1830           {1830}   internal, hidden
        24: unknown:18A1           {18A1}   internal, hidden
        25: unknown:1E00           {1E00}   hidden
        26: unknown:1EB0           {1EB0}   internal, hidden
        27: unknown:1861           {1861}   internal, hidden
        28: unknown:9300           {9300}   internal, hidden
        29: unknown:9001           {9001}   internal, hidden
        30: unknown:9205           {9205}   internal, hidden
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: diverted
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: diverted
         5: Mouse Gesture Button      , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: diverted, raw XY diverted
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Battery: 100%, discharging, next level 50%.

</details>

**Describe the solution you'd like**
Ability to use the mouse buttons as modifiers. I like to have a Super, Control and Shift key on my mouse to make selecting lists and adjusting windows easily (Super + click to move windows, super + right click to resize etc)

This is possible in Windows but through Solaar the mouse seems to stop taking button input when another is held down - this is normal for the gesture pad but the back and forward buttons do it to - the cursor will still move but clicking cancels out whatever button is already pressed.

If possible this would be an option to apply to the gestures pad aswell so foward, back and the gesture button can be used as modifiers.

**Describe alternatives you've considered**
Using 2 hands to click things
Not using a logitech mouse

**Comment by pfps** [comment]
It should be possible to do this in a customization program for your window manager.  However, it appears that window managers in Linux don't have this level of customization.

I don't understand what you mean by "the mouse stops taking button input when another is held down".  There should be nothing in Linux or Solaar that prevents programs from seeing the mouse buttons go up and down independently.  I use Emacs, and Emacs can see the back button going down, then the left button going down, then the left button coming up, and then the back button coming up.

What you want can almost be done in Solaar, but it needs Solaar rules.  There is no facility in an MX Master 3 to convert button motions to arbitrary key motions.   What can be done in Solaar is to divert the back and forward buttons and use button presses and releases to simulate keyboard input.  What can't be done is have button press simulate key press and button release simulate key release - the button press or release simulates both key press and key release.  Independent press and release wasn't added because it is dangerous - if you don't have the release corresponding to the press then a key or button would stay down and potentially make your system unusable.

There have been several requests for this ability, however.  If this ability will suit you please respond and it might be added.

One issue is that the current rule action is KeyPress, which isn't a good name when there can be key presses and key releases.  Probably there would be an extra argument which would be either down, up, or click.  Suggestions for better names are welcome.

**Comment by pfps** [comment]
How are you doing this?  With Solaar rules?  If so, please post your current rule set.

**Comment by ItMeCorban** [comment]
Yep just Solaar rules, screenshot attached
![image](https://user-images.githubusercontent.com/13917133/172651069-377611d4-aaad-4a59-aa9c-cba78331906b.png)

**Comment by pfps** [comment]
These rule will press-and-release the modifier keys when the button is pressed, provided that the button is diverted, so they won't solve your issue.

But I don't see any reason that your mouse freezes when the back or forward button is pressed.  That doesn't happen on my MX Master 3, whether the button is diverted or not.  For the mouse gesture button this depends on whether you have mouse gestures on.  If so, the mouse cursor will not move; if not, the mouse cursor should continue to move.

**Comment by ItMeCorban** [comment]
The cursor isn't freezing with the 2 buttons, only the gesture pad, but when I turned off gestures, it stopped following the button rule

**Comment by pfps** [comment]
These rule will press-and-release the modifier keys when the button is pressed, provided that the button is diverted, so they won't solve your issue.

But I don't see any reason that your mouse freezes when the back or forward button is pressed.  That doesn't happen on my MX Master 3, whether the button is diverted or not.  For the mouse gesture button this depends on whether you have mouse gestures on.  If so, the mouse cursor will not move; if not, the mouse cursor should continue to move.

**Comment by pfps** [comment]
See Issue #1517, which is a direct request for this capability.

To do what you want, you will need two rules, one to depress the modifier key, triggered by the button press, and one to release the modifier key, triggered by button release.

**Comment by ItMeCorban** [comment]
Ah okay cool I'll follow it over there then, thanks for the help!
