### ISSUE TITLE
About screen version 1.1.1 instead of 1.1.3

### ISSUE THREAD

**Issue by MHolkamp** [pwr-Solaar/Solaar#1632]
I have installed 1.1.3 version.
The about screen still tells me version 1.1.1

Is this an issue on my side or is it a common problem.

**Comment by pfps** [comment]
The version number comes from a constant in the Solaar code itself so it is very likely that you are running version 1.1.1.   Check whether you have multiple versions of Solaar installed or try `which solaar` to see what executable you are running for `solaar`.  Note that installing using pip will likely put the Solaar executable in a different place than installing using apt or dnf.
