### ISSUE TITLE
Please create an AppData file for Solaar

### ISSUE THREAD

**Issue by hughsie** [pwr-Solaar/Solaar#164]
Please consider writing and installing an AppData file with the application description and some screenshots, else Solaar looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't. See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by pfps** [comment]
If someone is interesting in writing this document it should be easy to incorporate into Solaar.
