### ISSUE TITLE
[QUESTION] I cannot figure how to write conditional rule for Mouse gesture with other button pressed to trigger a script

### ISSUE THREAD

**Issue by NikhilSaini38** [pwr-Solaar/Solaar#1645]
I am trying to write rules for my MX master 3. Here's My rules.yml
```
---
- Rule:
  - MouseGesture: Mouse Left
  - Execute: [qdbus, org.kde.kglobalaccel, /component/kwin, org.kde.kglobalaccel.Component.invokeShortcut,
      Switch One Desktop to the Right]
- Rule:
  - MouseGesture: Mouse Right
  - Execute: [qdbus, org.kde.kglobalaccel, /component/kwin, org.kde.kglobalaccel.Component.invokeShortcut,
      Switch One Desktop to the Left]
- Rule:
  - MouseGesture: Mouse Up
  - Execute: [qdbus, org.kde.kglobalaccel, /component/kwin, org.kde.kglobalaccel.Component.invokeShortcut,
      ExposeAll]
- Rule:
  - MouseGesture: Mouse Down
  - Execute: [qdbus, org.kde.kglobalaccel, /component/kwin, org.kde.kglobalaccel.Component.invokeShortcut,
      Expose]
...
```
I am trying to use `Window to Previous Desktop` and `Window to Next Desktop` when Left Shift is pressed while making the mouse gesture. Help please?

**Comment by pfps** [comment]
You have four mouse gestures that execute four separate KDE actions.  It looks as if you want to have different actions executed when Left Shift is down.    You should be able to use a `Modifiers: Shift` condition for this purpose, except that this would allow both left and right shift keys being down.

**Comment by NikhilSaini38** [comment]
Hi, can you please give me an example? i don't properly understand how to implement this in rule editor, do i create seperate sub-rule?
