### ISSUE TITLE
M185 new - Battery status unavailable

### ISSUE THREAD

**Issue by mfraser** [pwr-Solaar/Solaar#1651]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): solaar 1.1.4rc2
- Distribution: Kubuntu 22.04
- Kernel version (ex. `uname -srmo`): Linux 5.15.0-40-generic x86_64 GNU/Linux
- Output of `solaar show`:

Solaar version 1.1.4rc2

Nano Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:C534
  Serial       : None
    Firmware   : 29.01.B0016
  Has 2 paired device(s) out of a maximum of 2.
  Has 18 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)

  1: Wireless Keyboard  
     Device path  : /dev/hidraw2
     WPID         : 4075
     Codename     :  
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Polling rate : 20 ms (50Hz)
     Serial number: 00000000
     Model ID:      000000000000
     Unit ID:       00000000
          Firmware: RQK 71.00.B0002
     Supports 19 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Firmware RQK 71.00.B0002 4075
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         3: DEVICE NAME            {0005}   
            Name: Wireless Keyboard  
            Kind: keyboard
         4: RESET                  {0020}   
         5: BATTERY STATUS         {1000}   
            Battery: 30%, discharging, next level 5%.
         6: REPROG CONTROLS V4     {1B04}   
            Key/Button Diversion (saved): {Calculator:Regular, Mail:Regular, My Home:Regular, Search:Regular}
            Key/Button Diversion        : {Calculator:Regular, Mail:Regular, My Home:Regular, Search:Regular}
         7: WIRELESS DEVICE STATUS {1D4B}   
         8: NEW FN INVERSION       {40A2}   
            Fn-swap: disabled
            Fn-swap default: disabled
            Swap Fx function (saved): False
            Swap Fx function        : False
         9: ENCRYPTION             {4100}   
        10: LOCK KEY STATE         {4220}   
        11: KEYBOARD DISABLE KEYS  {4521}   
            Disable keys (saved): {Caps Lock:False, Num Lock:False, Scroll Lock:False, Insert:False, Win:False}
            Disable keys        : {Caps Lock:False, Num Lock:False, Scroll Lock:False, Insert:False, Win:False}
        12: unknown:1810           {1810}   internal, hidden
        13: unknown:1830           {1830}   internal, hidden
        14: unknown:1890           {1890}   internal, hidden
        15: unknown:18A0           {18A0}   internal, hidden
        16: unknown:18B0           {18B0}   internal, hidden
        17: unknown:1DF3           {1DF3}   internal, hidden
        18: unknown:1E00           {1E00}   hidden
     Has 4 reprogrammable keys:
         0: My Home                   , default: HomePage                    => HomePage                  
             is FN, FN sensitive, reprogrammable, divertable, pos:1, group:0, group mask:empty
             reporting: default
         1: Mail                      , default: Email                       => Email                     
             is FN, FN sensitive, reprogrammable, divertable, pos:2, group:0, group mask:empty
             reporting: default
         2: Search                    , default: Search Files                => Search Files              
             is FN, FN sensitive, reprogrammable, divertable, pos:3, group:0, group mask:empty
             reporting: default
         3: Calculator                , default: Calculator                  => Calculator                
             is FN, FN sensitive, reprogrammable, divertable, pos:4, group:0, group mask:empty
             reporting: default
     Battery: 30%, discharging, next level 5%.

  2: Wireless Mouse M185 new
     Device path  : /dev/hidraw3
     WPID         : 4054
     Codename     : M185n
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 00000000
     Model ID:      000000000000
     Unit ID:       00000000
          Firmware: RQM 64.00.B0008
     The power switch is located on the base.
     Supports 19 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Firmware RQM 64.00.B0008 4054
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         3: DEVICE NAME            {0005}   
            Name: Wireless Mouse  
            Kind: mouse
         4: RESET                  {0020}   
         5: REPROG CONTROLS V4     {1B04}   
            Mouse Gestures (saved): Off
            Mouse Gestures        : Off
            Key/Button Actions (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button}
            Key/Button Actions        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button}
            Key/Button Diversion (saved): {Middle Button:Regular}
            Key/Button Diversion        : {Middle Button:Regular}
         6: WIRELESS DEVICE STATUS {1D4B}   
         7: LOWRES WHEEL           {2130}   
            Wheel Reports: HID
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
         8: POINTER SPEED          {2205}   
            Pointer Speed: 1.0
            Sensitivity (Pointer Speed) (saved): 256
            Sensitivity (Pointer Speed)        : 256
         9: DEVICE RESET           {1802}   internal, hidden
        10: unknown:1810           {1810}   internal, hidden
        11: unknown:1830           {1830}   internal, hidden
        12: unknown:1850           {1850}   internal, hidden
        13: unknown:1869           {1869}   internal, hidden
        14: unknown:1890           {1890}   internal, hidden
        15: unknown:18B1           {18B1}   internal, hidden
        16: unknown:1DF3           {1DF3}   internal, hidden
        17: unknown:1E00           {1E00}   hidden
        18: unknown:1F03           {1F03}   internal, hidden
     Has 3 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, reprogrammable, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, reprogrammable, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
     Battery status unavailable.

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

- 1.1.4rc2
- _NAME: M335
  _serial: 5E91C7C9
  _wpid: '0640'
  hires-smooth-invert: false
  hires-smooth-resolution: true
  pointer_speed: 255
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 204: 82}
- {_NAME: Wireless Keyboard K520, _serial: 7A79C0BC, _wpid: 1A20, fn-swap: false}
- {_NAME: Wireless Keyboard K520, _serial: 7A79C0BC, _wpid: '2011', fn-swap: false}
- _NAME: Wireless Mouse M335
  _absent: [hi-res-scroll, lowres-smooth-scroll, smart-shift, thumb-scroll-mode, thumb-scroll-invert, dpi, dpi-sliding, speed-change, backlight, fn-swap,
    disable-keyboard-keys, report_rate, divert-crown, crown-smooth, divert-gkeys, multiplatform, change-host, gesture2-gestures, gesture2-params, m-key-leds,
    mr-key-led, onboard_profiles, backlight-timed, persistent-remappable-keys, gesture2-divert, lowres-scroll-mode]
  _modelId: '405000000000'
  _sensitive: {divert-keys: false, hires-smooth-invert: false, hires-smooth-resolution: false, reprogrammable-keys: true}
  _serial: 5E91C7C9
  _unitId: 5E91C7C9
  _wpid: '4050'
  divert-keys: {80: 0, 81: 0, 82: 0, 83: 0, 86: 0, 204: 0}
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  mouse-gestures: 0
  pointer_speed: 255
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 204: 82}
- {_NAME: Wireless Mouse M185/M235/M310, _serial: 86A015F6, _wpid: '4055', low-res-scroll: false, lowres-smooth-scroll: false, pointer_speed: 280, smooth-scroll: false}
- _NAME: Wireless Mobile Mouse MX Anywhere 2
  _absent: [hi-res-scroll, lowres-scroll-mode, smart-shift, thumb-scroll-invert, thumb-scroll-mode, onboard_profiles, report_rate, pointer_speed, speed-change,
    backlight, backlight-timed, fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led,
    multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer]
  _modelId: B01F40720000
  _serial: D5D1944C
  _unitId: 57DA93C2
  _wpid: '4072'
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 91: 0, 93: 0}
  dpi: 1000
  dpi-sliding: 0
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  mouse-gestures: 0
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 91: 91, 93: 93}
- _NAME: 'Wireless Keyboard  '
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, pointer_speed, dpi, dpi-sliding, speed-change, mouse-gestures, backlight, backlight-timed, reprogrammable-keys, persistent-remappable-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params, sidetone,
    equalizer]
  _modelId: '000000000000'
  _serial: '00000000'
  _unitId: '00000000'
  _wpid: '4075'
  disable-keyboard-keys: {1: false, 2: false, 4: false, 8: false, 16: false}
  divert-keys: {10: 0, 14: 0, 34: 0, 62: 0}
  fn-swap: false
- _NAME: Wireless Mouse M185 new
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, smart-shift, thumb-scroll-invert, thumb-scroll-mode, onboard_profiles,
    report_rate, dpi, dpi-sliding, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth, divert-crown,
    divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer]
  _modelId: '000000000000'
  _serial: '00000000'
  _unitId: '00000000'
  _wpid: '4054'
  divert-keys: {82: 0}
  lowres-scroll-mode: false
  mouse-gestures: 0
  pointer_speed: 256
  reprogrammable-keys: {80: 80, 81: 81, 82: 82}

**Describe the bug**
Keyboard showing 30% from new and mouse M185 new not showing any battery information just "Battery status unavailable."

**Comment by pfps** [comment]
The M185 mouse doesn't have any HID++ feature that provides the battery level so Solaar can't report it.  Your keyboard does report the battery level but may only have several very approximate levels, with 30% being used for anything other than "very low".  Either that or the batteries may indeed have started out low.
