### ISSUE TITLE
question - is it possible to remap a thumbwheel to work as a vertical scroll?

### ISSUE THREAD

**Issue by alan-barzilay** [pwr-Solaar/Solaar#1661]
Maybe I'm being incompetent, but I can't seem to find a way to turn my thumbwheel in the MXmaster 3 into a vertical scroll. I managed to divert it and use it for stuff like tab switching, but can't seem to find how to use it as another vertical scrollwheel. Is this possible? If so, how would such a rule look like?

Thank you for your time

**Comment by alan-barzilay** [comment]
It worked, thanks!
quick last question, the thumbwheel has a higher sensitivity then the vertical scroll wheel with just the [0,1] step. Is there a way to force them to be the same?

**Comment by pfps** [comment]
I don't think that there is a way to adjust the thumbwheel sensitivity nor is there a way to reduce the scrolling amount.
