### ISSUE TITLE
Support multiple gesture buttons

### ISSUE THREAD

**Issue by huipengcheng** [pwr-Solaar/Solaar#1663]
In Logi Option, I can assign multiple mouse buttons to the gesture button. But it seems like Solaar can only assign one button to the gesture button, or did I miss something?

**Comment by pfps** [comment]
Solaar currently only supports one button.  Having multiple buttons might be a worthwhile enhancement.  How does this work in Logi Option?  Can you do different things depending on which button is pressed?

**Comment by huipengcheng** [comment]
Yes, I actually set three buttons to the gesture button on my Master2s and Lift Vertical using Logi option, and it works flawlessly.

**Comment by pfps** [comment]
Solaar allows different buttons for different devices, just not several buttons on the same device.  The question is whether you can do different things with the different buttons, such as a left movement with the Mouse Gesture Button pressed moving left in workspaces but a left movement with the Smart Scroll button pressed doing leftward scrolling.

**Comment by pfps** [comment]
There is a new version that allows multiple keys for gestures.  It does not yet have capabilities in the rules to determine which key initiated the gesture.  Please download the current version of the PR and try it out.

**Comment by huipengcheng** [comment]
OK, I'm going to test it right now. Thanks for your work.

**Comment by huipengcheng** [comment]
It seems like actions can not be triggered by gestures.

![image](https://user-images.githubusercontent.com/42164573/179142735-fba441f6-9132-4bdf-b184-a57afcc661d2.png)
![image](https://user-images.githubusercontent.com/42164573/179142791-b8a863f6-5197-4efb-87f2-e846b064e733.png)

**Comment by pfps** [comment]
I don't think that rule is going to work.  The first condition requires a mouse gesture with no movement.  Then the subrules require a mouse gesture with movement.  Try converting that to four separate rules.

**Comment by huipengcheng** [comment]
Oh that' my mistake. I accidentally added the first Mouse Gesture rule. I will do a more careful test.

**Comment by pfps** [comment]
@huipengcheng Please test whether you can get rules to be sensitive to the button that initiated a mouse  gesture.

**Comment by huipengcheng** [comment]
I'm very sorry for the late response, I've been quite busy these days.

I installed that new version, then I set 2 gesture buttons and had used it for a few hours. Its behavior is exactly what I want and no error messages for now. It did a great job!k

Thank you for your work!

**Comment by huipengcheng** [comment]
Another question:

When I was using that new version on both my Master 3 and Lift Vertical, I accidentally found that there is an option called "Scroll Wheel Resolution" in the setting pane of Master3, but that option is not exist in the setting pane of Lift Vertical.

I know a little about High Resolution Scrolling, but I think Lift Vertical, which is a new product released this year, should have that ability as the same as Master3.

So, is it possible to enable Scroll Wheel Resolution for Lift Vertical in Solaar?

**Comment by pfps** [comment]
Using Scroll Wheel Resolution can interfere with smooth scrolling, which is used in modern Linux kernels.  

Please provide the output of `solaar scroll` for the Lift Vertical.   Different Logitech devices can have very different features and thus very different capabilities in Solaar.

**Comment by huipengcheng** [comment]
It seems like `solaar scroll` is an invalid command?

But I found something is the log at Solaar startup, is this you want?

```
INFO [ReceiverListener:hidraw6] logitech_receiver.status: <Device(1,B031,LIFT VERTICAL ERGONOMIC MOUSE,8AC05737)> pushing device settings [<Setting([feature:toggle] LIFT:lowres-scroll-mode=None)>, <Setting([feature:choice] LIFT:dpi=None)>, <Setting([feature:map choice] LIFT:reprogrammable-keys=None)>, <Setting([feature:map choice] LIFT:divert-keys=None)>, <Setting([feature:choice] LIFT:change-host=None)>]
```

**Comment by pfps** [comment]
Ooops, `solaar show`.

**Comment by huipengcheng** [comment]
Here is the output:

```
  1: LIFT VERTICAL ERGONOMIC MOUSE
     Device path  : None
     WPID         : B031
     Codename     : LIFT
     Kind         : mouse
     Protocol     : HID++ 4.5
     Serial number: 8AC05737
     Model ID:      B03100000000
     Unit ID:       8AC05737
        Bootloader: BL1 56.00.B0008
          Firmware: RBM 21.00.B0008
             Other:
     The power switch is located on the (unknown).
     Supports 31 HID++ 2.0 features:
         0: ROOT                   {0000}
         1: FEATURE SET            {0001}
         2: DEVICE FW VERSION      {0003}
            Firmware: Bootloader BL1 56.00.B0008 B0317599BD37
            Firmware: Firmware RBM 21.00.B0008 B0317599BD37
            Firmware: Other
            Unit ID: 8AC05737  Model ID: B03100000000  Transport IDs: {'btleid': 'B031'}
         3: DEVICE NAME            {0005}
            Name: LIFT VERTICAL ERGONOMIC MOUSE
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}
         5: RESET                  {0020}
         6: CRYPTO ID              {0021}
         7: DEVICE FRIENDLY NAME   {0007}
            Friendly Name: LIFT
         8: UNIFIED BATTERY        {1004}
            Battery: 100%, discharging.
         9: REPROG CONTROLS V4     {1B04}
            Key/Button Actions (saved): {Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, DPI Switch:DPI Switch}
            Key/Button Actions        : {Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, DPI Switch:DPI Switch}
            Key/Button Diversion (saved): {Middle Button:Mouse Gestures, Back Button:Regular, Forward Button:Regular, DPI Switch:Mouse Gestures}
            Key/Button Diversion        : {Middle Button:Diverted, Back Button:Regular, Forward Button:Regular, DPI Switch:Diverted}
        10: CHANGE HOST            {1814}
            Change Host        : 1:chp-arch
        11: HOSTS INFO             {1815}
            Host 0 (paired): chp-arch
            Host 1 (paired): chp-macos
            Host 2 (paired): Logitech Bolt receiver
        12: XY STATS               {2250}
        13: LOWRES WHEEL           {2130}
            Wheel Reports: HID
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
        14: ADJUSTABLE DPI         {2201}
            Sensitivity (DPI) (saved): 2000
            Sensitivity (DPI)        : 2000
        15: DFUCONTROL             {00C3}
        16: DEVICE RESET           {1802}   internal, hidden, unknown:000010
        17: unknown:1803           {1803}   internal, hidden, unknown:000010
        18: CONFIG DEVICE PROPS    {1806}   internal, hidden, unknown:000010
        19: unknown:1816           {1816}   internal, hidden, unknown:000010
        20: OOBSTATE               {1805}   internal, hidden
        21: unknown:1830           {1830}   internal, hidden, unknown:000010
        22: unknown:1891           {1891}   internal, hidden, unknown:000008
        23: unknown:18A1           {18A1}   internal, hidden, unknown:000010
        24: unknown:1E00           {1E00}   hidden
        25: unknown:1E02           {1E02}   internal, hidden
        26: unknown:1E22           {1E22}   internal, hidden, unknown:000010
        27: unknown:1602           {1602}
        28: unknown:1EB0           {1EB0}   internal, hidden, unknown:000010
        29: unknown:1861           {1861}   internal, hidden, unknown:000010
        30: unknown:18B1           {18B1}   internal, hidden, unknown:000010
     Has 7 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click
             mse, analytics key events, pos:0, group:1, group mask:empty
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click
             mse, analytics key events, pos:0, group:1, group mask:empty
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: diverted, raw XY diverted
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button
             mse, reprogrammable, divertable, raw XY, analytics key events, unknown:000800, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button
             mse, reprogrammable, divertable, raw XY, analytics key events, unknown:000800, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: DPI Switch                , default: DPI Switch                  => DPI Switch
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: diverted, raw XY diverted
         6: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Battery: 100%, discharging.
```

**Comment by pfps** [comment]
The vertical has the feature       13: LOWRES WHEEL           {2130}. 
It appears that this feature does not have high-resolution scrolling.

**Comment by huipengcheng** [comment]
Thanks for telling me that.

I'm wondering what does high-resolution scrolling actually do? I try to use the Master3 in Scroll Wheel Resolution enabled and disabled respectively, but I can not tell the difference between these two settings.

Furthermore, I've noticed that you mention the Scroll Wheel Resolution can interfere with smooth scrolling. I've been a Mac user for many years, and I installed [SmoothScroll](https://www.smoothscroll.net/mac/) to make my mouse scrolling super smooth. But actually, on Linux, when I disabled Scroll Wheel Resolution and use Master3, I've absolutely felt nothing about smooth scrolling. Is it possible to have the same scroll behavior like SmoothScroll on Linux?

**Comment by pfps** [comment]
I'm not an expert on how Smooth Scrolling works in Linux but I believe that applications have to be set up to use it.  If they don't and the mouse is in smooth scrolling mode the input system will only send the application synthesized scroll events, i.e., only when there is enough high-resolution scroll movement to make up a regular scroll.

**Comment by huipengcheng** [comment]
I see. Thank you so much!
