### ISSUE TITLE
changing Python version requires reinstalling if using pip

### ISSUE THREAD

**Issue by titi0001** [pwr-Solaar/Solaar#1672]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository):
- Distribution:
- Ubuntu 22.04 LTS
- Kernel version (ex. `uname -srmo`): `KERNEL VERSION HERE`
- Linux 5.15.0-41-generic x86_64 GNU/Linux
- Output of `solaar show`:
- Traceback (most recent call last):
  File "/home/user/.local/bin/solaar", line 54, in <module>
    import solaar.gtk
ModuleNotFoundError: No module named 'solaar'

<details>
I can't start anymore, even after reinstallation and using the latest version of solaar 1.1.4
```
SOLAAR SHOW OUTPUT HERE
```
``` solaar --show
Traceback (most recent call last):
  File "/home/thiago/.local/bin/solaar", line 54, in <module>
    import solaar.gtk
ModuleNotFoundError: No module named 'solaar'
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
CONTENTS HERE
```
</details>

- Errors or warrnings from Solaar:

**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by pfps** [comment]
Please correctly format your issue.

**Comment by titi0001** [comment]
worked perfectly in ubuntu version 20.04.4 after i upgraded to version 22.04 I can't start anymore, even after reinstallation and using the latest version of solaar 1.1.4 ``` SOLAAR SHOW OUTPUT HERE ``` solaar --show Traceback (most recent call last): File "/home/thiago/.local/bin/solaar", line 54, in import solaar.gtk ModuleNotFoundError: No module named 'solaar'

**Comment by pfps** [comment]
The most likely source of your problem is that the version of Python changed between 20.04 and 22.04.  

Try uninstalling Solaar and then reinstalling Solaar.   

It looks like you used pip to install Solaar so you would `pip uninstall solaar` then `pip install --user solaar`.   The former might not find anything because of the version change.

**Comment by titi0001** [comment]
after reinstalling and using the commands recommended by you, now everything is working normally @pfps  tanks!!!!
