### ISSUE TITLE
Disable G1 key

### ISSUE THREAD

**Issue by jolitp** [pwr-Solaar/Solaar#1693]
I have a G613 keyboard that got the ESC key broken, then fixed, now every time I turn the keyboard on, it sends the F1 signal, and if I press the G1 key it keeps sending the F1 signal too.

![a](https://user-images.githubusercontent.com/8359524/184557279-b233cd87-23c7-4611-90ab-67cd725db414.png)

I "fixed" it with the [jtroo](https://github.com/jtroo) / [kanata](https://github.com/jtroo/kanata) software by disabling the F1 key. But now it disables the actual F1 key.

Is there a way to target only the macro key and disable that?

I tried to use rules, but the startup problem persists.

**Comment by pfps** [comment]
If you divert the G keys they will produce input that is ignored by Linux.  If you want them to do something then you can write rules for any of them, for example you could have pressing the (diverted) G1 key simulate pressing the F1 key.

That likely won't fix the startup issue as the phantom F1 keypress is likely emitted before Solaar can tell the keyboard to divert the G keys.

**Comment by jolitp** [comment]
Thanks for the explanation.

So the best I can do is disable F1 key with Kanata and make one of the other G keys to send F1 instead.

**Comment by pfps** [comment]
Yes, that's probably the best that can be done.  You need something that ignores the startup glitch, and Solar is likely not going to be able to do that.  But then you can use Solaar to make a G key simulate the F1 key.
