### ISSUE TITLE
Create a flatpak release

### ISSUE THREAD

**Issue by BMichiel** [pwr-Solaar/Solaar#1694]
A flatpak release has been started by @hadess here: https://github.com/flathub/flathub/pull/2984
There is still a pending review from april.

This has not been active in a while. I feel like it would be a shame if this stagnates and eventually gets closed.
Could you/do you still want to make a flatpak release?

(I have not created a PR since I'm completely new to how flatpaks are supposed to work, sorry)

**Comment by hadess** [comment]
> This has not been active in a while. I feel like it would be a shame if this stagnates and eventually gets closed.

I suggest you read the PR carefully. There's nothing to do until kernel and systemd changes land.

**Comment by BMichiel** [comment]
Ah I missed the part about systemd. Sorry. Closing this issue then.
