### ISSUE TITLE
Supported device docs and device info

### ISSUE THREAD

**Issue by shoffmeister** [pwr-Solaar/Solaar#1696]
The info on https://pwr-solaar.github.io/Solaar/devices, the content of https://github.com/pwr-Solaar/Solaar/blob/master/lib/logitech_receiver/descriptors.py and https://github.com/pwr-Solaar/Solaar/tree/master/docs/devices seem to be somewhat misaligned.

I would like to support Solaar by adding clean / good information for the MX Master 3S mouse, the MX Keys Mini keyboard (both on Bolt), but don't know what the best approach is.

I have `solaar show` output (see attached).

Note that the devices appear to be working reasonably well, but then I am not _utilizing_ Solaar (just yet).

[mx-keys-mini.txt](https://github.com/pwr-Solaar/Solaar/files/9358951/mx-keys-mini.txt)
[mx-master-3s-bluetooth.txt](https://github.com/pwr-Solaar/Solaar/files/9358952/mx-master-3s-bluetooth.txt)
[mx-master-3s-bolt.txt](https://github.com/pwr-Solaar/Solaar/files/9358953/mx-master-3s-bolt.txt)
[bolt-receiver.txt](https://github.com/pwr-Solaar/Solaar/files/9358954/bolt-receiver.txt)

**Comment by pfps** [comment]
From https://pwr-solaar.github.io/Solaar/devices:

The device tables below provide a list of some of the devices that Solaar supports, giving their product name, WPID product number, and HID++ protocol information.. The tables concentrate on older devices that have explicit support information in Solaar.

There is little need to add modern devices to this list, as Solaar supports many of them without any need for even a descriptor.


The descriptors in https://github.com/pwr-Solaar/Solaar/blob/master/lib/logitech_receiver/descriptors.py are only needed for some devices.  Adding a descriptor for a device that does not need one is not useful.  (At one time Solaar did need a descriptor to support a device.)


The directory https://github.com/pwr-Solaar/Solaar/tree/master/docs/devices would be the most useful, except that it hasn't been kept up to date and isn't organized in the best way.  See the next comment for a proposal to update its organization.


The most useful thing to do as far as providing information about devices (and receivers) is to add entries to the devices directory according to its updated organization.

**Comment by pfps** [comment]
Here is a new README file for the directory describing how to add entries.  Take a look and see whether you think it needs changes.


Files in this directory are edited output from `solaar show` providing
information about devices and receivers that Solaar supports.  Directions
for constructing the files are given below.  The files 
  Unifying Receiver C52B.txt
  Craft Advanced Keyboard 4066.txt
  Craft Advanced Keyboard B350.txt
  MX Master 3 Wireless Mouse 4082.txt
  MX Master 3 Wireless Mouse B023.txt
are good examples of following the directions below.


File Naming

Logitech device names are often reused so the names of files can't just be
the device name.  File names start with the name of the device or receiver as
given in the first line of of output for the device.  The file name continues
with a space and the WPID, if the device is connected to a receiver, or the
second half of the USB id, if the device is connected via USB or Bluetooth.
As devices can behave differently when connected via a receiver or USB or
Bluetooth there should be a file for each possible connection method.

Files that do not follow this naming convention are retained for historical purposes.


File Contents

Each file should start with the Solaar version as given in the first line of
output from `solaar show` and a blank line.  The rest of the file is the
output of `solaar show` for the device or receiver. The output of `solaar
show` can be edited to remove serial numbers and variable information such as
the current values of settings.


Updating Files

Newer versions of Solaar add support for more settings so it is useful to provide updated
versions of these files if there is information from the current version of `solaar show`
that is not in the existing file.

**Comment by shoffmeister** [comment]
The README looks good and the naming policy makes a whole lot of sense! 

I'd suggest fine-tuning the instructions a bit, e.g.

> Files in this directory are generated by running `solaar show DEVICE-NAME > solaar-output.txt`, for example by running `solaar show mini > solaar-output.txt`
> Discover all possible DEVICE-NAMEs by runnning `solaar show`. 
>
> Please submit your solaar-output.txt files in a new issue on Github.

Rationale:
* by providing specific instructions and an example, you get the solaar version for free in the text file
* asking people to run per device might save maintainers a bit of work
* creating a ticket with attachment has a lot less friction than submitting a PR (clone, checkout, branch, submit, review cycle(s))
* asking random users to comply with a naming convention is futile, IMHO, so by design I'd burden maintainers with enforcing the right names for the text documents (I wouldn't expect too many samples to be submitted, to be honest)

**Comment by pfps** [comment]
Good idea.  I put the issue method into the general device documentation file.

The README is mostly for future maintainers.

**Comment by pfps** [comment]
Is there anything more to be done here?

**Comment by shoffmeister** [comment]
Nope, not from my point of view - still playing with the news toy to figure out what I want (to do with solaar).

Many thanks for all the time you have spent on this software (looking at the commit history)!
