### ISSUE TITLE
Usability: Rules editor hint for (Wayland) key presses

### ISSUE THREAD

**Issue by shoffmeister** [pwr-Solaar/Solaar#1701]
Personal experience shows: people don't read the fine manual, but just do - and then are quite surprised that the "Key press" action in the Rules Editor does not have the expected effect.

Suggestion: Add a very short hint to the input section 

![image](https://user-images.githubusercontent.com/3868036/185604113-16e3da64-47d9-4e55-8f38-dab1c6a3743c.png)

that alerts users to the various challenges of doing key press (on Wayland). This is rather important, IMHO, because solaar encountering failure, e.g.,
```
12:25:57,373  WARNING [MainThread] logitech_receiver.diversion: cannot create uinput device: "/dev/uinput" cannot be opened for writing
12:25:57,373  WARNING [MainThread] logitech_receiver.diversion: no way to simulate key input
```
 is typically not conveniently discoverable for users (which in itself is not ideal, IMHO).

The hint could be as simple as "Key press actions are not robust; see <the documentation> for details".

Then people (me) might read the readme (sooner) and eventually also the rules docs.

**Comment by pfps** [comment]
It probably is a good idea to add a short explanation of each rule component in the UI.  For Key Press I'm proposing: Simulate a chorded key click or depress or release.\nOn Wayland requires write access to /dev/uinput.

**Comment by pfps** [comment]
PR #1706 adds descriptions for each rule component in the area where changes are made.   Does this address your issue?

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1706, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1706/head:pull_1706
git checkout pull_1706
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1706
git fetch origin pull/1706/head
git reset --hard FETCH_HEAD
```
