### ISSUE TITLE
Log important events into a file

### ISSUE THREAD

**Issue by shoffmeister** [pwr-Solaar/Solaar#1702]
solaar does log warnings in case of failure, e.g.
```
12:25:57,373  WARNING [MainThread] logitech_receiver.diversion: cannot create uinput device: "/dev/uinput" cannot be opened for writing
```
but these warnings appear to be only visible on the console, on stdout. To see these warnings, (an auto-started) solaar needs to be stopped (pkill solaar) and the launched from the console. This enables users to see future log entries.

It would be nicer to have solaar (also) log important events into the journald log, enabling users to inspect the logs for any solaar events that failed ... looking _back_.

**Comment by shoffmeister** [comment]
Given that solaar is a GTK UI application, it might even be rather helpful to have these events accessible in the UI (e.g. a log listview?) instead of / in addition to journald

**Comment by pfps** [comment]
Solaar is not a system program, so using the system log seems wrong.   Being able to view at least the error and warning messages in a window does seem reasonable, but is going to require some effort as much of the code that generates the messages is inside conditions that test the debugging level.

**Comment by pfps** [comment]
PR #1704 logs messages to a file in ~/.tmp, deleting the file if Solaar terminates normally.  Give it a try and see whether it works for you.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1704, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1704/head:pull_1704
git checkout pull_1704
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1704
git fetch origin pull/1704/head
git reset --hard FETCH_HEAD
```

**Comment by shoffmeister** [comment]
Nice, this gives me
```
022-08-19 22:42:42,843,843  WARNING [MainThread] logitech_receiver.diversion: rules cannot access active process or modifier keys in Wayland
2022-08-19 22:42:42,843,843  WARNING [MainThread] logitech_receiver.diversion: cannot create uinput device: "/dev/uinput" cannot be opened for writing
```
(still need to reboot for uinput)

File in tmp has good security (u=rw) and naming (no collision), too.
