### ISSUE TITLE
Missing DPI change setting on MX Anywhere 2s

### ISSUE THREAD

**Issue by Massimo-B** [pwr-Solaar/Solaar#1703]
**Information**

- Solaar version 1.1.3

Connecting an MX Master 2s I had an option to set one button to change the DPI on the fly. For the MX Anywhere 2s this feature is missing? Is this a different feature set and not supported by the Anywhere 2s? It feels like that action changing the DPI is only a software feature, because changing the DPI is possible for almost all the Logitech pointer devices, no?

**Comment by pfps** [comment]
Setting the DPI by moving the mouse requires support from the mouse so it is not available for all mice.  To check whether the MX Anywhere 2s can support this feature please provide output from `solaar show`.

**Comment by Massimo-B** [comment]
```
$ solaar show
Solaar version 1.1.3

Unifying Receiver
  Device path  : /dev/hidraw5
  USB id       : 046d:C52B
  Serial       : DBC74325
    Firmware   : 24.10.B0036
    Bootloader : 00.06
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=126, 2=179

  1: Wireless Mouse MX Master
     Device path  : None
     WPID         : 4041
     Codename     : MX Master
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: B851DD8F
     The power switch is located on the base.
     Battery: unknown (device is offline).

  2: Wireless Mobile Mouse MX Anywhere 2S
     Device path  : None
     WPID         : 406A
     Codename     : MX Anywhere 2S
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: C53F2F0B
     Model ID:      B01A406A0000
     Unit ID:       3F714CA3
        Bootloader: BOT 57.00.B0003
          Firmware: MPM 13.00.B0003
          Firmware: MPM 13.00.B0003
             Other: 
     The power switch is located on the base.
     Supports 28 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 57.00.B0003 406AD22DCF4D01
            Firmware: Firmware MPM 13.00.B0003 B01AD22DCF4D01
            Firmware: Firmware MPM 13.00.B0003 406AD22DCF4D01
            Firmware: Other   
            Unit ID: 3F714CA3  Model ID: B01A406A0000  Transport IDs: {'btleid': 'B01A', 'wpid': '406A'}
         3: DEVICE NAME            {0005}   
            Name: Wireless Mobile Mouse MX Anywhere 2S
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
            Battery: 90%, discharging, next level 50%.
         7: CONFIG DEVICE PROPS    {1806}   internal, hidden
         8: CHANGE HOST            {1814}   
         9: REPROG CONTROLS V4     {1B04}   
        10: ADJUSTABLE DPI         {2201}   
            Sensitivity (DPI) (saved): 4000
            Sensitivity (DPI)        : 4000
        11: VERTICAL SCROLLING     {2100}   
            Roller type: 3G
            Ratchet per turn: 24
            Scroll lines: 0
        12: HIRES WHEEL            {2121}   
            Multiplier: 8
            Has invert: Normal wheel motion
            Has ratchet switch: Free wheel mode
            Low resolution mode
            HID notification
            Scroll Wheel Direction (saved): False
            Scroll Wheel Direction        : False
            Scroll Wheel Resolution (saved): False
            Scroll Wheel Resolution        : False
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
        13: DFUCONTROL UNSIGNED    {00C1}   
        14: DFUCONTROL SIGNED      {00C2}   
        15: unknown:1813           {1813}   internal, hidden
        16: unknown:1830           {1830}   internal, hidden
        17: unknown:1890           {1890}   internal, hidden
        18: unknown:1891           {1891}   internal, hidden
        19: unknown:18A1           {18A1}   internal, hidden
        20: unknown:18C0           {18C0}   internal, hidden
        21: unknown:1DF3           {1DF3}   internal, hidden
        22: unknown:1E00           {1E00}   hidden
        23: unknown:1EB0           {1EB0}   internal, hidden
        24: unknown:1803           {1803}   internal, hidden
        25: unknown:1861           {1861}   internal, hidden
        26: unknown:9001           {9001}   internal, hidden
        27: OOBSTATE               {1805}   internal, hidden
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2,g4
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3,g4
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3,g4
             reporting: default
         5: Left Tilt                 , default: Mouse Scroll Left Button    => Mouse Scroll Left Button  
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3,g4
             reporting: default
         6: Right Tilt                , default: Mouse Scroll Right Button   => Mouse Scroll Right Button 
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3,g4
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Battery: 90%, discharging, next level 50%.
```

**Comment by pfps** [comment]
This mouse is able to do sliding DPI but somehow Solaar has turned the setting off.  Please provide the contents of ~/.config/solaar/config.yaml.  Alternatively you can delete this file and see whether you can then use sliding DPI on the mouse.  If you do the latter you will have to redo your settings for your mice.

**Comment by Massimo-B** [comment]
```
- 1.1.3
- _NAME: Wireless Mouse MX Master
  _absent: [hi-res-scroll, lowres-scroll-mode, thumb-scroll-mode, thumb-scroll-invert, onboard_profiles, report_rate, pointer_speed, dpi-sliding, speed-change,
    mouse-gestures, backlight, backlight-timed, fn-swap, persistent-remappable-keys, disable-keyboard-keys, divert-crown, crown-smooth, divert-gkeys, m-key-leds,
    mr-key-led, multiplatform, gesture2-params]
  _modelId: B01240410000
  _sensitive: {dpi: true, gesture2-gestures: true, hires-scroll-mode: false, hires-smooth-resolution: true, reprogrammable-keys: false, smart-shift: false}
  _serial: ...
  _unitId: AC553F01
  _wpid: '4041'
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 0, 196: 0}
  dpi: 1400
  gesture2-divert: {46: false, 98: false, 211: false, 212: false}
  gesture2-gestures: {45: true, 46: true}
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}
  smart-shift: 0
- _NAME: MX Anywhere 2S
  _absent: [hi-res-scroll, lowres-scroll-mode, smart-shift, thumb-scroll-mode, thumb-scroll-invert, onboard_profiles, report_rate, pointer_speed, speed-change,
    backlight, backlight-timed, fn-swap, persistent-remappable-keys, disable-keyboard-keys, divert-crown, crown-smooth, divert-gkeys, m-key-leds, mr-key-led,
    multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, dpi-sliding, mouse-gestures, reprogrammable-keys, divert-keys, change-host]
  _dpi-sliding: 30
  _modelId: B01A406A0000
  _sensitive: {dpi: true, dpi-sliding: true}
  _serial: ...
  _unitId: 3F714CA3
  _wpid: 406A
  divert-keys: {82: 0, 83: 1, 86: 0, 91: 1, 93: 0}
  dpi: 4000
  dpi-sliding: 91
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  mouse-gestures: 0
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 91: 91, 93: 93}

```

**Comment by pfps** [comment]
It appears that Solaar ran into a problem with the reprogrammable-keys setting for the MX Anywhere 2s and has blacklisted it.  Quit out of Solaar.   Edit ~/.config/solaar/config.yaml and remove the _absent entry for the MX Anywhere 2S.  Then run Solaar as `solaar -ddd`.  This will produce a lot of output.  See whether the DPI Sliding Adjustment shows up and works.  If not, post the output from `solaar -ddd`.  If so, report success.

**Comment by pfps** [comment]
There is an upcoming change to this capability in Solaar.  Instead of a separate setting for sliding DPI the capability is set up in Key/Button Diversion.  You might want to clone Solaar from this repository and run it so that you get the new interface now.

**Comment by Massimo-B** [comment]
After deleting the file it's working.
It seems that if using this feature the button is not usable anymore for anything else. On the MX Anywhere 2s there actually is no button that I'd like to spend only for this option.

**Comment by pfps** [comment]
Yes, if you use a button for sliding DPI it is going to be dedicated for that purpose.

**Comment by Massimo-B** [comment]
Would it be possible to use a keyboard shortcut for switching and sliding DPI of the mouse?

**Comment by pfps** [comment]
Maybe.  There is an aspect of the feature used for sliding DPI that seems to indicate that the feature can be controlled by software instead of by pressing a key.  But I haven't been able to figure out how it works.

**Comment by Massimo-B** [comment]
You could at least provide some command line args like `solaar --increase-dpi` and `solaar --decrease-dpi` with some additional argument of the device name. Then I could just create my own shortcuts to call this.
This should then also work for devices that don't support DPI sliding.

This should work as solaar is already able to increase or decrease the DPI. You mean that sliding DPI feature is something more integrated into the device firmware?

**Comment by pfps** [comment]
That can be done already.  Try `solaar config mx dpi lower` and `solaar config mx dpi higher`.

Sliding DPI works by causing the mouse to change how it reports movement.  The changed movement reports are ignored by the driver but Solaar uses them to determine how far the mouse has moved and adjust the DPI.

**Comment by Massimo-B** [comment]
Perfect, thank you for these informations.
The `solaar config` is not well documented, or where can I find the documentation?
What does the device name "mx" mean?
The command works but takes some seconds to finish. This would make it harder to step 10 steps for instance by keyboard shortcut.

**Comment by Massimo-B** [comment]
> Solaar command line interface

Sorry, but where do I find this section in which usage page?
I searched the README, the Wiki here and `solaar -h` + `solaar config -h`. A man-page wasn't installed here.

**Comment by Massimo-B** [comment]
> Solaar config takes a second or two, but shouldn't take much more than that. If it does then I suggest upgrading Solaar to the version from this repository as there have been some changes that might make help speed it up.

I'm using solaar-1.1.3 on Gentoo.

**Comment by pfps** [comment]
The bulk of the Solaar documentation is on https://pwr-solaar.github.io/Solaar/ and pages referenced there.  The main Solaar Wiki page points to this documentation.  The usage page is
https://pwr-solaar.github.io/Solaar/usage

**Comment by pfps** [comment]
The current distributed version of Solaar is 1.1.4.  Version 1.1.5 should be coming out soon.

**Comment by Massimo-B** [comment]
> The CLI is, by design, quite minimal. If you want desktop notifications you would write a shell script or something similar to do the config and then do a notification.

I'm going to script it like this:
`notify-send -t 1000 -u low -e "$(solaar config m dpi lower)"`

**Comment by pfps** [comment]
The change that makes Solaar config run faster is only in this repository and will show up in 1.1.5.

Here are two timing runs, the first for this repository and second for Solaar 1.1.4.

```
idefix Solaar> time bin/solaar config 'mx master' dpi lower
Setting dpi of MX Master 3 Wireless Mouse to 1050
0.246u 0.025s 0:00.98 26.5%	0+0k 0+160io 0pf+0w
idefix Solaar> time solaar config 'mx master' dpi lower
Setting dpi of MX Master 3 Wireless Mouse to 1000
1.707u 2.441s 0:05.39 76.8%	0+0k 0+24io 0pf+0w
```

**Comment by Massimo-B** [comment]
> The change that makes Solaar config run faster is only in this repository and will show up in 1.1.5.

Meanwhile I'm on 1.1.9 now:
```
$ solaar --version
solaar 1.1.9
```
But increasing or decreasing the dpi via a keyboard shortcut takes about 4 seconds, which makes it quite impossible to use it for lowering 10 times for instance..:
```
$ time solaar config m dpi lower
Setting dpi of Wireless Mobile Mouse MX Anywhere 2S to 3250

real	0m3,867s
user	0m0,397s
sys	0m0,043s

$ time solaar config m dpi higher
Setting dpi of Wireless Mobile Mouse MX Anywhere 2S to 3300

real	0m3,547s
user	0m0,489s
sys	0m0,024s
```

**Comment by Massimo-B** [comment]
As the MX Anywhere 2s lacks a thumb button which I usually use for Sliding DPI and I don't want to loose some back or forward button for that option, is there any way to simulate it via a keyboard button? That should behave equally like pressing for toggling high and low, and holding for sliding DPI via moving mouse up and down. I guess that's not possible to achieve with a keyboard shortcut calling an API command, is it?

**Comment by Massimo-B** [comment]
As a workaround you could add an option to press Back and Forward simultaneously, like another virtual button to use for Sliding DPI. On the Anywhere 2s this is easy by using the thumb on both buttons

**Comment by Massimo-B** [comment]
Is it possible to have a keyboard button behave like the mouse button for Sliding and switching DPI, which would mean holding the keyboard button and move the mouse for sliding DPI?

Is it possible to add another virtual button to the list of Solaar by pressing back+forward simultaneously?

Is there some `solaar config` API call to toggle between 2 DPI settings, just like the mouse button can do?

**Comment by Massimo-B** [comment]
> The change that makes Solaar config run faster is only in this repository and will show up in 1.1.5.

Today I have 1.1.13 on Gentoo.
I still have the keyboard shortcut like this:
`notify-send -t 4000 -u low -e "$(solaar config m dpi higher)"`
But it still takes far too long in order to get DPI increased 3 or 4 steps:
```
$ time solaar config m dpi higher
Setting dpi of Wireless Mobile Mouse MX Anywhere 2S to 1500

real	0m4,999s
user	0m1,531s
sys	0m0,361s

$ time solaar config m dpi lower
Setting dpi of Wireless Mobile Mouse MX Anywhere 2S to 1450

real	0m3,316s
user	0m1,605s
sys	0m0,508s
```

**Comment by pfps** [comment]
There isn't a way to make a keyboard key do the work of a mouse button.

**Comment by pfps** [comment]
Solaar is not particularly efficient.
