### ISSUE TITLE
Clarify doc on devices that might keep settings

### ISSUE THREAD

**Issue by jeblad** [pwr-Solaar/Solaar#1708]
The point "Some Linux drivers view or modify the setting Scroll Wheel Resolution to implement smooth scrolling." under [Known issues](https://github.com/pwr-Solaar/Solaar#known-issues) also relates to some settings in `solaar` itself. In particular the “Smart Shift” button on a MX Anywhere 3 mouse got stuck after it was diverted. Two machines both diverted this button, and in addition the mouse kept the setting. Both machines had to clear the setting, and in addition the mouse had to be turned off.

Not sure where it is best to add a note that the devices themselves may keep the settings, and must be turned off to clear the values.

**Comment by pfps** [comment]
Almost all settings that Solaar changes do not persist when a device is turned off or goes into power saving mode.  So whenever a device connects Solaar pushes the remembered settings to the device.  

If a device is switching between two hosts then it is up to software on the host to ensure that the device is in the correct state, e.g., by pushing all settings to the device.  If Solaar is running on both hosts then Solaar will push all settings to the device when it connects to either host.  If no software is ensuring that device state is correct on some host then settings from another host will remain until the device is powered off or goes into a power saving state.

This is very different from the smooth scrolling problem where two pieces of software - Solaar and a Linux driver - are both trying to set the Scroll Wheel Resolution at nearly the same time.

So I'm not sure what should be added beyond the section of capabilities.md

Solaar keeps track of most of the changeable settings of a device.
Devices forget most changed settings when the device is turned off
or goes into a power-saving mode.
The exceptions include the setting to change the host the device is connected to
and the setting to persistently change what a key or button does.
When Solaar starts, it restores on-line devices to their previously-known state
for the unexceptionable settings and while running it restores
devices to their previously-known state when the device itself comes on line.
Setting information is stored in the file `~/.config/solaar/config.yaml`.

**Comment by jeblad** [comment]
Seems like I myself wasn't clear enough. I figured out what happen in this case, but the doc itself is not very clear. Perhaps it is written by a very technical person that knows very well how things are done, as it uses a lot of technical jargon without explaining the terms. Explain the terms before they are used, that makes the text a lot more readable.

Perhaps the documentation could be fetched from the wiki instead? That would make it somewhat easier to fix.

**Comment by pfps** [comment]
Is there a Solaar wiki?

Enhancing the Solaar documentation can be done by submitting a PR or just suggesting changes to particular files.

**Comment by jeblad** [comment]
Github has a wiki for each project, but it must be enabled. It use Markdown out of the box, but also other wiki markup formats. I use the wiki and include it inside the doc folder as “topics”. Some important pages are outside topics, but everything that is manual-like and can be contributed goes in topics (that is the wiki).

**Comment by pfps** [comment]
The Solaar wiki has been enabled.
