### ISSUE TITLE
Clarify doc on actions inside rules

### ISSUE THREAD

**Issue by jeblad** [pwr-Solaar/Solaar#1711]
The sentence “A Rule is a sequence of components, which are either sub-rules, conditions, or actions.” in [rules.md](https://github.com/pwr-Solaar/Solaar/blob/master/docs/rules.md) are somewhat confusing. Unless I'm mistaken “actions” in rules are what the rules editor calls “handling”. It seems like it is about the same, but with some mismatch perhaps. The language could be clearer on this point.

**Comment by pfps** [comment]
As far as I can tell "handl" does not show up in the rule editor at all.  Can you provide a place where it does?

**Comment by jeblad** [comment]
“Handlinger” comes from the Norwegian translation, it is a rather bad translation of “Actions”. I should have spotted that when I visited the translation two years ago.

In a project that needs translation it is often wise to make a dictionary for troublesome words. For example, what is a “notification” in solaar? It comes from “Logitech devices that use HID++ version 2.0 or greater produce feature-based notifications that Solaar can process using a simple rule language.”

**Comment by pfps** [comment]
That's a problem when translations are not checked carefully enough and why there are professional translators.  A project like Solaar doesn't have the luxury of professional translation so the way to fix problems like this is to update the translation.  It would be useful if the software used by translators checked when a word or phrase to be translated occurs elsewhere in the project but I don't think that this part of most translation packages.  An excellent translator should do this but it is probably too much to expect most translators to do this extra checking.

**Comment by pfps** [comment]
Submitting a change to the Norwegian translation would be useful.
