### ISSUE TITLE
Eats up batteries on my Logitech k380

### ISSUE THREAD

**Issue by eldarj** [pwr-Solaar/Solaar#1713]

**Comment by pfps** [comment]
Without more information there is nothing that can be done here.  Solaar does not send commands to devices except to change settings or to restore device state when devices connect.

**Comment by pfps** [comment]
You need to provide something that shows what Solaar is doing to cause the batteries to run down.   But first you need to provide the information requested for bug reports.  Without knowing the state of Solaar and the state of the device there is very little that can be done to find out what is going on.

There are also other things you can do:

 Check whether Solaar is consuming computer resources.  Under normal circumstances Solaar should not be doing much computing.
Check whether Solaar is sending commands to the device.  You can use `solaar -ddd` to see the interactions between Solaar and the device.  There will likely be lots of information sent from the device (at least one message for each keystroke).  But Solaar should not be sending much information to the device.

**Comment by pfps** [comment]
Closing due to no further response from submitter.
