### ISSUE TITLE
Debt: _log.isEnabledFor redundant

### ISSUE THREAD

**Issue by shoffmeister** [pwr-Solaar/Solaar#1716]
The implementation uses the following pattern for logging:
```
            if _log.isEnabledFor(_INFO):
                _log.info('stopping desktop notifications')
```
This does not result in faulty behaviour, yet the test for `_log.isEnabledFor` very often is redundant, because the logging call will perform the test itself, see e.g. Python 3.10.
```
    def info(self, msg, *args, **kwargs):
        """
        Log 'msg % args' with severity 'INFO'.

        To pass exception information, use the keyword argument exc_info with
        a true value, e.g.

        logger.info("Houston, we have a %s", "interesting problem", exc_info=1)
        """
        if self.isEnabledFor(INFO):
            self._log(INFO, msg, args, **kwargs)
```

Code complexity can be reduced by removing (many of) the `isEnabledFor()` calls, at the slight runtime expense of log strings being format-constructed and then being discarded without actually doing the logging.

Any removing of such calls has to be made carefully, as some `isEnabledFor()` do seem to protect some sections with side-effects; emitting plain strings will not cause side-effects. Because of that, applying change does come with a risk of introducing regressions.

**Comment by pfps** [comment]
These conditions have been in Solaar for a long time.  I think they were added in an attempt to eliminate the cost of evaluating the arguments to the logging calls. 

Given that the conditions don't cause any bugs, there doesn't seem to be a strong reason to remove them.
