### ISSUE TITLE
When devices are discharging solaar window pops up, but is kind annoying!

### ISSUE THREAD

**Issue by ZzAntares** [pwr-Solaar/Solaar#172]
Hi, I want to know if is something I can do (a trick or something) to prevent the solaar gui window to pop up in the screen, this happens when my devices are discharging but still they have energy (sufficient energy for 2 days maybe more). It's anoying because can appear more than 3 times in a minute. Would be nice to see in the GUI an checkbox option "Open solaar GUI at device discharge", so I would untick that option.

On windows the mouse just stop working if discharged (this is what I want on linux). What can I do?

**Comment by DuaelFr** [comment]
I totally agree. That window make me lose my focus really often even if the device is still functionning really well (it did happen 4 times while writing this comment). I already have system notifications, I don't need that pop in. 

Thank you for that nice software.

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
@ZzAntares Is this a problem with the version of Solaar in this repository?

**Comment by ZzAntares** [comment]
Sorry but I really don't know, I no longer need to use Solaar as I don't have a Logitech device anymore. I'm going to close this, but feel free to re-open if you want to still track this issue.
