### ISSUE TITLE
Gnome notifications does not go away on a HID-less host

### ISSUE THREAD

**Issue by jeblad** [pwr-Solaar/Solaar#1726]
**Information**

When the HIDs are removed from a host, the notifications in Ubuntu/Gnome keeps lingering. Seems like the Gnome folks use lack of events as an indication that there are no user present. This (abuse) of missing events makes it somewhat cumbersome to post notifications when HIDs are removed from the host, as they will hang on indefinitely. Not sure if this should be posted as an Ubuntu/Gnome issue or a solaar issue, posting it here in hope there are some easy solution available.

Perhaps some kind of NOP event could be injected on the HID-less host after a few seconds, but that has problems of its own. In particular, that could disable the automatic lock of the screen if repeated, replacing a minor bug with a security issue.

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.4-52-ge0b429c (but also in 1.1.4)
- Distribution: Ubuntu 22.04 / Gnome 42.2

**Comment by pfps** [comment]
What is an "HID"?  What "events" are missing?

**Comment by jeblad** [comment]
HID – Human Interface Device, not only mouse and keyboard. It can be various devices from a cockpit for a flight simulator, a bridge for a speed boat simulator, or other such devices.

In another setup they (research) repeated the last absolute position of the mouse. I'm not sure that is possible for a standard Logitech mouse? In even another project they (forensic) send a pseudo random stream that wiggle the mouse slightly on the same spot. Perhaps a keep-alive action that outputs a stream of wiggly mouse events for a few (configurable) seconds are enough to fool the Gnome notifications.

Still, I suspect this is something the Gnome folks should fix, it is a work-around to put this into solaar.

**Comment by pfps** [comment]
So in Gnome if there are no input events the on-screen notifications do not go away ever?  That seems bad.  (But Gnome is known to do lots of bad things.)

I'm not sure that there is a way for Solaar to fix this, and it would be a problem for any piece of software.

In any case this doesn't seem to be a Solaar bug.

**Comment by pfps** [comment]
Closing as not a Solaar bug.
