### ISSUE TITLE
Turning off a host makes diverted host change keys unusable

### ISSUE THREAD

**Issue by jeblad** [pwr-Solaar/Solaar#1727]
**Information**

If a Host Switch Channel on a device (keyboard) is diverted to local rule handling on a host that goes dead, typically by turning it off, then the device can't be switched to another host. The diverted state stays, it is set in the device, while the rule that should handle the keypress goes away, as it is done in the now dead host.

MX Keys detects the current host goes offline and switches to the first host that is online. The MX Anywhere are not able to handle the situation and just hangs on the dead host. A previous keyboard had an awfully long timeout when the host went dead. Haven't tested MX Mech mini, as I have only one Bolt dongle. I believe the M590 mouse switched after a rather short timeout.

Somehow the troublesome diverted key should be reset at shutdown. That to could be cumbersome as it is not given that solaar is still running. A simple solution could be to have a "shutdown" conditional that is triggered by a signal (i.e. SIGTERM). As signals are often abused it is not a given that this gives a good or even workable solution.

In this particular case it is not critical to me, because the MX Anywhere mouse has accessible buttons underneath to manually switch the host.

**Comment by jeblad** [comment]
I only observe the problem, I don't have any good solution.

**Comment by jeblad** [comment]
Just wondering, … The #1732 change, it seems like it resets the devices when solaar exits? I believe it is common to use solaar to set some config and then terminate the program. Would this change block such use cases? Perhaps this is a kind of behavior that should be explicitly set?

**Comment by pfps** [comment]
If the Solaar GUI is run it should be run all the time.   If a device is disconnected its state may not persist and Solaar has to be running to reestablish the desired state.

The Solaar CLI also can be used to change device state but to keep device state requires some sort of scripting so that the commands are rerun when required.

**Comment by jeblad** [comment]
I wonder whether users have just adapted the use of solaar from learned behavior from the Gnome Settings editor (not sure what is the real name of this app) and/or Gnome Tweak. Perhaps it should be written out somewhere that the program manipulate states, and that such states could become inconsistent if the program is terminated early.

This is a kind of information that is probably pretty obvious for the developers, but it is not obvious for the casual user.

**Comment by pfps** [comment]
PR #1736 adds wording to the documentation saying that Solaar should be run continuously.

**Comment by pfps** [comment]
I just realized that PR #1732 is not a good idea as it will undo the high-resolution scrolling that is used by the Linux input system.  The resolution of this issue will be to list it in the known issues.
