### ISSUE TITLE
Solaar won't start in Linux Mint 21

### ISSUE THREAD

**Issue by TheAmalgamist** [pwr-Solaar/Solaar#1731]
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.4
- Distribution: Linux Mint
- Kernel version (ex. `uname -srmo`): 5.15.0-46-generic
- Output of `solaar show`: 
  Traceback (most recent call last):
  File "/home/timotheus/.local/bin/solaar", line 54, in <module>
    import solaar.gtk
ModuleNotFoundError: No module named 'solaar'

<details>

```
SOLAAR SHOW OUTPUT HERE
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
- 1.1.4
- _NAME: MX Keys Keyboard
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, pointer_speed, dpi, dpi-sliding, speed-change, mouse-gestures, backlight, backlight-timed, fn-swap, reprogrammable-keys,
    persistent-remappable-keys, divert-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host,
    gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer]
  _battery: 4096
  _serial: E08853EA
  _wpid: 408A
- _NAME: MX Master 3 Wireless Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer]
  _battery: 4096
  _serial: 135F477D
  _wpid: '4082'
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 0, 196: 0}
  dpi: 1000
  dpi-sliding: 0
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  mouse-gestures: 0
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}
  smart-shift: 10
  thumb-scroll-invert: false
  thumb-scroll-mode: false
<details>

```
</details>

- Errors or warrnings from Solaar:

**Describe the bug**
solaar won't start at all. Neither via gui, nor via terminal

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by pfps** [comment]
What happens when you execute `solaar -dd`?

**Comment by TheAmalgamist** [comment]
Output after 'solaar -dd':
Traceback (most recent call last):
  File "/home/timotheus/.local/bin/solaar", line 54, in <module>
    import solaar.gtk
ModuleNotFoundError: No module named 'solaar'

**Comment by pfps** [comment]
I expect that python has been upgraded to a new version.  You will have to reinstall Solaar.  (It appears that you used pip to install Solaar.)

**Comment by pfps** [comment]
Closing due to no response from submitter.
