### ISSUE TITLE
Flatpak distribution

### ISSUE THREAD

**Issue by k2711000** [pwr-Solaar/Solaar#1734]
I am using a Steam Deck and all my peripherals are Logitech. It would be really nice if we could get a flatpak version of Solaar so we steam deck users can use it. (The Deck has an immutable root filesystem so I can't install anything using the terminal)

The kernel is 5.13, I believe it's a custom-made one by Valve.

**Comment by pfps** [comment]
Solaar requires installation of a udev file into /etc so that it can communicate with Logitech devices.  I don't think that this can be done using flatpack.
Issue #1721 seems to indicate that installing Solaar on a Steam deck is possible.

**Comment by sidevesh** [comment]
Would it be possible to have a flatpak version where we mention to the user that they need to copy the udev rule to the right location ?

**Comment by pfps** [comment]
That should be possible but doesn't solve the original poster's problem.

Solaar distributions are generally maintained by others.  (The only exception is pip, but that is more of a python mechanism.)  If you want to provide a flatpack distribution, even one that requires extra effort, please go ahead.

**Comment by jcotton42** [comment]
@k2711000 For the Steam Deck specifically you can use a distrobox in the meantime.

I'm using an Ubuntu 20.04 box, I installed solaar with `sudo apt install solaar --no-install-recommends` (not skipping the recommends wanted to install a *ton* of packages, including full-on gnome shell).

Then, still inside the distrobox, run `distrobox-export --app solaar` to make it show up in the "start menu" on KDE.

I don't know if notifications for things like low battery will work, but I was able to adjust settings on my mouse.

**Comment by k2711000** [comment]
> @k2711000 For the Steam Deck specifically you can use a distrobox in the meantime.
> 
> I'm using an Ubuntu 20.04 box, I installed solaar with `sudo apt install solaar --no-install-recommends` (not skipping the recommends wanted to install a _ton_ of packages, including full-on gnome shell).
> 
> Then, still inside the distrobox, run `distrobox-export --app solaar` to make it show up in the "start menu" on KDE.
> 
> I don't know if notifications for things like low battery will work, but I was able to adjust settings on my mouse.

Omg thank you!

**Comment by m13253** [comment]
```
sudo steamos-readonly disable
sudo pacman-keys --init
sudo pacman-keys --populate archlinux
yay -S solaar python-pyudev
sudo steamos-readonly enable
```

Notice that any modification to SteamOS system partition (except for flatpaks) will be reset during next system upgrade.

**Comment by pfps** [comment]
@m13253 Thanks.
