### ISSUE TITLE
Claim about secure unencrypted mouse

### ISSUE THREAD

**Issue by jeblad** [pwr-Solaar/Solaar#1742]
**Information**

There is a message in solaar

```text
The wireless link between this device and its receiver is not encrypted.

For pointing devices (mice, trackballs, trackpads), this is a minor security issue.

It is, however, a major security issue for text-input devices (keyboards, numpads),
because typed text can be sniffed inconspicuously by 3rd parties within range.
```

The claim that this is a minor security issue is quite frankly false. Depending on the exposure and the threat level this can be a big gaping security hole.

I propose to replace the text with something like

```text
The wireless link between this device and its receiver is not encrypted.

it is a security issue for pointing devices, but it is a major security issue for text-input devices. Typed text (like passwords) can be sniffed inconspicuously by 3rd parties within range.
```

The new text simply inform that this is a security issue for pointing devices, and that it is a serious issue for text input devices. In particular it does not give the impression that unencrypted pointing devices doesn't have any real problems.

**Comment by pfps** [comment]
I think that text was derived from some other material and, as you say, isn't correct.

**Comment by pfps** [comment]
Does the change in PR #1744 look reasonable?

**Comment by jeblad** [comment]
Seems fine to me! It was mostly the claim that it was a minor issue I balked on. Someone could point to that and say it isn't an issue at all.

To many hours trying to explain security issues I guess.
