### ISSUE TITLE
Add support for Logitech Bluetooth Mouse M555b

### ISSUE THREAD

**Issue by bennydente** [pwr-Solaar/Solaar#1743]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): solaar 1.1.4
- Distribution: Fedora 36
- Kernel version (ex. `uname -srmo`): Linux 5.19.4-200.fc36.x86_64 x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable):

Please may you add support fot Logitech Bluetooth Mouse M555b
thanks.

DRIVER=hid-generic
HID_ID=0005:0000046D:0000B009
HID_NAME=Logitech Bluetooth Mouse M555b
HID_PHYS=28:c2:dd:90:b0:b8
HID_UNIQ=00:07:61:fd:58:57
MODALIAS=hid:b0005g0001v0000046Dp0000B009

i try to use this command
hidrd-convert -o spec /sys/class/hidraw/hidraw0/device/report_descriptor

but i got an error:
Failed to read input item at offset 110:
invalid item encountered

**Comment by pfps** [comment]
Please attach /sys/class/hidraw/hidraw0/device/report_descriptor
You will probably have to copy the file and use a .txt extension in the new filename.

**Comment by bennydente** [comment]
Thanks. Here the file.


[report_descriptor.txt](https://github.com/pwr-Solaar/Solaar/files/9469792/report_descriptor.txt)

**Comment by pfps** [comment]
It looks as if this mouse does not use the Logitech HID++ protocol so it is not a device that Solaar can support.
