### ISSUE TITLE
Fix for lack of Process condition in Wayland

### ISSUE THREAD

**Issue by sidevesh** [pwr-Solaar/Solaar#1747]
Currently solaar doesn't support Process or Mouse process condition since the X11 api that we use for it is not available on Wayland,
one way we can implement it is by building a gnome extension that exposes the current wm_class value and the mouse over wm_class values over a dbus api maybe ?
I have seen this being done by some application to workaround this exact same issue but don't remember the name of it.

If this is okay then I can take ownership of building the gnome extension.

And then we can use the api made available by it in solaar for wayland users and add info in the docs and maybe when somewhere in rules editor that the corresponding gnome extension will need to be installed for some rules to work.

Let me know if this works or if you have any other approach in mind.

**Comment by pfps** [comment]
That only works for Gnome.  I would prefer something that works for any window manager under Wayland.  I also seem to remember that there was some talk about implementing an extension like this for general use.  If this extension already exists or is in progress then using it would be reasonable.

**Comment by sidevesh** [comment]
I  only found one extension doing this and it was specific to an application that I just can't remember the name of right now.
We can make this extension general purpose so other applications needing it could use it too, unless there are other things broken in Wayland that can be fixed with an extension that are specific to Solaar.

I agree that this would only solve the issue for Gnome and not the others but I am not sure there is a way yet to do this across DE.
We can have a similar extension for KDE, I think the extension that I had seen also had a KDE counterpart.

I also found https://gist.github.com/rbreaves/257c3edfa301786e66e964d7ac036269 which may allow you to implement this without Gnome extension and the link mentions a similar KDE counterpart.

**Comment by pfps** [comment]
Does this actually work on Gnome?  If so, it might be possible to include it, although something that works with multiple window managers would be preferable.

**Comment by sidevesh** [comment]
The command mentioned in the gist did not work for me, I was trying to replace the javascript code inside the command to get it to work correctly but didn't finish it. I can take a look at it again though if that would help.

**Comment by pfps** [comment]
Sure, see whether there is a way to get it to work in Gnome without extensions.

**Comment by sidevesh** [comment]
@pfps Looks like the gdbus Eval interface is not accessible anymore from Gnome 41,
so the only way to do this would be a Gnome extension,
also I found the extension I had seen that implements similar functionality https://github.com/xremap/xremap-gnome
If an extension is okay then I can go ahead and implement one and also make the changes to read from that extension in Wayland when Gnome is running,
afaik, an extension is the only way to accomplish this right now.

**Comment by pfps** [comment]
Aaah, this is where your comment belongs.

Sure, go ahead and see whether this extension works and how to get Solaar to interface with it.  It would be also useful to get the window that the mouse is over.

**Comment by CheariX** [comment]
https://github.com/kando-menu/gnome-shell-integration

Maybe this extension might be helpful? 
It provides the currently running application and mouse position via GNOME's dbus interface.

**Comment by pfps** [comment]
That might do the trick, but someone who runs Gnome will have to figure out how to get Solaar to use it.

**Comment by casualkoala** [comment]
Now that this feature has been successfully implemented for GNOME, would it be possible to see this extended to other desktop environments such as KDE or Sway?

**Comment by SirWobbyTheFirst** [comment]
So this could be implemented in KDE using the kdotool command found at https://github.com/jinliu/kdotool, it has support for detecting the current active window as well as manipulating windows whilst Wayland is active. Any thoughts?

**Comment by kevin-wijnen** [comment]
@pfps Would it be possible to reopen this issue, considering only Gnome support is provided? (#2101)

[The tool @SirWobbyTheFirst mentions](https://github.com/jinliu/kdotool) seems to fit the bill of what's necessary to get it to work on KDE as well via `windowstate > above`. (There seems to be `getactivewindow` as well, but according to the README it does not seem to be implemented yet in kdotool?)
