### ISSUE TITLE
Accessability – Illuminate pressed keys

### ISSUE THREAD

**Issue by jeblad** [pwr-Solaar/Solaar#1748]
**Information**

In some cases it could be nice to illuminate the keys that are pressed, and then let them fade away. It would give a visual feed back that the key is activated. For people with little sensitivity in the fingers (tactile hyposensitivity, [hyposensitivity](https://en.wikipedia.org/wiki/Hyposensitivity)) this could be a help.

Is enough known about the back lightning that it would be possible (or not) to implement such a illumination pattern in solaar?

**Comment by pfps** [comment]
This is something that Solaar is not set up to do.

**Comment by jeblad** [comment]
That is actually not an answer at all.
