### ISSUE TITLE
Applet is not updated after suspend/resume

### ISSUE THREAD

**Issue by oneiros-de** [pwr-Solaar/Solaar#175]
I have a Logitech Performance MX.
The applet seems to communicate with the mouse only till a resume KDE login; so the battery state is never updated after repeated suspend/resume.

System is OpenSUSE 13.1, Solaar is 0.9.2

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closed due to no response from submitter.
