### ISSUE TITLE
Logitech K380 keyboard support

### ISSUE THREAD

**Issue by xeddog** [pwr-Solaar/Solaar#1758]
Sorry for just asking a question here, but I could not find a place to do so.

I have an older pc that I have installed Ubuntu 22.04.1 onto.  To do this, I used a corded mouse and keyboard, but now I would like to move the pc to another location and use the K380 keyboard  and M720 mouse with it (it seems a little difficult to run usb cables across 12 feet of living room floor, not to mention awkward).  I initially installed solarr 1.1.1 from the repos and tried it.  No joy.  I then removed it, added the PPA, and installed V1.1.4.  This finally allowed the M720 mouse to connect, but not the K380 keyboard.

I see on github that in the docs/devices folder there is a K380 definition for the 046d:b342 receiver, but my receiver is the unifying 046d:c52b, or 046d:c534 (lsusb command shows both).

So now the question - any estimate on when/if the K380 will be compatible with my receiver?

**Comment by pfps** [comment]
The M720 mouse connects via Bluetooth or a Unifying Receiver.  The K380 connects only via Bluetooth. So there is no way to connect a K80 to a Unifying Receiver.  This is a hardware limitation.

If your computer has bluetooth you should be able to connect both your mouse and keyboard to it.  Solaar has no role in Bluetooth connecting.

**Comment by xeddog** [comment]
Well thank you for blowing my plans all the way to hell and beck.

Seriously though, thank you for the info.  That explains a few things for me.

Wayne

________________________________
