### ISSUE TITLE
Lost pairing with nano receiver

### ISSUE THREAD

**Issue by parkerlreed** [pwr-Solaar/Solaar#176]
My grandfather's mouse (M310 - unifying capable) came with a non-unifying receiver. I without thinking  paired the M310 with my own unifying receiver. This has now rendered the original nano receiver useless. Is there any way to manually program the mouse with the unifying receiver I have?

Non-unifying

```
Path         : /dev/hidraw1
USB id       : 046d:c52f
Serial       : 83919910
  Firmware   : 22.01.B0006
Notifications: wireless
               software present
```

Unifying

```
Path         : /dev/hidraw0
USB id       : 046d:c52b
Serial       : 58C49ABA
  Firmware   : 12.01.B0019
  Bootloader : 02.14
Notifications: wireless
               software present
```

**Comment by jrbenito** [comment]
@parkerlreed 

Is this still valid?

**Comment by parkerlreed** [comment]
Yep. Still works for my nano receiver. Only pairs to single device. I think I left it open in hopes of something be tied into Solaar to allow pairing with the nano but with a warning saying only one device.

**Comment by Lekensteyn** [comment]
Is Solaar reporting that only one device can be paired? (Can you actually press the Pair button or is the option disabled?)

**Comment by parkerlreed** [comment]
I don't have ti on my at the moment to check. At least when I first tried it was just that error message that I posted earlier. I tried pairing multiple with pair.c and it never did which is where I made the assumption about only being able to pair with 1 device at a time.

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by parkerlreed** [comment]
If you're asking me, that was 3 years ago... lol. I'm not sure I even have that hardware anymore. If this needs to be closed out, go ahead.
