### ISSUE TITLE
Can't assign Middle Click to other mouse buttons

### ISSUE THREAD

**Issue by hadess** [pwr-Solaar/Solaar#1769]
Blender uses the middle mouse button **a lot** and clicking with a mouse wheel isn't very nice, so I wanted to reassign one of the side buttons of my M650 to the middle button (in addition to the mouse wheel click) so I could click more easily, but the drop-down doesn't offer it as an option.

**Comment by pfps** [comment]
@hadess Button and key changes offered by Solaar are only those that the mouse or keyboard supports.  Thee output of `solaar show` shows what changes are possible.  Solaar rules provide more possibilities.

**Comment by hadess** [comment]
It would be useful to mention that. It's not clear from the UI that this feature is hardware dependent.

**Comment by pfps** [comment]
Everything in Solaar is hardware dependent.

**Comment by hadess** [comment]
Maybe the UI, the tooltip, or something else should mention the Rule Editor which, if I'm not mistaken, isn't hardware dependent, for key reassigning that falls outside what the hardware allows.

Or if it's feasible, the UI could offer in a single drop-down the combination of what the hardware allows and the Rule Editor allows under one UI, so that any buttons can be reassigned

**Comment by pfps** [comment]
Solaar rules are hardware dependent, it is just that they depend on a slightly different aspect of the hardware, and only to initiate rule processing.  Only keys/buttons that can be diverted can initiate Solaar rule processing.

Tooltips are for short, important messages.  Something long, like suggesting that rules could be used instead, belongs in other documentation.  Solaar now has a wiki where users can provide extra information about Solaar.

It doesn't seem reasonable to add rule editor functionality to the same menu as key/button reassignment, at least not without completely changing the Solaar GUI.
