### ISSUE TITLE
Feature request: option to start minimized to tray on startup

### ISSUE THREAD

**Issue by dsluo** [pwr-Solaar/Solaar#1777]
Currently, Solaar opens its GUI every time on boot. It would be nice if there was the option to start it minimized to tray so I don't have to close it manually. Could be as simple as a `--minimized` flag.

**Comment by pfps** [comment]
From https://pwr-solaar.github.io/Solaar/

Solaar’s GUI can be started in several ways

    --window=show (the default) starts with its main window visible,
    --window=hide starts with its main window hidden,
    --window=only does not use the system tray, and starts with main window visible.

Is `--window=hide` not what you want?

**Comment by dsluo** [comment]
I missed that in the docs. Thanks!
