### ISSUE TITLE
License mismatch on the Solaar SVG files

### ISSUE THREAD

**Issue by skitt** [pwr-Solaar/Solaar#178]
Hi Daniel,

The copyright file in packaging/debian specifies that the solaar*.svg files are available under a LGPL license, but the files themselves contain metadata specifying that they are available under a CC-BY-SA 3.0 license.

Which is the correct license?

Thanks in advance,

Stephen

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by skitt** [comment]
Thanks for the update, but this bug has nothing to do with running the code, and it’s still relevant.

**Comment by pfps** [comment]
I tried to find all svg and png files in the repository and grab their metadata using identify, but I couldn't find any license information in them.  Which files have the license and how do you see it?

**Comment by pfps** [comment]
Oops, now I see the CC license.  Somehow identify doesn't pick that up.

**Comment by pfps** [comment]
Take a look at https://github.com/pwr-Solaar/Solaar/pull/616 and see if it corrects this issue.

**Comment by pfps** [comment]
Closed due to no response from submitter.
