### ISSUE TITLE
Logitech, Inc. PRO Gaming Keyboard not recognized

### ISSUE THREAD

**Issue by svevo** [pwr-Solaar/Solaar#1780]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): **1.1.5**
- Distribution: **RPM**
- Kernel version (ex. `uname -srmo`): **Linux 5.19.12-200.fc36.x86_64 x86_64 GNU/Linux**
- Output of `solaar show` for the target device (if applicable): **NA**

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Logitech, Inc. PRO Gaming Keyboard support added

**Comment by pfps** [comment]
To start the process of support for a Logitech receiver or device:

First make sure the receiver or device is connected and active.

Then run and post the output of 

```
find /sys/devices -path '*046D*/uevent' -exec cat \{\} \; | egrep HID_NAME\|HID_ID\|HID_PHYS
```

to show the names of your Logitech devices and 

```
find /sys/devices/ -path '*046D*/report_descriptor' -print -exec hidrd-convert -o spec \{\} \;
```

to show decoded report descirptors for all Logitech devices.


The program hidrd-convert might be in the package hidrd. 
If you cannot install and run it then provide the contents of the files output by 

```
find /sys/devices/ -path '*046D*/report_descriptor' -print
```

You will have to copy the contents to a file with txt extension before attaching it to your comment.

**Comment by svevo** [comment]
> find /sys/devices -path '*046D*/uevent' -exec cat \{\} \; | egrep HID_NAME\|HID_ID\|HID_PHYS

OUTPUT:
```
HID_ID=0003:0000046D:0000C339
HID_NAME=Logitech PRO Gaming Keyboard
HID_PHYS=usb-0000:00:14.0-1.1/input0
HID_ID=0003:0000046D:0000C339
HID_NAME=Logitech PRO Gaming Keyboard
HID_PHYS=usb-0000:00:14.0-1.1/input1

```

> find /sys/devices/ -path '*046D*/report_descriptor' -print -exec hidrd-convert -o spec \{\} \;

OUTPUT:
[report_descriptor.txt](https://github.com/pwr-Solaar/Solaar/files/9697569/report_descriptor.txt)

**Comment by pfps** [comment]
PR #1781 should add the keyboard.  It also fixes a couple of other problems.  Please download and run PR #1781.  Run bin/solaar from the download directory and see whether your keyboard is recognized.   If not, run `bin/solaar -ddd` and post the output.  If so, please post the output of `bin/solaar show` to document the capabilities of the keyboard.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1781, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1781/head:pull_1781
git checkout pull_1781
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1781
git fetch origin pull/1781/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
PR #1783 uses a new way to identify devices.  Please try out this PR and see whether it solves your problem.   You will have to install the hidtools library using `pip install --user hid-tools`  Run Solaar as `bin/solaar -dd` and post the output here whether or not your keyboard is recognized.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1783, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1783/head:pull_1783
git checkout pull_1783
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1783
git fetch origin pull/1783/head
git reset --hard FETCH_HEAD
```

**Comment by svevo** [comment]
Hey pfps, sorry it took me so long to reply but I've been, literally, away from the keyboard in question until now.

I've tried to run Solaar from both PR #1781 and  #1783 with different results:

#1781 seems to do the trick as the keyboard is shown if the devices list as show below
![image](https://user-images.githubusercontent.com/33728/194435325-8e7581d8-2411-43da-9756-09dc65f55c14.png)

while it doesn't show up if I use #1783 version
![image](https://user-images.githubusercontent.com/33728/194435672-0166b3f4-8e5c-4824-9572-b355fbd96f2c.png)

**Comment by pfps** [comment]
@svevo Please run in PR #1783 as `./bin/solaar -dd` and post the output.  That should any errors and warnings.  Also make sure that you have installed hid-tools using pip as directed above.

**Comment by pfps** [comment]
@svevo Also please provide output of `./bin/solaar show` when the keyboard is recognized and active, in either PR.

**Comment by pfps** [comment]
I'm reopening this issue even though PR #1781 adds the keyboard because the issue is related to PR #1783, which should get more testing.
