### ISSUE TITLE
Auto-enable smooth scrolling when enabling continuous scrolling

### ISSUE THREAD

**Issue by JensErat** [pwr-Solaar/Solaar#179]
Smooth scrolling feels nice in continuous scrolling mode (I'm using a M705), but in the stepped mode it makes the scroll wheel rather useless, as it already registers minor movements, making middle-clicks without scrolling very difficult. Automatically enabling smooth scrolling when switching to continuous mode (and disabling it vice-versa) would be a great improvement.

`xev` prints events when changing to/from the continuous mode, so it should be possible to attach some configuration change to it:

```
ButtonPress event, serial 32, synthetic NO, window 0x4a00001,
    root 0xaa, subw 0x0, time 113403970, (389,619), root:(3593,639),
    state 0x10, button 20, same_screen YES

ButtonRelease event, serial 32, synthetic NO, window 0x4a00001,
    root 0xaa, subw 0x0, time 113404282, (389,619), root:(3593,639),
    state 0x10, button 20, same_screen YES
```

**Comment by jrbenito** [comment]
Relates to #219 

@JensErat ,

Does latest master branch version solves your problem? If so, could you please close this one?

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from submitter.
