### ISSUE TITLE
How to increase wheel scroll speed

### ISSUE THREAD

**Issue by jgato** [pwr-Solaar/Solaar#1793]
Is there any way of increasing the wheel scroll speed. I can increase the DPI, but this will affect mouse movements also.

**Comment by pfps** [comment]
It is possible to increase scroll wheel speed by using Solaar rules.  But there are pitfalls in this method.  First, the Linux HID++ driver modifies the behaviour of scroll wheels for some mice to implement smooth scrolling and this may cause interference with what Solaar needs to do to increase the scroll wheel speed, resulting in extremely fast scrolling.  Second, when Solaar is not running the scroll wheel may have no effect.  Third, you can only multiply scrolling speed by a integer.  So this method is not recommended if your driver implements smooth scrolling.  

If there is some method to increase scroll wheel speed in the Linux input system that would be preferable.

What you have to do is to create two rules that multiply the scroll wheel movement.  Two rules are needed to capture both up and down movement.   The feature and test depend on what kind of wheel your mouse has, which can be determined from the output of `solaar show`.  The following two rules double the mouse scrolling speed.

```
---
- Feature: HIRES WHEEL
- Test: hires_wheel_down
- MouseScroll: [0, 2]
...
---
- Feature: HIRES WHEEL
- Test: hires_wheel_up
- MouseScroll: [0, 2]
...
```
Then divert your scroll wheel using the Scroll Wheel Diversion setting and set the scroll wheel resolution to normal using Scroll Wheel Resolution.
