### ISSUE TITLE
Solaar 1.0.1 does not completely work with ERGO M575 Trackball that has a Unifying USB dongle.

### ISSUE THREAD

**Issue by ChiefHart** [pwr-Solaar/Solaar#1799]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository):Solar 1.0.1
- Distribution:  POP!_OS 20.04LTS
- Kernel version (ex. `uname -srmo`): `KERNEL VERSION HERE`5.17.5
- Output of `solaar show`:  Just the Ergo Track Ball no battery level or other info

<details>

```
SOLAAR SHOW OUTPUT HERE
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
CONTENTS HERE
```
</details>

- Errors or warrnings from Solaar:

**Describe the bug**

**To Reproduce**

**Screenshots**
!![image](https://user-images.githubusercontent.com/45080732/196084337-eb031bde-7228-47f0-9597-4131d7a6df48.png)

**Additional context**

**Comment by pfps** [comment]
Solaar 1.0.1 is very old.  Updating to a current version of Solaar should provide much more support for the ERGO M575.
