### ISSUE TITLE
project now vendors hid-parser, blocks update

### ISSUE THREAD

**Issue by dvzrv** [pwr-Solaar/Solaar#1806]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.6
- Distribution: Arch Linux
- Kernel version (ex. `uname -srmo`): n/a
- Output of `solaar show`: n/a

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present): n/a

- Errors or warrnings from Solaar: n/a

**Describe the bug**
Hi, I am packaging solaar for Arch Linux.
Distribution packaging relies on separation of concerns and separation of packages. The vendoring of hid-parser needs to be undone by all downstream distributions again, because it is available as a separate package and can be used by other Python packages as well (see https://github.com/pwr-Solaar/Solaar/pull/1783#issuecomment-1290174757).

Please make sure to rely on hid-parser as a normal dependency and remove the git submodule again as I will not update the package this way.

**To Reproduce**
1. Try to Package solaar as a Python package without vendoring
2. Each distribution starts to patch around in the code base to not have two versions of hid-parser in their repos

**Screenshots**
n/a

**Additional context**
Devendoring of readily available libraries poses an unnecessary workload on downstream distributions. In this case it seems not necessary at all to vendor hid-parser and the library could have been depended upon as a normal Python dependency (like [all the other dependencies this project has already](https://github.com/pwr-Solaar/Solaar/blob/9ce0fd7060a1d3b8e0ab4b3a70027ddc00c075db/setup.py#L63-L69)).

**Comment by pfps** [comment]
Is hid-parser already available on arch linux as a separate package?

**Comment by pfps** [comment]
See discussion in #1075.

**Comment by dvzrv** [comment]
> Is hid-parser already available on arch linux as a separate package?

It will be packaged as soon as at least one other package requires it.

**Comment by pfps** [comment]
But if hid-parser is not packaged how can Solaar use it as a dependency?  The other dependencies of Solaar are already packaged in distributions.

**Comment by pfps** [comment]
PR #1808 makes hid_parser an optional dependency.

**Comment by pfps** [comment]
Waiting to see if PR #1808 permits building in Ubuntu.

**Comment by pfps** [comment]
Fixed by PR #1808
