### ISSUE TITLE
Ubuntu PPA not working with Utopic 14.10

### ISSUE THREAD

**Issue by CraigAD** [pwr-Solaar/Solaar#181]
I have tried to install using the daniel.pavel/ppa but run into version conflict.  If I then switch over to use the Debian repository, it works just fine.  I have tested using nano receiver and M705 with its unifying receiver.

Could the Ubuntu PPA be updated soon?

**Comment by mfonville** [comment]
Ubuntu Vivid is released (15.04) any chance that you could update the PPA for this new release too? It should be trivial (you can copy the current packages to be rebuild for the newer distro from the PPA itself)

**Comment by aquatix** [comment]
Just wanted to chime in with my +1 for a build for 15.04. The trusty version seems to work ok still, but has no battery info anymore.

**Comment by Lekensteyn** [comment]
Can you see the battery status with the latest git code? The built-in battery monitor applet of various desktop environments do not report battery status anymore because of a change in Linux 3.19. See https://bugs.launchpad.net/ubuntu/+source/upower/+bug/1448834/comments/8

**Comment by mfonville** [comment]
If Daniel Pavel would visit https://launchpad.net/~daniel.pavel/+archive/ubuntu/solaar/+copy-packages and just check the checkbox next to the trusty package, set destination to one of te newer releases, put the radio button on 'rebuild the copied sources'; at least the current old revision would be made available for the newer Ubuntu releases.

**Comment by sagikazarmark** [comment]
:+1: 

Otherwise we have to create a community maintained PPA (since we are 3 versions ahead of Trusty) which I really don't want to.

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by muzena** [comment]
https://launchpad.net/~solaar-unifying

**Comment by pfps** [comment]
Is https://launchpad.net/~solaar-unifying an indication that this issue has been resolved?  (I don't know much about launchpad.)  If not, what, if anything need to be done?

**Comment by CraigAD** [comment]
Yes, all done! Thank you for asking. Wow, that was a while ago on Utopic 
14.10; we are now at Eoan 19.10 and Solaar has been well integrated to 
the release for a long while.

Craig Denman

**Comment by pfps** [comment]
OK, closing.
