### ISSUE TITLE
Swap function Broken - TK820

### ISSUE THREAD

**Issue by m00nglum** [pwr-Solaar/Solaar#1820]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.1
- Distribution: KDE Neon
- Kernel version (ex. `uname -srmo`): Linux x86_64 GNU/Linux
- Output of `solaar show`: 

<details>

```
Solaar version 1.1.1

Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:C52B
  Serial       : 1D019848
    Firmware   : 12.10.B0032
    Bootloader : 02.14
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=67

  1: Wireless All-in-One Keyboard TK820
     Device path  : /dev/hidraw5
     WPID         : 4102
     Codename     : TK820
     Kind         : keyboard
     Protocol     : HID++ 2.0
     Polling rate : 8 ms (125Hz)
     Serial number: 7D7699C9
     Model ID:      000000000000
     Unit ID:       00000000
          Firmware: RQK 52.00.B0025
        Bootloader: BL  02.00.B0001
          Hardware: 72
             Other: 
     The power switch is located on the top right corner.
     Supports 28 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: FEATURE INFO           {0002}   
         3: DEVICE FW VERSION      {0003}   
            Firmware: Firmware RQK 52.00.B0025 4102
            Firmware: Bootloader BL  02.00.B0001 4102
            Firmware: Hardware  72 
            Firmware: Other   
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         4: DEVICE NAME            {0005}   
            Name: Wireless All-in-One Keyboard TK820
            Kind: keyboard
         5: BATTERY STATUS         {1000}   
            Battery: 20%, discharging, next level 5%.
         6: WIRELESS DEVICE STATUS {1D4B}   
         7: unknown:1DF3           {1DF3}   internal, hidden
         8: REPROG CONTROLS        {1B00}   
         9: unknown:1F03           {1F03}   internal, hidden
        10: FN INVERSION           {40A0}   
            Swap Fx function (saved): True
            Swap Fx function        : True
        11: NEW FN INVERSION       {40A2}   
            Fn-swap: enabled
            Fn-swap default: enabled
        12: MOUSE POINTER          {2200}   
            DPI: 1000
            Acceleration: low
            Override OS ballistics
            No vertical tuning, standard mice
        13: DFUCONTROL LEGACY      {00C0}   
        14: unknown:1E80           {1E80}   internal, hidden
        15: TOUCHPAD RAW XY        {6100}   
        16: unknown:1860           {1860}   internal, hidden
        17: unknown:1E00           {1E00}   hidden
        18: REPROG CONTROLS V3     {1B03}   
        19: unknown:1890           {1890}   internal, hidden
        20: unknown:18E6           {18E6}   internal, hidden
        21: unknown:18A0           {18A0}   internal, hidden
        22: unknown:1830           {1830}   internal, hidden
        23: unknown:1F04           {1F04}   internal, hidden
        24: unknown:1EA1           {1EA1}   internal, hidden
        25: unknown:18B0           {18B0}   internal, hidden
        26: ENCRYPTION             {4100}   
        27: KEYBOARD LAYOUT        {4520}   
     Has 15 reprogrammable keys:
         0: Fn Left Click              => ShowUI                        divertable
         1: Metro Appswitch            => MetroAppSwitch                is FN, reprogrammable
         2: Metro Search               => MetroSearch                   is FN, reprogrammable
         3: unknown:00B2               => MetroShare2                   is FN, reprogrammable
         4: unknown:00B3               => MetroDevices2                 is FN, reprogrammable
         5: unknown:00B4               => MetroSettings2                is FN, reprogrammable
         6: Previous                   => Previous                      is FN
         7: Play/Pause                 => Play/Pause                    is FN
         8: Next                       => Next                          is FN
         9: Mute                       => Mute                          is FN
        10: Volume Down                => Volume Down                   is FN
        11: Volume Up                  => Volume Up                     is FN
        12: Sleep                      => Sleep                         is FN, reprogrammable
        13: Left Button                => Left Click                    mse
        14: Right Button               => Right Click 
         mse
     Battery: 20%, discharging, next level 5
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

I just updated to KDE NEON with the Ubuntu 22.04 backing yesterday.  Since then, the Solaar application no longer respects the setting to NOT swap the function keys (I want my F keys to work as F keys).

The GUI shows it dimmed out (pale blue), with the switch to the right.  I tried to set the setting in my json.config manually ("fn-swap": true
) to false, but when I start up the app, it just flips it back.  It never used to be a problem... only since this update did it start.  Thanks.

- Errors or warrnings from Solaar:

**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by pfps** [comment]
Changing OS version should not affect Solaar.   One odd thing about the TK820 is that it has two FN Swap settings.  Providing contents of ~/.config/solaar/config.json or ~/.config/solaar/config.yaml will show more about the settings for the keyboard.

Settings are greyed out because they are locked or ignored, as shown by the icons on the right-hand side of the of the configuration pane.  

Solaar might be encountering some error.  To see whether this is the case, quit out of Solaar, and then run it as `solaar -ddd` and check for any warnings or errors.  If the problem is continuing post the output of `solaar -ddd`.

**Comment by m00nglum** [comment]
I agree. It wasn't the OS update that I was attributing this to, except that a new version of solaar came with it.  I don't recall what the older version was, but I know it was not 1.1.1.

I'm sorry, I didn't realize that the lock there was clickable... it doesn't look clickable, I thought it was just an icon/label indicating the function of the slider (switch). The last version I had didn't have a picture of a lock.  I guess I interpreted it to mean "lock the swap fn either on or off", because in the old days (without the lock icon) it always remembered my choice (like it was locked).  I see now that it means that the slider is or is not adjustable. I clicked the lock, and was able to move the slider.

My apologies.  It really just looked like a label to me. It didn't occur to me that I could click it.  Please feel free to close this.

**Comment by m00nglum** [comment]
By the way -- thank you for writing this software and making it open. It is really great to have!

**Comment by pfps** [comment]
Even 1.1.1 is quite old, and missing some features.  You should be able to install a recent version of Solaar via `pip3 install --user solaar`, although you will have to include the directory where pip places user executables in your execution path.
