### ISSUE TITLE
Moving Mouse/Keyboard resume from suspend

### ISSUE THREAD

**Issue by jgato** [pwr-Solaar/Solaar#1825]
I have noticed, now I have changed to unify bolt, that devices can resume the laptop from suspend. It can be easy changed following this:
https://askubuntu.com/questions/1190888/since-19-10-update-mouse-movement-wakes-computer-from-sleep
I think this was not happening with unify receiver, or I didnt notice. I know this dont depend on Solaar, but... would this be a good feature? to configure if you want or not to allow devices to resume from suspend. In my case, I would not.

**Comment by pfps** [comment]
It shouldn't matter what device or receiver you have, just whether mouse movements (or other HID input) wakes up your system.

This is outside the scope of Solaar as currently envisioned.
