### ISSUE TITLE
Few Solaar behavior questions

### ISSUE THREAD

**Issue by class101** [pwr-Solaar/Solaar#1828]
Before feeling a possible bug report with all the necessary technical infos, I'd like to experiment a bit more here and I'm just not sure if Solaar is actually working the way it is intended to be on my system.

Is it the normal Solaar behavior, with default settings, upon sleep, Solaar seems to close itself (because the tray icon disappear) and after sleep, Solaar is started again ?

Did I miss something or is there any option to stop this stop/start behavior ? I expect on sleep and resume, to have the same solaar process running, I don't really expect Solaar to waste my battery upon each resume by stopping/starting/detecting devices :(

Ideally it knows or search for my device once but when, I don't have anything new to add, I'd expect it saves somewhere my device infos

I think there is rooms for battery saving and stability improvements, each time resuming my device is detected as Unknown device until I stop and start manually Solaar, so technically it did 2 stop and 2 starts to work. 

Thank you

**Comment by class101** [comment]
I think I have found my mistake will update and close if not much to do

**Comment by class101** [comment]
Ok I think the Unknown device is caused by the fact I should press once the Mx Keys Mini keyboard for it to attempt connecting the bluetooth when resuming after a suspend, and if I don't press quick enough I get the unknown device because the keyboard has not attempted to connect the bluetooth

Found a way to mitigate, If I remind to press quickly  the keyboard when entering the session + I have added a sleep 10 before the solaar auto execution, it suffices to get ride of the Unknown device problem :)

**Comment by pfps** [comment]
Aaah.  Bluetooth devices may work differently, depending on how the Bluetooth connection is handled when your computer suspends.  I have seen some glitches resulting from Bluetooth connections not being cleanly torn down by the OS at suspend time.  But this is not a problem with Solaar.

**Comment by class101** [comment]
Yes I forgot to mention about Bluetooth, must not be as easy to handle than wired usb devices :)

On new session opening ; I can mitigate with sleep 10 && thinking to ping to keyboard under that time for it to connect 
On resuming from suspend : Not found workaround yet, I always got Unknown device from here, I have also tested `--restart-on-wake-up` but no change

I could probably workaround that writing a udev rule to  stop it on suspend and start on resume :)

**Comment by class101** [comment]
I will close this ticket you responded to everything and you cannot do much on your end.

This was very cool from you to help me out,  I will probably find a better way to start it , will investigate the udev side it seems more suitable to run it when it gets detected here

**Comment by class101** [comment]
I have learned something interesting tonight about udev, leaving the information here for anybody interested

Instead of to rely on a autostart script with a sleep I made 2 udev rules, one starting solaar with a user service and the other shutdowns it

````bash
ACTION=="add", ATTR{id/vendor}=="046d", ATTR{id/product}=="b369", ENV{SYSTEMD_USER_WANTS}+="solaar.service", TAG+="systemd"
ACTION=="remove", ATTR{id/vendor}=="046d", ATTR{id/product}=="b369", RUN+="killall -9 solaar"
```

And the content of `/home/deck/.config/systemd/user/solaar.service`

```bash
[Unit]
Description=solaar udev service

[Service]
Type=oneshot
RemainAfterExit=no
ExecStart=/home/deck/script/run-solaar.sh
```
Like that it loads solaar on demand
