### ISSUE TITLE
Solaar expected behavior with K780 Keyboard with Swap fx function?

### ISSUE THREAD

**Issue by iointerrupt** [pwr-Solaar/Solaar#1833]
First off, thank you for this helpful tool.  As a linux user glad to have it handy for managing my logitech unifying software. I recently purchased a K780 keyboard.  and used solaar to switch the default behavior to make function keys ("swap fx function").  After doing so, I quit solaar and the keyboard functioned as expected with the function keys being default.  However, after a while, if the keyboard goes idle without key presses, and I start typing again, the keyboard goes back to its default handling of the fx function. Looks like the only way to maintain the swap, is to have solaar running in the background. 

I'm just wondering whether this is the expected behavior?

**Comment by pfps** [comment]
This is expected.

Most Logitech devices forget most of their settings when they go into a power-saving state and come back with the settings in their default state.  The Solaar GUI responds to the messages that devices emit when they become active again and sends commands to reestablish the settings that it has stored for them.

**Comment by pfps** [comment]
From the Solaar documentation:

> Solaar can also control some changeable settings of devices, such as scroll wheel direction and function key behavior. Solaar keeps track of most of these settings on a per-computer basis, because devices forget most settings when powered down, and the GUI application restores them whenever a device connects. For more information on how to use Solaar see [the usage page](https://pwr-solaar.github.io/Solaar/usage), and for more information on its capabilities see [the capabilities page](https://pwr-solaar.github.io/Solaar/capabilities).

**Comment by iointerrupt** [comment]
> This is expected.

Thanks for the quick response.  Guess that makes sense to save power the keyboard switches to a deep sleep and doesn't have a persistent storage to hold state.  Since I never changed the default behavior on my other unifying mice and kbs, issues like this never surfaced.  Thanks for the documentation also.  Will now set solaar to start during user login.
