### ISSUE TITLE
A4Tech FB10C

### ISSUE THREAD

**Issue by Restonov** [pwr-Solaar/Solaar#1834]
Is it possible to add A4Tech FB10C support? Device can work via Bluetooth and 2.4G

DRIVER=hid-generic
HID_ID=0005:00001235:0000AA22
HID_NAME=A4 FB10C
HID_PHYS=70:a6:cc:7b:21:1c
HID_UNIQ=ed:8e:0e:53:7d:79
MODALIAS=hid:b0005g0001v00001235p0000AA22

Bus 003 Device 009: ID 09da:0024 A4Tech Co., Ltd. A4tech 2.4G Wireless Device
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x09da A4Tech Co., Ltd.
  idProduct          0x0024 
  bcdDevice            0.02
  iManufacturer           1 A4tech
  iProduct                2 A4tech 2.4G Wireless Device
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x003b
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               2.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      63
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               2
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               2.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     195
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               2
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0000
  (Bus Powered)

**Comment by pfps** [comment]
Just for the record, Solaar only handles devices that use HID++, a Logitech protocol.  There are a few devices that use HID++ and have the branding of other companies but only a very few and these have the Logitech Unifying logo on them.

**Comment by Restonov** [comment]
@pfps yeap, my bad. Confused Logitech via A4Tech. Thanks for the clarification!
