### ISSUE TITLE
Request: add support for Logitech K811 keyboard

### ISSUE THREAD

**Issue by loz-hurst** [pwr-Solaar/Solaar#1836]
Keyboard has backlit keys, so it may be similar to the K810 that I found a closed request to add? Based on a quick Google (other search engines are available) I think this might be just a Mac-layout version of the Windows K810 keyboard.

Requested files [per website](https://pwr-solaar.github.io/Solaar/devices) are attached:

[K811-report_descriptor.txt](https://github.com/pwr-Solaar/Solaar/files/9981724/K811-report_descriptor.txt) (N.B. binary file)

[K811-uevent.txt](https://github.com/pwr-Solaar/Solaar/files/9981735/K811-uevent.txt)

**Comment by loz-hurst** [comment]
My mistake - hadn't realised I was running the system solaar instead of the latest one, installed from Git. Works fine in the latest code :)

**Comment by pfps** [comment]
Please post output of `solaar show` with the keyboard active.  This will help if problems show up for the keyboard in the future.
