### ISSUE TITLE
Request: add support for Logitech Rechargeable Trackpad T651

### ISSUE THREAD

**Issue by loz-hurst** [pwr-Solaar/Solaar#1837]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`):

```
$ ~/.local/bin/solaar --version
solaar 1.1.7
```

```
$ git describe --tags
1.1.7-5-ga04be16
```

- Distribution: Debian
- Kernel version (ex. `uname -srmo`): `Linux 5.10.0-19-amd64 x86_64 GNU/Linux`
- Output of `solaar show` for the target device (if applicable): N/A (not detected by Solaar at all)

[T651-report_descriptor.txt](https://github.com/pwr-Solaar/Solaar/files/9982054/T651-report_descriptor.txt)

[T651-uevent.txt](https://github.com/pwr-Solaar/Solaar/files/9982056/T651-uevent.txt)

**Is your feature request related to a problem? Please describe.**
Device not recognised by Solaar.

**Describe the solution you'd like**
Ideally device to be recognised and (at least) battery status reported by Solaar.

**Describe alternatives you've considered**
Guessing when the battery will run out, with poor accuracy.

**Additional context**
No context required, request to support a currently unsupported device.

**Comment by loz-hurst** [comment]
You are quite right, hid-parser wasn't installed and adding it fixed the detection.

The section came from the template for creating a request - I thought that was where you would expect the files to be (in "Details").

Sorry for the noise, I only discovered Solaar existed today. Awesome tool, thanks for creating and maintaining it!

**Comment by pfps** [comment]
Please provide output of `solaar show`.  That information will be used to help solve problems encountered with the trackpad.

**Comment by loz-hurst** [comment]
Hi,

Here's the relevant part of `solar show`:

```
$ ~/.local/bin/solaar show
Solaar version 1.1.7

USB and Bluetooth Devices

  1: Rechargeable Trackpad T651
     Device path  : /dev/hidraw9
     USB id       : 046d:B00C
     Codename     : Rechargeable
     Kind         : touchpad
     Protocol     : HID++ 2.0
     Serial number: 
     Model ID:      000000000000
     Unit ID:       00000000
          Firmware: RBM 05.00.B0026
             Other: 
     Supports 9 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: FEATURE INFO           {0002} V0     
         3: DEVICE FW VERSION      {0003} V0     
            Firmware: Firmware RBM 05.00.B0026 B00C
            Firmware: Other   
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         4: DEVICE NAME            {0005} V0     
            Name: Rechargeable Trackpad T651
            Kind: touchpad
         5: unknown:1E00           {1E00} V0    hidden 
         6: GENERIC TEST           {1800} V0    internal, hidden 
         7: BATTERY STATUS         {1000} V0     
            Battery: 90%, discharging, next level 70%.
         8: TOUCHPAD RAW XY        {6100} V0     
     Battery: 90%, discharging, next level 70%.
```

**Comment by pfps** [comment]
Thanks.  I see that there are not very many features, but that battery information is being reported.

**Comment by loz-hurst** [comment]
Indeed, it doesn't do much (it's just a touchpad surface - no buttons or anything other than power and the connect one on the bottom). I'm mainly using Solaar for battery monitoring :)
