### ISSUE TITLE
Cannot get/set config on M705 Marathon mouse after resuming from sleep.

### ISSUE THREAD

**Issue by pvaret** [pwr-Solaar/Solaar#184]
Hello,

Thank you for making Solaar. It's a great little piece of software.

I can't get or set the config on my M705 anymore:

```
$ sudo solaar-cli config 1
[8FDED8E0:mouse]
# Marathon Mouse M705

# Smooth Scrolling
#   possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
# smooth-scroll = ? (failed to read from device)

# Side Scrolling
#   possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
# side-scroll = ? (failed to read from device)

$ sudo solaar-cli config 1 smooth-scroll off
solaar-cli: error: failed to set 'smooth-scroll' = 'False' [False]
```

I had not looked at the config in a long time, so I don't know when it stopped working.

I tried unpairing and pairing again, unplugging the receiver, etc. No change.

That's with Solaar 0.9.2 on Ubuntu 14.04.

Is there a way I can peek under the hood to see what exactly is happening there? I found nothing in my logs.

Thanks.

EDIT: After some research, the above CLI issues may have happened because the Solaar GUI was running at the time. However, the Solaar GUI was already misbehaving when I started poking around with the CLI: the 'smooth scrolling' and 'side scrolling' buttons were unresponsive, with a spinner spinning endlessly next to them.

How to reproduce:
1. Start Solaar GUI;
2. Suspend the computer;
3. Resume from sleep;
4. Try to change the scrolling settings.

Result: The scrolling setting buttons go unresponsive.

At a guess, a possible solution could be to listen on the Resuming signal of the org.freedesktop.UPower DBUS interface, and refresh the device connection information when that signal is received.

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
