### ISSUE TITLE
K600 TV Trackpad isn't working

### ISSUE THREAD

**Issue by jasonbuckingham** [pwr-Solaar/Solaar#1845]
As stated in the title. The keyboard works, the 4 way switch above the trackpad will scroll a web page / scroll through buttons in an open window. But the trackpad itself will not move the cursor.

From looking at other users' setups, I have tried enabling Gestures and disabling Gestures Diversion, to no avail.

If there's a setup guide for end users, I have not been able to find it. Also, solaar --help didn't provide any useful information I could put into action.

**Comment by pfps** [comment]
Does the trackpad work without Solaar running?   To reboot your system without Solaar running.   It is unlikely that Solaar can make a trackpad work or prevent it from working. 

See also #1843
