### ISSUE TITLE
/<<PKGBUILDDIR>>/po/es.po:1324:56: invalid control sequence

### ISSUE THREAD

**Issue by ejsc1** [pwr-Solaar/Solaar#1850]
**Information**
PPA version of solaar to install:  1.1.7+git1899-8716dc7~ubuntu22.10.1
Distribution: Ubuntu 22.10 + https://launchpad.net/~solaar-unifying/+archive/ubuntu/ppa (git)
Build status: https://launchpad.net/~solaar-unifying/+archive/ubuntu/ppa/+build/24847374
Kernel version: Linux 6.1.0-060100rc5-generic x86_64 GNU/Linux

**Comment by pfps** [comment]
Thanks
