### ISSUE TITLE
Add git information in about and console

### ISSUE THREAD

**Issue by ejsc1** [pwr-Solaar/Solaar#1852]
**Information**
Installed version of solaar::  1.1.7+git1897-9c361c4~ubuntu22.10.1
Distribution: Ubuntu 22.10 + https://launchpad.net/~solaar-unifying/+archive/ubuntu/ppa (git)
Kernel version: Linux 6.1.0-060100rc5-generic x86_64 GNU/Linux

Example:
a)
![image](https://user-images.githubusercontent.com/48624942/202720677-1d1257ab-3113-429b-b29c-78765161e1c4.png)

b)
$ solaar show
Solaar version 1.1.7-9c361c4

[...]

**Comment by pfps** [comment]
This would be useful, but how is it done?

**Comment by pfps** [comment]
I don't think that PR #1853 points out the way.

It looks as if that project has a compile phase, which can be run when git information is available.  Python doesn't work quite that way.  But perhaps the setup process can do something.

**Comment by pfps** [comment]
There are some methods that may do this, but the one I found was for Python 2, which makes it old.

https://gist.github.com/jpmens/6248478

**Comment by pfps** [comment]
PR #1856 adds an 8-character commit hash to the version information.  Please give it a try.  This PR will then have to be checked out to see whether it works in distributions.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1856, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1856/head:pull_1856
git checkout pull_1856
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1856
git fetch origin pull/1856/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
I expect this is because you don't have the package that gets the commit information installed.  I put the import of the package inside a try block just for this case.

Try `pip install --user python-git-info` and see what happens.

**Comment by pfps** [comment]
No need to compile (or any Python analogue of that).  That is the next step.

**Comment by pfps** [comment]
Alternatively you can install Solaar from the clone directory using pip.  Please download the new version of the PR and try `pip install --user '.[git-commit]'`

**Comment by pfps** [comment]
Excellent
