### ISSUE TITLE
Use Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by ejsc1** [pwr-Solaar/Solaar#1858]
![image](https://user-images.githubusercontent.com/48624942/202870663-85166658-04d8-4023-97b6-364cc3f4c3af.png)

**Comment by pfps** [comment]
I'm not sure where this comes from.   Please expand.

**Comment by pfps** [comment]
That's GitHub running the pre-commit.  Is there any way to change the OS there?

**Comment by pfps** [comment]
Even though 22.04 is available it is probably better to stay with latest - as that is likely the default setup.

I've been seeing the error you are seeing on my fork of Solaar.  I'm not sure what is causing that.  There is lots of chatter about similar problems but I haven't seen anything that looks relevant.

**Comment by pfps** [comment]
Good catch.  I wonder when this changed.

**Comment by pfps** [comment]
I'm still not seeing a reason to move from 'latest'.

**Comment by pfps** [comment]
I'm still saying to not change until GitHub moves latest to 22.04, which should happen by the end of this year.

**Comment by pfps** [comment]
Latest has switched to 22.04 or will very soon.
