### ISSUE TITLE
Create Flatpak package

### ISSUE THREAD

**Issue by ejsc1** [pwr-Solaar/Solaar#1859]
Hello,

It is important to be independent of the distributions.

Add Solaar to https://flathub.org

Thanks,

**Comment by pfps** [comment]
Someone will have to take up this.

Solaar can be installed using pip from PyPI.

**Comment by pfps** [comment]
As I know nothing about flatpak someone else will have to provide help.

**Comment by pfps** [comment]
See #1734 #1694 #1540

**Comment by pfps** [comment]
The problem appears to be that Solaar distributes a file that can't currently be distributed using flatpak and also uses system facilities that are not available inside a flatpak distribution.

**Comment by MerkuR-92** [comment]
Is it still not possible to package Solaar functionality in a Flatpak?

Now that immutable operating systems are something real and usable (right now I'm using openSUSE MicroOS as my Linux distro with almost no compromises) it would be a great QoL improvent to have Solaar.

/etc is RW and there would be no problem putting the udev rule in there for things like gestures.

**Comment by Aqua1ung** [comment]
Just in case it is an issue of permissions, there is a UI [tool](https://flathub.org/apps/details/com.github.tchx84.Flatseal) that manages flatpak apps' permissions.

**Comment by pfps** [comment]
Interesting.   Does it install Solaar's udev rule?

**Comment by pfps** [comment]
OK, closing.
