### ISSUE TITLE
stderr: fatal: could not read Username for 'https://gitlab.com/': No such device or address

### ISSUE THREAD

**Issue by ejsc1** [pwr-Solaar/Solaar#1861]
In https://github.com/pwr-Solaar/Solaar/issues/1858  problem with https://github.com/pwr-Solaar/Solaar/pull/1862

**Comment by pfps** [comment]
This error does not appear to be affecting the Solaar repository itself.  Hopefully before 22.04 becomes 'latest' the problem will have been resolved.

**Comment by pfps** [comment]
But it would be nice if someone knows why the problem is occuring.

**Comment by pfps** [comment]
Maybe

**Comment by graingert** [comment]
flake8 moved from gitlab to GitHub
