### ISSUE TITLE
No git dir found

### ISSUE THREAD

**Issue by ejsc1** [pwr-Solaar/Solaar#1863]
**Information**
- Solaar version: 1.1.7+git1905-17c30a2~ubuntu22.10.1
- Distribution: Ubuntu 22.10 + https://launchpad.net/~solaar-unifying/+archive/ubuntu/ppa
- Kernel version: Linux 6.1.0-060100rc5-generic x86_64 GNU/Linux
- Output of `solaar show`:

```
$ solaar show
No git dir found
Solaar version 1.1.7

[...]
```

**Comment by pfps** [comment]
PR #1866 uses a new way to get the git information and should not have this problem.  Please give it a try.  Try running Solaar from the clone directory.  Try installing Solaar using `pip install .` and then run Solaar from the install directory (probably ~/.local/bin/solaar).  Get the version information via --version, via show, and in the about window.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1866, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1866/head:pull_1866
git checkout pull_1866
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1866
git fetch origin pull/1866/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
So far so good.
