### ISSUE TITLE
Improved presentation of the Solaar version

### ISSUE THREAD

**Issue by ejsc1** [pwr-Solaar/Solaar#1864]
**Information**
- Solaar version: 1.1.7+git1905-17c30a2~ubuntu22.10.1
- Distribution: Ubuntu 22.10 + https://launchpad.net/~solaar-unifying/+archive/ubuntu/ppa
- Kernel version: Linux 6.1.0-060100rc5-generic x86_64 GNU/Linux
- Output of `solaar show`

**I suggest:**

Current:
1.1.7-12345678; 1.1.7-12345679; 1.1.7-12345680; 1.1.7-12345681

Gets better:
1.1.7-stable; 1.1.7-12345679; 1.1.7-12345680; 1.1.8-stable

**Comment by pfps** [comment]
An upcoming PR improves this.
