### ISSUE TITLE
Only first 3 Functions on MK700 Keyboard

### ISSUE THREAD

**Issue by bksunday** [pwr-Solaar/Solaar#187]
Hi,

I'm not sure if Solaar can help me here but I installed this because I was hoping it would give me the ability to use all MK700 Function keys, but every keyboard grabbing commands or settings in any apps does not get any event from Fn + F4 to F12. Only From Fn + F1, F2 and F3.
##### Receiver (from dmesg):
- usb 2-2.4.4: Manufacturer: Logitech
- logitech-djreceiver 0003:046D:C52B.0005: hiddev0,hidraw2: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:00:13.2-2.4.4/input2
##### Devices (from solaar-cli show):
- Unifying Receiver [/dev/hidraw2:D4BE9AC0] with 2 devices
- 1: Marathon Mouse M705 [M705:9FE7EA68] 
- 2: Wireless Keyboard MK700 [MK700:CE350C51]
##### Things I've tried:
- xev | grep -A2 --line-buffered '^KeyRelease' | sed -n '/keycode /s/^._keycode ([0-9]_).\* (._, (._)).*$/\1 \2/p'
  only getting "XF86HomePage", "XF86Mail" and "XF86Search"
- sudo showkey --scancodes  
  only getting key down & up codes for the 3 function keys as well

**Comment by jrbenito** [comment]
@bksunday ,

Could you please verify if this is still reproducible on latest master branch commit?

thanks

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
