### ISSUE TITLE
Annotations: 1 warning: pre-commit: Node.js 12 actions are deprecated.

### ISSUE THREAD

**Issue by ejsc1** [pwr-Solaar/Solaar#1871]
**Information**
- Solaar version: 1.1.7+git1906-91b9a3a~ubuntu22.10.1
- Distribution: Ubuntu 22.10 + https://launchpad.net/~solaar-unifying/+archive/ubuntu/ppa?field.series_filter=kinetic
- Kernel version : Linux 6.1.0-060100rc5-generic x86_64 GNU/Linux

Others:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

![image](https://user-images.githubusercontent.com/48624942/203175078-e1b305fe-5164-4c70-8aa0-c57c9c3e7ee8.png)

**Comment by pfps** [comment]
Fixed by #1873
