### ISSUE TITLE
MX Master 2S: 2nd scroll wheel direction

### ISSUE THREAD

**Issue by Massimo-B** [pwr-Solaar/Solaar#1879]
Is it possible to change the direction of the 2nd scroll wheel (thumb scroll wheel) only? I don't see any option about the 2nd scroll wheel at all.

Version: Solaar-1.1.3

**Comment by pfps** [comment]
That depends on the features of the mouse.   Please provide the output of `solaar show`.   Also, please update to the current version of Solaar, as it supports more settings.

**Comment by pfps** [comment]
The 2S and 3S have different feature sets.  The 2S uses gestures and it may be able to reverse thumbwheel direction by changing the Natural Scrolling gesture.

**Comment by Massimo-B** [comment]
Ok, I bumped the Gentoo distribution to add release 1.1.7.
Beside that I found it in my version:

Gestures->
      Thumbwheel [x]
      **Natural scrolling [ ]**

The latter did change the direction.

Then there is

Gestures Diversion->
Thumbwheel [ ]

What does that do? Toggling that only disables thumbwheel.

**Comment by pfps** [comment]
Diverting something changes the mesages it produces from normal messages that are interpreted by the Linux input system to messages that are ignored by Linux but can trigger Solaar rules.
