### ISSUE TITLE
Rules for MX Master 3S Thumb Wheel

### ISSUE THREAD

**Issue by Froggy232** [pwr-Solaar/Solaar#1908]
Hello,
First, thanks you a lot for your software! It works perfectly for managing logitech devices on linux and is a godsend.
There is one function that I can't seems to achieve : I have an MX Master 3 and I would like to switch virtual desktop (on gnome) by using the thumb wheel.
So far, I have try to add custom rule but it seems that the thumb wheel inputs aren't recognized.
I have, of course, enabled the "Thumb Wheel Diversion" tickbox.
I have tried to make the thumb wheel send a notify first to test it, but it hasn't worked so far.
Does someone have more experience than me in this field?
Here is a picture of my rules so far : https://ibb.co/d5nds3M
Thanks you a lot!

**Comment by pfps** [comment]
notify-send with no arguments does not create a notification.   You need to add an argument.

You can run Solaar as `solaar -ddd` to show what is going on when you move the thumb wheel.

**Comment by Froggy232** [comment]
Thanks for your answer, I have tried to replace notify-send by "notify-send "la date d’aujourd’hui :" "`date`"" but it doens't change anything, probably because the thumb wheel isn't detected.

If I launch solaar -ddd and that I scroll the thumb wheel, I have a lot of messages like that : 

DEBUG [ReceiverListener:hidraw9] logitech_receiver.base: (12) => r[11 01 0F00 00000000000000000000000000000000]
2022-12-04 16:00:07,375,375    DEBUG [ReceiverListener:hidraw9] logitech_receiver.notifications: <Device(1,4082,MX Master 3 Wireless Mouse,78007208)>: notification for feature THUMB WHEEL, report 0, data 00000000000000000000000000000000

Where the data field change for each entry.
Thanks you a lot!

**Comment by Froggy232** [comment]
I just see a lot of error message if I try to add a rule with solaar -ddd

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/logitech_receiver/diversion.py", line 394, in evaluate
    result = component.evaluate(feature, notification, device, status, result)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/diversion.py", line 394, in evaluate
    result = component.evaluate(feature, notification, device, status, result)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/diversion.py", line 394, in evaluate
    result = component.evaluate(feature, notification, device, status, result)
  File "/usr/lib/python3.10/site-packages/logitech_receiver/diversion.py", line 1092, in evaluate
    subprocess.Popen(self.args)
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

Do you think it's related? I use archlinux

**Comment by pfps** [comment]
These messages show that Solaar is processing thumb wheel notifications.   The first 16 bits of  the data is the amount the wheel moved as a signed integer.

**Comment by pfps** [comment]
The exception appears to be related.  There is some problem running the command in the Execute action.   The line before the traceback should show what is being executed as a list containing the command name and the arguments.  I expect that the problem is that you are trying to execute the command "notify-send".   Solaar executes commands directly, not via a shell, so the way to print the date is to explicitly call a shell with arguments.  If all you want to do is to check whether your rule is getting to some point just use notify-send with a single argument.

**Comment by pfps** [comment]
It is possible but not easy to slow down the movement.   

You would have to write a program that kept track of the last time it was run and only switched workspaces after a certain amount of time had elapsed.  Then you would execute this program.


As far as the "Rapport"  (Report) condition goes, this is part of the thumb-wheel test - test - thumb wheel movements are notifications from the THUMB_WHEEL feature with report 0.  So checking the report number separately isn't useful.

**Comment by Froggy232** [comment]
Shit, I really wanted this feature but it will become too much of a hassle.
Thanks you a lot for your help anyway.

**Comment by pfps** [comment]
A better solution might be to use mouse gestures.  You would press the mouse gesture button (hidden in under where your thumb normally goes) and move the mouse to the left or right and then release the mouse gesture button.

A rule would look something like:
Mouse Gesture   Mouse Left
Key Press   Super_L + Page_Down

You would need to set up the mouse gesture button to initiate mouse gestures.  In older versions of Solaar there is a special setting for this.  In newer versions of Solaar you use Key/Button Diversion.

**Comment by Froggy232** [comment]
Thanks you a lot, but unfortunately, I'm only interested in thumb wheel scrolling for switching desktop.
I understand that it's a complicated task though, I was already unable to achieve it with logiops.
Thanks for your help!

**Comment by pfps** [comment]
See issue

**Comment by pfps** [comment]
See issue #1922 for a potential solution to your issue.

**Comment by Froggy232** [comment]
Thanks you a lot!
Do you know if it will be upstreamed?
I'm not really at ease with rebuilding the package, I would prefer to wait for the aur upgrade.
Thanks you!

**Comment by pfps** [comment]
Solaar should not be run as root.  Solaar uses a udev rule to give the seated user permissions to control Logitech devices.  This rule should be in place if you install Solaar from a regular distribution. 

For more information see https://pwr-solaar.github.io/Solaar/installation

The new thumb wheel rule conditions are in version 1.1.8rc3 and will up in version 1.1.8 which should be out in a week or so.

**Comment by Froggy232** [comment]
Thanks for your answer, I have followed the "Installing Solaar’s udev rule" instruction, but the thumb wheel inputs are still not recognized if I launch it as normal user.
I will try to investigate more, thanks A LOT for your work, again!

**Comment by pfps** [comment]
To have the udev rule take effect you have to restart udev processing via `sudo udevadm control --reload-rules` or restarting.

**Comment by Froggy232** [comment]
Yes, I have restarted.
I have tried to launch solaar with -ddd as normal user and the thumb wheel input are recognized, but it doesn't change workspace like with root.
I think solaar detect the input but don't execute the action when launched as normal user.

**Comment by Froggy232** [comment]
Yes, I will, thanks you again

**Comment by CyrusRaziel** [comment]
Sorry i have a similar problem. How do I set my thumb wheel to move between tabs of the browser?

**Comment by zhuoqun-chen** [comment]
> Sorry i have a similar problem. How do I set my thumb wheel to move between tabs of the browser?

I also don't know how to write custom rules for switching tabs with thumb wheels in chrome browser like on Mac or Windows.

**Comment by pfps** [comment]
Thumb wheel movements should be turned into horizontal scroll events by Linux.   It might then be possible to set an option in your browser to use horizontal scroll events to switch tabs.   No involvement of Solaar needed.

If this doesn't work then you could use Solaar rules.   First you need to determine how to programmatically switch tabs in your browser.  Then you write rules with conditions for the thumbwheel feature for your mouse and further conditions for the content of notifications from this feature that finally execute the switch tab command.
