### ISSUE TITLE
Add build date

### ISSUE THREAD

**Issue by ejsc1** [pwr-Solaar/Solaar#1916]
**Information**
- Solaar version: 1.1.7+git1929-f3a0b85
- Distribution: Ubuntu 22.10

## Example:

![image](https://user-images.githubusercontent.com/48624942/206579662-094baea5-c282-46f1-b5dd-d77204ff081d.png)

**Comment by pfps** [comment]
Solaar now has the git commit information when not at a release commit.   That should suffice, as mere age is not an indication of how out-of-date software is.
