### ISSUE TITLE
XF86_Calculator and XF86_Calculater

### ISSUE THREAD

**Issue by hchr** [pwr-Solaar/Solaar#1917]
Solaar version: solaar 1.1.7
MX Keys

Both XF86_Calculator and XF86_Calculater are in "Key press"

I Use the Calculator key to start Dolphin
If I don't set both XF86_Calculator and XF86_Calculater to Dolphin
it runs both kcalc and dolphin on key press

XF86_Calculater, properly a spell error and should be removed?
![solaar-calculator](https://user-images.githubusercontent.com/6417330/206855301-83506437-3ff0-4862-bef0-81fa24838011.png)

**Comment by hchr** [comment]
Thank you
So it's a Logitech bug?
I do think it's a spell error.

**Comment by pfps** [comment]
The XF86 key names don't come from Logitech but instead from a file of XF86 keys.   There are other files of XF86 keys that have the same two key names in them.  So XF86_Calculater is official but weird.
