### ISSUE TITLE
Thumbwheel Sensitivity

### ISSUE THREAD

**Issue by drstee** [pwr-Solaar/Solaar#1922]
Hi,

This tool is seriously awesome, but it could do with some way to adjust the thumbwheel sensitivity. I tried diverting the thumbwheel to zoom in/out. However, I have ended up disabling the thumbwheel completely as it was annoying me. The slightest accidental touch to the wheel and things zoom to the extreme!

I also tried setting it to adjust volume. However, same issue. Slightest little movement and I nearly deafened myself.

Thanks

**Comment by pfps** [comment]
That's just how the thumbwheel works - it sends lots of movement signals for each revolution.  To do something like control zooming or volume it needs to be hooked up to something outside of Solaar that cuts down the sensitivity.

**Comment by drstee** [comment]
Thanks for the fast reply! 

Fair enough, that's a pity. I may try and come up with a way of bodging around the issue sometime.

Cheers

**Comment by pfps** [comment]
Looking more closely at the feature it might be possible to do something better.   But the question is just what should be done.   

Thumbwheel movements are reported along with a flag that says whether the thumbwheel has just started moving, is continuing to move, or has stopped moving.  So it is possible to compute a total offset for a movement and have a test that is true when the offset is more than a given amount.

**Comment by drstee** [comment]
Interesting. Thanks for taking the time to look into this.

Certainly sounds

**Comment by pfps** [comment]
Try PR #1923.  Adding a parameter to thumb wheel tests causes the test only to be true when the signed total displacement of the thumb wheel is more than the parameter (which is then lessened by the parameter).

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1923, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1923/head:pull_1923
git checkout pull_1923
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1923
git fetch origin pull/1923/head
git reset --hard FETCH_HEAD
```

**Comment by drstee** [comment]
Work of genius sir! That has worked perfectly.

**Comment by pfps** [comment]
Can you post your ~/.config/solaar/rules.yaml file to show just what rules you are using?

**Comment by drstee** [comment]
No problem, see attached.

Replaced .yaml with .txt

[rules.txt](https://github.com/pwr-Solaar/Solaar/files/10203435/rules.txt)

**Comment by HubKing** [comment]
Does this mean that I can set the thumb wheel speed in Solar? I have enabled high-resolution wheel. Since the wheel moves fast, I set the mouse wheel speed to the minimum in Plasma 6 settings. But this makes the thumbnail very slow.

On Windows, the LogiOptions+ app allows me to set thumb wheel speed, but I cannot find that option in Solar, and the OS's mouse settings have only one scroll speed setting that applies to both wheels, so that's not useable.

<img width="1063" height="580" alt="Image" src="https://github.com/user-attachments/assets/f0928088-05f8-4775-9bdc-82a58761126a" />

**Comment by pfps** [comment]
Solaar is not a device driver so there are things that it cannot really do.  You can write Solaar rules that in effect slow the thumb wheel down, but Solaar rules introduce delays between the device input and the effect of rules that may make this approach infeasible.
