### ISSUE TITLE
Possible to have custom scroll wheel actions when gesture button is pressed

### ISSUE THREAD

**Issue by sidevesh** [pwr-Solaar/Solaar#1924]
I am trying to setup a workflow where when I have the gesture button pressed, scrolling the thumb wheel up or down a notch changes the browser tabs (so basically send Ctrl + Page up / doen when scrolling up or down a notch respectively),
I wasnt able to find a condition to detect if the gesture button is pressed,
 is it that the above workflow is possible with the current capabilities and I am missing something or would something need to be implemented to support such a workflow or is this just impossible ?

**Comment by pfps** [comment]
It's not really possible for general keys.  
For modifier keys this is already possible using the Modifiers condition.
It would be possible to add a new condition that is true if a diverted key or button is down.  Would that work?

**Comment by sidevesh** [comment]
That should be okay but would that work if the button is set as Mouse Gestures and not Diverted ?
If yes then that would work.

**Comment by pfps** [comment]
Mouse Gestures is a kind of diversion so that should work.

**Comment by pfps** [comment]
It turned out to be easy to implement KeyIsDown in the rule editor so you don't need to edit rules.yaml

**Comment by sidevesh** [comment]
Thanks for implementing this, I just tried the PR don't see the KeyIsDown option in the Conditions menu in rule editor, I can see the string changes in the PR so I am sure its runing the latest code

**Comment by pfps** [comment]
That's because I forgot to add it to the menu list.  Try downloading the PR again.

**Comment by sidevesh** [comment]
I tested it and it works great! One issue though and I am definitely stretching the capabilities of this quite a bit now,
I am trying to set this up so that I can use the gesture button press and then scroll for ctrl + page up/down while still having gesture noop to trigger a key press.
The way I wired this up is that when a scroll happens while gesture button is pressed down (using the KeyIsDown condition), I set the gesture button to simply diverted and not Mouse gestures, and then when the gesture button is released (Key condition) it gets set back to Mouse gestures.
That way noop gesture should still work if I dont scroll while pressing the gesture button,
this works except when a gesture is done right after a mouse gesture pressed scrolling, seems like the gesture is not detected, the second time it works.
I can see that the gesture button gets set back to Mouse gestures as I release the gesture button press after scrolling.
Any pointers on why this might be happening or if there's a better way to wire up this workflow ?

I think its fine to merge this pr in since this seems like a different issue,
and again, thanks for implementing this so swiftly, it absolutely blows my mind how much more better Solaar is compared to what Logitech offers with their first party software on Windows / Mac.

Edit: Posted this earlier on the commit but moved it here since this is not relevant to the pr.

**Comment by pfps** [comment]
I'm not exactly sure what rules you have written, but you should be able to just have the Mouse Gesture Button diverted to mouse gestures.   When the gesture button is down under these circumstances it should still be down for KeyIsDown.

If you think something is going wrong please post the rules you are using.

This PR will not be merged in until after version 1.1.8 is released.

**Comment by pfps** [comment]
Changing the status of the Mouse Gesture Button during a mouse gesture, i.e., when the Mouse Gesture Button is diverted to mouse gestures and pressed, will not do what I think you want it to do.  As soon as the button is pressed mouse gesture processing is initiated.  The mouse gesture gathering will be performed as long as the button is down.   The gathered mouse gesture will be processed when the Mouse Gesture Button is released.    If the Mouse Gesture Button status is changed when the button is down the status change is delayed until the button is released.  At least this is what I think is going to happen based on the documentation I have but in reality what will happen may differ for different mice.

As well, changes to the device are performed only when Solaar is in an idle state, so changing the diversion status of the Mouse Gesture Button may be delayed.

The processing interactions are quite complex, so the best way to find out what is going on is to run Solaar with the `-ddd` switch and capture the output.  You will need to annotate the output with what actions you performed.

**Comment by sidevesh** [comment]
Makes sense, changing the Key diversion from Mouse gestures to Diverted in between a gesture is surely hacky,
I think my [articular workflow can be achived if a Set / Read variable Action / Condition is added,
then a variable can be set when scrolling happens with Mouse gesture button pressed and then when Gesture noop happens, we can check if that variable is set before executing action.
Or maybe another less simpler but much more powerful approach would be to add a Execution output condition since we already have Execute action. This would probably also be simpler and quicker to implement.
Either of these approaches would make Rules execution stateful and allow for much more powerful rules, including the one I outlined above.
Can either of these be implemented ?

**Comment by pfps** [comment]
Neither of these is likely to be implemented.
If the Execution output condition checks the output of an external program that is very unlikely to be implemented.
