### ISSUE TITLE
Solaar needs access to uinput to simulate input in Wayland

### ISSUE THREAD

**Issue by Froggy232** [pwr-Solaar/Solaar#1927]
Hello,
So, I have tried to switch gnome workspace with the MX Master 3 Thumbwheel.
So far, I have : 

- Ticked the "Thumb Wheel Diversion" toolbox
- Create a new rule with "Test : thumb_wheel_up / Touch Press : Super_L + Page_Down"

If I try to switch workspace, it doesn't work.
If I do the same step as root, everything work.
Finally, if I launch solaar with -ddd option as normal user, the thumb wheel input are well received, so I think it's a problem with the execution of the action.
Thanks you a lot!

**Comment by pfps** [comment]
Please provide contents of ~/.config/solaar/rules.yaml and output of solaar -ddd

**Comment by Froggy232** [comment]
So, rules.yaml is here : https://pastebin.com/VzsqrVeu
Output of solaar -ddd is something like that : 

2022-12-12 14:24:35,813,813    DEBUG [ReceiverListener:hidraw5] logitech_receiver.notifications: <Device(1,4082,MX Master 3 Wireless Mouse,78007208)>: notification for feature THUMB WHEEL, report 0, data 00000000030400000000000000000000

**Comment by pfps** [comment]
From the Solaar documentation


* Solaar will try to use uinput to simulate input from rules under Wayland or if Xtest is not available but this needs write permission on /dev/uinput. For more information see [the rules page](https://pwr-solaar.github.io/Solaar/rules).

From the rules page:

*Note that rule processing only fully works under X11.
When running under Wayland with X11 libraries loaded some features will not be available.
When running under Wayland without X11 libraries loaded even more features will not be available.
Rule features known not to work under Wayland include process and mouse process conditions.
Under Wayland using keyboard groups may result in incorrect symbols being input for simulated input.
Under Wayland simulating inputs when modifier keys are pressed may result in incorrect symbols being sent.
Simulated input uses Xtest if available under X11 or uinput if the user has write access to /dev/uinput.
The easiest way to maintain write access to /dev/uinput is to use Solaar's alternative udev rule by downloading
`https://raw.githubusercontent.com/pwr-Solaar/Solaar/master/rules.d-uinput/42-logitech-unify-permissions.rules`
and copying it as root into the `/etc/udev/rules.d` directory.
You may have to reboot your system for the write permission to be set up.
Another way to get write access to /dev/uinput is to run `sudo setfacl -m u:${USER}:rw /dev/uinput`
but this needs to be done every time the system is rebooted.*

**Comment by pfps** [comment]
I suspect that the problem is no permissions on uinput.  To validate that requires looking at the early output of `solaar -ddd`.

**Comment by Froggy232** [comment]
Nice, thanks you!
The full output of solaar -ddd is here : https://pastebin.com/Y9S9KqFW

**Comment by pfps** [comment]
Indeed, the problem is lack of access to uinput
```
2022-12-12 14:31:33,962,962  WARNING [MainThread] logitech_receiver.diversion: cannot create uinput device: "/dev/uinput" cannot be opened for writing
```

**Comment by Froggy232** [comment]
Ok, sorry for that, so the solution would be to add the 42-logitech-unify-permissions.rules to udev rules?
I have already do that strangely, but I will try to do it again.
Thanks you, again

**Comment by badaz** [comment]
OMG it works ! Thanks a lot ! This should definetly be documented [here](https://pwr-solaar.github.io/Solaar/installation), I lost so much time figuring this out

**Comment by pfps** [comment]
If you are using Solaar rules you should read the rules documentation https://pwr-solaar.github.io/Solaar/rules which describes this.

**Comment by badaz** [comment]
Thanks so much, my bad, I went over this page many times, and until I stumbled upon this issue the similarity in the 2 rule.d file paths made me miss the fact that there were actually two different rule files
