### ISSUE TITLE
Error message when launch at startup

### ISSUE THREAD

**Issue by Froggy232** [pwr-Solaar/Solaar#1935]
Hello,

I have a small, minor bug where if I set solaar to launch at startup by using the provided .desktop file, I have this error message every time I boot :  https://ibb.co/pbr22mC
It says that it has detected the receiver, but it doesn't have the authorization to open it.
If I delete the .desktop file in the autostart directory and launch manually solaar at every boot, everything work flawlessly.

I think that adding a delay to the startup of solaar could solve this, as it's solve the apparently same problem with logiops.
Unfortunately, I don't know how to do that.

Thanks you!

**Comment by pfps** [comment]
This looks like the same problem as in Issue #1930.    It appears that Solaar is trying to access a Logitech device before Solaar's udev rule changes the permissions.  Look at that issue and try the PR mentioned there.

**Comment by Froggy232** [comment]
It seems to work, thanks you!
