### ISSUE TITLE
To unlock settings click on the lock icons

### ISSUE THREAD

**Issue by jasaf99** [pwr-Solaar/Solaar#1944]
With the mouse, it is not possible to make settings in Soolar. There is a lock on the right behind the respective settings, both in Bluetooth mode and for the stick.
![Screenshot_20221223_114725](https://user-images.githubusercontent.com/121291204/209322826-988a2547-3547-4184-b12d-8f1e979ac23b.png)

**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository):
- Distribution:
- Kernel version (ex. `uname -srmo`): `KERNEL VERSION HERE`
- Output of `solaar show`:

<details>

```
SOLAAR SHOW OUTPUT HERE
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
CONTENTS HERE
```
</details>

- Errors or warrnings from Solaar:

**Describe the bug**

**To Reproduce**

**Screenshots**

**Additional context**

**Comment by pfps** [comment]
Click on that lock to unlock the settings.

**Comment by pfps** [comment]
From https://pwr-solaar.github.io/Solaar/usage

> Device settings now have a clickable icon that determines whether the setting can be changed and whether the setting is ignored.

**Comment by pfps** [comment]
Closed due to no response from submitter.

**Comment by mrwensveen** [comment]
Sorry to necro this issue but I didn't want to open a new issue just for a question.

What is the use case for the lock icon? What does it mean for a setting to be locked/unlocked? Obviously, if it was just to prevent changing from the UI, an unlockable lock icon is just an extra click?
Do I unlock the setting, change it, and then lock the setting again?

**Comment by pfps** [comment]
The lock icon was initially put in place to prevent inadvertent changes of settings.

The lock icon now has a third value - ignore this setting.  Solaar will then not try to keep the setting aligned with the stored value.  This is needed, for example, if some other software (like a Linux driver) wants to modify the setting.

**Comment by mrwensveen** [comment]
That makes sense. Thanks for answering!
