### ISSUE TITLE
Multiple battery level in menubar/taskbar ?

### ISSUE THREAD

**Issue by iangregsondev** [pwr-Solaar/Solaar#1946]
Hi,

Can anyone help ? Everything seems to be working but I have 2 devices connected and I only have 1 battery level icon being displayed in the menubar/taskbar.

Is this normal ? What does the 1 icon refer to , which device ? Is it possible to display an icon for each device.

I suppose this picture shows better what I am referring to. You can see on the upper menu/taskbar - only 1 icon when there is actually 2 devices.

THanks

![image](https://user-images.githubusercontent.com/2370364/209843203-3ed57e13-54fc-4b3d-abc4-baf98c794bfe.png)

**Comment by pfps** [comment]
The icon in the status tray (menu bar) is for the device with the lowest battery level.    The Solaar menu shows levels for each active device.  If your system tray supports mouse-over pop-ups the Solaar mouse-over pop-up shows battery levels for all active devices as well, at least for recent versions of Solaar.

Showing multiple icons would be complicated and likely against the intent of the system tray.

**Comment by iangregsondev** [comment]
Ok, Thanks, yes makes sense.

Regards
