### ISSUE TITLE
Noise removal support

### ISSUE THREAD

**Issue by Tibladar** [pwr-Solaar/Solaar#1950]
**Information**
- Solaar version: 1.1.8
- Distribution: Ubuntu 22.04

Currently there's no support for setting the noise removal setting for headsets (at least for the Logitech G535)
![grafik](https://user-images.githubusercontent.com/52620063/210230913-81345c48-1443-43c6-9dff-b1e00e48c260.png)

I don't know if that setting affects the headset itself or is done on application side but when changing the setting there are some events being sent to the headset:
- Noise removal activated: [noise_removal_on.pcapng.gz](https://github.com/pwr-Solaar/Solaar/files/10331585/noise_removal_on.pcapng.gz)
- Noise removal deactivated: [noise_removal_off.pcapng.gz](https://github.com/pwr-Solaar/Solaar/files/10331586/noise_removal_off.pcapng.gz)

**Comment by pfps** [comment]
Presumably the traces you have are for running some Logitech software.  How did you obtain these traces?

The traces show one HID++ interaction with the device, which sets the sidetone level.  The other interactions appear to use other interfaces.  Solaar is designed for HID++ interactions and other interfaces are outside of its scope.

**Comment by pfps** [comment]
The USBHID interaction (set report request and response and then the URB_INTERRUPT in messages) appear to be the same in both traces, with the control data being
```
11ff041b00000000000000000000000000000000
```
which sets the sidetone to 0.

If you provide a trace that turns the noise removal to off then on then off again that would make it easier to see what is going on.

But if it is the sidetone feature that is being used, Solaar already has a setting for this that should show up for your headset.  It is just a matter of discovering which value is best to use.

**Comment by pfps** [comment]
I see the Logitech software sending commands to the device but each one is the same.  (The command is the data fragment for the USBHID SET_REPORT Request frames and sets sidetone to 0.)

So it appears that noise reduction is being done solely by the Logitech software with no device involvement.  I have no idea how that works.
