### ISSUE TITLE
DPI interacts differently with resolution scaling after restarting/unlocking the computer

### ISSUE THREAD

**Issue by DoNotWorr** [pwr-Solaar/Solaar#1951]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.7
- Distribution: Kubuntu
- Kernel version (ex. `uname -srmo`): Linux 5.15.0-56-generic x86_64 GNU/Linux
- Output of `solaar show`:

<details>

```
Solaar version 1.1.7

Lightspeed Receiver
  Device path  : /dev/hidraw4
  USB id       : 046d:C539
  Serial       : 9CC39F4A
    Firmware   : 39.06.B0040
    Bootloader : 02.09
    Other      : AA.BE
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

  1: G Pro Wireless Gaming Mouse
     Device path  : /dev/hidraw5
     WPID         : 4079
     Codename     : G Pro 
     Kind         : mouse
     Protocol     : HID++ 4.2
     Polling rate : 1 ms (1000Hz)
     Serial number: 5338F75D
     Model ID:      4079C0880000
     Unit ID:       5338F75D
        Bootloader: BOT 74.02.B0026
          Firmware: MPM 15.02.B0026
             Other: 
     The power switch is located on the base.
     Supports 29 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: Bootloader BOT 74.02.B0026 AADF85EE714A
            Firmware: Firmware MPM 15.02.B0026 407985EE714A
            Firmware: Other   
            Unit ID: 5338F75D  Model ID: 4079C0880000  Transport IDs: {'wpid': '4079', 'usbid': 'C088'}
         3: DEVICE NAME            {0005} V0     
            Name: G Pro Wireless Gaming Mouse
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: RESET                  {0020} V0     
         6: BATTERY VOLTAGE        {1001} V2     
            Battery: 70% 3973mV , discharging.
         7: COLOR LED EFFECTS      {8070} V4     
         8: LED CONTROL            {1300} V0     
         9: ONBOARD PROFILES       {8100} V0     
            Device Mode: On-Board
            Onboard Profiles (saved): Enable
            Onboard Profiles        : Enable
        10: MOUSE BUTTON SPY       {8110} V0     
        11: REPORT RATE            {8060} V0     
            Polling Rate (ms): 1
            Polling Rate (ms) (saved): 1
            Polling Rate (ms)        : 1
        12: ADJUSTABLE DPI         {2201} V1     
            Sensitivity (DPI) (saved): 400
            Sensitivity (DPI)        : 400
        13: DEVICE RESET           {1802} V0    internal, hidden 
        14: unknown:1803           {1803} V0    internal, hidden 
        15: OOBSTATE               {1805} V0    internal, hidden 
        16: CONFIG DEVICE PROPS    {1806} V4    internal, hidden 
        17: unknown:1811           {1811} V0    internal, hidden 
        18: unknown:1830           {1830} V0    internal, hidden 
        19: unknown:1890           {1890} V2    internal, hidden 
        20: unknown:1891           {1891} V2    internal, hidden 
        21: unknown:18A1           {18A1} V0    internal, hidden 
        22: unknown:1801           {1801} V0    internal, hidden 
        23: unknown:18B1           {18B1} V0    internal, hidden 
        24: unknown:1DF3           {1DF3} V0    internal, hidden 
        25: unknown:1E00           {1E00} V0    hidden 
        26: unknown:1EB0           {1EB0} V0    internal, hidden 
        27: unknown:1863           {1863} V0    internal, hidden 
        28: unknown:1E22           {1E22} V0    internal, hidden 
     Battery: 70% 3973mV , discharging.
```

</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
- 1.1.7
- _NAME: G Pro Wireless Gaming Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    pointer_speed, speed-change, backlight, backlight-timed, fn-swap, reprogrammable-keys, persistent-remappable-keys, divert-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params, sidetone,
    equalizer, scroll-ratchet]
  _battery: 4097
  _modelId: 4079C0880000
  _sensitive: {dpi: true}
  _serial: 5338F75D
  _unitId: 5338F75D
  _wpid: '4079'
  dpi: 400
  onboard_profiles: 1
  report_rate: 1
- _NAME: G Pro Wireless Gaming Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, reprogrammable-keys, persistent-remappable-keys, divert-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params, sidetone,
    equalizer]
  _battery: 4097
  _modelId: 4079C0880000
  _sensitive: {dpi: ignore}
  _serial: 97F1CC65
  _unitId: 97F1CC65
  _wpid: '4079'
  dpi: 400
  onboard_profiles: 1
  report_rate: 1
```
</details>

- Errors or warrnings from Solaar:

**Describe the bug**
When using resolution scaling in xrandr, the mouse will work like normal on startup.
After locking the computer for a longer period and then unlocking, there are two issues:

A. The mouse sensitivity is too high (multiplied by the resolution scaling multiplier, it seems). To be clear, when the bug changes I need to double my regular DPI.
B. It's not possible to change DPI in the Solaar application when using wireless mode (Logitech Wireless Pro). After connecting the usb cable it will work again (both in wired and wireless mode).

**To Reproduce**
1. Use xrandr to set a resolution scaling. I use `xrandr --output DP-1 --mode 3840x1600 --scale 1.5x1.5` after logging in.
To find name of output, use `xrandr | grep ' connected'`. To find mode, use default resolution for monitor. Use an arbitrary number for scaling like 1.5 or 2.
2. Use an apppropriate DPI in Solaar. It's not needed to change this on startup/login. As a side note, this bug usually occurs once per day for me, so I naturally have to change the DPI to my normal DPI in the morning (as described in step 6).
4. Lock computer for a while. I haven't found the exact amount which is required to reproduce this bug. It always happens in a lunch break (i.e 30-60 minutes) and rarely or never in a shorter break (i.e 5-10 minutes).
5. When you unlocked the computer, the bug will happen (see description of bug).
6. Bug is gone after a restart, but the halfed value in Solaar is still there (as described in step 2), so upon restarting the computer you need to double the DPI to get back to normal.

**Screenshots**
I can update the issue with screenshots of how the Solaar application looks when I'm unable to change the DPI (as described in part B of the bug)

**Additional context**
No

**Comment by pfps** [comment]
It is possible that the mouse works differently when connected via its USB cable versus when connected via a Lightspeed receiver.  To diagnose this please run `solaar show` for both connection methods and post the result.

**Comment by pfps** [comment]
The interaction with scaling and sensitivity and locking is puzzling.  

The only things that Solaar should be doing is setting the sensitivity of the mouse.  You can see the value for this setting in the output of `solaar show` in the ADJUSTABLE DPI feature, both as kept in Solaar (the entry with '(saved)') and as reported by the mouse (the other entry).  

Try running `solaar show` shortly after you restart your computer, after you run xrandr, after a short locking session, after a long locking session, and after you adjust the sensitivity.   Look for any unexpected changes in either entry.  Post all your results.

**Comment by DoNotWorr** [comment]
After unlocking the computer just now (step 4 in reproducing the bug) I noticed that there is an info message when trying to double the DPI to correct for the bug: Read/write operation failed.

I will update the PR with results from solaar show later.

**Comment by pfps** [comment]
Please run solaar as `solaar -ddd` and provide the output around the time of restart.

**Comment by pfps** [comment]
Do you have one mouse or two?  Your config file has two different G Pro entries with different serial numbers.

**Comment by pfps** [comment]
Closed due to no response from submitter.
