### ISSUE TITLE
Inaccurate battery indicator

### ISSUE THREAD

**Issue by Tibladar** [pwr-Solaar/Solaar#1957]
**Information**
- Solaar version: 1.1.8
- Distribution: Ubuntu 22.04

When using a Logitech G535 the battery level indicated in Solaar shows a different level than Logitech G Hub under Windows.

```
$ solaar show
solaar version 1.1.8

USB and Bluetooth Devices

  1: G535 Wireless Gaming Headset
     Device path  : /dev/hidraw0
     USB id       : 046d:0AC4
     Codename     : G535
     Kind         : ?
     Protocol     : HID++ 4.2
     Serial number: 
     Model ID:      000000000AC4
     Unit ID:       FFFFFFFF
          Firmware: U1  90.00.B0200
     Supports 6 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: Firmware U1  90.00.B0200 0AC4
            Unit ID: FFFFFFFF  Model ID: 000000000AC4  Transport IDs: {'btid': '0000', 'btleid': '0000'}
         3: DEVICE NAME            {0005} V0     
            Name: G535 Wireless Gaming Headset
            Kind: None
         4: SIDETONE               {8300} V0     
            Sidetone (saved): 0
            Sidetone        : 0
         5: ADC MEASUREMENT        {1F20} V3     
            Battery: 100% 4201mV , recharging.
            Power Management (saved): 7
            Power Management        : 7
     Battery: 100% 4201mV , recharging.
```
G Hub:
![grafik](https://user-images.githubusercontent.com/52620063/210422672-85e9d212-6b98-4fb0-9236-87e57d06b3e1.png)

Wireshark trace when G Hub pulls the battery level: [battery.pcapng.gz](https://github.com/pwr-Solaar/Solaar/files/10339048/battery.pcapng.gz)

**Comment by pfps** [comment]
The device doesn't have any information on battery status, as far as I can tell.  I guess you could get current maximum if you get the voltage after charging to maximum, but I don't know if even this would be accurate.  These batteries are not like the batteries in high-end laptops.

I'm sure that G Hub has its own mapping that is used for all devices with this kind of battery.

You could take battery measurements from Solaar and G Hub to get a better mapping.  That would probably require on the order of 20 measurements at the right times to get something you could count on.

**Comment by pfps** [comment]
I'm closing this (for now, at least).   If new information comes in the issue can be reopened.

**Comment by pfps** [comment]
For this device feature, Solaar is just reporting what the device reports.   The display could be a bit nicer when recharging, I admit.

It might be that your battery is aging and thus does not charge to full.

**Comment by pfps** [comment]
There are only a few battery levels that are reported for most devices that use the feature that this device uses, so a report of 50% might mean something quite different from half full.  Each device model (and firmware, and ...) has in principle its own way of determining the battery level.
