### ISSUE TITLE
Cannot pair MX Keys mini

### ISSUE THREAD

**Issue by dtto** [pwr-Solaar/Solaar#1960]
**Information**
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): solaar 1.1.8-21-g351e226
- Distribution: Debian GNU/Linux 11
- Kernel version (ex. `uname -srmo`): Linux 5.10.0-20-amd64 x86_64 GNU/Linux
- Output of `solaar show`:

<details>

```
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : 6A2591B2
    Firmware   : 12.11.B0032
    Bootloader : 04.16
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=100

  1: MX Master 3 Wireless Mouse
(SNIP) (the mouse works fine)

```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
- 1.1.8-21-g351e226
- _NAME: MX Master 3 Wireless Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer, adc_power_management]
  _battery: 4096
  _modelId: B02340820000
  _serial: CF771911
  _unitId: CF771911
  _wpid: '4082'
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 1, 196: 1}
  dpi: 1000
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}
  scroll-ratchet: 2
  smart-shift: 30
  thumb-scroll-invert: false
  thumb-scroll-mode: true
```
</details>

- Errors or warrnings from Solaar:

```
2023-01-05 21:47:33,493,493     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw0,12)>: present, 1 paired device. (1) pairing lock is open
2023-01-05 21:48:02,749,749     INFO [ReceiverListener:hidraw0] logitech_receiver.notifications: <UnifyingReceiver(/dev/hidraw0,12)>: pairing lock is closed
2023-01-05 21:48:02,749,749  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications: pairing error 1: device timeout
2023-01-05 21:48:02,749,749     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw0,12)>: present, 1 paired device. (1) pairing lock is closed
```

**Describe the bug**

I am unable to pair MX Keys Mini. I have an MX Keys working on Debian 11 on my other laptop with Solaar no problem but cannot get MX Keys Mini to pair. It just times out. The keyboard pairs fine with other devices. Solaar is working fine on this computer with the Logi MX Master 3 mouse. I was previously using the Solaar version that is in the Debian repos but upgraded in order to rule out that issue but still will not pair. Thank you for your work on this project. Let me know if I can provide other information.

**To Reproduce**
1. Go to Solaaar
2. Click on Pair new device
3. Times out

**Comment by dtto** [comment]
Thank you for your response. I can confirm that this keyboard is supposed to be compatible with Unifying devices, it is fully charged, and I am powering it on as instructed. The keyboard is in pairing mode according to the docs. I guess it may just not be compatible with Solaar?

**Comment by pfps** [comment]
Solaar is not involved in the pairing process, except to tell the receiver to start pairing.  So if the device is compatible with the receiver and the other conditions for pairing are met the device should pair with the receiver.

Devices that are compatible with Unifying receivers should have the Unifying logo on them.

Presumably this device is currently paired with some other receiver.  Try connecting that receiver to the computer that you are running Solaar on and see what Solaar shows about the receiver and the device via `solaar show`.

**Comment by dtto** [comment]
Well, after some back and forth with Logitech support, it turns out the MX Keys Mini cannot pair with the Unifying receiver, only with a bolt receiver. Apologies for the noise! Closing this issue.
