### ISSUE TITLE
Supported devices information

### ISSUE THREAD

**Issue by neeravmodi** [pwr-Solaar/Solaar#197]
Please update or sync the two supported devices pages:
- http://pwr.github.io/Solaar/devices.html
- https://github.com/pwr/Solaar/blob/master/docs/devices.md

For example, the M325 mouse entry has blank information in one, and has more detail in the other.  There are devices listed in only one page not the other.

Awesome project!  Works like a charm with K800 keyboard and M325 mouse.  Thank you!

**Comment by hyperair** [comment]
Hmm, would be nice to have smooth scrolling on the M325 though.

**Comment by olkrr** [comment]
Works with Keyboard/Mouse combo - Model K600, which isn't anywhere (i don't blame, it's a pretty rare model).

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Should have been fixed by #220
