### ISSUE TITLE
Solaar GUI doesn't seem to detect dongle after reboot

### ISSUE THREAD

**Issue by Str00pwafel** [pwr-Solaar/Solaar#1972]
The solaar GUI won't show the dongle information, only after I replug it works.
However, using the terminal with command solaar show, it does show all the information.

Solaar version is latest, 1.1.8.
I'm on latest up to date EndeavourOS with i3wm.

**Comment by pfps** [comment]
When does this happen?  Please provide the output of `solaar -ddd` when the problem occurs.

**Comment by Str00pwafel** [comment]
> When does this happen? Please provide the output of `solaar -ddd` when the problem occurs.

I've managed to figure out what triggered this.
I also have a logitech pro x wireless headset, and I had to turn this on atleast once.
After this, all is well and it works everytime now!

**Comment by pfps** [comment]
Yes, the headsets are slightly different from other devices.
