### ISSUE TITLE
MK295 and MK270 keyboards appear the same to Solaar

### ISSUE THREAD

**Issue by papinifrancesco** [pwr-Solaar/Solaar#1974]
Solaar version: 1.1.8-29-g2890966

I'd like the MK295 wireless keyboard to be recognized: at the moment shows up as a MK270

cat /sys/class/hidraw/hidraw6/device/uevent
```
DRIVER=logitech-hidpp-device
HID_ID=0003:0000046D:00004023
HID_NAME=Logitech Wireless Keyboard PID:4023
HID_PHYS=usb-0000:00:14.0-1/input1:1
HID_UNIQ=4023-00-00-00-00
MODALIAS=hid:b0003g0102v0000046Dp00004023
```

hidrd-convert -o spec /sys/class/hidraw/hidraw6/device/report_descriptor
```
Usage Page (Desktop),                   ; Generic desktop controls (01h)
Usage (Keyboard),                       ; Keyboard (06h, application collection)
Collection (Application),
    Report ID (1),
    Report Count (8),
    Report Size (1),
    Logical Minimum (0),
    Logical Maximum (1),
    Usage Page (Keyboard),              ; Keyboard/keypad (07h)
    Usage Minimum (KB Leftcontrol),     ; Keyboard left control (E0h, dynamic value)
    Usage Maximum (KB Right GUI),       ; Keyboard right GUI (E7h, dynamic value)
    Input (Variable),
    Report Count (6),
    Report Size (8),
    Logical Minimum (0),
    Logical Maximum (255),
    Usage Page (Keyboard),              ; Keyboard/keypad (07h)
    Usage Minimum (None),               ; No event (00h, selector)
    Usage Maximum (FFh),
    Input,
    Report ID (14),
    Usage Page (LED),                   ; LEDs (08h)
    Report Count (5),
    Report Size (1),
    Logical Minimum (0),
    Logical Maximum (1),
    Usage Minimum (01h),
    Usage Maximum (05h),
    Output (Variable),
    Report Count (1),
    Report Size (3),
    Output (Constant),
End Collection,
Usage Page (Consumer),                  ; Consumer (0Ch)
Usage (Consumer Control),               ; Consumer control (01h, application collection)
Collection (Application),
    Report ID (3),
    Report Size (16),
    Report Count (2),
    Logical Minimum (1),
    Logical Maximum (767),
    Usage Minimum (Consumer Control),   ; Consumer control (01h, application collection)
    Usage Maximum (02FFh),
    Input,
End Collection,
Usage Page (Desktop),                   ; Generic desktop controls (01h)
Usage (Sys Control),                    ; System control (80h, application collection)
Collection (Application),
    Report ID (4),
    Report Size (2),
    Report Count (1),
    Logical Minimum (1),
    Logical Maximum (3),
    Usage (Sys Sleep),                  ; System sleep (82h, one-shot control)
    Usage (Sys Power Down),             ; System power down (81h, one-shot control)
    Usage (Sys Wake Up),                ; System wake up (83h, one-shot control)
    Input (No Preferred, Null State),
    Report Size (6),
    Input (Constant, Variable),
End Collection,
Usage Page (FFBCh),                     ; FFBCh, vendor-defined
Usage (88h),
Collection (Application),
    Report ID (8),
    Usage Minimum (01h),
    Usage Maximum (FFh),
    Logical Minimum (1),
    Logical Maximum (255),
    Report Size (8),
    Report Count (1),
    Input,
End Collection,
Usage Page (FF00h),                     ; FF00h, vendor-defined
Usage (01h),
Collection (Application),
    Report ID (16),
    Report Size (8),
    Report Count (6),
    Logical Minimum (0),
    Logical Maximum (255),
    Usage (01h),
    Input,
    Usage (01h),
    Output,
End Collection,
Usage Page (FF00h),                     ; FF00h, vendor-defined
Usage (02h),
Collection (Application),
    Report ID (17),
    Report Size (8),
    Report Count (19),
    Logical Minimum (0),
    Logical Maximum (255),
    Usage (02h),
    Input,
    Usage (02h),
    Output,
End Collection,
Usage Page (FF00h),                     ; FF00h, vendor-defined
Usage (04h),
Collection (Application),
    Report ID (32),
    Report Size (8),
    Report Count (14),
    Logical Minimum (0),
    Logical Maximum (255),
    Usage (41h),
    Input,
    Usage (41h),
    Output,
    Report ID (33),
    Report Count (31),
    Logical Minimum (0),
    Logical Maximum (255),
    Usage (42h),
    Input,
    Usage (42h),
    Output,
End Collection
```

**Comment by pfps** [comment]
Please provide output of `solaar show` with the keyboard active.

**Comment by papinifrancesco** [comment]
solaar version 1.1.8-29-g2890966

Nano Receiver
  Device path  : /dev/hidraw5
  USB id       : 046d:C534
  Serial       : None
    Firmware   : 29.01.B0016
  Has 2 paired device(s) out of a maximum of 2.
  Has 15 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)

  1: Wireless Keyboard MK270
     Device path  : /dev/hidraw6
     WPID         : 4023
     Codename     : MK270
     Kind         : keyboard
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: 0E27E6CF
     Model ID:      000000000000
     Unit ID:       00000000
          Firmware: RQK 49.00.B0029
     Supports 18 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V0     
            Firmware: Firmware RQK 49.00.B0029 4023
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         3: DEVICE NAME            {0005} V0     
            Name: Wireless Keyboard  
            Kind: keyboard
         4: BATTERY STATUS         {1000} V0     
            Battery: 30%, discharging, next level 5%.
         5: REPROG CONTROLS        {1B00} V0     
         6: WIRELESS DEVICE STATUS {1D4B} V0     
         7: FN INVERSION           {40A0} V0     
            Swap Fx function (saved): False
            Swap Fx function        : False
         8: ENCRYPTION             {4100} V0     
         9: KEYBOARD LAYOUT        {4520} V0     
        10: unknown:1810           {1810} V0    internal, hidden 
        11: unknown:1830           {1830} V0    internal, hidden 
        12: unknown:1890           {1890} V0    internal, hidden 
        13: unknown:18A0           {18A0} V0    internal, hidden 
        14: unknown:18B0           {18B0} V0    internal, hidden 
        15: unknown:1DF3           {1DF3} V0    internal, hidden 
        16: unknown:1E00           {1E00} V0    hidden 
        17: unknown:1868           {1868} V0    internal, hidden 
     Battery: 30%, discharging, next level 5%.

**Comment by pfps** [comment]
Some Logitech devices are distinguishable from others only by examining their physical appearance.  This appears to be the case for the MK270 and the MK295 keyboards.  The MK270 is older so this is what is used inside Solaar as the name assigned to keyboards with ID 4023.  

Solaar could be changed to remove the MK270, but that does not appear to be a good idea.
