### ISSUE TITLE
Mouse MX 3S not working back/forward thumb buttons

### ISSUE THREAD

**Issue by macbeto** [pwr-Solaar/Solaar#1976]
I just bought a mouse Logi MX Master 3S working with Linux MInt and with Solaar installed.
The connection method is via USB Bolt, which is recognized by Solaar, but my back/forward buttons are not working, they do nothing. Although the thumb wheel is working ok.
Is that normal? thumb buttons are not suppose to work with Solaar?
Thank you

**Comment by pfps** [comment]
It's not Solaar that is interpreting the buttons, but Linux.  So somehow there is nothing that is listening to the mouse buttons that interprets the buttons the way you want them interpreted.

**Comment by pfps** [comment]
Is there anything more to do on this issue?

**Comment by macbeto** [comment]
Hi pfps:
Probably you are right, is not a solaar thing, so in case you need to close the issue feel free to do it.
But is totally strange that with Linux Mint 20.1 in both my computers, with two differents Logitech MX Master 3S it doesn't detect those buttons.
Doing a xev | grep button doesn't detect the click in those buttons, although it detect the rest of them, scrolling included.
I have installed every single driver, update, kernel update, even logiops software and never got the xev command any activity with those buttons.

**Comment by pfps** [comment]
What might be going wrong is that the buttons are reprogrammed or diverted.   The output of `solaar show` will show how these buttons are set up.  Providing that output might lead the way to a resolution.

**Comment by macbeto** [comment]
Hi Peter, 
This is the result of the command solaar show:
`solaar version 1.1.8

Receptor Bolt
  Device path  : /dev/hidraw3
  USB id       : 046d:C548
  Serial       : 33304243394533453737463944434533
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 2=26

  2: MX Master 3S
     Device path  : None
     WPID         : B034
     Codename     : MX Master 3S
     Kind         : mouse
     Protocol     : HID++ 4.5
     Serial number: 7B3AC42D
     Model ID:      B03400000000
     Unit ID:       7B3AC42D
        Bootloader: BL1 69.00.B0003
          Firmware: RBM 22.00.B0003
             Other: 
     The power switch is located on the (unknown).
     Supports 36 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V4     
            Firmware: Bootloader BL1 69.00.B0003 B03438FCA4E6
            Firmware: Firmware RBM 22.00.B0003 B03438FCA4E6
            Firmware: Other   
            Unit ID: 7B3AC42D  Model ID: B03400000000  Transport IDs: {'btleid': 'B034'}
         3: DEVICE NAME            {0005} V0     
            Name: MX Master 3S
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
         6: CRYPTO ID              {0021} V1     
         7: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Master 3S
         8: UNIFIED BATTERY        {1004} V3     
            Battery: 95%, discharging.
         9: REPROG CONTROLS V4     {1B04} V5     
            Acciones de Tecla/Botón (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Acciones de Tecla/Botón        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Desvio de Tecla/Botón (saved): {Middle Button:Normal, Back Button:Normal, Forward Button:Normal, Mouse Gesture Button:Normal, Smart Shift:Normal}
            Desvio de Tecla/Botón        : {Middle Button:Normal, Back Button:Normal, Forward Button:Normal, Mouse Gesture Button:Normal, Smart Shift:Normal}
        10: CHANGE HOST            {1814} V1     
            Cambiar Host        : 1:lixbeto
        11: HOSTS INFO             {1815} V2     
            Host 0 (paired): lixbeto
            Host 1 (unpaired): 
            Host 2 (unpaired): 
        12: XY STATS               {2250} V1     
        13: ADJUSTABLE DPI         {2201} V2     
            Sensibilidad (PPP) (saved): 1000
            Sensibilidad (PPP)        : 1000
        14: SMART SHIFT            {2110} V0     
            Rueda de desplazamiento con trinquete (saved): Giro libre
            Rueda de desplazamiento con trinquete        : Giro libre
            Rueda de desplazamiento Velocidad de trinquete (saved): 1
            Rueda de desplazamiento Velocidad de trinquete        : 1
        15: HIRES WHEEL            {2121} V1     
            Multiplier: 15
            Has invert: Normal wheel motion
            Has ratchet switch: Free wheel mode
            Low resolution mode
            HID notification
            Dirección Rueda Desplazamiento (saved): False
            Dirección Rueda Desplazamiento        : False
            Resolución Rueda Desplazamiento (saved): False
            Resolución Rueda Desplazamiento        : False
            Desvio Rueda Desplazamiento (saved): False
            Desvio Rueda Desplazamiento        : False
        16: THUMB WHEEL            {2150} V0     
            Dirección de la Rueda del Pulgar (saved): False
            Dirección de la Rueda del Pulgar        : True
            Desvío de la Rueda del Pulgar (saved): False
            Desvío de la Rueda del Pulgar        : False
        17: WHEEL STATS            {2251} V0     
        18: DFUCONTROL             {00C3} V0     
        19: DEVICE RESET           {1802} V0    internal, hidden, unknown:000010 
        20: unknown:1803           {1803} V0    internal, hidden, unknown:000010 
        21: CONFIG DEVICE PROPS    {1806} V8    internal, hidden, unknown:000010 
        22: unknown:1816           {1816} V0    internal, hidden, unknown:000010 
        23: OOBSTATE               {1805} V0    internal, hidden 
        24: unknown:1830           {1830} V0    internal, hidden, unknown:000010 
        25: unknown:1891           {1891} V7    internal, hidden, unknown:000008 
        26: unknown:18A1           {18A1} V0    internal, hidden, unknown:000010 
        27: unknown:1E00           {1E00} V0    hidden 
        28: unknown:1E02           {1E02} V0    internal, hidden 
        29: unknown:1602           {1602} V0     
        30: unknown:1EB0           {1EB0} V0    internal, hidden, unknown:000010 
        31: unknown:1861           {1861} V1    internal, hidden, unknown:000010 
        32: unknown:9300           {9300} V0    internal, hidden, unknown:000010 
        33: unknown:9001           {9001} V0    internal, hidden, unknown:000010 
        34: unknown:1E22           {1E22} V0    internal, hidden, unknown:000010 
        35: unknown:9205           {9205} V0    internal, hidden, unknown:000010 
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Mouse Gesture Button      , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:3, group mask:empty
             reporting: default
     Battery: 95%, discharging.

`

**Comment by pfps** [comment]
Solaar is reporting that the back and forward buttons are in their normal state so it looks as if Solaar is not involved.  To check for sure you could quit out of Solaar and then turn the  mouse off and on again.   That will undo any changes made to the mouse.

**Comment by pfps** [comment]
Another thing you can do is look at the raw input from the device using `sudo evtest /dev/input/eventXX`.  You can find XX by `ls /dev/input/event*` with the mouse turned off and then on.   

When I did this with my MX Master 3 I see that the two buttons produce 
```
Event: time 1675525738.676835, -------------- SYN_REPORT ------------
Event: time 1675525739.981809, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1675525739.981809, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 1
Event: time 1675525739.981809, -------------- SYN_REPORT ------------
Event: time 1675525740.154108, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1675525740.154108, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 0
Event: time 1675525740.154108, -------------- SYN_REPORT ------------
Event: time 1675525740.919526, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1675525740.919526, type 1 (EV_KEY), code 275 (BTN_SIDE), value 1
Event: time 1675525740.919526, -------------- SYN_REPORT ------------
Event: time 1675525741.114016, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1675525741.114016, type 1 (EV_KEY), code 275 (BTN_SIDE), value 0
Event: time 1675525741.114016, -------------- SYN_REPORT ------------
```
Something must be turning these events into forward and back on my machine (running XFCE under Fedora).  Maybe you have an older driver that does not do this?

I used some information from https://unix.stackexchange.com/questions/5218/how-to-debug-the-input-from-an-input-device-dev-input-event to get to the evtest command.

**Comment by macbeto** [comment]
Indeed, it looks like Solaar detects the  buttons, but when you press them nothing happens.
Without Solaar the behavior is pretty much the same, nothing happens when you press them.
The evtest command detect the key pressed, maybe those buttons are not mapped to some action?:

`Event: time 1675526917.381889, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1675526917.381889, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 1
Event: time 1675526917.381889, -------------- SYN_REPORT ------------
Event: time 1675526917.449050, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90006
Event: time 1675526917.449050, type 1 (EV_KEY), code 277 (BTN_FORWARD), value 1
Event: time 1675526917.449050, -------------- SYN_REPORT ------------
Event: time 1675526917.493943, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90006
Event: time 1675526917.493943, type 1 (EV_KEY), code 277 (BTN_FORWARD), value 0
Event: time 1675526917.493943, -------------- SYN_REPORT ------------
Event: time 1675526917.584035, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1675526917.584035, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 0
Event: time 1675526917.584035, -------------- SYN_REPORT ------------
Event: time 1675526918.237067, type 2 (EV_REL), code 0 (REL_X), value -1
Event: time 1675526918.237067, -------------- SYN_REPORT ------------
Event: time 1675526918.258867, type 2 (EV_REL), code 1 (REL_Y), value 1
Event: time 1675526918.258867, -------------- SYN_REPORT ------------
Event: time 1675526919.818997, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1675526919.818997, type 1 (EV_KEY), code 275 (BTN_SIDE), value 1
Event: time 1675526919.818997, -------------- SYN_REPORT ------------
Event: time 1675526919.984120, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1675526919.984120, type 1 (EV_KEY), code 275 (BTN_SIDE), value 0
Event: time 1675526919.984120, -------------- SYN_REPORT ------------
`

**Comment by macbeto** [comment]
Indeed, it looks like Solaar detects the buttons, but when you press them nothing happens.
Without Solaar the behavior is pretty much the same, nothing happens when you press them.
The evtest command detect the key pressed, maybe those buttons are not mapped to some action?:
`Event: time 1675526917.381889, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 1
Event: time 1675526917.381889, -------------- SYN_REPORT ------------
Event: time 1675526917.449050, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90006
Event: time 1675526917.449050, type 1 (EV_KEY), code 277 (BTN_FORWARD), value 1
Event: time 1675526917.449050, -------------- SYN_REPORT ------------
Event: time 1675526917.493943, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90006
Event: time 1675526917.493943, type 1 (EV_KEY), code 277 (BTN_FORWARD), value 0
Event: time 1675526917.493943, -------------- SYN_REPORT ------------
Event: time 1675526917.584035, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1675526917.584035, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 0
Event: time 1675526917.584035, -------------- SYN_REPORT ------------
Event: time 1675526918.237067, type 2 (EV_REL), code 0 (REL_X), value -1
Event: time 1675526918.237067, -------------- SYN_REPORT ------------
Event: time 1675526918.258867, type 2 (EV_REL), code 1 (REL_Y), value 1
Event: time 1675526918.258867, -------------- SYN_REPORT ------------
Event: time 1675526919.818997, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1675526919.818997, type 1 (EV_KEY), code 275 (BTN_SIDE), value 1
Event: time 1675526919.818997, -------------- SYN_REPORT ------------
Event: time 1675526919.984120, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1675526919.984120, type 1 (EV_KEY), code 275 (BTN_SIDE), value 0
Event: time 1675526919.984120, -------------- SYN_REPORT ------------`

**Comment by macbeto** [comment]
Indeed, it looks like Solaar detects the buttons, but when you press them nothing happens.
Without Solaar the behavior is pretty much the same, nothing happens when you press them.
The evtest command detect the key pressed, maybe those buttons are not mapped to some action?:

> Event: time 1675526917.381889, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 1
Event: time 1675526917.381889, -------------- SYN_REPORT ------------
Event: time 1675526917.449050, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90006
Event: time 1675526917.449050, type 1 (EV_KEY), code 277 (BTN_FORWARD), value 1
Event: time 1675526917.449050, -------------- SYN_REPORT ------------
Event: time 1675526917.493943, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90006
Event: time 1675526917.493943, type 1 (EV_KEY), code 277 (BTN_FORWARD), value 0
Event: time 1675526917.493943, -------------- SYN_REPORT ------------
Event: time 1675526917.584035, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1675526917.584035, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 0
Event: time 1675526917.584035, -------------- SYN_REPORT ------------
Event: time 1675526918.237067, type 2 (EV_REL), code 0 (REL_X), value -1
Event: time 1675526918.237067, -------------- SYN_REPORT ------------
Event: time 1675526918.258867, type 2 (EV_REL), code 1 (REL_Y), value 1
Event: time 1675526918.258867, -------------- SYN_REPORT ------------
Event: time 1675526919.818997, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1675526919.818997, type 1 (EV_KEY), code 275 (BTN_SIDE), value 1
Event: time 1675526919.818997, -------------- SYN_REPORT ------------
Event: time 1675526919.984120, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1675526919.984120, type 1 (EV_KEY), code 275 (BTN_SIDE), value 0
Event: time 1675526919.984120, -------------- SYN_REPORT ------------

**Comment by pfps** [comment]
Solaar isn't involved in processing these events at all.   The events come from the mouse, are potentially processed by a device-specific driver, and then sent for further processing.   As hinted at in the Stack Exchange thread you could try seeing whether xinput picks up the events.

But it certainly seems that some Linux processing is not happening to turn these raw events into forward and back mouse events.

**Comment by macbeto** [comment]
Yes, I assume Solaar has nothing to be with it.
I was following this link trying to remap the key press (https://askubuntu.com/questions/1145057/remapping-mouse-buttons-to-keyboard-keys), but with no luck so far.
Also I am researching with xinput. My id 11 is:
   ↳ Logitech USB Receiver Mouse             	id=11	[slave  pointer  (2)]
When I use xinput test 11 I get  this when press the backward/forward button, respectively:
button press   9 
button press   8 
And using xinput test-xi2 11:

> EVENT type 4 (ButtonPress)
    device: 11 (11)
    detail: 9
    flags: 
    root: 1610.85/594.96
    event: 150.85/168.96
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x7c6 event 0x7e00001 child 0x0
EVENT type 16 (RawButtonRelease)
    device: 11 (11)
    detail: 9
    flags: 
    valuators:

EVENT type 5 (ButtonRelease)
    device: 11 (11)
    detail: 9
    flags: 
    root: 1610.85/594.96
    event: 150.85/168.96
    buttons: 9
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x7c6 event 0x7e00001 child 0x0

> EVENT type 4 (ButtonPress)
    device: 11 (11)
    detail: 8
    flags: 
    root: 1546.50/570.68
    event: 114.50/113.68
    buttons:
    modifiers: locked 0 latched 0 base 0 effective: 0
    group: locked 0 latched 0 base 0 effective: 0
    valuators:
    windows: root 0x7c6 event 0x8000001 child 0x0

So the events when I press the buttons are detected, but they do nothing, I will try to map those events.
Thank you very much for all your help, Peter.
Regards

**Comment by macbeto** [comment]
Furthermore I installed input-remapper and I could remap the button EXTRA, which is one of the two side buttons, as BTN_Left and it works fine.
So the problem is basically the OS doesn't allow to use BTN_BACK and BTN_FORWARD.
X-Files

**Comment by macbeto** [comment]
I close the issue as it is not a Solaar thing.
