### ISSUE TITLE
Estimate time left for discharging/charging in tray menu and main window.

### ISSUE THREAD

**Issue by Reenuip** [pwr-Solaar/Solaar#1987]
I'd love to see an estimated time left on the battery. Ideally, I'd also like to see an ETA for charging as well, but that part isn't nearly as important.
Perhaps these could be calculated from the voltage table you have or just by observing the drain/charge rate (% over time).

**Comment by pfps** [comment]
For some batteries this might be possible, but the charge remaining estimate is already very rough so the battery life estimate is only going to be a guess.  These batteries are very different from the batteries in a laptop.  As well, battery life depends on the energy used by the device, which can very widely.

All in all, not worth the effort unless someone wants to do some investigation.

**Comment by Reenuip** [comment]
Honestly, I'd be happy with a crude estimate based on the last hour or so of use. Could just be an experimental option a user could toggle on either in the menu or by tweaking the config.

**Comment by pfps** [comment]
Estimating from the last hour of use is probably not possible.   The battery voltage does not change all that frequently.   Estimation will have to be from historical data, as is done for laptop batteries, and even with good batteries and lots of data the estimates for laptops can be off by a factor of 2 or 3 even with similar energy use.

**Comment by prahal** [comment]
I believe the battery discharge depends on the device model. And for one the LX7 mouse is supposed to take 8 months of constant usage to deplete its batteries. So an estimate over an hour will not notice a change in the voltage. Mind that Logitech mice have standby methods to save power, so the estimate will drift fast.
Also, an estimate requires to be able to sample the voltage drop over time. On a sample range over a month, this requires a mean to persist the values. Also, I do not know if you are interested to get an estimate of the remaining battery only after a month or two of usage.

**Comment by pfps** [comment]
Closing as this doesn't seem feasible.
