### ISSUE TITLE
Mice connected via wire do not need Wireless link indicator

### ISSUE THREAD

**Issue by vpelcak** [pwr-Solaar/Solaar#1993]
**Information**
The mouse connected via wire has Wireless Link indicator. See screenshot. 

![obrazek](https://user-images.githubusercontent.com/1659215/218970379-02321f1f-bea0-4cbc-aa37-cd06637c10cf.png)

Since they are connected via wire, Wireless Link is not used.

It should be corrected.

**Comment by pfps** [comment]
Fixed by PR #1991
