### ISSUE TITLE
Originating Device Condition Rule

### ISSUE THREAD

**Issue by cbeley** [pwr-Solaar/Solaar#1995]
**Information**

Currently, there appears to be no way to write a rule that applies only to a specific originating device. In the case of the Pop Keyboard and mouse, there is a conflict for diversion of the `Open Emoji Panel (0108)` button, which emits the same code when pressed on both the keyboard and the mouse.

It'd be nice to have the button on the mouse perform a different action than on the keyboard.

**Describe the solution you'd like**
I'm assuming there is no way to change the code that is emitted on the mouse. However, if it were possible to write a rule that was something like `when originating device is "pop mouse" and key is `Open Emoji Panel (0108)` (pressed)`, I think that would do the trick.

**Describe alternatives you've considered**
I did play a bit with trying to set the button to be the gesture button, then writing a divert rule for that. I assume this doesn't work because all the gesture button diversion does is try to divert "`Open Emoji Panel (0108)` (pressed)` to `mouse gesture button`.

**Additional context**

Other than for the pop mouse and keyboard, I'm not sure how much usefulness this feature would have otherwise. It's purely a consequence of Logitech deciding to use identical codes on both the mouse and keyboard.

Other than this issue, the mouse and keyboard, as well as diversion of all the special keys, works perfectly for me.

**Comment by cbeley** [comment]
Looking at https://github.com/pwr-Solaar/Solaar/blob/master/lib/logitech_receiver/diversion.py, it seems like the general approach to this would be to create a new rule like https://github.com/pwr-Solaar/Solaar/blob/master/lib/logitech_receiver/diversion.py#L949, but with `evaluate` testing the passed in device (https://github.com/pwr-Solaar/Solaar/blob/master/lib/logitech_receiver/device.py) for whether or not it is the desired device id.

The UI portion I imagine would be very similar to how active is: https://github.com/pwr-Solaar/Solaar/blob/master/lib/solaar/ui/diversion_rules.py#L2222, since we'll also need to enumerate available devices to show to the user.

I'm a bit rusty with Python, but may give this a shot if there is a lack of interest.

**Comment by pfps** [comment]
Yes.  I'm most of the way through doing the non-GUI part of this.

**Comment by pfps** [comment]
PR #1996 adds a Device condition.  No GUI support yet so you have to edit `/.config/solaar/rules.yaml`.  Here is an example rule with a Device condition:

```
---
- Device: 198E3EB8
- Execute: [notify-send, devicex]
...
```

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1996, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1996/head:pull_1996
git checkout pull_1996
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1996
git fetch origin pull/1996/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
PR #1996 now allows Device condition editing in the rules editor.

**Comment by cbeley** [comment]
I'll need to try it out with the rule editor, but I confirmed it works. Here's an example config of the mouse and keyboard keys operating indepednently.

```
%YAML 1.3
---
- Device: EE6553E9
- And:
    - Key: [Open Emoji Panel, pressed]
- KeyPress:
    - Super_L
    - click
---
- Key: [Snipping Tool, pressed]
- KeyPress:
    - Print
    - click
---
- Key: [Emoji Smiley Heart Eyes, pressed]
- KeyPress:
    - [Control_L, Shift_L, u]
    - click
- KeyPress:
    - "1"
    - click
- KeyPress:
    - f
    - click
- KeyPress:
    - "6"
    - click
- KeyPress:
    - "0"
    - click
- KeyPress:
    - d
    - click
- KeyPress:
    - KP_Enter
    - click
---
- Key: [Emoji Crying Face, pressed]
- KeyPress:
    - [Control_L, Shift_L, u]
    - click
- KeyPress:
    - "1"
    - click
- KeyPress:
    - f
    - click
- KeyPress:
    - "6"
    - click
- KeyPress:
    - "2"
    - click
- KeyPress:
    - d
    - click
- KeyPress:
    - KP_Enter
    - click
---
- Key: [Emoji Smiley, pressed]
- KeyPress:
    - [Control_L, Shift_L, u]
    - click
- KeyPress:
    - "1"
    - click
- KeyPress:
    - f
    - click
- KeyPress:
    - "6"
    - click
- KeyPress:
    - "0"
    - click
- KeyPress:
    - "0"
    - click
- KeyPress:
    - KP_Enter
    - click
---
- Key: [Emoji Smilie With Tears, pressed]
- KeyPress:
    - [Control_L, Shift_L, u]
    - click
- KeyPress:
    - "1"
    - click
- KeyPress:
    - f
    - click
- KeyPress:
    - "6"
    - click
- KeyPress:
    - "0"
    - click
- KeyPress:
    - "2"
    - click
- KeyPress:
    - KP_Enter
    - click
---
- Key: [Open Emoji Panel, pressed]
- KeyPress:
    - [Control_L, Shift_L, u]
    - click
- KeyPress:
    - "1"
    - click
- KeyPress:
    - f
    - click
- KeyPress:
    - "4"
    - click
- KeyPress:
    - "4"
    - click
- KeyPress:
    - d
    - click
- KeyPress:
    - KP_Enter
    - click
```

**Comment by cbeley** [comment]
Rule editor seems to working for me as expected with the above config. The only thing that is a little odd is I'm not sure if it makes sense to have "originating device" in the device selection for this particular rule. It'd effectively be a noop?

**Comment by pfps** [comment]
Yeah, that's not very useful.  Its presence is at least partly because almost all of the editing code is shared with the Active condition.  It's not wrong, of course, and separating the code is not trivial so I'm not going to remove it, at least for now.

**Comment by linusrg1** [comment]
btw @cbeley I curious what each of the key presses in the rules are doing just so i can configure the keys to different emojis if I would like.

**Comment by cbeley** [comment]
> btw @cbeley I curious what each of the key presses in the rules are doing just so i can configure the keys to different emojis if I would like.

Ctrl-shift-u allows you to type the hex for a Unicode character.

**Comment by linusrg1** [comment]
ok

> > btw @cbeley I curious what each of the key presses in the rules are doing just so i can configure the keys to different emojis if I would like.
> 
> Ctrl-shift-u allows you to type the hex for a Unicode character.

ok thats cool! is there a way to look up the hexes by chance? Im sorry iv'e never needed to look them up before.

**Comment by Gadg8eer** [comment]
I have [this version of Logi POP Keys](https://media.karousell.com/media/photos/products/2023/8/11/logitech_pop_keys_mechanical_w_1691728791_32855d9c_progressive) and because the keys feature different emojis, they must be giving different default input data because none of them work for me when I define the rules as specified above to solve the problem.
