### ISSUE TITLE
POP Mouse - Open Panel Emoji

### ISSUE THREAD

**Issue by RastaDill** [pwr-Solaar/Solaar#1997]
Hello. I have question about button "Open Emoji Panel" on my mice.
This button detect in xev.
This button apply setting from solaar if i change Actions (left, right, middle).
But if i set action Open Emoji Panel - nothing happens.

What called in system when click Open Emoji Panel?
I try change behaviour via Rule, but nothing changes. No one rule not working. Maybe I'm doing something wrong?
![image](https://user-images.githubusercontent.com/12989870/219867297-0e116742-d6a0-4a8c-8835-b5f8c439d5d7.png)

**Comment by pfps** [comment]
Solaar rules only work on notifications from devices.  Pressing keys only generates notifications if the key is diverted using the Key/Button Diversion setting in Solaar.   Keys and buttons that can be diverted will generate notifications when diverted no matter what they did before.  Make sure that the rule uses the same key that is diverted.

More help will require the information needed when opening bug issues.

**Comment by RastaDill** [comment]
Very thanks for you helps! I didn't realize at first that in order to reassign a key, must first set Diversion. Everything is working now. :+1:
