### ISSUE TITLE
Solaar exits with RC 1 when terminated

### ISSUE THREAD

**Issue by Vladimir-csp** [pwr-Solaar/Solaar#2001]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): solaar 1.1.8+dfsg-2
- Distribution: Debian testing
- Kernel version (ex. `uname -srmo`): `Linux 6.1.0-3-amd64 x86_64 GNU/Linux`
- Output of `solaar show`: 

<details>

```

```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
CONTENTS HERE
```
</details>

- Errors or warrnings from Solaar:

**Describe the bug**
When terminated, solaar exits with RC 1. This results in a failed unit if systemd is managing XDG autostart. No log warnings or stderr messages produced.

**To Reproduce**
1. run `solaar ; echo $?`
2. run `killall solaar`
3. see rc 1 printed

Workaround:
```
cat << EOF > ~/.config/systemd/user/app-solaar@autostart.service.d/exit-tweak.conf 
[Service]
SuccessExitStatus=0 1
EOF
systemctl --user daemon-reload
```

**Comment by pfps** [comment]
Seems reasonable.  PR #2003 should fix this problem.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #2003, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/2003/head:pull_2003
git checkout pull_2003
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_2003
git fetch origin pull/2003/head
git reset --hard FETCH_HEAD
```
