### ISSUE TITLE
Mx Anywere 3 constantly resetting settings on every reconnect. 

### ISSUE THREAD

**Issue by cardcraft** [pwr-Solaar/Solaar#2009]
When using my mouse every time I reconnect it the middle mouse function resets to its defaults.

There are no errors when running in a console.

This occurs using bluetooth and the unifying receiver.

**Comment by pfps** [comment]
From what you provide this could easily be normal behaviour for your mouse.   Most Logitech devices forget changes when they go into power-saving mode.  From https://github.com/pwr-Solaar/Solaar

> Solaar keeps track of most of these settings on a per-computer basis, because devices forget most settings when powered down, and the GUI application restores them whenever a device connects.

For most changes, having them persist requires running the Solaar GUI or having some other method of applying the changes whenever the device comes out of  a power-saving mode.

**Comment by cardcraft** [comment]
I did figure that the mouse wouldn't have any storage. This happens when I
change the connection even when the app is still enabled

**Comment by pfps** [comment]
To figure out what is going wrong you need to provide the information requested for a bug report.  Provide output of `solaar show` when the device is behaving correctly, when it is not, and after you use Solaar to set its behaviour back to what you want.   Also say what you did to restore correct behaviour.

**Comment by pfps** [comment]
Are you still interested in pursuing this problem?

**Comment by pfps** [comment]
Closing due to no response from submitter.
