### ISSUE TITLE
Anywhere 3, smart shift button action rise multiple time

### ISSUE THREAD

**Issue by Kowiste** [pwr-Solaar/Solaar#2019]
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository):solaar 1.1.1
- Distribution: Ubuntu 22.04.2 LTS
- Kernel version (ex. `uname -srmo`): Linux 5.19.0-35-generic x86_64 GNU/Linux
- Output of `solaar show`:

<details>

```
  1: MX Anywhere 3
     Device path  : /dev/hidraw3
     USB id       : 046d:B025
     Codename     : MX Anywhere 3
     Kind         : mouse
     Protocol     : HID++ 4.5
     Serial number: ?
     Model ID:      B02540900000
     Unit ID:       42C4C035
        Bootloader: BL1 13.01.B0015
          Firmware: MPM 24.01.B0015
             Other: 
     Supports 31 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BL1 13.01.B0015 0000AACD8D78
            Firmware: Firmware MPM 24.01.B0015 B025AACD8D78
            Firmware: Other   
            Unit ID: 42C4C035  Model ID: B02540900000  Transport IDs: {'btleid': 'B025', 'wpid': '4090'}
         3: DEVICE NAME            {0005}   
            Name: MX Anywhere 3
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: CRYPTO ID              {0021}   
         7: DEVICE FRIENDLY NAME   {0007}   
            Friendly Name: MX Anywhere 3
         8: UNIFIED BATTERY        {1004}   
         9: REPROG CONTROLS V4     {1B04}   
            Key/Button Actions (saved): {'196': 196, '80': 80, '81': 81, '82': 82, '83': 83, '86': 86}
            Key/Button Actions        : {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '196': 196}
            Key/Button Diversion (saved): {'196': 1, '82': 1, '83': 0, '86': 0}
            Key/Button Diversion        : {'82': 1, '83': 0, '86': 0, '196': 1}
        10: CHANGE HOST            {1814}   
            Change Host        : 3:thinkpad-e14-gen-2
        11: XY STATS               {2250}   
        12: ADJUSTABLE DPI         {2201}   
            Sensitivity (DPI) (saved): 1000
            Sensitivity (DPI)        : 1000
        13: SMART SHIFT ENHANCED   {2111}   
            Scroll Wheel Rachet (saved): 10
            Scroll Wheel Rachet        : 10
        14: HIRES WHEEL            {2121}   
            Multiplier: 15
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            Low resolution mode
            HID notification
            Scroll Wheel Direction (saved): False
            Scroll Wheel Direction        : False
            Scroll Wheel Resolution (saved): False
            Scroll Wheel Resolution        : False
        15: WHEEL STATS            {2251}   
        16: DFUCONTROL SIGNED      {00C2}   
        17: DEVICE RESET           {1802}   internal, hidden
        18: unknown:1803           {1803}   internal, hidden
        19: CONFIG DEVICE PROPS    {1806}   internal, hidden
        20: unknown:1812           {1812}   internal, hidden
        21: OOBSTATE               {1805}   internal, hidden
        22: unknown:1830           {1830}   internal, hidden
        23: unknown:18A1           {18A1}   internal, hidden
        24: unknown:1E00           {1E00}   hidden
        25: unknown:1EB0           {1EB0}   internal, hidden
        26: unknown:1861           {1861}   internal, hidden
        27: unknown:9300           {9300}   internal, hidden
        28: unknown:9001           {9001}   internal, hidden
        29: unknown:1E22           {1E22}   internal, hidden
        30: unknown:9205           {9205}   internal, hidden
     Has 7 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: diverted
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, analytics key events, unknown:000800, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, analytics key events, unknown:000800, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: diverted
         6: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:3, group mask:empty
             reporting: default
     Battery: 50%, discharging.

```
</details>

**Describe the bug**

I just install solaar to modify the behavior of my logitech anywhere 3.

I want to modify the smart shift button to use it as middle button:

1. key/button diversion: i select the smart shift and diverted.
2. Went to the rule editor: Create a new user defined rule , with action mouse click middle and count 1.

The problem is when i press the button over a link open 2 new tabs instead of only one, if I change the count to 2 its open 4 tabs.

How can I make it work?

**Comment by pfps** [comment]
Please use the bug template, which asks for the output of `solaar show` and the contents of your rule file.

**Comment by Kowiste** [comment]
> Please use the bug template, which asks for the output of `solaar show` and the contents of your rule file.

Sorry I just updated

**Comment by pfps** [comment]
The setup for your mouse looks fine, but what rules do you have?  That is the contents of ~/.config/solaar/rules.yaml

Also helpful would be the output of `solaar -ddd` as you press the smart shift button.

**Comment by Kowiste** [comment]
this is my rule:

%YAML 1.3
---
- MouseClick: [middle, 1]
...

and the output of solaar -ddd when i press the button is this:


15:58:01,517    DEBUG [ReceiverListener:hidraw3] logitech_receiver.base: (18) => r[11 FF 0900 00C40000000000000000000000000000]
15:58:01,517    DEBUG [ReceiverListener:hidraw3] logitech_receiver.notifications: <Device(255,B025,MX Anywhere 3,?)>: notification for feature REPROG CONTROLS V4, report 0, data 00C40000000000000000000000000000
15:58:01,517    DEBUG [ReceiverListener:hidraw3] logitech_receiver.notifications: <Device(255,B025,MX Anywhere 3,?)>: diverted controls pressed: 0xc4, 0x0, 0x0, 0x0
15:58:01,517     INFO [ReceiverListener:hidraw3] logitech_receiver.diversion: MouseClick action: 1 middle
u press the smart shift button.15:58:01,599    DEBUG [ReceiverListener:hidraw3] logitech_receiver.base: (18) => r[11 FF 0900 00000000000000000000000000000000]
15:58:01,600    DEBUG [ReceiverListener:hidraw3] logitech_receiver.notifications: <Device(255,B025,MX Anywhere 3,?)>: notification for feature REPROG CONTROLS V4, report 0, data 00000000000000000000000000000000
15:58:01,600    DEBUG [ReceiverListener:hidraw3] logitech_receiver.notifications: <Device(255,B025,MX Anywhere 3,?)>: diverted controls pressed: 0x0, 0x0, 0x0, 0x0
15:58:01,600     INFO [ReceiverListener:hidraw3] logitech_receiver.diversion: MouseClick action: 1 middle
u press the smart shift button.

**Comment by pfps** [comment]
The problem is that this rule action will successfully execute on every notification,  including device connection and disconnection but also including both pressing and releasing any diverted key.   You need a condition to restrict when the rule action will be executed, i.e., a Key condition for the smart shift button when either the button goes down or goes up.

**Comment by Kowiste** [comment]
Oh, ok thank you now is working fine, I tried to put the condition but I was searching for middle button, no for smart shift button.
