### ISSUE TITLE
assign keyboard keys to the mouse click

### ISSUE THREAD

**Issue by raknerak** [pwr-Solaar/Solaar#2026]
Hello;

I entered user-defined rules for my logitech anywhere 3 mouse for assigning copy/paste function to the back and forward buttons. Unfortunately, it does not work. I am copying snapshot of the output. Am I doing something wrong?

![Screenshot from 2023-04-01 14-19-03](https://user-images.githubusercontent.com/7880734/229286074-16b6fca4-23b0-4a29-980d-4cc867b91338.png)

**Comment by pfps** [comment]
You need to read https://pwr-solaar.github.io/Solaar/rules, particularly the part about how Solaar rules are triggered.  You also need to read the description of the MouseClick action.

**Comment by pfps** [comment]
Closing due to no response from submitter.
