### ISSUE TITLE
the smooth scrolling function does not work

### ISSUE THREAD

**Issue by pooh2pooh** [pwr-Solaar/Solaar#2033]
**Information**

- Solaar version: 1.1.8
- Distribution: Arch Linux
- Kernel version: `Linux 6.2.8-zen1-1-zen x86_64 GNU/Linux`
- Output of `solaar show`:

<details>

```
solaar version 1.1.8

Приёмник «Nano»
  Device path  : /dev/hidraw2
  USB id       : 046d:C52F
  Serial       : C8E89980
    Firmware   : 30.00.B0009
  Has 1 paired device(s) out of a maximum of 1.
  Has 39 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)

  1: Wireless Mouse Pebble M350
     Device path  : /dev/hidraw3
     WPID         : 4080
     Codename     : Pebble
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 325949ED
     Model ID:      B02140800000
     Unit ID:       54297D41
          Firmware: MPM 18.00.B0007
             Other: 
     The power switch is located on the base.
     Supports 27 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: Firmware MPM 18.00.B0007 4080BEA0D686
            Firmware: Other   
            Unit ID: 54297D41  Model ID: B02140800000  Transport IDs: {'btleid': 'B021', 'wpid': '4080'}
         3: DEVICE NAME            {0005} V0     
            Name: M350 Wireless Mouse
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
         6: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: Logitech Pebble
         7: BATTERY STATUS         {1000} V1     
            Battery: 20%, discharging, next level 5%.
         8: REPROG CONTROLS V4     {1B04} V4     
            Действие кнопки/клавиши (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button}
            Действие кнопки/клавиши        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button}
            Поведение клавиш/кнопок (saved): {Middle Button:Обычное}
            Поведение клавиш/кнопок        : {Middle Button:Обычное}
         9: CHANGE HOST            {1814} V1     
            Подключено к        : 1:not-a-virus
        10: ADJUSTABLE DPI         {2201} V1     
            Чувствительность (тчк/дюйм) (saved): 2000
            Чувствительность (тчк/дюйм)        : 2000
        11: LOWRES WHEEL           {2130} V0     
            Wheel Reports: HID
            Поведение колеса прокрутки (saved): False
            Поведение колеса прокрутки        : False
        12: DEVICE RESET           {1802} V0    internal, hidden 
        13: unknown:1803           {1803} V0    internal, hidden 
        14: CONFIG DEVICE PROPS    {1806} V5    internal, hidden 
        15: unknown:1812           {1812} V0    internal, hidden 
        16: OOBSTATE               {1805} V0    internal, hidden 
        17: unknown:1830           {1830} V0    internal, hidden 
        18: unknown:1890           {1890} V4    internal, hidden 
        19: unknown:1891           {1891} V4    internal, hidden 
        20: unknown:18A1           {18A1} V0    internal, hidden 
        21: unknown:1DF3           {1DF3} V0    internal, hidden 
        22: unknown:1E00           {1E00} V0    hidden 
        23: unknown:1EB0           {1EB0} V0    internal, hidden 
        24: unknown:1861           {1861} V0    internal, hidden 
        25: unknown:18B1           {18B1} V0    internal, hidden 
        26: unknown:1E22           {1E22} V0    internal, hidden 
     Has 4 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, reprogrammable, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, reprogrammable, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         3: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:3, group mask:empty
             reporting: default
     Battery: 20%, discharging, next level 5%.
```
</details>

- Contents of `~/.config/solaar/config.yaml`:

<details>

```
- 1.1.8
- _NAME: Wireless Mouse Pebble M350
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer]
  _battery: 4096
  _modelId: B02140800000
  _sensitive: {dpi: true, lowres-scroll-mode: false}
  _serial: 325949ED
  _unitId: 54297D41
  _wpid: '4080'
  change-host: null
  divert-keys: {82: 0}
  dpi: 2000
  lowres-scroll-mode: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82}
- _NAME: M350 Wireless Mouse
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer]
  _battery: 4096
  _modelId: B02140800000
  _sensitive: {dpi: true, lowres-scroll-mode: false}
  _unitId: 54297D41
  change-host: null
  divert-keys: {82: 0}
  dpi: 2000
  lowres-scroll-mode: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82}

```
</details>

- Errors or warrnings from Solaar:

**Describe the bug**
When you turn on the smooth scrolling function, scrolling does not work :(

**Additional context, -ddd**
```
2023-04-04 13:33:59,883,883    DEBUG [ReceiverListener:hidraw2] logitech_receiver.base: (16) => r[11 01 0B00 01000000000000000000000000000000]
2023-04-04 13:33:59,883,883    DEBUG [ReceiverListener:hidraw2] logitech_receiver.notifications: <Device(1,4080,Wireless Mouse Pebble M350,325949ED)>: notification for feature LOWRES WHEEL, report 0, data 01000000000000000000000000000000
2023-04-04 13:34:00,463,463    DEBUG [ReceiverListener:hidraw2] logitech_receiver.base: (16) => r[11 01 0B00 FF000000000000000000000000000000]
2023-04-04 13:34:00,463,463    DEBUG [ReceiverListener:hidraw2] logitech_receiver.notifications: <Device(1,4080,Wireless Mouse Pebble M350,325949ED)>: notification for feature LOWRES WHEEL, report 0, data FF000000000000000000000000000000
```

**Comment by pfps** [comment]
Solaar doesn't have a smooth scrolling function.   What exactly are you doing?   What exactly is happening?

**Comment by pfps** [comment]
There are two entries for your mouse in ~/.config/solaar/config.yaml.   This may be from an old bug in Solaar.   Please delete the file when Solaar is not running and see whether two entries return when you connect the mouse both ways it can connect.

**Comment by pooh2pooh** [comment]
> Solaar doesn't have a smooth scrolling function. What exactly are you doing? What exactly is happening?

I am attaching a screenshot from the off-site and from the solaar setup window:
![изображение](https://user-images.githubusercontent.com/21198356/229879016-f743f93f-00f5-4097-ac18-52982d1890d9.png)
![изображение](https://user-images.githubusercontent.com/21198356/229879305-18dcf193-6d09-44bc-8a8f-e5dac955100b.png)

> There are two entries for your mouse in ~/.config/solaar/config.yaml. This may be from an old bug in Solaar. Please delete the file when Solaar is not running and see whether two entries return when you connect the mouse both ways it can connect.

These two entries, one for each connection. With the receiver and Bluetooth.
The function does not work in both.

**Comment by pfps** [comment]
The driver only implements smooth scrolling for some mice, probably not yours.   To prevent any interference with the driver, you need to switch the lock icon to its ignore state, not the locked or unlocked state.

**Comment by pooh2pooh** [comment]
> The driver only implements smooth scrolling for some mice, probably not yours. To prevent any interference with the driver, you need to switch the lock icon to its ignore state, not the locked or unlocked state.

If you disable this option, scrolling works as usual. Just in -ddd mode scrolling events come correctly. And in general I would really like to have smooth scrolling in my system. Like it works in MacOS for example, or with the Smooth Scrool utility in Windows... Maybe there is more precise, perhaps technical information. Then there is a chance and find a solution :)

**Comment by pfps** [comment]
Smooth scrolling depends on the driver, not Solaar.

**Comment by bshener** [comment]
![image](https://user-images.githubusercontent.com/2650406/230805710-530021e9-a7e3-40c5-a454-505b5b1e2e87.png)

i set this function and working correctly in my case. but after 5-10 min later when i dont use mouse i guess its disabled. gui seems good but my scroll doesnt work correctly until  i click disable and enable again.

**Comment by pooh2pooh** [comment]
> ![image](https://user-images.githubusercontent.com/2650406/230805710-530021e9-a7e3-40c5-a454-505b5b1e2e87.png)
> 
> i set this function and working correctly in my case. but after 5-10 min later when i dont use mouse i guess its disabled. gui seems good but my scroll doesnt work correctly until i click disable and enable again.

Can you explain the effect on scrolling of this function. i.e. compare scrolling with and without the function enabled

**Comment by bshener** [comment]
> 

if its disable page scrolling moving very slow and not smooth if its enable its better. its hard to explain actually but i think its not about only scrolling speed its better to use always when using enabled. i cant do this without use solaar include system setting or another app. probably there is a calculation with scroll speed and how many spin scroll button. i didnt inspect source code actually. i am just talking about user experience.

**Comment by bshener** [comment]
> > ![image](https://user-images.githubusercontent.com/2650406/230805710-530021e9-a7e3-40c5-a454-505b5b1e2e87.png)
> > i set this function and working correctly in my case. but after 5-10 min later when i dont use mouse i guess its disabled. gui seems good but my scroll doesnt work correctly until i click disable and enable again.
> 
> Can you explain the effect on scrolling of this function. i.e. compare scrolling with and without the function enabled

if its disable page scrolling moving very slow and not smooth if its enable its better. its hard to explain actually but i think its not about only scrolling speed its better to use always when using enabled. i cant do this without use solaar include system setting or another app. probably there is a calculation with scroll speed and how many spin scroll button. i didnt inspect source code actually. i am just talking about user experience.

**Comment by pfps** [comment]
In general it is best to have this setting be ignored (by changing the lock icon away from either locked or unlocked).   The problem is that the HID++ driver assumes that it has full control of the setting and interactions between it and Solaar can result in unexpected behaviour.   It is even better to have the other two Scroll Wheel settings ignored as well, as even these can cause problems with the driver.

This all assumes that you have a version of the driver that implements smooth scrolling and that you don't have any of the other methods for implementing smooth scrolling in place.

**Comment by pfps** [comment]
Is there anything more to be done here?

**Comment by pfps** [comment]
Closed due to no response.
