### ISSUE TITLE
No percentage is displayed for either keyboard or mouse

### ISSUE THREAD

**Issue by twifty** [pwr-Solaar/Solaar#206]
I have a K800 keyboard and M950T mouse, on Ubuntu 14.04. The GUI displays the battery levels of each in icon and text form, but there is no percentage. `upower -d` successfully displays it for each device, so I know it should be possible.

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by twifty** [comment]
Since posting this I have been using Manjaro KDE which has the battery status built in.
