### ISSUE TITLE
After upgrading from 1.1.8-1.fc37 to 1.1.9-1.fc37 GKeys on G613 stop working

### ISSUE THREAD

**Issue by cfeatgit** [pwr-Solaar/Solaar#2064]
**Describe the bug**
Key G1 to G6 are not working anymore.

**To Reproduce**
Install solaar-udev-1.1.9-1.fc37.noarch and solaar-1.1.9-1.fc37.noarch
start solar with parameter -dd
-> press any G-Key, see exception  from _unpack, since notification data is only 15 Bytes (all zero) and it tries to unpack 4 Int.

Revert to solaar-udev-1.1.8-1.fc37 and solaar-1.1.8-1.fc37
-> everything works again.

**Comment by pfps** [comment]
This is almost certainly #2056

**Comment by pfps** [comment]
Closing due to no response from submitter.
