### ISSUE TITLE
Customizing gesture smart shift Logitech MX Master 3

### ISSUE THREAD

**Issue by tiger360** [pwr-Solaar/Solaar#2068]
I would like to configure the button located under the scroll wheel, commonly known as the SmartShift button, to execute a command line when pressed. Additionally, I would like to associate a gesture, specifically a downward gesture, with this button.

Ideally, I would like the SmartShift button to trigger a command line execution upon a single press, and perform a downward gesture to activate the associated functionality. This customization would greatly enhance my productivity and streamline my workflow.

I have explored Solaar and its available settings, but I couldn't find a straightforward way to achieve this customization. Therefore, I am reaching out to you for guidance on how to accomplish this task.

If there are any advanced configuration options or additional software that can help me achieve this customization, I would greatly appreciate your recommendations and instructions.

Thanks
![image](https://github.com/pwr-Solaar/Solaar/assets/5794444/87589de1-5219-46cb-bb15-abf018c2c588)

![image](https://github.com/pwr-Solaar/Solaar/assets/5794444/1ba710e3-ffbf-45e3-a03d-c2f2fad09686)

**Comment by pfps** [comment]
It appears that you want to have a rule trigger when you press the Smart Shift button and also have the button initiate mouse gestures.  If you set the Smart Shift button to Mouse Gestures this will happen.   You can then write a rule conditioned on the pressing of the Smart Shift button and a separate rule conditioned on whatever mouse gesture you want.  What you cannot get is the two to interact in this way.   But you can write a mouse gesture condition that requires that the button that starts the gesture is the Smart Shift button, which I think is what you want.


From https://pwr-solaar.github.io/Solaar/rules

Solaar can also create special notifications in response to mouse movements on some mice. Setting Key/Button Diversion for a key or button to Mouse Gestures causes the key or button to create a Mouse Gesture notification for the period that the key or button is depressed. Moving the mouse creates a mouse movement event. Stopping the mouse for a little while and moving it again creates another mouse movement event. Pressing a diverted key creates a key event. When the key is released the sequence of events is sent as a synthetic notification that can be matched with Mouse Gesture conditions.

Mouse Gesture conditions are true if the actions (mouse movements and diverted key presses) taken while a mouse gestures button is held down match the arguments of the condition. Mouse gestures buttons can be set using the ‘Key/Button Diversion’ setting, by changing the value to Mouse Gestures. The arguments of a Mouse Gesture condition can be a direction, i.e., Mouse Up, Mouse Down, Mouse Left, Mouse Right, Mouse Up-Left, Mouse Up-Right, Mouse Down-Left, or Mouse Down-Right, or the Logitech name of a key. If the first argument is the Logitech name of a key then that argument is matched against the button that was held down to initiate mouse gesture processing. For example, a Mouse Gesture condition of Mouse Up -> Mouse Up would match pressing any Mouse Gestures button, moving the mouse upwards, pausing momentarily, moving the mouse upwards again, and releasing the button. The condition Smart Shift -> Mouse Down -> Back Button would match pressing the Smart Shift button (provided that it is a Mouse Gestures button!), moving the mouse downwards, clicking the Back button (provided that it is diverted!), and then releasing the Smart Shift button. Directions and buttons can be mixed and chained together however you like. It’s possible to create a No-op gesture by clicking ‘Delete’ on the initial Action when you first create the rule. This gesture will trigger when you simply click a Mouse Gestures button.

**Comment by pfps** [comment]
Did this work for you?

**Comment by pfps** [comment]
Closing due to no response from submitter.

**Comment by tiger360** [comment]
no unfortunately i did not succeed.
![image](https://github.com/pwr-Solaar/Solaar/assets/5794444/5f6722f0-88da-4dec-a94e-30d043c5d0e4)

**Comment by pfps** [comment]
ChatGPT needs data and there is next to none for Solaar rules.

The rules that you write are stored in ~/.config/solaar/rules.yaml

**Comment by pfps** [comment]
Is there anything else to be done here?

**Comment by tiger360** [comment]
unfortunately i could not succeed to do it.
is there a video explaining something similar ?
even just clicking on the smart shift button to make a "CTRL+C", I didn't manage to do it 😅

**Comment by pfps** [comment]
Is there anything more to be done here?

**Comment by pfps** [comment]
Closing due to no response.
