### ISSUE TITLE
New logitech MX MASTER

### ISSUE THREAD

**Issue by patricklibert** [pwr-Solaar/Solaar#208]
Hi,

I bought the new Logitech MX MASTER, it's replace the performance MX.
Basic functionality is working.
I want the 'side scroll wheel' to work, Not the basic scrolling.

Check
http://www.logitech.com/en-roeu/product/mx-master

Thanks

**Comment by Lekensteyn** [comment]
Can you attach more device information?

```
solaar show > output.txt
```

**Comment by redman5087** [comment]
solaar show > output.txt doesn't work



solaar show > output.txt
usage: solaar [-h] [-d] [-V]
solaar: error: unrecognized arguments: show

**Comment by Lekensteyn** [comment]
It looks like you have an older version of Solaar installed. Can you try the version from git, and then invoke `bin/solaar show > output.txt`? Or else try `solaar-cli show > output.txt`

**Comment by redman5087** [comment]
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 8A8D9ADC
    Firmware   : 24.01.B0023
    Bootloader : 01.08
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=39

  1: Wireless Mouse MX Master
     Codename     : MX Master
     Kind         : mouse
     Wireless PID : 4041
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 8F46A716
        Bootloader: BOT 18.00.B0012
          Firmware: MPM 11.00.B0012
          Firmware: MPM 11.00.B0012
             Other: 
     The power switch is located on the base.
     Supports 29 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: unknown:0020           {0020}   
         6: BATTERY STATUS         {1000}   
         7: unknown:1814           {1814}   
         8: unknown:1B04           {1B04}   
         9: unknown:2201           {2201}   
        10: VERTICAL SCROLLING     {2100}   
        11: unknown:2110           {2110}   
        12: unknown:2121           {2121}   
        13: unknown:6501           {6501}   
        14: unknown:00C1           {00C1}   
        15: unknown:1813           {1813}   internal, hidden
        16: unknown:1830           {1830}   internal, hidden
        17: unknown:1890           {1890}   internal, hidden
        18: unknown:18A1           {18A1}   internal, hidden
        19: unknown:18C0           {18C0}   internal, hidden
        20: unknown:1DF3           {1DF3}   internal, hidden
        21: unknown:1E00           {1E00}   hidden
        22: unknown:1EB0           {1EB0}   internal, hidden
        23: unknown:1803           {1803}   internal, hidden
        24: unknown:1861           {1861}   internal, hidden
        25: unknown:9000           {9000}   internal, hidden
        26: unknown:9200           {9200}   internal, hidden
        27: unknown:9240           {9240}   internal, hidden
        28: unknown:1805           {1805}   internal, hidden
     Battery: 50%, discharging.

**Comment by jasontibbitts** [comment]
I haven't had any problems with the MX Master mice I have on two Fedora 21 machines.   Absolutely everything works, including the side scroll wheel and the three side buttons.  However, the battery status is a bit flaky.  At initial startup everything is fine, but after the mouse goes to sleep and wakes back up, the battery status changes to "unknown".  Restarting soaar or unplugging and re-plugging the receiver gets the battery status back to normal.

Currently I've updated to the git version and I'll see if anything changes.  My 'show' output isn't significantly different from the output in the above comment, except that the firmware versions of the receiver are a bit newer:

    Firmware   : 12.03.B0025
    Bootloader : 02.15

**Comment by jasontibbitts** [comment]
Just an update: I have no issues whatsoever with the package I built from git four days ago.  The problem with the battery status changing to unknown is gone.  Will pull again to try out the commit that happened a bit ago.

**Comment by prettyv** [comment]
@Lekensteyn I also just got mine today and am willing to help if any more detailed info is needed (you mentioned something about needing a capture to investigate the DPI adjustability in your last commit?)
And since the output of ```solaar show``` is a bit different with latest master than what was posted above, here is mine:
```
Unifying Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:c52b
  Serial       : D0609446
    Firmware   : 24.01.B0023
    Bootloader : 01.08
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=56

  1: Wireless Mouse MX Master
     Codename     : MX Master
     Kind         : mouse
     Wireless PID : 4041
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 2EEC5C40
        Bootloader: BOT 18.00.B0012
          Firmware: MPM 11.00.B0012
          Firmware: MPM 11.00.B0012
             Other: 
     The power switch is located on the base.
     Supports 29 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
         7: CHANGE HOST            {1814}   
         8: REPROG CONTROLS V4     {1B04}   
         9: ADJUSTABLE DPI         {2201}   
        10: VERTICAL SCROLLING     {2100}   
        11: SMART SHIFT            {2110}   
        12: HIRES WHEEL            {2121}   
        13: GESTURE 2              {6501}   
        14: DFUCONTROL 2           {00C1}   
        15: unknown:1813           {1813}   internal, hidden                                                                                                                                                                                                                                 
        16: unknown:1830           {1830}   internal, hidden                                                                                                                                                                                                                                 
        17: unknown:1890           {1890}   internal, hidden                                                                                                                                                                                                                                 
        18: unknown:18A1           {18A1}   internal, hidden                                                                                                                                                                                                                                 
        19: unknown:18C0           {18C0}   internal, hidden                                                                                                                                                                                                                                 
        20: unknown:1DF3           {1DF3}   internal, hidden                                                                                                                                                                                                                                 
        21: unknown:1E00           {1E00}   hidden                                                                                                                                                                                                                                           
        22: unknown:1EB0           {1EB0}   internal, hidden                                                                                                                                                                                                                                 
        23: unknown:1803           {1803}   internal, hidden                                                                                                                                                                                                                                 
        24: unknown:1861           {1861}   internal, hidden                                                                                                                                                                                                                                 
        25: unknown:9000           {9000}   internal, hidden                                                                                                                                                                                                                                 
        26: unknown:9200           {9200}   internal, hidden                                                                                                                                                                                                                                 
        27: unknown:9240           {9240}   internal, hidden                                                                                                                                                                                                                                 
        28: unknown:1805           {1805}   internal, hidden                                                                                                                                                                                                                                 
     Battery: 50%, discharging.
```
I see the battery percentage is the exact same as above, does the reading not work correctly at the moment or is that just random chance? I'll keep an eye on whether the reading changes over the next days...

**Comment by jasontibbitts** [comment]
For me the battery percentage reads 90% when fully charged, then drops to 50% and (so far) has stayed there.  I assume it will drop further once the mouse finally drains its charge, but so far for me it's been a couple of weeks and it still hasn't run low.

**Comment by jasontibbitts** [comment]
So my battery just got low enough for something to happen.

First Solaar opened a notification saying "Battery: 20% (invalid battery)".  The icon flashed yellow. The regular dialog opened and says the battery is at 50% (and it stays that way even if I close it).  The systray icon shows the battery being low, and the tooltip says the same "Battery: 20% (invalid battery)" message.  solaar show says "Battery: 20%, discharging.":

```
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 802C917E
    Firmware   : 12.03.B0025
    Bootloader : 02.15
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=251

  1: Wireless Mouse MX Master
     Codename     : MX Master
     Kind         : mouse
     Wireless PID : 4041
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 2788C6D5
        Bootloader: BOT 18.00.B0012
          Firmware: MPM 11.00.B0012
          Firmware: MPM 11.00.B0012
             Other:
     The power switch is located on the base.
     Supports 29 HID++ 2.0 features:
         0: ROOT                   {0000}
         1: FEATURE SET            {0001}
         2: DEVICE FW VERSION      {0003}
         3: DEVICE NAME            {0005}
         4: WIRELESS DEVICE STATUS {1D4B}
         5: RESET                  {0020}
         6: BATTERY STATUS         {1000}
         7: CHANGE HOST            {1814}
         8: REPROG CONTROLS V4     {1B04}
         9: ADJUSTABLE DPI         {2201}
        10: VERTICAL SCROLLING     {2100}
        11: SMART SHIFT            {2110}
        12: HIRES WHEEL            {2121}
        13: GESTURE 2              {6501}
        14: DFUCONTROL 2           {00C1}
        15: unknown:1813           {1813}   internal, hidden
        16: unknown:1830           {1830}   internal, hidden
        17: unknown:1890           {1890}   internal, hidden
        18: unknown:18A1           {18A1}   internal, hidden
        19: unknown:18C0           {18C0}   internal, hidden
        20: unknown:1DF3           {1DF3}   internal, hidden
        21: unknown:1E00           {1E00}   hidden
        22: unknown:1EB0           {1EB0}   internal, hidden
        23: unknown:1803           {1803}   internal, hidden
        24: unknown:1861           {1861}   internal, hidden
        25: unknown:9000           {9000}   internal, hidden
        26: unknown:9200           {9200}   internal, hidden
        27: unknown:9240           {9240}   internal, hidden
        28: unknown:1805           {1805}   internal, hidden
     Battery: 20%, discharging.
```

**Comment by jasontibbitts** [comment]
And hopefully a final update on this:

I let the mouse at work run down completely.  After it died I plugged it in to charge.  Unfortunately solaar still shows it at 5% battery and does not show that it is charging.

**Comment by mishan** [comment]
I have one of these and would really love to be able to adjust the SmartShift feature so the mouse wheel doesn't prematurely clutch out

**Comment by WorLord** [comment]
I was just looking for a way to disable the SMART SHIFT feature myself.  It's... OK, but I like it to be off.  

Output from 'solaar show':

Wireless Mouse MX Master
     Codename     : MX Master
     Kind         : mouse
     Wireless PID : 4041
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 67362E7C
        Bootloader: BOT 18.01.B0014
          Firmware: MPM 11.02.B0014
          Firmware: MPM 11.02.B0014
             Other: 
     The power switch is located on the base.
     Supports 29 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
         7: CHANGE HOST            {1814}   
         8: REPROG CONTROLS V4     {1B04}   
         9: ADJUSTABLE DPI         {2201}   
        10: VERTICAL SCROLLING     {2100}   
        11: SMART SHIFT            {2110}   
        12: HIRES WHEEL            {2121}   
        13: GESTURE 2              {6501}   
        14: DFUCONTROL 2           {00C1}   
        15: unknown:1813           {1813}   internal, hidden
        16: unknown:1830           {1830}   internal, hidden
        17: unknown:1890           {1890}   internal, hidden
        18: unknown:18A1           {18A1}   internal, hidden
        19: unknown:18C0           {18C0}   internal, hidden
        20: unknown:1DF3           {1DF3}   internal, hidden
        21: unknown:1E00           {1E00}   hidden
        22: unknown:1EB0           {1EB0}   internal, hidden
        23: unknown:1803           {1803}   internal, hidden
        24: unknown:1861           {1861}   internal, hidden
        25: unknown:9000           {9000}   internal, hidden
        26: unknown:9200           {9200}   internal, hidden
        27: unknown:9240           {9240}   internal, hidden
        28: unknown:1805           {1805}   internal, hidden
     Battery: 50%, discharging.

**Comment by javitonino** [comment]
I have submitted a PR adding support for DPI and Smart Shift for the MX Master. I have one of these and I am already set up for USB sniffing the Windows drivers, so if anyone is interested I could provide some traces or help to add new functionality.

**Comment by mishan** [comment]
Thank you @javitonino !

**Comment by arigit** [comment]
Running the latest code from the master branch; is there a way to set the "Smart Shift Sensitivity" with Solaar command line (or GUI)? I'm new to solaar. 

I tried changing the sensitivity on Windows using the official driver (which works) but unfortunately when I switch to my linux desktop, all the custom settings are gone, looks like the settings do not get stored in the device. 


Bootloader: BOT 18.01.B0014
          Firmware: MPM 11.02.B0014
          Firmware: MPM 11.02.B0014
             Other: 
     The power switch is located on the base.
     Supports 29 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
         7: CHANGE HOST            {1814}   
         8: REPROG CONTROLS V4     {1B04}   
         9: ADJUSTABLE DPI         {2201}   
        10: VERTICAL SCROLLING     {2100}   
        11: SMART SHIFT            {2110}   
        12: HIRES WHEEL            {2121}   
        13: GESTURE 2              {6501}   
        14: DFUCONTROL 2           {00C1}   
        15: unknown:1813           {1813}   internal, hidden
        16: unknown:1830           {1830}   internal, hidden
        17: unknown:1890           {1890}   internal, hidden
        18: unknown:18A1           {18A1}   internal, hidden
        19: unknown:18C0           {18C0}   internal, hidden
        20: unknown:1DF3           {1DF3}   internal, hidden
        21: unknown:1E00           {1E00}   hidden
        22: unknown:1EB0           {1EB0}   internal, hidden
        23: unknown:1803           {1803}   internal, hidden
        24: unknown:1861           {1861}   internal, hidden
        25: unknown:9000           {9000}   internal, hidden
        26: unknown:9200           {9200}   internal, hidden
        27: unknown:9240           {9240}   internal, hidden
        28: unknown:1805           {1805}   internal, hidden
     Battery: 90%, discharging.

**Comment by shihrer** [comment]
Anyone know if it's possible to get the thumb button to do anything?

**Comment by javitonino** [comment]
@shihrer Take a look at https://github.com/pwr/Solaar/issues/321#issuecomment-268617221. In short, you can remap it to other mouse buttons, but nothing overly useful.

**Comment by jasontibbitts** [comment]
For me without any configuration the thumb button just generates Ctrl-Alt-Tab.  I have that mapped as "Toggle Present Windows" in KDE, but I suppose you could have it do whatever by intercepting that key combination.  I actually find that to be something I use pretty often.

**Comment by pabgan** [comment]
Hello there. I have this mouse and use Gnome on Fedora 25. I would like the thumb button to fire the activity overview. Currently, when I click that button the "Activity" word gets highlighted, but does nothing. Do you know how can I achieve this?

**Comment by oryband** [comment]
There are still issued with saving the DPI value. The value is saved as string to `.config/solaar/config.json` but when turning the mouse off and on again the actual value being used is always 1000.

**Comment by oryband** [comment]
opened new issue #358

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original posters.
