### ISSUE TITLE
No module named _ctypes when instaling solaar 1.1.9 from repo

### ISSUE THREAD

**Issue by kylefelipe** [pwr-Solaar/Solaar#2081]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.9
- Distribution: Ubntu 20.04
- Python Version: 3.10
- Kernel version (ex. `uname -srmo`): Linux 5.19.0-43-generic x86_64 GNU/Linux
- Output of `solaar show`:

<details>

```
SOLAAR SHOW OUTPUT HERE
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
CONTENTS HERE
```
</details>

- Errors or warrnings from Solaar:

**Describe the bug**
When installing solaar from repository it shows "no module named _ctypes"

**To Reproduce**
1. Clone repo
2. cd to repo
3. install dependencies
4. pip install --user solaar
5. See error

**Screenshots**
![image](https://github.com/pwr-Solaar/Solaar/assets/24795382/65986d0b-48f7-4cbd-a994-81e1396a7f16)

**Additional context**

**Comment by pfps** [comment]
This appears to be a distribution problem.  How did you install Solaar?

**Comment by kylefelipe** [comment]
@pfps 
Steps to reproduce the behavior:
>1. Clone repo
>2. cd to repo
>3. install dependencies
>4. pip install --user solaar

**Comment by kylefelipe** [comment]
@pfps
Following this tutorial i solved my issue...
https://www.pythonpool.com/modulenotfounderror-no-module-named-_ctypes-solved/
Thx!
