### ISSUE TITLE
mx keyboard pin code for connection not showing while pairing

### ISSUE THREAD

**Issue by emitruc** [pwr-Solaar/Solaar#2084]
Hi, 
I would like to use the Logitech Unifying Receiver in my UBUNTU 22.04.1 system.

I have successfully paired a MX3 Anywhere mouse with or without Solaar. 

In Solaar I can see  the receiver and mouse properly paired

![image](https://github.com/pwr-Solaar/Solaar/assets/136356460/ea466320-1e35-4590-b12a-30ca6a5eaa74)

When I try to pair a new device, Logitch Keyboard MX Mini, the pairing runs for a while before failingù

![image](https://github.com/pwr-Solaar/Solaar/assets/136356460/4fa7c3ed-c8c4-4ce1-b534-61dc2bec0b77)

When I paired the same keyboard on another Linux-running machine using the built-in bluetooth, the pairing worked but it prompted a code I had to type on the keyboard.

I am worried that a similar PIN code is necessary for the pairing in Solaar but it does not show up.

How can I get Solaar to give me a PIN code to be typed on the keyboard? No problem using the command-line interface in case it is needed. 

Thanks
Emiliano

**Comment by pfps** [comment]
Is your MX Mini a unifying-capable device?   Look for the Unifying logo on it. 

What exactly is the model of the device you have?

**Comment by emitruc** [comment]
I must apologize. I assumed the logitech MX Mini was unifying-capable as the larger MX keyboard but I was wrong. The Mini does not have the unifying logo but it connects via Bluetooth only. Sorry for this stupid issue.
Emiliano

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
