### ISSUE TITLE
Need more information about french translation

### ISSUE THREAD

**Issue by david-geiger** [pwr-Solaar/Solaar#2086]
Hi,

I'm to update the French translation but we need more information about some strings like "diverted" and "diversion" what you mean about this? 

Also for "Sliding DPI" what is exactly the "DPI"?

Thanks in advance

Regards,
David

**Comment by david-geiger** [comment]
Thank you so much, and yes your explanation is perfect :)

**Comment by pfps** [comment]
OK, closing.
