### ISSUE TITLE
MX Keys: pairing failed: sequence timeout

### ISSUE THREAD

**Issue by sdarwin** [pwr-Solaar/Solaar#2091]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): solaar 1.1.9-19-g444fd4a
- Distribution:
- Kernel version (ex. `uname -srmo`): `KERNEL VERSION HERE` Linux 5.15.0-58-generic x86_64 GNU/Linux
- Output of `solaar show`:
attached file solaar-show.txt
[solaar-show.txt](https://github.com/pwr-Solaar/Solaar/files/11905722/solaar-show.txt)

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

attached files config.yaml and config.json
[config.yaml.txt](https://github.com/pwr-Solaar/Solaar/files/11905644/config.yaml.txt)
[config.json.txt](https://github.com/pwr-Solaar/Solaar/files/11905650/config.json.txt)

- Errors or warrnings from Solaar:
solaar -dd

attached file debug.txt 
[debug.txt](https://github.com/pwr-Solaar/Solaar/files/11905701/debug.txt)

**Describe the bug**
Hi,
Perhaps this is as much a request for help or feedback as it is a bug. I think there should be 3 ways to connect a Logitech MX Keys keyboard to a fairly new Ubuntu 22.04 HP Pavilion laptop:  

- Bluetooth
- Universal USB Transceiver
- Directly via USB cable

However at the moment only Bluetooth is working. What would be debugging steps to get the other methods to work?

1. directly via USB cable.  I connect the device and the keyboard does not operate.  Reboot the laptop.  Same thing. No response from keyboard.

2. Universal USB Transceiver.  Open Solaar. Click Nano Receiver. Click "Pair new device".  Nothing. Turn the keyboard on and off.  It quickly shows this error: "pairing failed: sequence timeout"

The battery is charged.  

I have tried this when the device is NOT connected via bluetooth, as well as when it is already connected to bluetooth.  Either way.  The error is consistent and the same.  "pairing failed: sequence timeout"

**Screenshots**
see attached screenshot
![Screenshot from 2023-06-29 06-18-19](https://github.com/pwr-Solaar/Solaar/assets/1257803/4dc2a40a-8649-47c1-831a-e417544c3bfd)

**Comment by pfps** [comment]
For newer devices Logitech provides information about connection methods.   For your keyboard the information is
```
Model ID: B35B408A0000  Transport IDs: {'btleid': 'B35B', 'wpid': '408A'}
```
So it looks as if direct USB connection is not supported.   Even if a USB cable was provided it may only be for charging.

Your keyboard is likely pairable with a unifying receiver, not a nano receiver.   From https://github.com/pwr-Solaar/Solaar

> Solaar can pair and unpair a Logitech device showing the Unifying [logo](https://pwr-solaar.github.io/Solaar/assets/solaar.svg) (Solaar's version of the logo) with any Unifying receiver, and pair and unpair a Logitech device showing the Bolt logo with any Bolt receiver, and can pair and unpair Lightspeed devices with Lightspeed receivers for the same model. Solaar can pair some Logitech devices with Logitech Nano receivers but not all Logitech devices can be paired with Nano receivers. Logitech devices without a Unifying or Bolt logo generally cannot be paired with Unifying or Bolt receivers.

**Comment by sdarwin** [comment]
@pfps wow! thanks!

I kept the receivers in a collection of cables and parts, some time had passed since the purchase, and I did not consider there were two receivers. Probably one from the keyboard and one from the mouse.  

Switch to the other receiver.  Now it works. See screenshot.

![Screenshot from 2023-06-29 09-51-20](https://github.com/pwr-Solaar/Solaar/assets/1257803/64f70c49-5a38-4e27-95a9-05d8eb0e85bf)

So it's fixed!

---

As a post-mortem on the issue lets consider if anything could be done to improve error reporting.  Currently there is one suggestion in the message "decent battery charge".   We have now discovered another reason, if someone gets "pairing failed: sequence timeout". 

Here is a possible idea. Add a hyperlink in the message to a FAQ or Errors webpage.  For this particular error explain:  "Another possible cause of the error is this keyboard requires a Universal Receiver, and you are attempting to pair with a Nano Receiver.  The pairing may not be supported. Check if you have a Universal Receiver to pair with, it should have a logo indicating that functionality."

**Comment by sdarwin** [comment]
Upon further consideration, yes the text you have provided in the README already contains the clue to the answer:  

"Solaar can pair some Logitech devices with Logitech Nano receivers but not all Logitech devices can be paired with Nano receivers."

The problem is, if someone gets the error in real life, perhaps first they try to search for it. Click Find (Ctrl-F) on the README, there is no text "Pairing failed" or "sequence timeout".   No answer.    Although now, this GitHub issue itself becomes a search result so it may be enough, that way.

**Comment by pfps** [comment]
The pairing window talks about this already.

**Comment by sdarwin** [comment]
That message starts with "Unifying Receiver: pair new device"...
But I was using the Nano receiver.  The problem occurred with the Nano, and indeed because of it. What message does that display?

**Comment by pfps** [comment]
The operative part of that message says:

Other receivers are only compatible with a few devices

peter

**Comment by sdarwin** [comment]
"Other receivers are only compatible with a few devices"  

Yes, clearly that is very informative.

the time to send a powerful and interesting message to the user is when an actual error has happened.  "FAIL".  "ERROR". Boom.  Now you have their attention.  At this point, hopefully it could say "Error 4927346", so they may Google "Error 4927346" and get exact instructions about it.   Or the equivalent would be a unique error name or message that can be searched for.    Or even better, but perhaps difficult, display the actual solution to the error.

**Comment by pfps** [comment]
All that Solaar can see is that there was a timeout.   The reason for this timeout is not known.

**Comment by DanishFayaz** [comment]
Hi, my unifying receiver can't pick up mx keys mini while its connected with master 3. Tried several ways: turned off bluetooth, device restarts. Any clues?

![Screenshot from 2023-10-01 22-03-02](https://github.com/pwr-Solaar/Solaar/assets/7261460/0a3ebfdc-cf83-4572-aec2-237ada993a5f)

**Comment by pfps** [comment]
Take a look at https://www.logitech.com/en-ca/products/keyboards/mx-keys-mini.html
It appears that the keyboard needs a Bolt receiver.
