### ISSUE TITLE
Give the user info on whether a dongle is found

### ISSUE THREAD

**Issue by velle** [pwr-Solaar/Solaar#2107]
... and whether communication with the dongle is successful.

My mouse, Logi M310, has been in the drawer for months. I just put in the dongle and replaced the battery, but it does not work. So in an attempt to find the issue I installed Solaar. 

The dongle is inserted and the mouse is turned on, but the Solaar menu writes "No Logitech Device Found". 

I don't see if Solaar actually can see any compatible dongles. Would it say somewhere if it did see any dongles? I dont normally use Solaar, so I don't know how its supposed to behave, and I don't have other Logitech products to test out with. 

Suggestion for improvement of GUI: I suggest that the GUI lists which dongles were found, or if no dongle was found then explicitly states that no dongle was found. 

Sincerely

**Comment by pfps** [comment]
There are so many different dongles (from Logitech and from others) that it is not reasonable for Solaar to list the dongles that it sees.   Instead you could use `lsusb` to see what devices are connected via USB.

That said, the receiver that the M310 is probably supportable by Solaar.   If you provide the output of `lsusb` it will probably be possible to add it to Solaar.  

But first you should ensure that you are using a recent version of Solaar, at least version 1.1.8.

**Comment by velle** [comment]
Thanks for replying :)

> There are so many different dongles (from Logitech and from others) that it is not reasonable for Solaar to list the dongles that it sees.

Perhaps there is a misunderstanding, so let me try and be more clear, and tell me where I am wrong :) 

There will rarely be more than one dongle, though occasionally maybe two or three dongles, in any given PC. Am I right? Wouldn't it be possible to give this information to the user, that this and this dongle is currently detected in the PC? And if no dongle is found, then explicitly let the user know that no dongle was found.

In my current case, I would like some kind of feedback on whether the dongle is found by Solaar. I don't know if it was actually found or not.

**Comment by velle** [comment]
I just realized a few things. And perhaps I now understand what you meant. 

First of all, I realized that its possible to buy a Unifying compatible mouse that comes with a dongle that is not a Unifying dongle. And thats actually the situation I am in. 

So there are lots of such dongles out there, that Solaar is not able to configure in any way. And its asking for a lot, by suggesting that Solaar should recognize all of them and list them :) Thats what you were telling me. 

It appears to me now, that Solaar did not list any devices in my case because there was no compatible dongle installed. 

In that case, the most helpful message to provide to the user would be something like "No dongle (configurable by Solaar) was found". The feedback I got was "No Logitech devices found", but to me maybe that meant that a Unifying dongle was indeed found, but no Logitech mice were found by that dongle. 

Sincerely

**Comment by pfps** [comment]
Solaar doesn't know whether a USB device is a dongle so it would have to report on all unknown Logitech devices (at least), of which there could easily be four or five.

**Comment by pfps** [comment]
Solaar can support most nano receivers, but it has  to know the USB id so that it can recognize the device as a Logitech receiver.   If you provide the USB id for your receiver, then it probably can be supported by Solaar.

**Comment by velle** [comment]
Thanks for the great info that you share with me. 

There is a good chance that if I upgrade Solaar then it will support my receiver, and I plan to do that. And if it does not support my receiver then I will create an issue on that. 

I managed to get hold of a Unifying receiver. And now I see what that the information in the GUI (both the system tray and the window) is a tree structure, where the receivers are root elements and any paired device (whether online or not) are child elements. 

Let me try to explain below, how I, as a user who did not know the normal/expected behavior of Solaar/Unifying was unable to decide what the problem was, and how all the guesses I made were wrong. 

When I created this thread yesterday, I did not know, that thenormal behavior, ie that each (recognized) receiver would be listed. I just had an empty list saying saying "No Logitech device found". It believe now, that the Nano receiver inserted at the time was not compatible with my version of Solaar. Do you agree?  

Yesterday (where I had no knowledge of normal Solaar behavior, and only got "No Logitech device found") I thought the reason for this error was one of the following:

1. Solaar was compatible with my receiver, and maybe that receiver was also paired to my mouse, but the mouse was somehow dead and there was no connection to the mouse
2. My receiver was dead (because it did not show up on the GUI)
3. Solaar was compatible with my receiver, and Solaar did recognize and communicate with my receiver. But because no mouse was paired (yet) via the receiver the list was empty. 

It turns out that it was none of the above. The closest one was number two, except it is probably not dead, but just incompatible with my version of Solaar. 

For a user with no prior knowledge of Solaar, a better (more precise and more helpful) message would be very helpful. 

Even if you disagree with changing the status message ("No Logitech device found"), do you understand the point I am trying to make on the helpfulness of this message? :)

Sincerely

**Comment by pfps** [comment]
I agree that the message, although true, is rather vague.  It is just that it is hard to obtain the information needed for a precise message.  That said, I'll try to think of something that would be more helpful.
