### ISSUE TITLE
MX Master 3 Key/Button actions - simulate middle button separate press and release

### ISSUE THREAD

**Issue by jurpoc** [pwr-Solaar/Solaar#2113]
**Information**

- Solaar version (`solaar --1.1.1` and `git describe --tags`):
- Distribution: Ubuntu 22.04.2 LTS
- Kernel version (ex. `uname -srmo`): Linux 6.2.0-26-generic x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable): 
Path         : /dev/hidraw5
Index        : 2
Wireless PID : 4082
Protocol     : HID++ 4.5
Polling rate : 8 ms (125Hz)
Serial       : F09432EE
  Bootloader : BOT 95.01.B0015
  Firmware   : MPM 19.01.B0015
  Other      : 

**Is your feature request related to a problem? Please describe.**
I am a mechanical engineer using FreeCAD on Linux. On Windows and another professional CAD software I map the Forward Button or Backward Button to behave as Middle Button for rotation and/or zoom of the 3D model. By doing so, I can be much more productive and my hand rests more. This is also the reason I bought MX Master 3 mouse. 

**Describe the solution you'd like**
A simple solution would be to add the option of selecting Middle Button for Forward Button or Backward Button in _Key/Button Actions_ -> _Forward Button_ -> _Mouse Middle button_ or _Key/Button Actions_ -> _Back Button_ -> _Mouse Middle button_

![Screenshot from 2023-08-07 17-44-45_1](https://github.com/pwr-Solaar/Solaar/assets/13086707/d095a0b1-fdcb-4a98-aad5-3897a709946b)

**Describe alternatives you've considered**
I tried to make a rule in the rule editor, but I manage to make diversion only for a click and not button pressed action, which is what I use most (press the button during rotation of 3D model).

**Comment by pfps** [comment]
Solaar provides an interface to the commands that devices support and the MX Master 3 only supports reprogramming the back and forward buttons to left, right, back, and forward.  It's a silly restriction. 

Recent versions of Solaar allow rules to trigger on either the press or the release of a button.

**Comment by jurpoc** [comment]
Thank you for a quick reply. This was also the case with an old Logitech mouse, where I was limited to do the same setting as Solaar is providing, with Logitech software in Windows.
Strangely you can do this setting with the Logitech software on Windows for MX Master 3, now.

I would need a state recognition not a single trigger, so that when button is pressed (all the time) it would be as if the middle button is pressed. The function in CAD software works until the button is pressed. I press the button and move the mouse to rotate the model and than release the button.

Thank you again for you great efforts.

**Comment by pfps** [comment]
Solaar rules should let you do this.  You need a rule that triggers when the button is pressed and simulates the middle button being pressed and another for the button release.

**Comment by jurpoc** [comment]
I am sorry, but with a button pressed trigger I cannot find any mouse button to bi simulated as pressed. There are only keyboard buttons to chose from.

What am I missing?

**Comment by pfps** [comment]
There is mouse click, but I see that it only simulates a click and can't do just press or release.   I'll enhance the action, but probably not right away.

**Comment by jurpoc** [comment]
Looking forward for this enhancement.
Thanks a lot.

**Comment by pfps** [comment]
PR #2125 should fix this problem.   Please try it out and see whether it works for you.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #2125, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/2125/head:pull_2125
git checkout pull_2125
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_2125
git fetch origin pull/2125/head
git reset --hard FETCH_HEAD
```

**Comment by jurpoc** [comment]
I tried to test it, but I could not make the mouse work with this branch. Maybe something related to Wayland.
I looked at the implementation and I think it should work for me.
Anyway, thank you for the effort.
Looking forward for the new official release with this function.
