### ISSUE TITLE
Add condition for hostname

### ISSUE THREAD

**Issue by Zocker1999NET** [pwr-Solaar/Solaar#2114]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): `1.1.9+dfsg-1` (from Debian repo)
- Distribution: Debian GNU/Linux
- Kernel version (ex. `uname -srmo`): Linux 6.4.0-1-amd64 x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable): *not applicable*

**Is your feature request related to a problem? Please describe.**
I want to synchronize my settings across my computers (PC, laptop). Synchronizing .config (or rather specific sub-directories of it) with Nextcloud, Syncthing, Git, SSH, … seems the easiest way for that. However, I want some rules to apply either only on my PC or my laptop due to differences in their UI configuration (different Desktop Environments, habits, …). However, it seems impossible to fulfill both requirements without writing a specialized synchronization engine for that, as all rules are loaded from one single file.

**Describe the solution you'd like**
Add a condition which checks for the host name of a machine. This allows users like me to have one ruleset applied to all their PCs while allowing differences to exist.
This would also allow less management than having different files in certain cases like: The same gesture/button should do the same on both PCs, but on both PCs they use different key combinations for that (e.g. because on PC, mapping to numpad is possible, or something similar).
Introducing this condition should be fairly easy (at least it looks like from the outside).

**Describe alternatives you've considered**
- do not synchronize the config files, which would introduce more manual maintenance work to have similar design
- writing a specialized synchronization script, however, IMO that would more work than the solution I proposed
- allow support for reading rules from multiple files to have one for both and one per PC. This may be added as well, but it would still introduce a higher maintenance work required from the users.

**Additional context**
I have seen similar tools that allow to check for the host name to allow such setups more easily (I don’t remember their names though).

**Comment by pfps** [comment]
Sound like a good idea.

**Comment by pfps** [comment]
PR #2124 adds a host condition to rules.  Please run it and see whether it works for you.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #2124, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/2124/head:pull_2124
git checkout pull_2124
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_2124
git fetch origin pull/2124/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
Have you had a chance to try out the PR?
