### ISSUE TITLE
Polybar integration

### ISSUE THREAD

**Issue by shoddysheep** [pwr-Solaar/Solaar#2116]
Hello, dear Solaar team. First off, I want to thank you for your work on this project, it's been seamless and smooth with my MX Vertical Wireless Mouse.

I am using Polybar for my desktop, which has support for adding custom bash scripts, and whilst there is a myriad of scripts to choose from (https://github.com/polybar/polybar-scripts/tree/master), I would love to get my hands on a Solaar battery level script that shows the echos the battery level and outputs it in the Polybar.

My bash skills are barely rudimentary, but is there a way to achieve this? :)

**Comment by pfps** [comment]
Solaar doesn't have a way of extracting battery levels.   But you should be able to see the battery levels in Power Manager and you may be able to extract them using that tool.
