### ISSUE TITLE
Any way to hide/disable the tray icon?!

### ISSUE THREAD

**Issue by kbtzr** [pwr-Solaar/Solaar#212]
First, if there's an issue for this already, I'm sorry I was unable to find it.

On Elementary OS, after installing Solaar, the mouse battery meter is handled nicely by the OS.
![screenshot from 2015-04-17 04 04 51](https://cloud.githubusercontent.com/assets/1047033/7197411/313311d0-e4b7-11e4-8ee8-feb18bf56915.png)

Is there any way to the disable Solaar's tray icon?

**Comment by Lekensteyn** [comment]
If you already have battery reporting from a UPower client, why do you still need Solaar? For applying some settings?

(AFAIK the icon cannot be hidden, but it is certainly possible to implement it.)

**Comment by lovrenco** [comment]
Isi it possibel to provide it in ElementaryOS style? (White color)

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
PR #666 allows running without the tray icon
