### ISSUE TITLE
Update Xorg keysyms

### ISSUE THREAD

**Issue by DJm00n** [pwr-Solaar/Solaar#2120]
New repo path: https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/tree/master/include/X11/

https://github.com/pwr-Solaar/Solaar/blob/8dd8c8b76fe5f17f93faf2778e48902566d0580b/lib/keysyms/generate.py#L8

**Comment by pfps** [comment]
Do you know that the changes are?

**Comment by DJm00n** [comment]
>Do you know that the changes are?

There was a bunch of changes for the last year and a half:
https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/commits/master/include/X11/keysymdef.h
https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/commits/master/include/X11/XF86keysym.h

**Comment by pfps** [comment]
OK, I'll see about generating keysyms from the new repository.

**Comment by pfps** [comment]
PR #2126 should fix this problem.   Please give it a try.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #2126, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/2126/head:pull_2126
git checkout pull_2126
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_2126
git fetch origin pull/2126/head
git reset --hard FETCH_HEAD
```
