### ISSUE TITLE
When comes the new version?

### ISSUE THREAD

**Issue by Svenum** [pwr-Solaar/Solaar#2133]
I need the new version. I am waiting now a long time for the g-key fix from https://github.com/pwr-Solaar/Solaar/pull/2046.

**Comment by pfps** [comment]
The new version was stalled for a bit waiting for some fixes and confirmation of other fixes.   

One thing that might help getting the next version out is testing PR #2132.  See issue #2131 for more information.  You don't have to have that device to test the PR, just download the PR and run `./bin/solaar -ddd` and check for any problems.

**Comment by pfps** [comment]
Pre-relase 1.1.10rc3 was just made.   If there are no problems reported a real release will be done in about a week.

**Comment by Svenum** [comment]
Works great for me :smile:
