### ISSUE TITLE
Cannot Change Language

### ISSUE THREAD

**Issue by mgorfer** [pwr-Solaar/Solaar#2137]
I just started using Solaar, and I have the UI only in Japanese, which I installed as a second language on my Manjaro Linux.
None of my other Apps or Settings are displayed in Japanese, though.

I guess this is actually a user error, (as I am sometimes getting an error shown in my terminal `bsdtar: Failed to set default locale`),
but would it be possible to add a language change button to the app? Or can this easily be done via the config files?

I did not find an option while checking the [Manual](https://pwr-solaar.github.io/Solaar/).

Here is a screenshot of my UI
![image](https://github.com/pwr-Solaar/Solaar/assets/13124998/29bb9b6e-7924-4d07-98a8-d60e05b966cc)

**Comment by pfps** [comment]
Solaar uses the usual GTK methods to determine what language to use.  What is probably happening is that some environment variable is indicating that your language is Japanese.  You need to change that variable.

There is no reason to add a language-setting capability to Solaar.

**Comment by mgorfer** [comment]
You are right, of course. There is no need to add this to Solaar.

Just to explain my solution in short:
In my Manjaro Linux – KDE Plasma – System Settings – Region & Language, I can add languages in order I want to see them in my applications.
Weirdly, some applications (e.g. Solaar, but also others) are shown in the second language, while the rest of my UI is in the first language. It also chooses the second language, when there are three languages in the list.

Removing all but the first language from the list shows everything in the first language again.

I am closing this now as I Solaar has no connection to this issue.
