### ISSUE TITLE
G700 unifying receiver isn't recognized

### ISSUE THREAD

**Issue by Djfe** [pwr-Solaar/Solaar#214]
If I can provide any useful data to you that allows support for it in the future that would be great :)

Would really like to see it supported.

I'm running Korora 21 (based on Fedora) with xfce

(this is about the G700, i don't own the G700s)

**Comment by Lekensteyn** [comment]
For a start, please provide the output of

    solaar show

(or clone the repo and invoke `bin/solaar show`)

**Comment by Djfe** [comment]
the current version on my System is 0.9.2 which doesn't support "show", yet, I assume, because it said it doesn't know show.

So I cloned the repo and invoked solaar show, but the output was simply:
```solaar: error: Logitech receiver not found```

**Comment by Djfe** [comment]
lsusb | grep Logitech outputs the following:
```Bus 002 Device 003: ID 046d:c531 Logitech, Inc.```

**Comment by Djfe** [comment]
according to https://bugs.launchpad.net/ubuntu/+source/upower/+bug/1380527 the M700s uses the same receiver ```046d:c531```

**Comment by muzena** [comment]
Djfe try this repository https://github.com/muzena/Solaar

**Comment by Djfe** [comment]
is it correct that I get ```Solaar: error: [Errno 13] Keine Berechtigung: '/dev/hidraw3' ``` without root rights (sudo)

Output with sudo:
```Unifying Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:c531
  Serial       : BAA49455
    Firmware   : 21.00.B0007
    Bootloader : 02.14
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: (none)

  1: G700 Gaming Mouse
     Codename     : G700
     Kind         : mouse
     Wireless PID : 1023
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: 744DD567
          Firmware: 22.02.B0037
        Bootloader: 02.11
             Other: 02.02
     The power switch is located on the base.
     Notifications: (none).
     Battery: critical, discharging.```

when are you going to contribute https://github.com/pwr/Solaar/commit/764ebc0b3a6066e5b8b2bc4c045d8778ac336262 to the main repo?

And shouldn't the G700 also have _R.three_leds and smooth and side scroll?

I'm not able to start the GUI btw. without root rights, it tells me that it is not allowed to access ```/dev/hidraw3```
and with sudo/su it crashes because of some issues with the bus or something:
```$ ./solaar
** (solaar:2459): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.```

```$ su
Password: 
# ./solaar
(solaar:2510): libappindicator-WARNING **: Unable to get the session bus: Verbindung ist geschlossen
(solaar:2510): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Verbindung ist geschlossen```

"Verbindung ist geschlossen" is the german translation for "Connection is closed."

**Comment by muzena** [comment]
Try this remove this solaar.
Install it from yorur os repository or find in fedora reposytory on web eg.
https://admin.fedoraproject.org/updates/FEDORA-2013-21942/solaar-0.9.2-1.fc20?_csrf_token=a39e2f5503a64c1ab89b2acaf80fdc5bd6f0b83c 
And replace and add these lines in files
 lib/logitech_receiver/base_usb.py 
 lib/logitech_receiver/descriptors.py 
rules.d/42-logitech-unify-permissions.rules
https://github.com/pwr/Solaar/compare/master...muzena:master

**Comment by Djfe** [comment]
sorry for the late answer
I couldn't find the libfolder of solaar :/

I searched in several folders for "logitech_receiver" and "solaar" but couldn't find the folder with all the python files

**Comment by muzena** [comment]
/usr/share/solaar/lib/logitech_receiver/base_usb.py
/usr/share/solaar/lib/base_usb.py
/lib/udev/rules.d/ rules.d/40-solaar.rules

**Comment by Djfe** [comment]
/usr/share/solaar/lib/ doesn't exist
there is only /usr/share/icons/

the .rules file doesn't exist either
I see a 69-unifying-receiver.rules file though

**Comment by muzena** [comment]
I extract and modified fedora solar rpm package:
https://mega.co.nz/#!7s0yzIAQ!awH-usqN8l9I2o5tDRG12KiOJ-hCXuEEvJdoY-MchPY
Extract package, copy in your root directory and overwrite files, restart PC and see if it working

**Comment by Djfe** [comment]
ah ok, so the libs are in the libs folder of python 2.7
good to know
I'll take a look at it later ;)

**Comment by Djfe** [comment]
Sorry I haven't had time lately:
I tested it out:
I just get an error message
![solaar bug](https://cloud.githubusercontent.com/assets/5685512/7690677/fea5e658-fdb5-11e4-9786-25f64180a0e0.png)

Am I doing something wrong or is there still an issue within the code?

**Comment by Djfe** [comment]
actually it works when I start it with sudo
How can I get it to run as root for autorun?

@Lekensteyn would you want to implement his changes?

**Comment by Djfe** [comment]
@Lekensteyn It would be amazing if you could take a look at his changes and cherry pick them :)

debug info:
```
~ $ sudo solaar -d
00:45:26,589     INFO [MainThread] root: language de_DE (UTF-8), translations path None
00:45:26,666     INFO [MainThread] solaar.ui: application /io/github/pwr/solaar, registered True
00:45:26,748     INFO [MainThread] solaar.ui.tray: using AppIndicator3
00:45:26,750     INFO [MainThread] solaar.ui.notify: starting desktop notifications
00:45:26,798     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
00:45:26,800     INFO [MainThread] solaar.listener: starting receiver listening threads
00:45:26,827     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path=u'/dev/hidraw3', vendor_id=u'046d', product_id=u'c531', serial=None, release='2100', manufacturer='Logitech', product='USB Receiver', interface=1, driver=u'hid-generic')
00:45:26,831     INFO [ReceiverListener:hidraw3] logitech_receiver.listener: started with <NanoReceiver(/dev/hidraw3,11)> (11)
00:45:26,831     INFO [ReceiverListener:hidraw3] solaar.listener: <NanoReceiver(/dev/hidraw3,11)>: notifications listener has started (11)
00:45:26,833     INFO [ReceiverListener:hidraw3] logitech_receiver.receiver: <NanoReceiver(/dev/hidraw3,11)>: receiver notifications enabled => ('wireless', 'software present')
00:45:26,836     INFO [ReceiverListener:hidraw3] solaar.listener: status_changed <NanoReceiver(/dev/hidraw3,11)>: present, No paired devices. (0) 
00:45:26,837     INFO [ReceiverListener:hidraw3] logitech_receiver.receiver: <NanoReceiver(/dev/hidraw3,11)>: found new device 1 (1023)
00:45:26,837     INFO [ReceiverListener:hidraw3] solaar.listener: Notification(1,41,07,122310) triggered new device <PairedDevice(1,1023,G700)> (mouse)
00:45:26,840     INFO [ReceiverListener:hidraw3] solaar.listener: status_changed <NanoReceiver(/dev/hidraw3,11)>: present, 1 paired device. (0) 
00:45:26,842  WARNING [ReceiverListener:hidraw3] logitech_receiver.notifications: 1: connection notification with unknown protocol 07: Notification(1,41,07,122310)
```

**Comment by Lekensteyn** [comment]
@Djfe I'll have a look at these in a month (hopefully).

You can also make it easier for merging by splitting the functionality and not touch unrelated parts. For example, adding new translations should not require touching all other translation files.

Oh, and reviews for all PRs are certainly welcome :-)

**Comment by Djfe** [comment]
Thx, take your time

Maybe you want to implement more than this change from this repo.

If not, then you have to ask @muzena to make a repo that cherry picks these changes that you just need to merge.

I'm not able to do it since I don't know Python, yet and don't know much about the solaar code in general (I just posted this issue)

Djfe

**Comment by teohhanhui** [comment]
I'm using G700s and would love to see it supported too :)

And would this be related as well? https://bugs.launchpad.net/ubuntu/+source/upower/+bug/1380527

(I'm not a gamer so it's only the lack of low battery notification that bugs me)

**Comment by muzena** [comment]
@Lekensteyn 
Can you commit this line: ATTRS{idVendor}=="046d", ATTRS{idProduct}=="c531", ENV{UPOWER_BATTERY_TYPE}="lg-wireless"
to http://cgit.freedesktop.org/upower/commit/?id=f8104a112eb967cd4c2aaf57b5a59aafe7c4738f
for enabling G700s/G700 battery icon and status like in picture:

![g700s](https://cloud.githubusercontent.com/assets/1978777/8236882/b00a5fbc-15eb-11e5-9442-7b77dc027e28.png)

**Comment by Lekensteyn** [comment]
@muzena I have no commit access, please propose your patch via https://bugs.freedesktop.org/enter_bug.cgi?product=upower

**Comment by EoD** [comment]
@Lekensteyn Any update on (partial) G700 support in 0.9.x?

**Comment by Lekensteyn** [comment]
@EoD The latest master should have support for the G700 Gaming Mouse, have you tried it already?

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
