### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by thureos** [pwr-Solaar/Solaar#2150]
Hey guys,

I try to donate money periodically to projects that I use on a daily basis. I noticed you don't have any "buy me a coffee" links on your GH Page, consider putting one.

Thank you for this amazing project!

**Comment by pfps** [comment]
Up until recently I could not accept payments due to my day job.   
I'll think about this - the idea would be to support obtaining more devices for testing.

**Comment by pfps** [comment]
I'm going to close this issue as there isn't a real need for funding.
