### ISSUE TITLE
Lower dbus-python requirements

### ISSUE THREAD

**Issue by m500s** [pwr-Solaar/Solaar#2154]
In setup.py, ver. 1.1.10, commit 91f1894 added
>'dbus-python (>=1.3.2)',

for el9 (rhel 9 and clones) the current version in the baseos is 1.2.18. I changed this to
>'dbus-python (>=1.2.18)',
and built and installed 1.1.10 shortly after release.

I have not come across any issues, but it's possible I may not be using whatever features require dbus-python.
I was wondering if the version could be lowered so updated epel 9 packages could be built without patching.
Thank you

P.S. this is a similar to https://github.com/pwr-Solaar/Solaar/issues/1418 with rhel8

**Comment by pfps** [comment]
dbus is only used when running under Wayland and then only for some rule features so you might not have actually tested this part of Solaar.

**Comment by m500s** [comment]
Yeah, I'm only using xorg so I can't give any more feedback here. Thanks

**Comment by pfps** [comment]
OK, closing, at least for now.
