### ISSUE TITLE
Battery status unavailable for K750

### ISSUE THREAD

**Issue by juboba** [pwr-Solaar/Solaar#216]
I just installed Solaar and everything works like a charm for my **M570**, but for my keyboard **K750** the battery status is not shown. This is too bad because I installed Solaar for checking my keyboard's battery status.

I didn't know my mouse reported the battery status (yay!). I also tried pressing the button just before running the _solar_ command with no luck.

Here's my **solaar** output:

```
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : E0EC96A2
    Firmware   : 12.01.B0019
    Bootloader : 02.14
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: (none)
  Device activity counters: 1=240, 2=13

  1: Wireless Trackball M570
     Codename     : M570
     Kind         : trackball
     Wireless PID : 1028
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: 542DF7F3
          Firmware: 26.00.B0003
        Bootloader: 02.06
             Other: 00.01
     The power switch is located on the base.
     Notifications: (none).
     Battery: 25%, discharging.

  2: Wireless Solar Keyboard K750
     Codename     : K750
     Kind         : keyboard
     Wireless PID : 4002
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: 86695385
          Firmware: RQK 33.00.B0015
        Bootloader: DFU 00.02.B0003
     The power switch is located on the edge of top right corner.
     Supports 11 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: REPROG CONTROLS        {1B00}   
         5: WIRELESS DEVICE STATUS {1D4B}   
         6: unknown:1DF3           {1DF3}   hidden
         7: FN INVERSION           {40A0}   
         8: ENCRYPTION             {4100}   
         9: SOLAR DASHBOARD        {4301}   
        10: KEYBOARD LAYOUT        {4520}   
     Has 12 reprogrammable keys:
         0: MY HOME                    => HomePage                      FN sensitive, is FN, reprogrammable
         1: Mail                       => Email                         FN sensitive, is FN, reprogrammable
         2: SEARCH                     => Search                        FN sensitive, is FN, reprogrammable
         3: Calculator                 => Calculator                    FN sensitive, is FN, reprogrammable
         4: MEDIA PLAYER               => Music                         FN sensitive, is FN, reprogrammable
         5: Previous                   => Previous                      FN sensitive, is FN
         6: Play/Pause                 => Play/Pause                    FN sensitive, is FN
         7: Next                       => Next                          FN sensitive, is FN
         8: Mute                       => Mute                          FN sensitive, is FN
         9: Volume Down                => Volume Down                   FN sensitive, is FN
        10: Volume Up                  => Volume Up                     FN sensitive, is FN
        11: SLEEP                      => Sleep                         FN sensitive, is FN, reprogrammable
     Battery status unavailable.
```

**Comment by Lekensteyn** [comment]
Is the status unavailable even when the keyboard is activated? When it goes standby, the information is possibly not reported.

Does the command `upower -d` report battery statistics for the K750?

**Comment by juboba** [comment]
This is the my output for "upower -d".
Daemon:
  daemon-version:  0.9.17
  can-suspend:     yes
  can-hibernate    yes
  on-battery:      no
  on-low-battery:  no
  lid-is-closed:   no
  lid-is-present:  no
  is-docked:       no

Running upower --monitor and pressing the 'power' button on the keyboard (the one with the happy and sad faces) doesn't produce any output.

I always try Solaar just after pressing the 'power' (faces) button and nothing.

**Comment by Lekensteyn** [comment]
UPower 0.9.17 is too old, you need at least 0.9.19 for Unifying support while 0.9.22 (or newer) is strongly recommended as it fixes quite some bugs.

As for the battery status in Solaar, perhaps the information is not available via immediate request/response queries. If you keep Solaar open for a while, does the battery status still not update?

**Comment by juboba** [comment]
Hey, I just upgraded my OS and with it my upower to version 0.9.23 and
still have the same output.

"La libertad no hace felices a los hombres, los hace sencillamente hombres."

-- Manuel Azaña

**Comment by Lekensteyn** [comment]
What OS? If you use Linux kernel 3.19 or newer you possibly have to modify a udev rule if this was not already done. http://cgit.freedesktop.org/upower/commit/?id=f8104a112eb967cd4c2aaf57b5a59aafe7c4738f

**Comment by juboba** [comment]
I want to thank you a lot for your interest in helping me. I'm using
Slackware current. I have no *-upower-csr.rules in /etc/udev/rules.d.
Should I create one?

**Comment by Lekensteyn** [comment]
You likely have one in [/usr]/lib/udev/rules.d/

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by andyforceno** [comment]
Sorry to re-open this, but I'm wondering, is there a reason why Solaar GUI would display the battery percentage but the command `solaar show` says "Battery status unavailable"? I have a K750, and I've been wanting to get my keyboard battery level when I'm not at my desk, but this requires getting it via standard output. I'm running Solaar v1.0.2.1.

**Comment by pfps** [comment]
The K750 reports its battery using a different mechanism than other devices.  I don't have the documentation for this mechanism but what I see in the Solaar code indicates that it only comes in the form of notification reports, and can't be queried directly.  (This does seem strange, but there are lots of strange things with Logitech devices.)  The Solaar GUI handles notifications, as they are needed to respond to changes in device state, but the Solaar CLI doesn't, and it would not be easy to add this capability.

**Comment by andyforceno** [comment]
Okay, thanks. Is there a way I could get the battery status (charge percentage) from the Solaar GUI notifications using Python?

**Comment by pfps** [comment]
I don't think so, unless you mean by writing code.  That  you could do.  Look in lib/logitech_receiver/notifications.py 
Putting a print statement in the section that handles SOLAR_DASHBOARD should do the trick.  There is even commented-out code that does the estimation.  YBMMV
