### ISSUE TITLE
solaar: error: Logitech receiver not found

### ISSUE THREAD

**Issue by GeorgeKontsevik** [pwr-Solaar/Solaar#2163]
Hey, I am using logitech mx master 3s mouse and ms keys s with ubuntu 20.04 LTS. I have installed solaar, but neither gui interface or cli can find my devices. However they both work fine in terms of basic actions. But many additional buttons on keyboard simply dosent work (even those that regulate the brightness of the keyboard itself). Solaar version is 1.0.1. What info I should also provide additionally so you could help me here?

**Comment by pfps** [comment]
Version 1.0.1 is very old and will not find many Logitech devices.    Please upgrade to a current version of Solaar using one of the methods described on https://github.com/pwr-Solaar/Solaar

**Comment by GeorgeKontsevik** [comment]
Thank you! I have upgraded the solaar version using pip to 1.1.10. But it still dosent show any devices.

**Comment by pfps** [comment]
Please provide output of `solaar -ddd show`

**Comment by GeorgeKontsevik** [comment]
I have a strange output: bash: /usr/bin/solaar: No such file or directory
Ran the command in a home directory

**Comment by pfps** [comment]
If you install Solaar using pip it will show up elsewhere.   I expect that bash is still remembering where Solaar was and that you need to clear out this information.  I don't use bash but the command for this may be `hash -r`.

**Comment by GeorgeKontsevik** [comment]
quick update: just needed to restart a pc, now it works, thanks
