### ISSUE TITLE
Better support for Cordless Desktop Wave (MK550) requested

### ISSUE THREAD

**Issue by janvlug** [pwr-Solaar/Solaar#2164]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): 1.1.10
- Distribution: Fedora
- Kernel version (ex. `uname -srmo`): Linux 6.5.7-200.fc38.x86_64 x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable):

<details>

```
solaar version 1.1.10

EX100 Receiver 27 Mhz
  Device path  : /dev/hidraw4
  USB id       : 046d:C517
  Serial       : None
  Has 2 paired device(s) out of a maximum of 4.
  Notifications: wireless (0x000100)

  1: Unknown device 003C
     Device path  : /dev/hidraw5
     WPID         : 003C
     Codename     : ? (003C)
     Kind         : mouse
     Protocol     : HID++ 1.0
     Serial number: 
     The power switch is located on the (unknown).
     Notifications: battery status (0x100000).
     Features: special buttons, scroll accel (0x420000)
     Battery: good, discharging.

  3: Unknown device 0060
     Device path  : /dev/hidraw6
     WPID         : 0060
     Codename     : ? (0060)
     Kind         : keyboard
     Protocol     : HID++ 1.0
     Serial number: 
     The power switch is located on the (unknown).
     Notifications: battery status (0x100000).
     Features: special buttons, scroll accel (0x420000)
     Battery: full, discharging.
```
</details>

I'm using only the keyboard of a Cordless Desktop Wave old keyboard/mouse combination.

The keyboard works fine.

But solaar shows some question marks.

Here is a file that shows some more details of this keyboard: 
[Cordless_Desktop_Wave_installation_guide_25384.1.0.pdf](https://github.com/pwr-Solaar/Solaar/files/13030320/Cordless_Desktop_Wave_installation_guide_25384.1.0.pdf)

Could you please add this model to Solaar?

Please let me know if you need more details.

Remark: The receiver always shows that both the mouse and the keyboard are connected. Which is not the case (because I only use the keyboard).

**Comment by pfps** [comment]
Solaar is mostly set up to handle newer devices.  Old devices need to be explicitly added.  And then only some of their features are supported.  Also old receivers may not report connection information in a way that Solaar can understand.

It would be possible to add information about the name of your keyboard but that would only add the name.  To add more will require downloading Solaar from this repository and running `./tools/scan-registers.sh 3` from the download directory and then posting the results here.

**Comment by pfps** [comment]
Do you still want to pursue this?

**Comment by janvlug** [comment]
YEs. Sorry, I thought I provided the requested details. I will provide them soon.

**Comment by janvlug** [comment]
I did the scan of the registers: 
[scan_registers.log](https://github.com/pwr-Solaar/Solaar/files/13228131/scan_registers.log)

**Comment by pfps** [comment]
OK.  It looks as if the mouse has no features beyond battery status but the keyboard has the ability to modify the status of the Fn key.  

I propose calling the devices "Wireless Wave Keyboard K530" and "Wireless Wave Mouse M530" and giving them ids of K530 and M530.  Does this work for you?

**Comment by janvlug** [comment]
Note that the mouse was not connected (I not use that mouse, and probably I do not even have it).

The suggested names are OK for me. Thanks for taking care of this!

**Comment by pfps** [comment]
Please try PR #2169 


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #2169, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/2169/head:pull_2169
git checkout pull_2169
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_2169
git fetch origin pull/2169/head
git reset --hard FETCH_HEAD
```

**Comment by janvlug** [comment]
Looks good:

![image](https://github.com/pwr-Solaar/Solaar/assets/5903208/0eb7e5fe-165b-4f09-8266-c12a62696dc6)

But, when I click on K550, I see in the terminal:
```
AssertionError
Traceback (most recent call last):
  File "/home/jan/Downloads/tmp/Solaar/lib/solaar/ui/window.py", line 393, in _device_selected
    _update_info_panel(device, full=True)
  File "/home/jan/Downloads/tmp/Solaar/lib/solaar/ui/window.py", line 789, in _update_info_panel
    _update_device_panel(device, _info._device, _info._buttons, full)
  File "/home/jan/Downloads/tmp/Solaar/lib/solaar/ui/window.py", line 760, in _update_device_panel
    _config_panel.update(device, is_online)
  File "/home/jan/Downloads/tmp/Solaar/lib/solaar/ui/config_panel.py", line 671, in update
    for s in device.settings:
             ^^^^^^^^^^^^^^^
  File "/home/jan/Downloads/tmp/Solaar/lib/logitech_receiver/device.py", line 337, in settings
    raise e
  File "/home/jan/Downloads/tmp/Solaar/lib/logitech_receiver/device.py", line 333, in settings
    setting = sclass.build(self)
              ^^^^^^^^^^^^^^^^^^
  File "/home/jan/Downloads/tmp/Solaar/lib/logitech_receiver/settings.py", line 229, in build
    assert rw.kind == RegisterRW.kind
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by pfps** [comment]
That looks like a problem with Solaar's expectations of how your receiver works.   There is very little documentation of this receiver so I expect that some expectation of Solaar is incorrect.

You can see both devices as active.  I think that your receiver keeps more information about the devices and thus Solaar can't tell that the device is not there.

**Comment by pfps** [comment]
Can you also run `bin/solaar show`?

**Comment by pfps** [comment]
The problem is an incorrect field in the description for your keyboard.   Please download Solaar and try again.

**Comment by janvlug** [comment]
The stacktrace is gone with the new version. All looks good.

This is the output of bin/solaar show: 
[solaar-show.log](https://github.com/pwr-Solaar/Solaar/files/13255214/solaar-show.log)

The only thing that I do not really understand is why there is a Battery level is provided for the mouse, even when I do not have that mouse at all. But this looks way better than it was. Thanks!

**Comment by pfps** [comment]
It is likely that the battery information is cached in the receiver, for this old style of receiver.  Newer receivers work differently.
