### ISSUE TITLE
Logitech K350 does not support Solaar key diversion rules

### ISSUE THREAD

**Issue by 2ashishs** [pwr-Solaar/Solaar#2167]
**Information**
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.9+dfsg-1
- Distribution: Ubuntu Budgie23.10
- Kernel version (ex. `uname -srmo`): `6.5.0-10-generic`
- Output of `solaar show`:

<details>

```
solaar version 1.1.9+dfsg-1

Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:C52B
  Serial       : EEF7983F
    Firmware   : 12.11.B0032
    Bootloader : 04.16
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

  2: Wireless Wave Keyboard K350
     Device path  : /dev/hidraw1
     WPID         : 200A
     Codename     : K350
     Kind         : keyboard
     Protocol     : HID++ 1.0
     Polling rate : 20 ms (50Hz)
     Serial number: 034D7751
          Firmware: 65.00.B0003
             Other: 00.01
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Features: (none)
     Battery: full, discharging.
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
No such file or directory
```
</details>

- Errors or warrnings from Solaar:
N/A

**Describe the bug**
I tried to add a new rule for the Logitech K350 keyboard, for action on  pressing `Application Switcher` or `Zoom` programmable keys.
Solaar does not recognize those keys.

**To Reproduce**
1. Rules Editor -> New User-defined Rule -> On Action -> Keypress
2. Press `Application Switcher` or `Zoom` programmable keys
3. Solaar does not recognize.

**Screenshots**
N/A

**Additional context**
Problem could potentially be due to Linux not recognizing the key-events.
But from the information I gathered, it was suggested that Solaar could help with that.

**Comment by pfps** [comment]
Solaar can only run rules on diverted keys.  The keys that can be diverted depend on the keyboard.  It appears that the K350 is too old to have the ability to divert any keys.

**Comment by pfps** [comment]
Is there anything more that needs to be done here?

**Comment by 2ashishs** [comment]
No, thanks! You may close the ticket.
