### ISSUE TITLE
Support for logitech new K380s

### ISSUE THREAD

**Issue by menon92** [pwr-Solaar/Solaar#2170]
Thanks for this awesome work. Does it support Logitech [K380S](https://www.logitech.com/en-us/products/keyboards/pebble-keys-2.920-011775.html) I checked the docs it says `Compatible with Logi Bolt USB receiver`

If it's not support how to add this support? 

Please let me know if you need any other information form my side

Thanks.  

**Information**

- Solaar version (`solaar --version` and `git describe --tags`):
- Distribution: Ubuntu 20.04 LTS
- Kernel version (ex. `uname -srmo`):
- Output of `solaar show` for the target device (if applicable):

<details>

```
OUTPUT HERE
```
</details>

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pfps** [comment]
It should work with no changes to Solaar, at least for all the features that Solaar supports.

**Comment by menon92** [comment]
@pfps Thanks for your reply. Today I bought a k380s but I'm unable to connect it using my Logitech USB receiver

**Comment by pfps** [comment]
It appears that this keyboard is only compatible with Bolt receivers so first make sure that you have a Bolt receiver, not a Unifying receiver.  If a Bolt receiver is connected to your system Solaar should show it both in the GUI and in `solaar show` even if there are no connected devices.  You can post the output of `solaar show` if you need more help.

**Comment by menon92** [comment]
@pfps I have [logi bolt USB receiver](https://www.logitech.com/en-us/products/mice/logi-bolt-usb-receiver.956-000007.html] and my Logitech `M650` mouse is connected using this bolt receiver. But Solaar is unable to detect the bolt USB. Here is solaar show the output
```sh
solaar: error: Logitech receiver not found
```
I run the `lsusb` command and get the bolt receiver
```sh
Bus 003 Device 013: ID 046d:c548 Logitech, Inc. USB Receiver
```

**Comment by pfps** [comment]
Which version of Solaar are you using.

**Comment by menon92** [comment]
```
solaar 1.0.1
```

**Comment by menon92** [comment]
@pfps Thanks for your help. After upgrading the solaar to `solaar 1.1.8` I'm able to connect my `K380S` keyboard. I upgraded the solar using
```
sudo add-apt-repository ppa:solaar-unifying/stable
sudo apt update
sudo apt install solaar
```
