### ISSUE TITLE
G535 battery information

### ISSUE THREAD

**Issue by josinaldobarbosa** [pwr-Solaar/Solaar#2172]
**Information**
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.9+git2025-4160b0e
- Distribution: Linux Mint 20.3 Cinnamon
- Kernel version (ex. `uname -srmo`): Linux 5.4.0-166-generic x86_64 GNU/Linux
- Output of `solaar show`: 

(This information was after using the headset for a while)

```
solaar version 1.1.9+git2025-4160b0e

USB and Bluetooth Devices

  1: G535 Gaming Headset
     Device path  : /dev/hidraw0
     USB id       : 046d:0AC4
     Codename     : G535 Headset
     Kind         : headset
     Protocol     : HID++ 4.2
     Serial number: 
     Model ID:      000000000AC4
     Unit ID:       FFFFFFFF
          Firmware: U1  90.00.B0200
     Supports 6 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: Firmware U1  90.00.B0200 0AC4
            Unit ID: FFFFFFFF  Model ID: 000000000AC4  Transport IDs: {'btid': '0000', 'btleid': '0000'}
         3: DEVICE NAME            {0005} V0     
            Name: G535 Wireless Gaming Headset
            Kind: None
         4: SIDETONE               {8300} V0     
            Sidetone (saved): 0
            Sidetone        : 0
         5: ADC MEASUREMENT        {1F20} V3     
            Battery: 90% 4135mV , discharging.
            Power Management (saved): 30
            Power Management        : 30
     Battery: 90% 4131mV , discharging.
```

**Describe the bug**
The battery value does not seem correct to me, after leaving it for several hours charging it does not reach 100%, the headset is new, 1 week of use.

**Screenshots**
![Captura de tela de 2023-11-04 19-33-08](https://github.com/pwr-Solaar/Solaar/assets/8990316/e6c48cdf-d66e-4f0e-8601-2a316341fa20)

**Comment by pfps** [comment]
The percentage that Solaar reports is taken by indexing the voltage into an array of voltages for a idealized Logitech battery, and one that may be different from the model in this device.   Further, even if the voltage array is correct for the battery model, individual batteries will be slighting different and may degrade over time.  This device does not report percentages at all.  

So take the percentage that Solaar reports as an estimate.

**Comment by josinaldobarbosa** [comment]
understood, just for comparison purposes I tested it on Windows and it was displayed correctly
![Sem título](https://github.com/pwr-Solaar/Solaar/assets/8990316/7f0970d0-f04c-41b7-a294-76fadc00904a)
as I can't be more precise, thank you for the answer and the project.
