### ISSUE TITLE
Potential issues with Wave Keys

### ISSUE THREAD

**Issue by skerit** [pwr-Solaar/Solaar#2175]
- Solaar version: solaar 1.1.10
- Distribution: Endeavour Linux
- Kernel version (ex. `uname -srmo`): Linux 6.5.9-zen2-1-zen x86_64 GNU/Linux

Just a heads up for people wanting to use Wave Keys keyboard: Solaar seems to become really sluggish when a Bolt receiver is paired with a Wave Keys keyboard.

This doesn't seem to be an issue exclusive to Solaar on Linux: the keyboard is actually my husband's. He was trying to use the Wave Keys on his Macbook. As soon as he paired it, the custom tool he uses to modify his mouse's behaviour went nuts.

In the end Solaar was the only tool that managed to remove the pairing from his Bolt receivers (he tried it on 2 different Bolt receivers)

**Comment by pfps** [comment]
It could be helpful to post the output of `solaar -ddd` when the keyboard is active.   That might show that there is a lot of extraneous communication.

**Comment by pfps** [comment]
Closing as not likely a bug.
