### ISSUE TITLE
70mb used RAM in idle mode (RSS)

### ISSUE THREAD

**Issue by Djfe** [pwr-Solaar/Solaar#218]
according to my taskmanager solaar uses 72,4mib of RAM right now, even though no windows is open and even though it hasn't recognized my mouse receiver, yet.

Why does it use so much RAM?

Could the RAM usage be reduced somehow? (It's not like it matters too much, but 70mib sound still a bit much too me for this functionality :/ )

**Comment by Lekensteyn** [comment]
Sounds like a memory leak, this needs some debugging.

**Comment by krassswr** [comment]
I have same problem it uses 44.3mb RAM. My system is Debian Testing, Python 2.7.10rc1, xfce4.12, solaar-cli 0.9.2 -debian version : 0.9.2+dfsg-5

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by krassswr** [comment]
Now I use version 1.0.1 and used RAM is 19.3 MB so I think that we can close this issue now.
