### ISSUE TITLE
impossible to add mx key

### ISSUE THREAD

**Issue by micker** [pwr-Solaar/Solaar#2182]
Hello i have a mx master 3 and mxkey on ubuntu 23.10
i add 1.1.9+dfsg-1
when i add my keyboard that doesn't works ...
![image](https://github.com/pwr-Solaar/Solaar/assets/2539440/afae8492-bc7e-40ca-948d-d6d7c5f5c952)
i try to use channel button to add it noting
i try to sutdown my keyboard and use add new  button and start my kyboard ...
i already have k350 and not mx
if use native bluethoos it works but i have a by delay on tips ... and strange display
![image](https://github.com/pwr-Solaar/Solaar/assets/2539440/3ab95c98-80d3-43c9-9ee0-f9cb0885272d)

**Information**

- Solaar version (1.1.9+dfsg-1
- Distribution ubuntu 23.10
- Kernel version Linux 6.5.0-13-generic x86_64 GNU/Linux
![image](https://github.com/pwr-Solaar/Solaar/assets/2539440/70009b60-affb-40ea-a54b-895adfc7b179)

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
- 1.1.9+dfsg-1
- _NAME: Wireless Mouse M215
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: 4347FCC9
  _wpid: '1020'
- _NAME: Wireless Wave Keyboard K350
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: '00000000'
  _wpid: 200A
- _NAME: Wireless Mouse M215
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: 117CA1BA
  _wpid: '1020'
- _NAME: MX Master 3 Wireless Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer, adc_power_management]
  _battery: 0
  _modelId: B02340820000
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: 117CA1BA
  _unitId: 117CA1BA
  _wpid: '4082'
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 0, 196: 0}
  dpi: 1000
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}
  scroll-ratchet: 1
  smart-shift: 1
  thumb-scroll-invert: false
  thumb-scroll-mode: false
- _NAME: MX Keys Keyboard
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, pointer_speed, dpi, speed-change, backlight-timed, reprogrammable-keys, persistent-remappable-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4096
  _modelId: B35B408A0000
  _sensitive: {backlight: true, hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _unitId: F798096F
  backlight: true
  change-host: null
  disable-keyboard-keys: {1: false, 2: false, 4: false, 8: false, 16: false}
  divert-keys: {10: 0, 110: 0, 111: 0, 191: 0, 199: 0, 200: 0, 209: 0, 210: 0, 211: 0, 224: 0, 225: 0, 226: 0, 227: 0, 228: 0, 229: 0, 230: 0, 231: 0, 232: 0,
    233: 0, 234: 0, 235: 0, 236: 0}
  fn-swap: true
  multiplatform: 0
```
</details>

thanks for any help

**Comment by pfps** [comment]
Please provide all the information requested in the bug report template.

**Comment by micker** [comment]
hope that is better

**Comment by pfps** [comment]
The bug report template also asks for the output of `solaar show`.

**Comment by micker** [comment]
Sorry forgot
<details>
`solaar version 1.1.9+dfsg-1

Récepteur Nano
  Device path  : /dev/hidraw1
  USB id       : 046d:C52F
  Serial       : 1A009D37
    Firmware   : 22.00.B0005
  Has 1 paired device(s) out of a maximum of 1.
  Has 38 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)

  1: MX Master 3 Wireless Mouse
     Device path  : /dev/hidraw2
     WPID         : 4082
     Codename     : MX Master 3
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 117CA1BA
     Model ID:      B02340820000
     Unit ID:       117CA1BA
        Bootloader: BOT 95.00.B0013
          Firmware: MPM 19.01.B0015
             Other: 
     The power switch is located on the base.
     Supports 35 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V3     
            Firmware: Bootloader BOT 95.00.B0013 0000D8279515
            Firmware: Firmware MPM 19.01.B0015 40826A9CA89D
            Firmware: Other   
            Unit ID: 117CA1BA  Model ID: B02340820000  Transport IDs: {'btleid': 'B023', 'wpid': '4082'}
         3: DEVICE NAME            {0005} V0     
            Name: Wireless Mouse MX Master 3
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
         6: CRYPTO ID              {0021} V1     
         7: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Master 3
         8: BATTERY STATUS         {1000} V1     
            Battery status unavailable.
         9: REPROG CONTROLS V4     {1B04} V4     
            Actions des boutons (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Actions des boutons        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, Mouse Gesture Button:Gesture Button Navigation, Smart Shift:Smart Shift}
            Affectation des boutons (saved): {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Regular, Smart Shift:Regular}
            Affectation des boutons        : {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, Mouse Gesture Button:Regular, Smart Shift:Regular}
        10: CHANGE HOST            {1814} V1     
            Changer d'hôte        : 2:yannick-01
        11: XY STATS               {2250} V1     
        12: ADJUSTABLE DPI         {2201} V1     
            Sensibilité (DPI) (saved): 1000
            Sensibilité (DPI)        : 1000
        13: SMART SHIFT            {2110} V0     
            Scroll Wheel Ratcheted (saved): Freespinning
            Scroll Wheel Ratcheted        : Freespinning
            Scroll Wheel Ratchet Speed (saved): 1
            Scroll Wheel Ratchet Speed        : 1
        14: HIRES WHEEL            {2121} V1     
            Multiplier: 15
            Has invert: Normal wheel motion
            Has ratchet switch: Free wheel mode
            High resolution mode
            HID notification
            Direction de la mollette (saved): False
            Direction de la mollette        : False
            Résolution de la mollette (saved): True
            Résolution de la mollette        : True
            Affectation de la molette (saved): False
            Affectation de la molette        : False
        15: THUMB WHEEL            {2150} V0     
            Direction de la molette de pouce (saved): False
            Direction de la molette de pouce        : False
            Affectation de la molette de pouce (saved): False
            Affectation de la molette de pouce        : False
        16: WHEEL STATS            {2251} V0     
        17: DFUCONTROL SIGNED      {00C2} V0     
        18: DEVICE RESET           {1802} V0    internal, hidden 
        19: unknown:1803           {1803} V0    internal, hidden 
        20: CONFIG DEVICE PROPS    {1806} V6    internal, hidden 
        21: unknown:1813           {1813} V0    internal, hidden 
        22: OOBSTATE               {1805} V0    internal, hidden 
        23: unknown:1830           {1830} V0    internal, hidden 
        24: unknown:1890           {1890} V5    internal, hidden 
        25: unknown:1891           {1891} V5    internal, hidden 
        26: unknown:18A1           {18A1} V0    internal, hidden 
        27: unknown:1DF3           {1DF3} V0    internal, hidden 
        28: unknown:1E00           {1E00} V0    hidden 
        29: unknown:1EB0           {1EB0} V0    internal, hidden 
        30: unknown:1861           {1861} V0    internal, hidden 
        31: unknown:9001           {9001} V0    internal, hidden 
        32: unknown:9203           {9203} V0    internal, hidden 
        33: unknown:9205           {9205} V0    internal, hidden 
        34: unknown:9300           {9300} V0    internal, hidden 
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, analytics key events, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Mouse Gesture Button      , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Battery status unavailable.

USB and Bluetooth Devices

  1: MX Keys Keyboard
     Device path  : /dev/hidraw4
     USB id       : 046d:B35B
     Codename     : MX Keys
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Serial number: 
     Model ID:      B35B408A0000
     Unit ID:       F798096F
        Bootloader: BL1 08.00.B0011
          Firmware: MPK 12.01.B0013
             Other: 
     Supports 30 HID++ 2.0 features:


</details>

**Comment by pfps** [comment]
Solaar lists your receiver as a Nano Receiver.   Nano Receivers have limited functionality, and can only pair with some devices.

Does your receiver have the Logitech Unifying logo on it?  If so, Solaar may be wrong about this receiver.   There appears to be something wrong in any case, as there are two devices connected to the receiver but `solaar show` lists only one.

What you can do is scan the registers of your receiver.  If you clone Solaar you can then run `./tools/scan-registers.sh ff /dev/hidraw1` from there and post the result.  That will show information about the receiver.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```

**Comment by micker** [comment]
maybe my bluethoss is limited ... (its an old laptop)
very very strange

**Comment by pfps** [comment]
Is there anything more to do here?
