### ISSUE TITLE
Add the 'Mouse Gesture Button' to 'Persistent Key/Button Mapping" setting

### ISSUE THREAD

**Issue by SmiggyCC** [pwr-Solaar/Solaar#2198]
Is there a way to have the Mouse Gesture Button that's on something like the MX Master 3 to behave like one of the buttons that would be under the Persistent Key/Button Mapping? I like to map Escape to this button but find it very annoying to try and work out on my MX Master 3 as opposed to my M720 Triathlon, I only need to find the Multiplatform Gesture Button & map Escape to it. If I want to do this on an MX Master 3 I have to set up rules for the Gesture Button but even then there's a delay for some reason & ceases movement  until I let go which is very annoying.

So in total
Way to make Gesture button on devices such as the MX Master 3 behave like a normal remappable button or add key stroke input option in 'Key/Button Diversion' to Mouse Gesture Button

**Comment by pfps** [comment]
That is the *only* option as your device does not have the feature necessary to do what you want in the device itself.

**Comment by pfps** [comment]
Closing as this is a limitation of the device.
