### ISSUE TITLE
The list of supported devices on the website is outdated

### ISSUE THREAD

**Issue by denilsonsa** [pwr-Solaar/Solaar#2199]
When I look at the [official website](https://pwr-solaar.github.io/Solaar/) for this project, there is a page with a listed of supported devices: https://pwr-solaar.github.io/Solaar/devices

However, I believe that page is outdated. I found issue #786 adding support for Logitech G613, but that keyboard is nowhere to be found on that page. Thus, I'm assuming there are more supported devices than those listed on that page.

The solution is, of course, to update the page. If that's a manual operation, it could be better to have some code to auto-generate the page from the list of supported devices from the source-code. (I'm assuming the source-code has a list of devices somewhere.)

**Comment by pfps** [comment]
From https://pwr-solaar.github.io/Solaar/devices

> The device tables below provide a list of some of the devices that Solaar supports, giving their product name, WPID product number, and HID++ protocol information. The tables concentrate on older devices that have explicit support information in Solaar and are not being updated for new devices that are supported by Solaar.

From the same page

> The directory https://github.com/pwr-Solaar/Solaar/tree/master/docs/devices contains edited output of solaar show on many devices and can be used to see what Solaar can do with the device.

The Solaar code does not have a list of supported devices.  Again from that page

> Most new HID++ devices do not need to be known to Solaar to work. You should be able to just run Solaar and the device will show up.

**Comment by denilsonsa** [comment]
That's what I get by just skimming through the page without reading it. 🙄 I just wanted to check the compatibility with one specific keyboard. (Because I was considering if I should buy it second-hand or not. For this use-case, I cannot just plug the keyboard because I don't have it yet.)

But this also highlights that an incomplete list of the supported devices is more confusing to the user. Maybe those tables should be generated from the list of files in that directory.

Thanks for your response. I'm just giving some feedback as someone from outside the Solaar project.

**Comment by pfps** [comment]
The directory of supported devices is also incomplete.

There are certainly devices that have been used in Solaar for which there is no information at all on the Solaar pages.  Nor is there good information from Logitech which devices are compatible with Solaar.  About the only way of determining whether a device not-in-hand can be supported is to find out which receiver it uses, especially if it uses a Unifying or Bolt receiver.
