### ISSUE TITLE
devices with 0 modelId and unitId result in multiple config.yaml entries

### ISSUE THREAD

**Issue by pfps** [pwr-Solaar/Solaar#2202]
See #2201, where the problem occurs.

@Jerther This is the issue for your config.yaml file with multiple entries for a K810 keyboard.

**Comment by Jerther** [comment]
To answer your question on the other issue, I only have 4 devices. Sometimes I use Solaar to program Unifying dongles for work but that's it.

**Comment by Jerther** [comment]
About the K810, If that can be of any help, here's what usually happens. I have a K380 at work, and a K810 at home so I switch between the two keyboards every week. Both keyboards can be paired with up to three devices. The K380 is only paired with one computer (work), and the K810 is paired with my work computer and my personal computer. Lots of things happen between my personal computer and the K810, but the pairing between the K810 and my work computer has been stable for months.

**Comment by pfps** [comment]
OK.  It may be that Solaar is or was creating a new entry for your K810 each time Solaar was started up.  Please remove all the entries for a K810 in your config.yaml file (or just delete the file).  Then run Solaar with the K810 active.  Next quit out of Solaar and start it up again.  Post the resulting config.yaml file.

**Comment by pfps** [comment]
@Jerther  Do you have an Illuminated Keyboard K810 available?  I would like to fix the problem with it showing up multiple times in config.yaml.  If you do, please run `solaar show` with the keyboard connected and active.

**Comment by Jerther** [comment]
Yes I do, but I'll be able to access it only sometime in the next few days. Probably tomorrow. I'll follow up then.

**Comment by pfps** [comment]
OK.  Thanks.

**Comment by Jerther** [comment]
Here
[config.zip](https://github.com/pwr-Solaar/Solaar/files/13685488/config.zip)

- Delete config.yaml
- Make sure the K810 is connected
- Start Solaar
- Quit Solaar
- Start Solaar
- Quit Solaar

**Comment by pfps** [comment]
OK.  The current version of Solaar already has a way of dealing with devices whose modelId and unitId are zero.  So there is no bug after all.
