### ISSUE TITLE
Support G195 keyboard in wireless mode

### ISSUE THREAD

**Issue by elirasza** [pwr-Solaar/Solaar#2204]
**Information**

- **Solaar version :** 1.1.10
- **Distribution :** Archlinux
- **Kernel version :** Linux 6.6.7-arch1-1 x86_64 GNU/Linux
- `solaar show` outputs

<details>
```
solaar: error: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/solaar/cli/__init__.py", line 206, in run
    raise Exception(
Exception: No supported device found.  Use "lsusb" and "bluetoothctl devices Connected" to list connected devices.
```
</details>

**Is your feature request related to a problem? Please describe.**
I would like to use solaar with my G195 keyboard. It is not the TKL version, but the "LIGHTSPEED Wireless RGB". Solaar recognizes it when connected with its micro-USB cable, but not when it is connection with its wireless dongle.

**Describe the solution you'd like**
To be able to configure the keyboard and have information on its battery level.

**Describe alternatives you've considered**
None

**Additional context**
According to the documentation process, here are the hidraw files. Oddly, they have two of them with the same signature, but in the descriptor files, we can the first one is considered as a mouse and the second one as a keyboard. I do not have a Logitech mouse but a Roccat one which already have its own hidraw path. You will also find the lsusb output.

[input0.txt](https://github.com/pwr-Solaar/Solaar/files/13743371/input0.txt)
[input0_descriptor.txt](https://github.com/pwr-Solaar/Solaar/files/13743370/input0_descriptor.txt)
[input1.txt](https://github.com/pwr-Solaar/Solaar/files/13743373/input1.txt)
[input1_descriptor.txt](https://github.com/pwr-Solaar/Solaar/files/13743372/input1_descriptor.txt)
[usb.txt](https://github.com/pwr-Solaar/Solaar/files/13743375/usb.txt)

**Comment by pfps** [comment]
Please provide output of `solaar show` when then keyboard is connected via USB.

**Comment by elirasza** [comment]
Here it is : [show.txt](https://github.com/pwr-Solaar/Solaar/files/13744025/show.txt)

**Comment by pfps** [comment]
I'm not sure that the descriptor files correspond to the keyboard.  

Can you start up the Solaar GUI as `solaar -ddd` with the receiver unplugged.  Then pug in the receiver and connect the keyboard to it.   Post the output from Solaar.

As far as I can tell Solaar has had support for this receiver since mid-2021.

**Comment by elirasza** [comment]
Here is is : [debug.txt](https://github.com/pwr-Solaar/Solaar/files/13746188/debug.txt)

When I plugged the receiver while solaar was up, it recognized it as "Lightspeed receiver". It never happened before.

**Comment by pfps** [comment]
Thanks.  It appears that this receiver works differently from other receivers and tries to contact the device for information that other receivers store locally.  As a result some information that Solaar expects to always be available is not and the device may not be set up correctly.

I have made a couple of patches to Solaar to paper over some of these situations.  Please download and run PR #2206.  This is likely not a complete fix.   Please run `bin/solaar -ddd` from the download directory and post the output.   If possible continue until both the receiver and keyboard show up in the Solaar main window.  You may have to toggle the power off and on on the keyboard for the keyboard to show up.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #2206, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/2206/head:pull_2206
git checkout pull_2206
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_2206
git fetch origin pull/2206/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
Also, please post the output of `solaar show` when the keyboard is connected via the receiver.  Also post the output of `solaar -ddd show` for the same situation.

**Comment by elirasza** [comment]
The PR worked like a charm, but your first advice (plugging out and in back the receiver) also seemed to work pretty well, so it may be a false positive. That being said, it detected my keyboard way faster and with more reliability than before.

Here you are :

- output of `solaar -ddd` [ddd.txt](https://github.com/pwr-Solaar/Solaar/files/13761907/ddd.txt)
- output of `solaar show` [show.txt](https://github.com/pwr-Solaar/Solaar/files/13761910/show.txt)
- output of `solaar -ddd show` [show_ddd.txt](https://github.com/pwr-Solaar/Solaar/files/13761914/show_ddd.txt)

**Comment by pfps** [comment]
OK, I'm declaring victory here.

**Comment by elirasza** [comment]
Thank you very much ! And GG :D
