### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by PeaceNira** [pwr-Solaar/Solaar#2205]
- Solaar version: 1.1.10
- Distribution: Fedora 39
- Kernel version: Linux 6.6.7-200.fc39.x86_64 x86_64 GNU/Linux

**Is your feature request related to a problem? Please describe.**
Adding a dark theme

**Describe the solution you'd like**
A toggle to enable "dark" mode to reduce eye strain

**Describe alternatives you've considered**
None?

**Additional context**
Willing to attempt to implement it myself

**Comment by pfps** [comment]
Feel free to work on this yourself.    Ideally there should be no code in Solaar that is specific to dark mode, with Solaar just using CSS it inherits.

**Comment by pfps** [comment]
If I switch Gtk theme from Adwaita to Adwaita-dark, Solaar switches to dark mode.  You should be able to do this as well.
