### ISSUE TITLE
[ICON][GNOME] Missing tray icon on bazzite

### ISSUE THREAD

**Issue by cmalvi** [pwr-Solaar/Solaar#2212]
Solaar runs inside a distrobox container (fedora).

- Solaar version 1.1.10
- Distribution: Fedora Silverblue (Bazzite)

It throws errors about icons not available in current theme.
On host system i'm using the stock theme. 

**Screenshots**
![image](https://github.com/pwr-Solaar/Solaar/assets/76235393/8ccb6b3b-606f-456d-8609-fe5f802abe1b)

**Comment by pfps** [comment]
Solaar looks in the usual places for usual icons.  I run Fedora and Solaar has no problem finding icons.   They should be under /usr/share/icons.  Look for files named 'battery-*' and 'solaar-*'.

My Fedora laptop has `/usr/share/icons/hicolor/scalable/apps/solaar-symbolic.svg`, `/usr/share/icons/hicolor/scalable/status/battery-good.svg`, and many other battery icons.

**Comment by cmalvi** [comment]
So maybe the problem is how the distrobox container handle it. Do you know if is possible to symlink host icons path so the container can access it?

**Comment by pfps** [comment]
No idea, sorry.
