### ISSUE TITLE
POP mouse is not on the compatibility list yet works (as far as I can tell) pretty much flawlessly 

### ISSUE THREAD

**Issue by TheMaroonHatHacker** [pwr-Solaar/Solaar#2216]
Just wondering if the compatibility list could be updated to include the POP mouse, as all solaar's functions work with this mouse.

**Comment by pfps** [comment]
As stated on that page, the list is incomplete.   For many devices, Solaar does not need any information about the device to support it, so there is no reason to have the list complete.
