### ISSUE TITLE
Help for edit rule configuration

### ISSUE THREAD

**Issue by salvatorebuono02** [pwr-Solaar/Solaar#2217]
Hi, 
I am having problems with the logitech M650L mouse. Specifically I want the 8 and 9 buttons (found using the **xev** command) to be mapped to **Ctrl+Alt+Left** and **Ctrl+Alt+Right**, which are Ubuntu's (22.04) shortcuts for switching between desktops. I have tried defining this set of rules, I have installed the Gnome extension of solaar but nothing seems to work. Can anyone help me?

![Schermata del 2024-01-11 18-37-43](https://github.com/pwr-Solaar/Solaar/assets/79745115/9d7363b6-f451-48c4-af7f-20622d07ea02)

**Comment by pfps** [comment]
Have you diverted the buttons?  Provide output of `solaar show`.

**Comment by salvatorebuono02** [comment]
Solaar version 1.1.1

Bolt Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:C548
  Serial       : 44344535433632334537453142373935
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 2=78

  2: Signature M650 L Mouse
     Device path  : None
     WPID         : B02A
     Codename     : Logi M650 L
     Kind         : mouse
     Protocol     : HID++ 4.5
     Serial number: 06CB6DD0
     Model ID:      B02A00000000
     Unit ID:       06CB6DD0
        Bootloader: BL1 38.02.B0013
          Firmware: RBM 16.02.B0013
             Other: 
     The power switch is located on the (unknown).
     Supports 30 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BL1 38.02.B0013 B02AB0706FCD
            Firmware: Firmware RBM 16.02.B0013 B02AB0706FCD
            Firmware: Other   
            Unit ID: 06CB6DD0  Model ID: B02A00000000  Transport IDs: {'btleid': 'B02A'}
         3: DEVICE NAME            {0005}   
            Name: Signature M650 L Mouse
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: DEVICE FRIENDLY NAME   {0007}   
            Friendly Name: Logi M650 L
         7: UNIFIED BATTERY        {1004}   
         8: REPROG CONTROLS V4     {1B04}   
            Azioni tasto/pulsante (saved): {'82': 82, '83': 83, '86': 86}
            Azioni tasto/pulsante        : {'82': 82, '83': 83, '86': 86}
            Key/Button Diversion (saved): {'82': 0, '83': 0, '86': 0}
            Key/Button Diversion        : {'82': 0, '83': 0, '86': 0}
         9: HOSTS INFO             {1815}   
            Host 0 (paired): salvatore-Inspiron-5515
        10: XY STATS               {2250}   
        11: LOWRES WHEEL           {2130}   
            Wheel Reports: HID
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
        12: ADJUSTABLE DPI         {2201}   
            Sensibilità (DPI) (saved): 1000
            Sensibilità (DPI)        : 1000
        13: unknown:00C3           {00C3}   
        14: DEVICE RESET           {1802}   internal, hidden, unknown:000010
        15: unknown:1803           {1803}   internal, hidden, unknown:000010
        16: CONFIG DEVICE PROPS    {1806}   internal, hidden, unknown:000010
        17: unknown:1816           {1816}   internal, hidden, unknown:000010
        18: OOBSTATE               {1805}   internal, hidden
        19: unknown:1830           {1830}   internal, hidden, unknown:000010
        20: unknown:1891           {1891}   internal, hidden, unknown:000008
        21: unknown:18A1           {18A1}   internal, hidden, unknown:000010
        22: unknown:1E00           {1E00}   hidden
        23: unknown:1E02           {1E02}   internal, hidden
        24: unknown:1E22           {1E22}   internal, hidden, unknown:000010
        25: unknown:1602           {1602}   
        26: unknown:1EB0           {1EB0}   internal, hidden, unknown:000010
        27: unknown:1861           {1861}   internal, hidden, unknown:000010
        28: unknown:18B1           {18B1}   internal, hidden, unknown:000010
        29: unknown:920A           {920A}   internal, hidden, unknown:000010
     Has 6 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, analytics key events, pos:0, group:1, group mask:empty
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, analytics key events, pos:0, group:1, group mask:empty
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, analytics key events, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, analytics key events, unknown:000800, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, analytics key events, unknown:000800, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Battery: 80%, discharging.

**Comment by pfps** [comment]
Version 1.1.1 is old.  I suggest updating.

As stated in the Solaar rules documentation:
> Solaar’s rules only trigger on HID++ notifications so device actions that normally produce HID output have to be first be set (diverted) to produce HID++ notifications instead of their normal behavior. Currently Solaar can divert some mouse scroll wheels, some mouse thumb wheels, the crown of Craft keyboards, and some keys and buttons. If the scroll wheel, thumb wheel, crown, key, or button is not diverted by setting the appropriate setting then no HID++ notification is generated and rules will not be triggered by manipulating the wheel, crown, key, or button. Look for HID++ or Diversion settings to see what diversion can be done with your devices.

The only divertable buttons on your mouse are the middle, back, and forward buttons.  So rule can only trigger on these buttons, and only if they are diverted.   Your mouse does not have a crown so there is no utility in rules that trigger on crown events.

**Comment by salvatorebuono02** [comment]
I downloaded solaar from ubuntu store and it hasn't any update yet. How can I map the back button with Ctrl+Alt+Left?

**Comment by salvatorebuono02** [comment]
ok I've updated to version 1.1.8 and defined following rules, but it does not work. 
![immagine](https://github.com/pwr-Solaar/Solaar/assets/79745115/55f062bf-3a25-4f14-9b74-74b24a46a29a)

**Comment by pfps** [comment]
You have to divert the button using Solaar before the device will produce anything that Solaar rules can see.

**Comment by salvatorebuono02** [comment]
How can I do it?

**Comment by pfps** [comment]
Use Solaar - there should be a Key/Button Diversion setting that can be used to divert those keys and buttons that can be diverted.

**Comment by salvatorebuono02** [comment]
ok done and then? rules are not working

**Comment by pfps** [comment]
Not working as in not being triggered at all?  Or not working in that desktop switching is not happening?

If you run Solaar as `solaar -ddd` there will be lots of debugging output produced.   This included the triggering of rules and what actions they are performing.

My suspicion is that you are running Wayland and have not set up permissions for /dev/uinput.  This is described in the Solaar rules documentation.

**Comment by salvatorebuono02** [comment]
This is the output:
2024-01-12 16:58:14,683,683     INFO [MainThread] root: language it_IT (UTF-8), translations path None
2024-01-12 16:58:14,815,815     INFO [MainThread] logitech_receiver.diversion: GDK Keymap set up
2024-01-12 16:58:14,816,816  WARNING [MainThread] logitech_receiver.diversion: rules cannot access active process or modifier keys in Wayland
2024-01-12 16:58:14,816,816  WARNING [MainThread] logitech_receiver.diversion: cannot create uinput device: "/dev/uinput" cannot be opened for writing
2024-01-12 16:58:14,818,818    DEBUG [MainThread] logitech_receiver.diversion: load rule: Rule(/home/salvatore/.config/solaar/rules.yaml)[Rule[Key: Back Button Short Press (pressed), KeyPress: Control_L Alt_L Left click], Rule[Key: Forward Button (pressed), KeyPress: Control_L Alt_L Right click]]
2024-01-12 16:58:14,818,818     INFO [MainThread] logitech_receiver.diversion: loaded 1 rules from /home/salvatore/.config/solaar/rules.yaml
2024-01-12 16:58:14,827,827    DEBUG [MainThread] solaar.ui.tray: using AppIndicator3
2024-01-12 16:58:14,833,833     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
Another Solaar process is already running so just expose its window

**Comment by pfps** [comment]
```
2024-01-12 16:58:14,816,816 WARNING [MainThread] logitech_receiver.diversion: cannot create uinput device: "/dev/uinput" cannot be opened for writing
```

You need to follow the steps in the rules documentation to set up permissions for /dev/uinput.

Also, if Solaar is already running, running it a second time will not change its behaviour.  You need to kill the running Solaar and start a new one with debugging turned on.

**Comment by pfps** [comment]
If you have the uninput rule installed then it needs to run, which can be done by rebooting.

You can check permissions in /dev/uinput using getfacl, as in:

```
idefix disjoint> getfacl /dev/uinput
getfacl: Removing leading '/' from absolute path names
# file: dev/uinput
# owner: root
# group: root
user::rw-
user:pfps:rw-
group::---
mask::rw-
other::---
```

Note that user::pfps has rw permissions.   If getfacl doesn't have such a line for your userid then the Solaar uinput rule hasn't run.

**Comment by salvatorebuono02** [comment]
Yes, you are right I did not copy the file in /etc/udev/rules.d . Now it is working thank you
