### ISSUE TITLE
How to use "depress" and "release" option in KeyPress action in Rule Editor? 

### ISSUE THREAD

**Issue by AugustineYang** [pwr-Solaar/Solaar#2218]
Hi! I'm trying to make a rule to simultaneously press "Control" button of the keyboard and click the left button of the mouse. In [the instruction of creating and editing rules](https://pwr-solaar.github.io/Solaar/rules.html), you mentioned that "A KeyPress action takes either ..., or a two-element list with the first element as above and the second element one of ‘click’, ‘depress’, or ‘release’ and executes key actions on a simulated keyboard to produce these symbols." Could you provide more information on this? Thanks for your reply! 
![截图 2024-01-16 14-13-29](https://github.com/pwr-Solaar/Solaar/assets/47497861/f4cc14b6-d343-4c6b-8a7d-7793d7fe8afd)

**Comment by pfps** [comment]
The wording might not be the best, but it appears to provide the necessary information.   What else do you need?

The rule that you show appears to correctly simulate a left mouse click with the left control key pressed.  Run Solaar as `solaar -ddd` to see what is happening.

**Comment by AugustineYang** [comment]
Thanks for your reply. I got the right debug info here, but the rule doesn't seem to work correctly. It only functions a left mouse button click. Also I got a warning symbol in the key input box of the "Key press" rule editor. ˙◠˙
![image](https://github.com/pwr-Solaar/Solaar/assets/47497861/654e34de-93b8-42a6-b1a8-6c8b020d949d)
![image](https://github.com/pwr-Solaar/Solaar/assets/47497861/cdbd8e8f-e9a3-4143-b19c-ef11ee5c8e59)

**Comment by pfps** [comment]
Please post the error log as text, not an image.

**Comment by AugustineYang** [comment]
Updating to the latest version solve the issue. Really appreciate your help.
