### ISSUE TITLE
Pairing a keypad

### ISSUE THREAD

**Issue by amigaman01** [pwr-Solaar/Solaar#2219]
I am a complete newbie to Linux.
I have a Logitek M720 Triathlon mouse which is working fine.
I also have a Logitech K850 keyboard which doesn't appear when I do a search.
Any help would be very much appreciated.

**Comment by pfps** [comment]
You need to better describe what you do have.  Do the devices work under Linux?  How are they connected - via Logitech receivers or wires or Bluetooth?   What is the output of `solaar show`?  What version of Solaar are you running?

**Comment by pfps** [comment]
Closing due to no response.
