### ISSUE TITLE
Any chance to add MK220 combo (K220 + M150)?

### ISSUE THREAD

**Issue by joaojotta** [pwr-Solaar/Solaar#222]
Well, the title says it all.

The combo is the MK220:
Keyboard: K220
Mouse: M150

Thanks and good work!

**Comment by Lekensteyn** [comment]
Please clone from git and report the output of `bin/solaar show > mk220.txt` and `lsusb -d 046d`.

**Comment by joaojotta** [comment]
And THAT'S how you catch a noob.
I know nothing of what you're talking about. ):

Is this the second part?
<code>Bus 007 Device 002: ID 046d:c534 Logitech, Inc.</code>

**Comment by bipson** [comment]
@joaojotta: the first part was about building the project from source, so that you have the newest version running on your machine. This requires you to clone the repository (this repository) to your machine (check this: http://stackoverflow.com/questions/315911/git-for-beginners-the-definitive-practical-guide#323906, don't forget to install git I guess). It is actually simpler than it looks, don't be afraid, use google if something is not clear, git is very widespread, so are introductory guides.
Alternatively, you could also download the zipped project from github (there is usually a link on the project's main page), but you would be required to do this every time you want the newest code, where the other way you can just use git commands.

Once you got this, you can build and run the newest version on your local machine, for which the steps are described in the readme (se the project's start page on the bottom). This might require that you search for some solutions regarding your python installation, udev rules and such, but it's not exactly rocket science.

**Comment by joaojotta** [comment]
Well, I guess I'm one step ahead.
Still, thanks @bipson.

The software is already running but I can't find the [code]mk220.txt[/code] under the [code]/bin/solaar[/code] folder not can I create one.

Thats the step I don't understand.
(sorry for the delay on the response but we got some virus at home and the kids have been sick)

**Comment by Lekensteyn** [comment]
Actually, the device info was already reported before at https://github.com/pwr/Solaar/blob/master/docs/devices/mk220.txt, so you do not have to report it once again. Once I've some time and finished MX master support, I'll look into this.

**Comment by joaojotta** [comment]
Great!
That's amazing!

I'm sorry for the double report than. I did search for it but got no results so...
Thanks again!

**Comment by FabioBeneditto** [comment]
Hi!

MK220 kit is very popular here in Brazil.

I still waiting for. Thanks! :)

**Comment by jrbenito** [comment]
Guys,

The problem with MK220 is that it is non unifying just like the MK270 (see issue #234). The receiver bundled with MK220 has product ID 0xc534 exactly like MK270 from the issue above. At this time, Solaar does not recognize this device, I made some changes to Solaar and it found the device but crashed with error as told by @Lekensteyn (again, see #234).

If you are on Linux machine with the receiver plugged in please run a `solaar show --debug` on a Solaar modified as I described in #234 and post it here so we can look it. I will only get back to home next week, until there I cannot do this command myself but would look to results and try to find something.

@FabioBeneditto, I am from Brazil also, if you want to help drop me a message.

Regards

**Comment by jrbenito** [comment]
@Lekensteyn ,

Regarding mk220.txt you pointed out, it is a different (newer?) combo with same label name (MK220 - WTF Logitech? Second time I see it, same thing with K270 keyboard and MK270 combo). The MK220 claimed by @joaojotta  uses different receiver `046d:c534` while the mk220.txt pointed in the repo uses `USB id       : 046d:c52e`

This is still related (dup) of #234 and #152

**Comment by jrbenito** [comment]
PR #337

**Comment by jrbenito** [comment]
@FabioBeneditto , @joaojotta 

Do you still have the MK220 available? If so, could you please checkout [my branch PR337](https://github.com/jrbenito/Solaar/tree/PR337) and run `solaar show` for me? 

Thanks

**Comment by FabioBeneditto** [comment]
@jrbenito let me clone and try it

**Comment by FabioBeneditto** [comment]
Results here: 
[PR337.txt](https://github.com/pwr/Solaar/files/832186/PR337.txt)

**Comment by jrbenito** [comment]
@FabioBeneditto ,

Thanks! One question: Are you using keyboard from the combo or another one?

The question came from the fact that your keyboard have same WPID as K270 (keyboard from MK270 combo). If you are using original keyboard then MK220 brings same keyboard as MK270. 

Regarding mouse M150, I will submit a PR with its descriptor based on your report.

**Comment by FabioBeneditto** [comment]
@jrbenito I'm using keyboard (K220) and mouse (M150) from combo.

**Comment by jrbenito** [comment]
@FabioBeneditto ,

Based on your report, Logitech´s K220 and K270 from MK220 and MK270 are the same keyboard. At least on newer versions of this combo. From the report at [mk220.txt](https://github.com/pwr/Solaar/blob/master/docs/devices/mk220.txt) there are wpid different for keyboard and mouse.

Descriptors submitted (PR #346) and PR337 test branch updated. If you could test again please.

**Comment by FabioBeneditto** [comment]
Test branch updated. Log attached.
[PR337-updated.txt](https://github.com/pwr/Solaar/files/834100/PR337-updated.txt)

**Comment by jrbenito** [comment]
Terrific, this may close this issue once merged. Thanks!

**Comment by surajprgupta** [comment]
Hi,
My MK220 combo isn't pairing with the unifying receiver.
I am getting message  - 
solaar: error: pairing failed: device not supported

**Comment by jrbenito** [comment]
Dear @surajprgupta 

MK220 combo isn´t unifying, its devices cannot be paired with unifying receiver neither on Windows nor on Linux. You need a nano receiver.

**Comment by abdul-billy** [comment]
@jrbenito 
I have mk220 combo which I lost its receiver, but I have extra nano receiver, can you please tell me what to do, keep in mind that I'm beginner

**Comment by jrbenito** [comment]
@abdul-billy , 
Currently you do need to pair using Logitech Windows software.

**Comment by CyberCrash-m** [comment]
> @abdul-billy ,
> Currently you do need to pair using Logitech Windows software.

@jrbenito i have the same situation like @abdul-billy with MK220 combo that has no on/off switch and the logetic connecting sw is not detecting... did you guys actualy mange to get it work with Nano receiver rather than that long USB that originally cam with it

**Comment by pfps** [comment]
https://support.logi.com/hc/en-us/articles/360023241974 seems to indicate that it is not possible to switch receivers for this keyboard, and maybe mouse.

**Comment by theleoni** [comment]
I have the MK220 combo, but I'm using just the mouse (M170). After doing some stuff, have connected the Solaar with the nano receiver (all good). But the battery level is "unknown". Someone knows if It's possible fix that to show the battery level? Using on Ubuntu 20.04, Solaar 1.0.6.

**Comment by pfps** [comment]
Please provide output from `solaar show` to see what the mouse can do.

**Comment by theleoni** [comment]
`solaar show`:
```
Nano Receiver
  Device path  : /dev/hidraw2
  USB id       : 046d:C534
  Serial       : None
    Firmware   : 29.01.B0016
  Has 2 paired device(s) out of a maximum of 2.
  Has 18 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)

  1: Wireless Keyboard MK270
     Device path  : /dev/hidraw3
     WPID         : 4023
     Codename     : MK270
     Kind         : keyboard
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: 00000000
     Battery: unknown (device is offline).

  2: Wireless Mouse M185 new
     Device path  : /dev/hidraw4
     WPID         : 4054
     Codename     : M185n
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 00000000
     Model ID:      000000000000
     Unit ID:       00000000
          Firmware: RQM 64.00.B0008
     The power switch is located on the base.
     Supports 20 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Firmware RQM 64.00.B0008 4054
            Unit ID: 00000000  Model ID: 000000000000  Transport IDs: {}
         3: DEVICE NAME            {0005}   
            Name: Wireless Mouse  
            Kind: mouse
         4: RESET                  {0020}   
         5: REPROG CONTROLS V4     {1B04}   
            Key/Button Actions (saved): {'80': 80, '81': 81, '82': 82}
            Key/Button Actions        : {'80': 80, '81': 81, '82': 82}
         6: WIRELESS DEVICE STATUS {1D4B}   
         7: LOWRES WHEEL           {2130}   
            Wheel Reports: HID
            Scroll Wheel HID++ Scrolling (saved): False
            Scroll Wheel HID++ Scrolling        : False
         8: POINTER SPEED          {2205}   
            Pointer Speed: 1.0
            Sensitivity (Pointer Speed) (saved): 256
            Sensitivity (Pointer Speed)        : 256
         9: DEVICE RESET           {1802}   internal, hidden
        10: unknown:1810           {1810}   internal, hidden
        11: unknown:1830           {1830}   internal, hidden
        12: unknown:1850           {1850}   internal, hidden
        13: unknown:1869           {1869}   internal, hidden
        14: unknown:1890           {1890}   internal, hidden
        15: unknown:18B1           {18B1}   internal, hidden
        16: unknown:1DF3           {1DF3}   internal, hidden
        17: unknown:1E00           {1E00}   hidden
        18: unknown:1F03           {1F03}   internal, hidden
        19: unknown:1E80           {1E80}   internal, hidden
     Has 3 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, reprogrammable, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, reprogrammable, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
     Battery status unavailable.
```

**Comment by pfps** [comment]
Solaar identifies your mouse as a M185.  This doesn't mean that it is not branded as an M170, just that this WPID has been used for mice branded as M185.  Logitech does reuse WPIDs.  Looking at the the supported features there is nothing that can be used to determine battery information so it is not possible for Solaar to report it.
