### ISSUE TITLE
No tray icon in Plasma 5

### ISSUE THREAD

**Issue by velifico** [pwr-Solaar/Solaar#223]
I think the problem is XEmbed support is no longer available in Plasma 5. Is there any way Solaar to use KDE's new statusnotifier?

**Comment by caco3** [comment]
This sadly is preventing me to upgrade to Plasma 5 :(

**Comment by tanghus** [comment]
There are some instructions on how to make it show in the systray [here](http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/).

Unfortunately they didn't work for me.

**Comment by tanghus** [comment]
There's a small gtk library [here on github](https://github.com/jjk-jacky/statusnotifier) that supports "modern" systray protocol.

**Comment by pfps** [comment]
ps -eo pid,user,pmem,args

**Comment by pfps** [comment]
The current version of Solaar uses the system tray if available.  This should solve your problem.  If not, you  can reopen this issue.
