### ISSUE TITLE
Better elementary OS support

### ISSUE THREAD

**Issue by jbreitbart** [pwr-Solaar/Solaar#224]
The currently used icon in solaar does not match the design of elementary OS. Would it be possible to use the battery status icons provided by the OS instead instead of the battery icon currently used?

There is a discussion with more details here: https://github.com/mank319/elementaryPlus/issues/43

**Comment by Lekensteyn** [comment]
Isn't this already possible by using icon themes?

Btw, if you do not need advanced features of Solaar and just need battery reporting, consider depending on UPower which also understands Unifying receivers.

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by jbreitbart** [comment]
I normally don't use solaar anymore, however I gave it a try. I cloned the current version, but after starting it from the terminal there is no indicator visible. The shell just sits there until I kill solaar. No idea what is happening

```
$ bin/solaar -V
solaar 1.0.1
```

**Comment by pfps** [comment]
When solaar is started up with no arguments (and no -V) it just sets up as a program in the "tray".  If you don't have a tray then maybe solaar won't be accessible at all.  If you don't open your tray then you won't notice solaar.
I have a change in for solaar to switch behaviour so that without any argument the solaar window will be visible, but that hasn't been merged into the main branch of solaar.
Anyway I'll close this issue, as being addressed by that pull request, PR #611

**Comment by BenoitDuffez** [comment]
For those wondering how to get a quick fix: clone this repo, run `bin/solaar -w show` and you will have a GUI.

FYI in more recent versions of Elementary OS, there is no Gnome tray available for apps. So when you start Solaar, nothing happens as there is no window and no tray.
Forcing the window with `-w show` fixed my problem.
