### ISSUE TITLE
Environment Variables Support

### ISSUE THREAD

**Issue by kroist** [pwr-Solaar/Solaar#2244]
Tried to add the action, which executes the script, which depends on environment variable. There is quite unusual way to set the variable from rules config, because of python.subprocess interface

Example:

If I want to add the following rule:

```
- Rule:
  - Key: [Mouse Gesture Button, released]
  - Execute: [SOME_ENV_VAR="abacaba", /usr/local/bin/some_bin]
```

then nothing happens, but if I prepend `env` to the args list
```
- Rule:
  - Key: [Mouse Gesture Button, released]
  - Execute: [env, SOME_ENV_VAR="abacaba", /usr/local/bin/some_bin]
```
it works as it should

I'm not an expert in python's supbrocess module, but it should be more obvious how to set additional env variables for the command.

**Describe the solution you'd like**
https://github.com/pwr-Solaar/Solaar/blob/06209d238abfc3ff2efdf2970b7c8dfd4a926d13/lib/logitech_receiver/diversion.py#L1338

can be executed as:
```
subprocess.Popen(self.args, env={'ENV_1': 'VAL_1', ...})
```

And user might add envs via config/UI the same way as arg list is implemented now.

**Comment by pfps** [comment]
What execute does is execute a command, not interpret a shell line. The env command is the command that sets up an environment and then runs another command.  That is the way to go here. 

So this enhancement is not planned.

**Comment by NXTler** [comment]
Have you somehow managed to get variables working?
