### ISSUE TITLE
How can I disable free spin and the smart shift button entirly on MX Master 3S?

### ISSUE THREAD

**Issue by imthenachoman** [pwr-Solaar/Solaar#2246]
First, if this is the wrong place for support, I apologize. I could not figure out where to go for help.

I have the MX Master 3S and Solaar seems to work with it. But I cannot figure out how to disable the smart shift button and disable free spinning entirely.

Right now when I press the smart shift button, I can see it toggle between free spinning and ratcheted. I want to remap the smart shift button to a keyboard shortcut. And I want it so the mouse never goes into free spinning, even if I scroll the wheel very fast.

I'm not sure what I am missing.

![image](https://github.com/pwr-Solaar/Solaar/assets/83817/12014e70-5135-41ae-858c-1bd48698c37b)

**Comment by pfps** [comment]
Scroll Wheel Ratchet Speed is the setting that switches between freespinning and ratcheted..  As indicated by its tooltip, set it to 50 for always ratcheted.

Remap the smart shift button to whatever you want, but you only have the seven options, none of which are keys.   You would have to divert this button and add a Solaar rule to simulate the key.

**Comment by imthenachoman** [comment]
> As indicated by its tooltip, set it to 50 for always ratcheted.

Ah. I see. Let me try that.

> You would have to divert this button and add a Solaar rule to simulate the key.

I used `Key/Button Diversion` to set `Smart Shift` to `Diverted`. That seems to have disabled the button changing ratchet -- which means the diversion worked. 

I'm stuck on how to create the rule. Am I doing it right?

![image](https://github.com/pwr-Solaar/Solaar/assets/83817/ce36c120-c4fa-4f9b-bf98-2f3d058c1d48)

**Comment by imthenachoman** [comment]
Ah. Never mind. I see that rule processing does not work in Wayland. :/

**Comment by pfps** [comment]
You can probably make it work in Wayland by installing the alternative Solaar udev rule.   See https://pwr-solaar.github.io/Solaar/rules

**Comment by imthenachoman** [comment]
YES! That worked. I saw that page but the way it read it sounded like the udev rules wouldn't work with wayland. Thank you so much!
