### ISSUE TITLE
Clean up common logging code

### ISSUE THREAD

**Issue by MattHag** [pwr-Solaar/Solaar#2254]
**Information**
latest master branch

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The logging code used in every module seems a bit uncommon and worsens readability in my opinion. Therefore, I suggest a small clean up.

The existing code relies on:
```
from logging import INFO as _INFO
from logging import getLogger
...
_log = getLogger(__name__)
del getLogger

if _log.isEnabledFor(_INFO):
    _log.info("Log message")
```

It is not good practice and haven't seen this practice before and I would also stick to the common names, which every Python developers knows.

```
import logging
...
logger = getLogger(__name__)

if logger.isEnabledFor(logging.Info):
    logger.info("Log message")
```

**Comment by pfps** [comment]
Looks reasonable.
