### ISSUE TITLE
Simplify installation of udev rules

### ISSUE THREAD

**Issue by MattHag** [pwr-Solaar/Solaar#2263]
**Information**

- Solaar version: latest master branch

**Is your feature request related to a problem? Please describe.**
Udev rule installation requires knowledge of paths and can be simplified for Unix systems.

**Describe the solution you'd like**
Simplify udev rule installation and update installation manual.

Create Makefile with the folowing commands:

- `make install_udev`
- `make install_udev_uinput`
- `make uninstall_udev`

**Describe alternatives you've considered**
Python script needs more effort and.

**Additional context**
Makefile can be extended to install _apt_ and _pip_ packages.

**Comment by pfps** [comment]
These scripts require su privileges, right?

**Comment by MattHag** [comment]
Yes, the commands require them and you'll get a password prompt.

**Comment by pfps** [comment]
It seems reasonable to put in this make file to eliminate the need to know where the udev files are put.   Could it also check for missing dependencies?  The problem with adding missing dependencies is the divergence between apt-based and dnf-based distributions.

**Comment by MattHag** [comment]
Yes, as mentioned in another issue, we can move the _apt_ and _pip_ install command to the Makefile too. And update the GitHub action to leverage the make commands and the Makefile is the source of truth. 

We can at least support a convenient setup with Ubuntu. It should be possible to provide a 
`make install`
that determines the Display manager automatically and adapts the installed dependencies, udev rules etc.

But this is something for another change.

**Comment by MattHag** [comment]
I need to fix some lines in this PR

**Comment by MattHag** [comment]
Ready
