### ISSUE TITLE
GUI: Add padding to devices scrollable view

### ISSUE THREAD

**Issue by MattHag** [pwr-Solaar/Solaar#2266]
**Information**

- Solaar version: solaar 1.1.11rc1-3-ge1ac8b5
- Distribution: Ubuntu 20.04

**Is your feature request related to a problem? Please describe.**
The latest GUI misses some whitespace on the scrollable view visible on the screenshot below. The

1. The text 'Backlight' has no whitespace to the left side of the surrounding rectangle.
2. It misses some top and bottom padding. On the screenshot shows the lack of padding on top. This leads to the impression, that there should be more content above, but there isn't. The same issue applies to the bottom padding, where input selections directly hit the surrounding rectangle too.

![Screenshot from 2024-02-11](https://github.com/pwr-Solaar/Solaar/assets/16444067/469e94b1-f4dd-4c8d-a8be-c070ce4c3537)

**Describe the solution you'd like**

- 'Backlight' etc should get a little spacing padding between the border.
- The scrollable view should get top and bottom padding. Thus, the viewer can see that the top or bottom end is reached.

**Comment by pfps** [comment]
A solution is to just remove the "shadow" around the scrolling region and add a horizontal line just above it.   PR #2268 does this.

**Comment by MattHag** [comment]
Yeah, that's absolutely possible as long as the scrollability is easy to detect.

**Comment by pfps** [comment]
It should be the same as before.   Here is a screenshot from the current version and then one from the PR
![Screenshot from 2024-02-11 09-40-25](https://github.com/pwr-Solaar/Solaar/assets/6618235/c10dbe65-cd07-4a52-90e7-0e4fa585c863)
![Screenshot from 2024-02-11 09-42-08](https://github.com/pwr-Solaar/Solaar/assets/6618235/ac553e1b-7ffa-4516-b199-b8bf047c525c)

**Comment by pfps** [comment]
As you say, the remaining issue is how to easily determine whether the configuration panel is scrollable.  Just having the shadow doesn't do that well, in my opinion.  If the scroll bar was visible when the window first comes up if there is non-visible bits that would do the trick.

**Comment by pfps** [comment]
The problem is that there does not seem to be a way in GTK to have the scrollbar "line" always be visible.  It fades away under various circumstances but comes back when useful.

But the "shadow" around the scrolling region isn't indicative that there is a scrolling region.   So I think removing the "shadow" is a good idea as it helps with the left and top margins.

**Comment by pfps** [comment]
When you do hit the top or bottom there is a stop indicator that shows up briefly.

**Comment by MattHag** [comment]
The second screenshots shows an improvement to the status quo. However, giving a hint that a view is scrollable seems not the strength of GTK. Let's merge this.

**Comment by MattHag** [comment]
Today I discovered, that Ubuntu seems to add a slight inner shadow to the edge, which hides scrollable content. So the solution should be perfect on Ubuntu 👍
