### ISSUE TITLE
Error "Pairing failed: failed to open pairing lock." now appearing

### ISSUE THREAD

**Issue by LorinRicker** [pwr-Solaar/Solaar#227]
Ubuntu 14.04, Solaar 0.9.2, Python 2.7.6

I've had to re-pair a Logitech K750 keyboard, once paired successfully (but offline for awhile), now attempts to pair this device get the following error-box:

  Pairing failed: failed to open pairing lock.
  No further details are available about the error. [Close]

What does this mean, and how can I fix it?  This "used to work", don't know what, if anything, might have changed regarding the Solaar installation on this laptop (probably nothing, as it's been install, use and forget it).

TIA for any help and response!

**Comment by LorinRicker** [comment]
P.S. Existing Unifying Receiver continues to work fine with Logitech M325 mouse, has been for well over a year; this same K750 keyboard worked for most of that year as well, until I turned it off while we moved. Now just want to re-pair it and use it... Thanks!

**Comment by Lekensteyn** [comment]
It seems that the K750 keyboard is not replying at all. Is its battery charged?

**Comment by LorinRicker** [comment]
It's the solar/light powered keyboard, so it should be charged.  I've tried this with another Logitech wireless keyboard, brand new batteries, same response. I found the Python code that annunciates the error box, but haven't backtracked the cause for "No further details..." -- this stuff is pretty complicated to detect, no?  Thanks...

**Comment by LorinRicker** [comment]
Woah - wait - what?  Now this is interesting!  The keyboard now works (I'm typing on it right now), but it does not show up in Solaar's GUI under the Unifying Receiver as a device!???  Seems to have paired, even with the error-box. Since it's "not there", I'll not be able to unpair it (if I wanted to... I don't). Might the keyboard show up after a laptop reboot? I'm not gonna try without some feedback here.  Thanks!

**Comment by LorinRicker** [comment]
Even tho "it now works...", Solaar fails to show the K750 keyboard under the Unifying Receiver (GUI display).  But lsusb sees it fine, and I'm curious as to whether this is a bug, or "expected behavior"? --

$ lsusb -v -d 046d:

Bus 003 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x046d Logitech, Inc.
  idProduct          0xc52b Unifying Receiver
  bcdDevice           12.01
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           84
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          4 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower               98mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard                           <<<=== there it is!
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      59
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               8
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     148
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               2
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      98
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0020  1x 32 bytes
        bInterval               2

**Comment by LorinRicker** [comment]
And the command-line solaar shows it fine:
$ solaar-cli show
Unifying Receiver [/dev/hidraw0:714194DB] with 3 devices
1: Wireless Solar Keyboard K750 [K750:EDC90418] 
2: Wireless Mouse M325 [M325:29B2D09D] 
3: Wireless Mouse M325 [M325:07A95795] offline

So this is a bug with the GUI?  Both for the pairing action and for the subsequent display of the device?

**Comment by Lekensteyn** [comment]
Can you start with `solaar --debug`? Can you reproduce it with git code?

**Comment by takkun324** [comment]
I'm not sure if it is the same bug but I just had a similar issue with a M310 mouse. The GUI kept giving the "failed to open pairing lock" error. Reading the comments here, I decided to give the CLI a try. It too have a "error: device timeout" but it is now working (so it did pair).

**Comment by rlipscombe** [comment]
Same problem with a T620 mouse: failed to open pairing lock but it works anyway.

**Comment by AngelBright** [comment]
Hi. I just had the exact same problem; suspect it is just a GUI issue. No matter what I did, the K750 would not work. However, the minute I connected a cabled USB keyboard, suddenly the K750 started working. Still doesn't show up in the GUI interface but does show on the command line.

**Comment by Mektoub** [comment]
I had the same problem. I found out that I already had 6 paired devices. So I removed one and I was able to pair a new device then.

**Comment by msplival** [comment]
Looks like a GUI issue. 'solaar-cli pair' helped me.

**Comment by acwest** [comment]
I am getting the same behaviour. I got the pairing lock error in the gui, but the mouse started working, and the solaar-cli command has no problem seeing the mouse

**Comment by MikecuriousMind** [comment]
I searched for libappindicator-sharp, installed it, logged in/out a few times and now it's working again. It's really not all that important to me as the cli works if I ever need to pair/unpair devices. Am trying to figure out how to wake the pc from suspend via keyboard (k350) but no luck yet.

**Comment by renyuneyun** [comment]
Doesn't seem to be a GUI-only problem (though, I think this mainly relates to the GUI):

I have the same issue just now, when pairing a new mouse (M590) - pairing shows the error dialog box, now showing the device, but device works + `solaar-cli show` shows the device.

Then I switched to `solaar-cli`, and unpair and re-pair the mouse. It succeeded (though I was getting some errors in the beginning tries, but I suspect that was my fault).
Then, open solaar (GUI) again, the new device is now shown ("number of paired device" is still **2** which is the number before pairing this new mouse).

**Comment by chaim1221** [comment]
Just happened to me. And indeed, the keyboard actually paired. `solaar-cli show` does indeed show the device. Wireless Keyboard K350, Solaar 0.9.2, Ubuntu 16.04.4 LTS

**Comment by tsela** [comment]
Same here: `solaar-cli` shows two devices paired (MX Ergo trackball and K800 keyboard), but the GUI says it only sees one device (the mouse). Restarting the computer does not help, nor does restarting the GUI.

Weirder still, just a minute ago the GUI said it saw two devices, but it only showed the mouse. Then it suddenly showed the keyboard, but that's when the keyboard stopped working and stayed completely unresponsive until I closed the Solaar GUI.

In any case, this afternoon the trackball kept acting up, and this evening it was the turn of the keyboard. Now they seem to both work, but for how long... This computer is brand new and running Ubuntu 19.04. There shouldn't be any incompatibility, right?

**Comment by pfps** [comment]
Please check with the version of solaar current on github.

**Comment by pfps** [comment]
The current version on github is 1.0.1.  If you are still running version 0.9.2 you should get a newer version for your distribution if possible.  Otherwise you can clone solaar from this repository.

**Comment by pfps** [comment]
Closing due to no response from original poster.
