### ISSUE TITLE
PNG icons installed as scalable icons

### ISSUE THREAD

**Issue by skitt** [pwr-Solaar/Solaar#2285]
The 1.1.11 pre-releases install various PNG icons in `/usr/share/icons/hicolor/scalable/apps/`, but the `scalable` hierarchy is reserved for scalable (SVG) icons.

**Comment by pfps** [comment]
Hmm.  I think that this has been the case for quite some time, but it should be fixed.

**Comment by pfps** [comment]
The solution is to convert them to svg.  The result is not great, but the png images are also not great and the png files are only used for some old hardware that might be used by any user of Solaar.  As well, the names of these icons have been changed to include `solaar` as should have been done.

**Comment by pfps** [comment]
Hmm, a better solution is to put them in the 32x32 directory.

**Comment by skitt** [comment]
Right, the change was made in https://github.com/pwr-Solaar/Solaar/commit/5ca1790cb861ae63d802d0254a8b3cdca5f592ff, but that hasn’t been in a release yet :wink:. I agree the better solution is to put them in `32x32`.
