### ISSUE TITLE
Solaar not starting all the time

### ISSUE THREAD

**Issue by heynnema** [pwr-Solaar/Solaar#229]
Solaar is in my startup applications list. However, after a reboot and login, sometimes it only displays its solaar icon in the top panel. However, if I quit and restart Solaar, then it properly displays its battery condition icon in the top panel, and the list of paired devices.

**Comment by ciubex** [comment]
Same issue: Ubuntu 14.04 LTS, 3.19.0-42-generic
Device: Logitech T620

**Comment by Arthur-D** [comment]
I have something similar with Kubuntu 14.04. I need to unplug my Unifying Receiver and then reinsert it for any battery status to show.

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from submitter.
