### ISSUE TITLE
installing Solaar on debian bookworm running inside Chrome OS

### ISSUE THREAD

**Issue by solanuscasey** [pwr-Solaar/Solaar#2293]
Not sure this is a bug or if I'm doing something wrong, but I am running debian bookworm from a chromebox, and have attempted this using several different install methods.(clone from  github using terminal, download .deb from debian.com, and sudo apt install solaar) Each of these successfully installed and launched with no issues, but no devices appeared in the window.  The mouse(G 502 lightspeed) is not supported according to the devices page, but my keyboard(G915 TKL lightspeed) should be. Not sure if I did something wrong or if the chrome container just doesn't support this.
Thank you.

**Comment by MattHag** [comment]
You likely missed the udev rule installation. With the latest Github version you can do
```make install_udev```
 and if that doesn't help, 
```make install_udev_uinput```
. Restart and test again.

**Comment by pfps** [comment]
As it states, the devices page is only a partial listing of supported devices.  G502 mice (there are several models) should be supported.  As Matt says, a likely cause is that the udev rule is not installed or in effect.   (After installation you have to either restart your computer or cause udev to notice the new rule and then disconnect and reconnect your devices.)  For more information see https://pwr-solaar.github.io/Solaar/installation

**Comment by solanuscasey** [comment]
when I run "make install_udev", I get the output "-bash: make: command not found" and I get the same output for "make install_udev_uinput"

**Comment by solanuscasey** [comment]
/rules.d/42-logitech-unify-permissions.rules is not registering as a file or directory, /etc/udev/rules.d is. I'm bad at linux so I probably did something wrong but I have no idea what

**Comment by pfps** [comment]
You probably either need to restart your computer or `sudo udevadm control --reload-rules` and then disconnect and reconnect your devices.   This runs udev on the devices, which then sets them up so that Solaar can manipulate them.

**Comment by solanuscasey** [comment]
Will be restarting, already tried the reload rules command(it worked, but the devices didnt connect even after disconnecting and reconnecting.)

**Comment by pfps** [comment]
If it still isn't working, run `solaar -ddd` and post the output.  Also post the output of `ls -l /etc/udev/rules.d`.

The other thing that might be going wrong is that both these devices are only recognized by parsing their HID report descriptors, which is only done if the Python hid-parser library is installed.  (Use `pip install hid-parser` to do this.)

**Comment by solanuscasey** [comment]
Alright thank you, I will let you know how it goes when I get the chance.

**Comment by solanuscasey** [comment]
ran solaar -ddd, got this output 
![image](https://github.com/pwr-Solaar/Solaar/assets/130777143/c1a57c2a-7e55-4d2d-8474-03bca9e4c6a5)

**Comment by solanuscasey** [comment]
ran ls -l /etc/udev/rules.d, got this output
![Screenshot 2024-02-17 10 01 35](https://github.com/pwr-Solaar/Solaar/assets/130777143/b73ae1d9-17ad-48bc-9465-089d6aacb471)

**Comment by pfps** [comment]
What version of Solaar are you running?  Use `solaar --version`.

**Comment by solanuscasey** [comment]
solaar 1.1.8+dfsg-2

**Comment by pfps** [comment]
That's old.   You should update to 1.1.10.  You can use `pip install solaar` to do this.  You should then add the pip user installation directory (likely `~/.local/bin`) to your path.  You could also run solaar as `~/.local/bin/solaar`.  If your devices still don't show up then again run solaar with `-ddd`, grab the output as a text file, and post it here.

**Comment by solanuscasey** [comment]
> which is only done if the Python hid-parser library is installed. (Use `pip install hid-parser` to do this.)

will need to install pip package manager, python 3 or 2?

**Comment by pfps** [comment]
Python 3

**Comment by solanuscasey** [comment]
solanuscasey57@penguin:~$ pip install solaar
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

Am I missing some software?

**Comment by solanuscasey** [comment]
solanuscasey57@penguin:~$ pipx install solaar
Fatal error from pip prevented installation. Full pip output in file:
    /home/solanuscasey57/.local/pipx/logs/cmd_2024-02-17_10.21.14_pip_errors.log

pip seemed to fail to build package:
    dbus-python>=1.3.2

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ../subprojects/dbus-gmain/meson.build:107:11: ERROR: Dependency lookup for dbus-1 with method 'pkgconfig' failed: Pkg-config for machine host machine not found. Giving up.
    error: metadata-generation-failed

**Comment by pfps** [comment]
This is part of a change to how Python packages are installed, required in some distributions.   I think that you can install `pipx` and then `pipx install solaar`.  (The idea is to allow installed Python packages each have their own version of the Python packages they use.)

I see that you already tried `pipx, though.

**Comment by pfps** [comment]
You could try `pipx install dbus-python`, which should install the current version of dbus-python for just you.  This version is from Sept. 2022 so it should be compatible with the current version of Debian.

**Comment by solanuscasey** [comment]
solanuscasey57@penguin:~$ pipx install dbus-python
Fatal error from pip prevented installation. Full pip output in file:
    /home/solanuscasey57/.local/pipx/logs/cmd_2024-02-17_10.31.22_pip_errors.log

pip seemed to fail to build package:
    dbus-python

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ../subprojects/dbus-gmain/meson.build:107:11: ERROR: Dependency lookup for dbus-1 with method 'pkgconfig' failed: Pkg-config for machine host machine not found. Giving up.
    error: metadata-generation-failed

Error installing dbus-python.

**Comment by pfps** [comment]
Time to bring in someone who knows more about Debian.

@skitt @antonsoroko Do either of you know what is going wrong here?

**Comment by skitt** [comment]
Yes, `pipx` can’t find either the dbus libraries or `pkgconfig` itself. I think the simplest solution here is to install the packaged module: `sudo apt install python3-dbus`.

**Comment by solanuscasey** [comment]
solanuscasey57@penguin:~$ pipx install solaar
Fatal error from pip prevented installation. Full pip output in file:
    /home/solanuscasey57/.local/pipx/logs/cmd_2024-02-17_11.07.43_pip_errors.log

pip seemed to fail to build package:
    dbus-python>=1.3.2

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ../subprojects/dbus-gmain/meson.build:107:11: ERROR: Dependency lookup for dbus-1 with method 'pkgconfig' failed: Pkg-config for machine host machine not found. Giving up.
    error: metadata-generation-failed

successfully installed python3-dbus with your instructions, but solaar still will not install with pip

**Comment by pfps** [comment]
@skitt  Any other suggestions?

**Comment by skitt** [comment]
OK, I thought the module would be available for `pipx` (it should…). To allow `pipx` to build the module itself, install the appropriate dependencies: `sudo apt install libdbus-1-dev pkgconf`.

**Comment by pfps** [comment]
Please don't use screenshots.  Instead cut and paste the text.

Did you uninstall Solaar using apt?  That may have removed its dependencies.  If so, you should install the old version of Solaar using apt and then try to install the current version using pipx.   Otherwise you have to install all the Solaar dependencies manually, as described in the Solaar installation page.

**Comment by solanuscasey** [comment]
which one am i installing?

**Comment by pfps** [comment]
Just run `sudo apt install solaar`.  The (only) reason to do this is to install all dependencies that Solaar needs.  Then `pipx install solaar` should have access to the system packages that are needed for Solaar.  You will need to make sure that you then run the Solaar installed by pipx in ~/.local/bin

**Comment by solanuscasey** [comment]
still getting this on pipx install 
solanuscasey57@penguin:~$ pipx install solaar
Fatal error from pip prevented installation. Full pip output in file:
    /home/solanuscasey57/.local/pipx/logs/cmd_2024-02-17_14.04.20_pip_errors.log

pip seemed to fail to build package:
    dbus-python>=1.3.2

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ../subprojects/dbus-gmain/meson.build:108:11: ERROR: Dependency "glib-2.0" not found, tried pkgconfig
    error: metadata-generation-failed

Error installing solaar.

**Comment by pfps** [comment]
You mean after `apt install Solaar`?

If so, it's back to a Debian expert.  @skitt What's a good way to install Solaar 1.1.10 in Debian Bookworm?  Is it possible that there is a Python version mismatch problem here?

**Comment by solanuscasey** [comment]
I believe I can use git clone https://github.com/pwr-Solaar/Solaar.git

**Comment by pfps** [comment]
You certainly could clone Solaar and run as `bin/solaar` from there, following the install instructions in https://pwr-solaar.github.io/Solaar/installation.

**Comment by skitt** [comment]
Oh, I forgot I’d backported Solaar in Debian 12, so you can install it from there... Add

```
deb http://deb.debian.org/debian bookworm-backports main
```

to `/etc/apt/sources.list`, then

```
sudo apt update
sudo apt install -t bookworm-backports solaar
```

will upgrade you to 1.1.10.

**Comment by solanuscasey** [comment]
deb does not appear to be a command, am I installing a file or downloading and then copying?

**Comment by pfps** [comment]
You are editing a file, adding a line to it.  You probably need to do this as root.

**Comment by solanuscasey** [comment]
do i need to install an external text editor?

**Comment by pfps** [comment]
You have to have some way to change a text file.   At a bare minimum you could, as root
```
cd /etc/apt
mv sources.list sources.list.orig
cat sources.list.orig <<EOF > sources.list
deb http://deb.debian.org/debian bookworm-backports main
EOF
```
but it would be much safer to do this using `ed` or `vi` or `emacs`.

**Comment by solanuscasey** [comment]
which do you recommend?

**Comment by pfps** [comment]
If you have no experience in Linux then each of these has lots to learn, but you can probably use `ed`, using only the bits that are needed.  If you are going to be using Linux you should learn one of the Linux text editors.

Copy `/etc/apt/sources.list` somewhere just in case you mess something up.
Run `ed /etc/apt/sources.list` as root.
Enter `,p` to show the entire file.  (Each of the following are commands to ed and need to be followed by pressing Enter.)
Enter `a` to add some new text (at the end of the file).
Enter `deb http://deb.debian.org/debian bookworm-backports main`
Enter `.` to finish the addition.
Enter `,p` to show what you have done.
Enter `w` to write the file back.

**Comment by solanuscasey** [comment]
used nano, went fine but returned a permission denied message when attempting to save.

**Comment by solanuscasey** [comment]
successfully updated to 1.1.10, now what? should I go back and try the initial suggestions on this thread?

**Comment by pfps** [comment]
Try running Solaar, making sure that you are running version 1.1.10.  (Use `--version` to check.)   If your devices don't show up, run Solaar with `-ddd`, and cut-and-paste the output into a new comment.

**Comment by solanuscasey** [comment]
solanuscasey57@penguin:~$ solaar -ddd
2024-02-17 15:53:44,971,971     INFO [MainThread] root: version 1.1.10+dfsg-2, language en_US (UTF-8)
2024-02-17 15:53:45,155,155     INFO [MainThread] logitech_receiver.diversion: GDK Keymap set up
2024-02-17 15:53:45,155,155  WARNING [MainThread] logitech_receiver.diversion: rules cannot access modifier keys in Wayland, accessing process only works on GNOME with Solaar Gnome extension installed
2024-02-17 15:53:45,155,155  WARNING [MainThread] logitech_receiver.diversion: cannot create uinput device: "/dev/uinput" does not exist or is not a character device file - verify that the uinput module is loaded
2024-02-17 15:53:45,173,173    DEBUG [MainThread] solaar.ui.tray: using Ayatana AppIndicator3
2024-02-17 15:53:45,176,176     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
2024-02-17 15:53:45,240,240    DEBUG [MainThread] solaar.ui: startup registered=True, remote=False
2024-02-17 15:53:45,241,241    DEBUG [AsyncUI] solaar.tasks: started
2024-02-17 15:53:45,241,241     INFO [MainThread] solaar.ui.notify: starting desktop notifications
2024-02-17 15:53:45,244,244    DEBUG [MainThread] solaar.ui.icons: sys.path[0] = /usr/share/solaar/lib
2024-02-17 15:53:45,244,244    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
2024-02-17 15:53:45,244,244    DEBUG [MainThread] solaar.ui.icons: icon theme paths: ['/usr/share/solaar/icons', '/home/solanuscasey57/.local/share/icons', '/home/solanuscasey57/.icons', '/home/solanuscasey57/.local/share/icons', '/home/solanuscasey57/.local/share/flatpak/exports/share/icons', '/var/lib/flatpak/exports/share/icons', '/usr/local/share/icons', '/usr/share/icons', '/home/solanuscasey57/.local/share/pixmaps', '/home/solanuscasey57/.local/share/flatpak/exports/share/pixmaps', '/var/lib/flatpak/exports/share/pixmaps', '/usr/local/share/pixmaps', '/usr/share/pixmaps']
2024-02-17 15:53:45,300,300     INFO [MainThread] solaar.listener: starting receiver listening threads
2024-02-17 15:53:45,301,301    DEBUG [MainThread] solaar.ui: activate

(solaar:7397): Gtk-CRITICAL **: 15:53:45.406: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by pfps** [comment]
This is a bit of a puzzle.  It is almost as if dbus is not being used, but I don't see how this can happen.   You say you are running on a chromebox, which is a computer.  It may be that if you are indeed running Debian as a guest OS inside a container that dbus is not being used to manage devices.  I've never run Solaar inside a container so I don't know whether that will work.

**Comment by solanuscasey** [comment]
from my understanding of how chrome os and linux work together, chrome runs off linux, but the system is not like other desktops. Chromebox is just like a chromebook, just with more storage, requires an external display, and runs faster than a normal chromebook.(chromebook but desktop format)
https://www.chromium.org/chromium-projects/.

**Comment by pfps** [comment]
The issue is whether the computer is running Linux (Debian) natively.  If so, dbus should be running and Solaar should work.  

There are a bunch of things that can be checked to see what might be going wrong.  An easy one is whether the HID raw interface is available.  Run `ls -l /dev/hidraw*`.   There should be files there.  Another easy thing to do is to check whether dbus is running.  Run `dbus-monitor` and disconnect and reconnect (or turn off and on, if connected via bluetooth) a Logitech device or receiver.  If there is no output or the command fails then dbus is not running correctly.

**Comment by solanuscasey** [comment]
solanuscasey57@penguin:~$ ls -l /dev/hidraw*
ls: cannot access '/dev/hidraw*': No such file or directory
solanuscasey57@penguin:~$ ls -l /dev/hidraw
ls: cannot access '/dev/hidraw': No such file or directory

solanuscasey57@penguin:~$ dbus-moniter
-bash: dbus-moniter: command not found
solanuscasey57@penguin:~$ dbus
-bash: dbus: command not found
solanuscasey57@penguin:~$

**Comment by pfps** [comment]
So it is likely that the sandbox in which "Linux" runs is not set up to do the things that Solaar needs and the guest OS isn't a full Linux OS.  But as far as I can tell, you should be able to run Linux directly on the hardware (albeit perhaps with some work).

Someone who understands how Linux is set up under Chrome OS (or whatever is the host OS)  would have to see whether it is possible to run programs like Solaar there.

**Comment by solanuscasey** [comment]
I guess that makes sense, I was having issues with ssr and kazam where they could not record any of my screen except the mouse since they cant actually interact with the computer.

**Comment by solanuscasey** [comment]
oh well, guess I'll have to pester logitech till they add support for chrome/linux

**Comment by solanuscasey** [comment]
thx anyway

**Comment by antonsoroko** [comment]
@solanuscasey just FYI: you used "dbus-monit**e**r" instead of "dbus-monit**o**r".

but anyway, i guess you should ask google support (or your device vendor support) about possibility to run linux apps that need direct access to devices.

also from "Check what’s not supported yet" section here
https://support.google.com/chromebook/answer/9145439?hl=en
it is a bit hard to understand if it allows access to USB devices.

maybe there is a way to remove some "sandbox" restrictions (search the internet) - but it guess it also can lead to some security issues.

**Comment by solanuscasey** [comment]
came back to this since i found out how to remove security restrictions, but having trouble with install
solanuscasey57@penguin:~$ sudo pipx install solaar
Fatal error from pip prevented installation. Full pip output in file:
    /root/.local/pipx/logs/cmd_2024-02-28_20.04.22_pip_errors.log

pip seemed to fail to build package:
    dbus-python

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    ../subprojects/dbus-gmain/meson.build:108:11: ERROR: Dependency "glib-2.0" not found, tried pkgconfig
    error: metadata-generation-failed

Error installing solaar.

**Comment by pfps** [comment]
Iit appears that Glib is not installed or available.   That's an issue with your setup.  You may have to install whatever system package is needed to install Glib on your system.

**Comment by antonsoroko** [comment]
@solanuscasey 
i think you need to do `sudo apt install libglib2.0-0 libglib2.0-dev`
https://packages.debian.org/search?keywords=libglib2.0&searchon=all&suite=stable&section=all

(just a note: i am not sure that you will succeed in the end, since i am not sure if that "container with Debian" provided by Chrome OS supports launching or forwarding of GUI, like X11, for example. i suggest you to be prepared for that.)

**Comment by solanuscasey** [comment]
theoretically I can disable crocs-termina security using crosh so hopefully
i get that figured out
