### ISSUE TITLE
unify device information

### ISSUE THREAD

**Issue by pfps** [pwr-Solaar/Solaar#2299]
Information about devices is currently stored in several ways:
- directly on the device object, e.g., power switch location
- in settings on the device, e.g., fn-swap
- in the status structure on the device, e.g., battery information

It would be useful to store all the information the same way.

This would also allow for a single callback to the GUI.

**Comment by pfps** [comment]
One thing to start up with is to revise how the status structure stores information.  Right now it uses a dictionary with numeric keys (and symbols for each of these).  This could be changed to attributes of a class object, eliminating the need to import the symbols.  As well, there are multiple keys for batteries so a named tuple could be used instead.

**Comment by MattHag** [comment]
Instead of dicts and namedtuples, dataclasses should be favoured.

**Comment by pfps** [comment]
See #2368

**Comment by pfps** [comment]
With #2377 the status objects are gone.   There is still a separation between settings and other data, but I think this is reasonable.
