### ISSUE TITLE
solaar-cli does not work even though the gui does

### ISSUE THREAD

**Issue by michaelmrose** [pwr-Solaar/Solaar#230]
solaar --version = 0.9.2
solaar gui works perfectly other than spamming incredibly obnoxious windows repeatedly whenver the mouse gets low.
sudo solaar-cli config 1identifies the settings that can be set and their possible settings but fails to read its current value output is as follows

[69041711:mouse]
 Performance Mouse MX

Sensitivity (DPI)
possible values: one of [ 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400, 1500 ], or higher/lower/highest/max/lowest/min
dpi = ? (failed to read from device)

Smooth Scrolling
possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
smooth-scroll = ? (failed to read from device)

Side Scrolling
possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
side-scroll = ? (failed to read from device)

trying to set a value similarly fails ex.
sudo solaar-cli config 1 dpi 900 results in
solaar-cli: error: failed to set 'dpi' = '900' ['900']

Note gui is not running at the same time.

**Comment by mkraemer** [comment]
+1, i'm seeing the same behaviour

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
