### ISSUE TITLE
Mouse gesture without holding the button down

### ISSUE THREAD

**Issue by izlence** [pwr-Solaar/Solaar#2300]
I have MX Ergo trackball mouse. 
I am able to use the DPI Change button for mouse gestures. 
For example I press DPI button and hold it down and move the trackball to activate some rules. It's difficult.
It would be easier if I could  move the trackball without the need to hold the mouse gesture button pressed.

I wonder if it is possible to initiate a gesture by the DPI button and continue with some following mouse events (moving, clicking) without holding the mouse gesture button pressed.

I have spent several hours but couldn't achieve this.

Thank you.

**Comment by pfps** [comment]
This appears to be possible with some programming, but might take a while.

**Comment by izlence** [comment]
Actually it would be so nice if that would be possible...

From your answer I got the opinion that with the existed version it is not likely to achieve that..

For now, let me stop investigating and searching about the options Solaar provided in the existed version.

Thanks.

**Comment by pfps** [comment]
In the current version of Solaar this is not possible.   Mouse gesture processing can only happen when a mouse is in a special mode and right now this special mode is only set when a button diverted to mouse gestures is down.

**Comment by pfps** [comment]
It doesn't seem possible to do this at all, at least in the hardware I have.  The documentation I have appears to indicate that it is possible, but when I try the commands that should set up for gesture processing, the mouse does not respond.   So I guess that this is not possible.
