### ISSUE TITLE
pairing a K220 with a nano receiver paired with a K270

### ISSUE THREAD

**Issue by rxf4e1** [pwr-Solaar/Solaar#2302]
Hello, title says it all, please how do i 
make it pair with the right layout?

**Comment by pfps** [comment]
Pairing in Solaar is process that makes a connection between a mouse or keyboard and a receiver.   But neither of these appear to be receivers, so just what do you want to do?

**Comment by rxf4e1** [comment]
i just wanted it to get the right layout, because it paired with a k270 but i have a k220, is there a way to repair to the right one?

**Comment by rxf4e1** [comment]
sorry if i did no explained my self well, i have a nano receiver that have paired with a k270 keyboard, but my keyboard is a k220, i want to know how do i pair to the right one.

**Comment by pfps** [comment]
Many nano receivers are limited as to which devices they can pair to so it might not be possible to make the pairing you want.

You can try to pair by running `solaar` with the receiver connected to your computer.  This should open up the Solaar main window with the receiver showing in the left-hand side.  Select the receiver and click on "Pair new device" and follow the instructions on the window that pops up.  For a nano receiver a successful pairing may unpair a device that was previously paired with the receiver.

Note that some receivers have only a limited number of successful pairings.

**Comment by rxf4e1** [comment]
Still getting the k270 instead of k220.

**Comment by pfps** [comment]
Then the pairing likely failed because your receiver is incompatible with the K220.  If the pairing failed you should see a pop-up window saying something about a timeout.

**Comment by rxf4e1** [comment]
ok thank you for the support, i'm going to close for now.
