### ISSUE TITLE
Extend Makefile with installation and test targets

### ISSUE THREAD

**Issue by MattHag** [pwr-Solaar/Solaar#2303]
**Information**
- Solaar version: 1.1.11rc4

**Is your feature request related to a problem? Please describe.**
The Solaar installation with all its dependencies (pip, apt, udev etc.) is cumbersome. Although some setup steps for GItHub CI exists, they are not usable for local setup of Solaar. 

**Describe the solution you'd like**
Move the setup commands into a Makefile and use the targets in GitHub workflow files. Thus, the commands are in a single place and also usable for local setups.

**Additional context**
This extends #2263

**Comment by pfps** [comment]
Good idea.  It might be reasonable to set up a bunch of small changes and have 1.1.12 come out only a few weeks after 1.1.11.

**Comment by MattHag** [comment]
I think right after 1.1.11 there should be most of the refactoring, cleanup and modernization tickets tackled. Then new features can be added and tests can be added in parallel at any time.

**Comment by pfps** [comment]
This sounds like a good plan.  Tackle a bunch of small-to-medium tasks to clean up the code and set up better infrastructure.  Then 1.1.12 can be pushed out.

**Comment by MattHag** [comment]
In addition to that change, the setup instructions need to be revised, restructured and simplified. 
- The existing structure is hard to understand.
- It is rather uncertain which setup steps are required for macOS, next to brew.
- The optional and required steps are mixed in a huge paragraph.

As minor support for macOS was added and Windows might be supported as well, the setup instructions need to be split according to OS. They should be clear for an average user, that is able to find the shell and know their operating system.

With this change, the installation for Ubuntu using the latest source code should reduce to the command
```make install_ubuntu```
in the Solaar root directory. It installs the apt and pip dependencies and installs the udev rule.

**Comment by pfps** [comment]
Yes, more makefile entries would be useful.

**Comment by MattHag** [comment]
I don't know other distributions like Fedora, but it should be easy for developers to extend that Makefile and make Solaar installation for development a no brainer.

In the end the Makefile could even be OS agnostic by detecting it with `uname`
https://stackoverflow.com/questions/714100/os-detecting-makefile
