### ISSUE TITLE
Update readme.md and related docs

### ISSUE THREAD

**Issue by MattHag** [pwr-Solaar/Solaar#2328]
**Information**
- Solaar version: 1.1.11

Extend and update the Readme. Visiting Solaar Github page is not inviting and too mich information is cramped onto the first page. Nobody wants to to read all of it on the first visit.

For **users** the most important points will be

- Supported OS
- How does it work and look (screenshots)?
- Which devices are supported?
  - MX Master 3S is definitely missing there
- How to install it?

For **developers** the [input remapper](https://github.com/sezanzeb/input-remapper) has a nice start page with logo and screenshots. Solaar could use

- The logo
- Short description paragraph and supported OS
- Github status Badges for pytest status, test coverage
- Screenshots
- Remove redundant info and move important, but lengthy info to dedicated pages.

P.S. Changelog is commonly written with lowercase l.

**Comment by pfps** [comment]
Yes.  Right now README.md links to docs/index.md.   This should be changed, and the README tightened up.

**Comment by MattHag** [comment]
Yes this should be swapped.

**Comment by pfps** [comment]
PR #2337 should fix this issue.

**Comment by pfps** [comment]
PR #2337 has implemented this.
