### ISSUE TITLE
High CPU usage when moving the pointer fast

### ISSUE THREAD

**Issue by strelec** [pwr-Solaar/Solaar#233]
When I move the mouse really rapidly, the cpu usage reaches 5-7%.

What kind of calculation is Solaar performing on mouse movement? I have thought the only purpose of solaar is to communicate the configuration settings to the mouse via unifying receiver.

**Comment by Lekensteyn** [comment]
Solaar still receives every input event which need to be processed (interpreted). It can likely be optimized though as it should only react on a subset of events. Perhaps all DJ messages (report ID 0x20 and 0x21) can be ignored (have to check whether this is used for device detection or not).

**Comment by strelec** [comment]
Well, that is a sensible thing to do, because currently, Solaar amounts to 3 minutes of CPU time (normal usage), which is 10 minutes shorter battery life on a laptop.

What is the disadvantage of simply killing Solaar, once I get the settings right?

**Comment by Lekensteyn** [comment]
There is no disadvantage during normal, active use. Battery status is already reported through UPower to various tools. You still have to run it when re-inserting your device or when the device is powered off (inactivity sleep included).

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
