### ISSUE TITLE
keyboard double-connected to Bolt receiver causing Solaar to hang

### ISSUE THREAD

**Issue by rp1231** [pwr-Solaar/Solaar#2348]
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.10
- Distribution: NixOs
- Kernel version (ex. `uname -srmo`): `KERNEL VERSION HERE`

**Describe the bug**
Solaar was hanging when there was a previously paired device.
![Screenshot from 2024-02-29 14-09-33](https://github.com/pwr-Solaar/Solaar/assets/47380919/42be5368-6fc0-4e0e-a8ac-ad0a3f65b028)

**To Reproduce**
I had previously paired it both my mouse and keyboard with the bold receiver.
Then I paired the keyboard via bluetooth.
Then I again paired it to the bolt receiver resulting in a ghost version of the keyboard.

**Additional context**
Solaar would start hanging and I would keep getting a popup to close solaar or wait for it to respond.
After waiting for some time I managed to click on the ghost keyboard and unpair it to make the problem go away.

**Comment by pfps** [comment]
Bluetooth pairing doesn't affect the pairing between the keyboard and the Bolt receiver so you should not have paired the device again.  For Unifying receivers it is not possible to pair a device that is already paired to an active receiver but it appears that this is possible for Bolt receivers.  But Solaar shouldn't hang if a device is double-paired.

**Comment by pfps** [comment]
I see that multi-connection devices can be multiply connected to at least Bolt receivers.  But when I do this Solaar doesn't hang in any way.   I don't think that there are any differences between 1.1.10 and the current version of Solaar that would affect this.

So unless you can provide details of just what you were doing when Solaar hung this bug will have to remain unconfirmed.  Either that or you will have to recreate the situation and help diagnose the problem.

**Comment by pfps** [comment]
What I did was have the keyboard paired with the Bolt receiver via connection 1, then pair via bluetooth via connection 2, then pair with the Bolt receiver again via connection 3.  I think I did this by having connection 2 active, then open pairing on the Bolt receiver, then switch to connection 3 (and maybe then turning the keyboard off and on again) and continue with the pairing dialogue.

**Comment by pfps** [comment]
OK.  I don't think that the dual-boot setup is the problem, just that the keyboard is double-connected.   I tried to set up the same situation as far as I am able by performing the steps above but all on the same Linux box, disconnecting the keyboard and receiver between each step.   This should have ended up with the same state for both the receiver and keyboard and a very similar state for the Linux kernel.

I was unable to get Solaar to hang, even with multiple attempts.

So I'm going to improve the title of this issue and close it for now.

**Comment by pfps** [comment]
That shouldn't matter.  Once pairing is done all the information is in the receiver and device.  But maybe there is some residual difference.
