### ISSUE TITLE
Pairing MX Master times out

### ISSUE THREAD

**Issue by jaggernod** [pwr-Solaar/Solaar#235]
STEPS:
- clone the current Solaar repo
- manuall install as stated in README
- run: 

```
bin/solaar pair
```

EXPECTED RESULT:
- Solaar pairs the MX Master

ACTUAL RESULT:
- Solaar shows time out:

```
$ ./solaar pair
Pairing: turn your new device on (timing out in 20 seconds).
solaar: error: pairing failed: device timeout
```

REDPODUCTION:
- 100%

ENVIROMENT:
- master branch, commit: cf27328d13243bab876fb42d441b00cf903e91e5
- ./solar show:

```
$ ./solaar show
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 47A899C6
    Firmware   : 24.01.B0023
    Bootloader : 01.08
    Other      : AA.AC
  Has 0 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)
```

**Comment by jaggernod** [comment]
Noticed that when I disabed ```hidpp10.NOTIFICATION_FLAG.wireless``` it started pairing.
Any ideas why?

```
diff --git a/lib/solaar/cli/pair.py b/lib/solaar/cli/pair.py
index f9e582f..201d43c 100644
--- a/lib/solaar/cli/pair.py
+++ b/lib/solaar/cli/pair.py
@@ -46,8 +46,8 @@ def run(receivers, args, find_receiver, _ignore):
 
 	# check if it's necessary to set the notification flags
 	old_notification_flags = _hidpp10.get_notification_flags(receiver) or 0
-	if not (old_notification_flags & _hidpp10.NOTIFICATION_FLAG.wireless):
-		_hidpp10.set_notification_flags(receiver, old_notification_flags | _hidpp10.NOTIFICATION_FLAG.wireless)
+#	if not (old_notification_flags & _hidpp10.NOTIFICATION_FLAG.wireless):
+#		_hidpp10.set_notification_flags(receiver, old_notification_flags | _hidpp10.NOTIFICATION_FLAG.wireless)
 
 	# get all current devices
 	known_devices = [dev.number for dev in receiver]
```

**Comment by ShachMaT** [comment]
I have the same problem, mouse got good power was close to receiver (5cm) and not pairing.

Mouse is Logitech M510.

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original posters.
