### ISSUE TITLE
Refactor receiver module

### ISSUE THREAD

**Issue by MattHag** [pwr-Solaar/Solaar#2350]
**Information**
- Solaar version: 1.1.11

**Describe the solution you'd like**
The Receiver class contains many branches based on the _receiver_kind_. There's the opportunity to split that with subclasses, which implement specific devices like BoltReceiver, UnifyingReceiver etc. and use the factory pattern to instantiate a proper device.

**Comment by pfps** [comment]
This is a good idea, but the code is fragile and access to some of the hardware is not possible.   A testing methodology will be needed before this is done, with test paths derived from the current code.  For example, the current code will have to be examined to see what assumptions it makes about 27MHz receivers and a test devised to ensure that the expected responses produce the same result in the changed code.
