### ISSUE TITLE
Snipping tool key inputs "S" as long as keyboard is in power save mode

### ISSUE THREAD

**Issue by piratenpanda** [pwr-Solaar/Solaar#2356]
As per https://github.com/pwr-Solaar/Solaar/issues/2352 I'm opening a feature request to try fixing the problem that the Logitech MX Keys S "snipping tool" key inputs "S" as long as it's not fully woken up until the diversion of solaar can take over.

this is with Solaar 1.1.11, Arch Linux, Kernel 7.6.7

**Comment by pfps** [comment]
PR #2382 should fix your problem.   To test it out quit from any running Solaar and then run Solaar as `bin/solaar` from the download directory.   Try triggering the bug.  If you can, then run Solaar as `bin/solaar -ddd`, trigger the bug, and post the output.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #2382, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/2382/head:pull_2382
git checkout pull_2382
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_2382
git fetch origin pull/2382/head
git reset --hard FETCH_HEAD
```

**Comment by piratenpanda** [comment]
So far I can't reproduce the "S" and the snipping tool works fine without having to press the key twice

**Comment by pfps** [comment]
OK, that looks like a win.
