### ISSUE TITLE
Is "udev rule installation" necessary with Ubuntu package?

### ISSUE THREAD

**Issue by skierpage** [pwr-Solaar/Solaar#237]
I installed the Solaar package on Ubuntu 15.04 (using the workaround in #232) and ran `solaar`.  It seems to work, I have a second battery icon in notifications with "Unifying Receiver" and I paired my M705 mouse. The only strangeness is it warns "Wireless Link not encrypted".

Since the package is for an older Ubuntu I read [Manual installation](https://pwr.github.io/Solaar/installation.html) (installation.md). That says 

> Normally USB devices are not accessible for r/w by regular users, so you will need to do a one-time udev rule installation to allow access to the Logitech Unifying Receiver.

It doesn't look like the Solaar ubuntu package install added anything to /etc/udev\* , so I wonder if this section is true for recent Ubuntu.

Thanks for such a nice utility.

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to age.
If you install Solaar  from a package everything should be done for you.  If you are installing yourself, you probably need to follow the installation directions for devices to be set up correctly unless a previous  install from a package did that already.
