### ISSUE TITLE
Upgrade all possible strings to f-string

### ISSUE THREAD

**Issue by MattHag** [pwr-Solaar/Solaar#2372]
- Solaar version: 1.1.11

Although ruff linter and formatter is in place, the string formatting is still old school with .format and %. Use [flynt](https://github.com/ikamensh/flynt) or a similar tool to upgrade all strings with arguments to f-strings.

**Comment by pfps** [comment]
How can this be done and still allow translation?

**Comment by MattHag** [comment]
I'll find it out.
