### ISSUE TITLE
Add Action - "String Key Press" as a Macro inputs that will be translated into multiple key presses.

### ISSUE THREAD

**Issue by EUA** [pwr-Solaar/Solaar#2376]
Currently, it's possible to add such a feature by defining with multiple key presses, but programming it looks really ugly and not possible for long sentences.

Here is what happens while programming only 4 letters!
![Screenshot from 2024-03-10 04-57-05](https://github.com/pwr-Solaar/Solaar/assets/125917/a64298ce-8948-4c66-a8c3-4bbfb55ddd4e)

Instead of that, I want to have an "action" rule like "String "KeyPress" that allows Solaar write text strings as it written from keyboard.

For example, we should add some repeated texts into it like closing words of an emails... And it will be super useful.
Within a key press into unused button at mouse, macro should automatically add the string as a keyboard...

This is a killer feature for me. Doesn't it looks useful and an easy to do for you?

**Comment by pfps** [comment]
This is currently possible with a sequence of KeyPress actions so this is only a convenience.

**Comment by EUA** [comment]
Well, I don't think if anyone try to move that road for 5-10 word sentences with current state. It's not quite possible because 4 letter is enough to fill whole screen due... UI Bug?
I don't think if such a big "text_box" space required for entering a letter only into it. Might be adjusted also.

**Comment by pfps** [comment]
A reason for the big box is that some keys have long names, like `XF86_AudioNext`.

**Comment by pfps** [comment]
I don't see a way forward on this enhancement.

**Comment by EUA** [comment]
Why not implement that box accept a text strings and put characters one by one instead of 1 char per box approach?

**Comment by pfps** [comment]
In part because that's not how input happens.   Instead of  input being by character, input is by simulated keystroke.  That is, input is not an 'A', instead it is left-shift-key down, a-key down, a-key up, left-shift-key up.  And even this is a simplification.
