### ISSUE TITLE
Fine tune `Later` action for different use cases

### ISSUE THREAD

**Issue by akseron** [pwr-Solaar/Solaar#2385]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): 1.1.11, 1.1.11-104-g4a89a79a
- Distribution: Ubuntu 23.10
- Kernel version (ex. `uname -srmo`): Linux 6.7.9-zabbly+ x86_64 GNU/Linux

<details>

```
OUTPUT HERE
```
</details>

**Is your feature request related to a problem? Please describe.**
I have some key / click combinations I am trying to run, which are I believe achievable with minor tweaks to the current way the `Later` action is designed. It is currently in seconds but it would be better to be usable in milliseconds.

**Describe the solution you'd like**
Using a float based value instead of an integer for `Later`, so that some more adjustments are possible  for different use cases. For example, I am trying to assign print screen and selection to a button. This is possible, however due to a pop-up, there is a small delay of about 0.1/0.2 seconds necessary between my two key presses, whereas 1 second is a bit too long.

Thank you!

**Comment by pfps** [comment]
PR #2392 should allow this.  Try it out by changing a Later value to something like 0.1.  I like to check whether rules are working correctly by using an Execute action with notify-send and a short string as the argument.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #2392, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/2392/head:pull_2392
git checkout pull_2392
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_2392
git fetch origin pull/2392/head
git reset --hard FETCH_HEAD
```

**Comment by akseron** [comment]
Hi @pfps thank you for the detailed instructions! The pr works exactly as intended and from what I could tell consistently works. Thank you very much for your time :smile: 

I did notice however, that the input required in the rule editor was '0,1' instead of '0.1'. This is no problem for me, but maybe an interesting thing to note.

**Comment by pfps** [comment]
I expect that that is because you have  a European locale, so the decimal "point" is a comma.
