### ISSUE TITLE
K800 not added to list if already on at launch

### ISSUE THREAD

**Issue by fipm** [pwr-Solaar/Solaar#240]
I have two unifying receivers installed in a multiseat setup (Arch linux). One of the receivers has a T650 and a K800 paired to it. At login the K800 is not listed in the GUI. I have to turn off and on the keyboard to see it in list.

**Comment by TheRojam** [comment]
What is a multiseat setup?
BTW for it works very fine. Exept the special key which are not set in xorg.config

**Comment by Lekensteyn** [comment]
Multiseat is where you have multiple users on the same physical system. So two users, each having a different keyboard + screen.

**Comment by jrbenito** [comment]
@fipm,

I can reproduce this behavior with my M510 mouse + K270 keyboard (both unifying). However, it is not 100% and I could not do any debug yet. I confirm that turn off/on does make it show up.

First I thought it was related to the fact my M510 is not being properly recognized due HID++ version upgrade. However, per your description this might not be the case.

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original posters.
