### ISSUE TITLE
how to trigger pinch out on wayland

### ISSUE THREAD

**Issue by ctrngk** [pwr-Solaar/Solaar#2402]
device: macbook with built-in trackpad
mouse:  Logitech mx master 3s
os: fedora 39 workstation (wayland gnome 45)
solaar 1.1.11

**Question** 
I want to use middle button of mouse to trigger "pinch out" action. How?  Can I execute something to tell the system to "pinch out"?

**Background**
Normally I used two fingers to pinch out/in with trackpad on wayland, which works well for firefox or some other apps.  Now my intention is try to replace trackpad with mouse. 

I used [libinput-gestures -d](https://github.com/bulletmark/libinput-gestures), and the "pinch out" and "pinch in" action of trackpad are, of course,  detected

```
libinput-gestures: session gnome+wayland on Linux-6.7.9-200.fc39.x86_64-x86_64-with-glibc2.38, python 3.12.2, libinput 1.25.0
...
libinput-gestures: device /dev/input/by-path/pci-0000:00:14.0-usbv2-0:5:1.2-event-mouse(event12): bcm5974
libinput-gestures: PINCH in 2 [-7.039999999999997, -1.9900000000000004]
   ....
libinput-gestures: PINCH out 2 [11.030000000000003, 2.3700000000000006]
   ...
```

**Comment by pfps** [comment]
This does not appear to be a question about Solaar but is instead about how trackpad events interact with Linux and Wayland and Gnome.   If you can figure out what the trackpad sends then you can try to figure out how to set up Solaar to emulate it, but you first need to find out what the trackpad does and that has nothing to do with Solaar.

**Comment by pfps** [comment]
Closing due to no response from submitter.
