### ISSUE TITLE
Displaying function lock status - F1 to F12 vs Media Keys - for Logitech ERGO K860

### ISSUE THREAD

**Issue by arnoldoree** [pwr-Solaar/Solaar#2407]
**Information**

- Solaar version: solaar 1.1.10+dfsg-2
- Distribution: Debian Linux - Bookworm
- Kernel version: Linux 6.6.22-gnu x86_64 GNU/Linux [Linux Libre]
- Output of `solaar show` for the target device (if applicable):

<details>

```
  1: Wireless Keyboard ERGO K860
     Device path  : /dev/hidraw5
     WPID         : 4088
     Codename     : ERGO K860
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Polling rate : 20 ms (50Hz)
     Serial number: 6A35F00A
     Model ID:      B35940880000
     Unit ID:       6A35F00A
        Bootloader: BL1 09.00.B0010
          Firmware: MPK 10.00.B0010
             Other: 
     The power switch is located on the top edge.
     Supports 31 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: Bootloader BL1 09.00.B0010 0000EC099C7F01
            Firmware: Firmware MPK 10.00.B0010 4088EC099C7F01
            Firmware: Other   
            Unit ID: 6A35F00A  Model ID: B35940880000  Transport IDs: {'btleid': 'B359', 'wpid': '4088'}
         3: DEVICE NAME            {0005} V0     
            Name: Wireless Keyboard ERGO K860
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
         6: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: ERGO K860
         7: BATTERY STATUS         {1000} V1     
            Battery: 50%, discharging, next level 20%.
         8: REPROG CONTROLS V4     {1B04} V4     
            Key/Button Diversion (saved): {Calculator:Regular, Show Desktop:Regular, Lock PC:Regular, Screen Capture/Print Screen:Regular, Brightness Down:Regular, Brightness Up:Regular, Host Switch Channel 1:Regular, Host Switch Channel 2:Regular, Host Switch Channel 3:Regular, MultiPlatform Search:Regular, Mission Control/Task View:Regular, Previous Fn:Regular, Play/Pause Fn:Regular, Next Fn:Regular, Mute Fn:Regular, Volume Down Fn:Regular, Volume Up Fn:Regular, App Contextual Menu/Right Click:Regular, Right Arrow:Regular, Left Arrow:Regular, Multiplatform App Switch 2:Regular, Fn Inversion/Hot Key:Regular}
            Key/Button Diversion        : {Calculator:Regular, Show Desktop:Regular, Lock PC:Regular, Screen Capture/Print Screen:Regular, Brightness Down:Regular, Brightness Up:Regular, Host Switch Channel 1:Regular, Host Switch Channel 2:Regular, Host Switch Channel 3:Regular, MultiPlatform Search:Regular, Mission Control/Task View:Regular, Previous Fn:Regular, Play/Pause Fn:Regular, Next Fn:Regular, Mute Fn:Regular, Volume Down Fn:Regular, Volume Up Fn:Regular, App Contextual Menu/Right Click:Regular, Right Arrow:Regular, Left Arrow:Regular, Multiplatform App Switch 2:Regular, Fn Inversion/Hot Key:Regular}
         9: CHANGE HOST            {1814} V1     
            Change Host        : 1:PICTCEOMWS08
        10: HOSTS INFO             {1815} V1     
            Host 0 (paired): PICTCEOMWS08
            Host 1 (unpaired): 
            Host 2 (unpaired): 
        11: K375S FN INVERSION     {40A3} V0     
            Swap Fx function (saved): True
            Swap Fx function        : True
        12: ENCRYPTION             {4100} V0     
        13: LOCK KEY STATE         {4220} V0     
        14: KEYBOARD DISABLE KEYS  {4521} V0     
            Disable keys (saved): {Caps Lock:False, Num Lock:False, Scroll Lock:False, Insert:False, Win:False}
            Disable keys        : {Caps Lock:False, Num Lock:False, Scroll Lock:False, Insert:False, Win:False}
        15: MULTIPLATFORM          {4531} V1     
            Set OS (saved): Windows
            Set OS        : Windows
        16: DFUCONTROL SIGNED      {00C2} V0     
        17: DEVICE RESET           {1802} V0    internal, hidden 
        18: unknown:1803           {1803} V0    internal, hidden 
        19: CONFIG DEVICE PROPS    {1806} V5    internal, hidden 
        20: unknown:1813           {1813} V0    internal, hidden 
        21: OOBSTATE               {1805} V0    internal, hidden 
        22: unknown:1830           {1830} V0    internal, hidden 
        23: unknown:1890           {1890} V5    internal, hidden 
        24: unknown:1891           {1891} V5    internal, hidden 
        25: unknown:18A1           {18A1} V0    internal, hidden 
        26: unknown:1DF3           {1DF3} V0    internal, hidden 
        27: unknown:1E00           {1E00} V0    hidden 
        28: unknown:1EB0           {1EB0} V0    internal, hidden 
        29: unknown:1861           {1861} V0    internal, hidden 
        30: unknown:18B0           {18B0} V0    internal, hidden 
     Has 24 reprogrammable keys:
         0: Host Switch Channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         1: Host Switch Channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         2: Host Switch Channel 3     , default: HostSwitch Channel 3        => HostSwitch Channel 3      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         3: Brightness Down           , default: Brightness Down             => Brightness Down           
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:1, group:0, group mask:empty
             reporting: default
         4: Brightness Up             , default: Brightness Up               => Brightness Up             
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:2, group:0, group mask:empty
             reporting: default
         5: Mission Control/Task View , default: Mission Control/Task View   => Mission Control/Task View 
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:3, group:0, group mask:empty
             reporting: default
         6: Multiplatform App Switch 2, default: App Switch                  => App Switch                
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:4, group:0, group mask:empty
             reporting: default
         7: Show Desktop              , default: Show Desktop                => Show Desktop              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:5, group:0, group mask:empty
             reporting: default
         8: MultiPlatform Search      , default: Multiplatform Search        => Multiplatform Search      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:6, group:0, group mask:empty
             reporting: default
         9: Previous Fn               , default: Previous                    => Previous                  
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:7, group:0, group mask:empty
             reporting: default
        10: Play/Pause Fn             , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:8, group:0, group mask:empty
             reporting: default
        11: Next Fn                   , default: Next                        => Next                      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:9, group:0, group mask:empty
             reporting: default
        12: Mute Fn                   , default: Mute                        => Mute                      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:10, group:0, group mask:empty
             reporting: default
        13: Volume Down Fn            , default: Volume Down                 => Volume Down               
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:11, group:0, group mask:empty
             reporting: default
        14: Volume Up Fn              , default: Volume Up                   => Volume Up                 
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:12, group:0, group mask:empty
             reporting: default
        15: Fn Inversion/Hot Key      , default: Fn Inversion                => Fn Inversion              
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        16: Screen Capture/Print Screen, default: Screen Capture              => Screen Capture            
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        17: Calculator                , default: Calculator                  => Calculator                
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        18: App Contextual Menu/Right Click, default: Right Click/App Contextual Menu => Right Click/App Contextual Menu
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        19: Lock PC                   , default: WindowsLock                 => WindowsLock               
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        20: Left Arrow                , default: Keyboard Left Arrow         => Keyboard Left Arrow       
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        21: Right Arrow               , default: Keyboard Right Arrow        => Keyboard Right Arrow      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        22: F Lock                    , default: Do Nothing One              => Do Nothing One            
             is FN, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        23: FN Key                    , default: Do Nothing One              => Do Nothing One            
             nonstandard, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
     Battery: 50%, discharging, next level 20%.
```
</details>

**Is your feature request related to a problem? Please describe.**
Logitech have somehow decided that media keys are more important and fundamental on a keyboard that at £120.00 is clearly the preserve of professional applications.

They have further to this made the default for the combo media keys and function keys, the media keys state. With the function keys state only being accessible through function lock + ESCAPE, with the keyboard reverting to media keys state where the keyboard is not used for a period of time.

Moreover, there is no physical indication as to the the function vs media keys state of the keyboard. Meaning that you can be in the middle of a complex workflow, try to use the function keys say for a file copy, and find that you are instead prosecuting some irrelevant media function.

**Describe the solution you'd like**
(1) I would like Solaar to integrate a system tray indication of the present function vs media key state of the keyboard.

(2) I would like Solaar to include an option to keep the keyboard in its function keys state, or to at least change the default of the keyboard to the function key state.

**Describe alternatives you've considered**
I have contacted Logitech and sought a solution, but they have simply confirmed that the above was a design decision made by their teams.

**Additional context**
N/A

**Comment by pfps** [comment]
Solaar should already do this, as it pushes settings to devices  whenever they reconnect after going into power-saving mode.   There was one exclusion - pressing a function key while in power-saving mode can result in the default behaviour - but this should be fixed in the version of Solaar in this repository.

**Comment by arnoldoree** [comment]
Thanks for the information. I've just upgraded to Debian official repository package version "solaar (1.1.11+dfsg-2)" [ https://packages.debian.org/trixie/solaar ]. I hope this is the same pakcage version you are referring to? 

I'll test the behaviour of the new package for a couple of days, paying special attention to power-saving cycles. Wnd with all being well will then close this issue.

**Comment by pfps** [comment]
I suspect that this is just version 1.1.11.   You probably need to download Solaar from this repository and then run `bin/solaar` from the download directory (after quitting any running copies of Solaar).

**Comment by arnoldoree** [comment]
I see. I compared the latest release version in this Solaar github repository 1.1.11 [https://github.com/pwr-Solaar/Solaar/releases/tag/1.1.11] with the above Debian trixie official repository version, and found them to both be 1.1.11. 

So am I right in understanding that rather you mean I should install the 'source code' of the master branch of this repository itself? 

If I am to download and run bin/solaar directly, does that mean that I will now be working with an alternate Solaar 'codebase', which will no longer be initialized and controlled by systemd?

And if I did want to install the master branch, but retain the full ordinary init system functionality / control, are the instructions to follow the ones at |https://pwr-solaar.github.io/Solaar/installation|> "Installating from GitHub", or otherwise?

**Comment by pfps** [comment]
Yes, there are changes in this repository that affect how devices report their initial message after they are in power-saving mode.

If you have Solaar already installed from a package then you should be able to just quit out of any running Solaar and instead run `bin/solaar` from the download directory after cloning this repository, as any other required actions will have been performed by the package installation.

This leaves any autostarted Solaar alone and doesn't affect anything in systemd, but I am not aware of any interaction between systemd and Solaar.

**Comment by arnoldoree** [comment]
Would this setup mean that every time I rebooted my computer I would need to shut down the package installed Solaar, and then re-execute bin/solaar as cloned from the repo?

**Comment by pfps** [comment]
Hopefully not, unless the package also installed Solaar as a startup program.  In this case you should figure out how Solaar is started and arrange for that to start the downloaded Solaar instead.

**Comment by arnoldoree** [comment]
Alright then will look into the relevant particulars of the Debian package. Having said that, would it not be more straight forward just to build an apt/deb package directly from this repository's master brance source code in accordance to the instructions at this location: https://pwr-solaar.github.io/Solaar/installation > Installating from GitHub?

**Comment by arnoldoree** [comment]
Okay, I understand. I'll look into it the particulars of the Debian package construct, and if the findings are adverse or overly complicating, I'll create my own systemd unit file automatically executing bin/solar as downloaded from this repository. And will further wait for the release of the Debian package with the sought updates.

**Comment by arnoldoree** [comment]
I've undertaken the aforementioned course of action.

(1) I cloned solaar from this repository, and coped the directory into /opt/solaar

(2) I used dpkg -L to identify the files copied / created by the debian package
<details>
dpkg -L solaar
/.
/etc
/etc/xdg
/etc/xdg/autostart
/etc/xdg/autostart/solaar.desktop
/usr
/usr/bin
/usr/bin/solaar
/usr/lib
/usr/lib/udev
/usr/lib/udev/rules.d
/usr/lib/udev/rules.d/60-solaar.rules
/usr/share
/usr/share/applications
/usr/share/applications/solaar.desktop
/usr/share/doc
/usr/share/doc/solaar
/usr/share/doc/solaar/changelog.Debian.gz
/usr/share/doc/solaar/changelog.gz
/usr/share/doc/solaar/copyright
/usr/share/icons
/usr/share/icons/hicolor
/usr/share/icons/hicolor/32x32
/usr/share/icons/hicolor/32x32/apps
/usr/share/icons/hicolor/32x32/apps/solaar-light_000.png
/usr/share/icons/hicolor/32x32/apps/solaar-light_020.png
/usr/share/icons/hicolor/32x32/apps/solaar-light_040.png
/usr/share/icons/hicolor/32x32/apps/solaar-light_060.png
/usr/share/icons/hicolor/32x32/apps/solaar-light_080.png
/usr/share/icons/hicolor/32x32/apps/solaar-light_100.png
/usr/share/icons/hicolor/32x32/apps/solaar-light_unknown.png
/usr/share/icons/hicolor/scalable
/usr/share/icons/hicolor/scalable/apps
/usr/share/icons/hicolor/scalable/apps/solaar-attention.svg
/usr/share/icons/hicolor/scalable/apps/solaar-init.svg
/usr/share/icons/hicolor/scalable/apps/solaar-symbolic.svg
/usr/share/icons/hicolor/scalable/apps/solaar.svg
/usr/share/locale
/usr/share/locale/ca
/usr/share/locale/ca/LC_MESSAGES
/usr/share/locale/ca/LC_MESSAGES/solaar.mo
/usr/share/locale/cs
/usr/share/locale/cs/LC_MESSAGES
/usr/share/locale/cs/LC_MESSAGES/solaar.mo
/usr/share/locale/da
/usr/share/locale/da/LC_MESSAGES
/usr/share/locale/da/LC_MESSAGES/solaar.mo
/usr/share/locale/de
/usr/share/locale/de/LC_MESSAGES
/usr/share/locale/de/LC_MESSAGES/solaar.mo
/usr/share/locale/el
/usr/share/locale/el/LC_MESSAGES
/usr/share/locale/el/LC_MESSAGES/solaar.mo
/usr/share/locale/es
/usr/share/locale/es/LC_MESSAGES
/usr/share/locale/es/LC_MESSAGES/solaar.mo
/usr/share/locale/fi
/usr/share/locale/fi/LC_MESSAGES
/usr/share/locale/fi/LC_MESSAGES/solaar.mo
/usr/share/locale/fr
/usr/share/locale/fr/LC_MESSAGES
/usr/share/locale/fr/LC_MESSAGES/solaar.mo
/usr/share/locale/hr
/usr/share/locale/hr/LC_MESSAGES
/usr/share/locale/hr/LC_MESSAGES/solaar.mo
/usr/share/locale/it
/usr/share/locale/it/LC_MESSAGES
/usr/share/locale/it/LC_MESSAGES/solaar.mo
/usr/share/locale/ja
/usr/share/locale/ja/LC_MESSAGES
/usr/share/locale/ja/LC_MESSAGES/solaar.mo
/usr/share/locale/nb
/usr/share/locale/nb/LC_MESSAGES
/usr/share/locale/nb/LC_MESSAGES/solaar.mo
/usr/share/locale/nl
/usr/share/locale/nl/LC_MESSAGES
/usr/share/locale/nl/LC_MESSAGES/solaar.mo
/usr/share/locale/nn
/usr/share/locale/nn/LC_MESSAGES
/usr/share/locale/nn/LC_MESSAGES/solaar.mo
/usr/share/locale/pl
/usr/share/locale/pl/LC_MESSAGES
/usr/share/locale/pl/LC_MESSAGES/solaar.mo
/usr/share/locale/pt
/usr/share/locale/pt/LC_MESSAGES
/usr/share/locale/pt/LC_MESSAGES/solaar.mo
/usr/share/locale/pt_BR
/usr/share/locale/pt_BR/LC_MESSAGES
/usr/share/locale/pt_BR/LC_MESSAGES/solaar.mo
/usr/share/locale/ro
/usr/share/locale/ro/LC_MESSAGES
/usr/share/locale/ro/LC_MESSAGES/solaar.mo
/usr/share/locale/ru
/usr/share/locale/ru/LC_MESSAGES
/usr/share/locale/ru/LC_MESSAGES/solaar.mo
/usr/share/locale/sk
/usr/share/locale/sk/LC_MESSAGES
/usr/share/locale/sk/LC_MESSAGES/solaar.mo
/usr/share/locale/sr
/usr/share/locale/sr/LC_MESSAGES
/usr/share/locale/sr/LC_MESSAGES/solaar.mo
/usr/share/locale/sv
/usr/share/locale/sv/LC_MESSAGES
/usr/share/locale/sv/LC_MESSAGES/solaar.mo
/usr/share/locale/tr
/usr/share/locale/tr/LC_MESSAGES
/usr/share/locale/tr/LC_MESSAGES/solaar.mo
/usr/share/locale/zh_CN
/usr/share/locale/zh_CN/LC_MESSAGES
/usr/share/locale/zh_CN/LC_MESSAGES/solaar.mo
/usr/share/locale/zh_TW
/usr/share/locale/zh_TW/LC_MESSAGES
/usr/share/locale/zh_TW/LC_MESSAGES/solaar.mo
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/solaar.1.gz
/usr/share/metainfo
/usr/share/metainfo/io.github.pwr_solaar.solaar.metainfo.xml
/usr/share/python3
/usr/share/python3/runtime.d
/usr/share/python3/runtime.d/solaar.rtupdate
/usr/share/solaar
/usr/share/solaar/lib
/usr/share/solaar/lib/hidapi
/usr/share/solaar/lib/hidapi/__init__.py
/usr/share/solaar/lib/hidapi/hidapi.py
/usr/share/solaar/lib/hidapi/hidconsole.py
/usr/share/solaar/lib/hidapi/udev.py
/usr/share/solaar/lib/keysyms
/usr/share/solaar/lib/keysyms/__init__.py
/usr/share/solaar/lib/keysyms/generate.py
/usr/share/solaar/lib/keysyms/keysymdef.py
/usr/share/solaar/lib/logitech_receiver
/usr/share/solaar/lib/logitech_receiver/__init__.py
/usr/share/solaar/lib/logitech_receiver/base.py
/usr/share/solaar/lib/logitech_receiver/base_usb.py
/usr/share/solaar/lib/logitech_receiver/common.py
/usr/share/solaar/lib/logitech_receiver/descriptors.py
/usr/share/solaar/lib/logitech_receiver/device.py
/usr/share/solaar/lib/logitech_receiver/diversion.py
/usr/share/solaar/lib/logitech_receiver/hidpp10.py
/usr/share/solaar/lib/logitech_receiver/hidpp20.py
/usr/share/solaar/lib/logitech_receiver/i18n.py
/usr/share/solaar/lib/logitech_receiver/listener.py
/usr/share/solaar/lib/logitech_receiver/notifications.py
/usr/share/solaar/lib/logitech_receiver/receiver.py
/usr/share/solaar/lib/logitech_receiver/settings.py
/usr/share/solaar/lib/logitech_receiver/settings_templates.py
/usr/share/solaar/lib/logitech_receiver/special_keys.py
/usr/share/solaar/lib/logitech_receiver/status.py
/usr/share/solaar/lib/solaar
/usr/share/solaar/lib/solaar/__init__.py
/usr/share/solaar/lib/solaar/cli
/usr/share/solaar/lib/solaar/cli/__init__.py
/usr/share/solaar/lib/solaar/cli/config.py
/usr/share/solaar/lib/solaar/cli/pair.py
/usr/share/solaar/lib/solaar/cli/probe.py
/usr/share/solaar/lib/solaar/cli/profiles.py
/usr/share/solaar/lib/solaar/cli/show.py
/usr/share/solaar/lib/solaar/cli/unpair.py
/usr/share/solaar/lib/solaar/commit
/usr/share/solaar/lib/solaar/configuration.py
/usr/share/solaar/lib/solaar/gtk.py
/usr/share/solaar/lib/solaar/i18n.py
/usr/share/solaar/lib/solaar/listener.py
/usr/share/solaar/lib/solaar/tasks.py
/usr/share/solaar/lib/solaar/ui
/usr/share/solaar/lib/solaar/ui/__init__.py
/usr/share/solaar/lib/solaar/ui/about.py
/usr/share/solaar/lib/solaar/ui/action.py
/usr/share/solaar/lib/solaar/ui/config_panel.py
/usr/share/solaar/lib/solaar/ui/diversion_rules.py
/usr/share/solaar/lib/solaar/ui/icons.py
/usr/share/solaar/lib/solaar/ui/notify.py
/usr/share/solaar/lib/solaar/ui/pair_window.py
/usr/share/solaar/lib/solaar/ui/tray.py
/usr/share/solaar/lib/solaar/ui/window.py
/usr/share/solaar/lib/solaar/upower.py
/usr/share/solaar/lib/solaar/version
/usr/share/solaar/lib/solaar-1.1.11.egg-info
/usr/share/solaar/lib/solaar-1.1.11.egg-info/PKG-INFO
/usr/share/solaar/lib/solaar-1.1.11.egg-info/dependency_links.txt
/usr/share/solaar/lib/solaar-1.1.11.egg-info/requires.txt
/usr/share/solaar/lib/solaar-1.1.11.egg-info/top_level.txt
</details>

(3.) I updte d the desktop files at:

(3.a) /etc/xdg/autostart/solaar.desktop
<details>
[Desktop Entry]
Name=Solaar
Comment=Logitech Unifying Receiver peripherals manager
Comment[fr]=Gestionnaire de périphériques pour les récepteurs Logitech Unifying
Comment[hr]=Upravitelj Logitechovih uređaja povezanih putem Unifying i Nano prijemnika
Comment[ru]=Управление приёмником Logitech Unifying Receiver
Comment[de]=Logitech Unifying Empfänger Geräteverwaltung
Comment[es]=Administrador de periféricos de Logitech Receptor Unifying
Comment[pl]=Menedżer urządzeń peryferyjnych odbiornika Logitech Unifying
**Exec=/opt/solaar/bin/solaar --window=hide**
Icon=solaar
StartupNotify=true
Terminal=false
Type=Application
Keywords=logitech;unifying;receiver;mouse;keyboard;
Categories=Utility;GTK;
#Categories=Utility;GTK;Settings;HardwareSettings;
</details>

(3.b) /usr/share/applications/solaar.desktop
<details>
[Desktop Entry]
Name=Solaar
Comment=Logitech Unifying Receiver peripherals manager
Comment[fr]=Gestionnaire de périphériques pour les récepteurs Logitech Unifying
Comment[hr]=Upravitelj Logitechovih uređaja povezanih putem Unifying i Nano prijemnika
Comment[ru]=Управление приёмником Logitech Unifying Receiver
Comment[es]=Administrador de periféricos de Logitech Receptor Unifying
Exec=/opt/solaar/bin/solaar
Icon=solaar
StartupNotify=true
Terminal=false
Type=Application
Keywords=logitech;unifying;receiver;mouse;keyboard;
Categories=Utility;GTK;
#Categories=Utility;GTK;Settings;HardwareSettings;
X-GNOME-UsesNotifications=true
</details>

(4) I replaced /bin/solaar with a symbolic link to /opt/solaar/bin/solaar
<details>
lrwxrwxrwx  1 root   root          22 Mar 27 07:38 solaar -> /opt/solaar/bin/solaar
-rwxr-xr-x  1 root   root        2005 Feb 22 07:19 solaar.legacy
-rwxr-xr-x  2 root   root        2010 Mar 27 07:15 solaar.legacy2
</details>
---
At this stage solaar is running with the icon available in the system tray.

How would I know that the minor version update has taken effect. As the applications hows only version 1.1.11?

**Comment by pfps** [comment]
What is the output of `solaar --version`?    A version of Solaar running from a download should include commit information, like `solaar 1.1.11-126-g90285d55`.

**Comment by arnoldoree** [comment]
The output to "solaar--version -&- /opt/solaar/bin/solaar --version" is: 
- "solaar 1.1.11-158-g04a818f2"

Which I am seeing is quite different from your version number, but yet was changed from the previous version number before the above procedure.

The git clone command used was:
"git clone --branch master https://github.com/pwr-Solaar/Solaar.git"

Having said the above, with my current version number I'm still getting the undesirable default media key behaviour with this version.

I'm going to switch tactics. Purge the apt package completely, and then manually execute directly from "the correct" git cloned version. So that I can first of all validate the correct behaviour. Further to which I will worry about auto start.

If you could kindly provide me the git clone command to end up with the exact version number you have printed. That will be great.

**Comment by pfps** [comment]
The commit is going to be different - it comes from whatever the current commit is and showed the output from the version of Solaar that is in pypip.   When I switch to the version that is current in GitHub Solaar shows the same commit that you are showing.

**Comment by arnoldoree** [comment]
Thanks for confirming the above. I'll proceed (next week) to do a manual / from-scratch install from the same codebase already cloned; with the aforementioned view to validating the desired retention of function key state on wake from power saving mode.
