### ISSUE TITLE
bluez 5.73 causes problems with Bluetooth-connected devices

### ISSUE THREAD

**Issue by pfps** [pwr-Solaar/Solaar#2424]
A change in bluez 5.73 causes Solaar to no longer detect when Bluetooth-connected devices reconnect.  Settings for these devices will remain in their default state when reconnecting after going into a power-saving mode or being turned off and on.  For example, function keys may change behavior or diverted keys become undiverted.

The cause of the issue is the same as for https://github.com/bluez/bluez/issues/778.  

The best workaround for now is probably to quit Solaar and restart it.

**Comment by tonymartino** [comment]
I swap my mouse between different devices frequently. This sounds like the reason my scroll wheel sensitivity is reset to low every time I reconnect the mouse to my Fedora 39 machine running bluez 5.70-3.

**Comment by pfps** [comment]
This problem only showed up with bluez 5.73 and should not affect bluez 5.70.

**Comment by tonymartino** [comment]
Apologies, the machine is running 5.73

`bluez.x86_64                                         5.73-3.fc39                             @updates     `

**Comment by pfps** [comment]
Yes, this is almost certainly the cause.

**Comment by pfps** [comment]
Version 5.73 of bluez is causing other problems, including delays in starting up Solaar if there is a Bluetooth connection where the device is not active on the connection.
