### ISSUE TITLE
ModuleNotFoundError: No module named 'evdev'

### ISSUE THREAD

**Issue by Augusto7743** [pwr-Solaar/Solaar#2431]
Hello.
Thanks for reading my topic.
Here is Lubuntu ( Ubuntu using LXQT ) 20.04 and installed Solaar from PPA.
Mouse is an model M90 USB wired.

When trying launch Solaar not start and is showed the error message lines

====
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/gtk.py", line 157, in main
    import solaar.listener as listener
  File "/usr/share/solaar/lib/solaar/listener.py", line 31, in <module>
    from logitech_receiver import notifications as _notifications
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 25, in <module>
    from . import diversion as _diversion
  File "/usr/share/solaar/lib/logitech_receiver/diversion.py", line 35, in <module>
    import evdev
ModuleNotFoundError: No module named 'evdev'
====

That behavior is an bug or is because the mouse is an simple model using wired usb ?

Have an nice week.

**Comment by pfps** [comment]
See Issue #2422.

This appears to be a problem with the distribution.

**Comment by Augusto7743** [comment]
Your reply has an information about an solution. Thanks.
Installed python3-evdev and now Solaar start, but not show any connected devices.
Solaar works with Logitech simple mouse model M90 usb wired too ?

**Comment by pfps** [comment]
Not all Logitech devices use the protocol that Solaar supports, particularly some low-end devices.

**Comment by Augusto7743** [comment]
Thanks very much for your reply.
Possibly not work with my mouse model.
Have an nice week and good luck in your path.
