### ISSUE TITLE
Always use english letters

### ISSUE THREAD

**Issue by DanyloTrofymov** [pwr-Solaar/Solaar#2437]
Is it possible to make Keypress always use english letters? e.g. when I use rule below in English, it works fine(I see 😍), but once i switch no ukrainian language(cyryllic symbols) i see 1а60в and the message sends(enter is pressed)

```
---
- Key: [Emoji Smiley Heart Eyes, pressed]
- KeyPress:
  - [Control_L, Shift_L, u]
  - click
- And:
  - KeyPress:
    - ['1', f, '6', '0', d, KP_Enter]
    - click
...
```

**Comment by pfps** [comment]
What exactly did you do?   Did the actual rule change or did you switch languages and then try to create a rule? Screenshots might help.

**Comment by DanyloTrofymov** [comment]
I mean when the rule is already created, and I switch language - it seems like keys are emulated not by letters but by it's key numbers which causes some issues with other languages. Here is webm
[Screencast 2024-04-22 11:34:13.webm](https://github.com/pwr-Solaar/Solaar/assets/72090683/c27cdc43-26f8-421c-a62c-327e33be1c4f)

**Comment by DanyloTrofymov** [comment]
Also I've noticed that when i am trying to emulate Thumbs Up emoji with U+1F44D unicode, 4 is emulated only once, so +1F44D becomes +1F4D and I see other weird symbol instead of emoji

**Comment by pfps** [comment]
The translation from regular keyboard input signals to information seen by applications is done by the Linux input system and window system and even other part of Linux.  All the Solaar keypress action can do is simulate regular keyboard input signals.   These signals are then transformed and made available to programs.

So it appears that Solaar has nothing to do with the switch and there is no way to do what you are requesting.

**Comment by DanyloTrofymov** [comment]
Ok, thank you. I am suggesting you to check something like keyboard-switch library. The main idea is to check if language is english, then if not - remember previous one, then switch language, simulate keypress, and then switch it back to remembered one.

 And what about the issue with simulating  '4' only once? Do you know about it?

**Comment by pfps** [comment]
This is beyond the scope of Solaar.  

As far as the single simulation, you probably need several keypress actions so that the 4 is released before being pressed again.

**Comment by pfps** [comment]
If you have a reliable way of doing this then, sure, submit a PR.   It will be checked to see whether it works on other computers and may end up in Solaar if it is deemed that the scope of Solaar can be expanded.

**Comment by DanyloTrofymov** [comment]
1. Do you have any documentation or codestyle to make it heigh-qualuty? 
2. Shoud this functionality be optional?

**Comment by pfps** [comment]
Solaar has a code style.   If you clone the Solaar repository you will also get the code style control files.  I'm not sure if you need to do anything more to have your code style-checked with you commit.

I'm fine with not having a command line flag for this for now.   I think the first thing to do is to see whether the capability will work in other settings.

**Comment by pfps** [comment]
As far as I can tell changing the keyboard map does not affect the input when using xtest.  

Using this rule
```
---
- MouseGesture: Mouse Left
- KeyPress:
  - y
  - click
...
```

I see the following when typing the 'y' key on my keyboard and then performing a mouse-left gesture each time after the `setxkbmap` command:

```
idefix Solaar> setxkbmap us
idefix Solaar> yy
yy: Command not found.
idefix Solaar> setxkbmap de
idefix Solaar> zy
zy: Command not found.
idefix Solaar> setxkbmap us
idefix Solaar> yy
```

**Comment by pfps** [comment]
Part of the problem is that there are programs that modify the keyboard layout.   I have iBus running, and that resets the keyboard layout to `us` periodically.

**Comment by pfps** [comment]
This appears to be something that Solaar cannot control.
