### ISSUE TITLE
Solaar catches xbox controller 

### ISSUE THREAD

**Issue by Svenum** [pwr-Solaar/Solaar#2440]
Solaar catches my xbox controller and then he does not work. If I plug the controller in and THEN start solaar it works but the other way around not.

solaar -ddd:

```
2024-04-20 17:10:10,467,467    DEBUG [MainThread] hidapi.udev: Dbus event add Device('/sys/devices/pci0000:00/0000:00:08.1/0000:c5:00.3/usb1/1-2/1-2.1/1-2.1:1.0/gip0/gip0.1/0003:045E:0B02.0020/hidraw/hidraw21')
2024-04-20 17:10:10,468,468     INFO [MainThread] hidapi.udev: Report Descriptor not processed for DEVICE /dev/hidraw21 BID 0003 VID 0000045E PID 00000B02: No module named 'hid_parser'
```

solaar is the latest 1.1.12-rc1 release (with your last changes @pfps )

**Comment by pfps** [comment]
Please provide the total output of `solaar -ddd` for the case where the problem occurs.

**Comment by pfps** [comment]
There is a problem uncovered by the short output you provided.  Solaar now includes a version of hid_parser but it is not installed correctly.

**Comment by pfps** [comment]
PR #2441 should correctly install the included hid_parser.  It might fix your problem.

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #2441, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/2441/head:pull_2441
git checkout pull_2441
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_2441
git fetch origin pull/2441/head
git reset --hard FETCH_HEAD
```

**Comment by Svenum** [comment]
Seems to not fix it. But now the controller behaves the same even if solaar is completly closed. So maybe not solaar related.... I will try other tings. But here are anyway the logs maybe you could finde something:
[solaar.log](https://github.com/pwr-Solaar/Solaar/files/15049260/test.log)

**Comment by Svenum** [comment]
Ok, sorry for the wrong alarm. I disabled the xone and xpadneo kernel module. Now it seems to work with the builtin ones.

**Comment by pfps** [comment]
Solaar shouldn't do anything to non-Logitech devices (except determine that they are not Logitech devices and this shouldn't actually perform any interactions with the device).

**Comment by Svenum** [comment]
Yeah, it was a unfortunate coincidence. I closed solaar and it worked. And then I started solaar with -ddd and saw the messages while plugging the controller in. So I ment that this was the issue. The real issue is this: https://github.com/atar-axis/xpadneo/issues/457 I think.
