### ISSUE TITLE
ModuleNotFoundError: No module named 'solaar' 

### ISSUE THREAD

**Issue by ArthurPeabody** [pwr-Solaar/Solaar#2454]
When I run solaar, I get:
<blockquote>
<pre>
Traceback (most recent call last):
  File "/usr/bin/solaar", line 54, in 
    import solaar.gtk
ModuleNotFoundError: No module named 'solaar'
</pre>
</blockquote>

Python 3.11.9 
Slackware 15.0 
Solar 1.1.11 (installed from slackbuilds.org package)
Linux 6.8.7 x86_64 GNU/Linux 

There is no ~/.config/solaar/  There is nothing in ~/.tmp/

I think the error means it can't find solaar.gtk.py, but don't see how that can be right.  I assume I'm doing something wrong.

**Comment by ArthurPeabody** [comment]
Thanks.  When I run python --version, it reports version 3.11.9.  The Solaar package I installed installs its libraries in /lib/python311 How does Solaar have a different opinion?

Slackware has a python2.7 package, apparently for support for some python2 apps.  I uninstalled that.  That made no difference.

**Comment by pfps** [comment]
All this is a function of how Python software is set up on your system.  Somehow the Solaar main program cannot find the Solaar libraries. Without knowledge of how your system is set up, there isn't much that can be done here.

**Comment by ArthurPeabody** [comment]
They were installed in /lib/python3.11/site-packages instead of /usr/lib64/python3.11/site-packages

**Comment by ArthurPeabody** [comment]
Yes.  I never blamed Solaar.  I wanted to understand the meaning of the error.  I have already posted a query with the distribution.  Perhaps my raising the issue may help others who have the same problem.
