### ISSUE TITLE
Left Alt not being pressed down while holding the Forward button

### ISSUE THREAD

**Issue by benoitex** [pwr-Solaar/Solaar#2464]
- Solaar version: 1.1.12
- Distribution: Ubuntu 22.04
- Kernel version (ex. `uname -srmo`): 6.5.0-28-generic
- Output of `solaar show`:

<details>

```
12:07:30,685    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (17) => r[20 01 0200 0001F0FF00004E00000000]
12:07:30,719    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (17) => r[20 01 0200 0001000000003D00000000]
12:07:30,929    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (17) => r[11 01 0A00 00560000000000000000000000000000]
12:07:30,929    DEBUG [ReceiverListener:hidraw5] logitech_receiver.notifications: <Device(1,407B,MX Vertical Wireless Mouse,CA7E3F12)>: notification for feature REPROG CONTROLS V4, report 0, data 00560000000000000000000000000000
12:07:30,929    DEBUG [ReceiverListener:hidraw5] logitech_receiver.notifications: <Device(1,407B,MX Vertical Wireless Mouse,CA7E3F12)>: diverted controls pressed: 0x56, 0x0, 0x0, 0x0
12:07:30,930     INFO [ReceiverListener:hidraw5] logitech_receiver.diversion: KeyPress action: ['Alt_L'], modifiers 0 ['0x40']
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

[Capture d’écran du 2024-05-05 13-50-34](https://github.com/pwr-Solaar/Solaar/assets/168964660/e4f59e01-ce86-4a16-9adc-9cccd9ed5a90)

I've assigned the Forward button to the Left Alt key, but I can't keep it pressed down as long as I hold the forward button. The Alt input only functions for a fraction of a second.

Currently, this setup functions with the Left Alt keyboard key, and it also performs as expected on Windows with the Logitech software.

I attempted to check if there was a conflict with the alternate keys configuration, but since the keyboard key is working, I must assume it's a problem related to Solaar.

**Comment by pfps** [comment]
It appears that you want the Left Alt key simulated down as long as you press the Forward button.  You need two rules for that one triggering on each of the pressed and released actions for the button and then depressing or releasing the key.

**Comment by benoitex** [comment]
Thanks, setting those rules did the trick: 

![image](https://github.com/pwr-Solaar/Solaar/assets/168964660/142f5235-50db-4f0c-baab-5f83035856eb)

I don't quite understand the difference between depressed/released and why I needed to associate Press Forward with Depress Alt, but hey it works.
