### ISSUE TITLE
Please provide a (signed) Release file for the apt repository

### ISSUE THREAD

**Issue by fastcat** [pwr-Solaar/Solaar#247]
Newer versions of apt complain about your repo thus on every `apt-get update`:

```
W: The repository 'http://pwr.github.io/Solaar/packages ./ Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Please provide a signed Release file.  Noobs will probably need some quick instructions on how to import your key, also.

**Comment by ChristianBeer** [comment]
I would second that. This is going to be a problem with the next stable version of Debian for sure.

**Comment by hobarrera** [comment]
Tags can easily be signed with `git tag -s`. Can you guys use that? Sounds like it would interfere minimally with the dev's workflow.

**Comment by maugsburger** [comment]
now the complete repository is dead:
Err http://pwr.github.io/Solaar/packages ./ Sources            
  Empty files can't be valid archives

http://pwr.github.io/Solaar/packages/ => 404

**Comment by fastcat** [comment]
> Tags can easily be signed with git tag -s. Can you guys use that? Sounds like it would interfere minimally with the dev's workflow.

That's not how apt repository signing works.

There are some very simple tools to manage a small apt repo like this.  I use reprepro (https://mirrorer.alioth.debian.org/) for some things like this locally, but there are other similar tools too.

**Comment by hobarrera** [comment]
> There are some very simple tools to manage a small apt repo like this. I use reprepro (https://mirrorer.alioth.debian.org/) for some things like this locally, but there are other similar tools too.

This isn't an apt repository, but a distribution-agnostic app. Does Debian really require all upstreams to alter their repositories in order to be packaged into Debian?

**Comment by fastcat** [comment]
This package's github pages tries to provide an apt repository, but the format it uses is no longer supported, that's what this ticket is about, not the core solaar software.

**Comment by SlySven** [comment]
Debian (and I guess other downstream derivatives) likes to authenticate packages so that a miscellaneous `.deb` file a *sysop* tries to load into their system can be proven to be what it claims to be (don't forget that Debian and others serve packages from mirrors around the World so the files can come from a multitude of places) so signing the package is not such a stupid idea as it seems.  I think it just results in a suitable `.sig` file alongside the `.deb` file with the same name - and the project owner to provide (publish) the **Public** key used when the **Private** one is used to generate the signature file from the package file.

Package managers WILL moan if asked to install *Unsigned* packages as a heads-up that the authenticity cannot be confirmed and they *may* mark them also in any package listing display they provide.

@fastcat 's suggestion:

> There are some very simple tools to manage a small apt repo like this. I use reprepro (https://mirrorer.alioth.debian.org/) for some things like this locally, but there are other similar tools too.

does seem to be something to look into, IMHO.

**Comment by Lekensteyn** [comment]
Unauthenticated packages over cleartext HTTP, what can possibly go wrong...?

Have you tried the Ubuntu PPA? There is no native code, so it should just work (in theory). You do have to watch out for the Python version that is used by a release though.

**Comment by MagicFab** [comment]
For Debian packages updates, see #288 . tl;dr: there aren't any at the moment.

**Comment by pfps** [comment]
There have been quite a few changes to solaar over the past few years so this issue may have already been addressed. If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still running solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by MagicFab** [comment]
This was about the separate Debian repository, when it existed.

It doesn't anymore, because Solaar is a standard package in Debian. This issue should be closed.

**Comment by fastcat** [comment]
Indeed!
