### ISSUE TITLE
How to trigger individual button action while maintaining combination of others?

### ISSUE THREAD

**Issue by ctrngk** [pwr-Solaar/Solaar#2470]
I used to hold the back button together with scrolling up/down to control page's zoom in/out, which works perfectly.  
Now I would like to click the back button individually to trigger back to normal size, i.e. control + 0,  but I don't know how. 

![Screenshot from 2024-05-08 12-59-48](https://github.com/pwr-Solaar/Solaar/assets/16743578/41940e95-37c8-4be6-b6fe-f443b78be178)

```
---
- KeyIsDown: Back Button
- And:
  - Test: [hires_wheel_up, 0x1]
- KeyPress:
  - [Control_L, Shift_L, equal]
  - click
...
---
- KeyIsDown: Back Button
- And:
  - Test: [hires_wheel_down, 0x1]
- KeyPress:
  - [Control_L, minus]
  - click
...
--- []
...
---
- Test: [hires_wheel_down, 0x5]
- MouseScroll: [0x0, 0x0]
- MouseScroll: [0x0, 0x1]
...
---
- Test: [hires_wheel_up, 0x5]
- MouseScroll: [0x0, 0x0]
- MouseScroll: [0x0, -0x1]
...
--- []
...
```

**Comment by pfps** [comment]
From https://pwr-solaar.github.io/Solaar/rules:
> Key conditions are true if the Logitech name of the current diverted key or button being pressed is their string argument. Alternatively, if the argument is a list [name, action] where action is either 'pressed' or 'released', the key down or key up events of name argument are matched, respectively. Logitech key and button names are shown in the Key/Button Diversion setting. These names are also shown in the output of solaar show in the ‘reprogrammable keys’ section. Only keys or buttons that have ‘divertable’ in their report can be diverted. Some keyboards have Gn, Mn, or MR keys, which are diverted using the ‘Divert G Keys’ setting.

**Comment by ctrngk** [comment]
Ok. let me try to be more specific.  Here is what I did
![Screenshot from 2024-05-08 17-56-56](https://github.com/pwr-Solaar/Solaar/assets/16743578/e2586bc9-122a-4a70-89dd-ce86fd131f20)


When the back button is pressed and released, the XF86_AudioRaiseVolume function works as planned. Additionally, holding down the back button while scrolling up or down activates the zoom function. However, during this process, the XF86_AudioRaiseVolume function unexpectedly triggers as well. What measures can be implemented to avoid this?

**Comment by pfps** [comment]
Solaar doesn't remember what it previously did.  (There are some very small exceptions.)   So the audio rule is unconditionally triggered when the back button is released, as expected.

You could write programs (or shell scripts) that are called.  These programs could arrange to keep track of whether the wheel was turned while the back button was down and only do the volume change under the correct circumstances.

**Comment by El-Barto89** [comment]
Can I ask why I can't obtain your same result in zooming in and out? I've copied exactly what you wrote...no action at all.

**Comment by ctrngk** [comment]
> Can I ask why I can't obtain your same result in zooming in and out? I've copied exactly what you wrote...no action at all.

I left out the specific settings because I wasn't sure if they applied directly to our current topic. But, if you're interested, here are the extra steps that might be helpful. (By the way, I'm still unsure why this solution requires using two mouse scrolls. I arrived at it through trial and error.)

![Screenshot from 2024-06-02 17-11-21](https://github.com/pwr-Solaar/Solaar/assets/16743578/f5703f1c-5369-4c3d-935a-d207bb9bfcaf)

![Screenshot from 2024-06-02 17-01-52](https://github.com/pwr-Solaar/Solaar/assets/16743578/f417eb81-1495-4e4e-b031-b323a85bcb7c)
