### ISSUE TITLE
solaar does not install version file

### ISSUE THREAD

**Issue by juanitotc** [pwr-Solaar/Solaar#2472]
Installing solaar-1.1.12 with:

```
sudo python3.9 setup.py install --root=/tmp/pkg
```

..the file named version is not installed and solaar will not start.

copying version to /tmp/pkg/usr/local/lib/python3.9/site-packages/solaar fixes the problem.

**Comment by pfps** [comment]
I don't recognize that command as a supported way to install Solaar.   What I do locally is `pip install .` from the Solaar directory.  You can see other methods in the Solaar Makefile.

**Comment by juanitotc** [comment]
i'm packaging solaar for tinycorelinux and didn't want there various python packages to be installed as well.

setup.py install works if the version file is copied over.

**Comment by pfps** [comment]
Given that setup.py works fine with pip it is up to you to determine what needs to be changed for your purposes.  Feel free to submit the change as a PR.
