### ISSUE TITLE
solaar will not start in tinycorelinux without binutils ld

### ISSUE THREAD

**Issue by juanitotc** [pwr-Solaar/Solaar#2473]
Using solaar-1.1.12, solar will not start without a sylink python -> python3 or python -> python3.9

Since the symlink /usr/local/bin/python is sometimes used to differentiate between python2.x and python3.x, maybe it would be better if solaar uses the symlink python3 to start.

Note that solaar installs without the symlink /usr/local/bin/python being present

**Comment by juanitotc** [comment]
I am packaging solaar for tinycorelinux where, if python-2.x is loaded, the symkink points to python2.

If only python3.x is loaded the symlink python is not present since most python3.x apps seem to use the python3 symlink

**Comment by pfps** [comment]
OK
