### ISSUE TITLE
Developer docs: High level component overview

### ISSUE THREAD

**Issue by MattHag** [pwr-Solaar/Solaar#2481]
**Information**
- Solaar version: 1.1.12

We should introduce a little graph showcasing the high level concept of Solaar with its main components. This helps with putting the code in the right module and separation of concerns. It's important for testing and maintainability to keep modules self-contained and have clear boundaries between packages.

### Implementation
[Mermaid](https://mermaid.js.org/) works with Jekyll and should support us in adding a graph as maintainable inline code.

**Comment by pfps** [comment]
A  high-level description of how Solaar works would be very useful, I agree.
