### ISSUE TITLE
how can I check if a process is open and execute two different operations based on it

### ISSUE THREAD

**Issue by dademiller360** [pwr-Solaar/Solaar#2484]
Hi guys
I would like to use the gesture button pressed to open a specific browser page
OS Ubuntu 22.04.4 LTS

the goal is:
- if edge is not running
- open a new page on www.google.com
- specific width and heigh on the new page
- if the process is running
- close it

there is a way to do it with rule editor?

thank you very much

**Comment by pfps** [comment]
Solaar has the Execute action for rules that lets you run an external program with arguments.   From there on you are on your own.

**Comment by dademiller360** [comment]
thank you very much @pfps 
I'm going to work on it
even if I know it's not the right place to ask
there is any comunty where rules are shared?
or github search is the way?
thanks again
