### ISSUE TITLE
How to autostart in a tray?

### ISSUE THREAD

**Issue by michaldybczak** [pwr-Solaar/Solaar#2491]
I installed Solaar from AUR and it works. After system restart, I realized, Solaar is not working, so I launched it manually. I added it to autostart in Plasma, but then it opens a window every time system boots, which is super annoying.

What is the exec command to launch it in a tray, and why doesn't it have an option to create a proper tray autostart?

Thank you

**Comment by michaldybczak** [comment]
Ah, finally found it:
solaar --window=hide

Still, this should be created automatically during install. When one adds to autostart in KDE and finds an app, it just finds whatever default .desktop file is in the system, and this one has a windowed version. To fix it, there should be solaar-tray .desktop to find or have an option in GUI to autostart (creating such .desktop file in ~/.config/autostart/

**Comment by pfps** [comment]
Setting up autostart is done by packages that include Solaar, and is not part of Solaar per se.  You could contact whoever put the package together.

There is a desktop file that has the correct option in the Solaar repository for packagers to use  - ./share/autostart/solaar.desktop

**Comment by michaldybczak** [comment]
I was convinced that it was the AUR package, but I checked, and it turned out to be a repo package, with maintainer freswa@archlinux.org, so basically the package comes from Arch repo. After install, there was no autostart and no desktop file in - ./share/autostart/
As far I know, Arch makes packages to be as vanilla as possible. Is it possible that by default it looks like this, and you just assume that maintainers will add that?

Frankly, I don't understand why such a feature would be part not part of the Solaar. This is obviously meant to be autorun in the tray and only sporadically opened as a window to configure the device. Without Solaar running in the background, any settings done (like mouse DPI), are not working (and defaults are used).

**Comment by pfps** [comment]
Solaar doesn't include repository instructions.  It is up to whoever puts the repository together to determine where ancillary files go.
