### ISSUE TITLE
Request: Question about openSUSE package updates method

### ISSUE THREAD

**Issue by RDhar** [pwr-Solaar/Solaar#2496]
**Is your feature request related to a problem? Please describe.**

Not a problem as such, more of a "thank you for sharing this project of yours!" and a question about how the [solaar-1.1.11-1.2.noarch.rpm](https://opensuse.pkgs.org/tumbleweed/opensuse-oss-x86_64/solaar-1.1.11-1.2.noarch.rpm.html) package is updated, and how can we get it to the latest version for use on openSUSE?

Thanks once again for your time!

**Comment by pfps** [comment]
That's up to whoever is maintaining the openSUSE distribution.   You should be able to find this out from the SUSE packaging and distribution systems.

**Comment by RDhar** [comment]
Gotcha, will follow-up there, thank you!
