### ISSUE TITLE
Question about mouse gestures and Logi AI Prompt Builder

### ISSUE THREAD

**Issue by RDhar** [pwr-Solaar/Solaar#2497]
More of a question, rather than a request, about how to convert the following Logi Options+ mouse gestures configuration to Solaar for the MX Master 3S.

**Back button**
- Drag ⬆️: Volume up
- Drag ⬇️: Volume down
- Drag ⬅️: Ctrl + Win + Left
- Drag ➡️: Ctrl + Win + Right
- Click: Right arrow

**Horizontal scroller**
- Scroll ⬆️: Ctrl + Tab
- Scroll ⬇️: Ctrl + Shift + Tab

Within docs, I came across [this page](https://pwr-solaar.github.io/Solaar/rules)... which, I gotta admit, I might bea a tad too thick to quite understand :sweat_smile:.

And I'm pretty sure it's out-of-scope at the moment, but is there plans to integrate [Logi AI Prompt Builder](https://www.logitech.com/en-us/software/logi-ai-prompt-builder.html) (though it seems quite a reach at the moment)?

**Comment by pfps** [comment]
The back button actions need to be done by rules that trigger on mouse gestures.  The documentation for mouse gestures should help there.   To actually do mouse gestures with the back button you have to divert it using Key/Button Diversion to Mouse Gestures.

I think you mean the thumb wheel as the horizontal scroller.  You can write rules that trigger on thumb wheel notifications.   There is an example in the rule documentation page of this.

Anything AI is far out of scope.

**Comment by MattHag** [comment]
> Within docs, I came across [this page](https://pwr-solaar.github.io/Solaar/rules)... which, I gotta admit, I might bea a tad too thick to quite understand 😅.

Yeah, it's far too complicated and lacks headings. We can use this ticket to improve the rule documentation.
There should at least be a structure. Headings that split all Conditions and Actions. Also explain Diversion. In addition, add all the missing subheadings for the paragraphs like "KeyPress".

**Comment by pfps** [comment]
Feel free to update any documentation.   Anyone can put in a PR.
