### ISSUE TITLE
merge/hide notifications on startup

### ISSUE THREAD

**Issue by Lekensteyn** [pwr-Solaar/Solaar#25]
With two devices plugged in, Solaar shows me three notifications, basically:
- Receiver: You have two devices!
- Keyboard connected
- Mouse connected

What about being less verbose with notifications and merging them?

**Comment by simonbcn** [comment]
Similar problem. I use this program just so I don't forget to recharge the mouse before the battery runs out. The other notifications seem to me unnecessary. At least this should be configurable.

**Comment by Lekensteyn** [comment]
@simonbcn If you just want battery notifications, any UPower application should already provide this information. On KDE Plasma for example, the battery monitor does support the Unifying receiver and warns when the battery level becomes low.

**Comment by simonbcn** [comment]
@Lekensteyn I used the Performance MX and Gnome Shell detects the battery automatically but with MX Master doesn't detect it.

**Comment by Lekensteyn** [comment]
@simonbcn Can you create a bug report at https://bugs.freedesktop.org/enter_bug.cgi?product=upower (you can add me (peter@lekensteyn.nl) as cc)? Please include the output of `upower -d`

**Comment by simonbcn** [comment]
That bug was already created on [May 4, 2016](https://bugs.freedesktop.org/show_bug.cgi?id=95260). I have added my info but almost a year without any solution or response.

**Comment by pfps** [comment]
Closing as fewer notifications are now being produced.
