### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by retrixe** [pwr-Solaar/Solaar#250]
It pretty much looks like it.

**Comment by heynnema** [comment]
I wish it wasn't true, but no new code has been released for over 7 months, and no new Ubuntu .deb packages for over 1 year.

**Comment by ibu2004** [comment]
I would love to fork it but I don't know how it works. I can code in Python
3.x and 2.x.

**Comment by Lekensteyn** [comment]
@heynnema The code is purely Python, no native stuff. You should be able to use the debs from older distro releases in newer ones.

I still have commit access, forking should not be necessary. Solaar is just not that high on my priority list. Reviews for the PRs would be more than welcome though ;)

**Comment by heynnema** [comment]
Thanks for your reply! However, am I looking at the wrong code web page? All of the code there is old, and I don't see any of the newer patches and commits there. Cheers, Al

**Comment by Lekensteyn** [comment]
Two patches were merged today: https://github.com/pwr/Solaar/commits/master
Where are you looking at?

**Comment by heynnema** [comment]
I'm new to git/github, and I'm looking at the dates on page https://github.com/pwr/Solaar. The dates range from months to years since the last update/mod? Am I looking at the wrong thing? If I download the .zip file, will I be getting the latest code? Cheers, Al

**Comment by Lekensteyn** [comment]
Each file may have a different modification time as not every change (commit) will affect every file. If you download the zip file (master.zip) you will indeed get the latest version.

**Comment by heynnema** [comment]
Thanks for your fast reply! In reviewing the code, I don't see a MAKE file, configure file, or an installation script. How do I install this? Cheers, Al

**Comment by hobarrera** [comment]
The [readme](https://github.com/pwr/Solaar#manual-installation) links to manual installation instructions, though I do believe these should also mention that you should run `python setup.py install` (probably as root).

**Comment by Lekensteyn** [comment]
This is a standard Python project, `python setup.py install` (as root) would normally work, but might get you in trouble later when you install it from your repositories. What distribution are you using? Ubuntu 15.04+ and Debian Jessie have this already in their official repos.

For testing, it suffices to run `bin/solaar &` from the source tree.

**Comment by heynnema** [comment]
Thanks again for your fast reply.

I double-checked... nowhere is "python setup.py install" documented as the way to get the initial code installed. It sounds like I shouldn't install it this way anyway, if I'm using a .deb or a repo.

I'm currently using Ubuntu 15.10. Here are the repo's that I have installed for Solaar:

daniel_pavel-solaar-raring.list:deb http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu trusty main #Solaar
trebelnik-stefina-ubuntu-solaar-vivid.list:deb http://ppa.launchpad.net/trebelnik-stefina/solaar/ubuntu utopic main #Solaar
trebelnik-stefina-ubuntu-solaar-vivid.list:# deb-src http://ppa.launchpad.net/trebelnik-stefina/solaar/ubuntu utopic main #Solaar

Cheers, Al

**Comment by KDB2** [comment]
Placing the new code in an old deb packages, adapting the version may work. I will look at it tonight or next weekend. I'm also interested to get an updated version.

**Comment by Lekensteyn** [comment]
If you are using debs, try the `packaging/build_deb.sh` script

**Comment by KDB2** [comment]
Ok thanks for the tip. I will look at this.

**Comment by heynnema** [comment]
Well, I'm still learning my way around GIT. I did a git clone/git init/git add/git commit. Git log showed the latest commit from Jan 13. I then did the packaging/build_deb.sh, and it build 3 debs in dist. But trying any of the debs indicates that there's a newer version already installed. The debs are named with 0.9.2-3, and my installed version from the Ubuntu repos is 0.9.2+dfsg-5. What does dfsg stand for? How can there be a newer version installed, -5?, as I know the python files are not the current ones? Cheers, Al

**Comment by KDB2** [comment]
Look in the build files (before you run the script) and search for the version number. Bump it to 0.9.3.

**Comment by SlySven** [comment]
@heynnema 
> What does dfsg stand for?

I think this means *Debian Free Software Guidelines* and suggests to me that the upstream project (here?) has been taken on board and fully *Debian*-ised.  Given that your homebrew version is 0.9.2 *patch* 3 and the Debian one has been patched *five* times that suggests the latter has had 5 alterations from the 0.9.2 base version - and indeed may be later.  I do not think that you can be sure that the three changes and the Debian five are the same though...

**Comment by mfonville** [comment]
For the debs it might be useful to set-up an Ubuntu PPA that runs the recipe to build it automatically for the various releases when there are any updates to the repo.

**Comment by heynnema** [comment]
Minor bug... when running packaging/build_deb.sh, it builds 5 files into the dist folder. If you run build_deb.sh later, it fails, because it finds that the existing .orig.tar.gz in the dist folder doesn't match what it's building, so it stops. By manually deleting the dist folder (or its contents) then build_deb.sh works fine again. Cheers, Al

**Comment by MagicFab** [comment]
Check issue #407, there has been quite some discussions and activity to move the project to a new repository and publish an updated release.

**Comment by Lekensteyn** [comment]
We gained admin access and have more devs! Closing this since we appear to be alive, see also #407.
