### ISSUE TITLE
Random sleeping/not registering inputs on Logitech MX Keys S 

### ISSUE THREAD

**Issue by piratenpanda** [pwr-Solaar/Solaar#2500]
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository):
1.1.13-14-g815dce07
 
- Distribution:
Arch linux,  6.9.2-arch1-1 SMP PREEMPT_DYNAMIC Sun, 26 May 2024 01:30:29 +0000 x86_64 GNU/Linux
Gnome solaar extension installed

- Output of `solaar show`:
[show.txt](https://github.com/pwr-Solaar/Solaar/files/15455073/show.txt)
[config.yaml.txt](https://github.com/pwr-Solaar/Solaar/files/15455081/config.yaml.txt)

- Errors or warrnings from Solaar:
[Solaar_ct1r0u3b.txt](https://github.com/pwr-Solaar/Solaar/files/15455088/Solaar_ct1r0u3b.txt) 

**Describe the bug**
I'm running latest git but the problems appeared around 1.1.12 I think. Sometimes when I'm in an input field I can't enter anything, the keys I press also don't run into any sort of buffer, they are completely ignored until the keyboard finally enters input again. Could this also be a USB power issue (I would not understand how this would happen, though)

**To Reproduce**
1. Use a text editor, browser, Signal Desktop, really anything that has text input fields
2. Try entering text
3. Sometimes no text is entered after key presses

**Comment by pfps** [comment]
Solaar is unable to find the battery icons in the normal places.   Where are they installed in your system?  This is not causing your issue, however.

Solaar is experiencing timeouts when communicating with one of your devices for some unknown reason.  I don't know whether this is related to your issue.  It could be that these timeouts are indicative of problems with the device or receiver.

Solaar shouldn't be doing anything that affects normal I/O from devices.  The problem could be some hardware or firmware issue on the receiver or device.   

You could try `solaar -ddd` to get more debugging output from Solaar, but I don't think that this would help.   You could also try using `evtest` to see the inputs from the device.

**Comment by piratenpanda** [comment]
I'm running solaar via a desktop: Exec=/home/panda/Solaar/bin/solaar --window=hide
anything else I need to do?

Thanks for the pointers for the timeouts. Will investigate further.

**Comment by pfps** [comment]
If you want to capture debugging output run Solaar directly as `solaar -ddd`.

But the problem is almost certainly not with Solaar if regular input to other programs is affected.  Solaar is not a device driver.

**Comment by pfps** [comment]
Closing due to no response from submitter.
