### ISSUE TITLE
Option to set Solaar language

### ISSUE THREAD

**Issue by Diego-MX** [pwr-Solaar/Solaar#2507]
**Information**

- Solaar version (`solaar 1.1.11+dfsg-2):
- Distribution: (Ubuntu 24.04
- Kernel version (Linux 6.8.0-31-generic x86_64 GNU/Linux):
- Output of `solaar show` for the target device (NOT applicable):

<details>

```
OUTPUT HERE
```
</details>

**Is your feature request related to a problem? Please describe.**
Not really a problem.  I set my system language to a non-dominant language as a personal challenge.  
However Solaar is a more challenging application, that I'd rather show in English.  
Therefore I'm trying to run it in English. 

**Describe the solution you'd like**
If there are more settings to configure, I'd like a Settings menu where they can be configured.  

**Describe alternatives you've considered**
This is not a Solaar-specific feature, but in general of any application. 
I have tried modifying the `solaar.desktop` files in both `.config/autostart` and `.local/share/applications` folders.  
Changing the `Exec` parameters to: 
`sh -c "LANGUAGE=en_US:en && solaar (--window=hide)"`
But I'm still having difficulty figuring it out. 

**Additional context**
Thank you for your consideration.

**Comment by MattHag** [comment]
Perfect for another addition to the documentation. So far, it is only mentioned along the [translation instructions](https://pwr-solaar.github.io/Solaar/i18n).

**Comment by pfps** [comment]
There is nothing specific to Solaar about this so I don't see that any documentation is needed.

**Comment by MattHag** [comment]
When something is not common knowledge, but a supported feature, then it makes sense to add it.
