### ISSUE TITLE
Needed help to set basic action

### ISSUE THREAD

**Issue by El-Barto89** [pwr-Solaar/Solaar#2511]
Hi every one, I'm willing to learn to remap my MX Master 3, but no matter how I tried there's no way to make it work.
can someone share his yaml file to let me reverse understand whats going on under the hood? 
For example if I want to remap my thumb button (mouse gesture) to only act as a tab key (tab action while held and released when button is not pressed anymore), what it the correct settings?
I've already diverted the key I want to remap.

**Comment by pfps** [comment]
The thumb wheel on an MX Master 3 is not a mouse gesture.  There is a compound rule that does things with the thumb wheel near the end of https://pwr-solaar.github.io/Solaar/rules

**Comment by pfps** [comment]
Ooops, you probably did mean the button under your thumb, which can be used to initiate mouse gestures and is called the Mouse Gesture Button.   You probably want a rule like half of the built-in rule (i.e., a rule with a Key condition and a Key press action).   But if you want the tab key depressed while the thumb button is depressed you need separate press and release rules.

**Comment by El-Barto89** [comment]
Exactly, I'm willing to remap my mouse gesture button the one under the orizontal scroll wheel, to act as a tab key. tab when pressed and holded and nothing when released. I read the https://pwr-solaar.github.io/Solaar/rules but i cannot figure out how to make it work, If I remap the key, it is realeased while im still holding it. I'll appreciate If you can show me some code to understand the logic.

**Comment by pfps** [comment]
I think what you want is to is to have two rules.   One rule has a Key condition for the mouse gesture button with the Key down flag and a Key press action for Tab with the Depress flag.  The other is similar but with Key up and Release flags.

**Comment by El-Barto89** [comment]
Thank you!!! it worked!
