### ISSUE TITLE
Add ability to emit MX Master gesture events while moving rather than at end of move

### ISSUE THREAD

**Issue by Elektrobomb** [pwr-Solaar/Solaar#2513]
**Problem**
 - In Logi options for Windows, the default behaviour for some gestures (e.g. media controls) is to continuously vary the modified value while the Gesture button is held down. 
   - For example, when changing volume I can hold the gesture button and move up and down until I am happy with the volume and then  release the button to stop modifying the value
 - In contrast, Solaar only seems to support discrete gestures.
   - For example: if I gesture up, I get one step of volume modification regardless of distance travelled my the mouse and the volume is only set on release of the gesture button.  

**Solution?**
 - I think the easiest solution to this issue would be to add a checkbox to the "Gestures" dropdown to enable continuous gestures (or something named similarly)
 - This would change the behaviour of [the gesture class](https://github.com/pwr-Solaar/Solaar/blob/244d0ee88acc5638441ff5bf1f4279ae027c64f8/lib/logitech_receiver/settings_templates.py#L793) to emit gesture events continuously when they are received rather than only at the end of the move
 - I'm going to see if I can have a crack at implementing the above but any help / guidance would be appreciated

**Comment by pfps** [comment]
One issue with this is the added computational cost of running rules for each mouse movement.   An implementation more like sliding DPI might be better.

**Comment by RDhar** [comment]
Thanks @pfps, was just thinking this would be ideal for adjust volume for example:

- Back button + Gesture Up = Volume Up
- Back button + Gesture Down = Volume Down

How (if at all) is this possible to configure? Here's my attempt so far, but this only changes the DPI. Then I amended to "Back button" "Diverted", which had no effect. I think I've misconfigured the rules? 

![image](https://github.com/pwr-Solaar/Solaar/assets/19497993/36639192-f3b8-4deb-b23d-a732e86d3a56)

**Comment by pfps** [comment]
You have to change the Diversion for Back Button to be Mouse Gestures.

**Comment by RDhar** [comment]
Thank you! I'm just about to follow the [example rule file](https://pwr-solaar.github.io/Solaar/rules#example-solaar-rule-file)'s thumb wheel configuration to emular behaviour [similar to this](https://github.com/pwr-Solaar/Solaar/issues/2511) on an MX Master 3S.

Specifically, `Thumb Wheel UP` = <kbd>Ctrl</kbd> + <kbd>Tab</kbd>, and `Thumb Wheel DOWN` = <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Tab</kbd>.

What's the best way to go about this?

**Comment by pfps** [comment]
The problem with this is that you might get a lot of tabs so you may want to use the special thumb wheel parameter.   See the rules documentation for more information.

**Comment by Allowexe** [comment]
I'll want the same possibility too

**Comment by MattHag** [comment]
> The problem with this is that you might get a lot of tabs so you may want to use the special thumb wheel parameter. See the rules documentation for more information.

Somehow the thumb wheel parameters and all the rule configuration descriptions don't show up in 1.1.13 Ubuntu install.

**Comment by pfps** [comment]
Please provide `solaar -ddd` log and screenshot.

**Comment by MattHag** [comment]
> Specifically, `Thumb Wheel UP` = Ctrl + Tab, and `Thumb Wheel DOWN` = Ctrl + Shift + Tab.
> 
> What's the best way to go about this?

This should be all you need, when diversion is active for the scroll wheel. Just configure it with the keys you want.
```
%YAML 1.3
---
- Rule:
  - Test: [thumb_wheel_up, 10]
  - KeyPress:
    - [Control_L, Page_Down]
    - click
...
---
- Rule:
  - Test: [thumb_wheel_down, 10]
  - KeyPress:
    - [Control_L, Page_Up]
    - click
...
```

**Comment by MattHag** [comment]
> > The problem with this is that you might get a lot of tabs so you may want to use the special thumb wheel parameter. See the rules documentation for more information.
> 
> Somehow the thumb wheel parameters and all the rule configuration descriptions don't show up in 1.1.13 Ubuntu install. It might be related to parsing errors of the rules.yaml, which might be related to the refactoring of the rule loading part.

#2462 Okay, that's not even merged, but could fix the issues and test the loading of rules. 

BTW: I'll try to provide a log, if rule loading issues persist on that notebook with Solaar 1.1.13 and tested it with config files.

**Comment by pfps** [comment]
Closed due to inactivity.
