### ISSUE TITLE
Is there a way to modify rules from a rule or set/view some internal memory/state to alter the behavior of a button once it's clicked?

### ISSUE THREAD

**Issue by imthenachoman** [pwr-Solaar/Solaar#2518]
I have the MX Master 3S.

I have a rule that executes `ctrl + alt + d` when the `Mouse Gesture Button` is pressed.

What I want to do is alter the behavior of the `Mouse Gesture Button` after it has been pressed once. Ultimately what I want is:

- **initial** : `Mouse Gesture Button` -> `ctrl + alt + d`
- **once `Mouse Gesture Button` has been pressed**:
  - `Mouse Gesture Button` -> `ctrl + alt + shift + d`
  - `Esc` -> `ctrl + alt + d`

Is something like this possible? I had two ideas:

- Either have a rule alter a rule -- the `Mouse Gesture Button` -> `ctrl + alt + d` rule would also say to change the key combination for `Mouse Gesture Button`
- Or have rules set a state/memory/something that I can then reference with a condition later

![image](https://github.com/pwr-Solaar/Solaar/assets/83817/4c1613fa-ff1e-49ba-9945-b8216d6f02d7)

**Comment by pfps** [comment]
This does not appear to be possible in Solaar and is not planned.

**Comment by imthenachoman** [comment]
Got it. Is it possible to:

1. Execute shell commands/programs from a rule
2. Is it possible to modify rules from the command line

My thought is, could I write a script that alters rules and have a rule that runs the script...

**Comment by pfps** [comment]
There is a rule action to execute programs.

There is no way to change the rule set, except by quitting Solaar, changing the rule file, and restarting Solaar.    This would take several seconds.

There has been a request to allow execution of Python code from rules.   That would allow for lots of things, including conditional rules.

**Comment by imthenachoman** [comment]
Humm. I'm thinking:

- I create rule files for the different situations I want
- I create a rule that runs a program that would quit Solaar, swap out the active rule file with the one I want, and restart Solar

Thoughts?

**Comment by pfps** [comment]
That should work, but would have a delay of several seconds while Solaar restarts.

**Comment by imthenachoman** [comment]
That's fine. Thank you very much! I'll play around with this. I'll close this issue out too.
