### ISSUE TITLE
bluetooth headset turns off wireless keyboard

### ISSUE THREAD

**Issue by jiohdi** [pwr-Solaar/Solaar#2520]
I bought a shokz comm2 headset which connects to my comp via usb-c dongle. I also have a logitech wireless keyboard and mouse and a single unit air-mouse(has keyboard on backside). When I turn on the shokz two things happen, the system gets a shutdown signal which I can stop and the keyboard functions stop. the mouse and the air-mouse still operate as normal.

when I started the shokz before boot up and hd decrypt, it and the keyboard worked together. but shutting down the shokz for battery charging and restarting presents the same problem above.
"Is it possible to reconfigure the receiver with solaar to sort out the incompatibility" 
btw, the logitech has a nano-receiver only.

**Comment by pfps** [comment]
It appears that your headset is sending some input that causes this behaviour.   Solaar isn't involved with this and can only help if the headset shows up when you run Solaar.  If it does then try to change the settings and see if any make any difference (which is unlikely).

**Comment by pfps** [comment]
Closing because Solaar is almost certainly not involved.
