### ISSUE TITLE
How to navigate forward/backward with Gestures?

### ISSUE THREAD

**Issue by membersound** [pwr-Solaar/Solaar#2530]
I want to act mouse gestures on the forward/backward button, eg in the browser.
But nothing happens:
![image](https://github.com/pwr-Solaar/Solaar/assets/5269630/8764e923-a6ca-4472-ad5a-27547a1668c4)

If I change the key to a single key, eg "Key X Press", then the letters are typed correctly on mouse gesture.
So the gesture in general works.

But somehow the combination of ALT+Arrow does nothing.
What could be the problem?

solaar --version
solaar 1.1.9+dfsg-1

uname -srmo
Linux 6.5.0-35-generic x86_64 GNU/Linux

```
cat ~/.config/solaar/config.yaml
- 1.1.9+dfsg-1
- _NAME: MX Anywhere 3S
  _absent: [hi-res-scroll, lowres-scroll-mode, scroll-ratchet, thumb-scroll-invert, thumb-scroll-mode, onboard_profiles, report_rate, pointer_speed, speed-change,
    backlight, backlight-timed, fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led,
    multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B03700000000
  _sensitive: {divert-keys: false, hires-smooth-invert: false, reprogrammable-keys: false, smart-shift: false}
  _unitId: 91E9C425
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 196: 2}
  dpi: 1500
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 196: 196}
  smart-shift: 12

```

**Comment by pfps** [comment]
The name to use for the right arrow is Right.  The rightarrow key is a key on some (a very few) keypads that produces the rightarrow character.

**Comment by membersound** [comment]
Thank you so much!
