### ISSUE TITLE
Invert fn with ctrl key on MX keys mini

### ISSUE THREAD

**Issue by cip123** [pwr-Solaar/Solaar#2531]
**Information**
solaar 1.1.1

Hello, I have an MX keys mini keyboard that I share between a Linux and a Macbook computer. I would love it if I could get consistent behavior between them. 

I don't know if it's possible via Solaar, but can I have the FN and control keys swapped?

**Comment by pfps** [comment]
Solaar is not a device driver and can only do things that are supported by the device so if you can't remap or divert these keys then Solaar can't change their behaviour.
