### ISSUE TITLE
the MX keyboard light diode of the ShiftLK key is inconsistent

### ISSUE THREAD

**Issue by Cherkah** [pwr-Solaar/Solaar#2532]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.13
- Distribution: EndeavourOS 
- Kernel version (ex. `uname -srmo`): `Linux 6.9.5-arch1-1`
- Output of `solaar show`: 
[solaarLogs.txt](https://github.com/user-attachments/files/15924681/solaarLogs.txt)

<details>

```
SOLAAR SHOW OUTPUT HERE
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present): 
[solaarYaml.txt](https://github.com/user-attachments/files/15924699/solaarYaml.txt)

<details>

```
CONTENTS HERE
```
</details>

- Errors or warrnings from Solaar: 
[solaarError.txt](https://github.com/user-attachments/files/15924817/solaarError.txt)

**Describe the bug**

Sometimes the diode of the ShiftLK key (MX Key keyboard) doesn't light up when press on it && sometimes it stays lightning up.
On the laptop the diode of the same keyboard key reacts normally.
This behavior is not observed when the keyboard is either only connected via Bluetooth to the PC or uses the Logitech USB dongle without using Solaar.

this bug happens all the time and throughout the session

sorry if this is a bug that has already been reported, but my research didn't give me anything similar

**To Reproduce**
1. connect the MX Key keyboard via solaar
2. press on the shift lok key
3. See error

**Screenshots**

**Additional context**

**Comment by pfps** [comment]
Solaar doesn't have any control over the shift lock light so there doesn't seem to be any way that Solaar is involved in whether the light is on or not.

**Comment by Cherkah** [comment]
ok
given that certain problems relating to lighting had been reported i therefore deduced that solaar probably had a link in my affair.

no matter, I still have the option of updating my keyboard/mouse pair via the Logitech Hub on a Windows machine..
