### ISSUE TITLE
Solaar does not recognize Unifying Receiver plugged into Raspberry Pi 4

### ISSUE THREAD

**Issue by rhhollin** [pwr-Solaar/Solaar#2549]
**Information**

- Solaar version 1.1.13:
- Distribution: OctoPi:
- Kernel version 1.0.0:
- Output of `solaar show`:

solaar: error: Traceback (most recent call last): File "/home/pi/.local/lib/python3.9/site-packages/solaar/cli/_init_.py, Line 217, in run raise exception( Exception: No supported devices found. Use "lsub" and "bluetoothctl devices connected" to list connected devices.

```
Solaar does not recognize unifying receiver inserted into Raspberry Pi 4 USB slot, will not pair devices
```

- Errors or warnings from Solaar:
See description above

**Describe the bug**
Solaar GUI is blank, command line pairing attempt provides same error as Solaar show
**To Reproduce**
Steps to reproduce the behavior (GUI):
1. Place unifying receiver into RPi
2. Boot the RPi
3. Open Solaar GUI
4. Devices screen is blank

Steps to reproduce the behavior (command line):
1. Place Unifying Receiver in RPi
2. Boot the RPi
3. enter "solaar" pair
4. solaar error displayed as above

**Comment by pfps** [comment]
Try `solaar -ddd` and report the output.

**Comment by rhhollin** [comment]
running solaar -ddd launches the Solaar GUI interface with the same issue as reported, i.e. the unifying receiver does not show up in the devices box which is still blank

**Comment by pfps** [comment]
What is the output from `solaar -ddd`?  There should be a lot of messages.

**Comment by rhhollin** [comment]
OK, ran solaar -ddd and from comments realized I had not loaded a piece of required software. Once loaded, Solaar worked as expected and recognized the new device. Thanks for all of the help!!
