### ISSUE TITLE
Non-battery tray icon can't be themed independently 

### ISSUE THREAD

**Issue by Bingo90** [pwr-Solaar/Solaar#2550]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.11
- Distribution: Fedora 40 Gnome
- Kernel version (ex. `uname -srmo`): `Linux 6.9.7-200.fc40.x86_64 x86_64 GNU/Linux`

**Describe the bug**
Solaar uses the application icon as the tray icon. I'm using the Papirus icon theme which correctly themes the application icon, but can't theme the tray icon independently. I opened an issue there, but it's apparently an upsteam issue, which is why I'm opening a new issue here.

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/3761

**Screenshots**
![grafik](https://github.com/pwr-Solaar/Solaar/assets/28258958/cff038ba-eee1-4cd8-ba2b-4bf141aa6c5f)

**Comment by pfps** [comment]
What is the problem, exactly?

**Comment by pfps** [comment]
So what solution could there be?

**Comment by Bingo90** [comment]
> So what solution could there be?

Use a different name for the tray icon like "solar-indicator" in Papirus' case.

**Comment by pfps** [comment]
This is not a bug, just the way that Solaar works.
