### ISSUE TITLE
Is it possible to control the LEDs on the Logitech G733 Headset

### ISSUE THREAD

**Issue by Guilhermedlv** [pwr-Solaar/Solaar#2555]
Hello, I installed Solaar to control my Logitech devices that I have on my system,

The Mouse G PRO worked very well, I was able to control the DPI and LEDs,

However, my G733 headset appeared on the Solaar panel but I can't control the LEDs,

Print

![image](https://github.com/user-attachments/assets/9c3accc7-0343-4a5f-85c9-4c64dc2ee181)

Do I need to perform any other configuration? Or is it a compatibility issue?

**Comment by pfps** [comment]
It looks as if you have an LED Control setting for your headset so play around with that.  If you don't see anything useful please post the output `solaar show` and run Solaar as `solaar -ddd` and post the messages during startup.

**Comment by Guilhermedlv** [comment]
Yes, it even appears to control the LED, but it doesn't make any changes to the LED, 

Follow the commands

![image](https://github.com/user-attachments/assets/7b257e21-7189-4e4e-bc12-3c08cef494bc)

**Comment by pfps** [comment]
I can't tell what is going on without the outputs requested above.

**Comment by Guilhermedlv** [comment]
Ok, follow the prints

![image](https://github.com/user-attachments/assets/1a1423e3-9da0-4b0b-b9f5-429c1feacca9)

**Comment by pfps** [comment]
You have to kill running Solaar to get good information from `solaar -ddd`

**Comment by pfps** [comment]
I think you are running into a bug in `solaar show` that has been fixed, so don't worry about that.  But if possible try to download Solaar from this repository and run it.

**Comment by Guilhermedlv** [comment]
Yes, it is possible, and when I killed the process and started again and started correctly, it is working very well now, even another Logitech keyboard appeared on the panel, something that didn't even appear before.
But for now everything is ok, thanks for the help.

**Comment by Guilhermedlv** [comment]
Friend, today I realized something,

When the system started Solaar my Headset did not appear, however when finishing the application and opening it via the solaar -ddd command it started correctly with the settings on the headset.
