### ISSUE TITLE
MX Master Keys S keyboard (Bolt Receiver) wakes up OS immediate after suspension

### ISSUE THREAD

**Issue by thisiscam** [pwr-Solaar/Solaar#2563]
I am encountering an issue and I'm unsure whether it is related to the Solaar software or the hardware itself. The problem is as follows:

- When I leave the keyboard powered on, the system wakes up immediately after being suspended.
- When I power off the keyboard, there are no spurious wake-ups.

This issue appears similar to the one reported here: [Reddit Link](https://www.reddit.com/r/logitech/comments/16lbju5/my_mx_keys_s_keeps_waking_up_my_linux_systems/).

Issue #361 might offer a potential workaround by disabling the keyboard's wake-up feature. However, this solution does not seem effective if the same Bolt connector is used for both the keyboard and mouse. From the operating system's perspective, there appears to be only one USB receiver, and it's not possible to block only the keyboard.

Ideally, we should look into what signal from the Bolt is waking up the system, and somehow handle that in the driver (if such a thing exist)

**Comment by pfps** [comment]
Solaar is not a driver and shouldn't be involved in suspending or wakeup.

**Comment by thisiscam** [comment]
> Solaar is not a driver and shouldn't be involved in suspending or wakeup.

I agree. Any idea on where I should be looking for a solution?

**Comment by pfps** [comment]
I had a similar problem quite some time ago.   A device was sending messages during Linux suspension for some reason.   I think I turned of wakeup for that device for a while and after some upgrades the problem stopped.

I think there was a Fedora bugreport on the problem.

**Comment by thisiscam** [comment]
Thanks! I think we can close this for now. 

I tried temporarily updating from Linux 6.5 -> 6.9 kernel and the issue appears to be fixed. Unfortunately, I have to stay 6.5 due to Ubuntu 22 missing all the drivers etc. Will wait till Ubuntu 24 + 6.9 is stable and upgrade to fix this
