### ISSUE TITLE
Change between virtual desktops with master mx 3s

### ISSUE THREAD

**Issue by miguelc3** [pwr-Solaar/Solaar#2566]
Hello,

I've been searching and trying to figure out how to change between virtual desktops on ubuntu with the master mx 3s. Can anyone tell me if it is possible? And if it is, how can I do it. I know that on windows it is.

Thank you,
Miguel Pereira

**Comment by pfps** [comment]
It's unclear what role you want Solaar to have here.   Can't something like active corners do what you want?  Or even right clicking and selecting from the system menu?

**Comment by miguelc3** [comment]
Basically I would like to change virtual desktops with the mouse, for example, if I click on the side upper button move to the desktop on the left and by clocking on the lower side button, move to the desktop on the right.

**Comment by pfps** [comment]
First you need to find out how you can move between desktops. Then you need to figure out whether these buttons are divertable.  If they are the forward and back buttons then they are.  Then to into Solaar and divert them.  Then write rule that have a condition for the keypress of button and either simulates the input that is used to switch desktops or executes the command that switches desktops.
