### ISSUE TITLE
Have the option to Switch DPI Level in an alternative way than gestures

### ISSUE THREAD

**Issue by blackcoffeerider** [pwr-Solaar/Solaar#2572]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): 1.1.13-1 from extra/solaar (feature parity w/ master @ the time of the request filing)
- Distribution: Manjaro
- Kernel version (ex. `uname -srmo`): Linux 6.9.10-1-MANJARO x86_64 GNU/Linux

**Thumbwheel-tap and DPI Cycling missing?**

Not sure if I am missing this somehow but as far as I can see there is only the option to switch DPIs with gestures?
On a MX Master 3S I would like to do the switching by tapping the thumbwheel.
Logiops gives us the option to do that.

**Target solution**
I would like to have the option to 
a)  react to Thumbwheel tap 
b) give a DPI array somewhere [800, 1000, 1200, 1400, 1600] (with a new UI for editing this range - as a table?
c) be able to cycle through that when hitting a button (specificly thumbwheel tap) (With a custom Action?)

**Considered Alternatives**
I made a rules file that roughly does what i am looking for but it is slightly clunky imho.

https://gist.github.com/blackcoffeerider/773f49aa1a099364d73484255cc2d43c

Features:
[2417 - Storing of rule values](https://github.com/pwr-Solaar/Solaar/issues/2417)
[2492 - Python "plugins"](https://github.com/pwr-Solaar/Solaar/issues/2492)
would come a long way for such scenarios.

**Comment by pfps** [comment]
The way to do this is using rules, as you have done.   I don't see what else you want that fits into Solaar.

**Comment by blackcoffeerider** [comment]
The "Tap" is a distinct function code that is currently not exposed in the UI at all.
Would you accept pull requests on that topic?

**Comment by pfps** [comment]
What is a tap?

**Comment by blackcoffeerider** [comment]
Tap is a gesture that is available on the MX Masters series thumb wheel. It is a short touching of the wheel. (It is similar to the short forceful hitting of most mouse pads on laptops that registers as mouse klick.) 
I don't know what it originally does on windows.

**Comment by pfps** [comment]
This information is available in the notifications that the device emits when the thumbwheel is diverted and can be used in rules.  You will have to write rules that are sensitive to the notifications using the testbytes condition.

**Comment by MattHag** [comment]
> The "Tap" is a distinct function code that is currently not exposed in the UI at all. Would you accept pull requests on that topic?

I nnever heard of that acrion before.would be cool to if you make a PR.
