### ISSUE TITLE
How to set Alt + Tab behaviour with Mouse Gesture button on MX Master 3S

### ISSUE THREAD

**Issue by SrdjanMilic** [pwr-Solaar/Solaar#2579]
Is it possible to set Mouse Gesture to act as Alt + Tab for app switching?
I'm using Arch Linux with Wayland and not sure if it possible at all or I can't figure out how to do so.

**Comment by pfps** [comment]
You need to have a rule that is sensitive to the mouse gesture and simulates the input.   You should be able to do this under Wayland if the special Solaar Wayland udev rule is installed.

**Comment by SrdjanMilic** [comment]
Is this the way to install `udev` rule you have mention?

![image](https://github.com/user-attachments/assets/62fa4ea1-ffb7-41bf-a641-441501cf448b)

**Comment by pfps** [comment]
The special Wayland rule also adds permissions to /dev/uinput.  See https://pwr-solaar.github.io/Solaar/installation/ for more information.

**Comment by SrdjanMilic** [comment]
OK. I've created that rule. What options should I set whit in the app?
![image](https://github.com/user-attachments/assets/77128f64-e14b-4645-b953-afb45fd0a068)
![image](https://github.com/user-attachments/assets/447fd9f1-207f-4aa7-ac01-07e49ff5919f)

**Comment by pfps** [comment]
You have to have the Mouse Gesture Button set to Mouse Gestures.   

But you can't access modifiers in Wayland.   This is one of Wayland's security features.

**Comment by SrdjanMilic** [comment]
So, it can not be done under Wayland.
Thank you very much for your help and time! 🙏

**Comment by SrdjanMilic** [comment]
This is the settings that works perfectly under Linux Mint (no Wayland):

![image](https://github.com/user-attachments/assets/22fac898-f30c-482b-a289-13b23f2458bc)
