### ISSUE TITLE
Basic Question About Solaar, Ubuntu 24.04, And Logitech M720

### ISSUE THREAD

**Issue by RH2357** [pwr-Solaar/Solaar#2583]
Please, if this is not the appropriate place to post this type of question please let me know and tell me where I should post it.

Issue is with the Solaar, Ubuntu 24.04, and a Logitech M720.

Installed and setup Solaar without issue. Very easy and I have the mouse working just fine with my laptop.

What I want to do is use the "front" button to enter my e-mail address. However, for the life of me I can not figure that out. I've read through the documentation and searched on-line to no avail.

If someone could help I would be grateful.

Regards,

Richard Huelbig

**Comment by pfps** [comment]
Solaar doesn't do anything with regular input from the mouse.   But for some devices and some keys you can "divert" or change the input into special "notifications" that can be used to trigger Solaar rules.   You need to see whether your front button can be diverted using the Key/Button Diversion setting.   If the key can be diverted, divert it and write a Solaar rule that triggers when the key is depressed or released and does something to do whatever you want to be done.   For more information see https://pwr-solaar.github.io/Solaar/rules

**Comment by RH2357** [comment]
Not sure if I'm supposed to say thank you or just give a thumbs-up. In either case, thank you.
