### ISSUE TITLE
Solaar API

### ISSUE THREAD

**Issue by dakhnod** [pwr-Solaar/Solaar#2587]
Solaar exposes a few functions that I would love to trigger from an external program. 
An example is to switch host from another program.

I would love to write a script that makes my mouse and keyboard switch to another device slot.

Is that possible somehow?

Maybe through a udev interface?

**Comment by pfps** [comment]
You can already so this using the Solaar command line interface.  The overhead is much higher, of course.

The command is `solaar config [-h] device [setting] [value_key] [extra_subkey] [extra2]`

**Comment by dakhnod** [comment]
Great, thanks!
