### ISSUE TITLE
Automatic host switch

### ISSUE THREAD

**Issue by dakhnod** [pwr-Solaar/Solaar#2588]
This is related to #2587

A neat feature would be to allow solaar to set an area on each border of the screen, where the mouse should hover for a bit of time.
If that happens, sollar could send a request to the mouse and keyboard to switch to another host.

Basically, I want to copy logitech flow...

**Comment by pfps** [comment]
Solaar has no idea of where the mouse is so this is not envisioned to be part of Solaar.

**Comment by dakhnod** [comment]
Got it, thanks!
