### ISSUE TITLE
G735

### ISSUE THREAD

**Issue by AbuObaidafa** [pwr-Solaar/Solaar#2594]
Please add support for the Headset G735

**Comment by pfps** [comment]
If the headset doesn't work with Solaar as it is it probably isn't supportable at all.

If  `solaar -ddd` shows errors while the headset is connected and active then there might be a bug that needs to be fixed to support the headset.  If so, post the output.

**Comment by AbuObaidafa** [comment]
But where can i see the errors?

**Comment by pfps** [comment]
Run `solaar -ddd` in a terminal window.

**Comment by AbuObaidafa** [comment]
Nothing really happens.My Headset is probably not supportable
unfortunately.Thans anyways and sorry for wasting your time
