### ISSUE TITLE
Hide tray icon

### ISSUE THREAD

**Issue by a-e-egorov** [pwr-Solaar/Solaar#2596]
**Information**
- Solaar version (`solaar --version` and `git describe --tags`): 1.1.13
- Distribution: Ubuntu 24.04

Hi, is it possible to hide both the window and tray icon of Solaar without stopping it (i.e. leaving it running in background)? If no, introduction of such possibility would be very useful, because the tray icon just spoils a bit of space (considering cases of its rare usage). In such cases one may use Solaar app tile inside OS app menu in order to open Solaar, if the tray icon will be hidden.

**Comment by pfps** [comment]
Solaar requests to be shown in the system/status tray.  The tray software then gets to decide what to do with Solaar's request.   Even in a simple windowing system like XFCE the tray software has options to hide tray items.

**Comment by iacobucci** [comment]
In some tray systems, like [AppIndicator/KStatusNotifierItem support for GNOME Shell](https://github.com/ubuntu/gnome-shell-extension-appindicator), it is still not possible to hide them easily. Ive made a small patch for my personal fork (i haven't published it on github). Here it is:

```diff
diff --git a/lib/solaar/ui/tray.py b/lib/solaar/ui/tray.py
index d0c77867..24f231ae 100644
--- a/lib/solaar/ui/tray.py
+++ b/lib/solaar/ui/tray.py
@@ -171,7 +171,7 @@ try:
             "indicator-solaar", _icon_file(icons.TRAY_INIT), AppIndicator3.IndicatorCategory.HARDWARE
         )
         ind.set_title(NAME)
-        ind.set_status(AppIndicator3.IndicatorStatus.ACTIVE)
+        ind.set_status(AppIndicator3.IndicatorStatus.PASSIVE)
         # ind.set_attention_icon_full(_icon_file(icons.TRAY_ATTENTION), '') # works poorly for XFCE 16
         # ind.set_label(NAME.lower(), NAME.lower())

@@ -480,7 +480,8 @@ def update(device=None):
     _update_tray_icon()

     if _icon:
-        if not _devices_info:
-            _hide(_icon)
-        else:
-            _show(_icon)
+        _hide(_icon)
```

Now i just know that solaar starts and i dont need to see a tray icon for it.

**Comment by pfps** [comment]
That's weird.  _hide just sets the status to PASSIVE so it appears that all you are doing is forcing the status to be PASSIVE all the time.

**Comment by iacobucci** [comment]
> That's weird. _hide just sets the status to PASSIVE so it appears that all you are doing is forcing the status to be PASSIVE all the time.

To be honest I'm not an expert on app indicator APIs, I can only say that with the aforementioned gnome extension it works!
