### ISSUE TITLE
Question:  Does Solaar control the wake up in Ubuntu

### ISSUE THREAD

**Issue by Andrew-Robbie-42** [pwr-Solaar/Solaar#2601]
Newbie here,

Currently I have to power OFF/ON my monitor to get the display to wake up after a session timeout.  Pressing keyboard keys, or moving the mouse does not wake up the Linux display.

So many layers, so I'm not sure if this is Solaar, Ubuntu, or the display driver that needs attention...

TIA,
Andrew

**Comment by pfps** [comment]
Solaar should not have any effect on wakeup, and particularly not on the display.
