### ISSUE TITLE
How can I save settings when using Linux Mint?

### ISSUE THREAD

**Issue by Lady-Fitzgerald** [pwr-Solaar/Solaar#2602]
I have a herd of Logitech M525 Unifying Receiver Mice I use because they fit my small hands well without causing wrist strain like larger mice will (it doesn't help that I'm a flatulent geriatric). These mice worked very well for me when using the wheel click button in Linux Mint 19.3 despite the mice having a very sensitive scroll wheel. However, now that I'm on Mint 21.1, the scroll wheel is so sensitive, it's hard to use the wheel button without the mouse pointer scurrying all over the screen before the wheel is fully depressed. I can set each mouse (I use two on my desktop computer) to slow down the scroll wheel but, even though I'm leaving Solaar running all the time, I have to reset them whenever I reboot the computer, I turn the mice off and then back on, and whenever the mice have been idle for awhile, even if kept turned on and Solaar still running.

I tried a Logitech M550 mouse since it also would fit my hand but, after pairing with Solaar, I would get annoying context menus popping up and getting in the way whenever I tried to use the wheel click button (and use that button a lot when browsing), making it prety much useless to me so I sent it back to the vendor.

The documentation page suggests there is a way to save the settings in Solaar but I couldn't make sense of the documentation. Can someone explain how I can save or otherwise get the settings to"stick"? Having to reset them umpteen times a day is getting older than I am!

Jeannie

**Comment by pfps** [comment]
Solaar automatically saves the settings for each device (separately).

The problem with the mouse wheel appears to be the driver problem described in https://pwr-solaar.github.io/Solaar/index: 

> The Linux HID++ driver modifies the Scroll Wheel Resolution setting to implement smooth scrolling. If Solaar changes this setting, scrolling can be either very fast or very slow. To fix this problem click on the icon at the right edge of the setting to set it to "Ignore this setting", which is the default for new devices. The mouse has to be reset (e.g., by turning it off and on again) before this fix will take effect.

The driver issue can sometimes be even more serious than this.

**Comment by Lady-Fitzgerald** [comment]
Thanks for replying.

No, Solaar is NOT saving settings for either mouse period, even when I change the setting for each mouse separately. As soon as I turn off the mouse, the setting gets lost. Same if I reboot the computer (and yes, I have Solaar set to start at boot and I leave it running). Even worse, if the mouse is idle while still turned on for a while, the setting change will be lost.

I've tried reading that wall of data on the page you linked several times but my ADHD addled brain just shuts down from overload.

I used this command [sudo apt install Solaar] to make sure I had the latest version installed and it showed that I do (1.1.1+dfsg-1). 

The problem I'm having is the scroll wheel speed is too fast, making it too sensitive. Changing the setting to "ignore this setting" just leaves the scroll speed still stuck at too fast, doing nothing to slow down the scroll wheel speed.

Having to reset the mouse several times a day, even though the computer and Solaar stays on is getting older than I am and is driving me as crazy as having the too fast scroll wheel speed making the wheel click button almost impossible to use.

**Comment by pfps** [comment]
Solaar saves its settings in ~/.config/solaar/config.yaml and applies them each time Solaar is started or the device becomes active.     You should be able to see the settings in the Solaar main window and see that changes you make are retained.

If the scroll wheel speed is the only problem, then this is a problem with the driver, not Solaar.   Try not running Solaar at all (check using `ps`) and see whether the problem persists.

**Comment by pfps** [comment]
Closing due to no response.
