### ISSUE TITLE
The most frustrating and non-operational software I've witnessed in a while

### ISSUE THREAD

**Issue by imfatant** [pwr-Solaar/Solaar#2613]
Gawww on... this is a wind up. Trying to get this software to work with a Pi 5 and.. three different unifying receivers all failing to bind (with a Logi Keys 2 K380s). Always says there's not enough power, or too much much power, or something. Congrats on a truly annoying experience, not to mention the self-build process where it's kind-a "well ya might give this a go mate, but f**ked if I really know".

**Comment by MattHag** [comment]
For which system do you build it yourself?
