### ISSUE TITLE
Question: How do I identify a wine game to set as the process

### ISSUE THREAD

**Issue by cip123** [pwr-Solaar/Solaar#2616]
I want to make rules work only for a specific game that I am running using wine. I  tried to add the `wine` Process as a rule condition, but it doesn't work. 

Is there any way to identify what process is currently active so I can filter by it?

**Comment by pfps** [comment]
If you find out what window is focussed and what process is running that window then Process should work.  But this only works in X11

**Comment by cip123** [comment]
Thanks for the tip. I managed to do it using `xprop | grep WM_CLASS` and clicked the window. The process name was `steam_proton` in my case.
