### ISSUE TITLE
Any updates to address security holes identified by Bastille Security ?

### ISSUE THREAD

**Issue by dwiniecki** [pwr-Solaar/Solaar#262]
With the late-February announcement from Bastille Security, of vulnerability for Logitech Unifying receiver devices (firmware 012.xxx.00xx, 024.xxx.000xx) I would like to ask if this Solaar package has been or will be updated?

The firmware reported with Solaar 0.9.2 is 12.01.B0019.  Is this vulnerable to the identified vulnerability?

I have taken my Logitech devices offline in the interim.

**Comment by heynnema** [comment]
Logitech has already released firmware updaters for their effected dongles. Check their support and forums for details.

https://forums.logitech.com/t5/Mice-and-Pointing-Devices/Logitech-Response-to-Unifying-Receiver-Research-Findings/td-p/1493878

**Comment by dwiniecki** [comment]
Yes.  I have seen that.  How to get it onto a Linux setup (Ubuntu 14.04)?

**Comment by Lekensteyn** [comment]
In the past I wrote a firmware updater specific to the T650 touchpad (https://git.lekensteyn.nl/t650-dfu/), I have no idea if the protocol also works for the receiver, I have yet to try it. In any case, communication with the receiver and devices should be ceased until the update is complete, I think that the updater will be kept as a separate tool (and not included in Solaar since it is too noisy).

If you are worried about it now, you can try to setup a (virtual) Windows machine and update it from there. In some future, I will try to update my receivers and share the results :-)

**Comment by heynnema** [comment]
No, you need a real Windows machine to install the firmware into the Logitech Unifying receivers.

Cheers, Al

**Comment by heynnema** [comment]
ps: the Logitech firmware .exe files don't actually do the firmware upgrade. All they do is to install the firmware bin file into a special file directory that the Unifying Software uses to actually do the work.

Cheers, Al

**Comment by Lekensteyn** [comment]
For device firmware updates, the exe file contained a binary which is encrypted if I remember correctly. The actual firmware blob is made available in plaintext while the update is in progress, so you can actually copy that firmware file and put it on the device *if you know the protocol*. The linked t650-dfu program could probably be modified for these receivers.

I suppose that it works similar for the USB receiver, in that case a virtual machine works too (with USB pass through).

**Comment by dwiniecki** [comment]
That is all good information.  However, how do I use this to update drivers on a Linux (Ubuntu 14.04) system?

My Solaar setup indicates the driver in use is 12.01.B0019.  This doesn't exactly meet the pattern of the problematic driver provided by Logitech (firmware 012.xxx.00xx, 024.xxx.000xx) but I do not know if the Solaar driver fixes the issue identified by Bastille.

Any advice will be appreciated.

Best wishes,

**Comment by kq01526** [comment]
Any update?

**Comment by Lekensteyn** [comment]
No updates, lack of time :| You can either try to update the firmware via a (virtual) machine running Windows or wait more until the update is available.

**Comment by pfps** [comment]
Try fwupdmgr.  It should update Logitech receivers to the most recent software.
