### ISSUE TITLE
Cant set the buttons

### ISSUE THREAD

**Issue by justintime2k** [pwr-Solaar/Solaar#2668]
so i have this Problem where i cant change the Button imputs. im quite new to Linux, but wanted to try it for a while and i think i made amistake

**Comment by pfps** [comment]
You will have to provide more information on what you are trying to do and what device you are trying to do it on including the output of `solaar show`.

**Comment by justintime2k** [comment]
so i have the g502x plus, aand do you mean this?
![image](https://github.com/user-attachments/assets/d370b6d7-1067-4870-9484-23d93ed308a0)

**Comment by justintime2k** [comment]
or what output do you mean .-.

**Comment by pfps** [comment]
Just run `solaar show` on a Linux command line and post the text output.  But from the output you provided it appears that there is nothing that Solaar can do with this device to change the way the buttons work, assuming you are running Solaar 1.1.13.  If not, you should upgrade and see if any other settings show up.

**Comment by justintime2k** [comment]
i think im doing something wrong, bc it just spits out htis
![image](https://github.com/user-attachments/assets/166ae47d-ebfe-4e22-a67b-483880883639)

**Comment by pfps** [comment]
If `solaar show` says "command not found" then Solaar is not in your execution path.  You need to somehow either find out where Solaar is and type that location in directly or adjust your execution path to include where it is.

**Comment by justintime2k** [comment]
Can you tell me how to do it? If no I'll find something on how to do it

**Comment by pfps** [comment]
See https://www.digitalocean.com/community/tutorials/how-to-view-and-update-the-linux-path-environment-variable

**Comment by justintime2k** [comment]
I will do that. Thanks a lot!
