### ISSUE TITLE
Logitech MX master -> Horitonzal issue

### ISSUE THREAD

**Issue by notaduck** [pwr-Solaar/Solaar#267]
So i got my new Logitech mx master today.  
Almost everything is working and it was just plug & play but the horizontal scroll isn't working?

OS -> Deepin 15.11 (ubuntu based)
Solaar version -> 0.92

```
solaar-cli show
Unifying Receiver [/dev/hidraw0:F23D9023] with 1 devices
1: Wireless Mouse MX Master [MX Master:250C5EEA] 
```

```
Index        : 1
Wireless PID : 4041
Protocol     : HID++ 4.5
Polling rate : 8 ms (125Hz)
Serial       : 250C5EEA
  Bootloader : BOT 18.01.B0014
  Firmware   : MPM 11.02.B0014
  Firmware   : MPM 11.02.B0014
  Other      : 
```

**Comment by daoswald** [comment]
I find that horizontal scrolling works on my MX Master (same firmware as listed above).  However, the scrolling is reversed from what I would consider intuitive.  I expect that rolling my thumb upward will scroll to the right, and down to the left.  If the thumb-wheel were sitting on top of the mouse, this would be the most obvious orientation, and the fact that it's on the side of the mouse doesn't change what I would expect.  But what actually happens is that rotating upward scrolls to the left, and down to the right.

**Comment by Lekensteyn** [comment]
@javitonino maybe you know how this is supposed to work here? I guess this is more a libinput/xinput configuration issue, but then I have no device to test with.

**Comment by javitonino** [comment]
Horizontal scrolling should work out of the box, no need to install Solaar at all. It is handled direcly by the xinput system, so I'd say it is not a Solaar issue (unless uninstalling Sollar magically fixes it).

@daoswald I think there is a reverse scroll wheel option implemented in the HID protocol that could be added to Solaar. But you can use xinput directly for that (do something like `xinput set-prop "Logitech MX Master" "Evdev Scrolling Distance" 1 -1 1`) so I'm not sure it is a worthy addition.

**Comment by jrbenito** [comment]
@notaduck and @daoswald ,

Could you please add output from `bin/solaar show` using latest version (master latest commit) from this repository?

Thanks.

**Comment by kas** [comment]
@daoswald 

This is the command you want. Reverses horizontal scrolling for my MX Master on my Ubuntu MATE distro

`xinput set-button-map 'Logitech MX Master' 1 2 3 4 5 7 6`

[source](https://nerdonthestreet.com/forum/topicview/browse/tech-talk/logitech-mx-master-on)

**Comment by indecisivemal** [comment]
@jrbenito c36cc50 shows:
```
Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c52b
  Serial       :
    Firmware   : 12.03.B0025
    Bootloader : 02.15
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=203

  1: Wireless Mouse MX Master
     Codename     : MX Master
     Kind         : mouse
     Wireless PID : 4060
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number:
        Bootloader: BOT 18.05.B0018
          Firmware: MPM 11.05.B0018
          Firmware: MPM 11.05.B0018
             Other: 
     The power switch is located on the base.
     Supports 31 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
         7: unknown:1806           {1806}   internal, hidden
         8: CHANGE HOST            {1814}   
         9: REPROG CONTROLS V4     {1B04}   
        10: ADJUSTABLE DPI         {2201}   
        11: VERTICAL SCROLLING     {2100}   
        12: SMART SHIFT            {2110}   
        13: HIRES WHEEL            {2121}   
        14: GESTURE 2              {6501}   
        15: DFUCONTROL 2           {00C1}   
        16: unknown:1813           {1813}   internal, hidden
        17: unknown:1830           {1830}   internal, hidden
        18: unknown:1890           {1890}   internal, hidden
        19: unknown:1891           {1891}   internal, hidden
        20: unknown:18A1           {18A1}   internal, hidden
        21: unknown:18C0           {18C0}   internal, hidden
        22: unknown:1DF3           {1DF3}   internal, hidden
        23: unknown:1E00           {1E00}   hidden
        24: unknown:1EB0           {1EB0}   internal, hidden
        25: unknown:1803           {1803}   internal, hidden
        26: unknown:1861           {1861}   internal, hidden
        27: unknown:9000           {9000}   internal, hidden
        28: unknown:9200           {9200}   internal, hidden
        29: unknown:9240           {9240}   internal, hidden
        30: unknown:1805           {1805}   internal, hidden
     Battery: 90%, discharging.
```
Wireshark while setting horizontal scroll inversion does a few URB_CONTROL exchanges, the only difference I saw was...
```
Set default:  11:01:0e:2b:00:01:02:02:00:00:00:00:00:00:00:00:00:00:00:00
Set inverted: 11:01:0e:2b:00:01:02:00:00:00:00:00:00:00:00:00:00:00:00:00
```

**Comment by cherio** [comment]
@javitonino I had to tweak your command as follows "xinput --set-button-map 'Logitech MX Master' 1 2 3 4 5 7 6". The option was missing dashes. Works like a charm! Thanks!

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original posters.

**Comment by pfps** [comment]
My reading of the Wireshark trace is that the relevant feature is GESTURE 2.   That feature has a partial implementation in PR #788, but not for this part, I think.

**Comment by pfps** [comment]
@notaduck 
The recent support of GESTURE 2 might allow changing the direction (and maybe even sensitivity) of the thumb wheel scroll.  Please give it a try.

**Comment by notaduck** [comment]
@pfps srry for the long answer time from my site, but I recently lost the MX master ad bought a Vertical instead.
But it nice to see a collaborator is caring so much to follow up on this old issue!!!

**Comment by half-duplex** [comment]
I don't know which patch it was, but my MX Master now has an option for this in 7a82b93!
Somewhat confusingly, it's under Gestures -> Natural scrolling, but only toggles natural scrolling for the thumb wheel, not the regular scroll wheel which is controlled by "High Res Wheel Invert" above.

**Comment by pfps** [comment]
Yes, the recent support of GESTURE 2 added a setting to change the direction of the thumb wheel.  It may be possible to fiddle with various wordings so that the setting or its tooltip is more explanatory.  Unfortunately there does not appear to be a feature for changing the sensitivity of the thumb wheel.

**Comment by pfps** [comment]
The current situation appears to be the best that can be arranged.  
Different versions of the MX Master have different features.  Some versions can change the direction of thumb scrolling.  None appear to have a feature to change the thumb wheel speed.

The Logitech software may be able to change thumb wheel speed by reinterpreting the thumb wheel input, but this it something that Solaar is not set up to do.
