### ISSUE TITLE
Regression from 1.1.13: BoltReceiver is broken

### ISSUE THREAD

**Issue by rloutrel** [pwr-Solaar/Solaar#2674]
**Information**
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): current master version
- Distribution: Fedora 41 - Kde Plasma
- Kernel version (ex. `uname -srmo`): Linux 6.11.6-300.fc41.x86_64 x86_64 GNU/Linux
- Output of `solaar show`:

<details>

```
rules cannot access modifier keys in Wayland, accessing process only works on GNOME with Solaar Gnome extension installed
Exception ignored in: <function Receiver.__del__ at 0x7f9dbbe500e0>
Traceback (most recent call last):
  File "/home/user/PycharmProjects/Solaar/lib/logitech_receiver/receiver.py", line 146, in __del__
    self.close()
  File "/home/user/PycharmProjects/Solaar/lib/logitech_receiver/receiver.py", line 138, in close
    handle, self.handle = self.handle, None
                          ^^^^^^^^^^^
AttributeError: 'BoltReceiver' object has no attribute 'handle'
solaar version 1.1.13-146-gc4c2e907

Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:C52B
  Serial       : 850E9BC4
  C Pending    : ff
    0          : 24.11.B0036
    1          : 02.09
    3          : AA.AC
  Has 4 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=64, 4=103

  1: MX Master 3 Wireless Mouse
     Device path  : /dev/hidraw8
     WPID         : 4082
     Codename     : MX Master 3
     Kind         : mouse
     Protocol     : HID++ 4.5
     Report Rate : 8ms
     Serial number: 8551427E
     The power switch is located on the base.
     Battery: unknown (device is offline).

  2: MX Keys Keyboard
     Device path  : /dev/hidraw3
     WPID         : 408A
     Codename     : MX Keys
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Report Rate : 20ms
     Serial number: DA6DBA41
     The power switch is located on the edge of top right corner.
     Battery: unknown (device is offline).

  3: MX Anywhere 3
     Device path  : /dev/hidraw2
     WPID         : 4090
     Codename     : MX Anywhere 3
     Kind         : mouse
     Protocol     : unknown (device is offline)
     Report Rate : 8ms
     Serial number: BBF9D6AF
     The power switch is located on the base.
     Battery: unknown (device is offline).

  4: Wireless Mobile Mouse MX Anywhere 2S
     Device path  : /dev/hidraw9
     WPID         : 406A
     Codename     : MX Anywhere 2S
     Kind         : mouse
     Protocol     : HID++ 4.5
     Report Rate : 8ms
     Serial number: 6AA02117
     Model ID:      B01A406A0000
     Unit ID:       88952BBA
                 1: BOT 57.00.B0003
                 0: MPM 13.00.B0003
                 0: MPM 13.00.B0003
                 3: 
     The power switch is located on the base.
     Supports 28 HID++ 2.0 features:
solaar: error: Traceback (most recent call last):
  File "/home/user/PycharmProjects/Solaar/lib/solaar/cli/__init__.py", line 221, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/home/user/PycharmProjects/Solaar/lib/solaar/cli/show.py", line 320, in run
    _print_device(dev, dev.number)
  File "/home/user/PycharmProjects/Solaar/lib/solaar/cli/show.py", line 151, in _print_device
    flags = dev.request(0x0000, feature.bytes(2))
                                ^^^^^^^^^^^^^
AttributeError: 'SupportedFeature' object has no attribute 'bytes'
```
</details>

- Errors or warnings from Solaar:
Exception ignored in: <function Receiver.__del__ at 0x7fb670593c40>
Traceback (most recent call last):
  File "/home/user/PycharmProjects/Solaar/lib/logitech_receiver/receiver.py", line 146, in __del__
    self.close()
  File "/home/user/PycharmProjects/Solaar/lib/logitech_receiver/receiver.py", line 138, in close
    handle, self.handle = self.handle, None
                          ^^^^^^^^^^^
AttributeError: 'BoltReceiver' object has no attribute 'handle'

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a BoltReceiver (with a device plugged in)

** Screenshots (v 1.1.13 vs current master) **
V 1.1.13 
![image](https://github.com/user-attachments/assets/be67721d-dc3c-4d6c-979f-db068ab3e5ec)

V current Master
![image](https://github.com/user-attachments/assets/4fe79747-1543-42f0-ab10-b63d11babdbb)

**Additional context**
When switching back to the tag 1.1.13, the boltreceiver ist working as expected

**Comment by rloutrel** [comment]
I am starting to look after the problem, but this is deep further to my knowledge

**Comment by pfps** [comment]
That's a bug, indeed.

**Comment by MattHag** [comment]
Should be fixed by #2661

**Comment by pfps** [comment]
@rloutrel Can you try out #2661?

To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #2661, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/2661/head:pull_2661
git checkout pull_2661
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_2661
git fetch origin pull/2661/head
git reset --hard FETCH_HEAD
```

**Comment by rloutrel** [comment]
The bug is fixed with these modifications

**Comment by pfps** [comment]
@rloutrel  Thanks for the report.
