### ISSUE TITLE
enhancement: property battery rechargeable

### ISSUE THREAD

**Issue by jontis** [pwr-Solaar/Solaar#269]
I think it might be useful to set a property for  which battery type you use. 
I put rechargeable batteries in my mouse and a fully charged rechargeable battery has a much lower voltage than a non-rechargeable. Thus, the rechargeable is reported as having low charge even when it is full.

**Comment by Lekensteyn** [comment]
This cannot really be detected, would it help if the warning is not shown?

**Comment by jontis** [comment]
I was hoping that you could set the property manually if the option was there.
Maybe some weak intelligence could set it if we want to go advanced. I figure that an alkaline battery with very low voltage is going steeply down, while a fully loaded rechargeable battery with the same voltage would hold that voltage for a long time. But initially, a manual setting is what I was hoping for.

**Comment by Lekensteyn** [comment]
Unfortunately most devices only report four gradations, critical (5%), low (20%), good (50%) and full (90%). We cannot really read voltages and tune it to the type of batteries that are in use.
