### ISSUE TITLE
Pressing Back and Forward buttons on the same time for MX 3S

### ISSUE THREAD

**Issue by ghost** [pwr-Solaar/Solaar#2690]
![Screenshot_20241118_230154](https://github.com/user-attachments/assets/e9c57cf3-76f7-4a91-b046-db97ffaf6a88)

How to make pressing Back and Forward buttons on the same time for MX 3S trigger an action, and not the indiviual action already set for them if pressed alone?

**Comment by pfps** [comment]
This is not possible.
