### ISSUE TITLE
Unable to pair MX Master 3S

### ISSUE THREAD

**Issue by steveklett** [pwr-Solaar/Solaar#2693]
**Information**
- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.1.11+dfsg-2 (installed from Mint Software Manager)
- Distribution: Linux Mint 22 Wilma base: Ubuntu 24.04 noble
- Kernel version (ex. `uname -srmo`): Linux 6.8.0-49-generic x86_64 GNU/Linux
- Output of `solaar show`:

<details>

```
Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:C52B
  Serial       : 342194DD
    Firmware   : 12.03.B0025
    Bootloader : 02.15
    Other      : AA.AA
  Has 3 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)

  1: Wireless Illuminated Keyboard K800
     Device path  : /dev/hidraw2
     WPID         : 2010
     Codename     : K800
     Kind         : keyboard
     Protocol     : HID++ 1.0
     Report Rate : 20msms
     Serial number: CB950A08
     The power switch is located on the top right corner.
     Battery: unknown (device is offline).

  2: Wireless Mouse M325
     Device path  : /dev/hidraw3
     WPID         : 400A
     Codename     : M325
     Kind         : mouse
     Protocol     : HID++ 2.0
     Report Rate : 8msms
     Serial number: 5648F416
     The power switch is located on the base.
     Battery: unknown (device is offline).

  6: M215 2nd Gen
     Device path  : /dev/hidraw4
     WPID         : 401B
     Codename     : M215 2nd Gen
     Kind         : mouse
     Protocol     : unknown (device is offline)
     Report Rate : 8msms
     Serial number: C7140D9A
     The power switch is located on the base.
     Battery: unknown (device is offline).
```
</details>

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
- 1.1.11+dfsg-2
- _NAME: Wireless Mouse M325
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi, speed-change, backlight, backlight_level, backlight_duration_hands_out,
    backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, fn-swap, reprogrammable-keys, persistent-remappable-keys,
    divert-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures,
    gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4096
  _serial: 5648F416
  _wpid: 400A
- {_NAME: Wireless Illuminated Keyboard K800, _serial: CB950A08, _wpid: '2010', fn-swap: false, hand-detection: true}
- {_NAME: Wireless Mouse M325, _serial: 5EEAD52B, _wpid: 400A}
- {_NAME: Wireless Mouse M325, _serial: B874E10F, _wpid: 400A}
- {_NAME: Wireless Illuminated Keyboard K800, _serial: A39978FB, _wpid: '2010'}
- {_NAME: M215 2nd Gen, _serial: C7140D9A, _wpid: 401B}
```
</details>

- Errors or warrnings from Solaar:

No errors or log files available

**Describe the bug**
I found and read Issue https://github.com/pwr-Solaar/Solaar/issues/667

I plugged my Unify receiver into my new Linux laptop and my 3S mouse was not working. I opened Solaar and the 3S was not listed as a device. I tried in vain to pair it but could never get Solaar to detect or react to the pairing process.
I've paired two other logitech devices without a problem.
I've put the mouse into pairing mode (fast flashing light) and attempted the Solaar pairing scan procedure numerous times without luck.

I'm VERY new to Linux (10 hours) so perhaps I'm missing something obvious.

**To Reproduce**
1. Go to Solaar and initiate pair procedure
2. Hold button on bottom of 3S mouse until it flashes quickly
3. Observe Solaar for some sort of reaction
4. Nothing happens, mouse is not paired

**Screenshots**

**Additional context**

**Comment by pfps** [comment]
https://www.logitech.com/en-us/products/mice/mx-master-3s.910-006558.html?srsltid=AfmBOoqhc05KL4JXX1xs8RLNEa-JLEJOuMh5nW_eDQ2tabJZTio3FHPI says that the 3S is not compatible with Unifying receivers.  You use Bluetooth to connect to it or a Bolt receiver.

**Comment by MattHag** [comment]
Yes, the MX Master 3S is compatible with Logitech Bolt and Bluetooth, but not compatible with Unifying receivers.
