### ISSUE TITLE
Need help adding support for an unsupported device (MK250)

### ISSUE THREAD

**Issue by marxo** [pwr-Solaar/Solaar#2694]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): 1.1.13
- Distribution: Arch Linux
- Kernel version (ex. `uname -srmo`): Linux 6.11.6-arch1-1 x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable): /

I have a loose Wireless Optical Mouse from a MK250 set, and a `046d:c52b` Logitech Unifying Receiver. The receiver works as intended with different devices, however, when I try to connect the MK250 mouse, it fails with the message

`pairing error 2: device not supported`

![Screenshot from Solaar GUI](https://github.com/user-attachments/assets/c17e9d2c-b6c1-4b6f-870f-ed2dce7243ee)

**Describe the solution you'd like**
I am looking for a way to get info on the device that the receiver gets, so I could try and add support for it. When I do `solaar -ddd show` no info regarding this mouse is displayed. I'm assuming the receiver checks against its list of supported devices and doesn't bother further.

Because the receiver detects the device, I'm assuming it successfully communicates with it, but I'm unable to find the information the mouse exchanges with the receiver. Is there any documented guide on steps to take to add an unsupported device?

**Comment by pfps** [comment]
This is done in the receiver and cannot be changed.

**Comment by MattHag** [comment]
This keyboard certainly uses a special 2.4 GHz Receiver, that's not compatible with Unifying.

**Comment by marxo** [comment]
> This keyboard certainly uses a special 2.4 GHz Receiver, that's not compatible with Unifying.

Would a Unifying receiver detect a device that couldn't/can't use it?

**Comment by pfps** [comment]
Yes.
