### ISSUE TITLE
Disable Horizontal Scrolling

### ISSUE THREAD

**Issue by basil-gray** [pwr-Solaar/Solaar#2703]
Hello. Is there a way for Solaar to disable "Horizontal Scrolling", or at least divert the side mouse buttons with a rule that lets it function like a normal button?

Horizontal Scrolling on the side mouse button causes an issue in some games (namely StarCraft II) where "drag scroll" simply makes the screen jitter, rather than actually registering an continuous down press while the button is held.

Thanks.

![image](https://github.com/user-attachments/assets/a57cb8bf-a7f6-4b25-85f8-059fbc7fdf33)

**Comment by basil-gray** [comment]
Nevermind - this did the trick. Thank you.

![image](https://github.com/user-attachments/assets/2a1a314e-9513-4865-a269-6d806d9d528d)

**Comment by gyrovox** [comment]
Here is another way to do it, so you do not have to bind it to a random key

<img width="802" height="413" alt="Image" src="https://github.com/user-attachments/assets/5d918cd7-e56f-4269-8a7d-740287a906eb" />
