### ISSUE TITLE
Logitech MX Creator Console

### ISSUE THREAD

**Issue by jeblad** [pwr-Solaar/Solaar#2704]
The Logitech MX Creator Console is out, and there are very little information available whether or not it can be used under Linux. 

It would be nice to know whether Solaar will support it, or whether it is defined as outside the scope.

**Comment by pfps** [comment]
This depends on whether it uses the HID++ protocol, which is unknown to me.  The likely only way to tell will be to try running Solaar with the device connected.

**Comment by jeblad** [comment]
I have only superficial knowledge about MX Creator. I briefly considered it as a replacement for some other device.

**Comment by pfps** [comment]
Understood.
