### ISSUE TITLE
How to divert an "additional" button

### ISSUE THREAD

**Issue by beelze** [pwr-Solaar/Solaar#2710]
Currently I'm using `Middle Button` as `Mouse Gestures` (MX Master 3S) and I want to use `Mouse Gesture Button` events in Rules. But this button as such seems not producing events (because it is not diverted I believe). But `Key/Btn Diversion` setting is already used by `Middle Button` and I do not know how to "additionally" divert `Mouse Gesture Button`.

**Comment by pfps** [comment]
The Key/Button Diversion setting allows diversion of any key or button that can be diverted.   Just select the appropriate key or button using the left-hand selection box for the setting.

**Comment by beelze** [comment]
Sorry but I do not understand what exactly should I do to divert a Gesture Button. 
![solaar](https://github.com/user-attachments/assets/4f448fff-56b8-4ff7-ab3f-6683e02ae87b)

**Comment by pfps** [comment]
The "Middle Button" box in the Key/Button Diversion can be changed to divert other keys or buttons, such as "Mouse Gesture Button".

**Comment by beelze** [comment]
But I want to keep an ability to use Middle Button "diverted" gestures in Rules. All I need is to "additionally" divert Gesture Button and not break current Rules.

**Comment by pfps** [comment]
Each key/button has its own diversion status so you can do what you want.

**Comment by beelze** [comment]
Oh, thanks, finally I got it. Wheels diversions are set separately so I thought about this combo as a single setting.
