### ISSUE TITLE
Support wireless headset g930, g933 to show battery status?

### ISSUE THREAD

**Issue by ramok** [pwr-Solaar/Solaar#272]
It is possible make support of them, even they did't use Logitech Unifying Receiver, but use HID++?

**Comment by Lekensteyn** [comment]
It might be possible, can you show lsusb information for this device? Is it wireless or not?

You can also try the to tools/hidconsole tool to connect (might require some editing of device IDs).

**Comment by divad** [comment]
`Bus 001 Device 003: ID 046d:0a1f Logitech, Inc. G930
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x046d Logitech, Inc.
  idProduct          0x0a1f G930
  bcdDevice            1.00
  iManufacturer           1 Logitech
  iProduct                2 Logitech G930 Headset
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength          239
    bNumInterfaces          4
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass         1 Audio
      bInterfaceSubClass      1 Control Device
      bInterfaceProtocol      0 
      iInterface              3 Logitech G930 Headset
      AudioControl Interface Descriptor:
        bLength                10
        bDescriptorType        36
        bDescriptorSubtype      1 (HEADER)
        bcdADC               1.00
        wTotalLength           80
        bInCollection           2
        baInterfaceNr( 0)       1
        baInterfaceNr( 1)       2
      AudioControl Interface Descriptor:
        bLength                12
        bDescriptorType        36
        bDescriptorSubtype      2 (INPUT_TERMINAL)
        bTerminalID             1
        wTerminalType      0x0101 USB Streaming
        bAssocTerminal          0
        bNrChannels             2
        wChannelConfig     0x0003
          Left Front (L)
          Right Front (R)
        iChannelNames           0 
        iTerminal               0 
      AudioControl Interface Descriptor:
        bLength                10
        bDescriptorType        36
        bDescriptorSubtype      6 (FEATURE_UNIT)
        bUnitID                 2
        bSourceID               1
        bControlSize            1
        bmaControls( 0)      0x03
          Mute Control
          Volume Control
        bmaControls( 1)      0x00
        bmaControls( 2)      0x00
        iFeature                0 
      AudioControl Interface Descriptor:
        bLength                 9
        bDescriptorType        36
        bDescriptorSubtype      3 (OUTPUT_TERMINAL)
        bTerminalID             3
        wTerminalType      0x0301 Speaker
        bAssocTerminal          0
        bSourceID               2
        iTerminal               0 
      AudioControl Interface Descriptor:
        bLength                12
        bDescriptorType        36
        bDescriptorSubtype      2 (INPUT_TERMINAL)
        bTerminalID             4
        wTerminalType      0x0201 Microphone
        bAssocTerminal          0
        bNrChannels             1
        wChannelConfig     0x0000
        iChannelNames           0 
        iTerminal               0 
      AudioControl Interface Descriptor:
        bLength                 9
        bDescriptorType        36
        bDescriptorSubtype      6 (FEATURE_UNIT)
        bUnitID                 5
        bSourceID               4
        bControlSize            1
        bmaControls( 0)      0x03
          Mute Control
          Volume Control
        bmaControls( 1)      0x00
        iFeature                0 
      AudioControl Interface Descriptor:
        bLength                 9
        bDescriptorType        36
        bDescriptorSubtype      3 (OUTPUT_TERMINAL)
        bTerminalID             6
        wTerminalType      0x0101 USB Streaming
        bAssocTerminal          0
        bSourceID               5
        iTerminal               0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       1
      bNumEndpoints           1
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
      AudioStreaming Interface Descriptor:
        bLength                 7
        bDescriptorType        36
        bDescriptorSubtype      1 (AS_GENERAL)
        bTerminalLink           1
        bDelay                  4 frames
        wFormatTag              1 PCM
      AudioStreaming Interface Descriptor:
        bLength                32
        bDescriptorType        36
        bDescriptorSubtype      2 (FORMAT_TYPE)
        bFormatType             1 (FORMAT_TYPE_I)
        bNrChannels             2
        bSubframeSize           2
        bBitResolution         16
        bSamFreqType            8 Discrete
        tSamFreq[ 0]         8000
        tSamFreq[ 1]        11025
        tSamFreq[ 2]        16000
        tSamFreq[ 3]        22050
        tSamFreq[ 4]        24000
        tSamFreq[ 5]        32000
        tSamFreq[ 6]        44100
        tSamFreq[ 7]        48000
      Endpoint Descriptor:
        bLength                 9
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            9
          Transfer Type            Isochronous
          Synch Type               Adaptive
          Usage Type               Data
        wMaxPacketSize     0x0120  1x 288 bytes
        bInterval               1
        bRefresh                0
        bSynchAddress           0
        AudioControl Endpoint Descriptor:
          bLength                 7
          bDescriptorType        37
          bDescriptorSubtype      1 (EP_GENERAL)
          bmAttributes         0x00
          bLockDelayUnits         0 Undefined
          wLockDelay              0 Undefined
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       1
      bNumEndpoints           1
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
      AudioStreaming Interface Descriptor:
        bLength                 7
        bDescriptorType        36
        bDescriptorSubtype      1 (AS_GENERAL)
        bTerminalLink           6
        bDelay                  1 frames
        wFormatTag              1 PCM
      AudioStreaming Interface Descriptor:
        bLength                11
        bDescriptorType        36
        bDescriptorSubtype      2 (FORMAT_TYPE)
        bFormatType             1 (FORMAT_TYPE_I)
        bNrChannels             1
        bSubframeSize           2
        bBitResolution         16
        bSamFreqType            1 Discrete
        tSamFreq[ 0]        16000
      Endpoint Descriptor:
        bLength                 9
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            5
          Transfer Type            Isochronous
          Synch Type               Asynchronous
          Usage Type               Data
        wMaxPacketSize     0x0020  1x 32 bytes
        bInterval               1
        bRefresh                0
        bSynchAddress           0
        AudioControl Endpoint Descriptor:
          bLength                 7
          bDescriptorType        37
          bDescriptorSubtype      1 (EP_GENERAL)
          bmAttributes         0x00
          bLockDelayUnits         0 Undefined
          wLockDelay              0 Undefined
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              4 Audio Controls
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.01
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     164
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              10
Device Status:     0x0000
  (Bus Powered)
`

**Comment by divad** [comment]
Not sure what to do with hidconsole...

```
.. Opening device /dev/hidraw0
.. Opened handle 3, vendor 'Logitech' product 'Logitech G930 Headset' serial None.
.. Press ^C/^D to exit, or type hex bytes to write to the device.
?? Input: 
```

**Comment by jasontibbitts** [comment]
I've been using a G933 headset recently and was wondering if it made any sense for solaar to talk to it.  I do believe it's a HID++ device and hidconsole can talk to it as shown above but I also have no idea what to do with it.  It does show output when I twiddle the volume wheel but not when I press the G keys.  I assume they need to be programmed before they do anything, and this particular headset has not ever been connected to a machine running official Logitech software.

```
.. Opening device /dev/hidraw4
.. Opened handle 3, vendor b'Logitech' product b'Logitech G933 Gaming Wireless Headset' serial None.
.. Press ^C/^D to exit, or type hex bytes to write to the device.
>> (   2.761) [01 01 0000 00] b'\x01\x01\x00\x00\x00'
>> (   2.811) [01 01 0000 00] b'\x01\x01\x00\x00\x00'
>> (   2.860) [01 00 0000 00] b'\x01\x00\x00\x00\x00'
>> (   3.610) [01 02 0000 00] b'\x01\x02\x00\x00\x00'
>> (   3.660) [01 02 0000 00] b'\x01\x02\x00\x00\x00'
>> (   3.710) [01 02 0000 00] b'\x01\x02\x00\x00\x00'
>> (   3.760) [01 00 0000 00] b'\x01\x00\x00\x00\x00'
```

**Comment by FM1337** [comment]
any updates on this? I got this headset yesterday and I would like to be able to know the battery level while working on Linux

**Comment by A3tra3rpi** [comment]
Have you got it working? I have been trying to get battery information of G933 for couple of days now. I used wireshark and windows vm with logitech gaming software to try guess how the data requesting works.
(when opening battery monitoring page of the gaming software)
Protocol (Bus 7, Device 6, interfaces 0 and 3 in my case):

host>7.6.0
Endpoint: 0x00, Direction: OUT
Request: 0x21 0x09 0x0211 0x0003
Data: 11ff080c00000000000000000000000000000000

7.6.0>host (some kind of default packet, probably ack)
Endpoint: 0x00, Direction: OUT

7.6.3>host
Endpoint: 0x83, Direction: IN
Data: 11ff080c0ed00100000000000000000000000000

host>7.6.3 (some kind of default packet, probably ack)
Endpoint: 0x83, Direction: IN

I found that the byte 6 of the response corresponds to state of the device:
disconnected:0x0, idle:0x01, charging:0x03 (also 0x07 and 0x87 which I haven't figured out yet)
From this I noticed that the byte 5(d0 in this case) seems to change in relation to charging and discharging, but don't know how to convert it to usable information.
I made a script that gets this data automatically, but I need a way to calculate the battery percentage to make it useful.

**Comment by ramok** [comment]
Can you attach script, please?
And also attach data samples what you catch with it, with you comments?

**Comment by A3tra3rpi** [comment]
https://github.com/A3tra3rpi/G933-battery-information-for-linux
It is now somewhat usable. There is a placeholder function to estimate battery percentage but the results are not totally accurate. It calculates the value linearly from the bytes 4 and 5 of the received data packet: about 0x10, 0x0 when fully charged and 0xD, 0x0 on shutdown. When discharging second byte falls from 0xFF to 0x0 and first byte drops by 1 when the second byte starts again from 0xFF. There is also a dump of few hours worth of logging the received data.

**Comment by andriyor** [comment]
For checking battery level you can use https://github.com/Sapd/HeadsetControl
`HeadsetControl -b `

**Comment by FFY00** [comment]
Which HID++ feature does it use? I am pretty sure you can just add it in the kernel driver and have it report the battery status natively and showing up in upower.

**Comment by andriyor** [comment]
If you use GNOME you can use [argos](https://github.com/p-e-w/argos) with such script to show battery status on the panel.

![image](https://user-images.githubusercontent.com/11459840/71965882-34ca7780-3209-11ea-8e12-ef8b88efeaa8.png)


**`HS.c.1m.sh`**

```bash
#!/usr/bin/env bash
# Dependencies: bash>=3.2, argos, HeadsetControl, paper icons
# https://extensions.gnome.org/extension/1176/argos/
# https://github.com/Sapd/HeadsetControl
# https://github.com/snwh/paper-icon-theme

regex="([0-9]*)%$"
VOLUME_CHANGE="(101)"
BATTERY_LEVEL="$(HeadsetControl -b)"

if [[ $BATTERY_LEVEL =~ $regex ]]; then
    STATUS="${BASH_REMATCH}"
elif [[ $BATTERY_LEVEL =~ $VOLUME_CHANGE ]]; then
	ICON=${ICON_ARRAY[0]}
 	STATUS="???%"
else	
 	STATUS="Disconnected"
fi

echo "$STATUS | iconName=audio-headphones-symbolic"
```

also if you use XFCE use this script https://github.com/andriyor/xfce4-genmon-scripts/blob/master/headset-battery-panel.sh with `xfce4-genmon-plugin`

**Comment by FFY00** [comment]
I think 430b70711ba307f43751f6f6b8331e23690f0c6f should show the battery in `solaar show`. Can you please check?

**Comment by pfps** [comment]
Closing as power applets should be able to show battery status for these devices.

**Comment by Sebclem** [comment]
Hi, i still can't see my G933.
Solaar 1.0.2
Kubuntu 20.04

```
~ solaar show 
solaar: error: Logitech receiver not found
```

**Comment by pfps** [comment]
As expected, Solaar doesn't handle the receiver of this device.

**Comment by pfps** [comment]
Recent changes to Solaar should make it easy to support these devices if they use HID++.   If you are still interested in using Solaar please respond.

**Comment by Sebclem** [comment]
I'm still interested ! 😃

**Comment by pfps** [comment]
@Sebclem Please provide the output of `lsusb -v -d <device>` where <device> is the the vendor:product ID for your headset receiver.  You can get this information from `lsusb`.

**Comment by Sebclem** [comment]
This is for G930: https://pastebin.com/jWHqFEwN

I'm currently at work but when a get home i can get you the output for the G933

**Comment by pfps** [comment]
I've added a tiny bit to PR #968 to handle the G930.

The first test should be `bin/soaar show`.  If that works, try `bin/solaar`.   If that doesn't work, provide output from `bin/solaar -dd show` and also output of `udevadm info -q all -a /dev/hidrawN` for each N in /dev/hidraw*.  You could also try changing the interface for the G930 at the end of lib/logitech_receiver/descriptors.py.  I think I have this right, but maybe 2 (or 1 or 0 or 4) is right.



To download and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #968, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/968/head:pull_968
git checkout pull_968
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_968
git fetch origin pull/968/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
Unfortunately, I forget to say that the Solaar udev rule needs to be installed.

[From installation.md]

You can install this rule by copying, as root,
rules.d/42-logitech-unify-permissions.rules from Solaar to
/etc/udev/rules.d.
You will probably also have to tell udev to reload its rule via
sudo udevadm control --reload-rules.
And then disconnect (unplug) and reconnect (replug) your receiver.
The output of ls -l /dev/hidrawN (where /dev/hidrawN is the node for your receiver) should have a + after the permissions once you do this.

**Comment by Sebclem** [comment]
Ok, there is something wrong:

I have the right permission on hidraw3:
```shell
crw-rw----+ 1 root plugdev 241, 3 oct.   8 09:55 /dev/hidraw3
```
But when i do `bin/solaar show` i got this exception:
```python
Wired Devices
solaar: error: Traceback (most recent call last):
  File "/home/sebastien/Solaar/lib/logitech_receiver/base.py", line 209, in write
    _hid.write(int(handle), wdata)
  File "/home/sebastien/Solaar/lib/hidapi/udev.py", line 336, in write
    raise IOError(_errno.EIO, 'written %d bytes out of expected %d' % (bytes_written, len(data)))
OSError: [Errno 5] written 0 bytes out of expected 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebastien/Solaar/lib/solaar/cli/__init__.py", line 199, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/home/sebastien/Solaar/lib/solaar/cli/show.py", line 277, in run
    _print_device(d, num=dev_num)
  File "/home/sebastien/Solaar/lib/solaar/cli/show.py", line 90, in _print_device
    dev.ping()
  File "/home/sebastien/Solaar/lib/logitech_receiver/device.py", line 439, in ping
    protocol = _base.ping(self.handle or self.receiver.handle, self.number, long_message=self.bluetooth)
  File "/home/sebastien/Solaar/lib/logitech_receiver/base.py", line 495, in ping
    write(ihandle, devnumber, request_data, long_message)
  File "/home/sebastien/Solaar/lib/logitech_receiver/base.py", line 213, in write
    raise NoReceiver(reason=reason)
logitech_receiver.base.NoReceiver: {'reason': OSError(5, 'written 0 bytes out of expected 7')}
```

**Comment by pfps** [comment]
That error probably means that /dev/hidraw3 does not accept HID++ commands.  I'm not an expert in this area, so I'm not sure whether this is just because the Linux drivers don't set things up correctly or the device doesn't talk HID++.  

Could you try out https://github.com/A3tra3rpi/G933-battery-information-for-linux via `git clone https://github.com/A3tra3rpi/G933-battery-information-for-linux.git`?  You may have to install pyusb via `pip install --user pyusb`.   If you have a G930 you will have to change the PIP.

**Comment by Sebclem** [comment]
Does not work with G930, i got this error:
```
('Exception:', USBError(32, u'Pipe error'))
```
I don't know if this can help but, i use this with G930 and it's work:
https://github.com/Roliga/g930-battery-percentage

**Comment by pfps** [comment]
Thanks.   I'm not sure what the remaining problems are and diagnosing them without the device is difficult.  So I'm going to put this back to low priority again unless someone comes up with a path to a solution.

**Comment by Sebclem** [comment]
Ok i understand, thank you !

**Comment by brunobmello25** [comment]
Hello. I am a Logitech G930 owner and would like to contribute with the project, but I can't seem to find a readme for a starting point. Should I follow the Manual Installation Guide or is there a better place for me to start?

**Comment by pfps** [comment]
The installation guide tells you how to download Solaar.  You can then edit the files.  Contributing is done the usual github way - create your fork of Solaar on github and make it the upstream of your clone, then push to your upstream and create pull requests.

**Comment by pfps** [comment]
Issue #641 is about supporting headsets, so I'm closing this issue as sort of a duplicate.
