### ISSUE TITLE
cli: is it a simple way to intercept solaar events?

### ISSUE THREAD

**Issue by Cherkah** [pwr-Solaar/Solaar#2720]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`):1.1.13-2
- Distribution: Endeavouros
- Kernel version (ex. `uname -srmo`): Linux 6.12.6-arch1-1 x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable):

<details>

```
1: MX Keys Keyboard
Device path  : /dev/hidraw1
WPID         : 408A
Codename     : MX Keys
Kind         : keyboard
Protocol     : HID++ 4.5
Report Rate : 20ms
Serial number: F710ADCD
The power switch is located on the edge of top right corner.
Battery: unknown (device is offline).

2: MX Master 3 Wireless Mouse
Device path  : /dev/hidraw3
WPID         : 4082
Codename     : MX Master 3
Kind         : mouse
Protocol     : HID++ 4.5

```
</details>

**Is your feature request related to a problem? Please describe.**
my laptop has a french-belgian layout and my logitech has a french-france layout. I created a script.sh to automatically change the layout of my keyboard when I connect/disconnect my logitech keyboard to have the belgian layout and vice versa.

so as to my script works as i expect i have to connect my keyboard via bluetooth (bluez). This  causes minor inconveniences such as lags, keyboard recognition on startup

**Describe the solution you'd like**
i would be interested to know how to obtain in command line the events of status of the device (connected/disconnected)? the goal being to have a script much more reactive and robust than the one I have.

**Describe alternatives you've considered**
now i'm using this methode so as to identify the state of my keyboard logitech:
```
# Écouter les événements D-Bus
dbus-monitor --session | rg --line-buffered "Keyboard: Batterie|sensorRemoved" | while read -r line; do
    # Filtrer et traiter uniquement les événements pertinents
    process_event "$line"
    # Introduire un léger délai pour réduire la charge CPU
    sleep 0.1
done
```
**Additional context**

**Comment by pfps** [comment]
The ability of an external program to receive events from Solaar is not planned.  

If you want to be notified of the appearance of a device then dbus is probably the best interface to use.
