### ISSUE TITLE
Start Solaar minimized

### ISSUE THREAD

**Issue by ShyPixie** [pwr-Solaar/Solaar#275]
Why we don't have a --minimized param to be able to start the gui minimized when start? I'm trying to autostart Solaar minimized with xfce but don't works with the last release.

**Comment by Lekensteyn** [comment]
Can you try #161?

**Comment by ShyPixie** [comment]
I want to hide the window, not the trayicon.

**Comment by pfps** [comment]
In version 1.0.1 solaar starts up with only a tray icon - no window visible at all.  Does this solve your issue?
I have a pull request https://github.com/pwr-Solaar/Solaar/pull/611 to have a flag to determine whether to start with the window visible or not.  Would this solve your issue?

**Comment by sarvasana** [comment]
I am on version 1.0.4 on Gnome 3.38.2, archlinux x86_64, kernel 5.9.14-arch1-1.

Solaar still opens the dialog.
