### ISSUE TITLE
Xenial PPA

### ISSUE THREAD

**Issue by mohitt** [pwr-Solaar/Solaar#285]
Hi Daniel,

Can you please add 16.04 or Xenial release in PPA as well. It works on Xenial. :).

Regards
Mohit

**Comment by Lekensteyn** [comment]
Solaar is already included in Xenial, a PPA would be needed if you want the most recent development version. (Well, @pwr seems a bit busy, so there will probably not be any new releases soon.)

**Comment by MagicFab** [comment]
@Lekensteyn I am also interested in this, mostly to also get the updated translations :)

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by MagicFab** [comment]
FYI release 1.01 is available since Ubuntu Eoan (19.10) was released.
If you prefer using only LTS releases, Ubuntu 20.04 should be available next April.

**Comment by MagicFab** [comment]
It seems there is a Xenial PPA, see : https://launchpad.net/~solaar-unifying/+archive/ubuntu/stable (linked from main Solaar project page), although I haven't tested it.
