### ISSUE TITLE
"failed to open pairing lock" error not localized, others possibly missing

### ISSUE THREAD

**Issue by MagicFab** [pwr-Solaar/Solaar#287]
After updating language files manually, I noticed this error message is not localized:

"failed to open pairing lock"

Can the corresponding string just be added to the language file (for example fr.po) and with its translation? If so I can do it but I think the code also needs to be changed, I didn't check if this was hardcoded (I suppose it is).

**Comment by Lekensteyn** [comment]
I think that the code needs to be modified first, otherwise it will not be picked up.

The message is quite technical, but it means something like being unable to signal the hardware that the receiver device can start pairing with a new device.

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original posters.
