### ISSUE TITLE
Please update github and official Debian packages to 9.3

### ISSUE THREAD

**Issue by MagicFab** [pwr-Solaar/Solaar#288]
It seems only packages up to 9.2 are available from Debian from this repository:
https://github.com/pwr/Solaar/blob/master/docs/debian.md

Official Debian packages (in Debian itself) also seem outdated:
https://tracker.debian.org/pkg/solaar

**Comment by Lekensteyn** [comment]
For the official packages, contact the Debian maintainer.

The packages in the pwr repo will probably not be updated any time soon. I can push new packages to that repo, but I think that a new release would be better because everyone else benefits too. Lack of time though to review all patches and bugs :/

**Comment by MagicFab** [comment]
I've already asked the Debian maintainer to sync, sorry if I didn't link directly:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819687

**Comment by MagicFab** [comment]
FYI the documentation at https://github.com/pwr/Solaar/blob/master/docs/debian.md mentions a repository for current Debian packages but it's been 404 for some time now.

**Comment by MagicFab** [comment]
In #407 there is quite some discussion and activity around moving to a new repository and having new releases. Someone even [offered to help with Debian packages](https://github.com/pwr/Solaar/issues/407#issuecomment-418144832) too.

**Comment by jean-christophe-manciot** [comment]
I believe that the official Debian & Ubuntu official repositories wait for a new 0.9.3 tag before building a new  release.

**Comment by Jeansen** [comment]
I am not familiar with debian packaging, yet. I hope to find some free time to get into. Then I would be happy to do some packaging :)

**Comment by MagicFab** [comment]
I got a message today the current Debian maintainer for Solaar is upgrading the package. I am letting him know about this report.

**Comment by doooby** [comment]
Installed the package `solaar` on debian 9.8 and it's paired my mouse just fine.

**Comment by Jeansen** [comment]
Any update on the Debian package? So far not much has changed since January: https://tracker.debian.org/pkg/solaar

**Comment by scorbin** [comment]
Is there a way to build solaar from source? It looks like the repository is never going to be updated

**Comment by scorbin** [comment]
I got it to work with clone  solaar repo and running the following:
scorbin@xps7:~/Solaar/bin$ python solaar config 1 fn-swap 0

**Comment by scorbin** [comment]
How can i make python solaar config 1 fn-swap 0 permanent?

**Comment by MagicFab** [comment]
Hmm... I see new versions in Debian Testing since August (!), see : 
https://packages.debian.org/search?keywords=solaar-gnome3
https://tracker.debian.org/pkg/solaar

Nothing in backports though.

**Comment by pfps** [comment]
I'm not sure what would be required for a backport.  If it is only packaging, that's the responsibility of whoever is doing the Debian packaging.  If a change is required to solaar itself, what changes might be required?  As far as I can tell, the current version of solaar should be compatible with any recent Linux distribution.

**Comment by Jeansen** [comment]
That's up to the maintainer of the package. He just has to upload it for backports and make changes, or create patches in case of an error. 

On the other hand, there is nothing preventing you from adding the test repro to you sources.list and only pin (https://wiki.debian.org/de/AptPreferences) that one package (so you do not mix all other packages by accident). 

Normally, it works and solaar does not really have much dependencies.

Of course, you could always contact the maintainer and ask him politely to provide a package for backports, too.

**Comment by pfps** [comment]
I don't see any remaining problems here, so I'm closing this issue.
