### ISSUE TITLE
MX™ 620 Cordless Laser Mouse: Receiver detected, but not the mouse itself. 

### ISSUE THREAD

**Issue by tuxmaster** [pwr-Solaar/Solaar#292]
For the full description see: [Fedora Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1377029).
--- Copy ---
Description of problem:
The tool find the sender, but can't access it.
Only the error at the picture are shown.

Plug out and plug in the receiver don't help. 

Version-Release number of selected component (if applicable):
solaar-0.9.2-4.20150528gitcf27328.fc24.4.noarch

How reproducible:
Every time

Steps to Reproduce:
1. plug in the receiver
2. start solaar

Actual results:
Error message about the permissions.

Expected results:
Battery information.

---

```
$ solaar -dd show
20:10:12,878    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 030000]
20:10:12,899    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 FF 83B5 03E8E7B5FCFF00000000000000000000]
20:10:12,899    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 80B2 000000]
20:10:12,907    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 80B2 000000]
20:10:12,908    DEBUG [MainThread] solaar.cli: [/dev/hidraw1] => <NanoReceiver(/dev/hidraw1,3)>
20:10:12,920    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 8102 000000]
20:10:12,923    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8102 000100]
Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c521
  Serial       : E8E7B5FC
20:10:12,923    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 81F1 010000]
20:10:12,931    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 81F1 015701]
20:10:12,932    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 81F1 020000]
20:10:12,939    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 81F1 020023]
20:10:12,940    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 81F1 040000]
20:10:12,947    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F81 F10300]
20:10:12,948    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {81F1}: 3 = invalid value
20:10:12,948    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 81F1 030000]
20:10:12,955    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F81 F10300]
20:10:12,955    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {81F1}: 3 = invalid value
    Firmware   : 57.01.B0023
  Has 1 paired device(s) out of a maximum of 0.
20:10:12,956    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 8100 000000]
20:10:12,963    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8100 000100]
  Notifications: wireless (0x000100)
20:10:12,963    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B3 000000]
20:10:12,971    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F83 B30200]
20:10:12,972    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {83B3}: 2 = invalid address
20:10:12,972    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 8102 000000]
20:10:12,979    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8102 000100]
```

**Comment by Lekensteyn** [comment]
Hmm, perhaps the reverse engineered information is not entirely correct. In your output the (presumably) reported number of devices field is indeed 0.
```
11 FF 83        GET_LONG_REGISTER_RSP from receiver
B5              register: Pairing Information
03              "Receiver information"?
E8 E7 B5 FC     Serial number
FF              ??
00              Normally we observe the number of devices here...
000000000000000000
```

Will get back to this later.

**Comment by Lekensteyn** [comment]
Is this device like 9 years old? Apparently it does not support the Unifying, but Quad protocol.

Product specifications page:
http://support.logitech.com/en_us/product/mx-620-cordless-laser-mouse

**Comment by tuxmaster** [comment]
Yes, but only 3 years old.

**Comment by Lekensteyn** [comment]
OK, apparently the protocol used by older receivers (Quad) always have zeroes after the base address. Can you try replacing this:
```
		self.max_devices = ord(serial_reply[6:7])
```
by
```
		self.max_devices = 1
```
in `lib/logitech_receiver/receiver.py`? Do things like battery reporting work?

**Comment by tuxmaster** [comment]
Yes, this will work :)

**Comment by Lekensteyn** [comment]
@tuxmaster Does that mean that you was able to retrieve battery information (and maybe other settings)? Do you have a `solaar --debug show` output?

**Comment by tuxmaster** [comment]
Yes, but I can't post the picture, because github don't like the png file.
solaar --debug show will result in:
Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c521
  Serial       : E8E7B5FC
    Firmware   : 57.01.B0023
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: wireless (0x000100)
21:33:31,051     INFO [MainThread] logitech_receiver.receiver: <NanoReceiver(/dev/hidraw1,3)>: found new device 1 (0A11)

21:33:39,068  WARNING [MainThread] logitech_receiver.base: (3) timeout (8.02/8.00) on device 1 ping
  1: ? (0A11)
     Codename     : ? (0A11)
     Kind         : ?
     Wireless PID : 0A11
     Protocol     : unknown (device is offline)
     Serial number: E8E7B5FC
     The power switch is located on the (unknown).
     Battery: unknown (device is offline).


But the gui of it will display the battery status.

**Comment by Lekensteyn** [comment]
That can probably be worked around by removing `dev.ping()` in `lib/solaar/cli/show.py`. A proper fix needs to skip the check for this special device, patches welcome.

**Comment by tuxmaster** [comment]
This will result in:
 solaar --debug 
17:45:54,616     INFO [MainThread] root: language de_DE (UTF-8), translations path None
/usr/lib/python2.7/site-packages/solaar/gtk.py:34: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
/usr/lib/python2.7/site-packages/solaar/ui/notify.py:33: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
17:45:54,687     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
17:45:54,717     INFO [MainThread] solaar.ui.notify: starting desktop notifications
17:45:54,747     INFO [MainThread] solaar.listener: starting receiver listening threads
17:45:54,786     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path=u'/dev/hidraw1', vendor_id=u'046d', product_id=u'c521', serial=u'', release='5701', manufacturer='Logitech', product='USB Receiver', interface=1, driver=u'hid-generic')
17:45:54,818     INFO [ReceiverListener:hidraw1] logitech_receiver.listener: started with <NanoReceiver(/dev/hidraw1,14)> (14)
17:45:54,818     INFO [ReceiverListener:hidraw1] solaar.listener: <NanoReceiver(/dev/hidraw1,14)>: notifications listener has started (14)
17:45:54,833     INFO [ReceiverListener:hidraw1] logitech_receiver.receiver: <NanoReceiver(/dev/hidraw1,14)>: receiver notifications enabled => ('wireless',)

(solaar:20645): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
17:45:54,841     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <NanoReceiver(/dev/hidraw1,14)>: present, No paired devices. (0) 
17:45:54,849     INFO [ReceiverListener:hidraw1] logitech_receiver.receiver: <NanoReceiver(/dev/hidraw1,14)>: found new device 1 (100A)
17:45:54,850     INFO [ReceiverListener:hidraw1] solaar.listener: Notification(1,41,03,820A10) triggered new device <PairedDevice(1,100A,MX620)> (mouse)
17:45:54,865     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <NanoReceiver(/dev/hidraw1,14)>: present, 1 paired device. (0) 
17:45:54,881     INFO [ReceiverListener:hidraw1] logitech_receiver.receiver: <PairedDevice(1,100A,MX620)>: device notifications enabled ('battery status',)
17:45:54,889     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <PairedDevice(1,100A,MX620)>: paired online, {'BATTERY LEVEL': 75, 'BATTERY CHARGING': False, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'LINK ENCRYPTED': False, 'NOTIFICATION FLAGS': 1048576, 'ERROR': None} (1) 
17:45:54,890     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <PairedDevice(1,100A,MX620)>: paired online, {'BATTERY LEVEL': 75, 'BATTERY CHARGING': False, 'BATTERY STATUS': NamedInt(0, 'discharging'), 'LINK ENCRYPTED': False, 'NOTIFICATION FLAGS': 1048576, 'ERROR': None} (0)

**Comment by kadir-gunel** [comment]
@tuxmaster  did you manage to work get it work with unifying receiver ?

**Comment by tuxmaster** [comment]
This device have it's one receiver and not using the unify one.
And yes it was working after the change from  https://github.com/pwr/Solaar/issues/292#issuecomment-252199955

**Comment by kadir-gunel** [comment]
I see. I thought you made it work with unifying receiver.

**Comment by Lekensteyn** [comment]
@tuxmaster Do you still need changes on the latest git master?

**Comment by tuxmaster** [comment]
Yes it will be needed.
But then it will work, like in the picture.
![bildschirmfoto von 2018-08-18 19-32-03](https://user-images.githubusercontent.com/6240474/44301800-8117cd80-a31d-11e8-9f17-ed392bb140bf.png)

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original posters.
