### ISSUE TITLE
New release/version any time soon?

### ISSUE THREAD

**Issue by Petross404** [pwr-Solaar/Solaar#296]
Hello and congratulations for writing Solaar. I am a gentoo user and I was wondering if you could make a release any time soon in order to have the newest of Solaar here in Gentoo (and all the rest of course).

Thank you very much.

**Comment by Lekensteyn** [comment]
There are no immediate plans to release a new version, I suggest that Gentoo users take a git snapshot for the latest features and bugfixes.

There is a backlog of pull requests and issues that also need to be taken care of, help is appreciated ;)

**Comment by mavosnet** [comment]
Can I help? I have very little experience with git (or GitHub) but I am quite proficient in Python (and Linux in general). If somebody would be so kind as to explain (to a git novice) what needs to be done, I could perhaps have a go at it.

Bottom line: I'm interested in helping out if time permits but don't know what to do.

**Comment by jrbenito** [comment]
@mavosnet,

You can help on open issues and/or reviewing open PRs (look to [issues](https://github.com/pwr/Solaar/issues) and [PRs](https://github.com/pwr/Solaar/pulls) links above).

Also, if you need assistance with git or github I am glad to help. Call me on gitter, e-mail (jrbenito at benito dot com dot br) or here.

**Comment by cement-head** [comment]
It is time for a new release; can someone in charge build and release?  Thanks.

**Comment by FFY00** [comment]
Done!
