### ISSUE TITLE
Cannot open solaar on arch with KDE/Plasma

### ISSUE THREAD

**Issue by alex9099** [pwr-Solaar/Solaar#300]
Hi, everyone i'm with problems opening the master bin file "solaar", it gives me a error:

`
(solaar:2123): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(solaar:2123): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(solaar:2123): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
solaar: error: Namespace AppIndicator3 not available
`

The version on the AUR puts the icon on the system tray but i cant open the settings window, and AFAIK only the master version has the ability to change the fn-swap option on k400 plus

**Comment by Lekensteyn** [comment]
Have you tried solaar-git? Such issues should already have been fixed in there

**Comment by alex9099** [comment]
no success :( same error

**Comment by Lekensteyn** [comment]
Looks like #276. Can you try this patch and report results:
https://github.com/Lekensteyn/Solaar/commit/023c5397aa92e701fe250df1f122e61180d1fb51

**Comment by alex9099** [comment]
Where can i find that file (lib/solaar/ui/tray.py) on the solaar-git AUR installation ?

**Comment by Lekensteyn** [comment]
Are there any errors when running solaar from console?

**Comment by alex9099** [comment]
not errors, warnings :+1: 
`
(solaar:5624): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(solaar:5624): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(solaar:5624): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(solaar:5624): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(solaar:5624): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

(solaar:5624): Gtk-WARNING **: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
`

**Comment by Lekensteyn** [comment]
Oh right, now I remember having the same issue... Looks like there is already a ticked for that: #223

I've pushed the appindicator import patch to master, can I close this issue now in favor of #223?

**Comment by alex9099** [comment]
The icon appears on the tray but when i click it it should open a window AFAIK

**Comment by Lekensteyn** [comment]
Right, the icon appears, but clicking does not work. The current implementation uses XEmbed (or something like that), but the xembed-proxy implementation that Plasma uses either does not like this or does not provide full backwards compatibility.

**Comment by alex9099** [comment]
So... is there any workaround for this to work ?

**Comment by Lekensteyn** [comment]
No workaround at the moment I am afraid (well, apart from commenting out the "hide window" part...)

**Comment by alex9099** [comment]
How about the battery integration? i remember with linux mint that the battery level appeared near the laptop battery :)

**Comment by alex9099** [comment]
Strange, it only shows the name sometimes and never shows the battery level (solaar shows the battery level when the dongle is connected or the keyboard turned on)

**Comment by Lekensteyn** [comment]
With the `upower -d` (or `upower -i ...` using the device from `upower -e`) you should see the information known to UPower. Does that contain the battery level?

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original posters.
