### ISSUE TITLE
[persistence] Config commands return saved values even on read/write fails

### ISSUE THREAD

**Issue by jrbenito** [pwr-Solaar/Solaar#314]
Solaar is saving configuration settings for every `solaar config ...` command issued even when it failed to write on device. A subsequent read of the setting, that might fail too, will return the saved setting instead of error. This mislead user to believe a feature is set while it is not or vice versa.

## Steps to reproduce:

-No configuration file, issue a config read command `solaar config 1`:
```
[...]
15:23:00,104    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 01 000F 211000]
15:23:00,198    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 01 000F 00000000000000000000000000000000]

<Setting([feature:toggle] M510v2:smooth-scroll=None)>
# Smooth Scrolling
# High-sensitivity mode for vertical scroll with the wheel.
#   possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
15:23:00,198    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 01 000F 212000]
15:23:00,292    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 01 000F 00000000000000000000000000000000]
15:23:00,292     INFO [MainThread] solaar.configuration: saved {u'4051:8989B04C': {'_name': u'Wireless Mouse M510'}, '_version': u'0.9.2'} to /home/jbenito/.config/solaar/config.json
smooth-scroll = ? (failed to read from device)
```
Notice solaar did failed to read status and signal it as expected.

-Try to write configuration issuing `solaar config 1 smooth-scroll on`:
```
[...]
15:24:43,620    DEBUG [MainThread] logitech_receiver.settings: smooth-scroll: write True to <PairedDevice(1,4051,M510v2)>
15:24:43,621     INFO [MainThread] solaar.configuration: saved {u'4051:8989B04C': {u'smooth-scroll': True, u'_name': u'Wireless Mouse M510'}, u'_version': u'0.9.2'} to /home/jbenito/.config/solaar/config.json
15:24:43,621    DEBUG [MainThread] logitech_receiver.settings: BooleanValidator: prepare_write(True, None) => 1
15:24:43,621    DEBUG [MainThread] logitech_receiver.settings: smooth-scroll: prepare write(True) => 1
15:24:43,621    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 01 000E 212000]
15:24:43,714    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 01 000E 00000000000000000000000000000000]
solaar: error: failed to set 'smooth-scroll' = 'True' [True]
```

Notice solaar failed to write configuration, however, it saved `True` to its configuration file on `15:24:43,621` line above.

-Read configuration again with `solaar config 1`:
```
[...]
15:26:30,687    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 01 0009 211000]
15:26:30,781    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 01 0009 00000000000000000000000000000000]

<Setting([feature:toggle] M510v2:smooth-scroll=None)>
# Smooth Scrolling
# High-sensitivity mode for vertical scroll with the wheel.
#   possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
15:26:30,781    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 01 0008 212000]
15:26:30,875    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 01 0008 00000000000000000000000000000000]
smooth-scroll = True
```

Notice that even write operation failed before, now solaar answers the feature is True (On). If I have suppressed debug information, it would mislead me to believe everything is set as expected.

## Actual behavior:

Solaar is reporting whatever is written to its configuration file, no matter it matches the device or not. Also, Solaar is write values to configuration file even before it was successfully written to the device.

## Expected behavior:

Solaar shall report results from device reading and not from its configuration file. Configuration file must match the user desires but UI must present actual settings on device.

**Comment by pfps** [comment]
It appears to me that Solaar is working on the basis that the user-supplied changes and information read from the saved configuration are the basis for the state of the device.  When the device is off-line these values are what are displayed and applied to the device when it comes on line.  So the values on the device don't really matter, as the idea is that they will be overwritten.

That's one way of thinking how Solaar should work and appears to me to be internally consistent.  If you want Solaar to work a different way you'll have to convince people that your way is better.

**Comment by pfps** [comment]
Closing due to no response from submitter.
