### ISSUE TITLE
Canot open Solaar on linux mint 18

### ISSUE THREAD

**Issue by Driky** [pwr-Solaar/Solaar#323]
Hi,
I installed Solaar from : 
`    ppa:trebelnik-stefina/solaar
`
When i try to open it, it doesn't respond. When i do it from the command line it send back the message : 

> solaar: error: Namespace AppIndicator3 not available

**Comment by Lekensteyn** [comment]
What version is that? The version in git should have fixed that issue.

Cannot really see which version it is based on:
https://launchpad.net/~trebelnik-stefina/+archive/ubuntu/solaar/+packages

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
