### ISSUE TITLE
K830 reprog, K400 error, greetings

### ISSUE THREAD

**Issue by mickleby** [pwr-Solaar/Solaar#330]
Greetings

I own Logitech K400 and K830. I believe there is Windows software to reprogram K830. I'll poke around the Solaar project; maybe I can help. I'm running Netrunner Core 16.09, http://www.netrunner.com/.

When I `solaar show` the K400 the response is glacial slow, and `solaar config` returns error. I suppose the error is due to some timeout. I'll look into this.

`michael@michael-pc:\~/Solaar/Solaar$ lsusb`
`Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub`
`Bus 001 Device 004: ID 046d:c52b Logitech, Inc. Unifying Receiver`
`Bus 001 Device 003: ID 046d:c52b Logitech, Inc. Unifying Receiver`
`Bus 001 Device 002: ID 13d3:3410 IMC Networks `
`Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub`
`michael@michael-pc:~/Solaar/Solaar$ ./bin/solaar -D /dev/hidraw2 show`
`Unifying Receiver`
`  Device path  : /dev/hidraw2`
`  USB id       : 046d:c52b`
`  Serial       : 14EB93B1`
`    Firmware   : 12.01.B0019`
`    Bootloader : 02.14`
`  Has 1 paired device(s) out of a maximum of 6.`
`  Notifications: wireless, software present (0x000900)`
`  Device activity counters: 1=245`
` `
 ` 1: Wireless Touch Keyboard K400`
`     Codename     : K400`
`     Kind         : keyboard`
`     Wireless PID : 400E`
`     Protocol     : HID++ 2.0`
`     Polling rate : 8 ms (125Hz)`
`     Serial number: 7CF9531B`
`          Firmware: RQK 39.00.B0008`
`     The power switch is located on the edge of top right corner.`
`     Supports 18 HID++ 2.0 features:`
`         0: ROOT                   {0000}   `
`         1: FEATURE SET            {0001}   `
`         2: FEATURE INFO           {0002}   `
`         3: DEVICE FW VERSION      {0003}   `
`         4: DEVICE NAME            {0005}   `
`         5: BATTERY STATUS         {1000}   `
`         6: REPROG CONTROLS        {1B00}   `
`         7: REPROG CONTROLS V2     {1B01}   `
`         8: WIRELESS DEVICE STATUS {1D4B}   `
`         9: unknown:1DF0           {1DF0}   hidden`
`        10: unknown:1DF3           {1DF3}   hidden`
`        11: unknown:1F01           {1F01}   hidden`
`        12: VERTICAL SCROLLING     {2100}   `
`        13: HI RES SCROLLING       {2120}   `
`        14: MOUSE POINTER          {2200}   `
`        15: ENCRYPTION             {4100}   `
`        16: KEYBOARD LAYOUT        {4520}   `
`        17: TOUCHPAD FW ITEMS      {6010}   `
`     Has 17 reprogrammable keys:`
`         0: FN F1                      => Do Nothing One                is FN, reprogrammable`
`         1: FN F2                      => Do Nothing One                is FN, reprogrammable`
`         2: FN F3                      => Do Nothing One                is FN, reprogrammable`
`         3: FN F4                      => Do Nothing One                is FN, reprogrammable`
`         4: FN F5                      => Do Nothing One                is FN, reprogrammable`
`         5: FN F6                      => Do Nothing One                is FN, reprogrammable`
`         6: FN F7                      => Do Nothing One                is FN, reprogrammable`
`         7: FN F8                      => Do Nothing One                is FN, reprogrammable`
`         8: FN F9                      => Do Nothing One                is FN, reprogrammable`
`         9: FN F10                     => Do Nothing One                is FN, reprogrammable`
`        10: FN F11                     => Do Nothing One                is FN, reprogrammable`
`        11: Mute                       => Mute                          nonstandard`
`        12: Volume Down                => Volume Down                   nonstandard`
`        13: Volume Up                  => Volume Up                     nonstandard`
`        14: LEFT CLICK                 => LeftClick                     mse`
`        15: LEFT CLICK                 => LeftClick                     mse`
`        16: RIGHT CLICK                => RightClick                    mse`
`     Battery: 70%, discharging.`
` `
`michael@michael-pc:\~/Solaar/Solaar$ ./bin/solaar -D /dev/hidraw2 config 1`
`solaar: error: `
`michael@michael-pc:~/Solaar/Solaar$ `

**Comment by Lekensteyn** [comment]
With `solaar --debug` you should get more info. Tip: to format code on Github, you can indent it with four spaces or use backticks like this:

    ```
    code here
    ```

**Comment by t6** [comment]
I have a K400 too and get the same error.  The issue seems to be an assert that checks if the device is of the correct kind. The K400 is detected as a keyboard but has a `smooth-scroll` setting which is assumed to only be available for mice.  I'm patching Solaar like this to work around it, so I can set `fn-swap=0`.

```diff
--- lib/logitech_receiver/settings.py.orig	2017-04-17 19:26:20 UTC
+++ lib/logitech_receiver/settings.py
@@ -61,7 +61,6 @@ class Setting(object):
 
 	def __call__(self, device):
 		assert not hasattr(self, '_value')
-		assert self.device_kind is None or self.device_kind == device.kind
 		p = device.protocol
 		if p == 1.0:
 			# HID++ 1.0 devices do not support features
```

**Comment by pfps** [comment]
I have a K400, but not with me.  I'll try to see what the current behaviour in Solaar is.  
If you are still using Solaar could you also check with the current version in github?
Thanks.

**Comment by t6** [comment]
Still the same. It dies with
```
$ solaar config 1
solaar: assertion failed: /usr/local/lib/python3.7/site-packages/logitech_receiver/settings.py line 64
```
but is fine when removing the assertion.

**Comment by pfps** [comment]
OK,  I'll try to see what is going on, probably this weekend.  It may be that the assertion is too broad, but maybe it is preventing something bad happening somewhere else.

**Comment by mickleby** [comment]
Help me catch up. 

WHY would I type `solaar config 1`? I'll point out that `solaar config 0` and `solaar config 1` both return vales for the only K830 while `solaar config 2` returns 
`solaar: error: no device found matching '2'`

I can say, `/usr/bin/solaar config K830 fn-swap 0` works as expected on 
`/usr/bin/solaar -V`
`solaar 1.0.1` and
`/usr/local/bin/solaar -V`
`solaar 0.9.2`

I can also say, after years of satisfied usage I had to replace my K830. I get the idea my new K830 has something different because the solaar widget seems to show more info -- and KDE Battery widget now reports the keyboard battery where it never did w my previous K830.

I'm wondering if this is the error at hand:
`19:34:26,790  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications:` `<PairedDevice(1,404C,K830)>: unrecognized Notification(1,01,00,0000000000000000000000) for` `feature FEATURE SET (index 01)`
`19:34:26,937     INFO [ReceiverListener:hidraw0] solaar.listener:` `Notification(1,41,01,4C401E4000000000000000) triggered new device` `<PairedDevice(1,404C,K830)> (keyboard)`
`19:34:27,099     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed` `<UnifyingReceiver(/dev/hidraw0,15)>: present, 1 paired device. (0)` 
`19:34:27,101  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications: 1: connection` `notification with unknown protocol 01: Notification(1,41,01,4C401E4000000000000000)`
`19:34:27,101    ERROR [ReceiverListener:hidraw0] logitech_receiver.listener: processing` `Notification(0,41,02,0000000000000000000000)`
`Traceback (most recent call last):`
`  File "/usr/share/solaar/lib/logitech_receiver/listener.py", line 185, in run`
`    self._notifications_callback(n)`
`  File "/usr/share/solaar/lib/solaar/listener.py", line 185, in _notifications_handler`
`    assert 0 < n.devnumber <= self.receiver.max_devices`
`AssertionError`
`19:34:34,312     INFO [ReceiverListener:hidraw0] solaar.listener: Notification(1,41,04,314C40)` `triggered new device <PairedDevice(1,404C,K830)> (keyboard)`
`19:34:34,560     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed` `<UnifyingReceiver(/dev/hidraw0,15)>: present, 1 paired device. (0) `
`19:34:34,561     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed` `<PairedDevice(1,404C,K830)>: paired online, {'BATTERY LEVEL': 50, 'BATTERY CHARGING':` `False, 'BATTERY STATUS': None, 'LINK ENCRYPTED': True, 'ERROR': None} (0) `
`19:34:34,564  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications:` `<PairedDevice(1,404C,K830)>: unrecognized Notification(1,42,00,0000000000000000000000)`
`19:34:34,565  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications:` `<PairedDevice(1,404C,K830)>: unknown BATTERY` `Notification(1,06,10,0404C00F0A0000000000000000000000)`
`19:34:34,572  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications:` `<PairedDevice(1,404C,K830)>: unrecognized Notification(1,03,00,0000000000000000000000) for` `feature DEVICE NAME (index 03)`
`^C`

Isn't this a logic error? Are you sure I'm not devnumber==0? Like devs[0]==K830?
`assert 0 < n.devnumber <= self.receiver.max_devices`

Regarless, I can flip the fn-swap from the CLI as well as the widget. I'll see if I can learn how to regrogram a multimedia key.

Let me know if I can reproduce or test or anything.

**Comment by Klap-in** [comment]
btw, the following Github layout syntax, you can use for code/text blocks:

    ```
    text
    ```

**Comment by mickleby** [comment]
are you a bot Klap-in? Let me try; is your suggestion 3 back-ticks?:

```
05:14:32,167  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,404C,K830)>: unrecognized Notification(1,01,00,0000000000000000000000) for feature FEATURE SET (index 01)
05:14:32,291     INFO [ReceiverListener:hidraw0] solaar.listener: Notification(1,41,01,4C401E4000000000000000) triggered new device <PairedDevice(1,404C,K830)> (keyboard)
05:14:32,433     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw0,15)>: present, 1 paired device. (0) 
05:14:32,434  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications: 1: connection notification with unknown protocol 01: Notification(1,41,01,4C401E4000000000000000)
05:14:32,434    ERROR [ReceiverListener:hidraw0] logitech_receiver.listener: processing Notification(0,41,02,0000000000000000000000)
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/usr/share/solaar/lib/solaar/listener.py", line 185, in _notifications_handler
    assert 0 < n.devnumber <= self.receiver.max_devices
AssertionError
05:14:36,977  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,404C,K830)>: unrecognized Notification(1,03,00,0000000100000000000000) for feature DEVICE NAME (index 03)
^C
```

Yes, good. Thank you. Klap-in can I highlight text in a codeblock?

**Comment by mickleby** [comment]
```05:14:32,291     INFO [ReceiverListener:hidraw0] solaar.listener: Notification(1,41,01,4C401E4000000000000000) triggered new device <PairedDevice(1,404C,K830)> (keyboard)
05:14:32,433     INFO [ReceiverListener:hidraw0] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw0,15)>: present, 1 paired device. (0) 
05:14:32,434  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications: 1: connection notification with unknown protocol 01: Notification(1,41,01,4C401E4000000000000000)
05:14:32,434    ERROR [ReceiverListener:hidraw0] logitech_receiver.listener: processing Notification(0,41,02,0000000000000000000000)
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/usr/share/solaar/lib/solaar/listener.py", line 185, in _notifications_handler
    assert 0 < n.devnumber <= self.receiver.max_devices
AssertionError
```
Again not yet clear what bug at issue. For the error I quote, looks like a notification is received for "device 0" while other notifications are for "device 1"
`Notification(1,41,01,4C401E4000000000000000)`
`Notification(0,41,02,0000000000000000000000)`

**Comment by pfps** [comment]
I think I know what is going on.  The failing assertion is there to check that the device is the right kind for the setting.  In this case it is probably checking that the device is a tablet for some tablet setting.  The K400 is identified as a keyboard, not a tablet.   I'll check in a few days when I'm where my K400+ is.
The fix might be a bit involved, however.

**Comment by mickleby** [comment]
Sounds like you're on top of it.

I opened this ticket 3 years ago, and I don't remember why. Maybe at that time I was unable to flip the fn-swap from CLI? Works fine now. Maybe I was trying to ask about reprogramming the media keys? I haven't yet looked to see; does that work?

Please, when you do take a look, if you could point me to the spot in the code to decode the notifications?
```
Notification(1,41,01,4C401E4000000000000000)
Notification(0,41,02,0000000000000000000000)
```
The assert I'm reporting today is obvious, the first parameter of the notification is '1', devnumber == '1', no error. Receiving a notification from devnumber == '0' fails the assert. But WHY do we receive a notification from a non-existent device??

**Comment by pfps** [comment]
The handling of notifications in Solaar is a bit of a mess.  They are created in lib/logitech_receiver/base.py function make_notification.  Currently too many are being created, resulting in lots of debug messages and warnings when the false notifications are processed.  Then notifications are handled in .../notifications.py.   
The productions of notifications in HID++ is also a bit of a mess.  There are notifications with a payload of three bytes and ones with a payload of 12 bytes.
The first notification above is a DJ paired device (41) message for your device #1 (1) with more notifications to come (01).   The other notification is saying that there are no more paired devices and this message doesn't have any other useful content (02).   I'm not sure how well these particular notifications are handled as the same information is communicated via other means as well.
I have some fixes in the works to filter out (allmost) all of the misleading messages.

**Comment by pfps** [comment]
@mickleby 
solaar config <n>
gives you the configurable items for the device with number <n> (unless <n> is 0 in which case it gives the options for device 1).
So I get
> bin/solaar config 1
Wireless Touch Keyboard K400 Plus (K400 Plus) [404D:132A9261]

# Swap Fx function
# When set, the F1..F12 keys will activate their special function, and you must hold the FN key to activate their standard function.  When unset, the F1..F12 keys will activate their standard function, and you must hold the FN key to activate their special function.
#   possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
fn-swap = True

**Comment by pfps** [comment]
@t6 Which version of solaar gives you the error?  I'm not having a problem with my K400+, but it does have a different set of features as the K400.

**Comment by mickleby** [comment]
@pfps Cheers! I think I'm up to speed again. ONLY items returned by `solaar config [devnumber]` are configueable. (And for me at least, indeed they are configurable using both 1.0.1 and 0.9.2.)

So then back to a secondary question in my original issue: Can we configure multimedia keys from Linux as is possible on Windows?

**Comment by pfps** [comment]
As far as reprogramming keys, Solaar doesn't do that right now, but @doctor64 is thinking of adding that capability.  It's not going to be easy in the UI and the result might only handle some versions of the feature.  See #592 for more information.
The chatter about notifications should be mostly ignored.  More and more messages have been added to the interface and Solaar was not doing a good job of categorizing them and ignoring the unimportant ones.  My PR #646 should fix this.
So it looks as if things are mostly OK from your perspective.

**Comment by mickleby** [comment]
@pfps Right. So is there something I can help test? And can/should I close this issue -- or are there other reports of same/similar?

**Comment by pfps** [comment]
If you are satisfied, please close - solaar has too many open issues.
If there is a problem with the K400+ another issue could be opened for that.

**Comment by mickleby** [comment]
Fixed
