### ISSUE TITLE
Unable to add device through GUI, Ubuntu 16.10

### ISSUE THREAD

**Issue by arlenn** [pwr-Solaar/Solaar#331]
Tried to add new device though GUI Ubuntu 16.10, no add option.  Removed existing device to see if that would help.  Still no option to add devices.

Was able to add devices though CLI.  GUI still shows no devices.

Have removed and reinstalled Solaar 0.9.2 through Ubuntu repository with no improvement.

![solaar](https://cloud.githubusercontent.com/assets/9562792/22191758/de78edb4-e0e2-11e6-8cf6-6f1517a26540.png)
![solaar2](https://cloud.githubusercontent.com/assets/9562792/22191760/e0d90d32-e0e2-11e6-9339-8425163c09e3.png)

**Comment by Lekensteyn** [comment]
That looks strange, perhaps some icon theme is missing. Could you investigate this?

**Comment by arlenn** [comment]
Thanks for the attention,

This seems to affect one other person.  I am not alone:
https://bugs.launchpad.net/ubuntu/+source/solaar/+bug/1636710

Thanks in advance

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original posters.
