### ISSUE TITLE
M185 receiver not found, USB ID not in valid list

### ISSUE THREAD

**Issue by jwkokc** [pwr-Solaar/Solaar#333]
My just-purchased M185 mouse's receiver (Product c534) isn't listed in the source code, so the program reports 'No receivers found." I can edit the *.py files if someone will tell me which ones to attack -- I've been doing such things for more than 25 years now.

**Comment by zoltanlaczko** [comment]
see #234 and #222

**Comment by jwkokc** [comment]
Thanks for the references! I managed to solve the problem by following the patches described in #234 and now the GUI shows as expected though the information displayed is quite minimal. I had hoped that this would let me monitor the state of the battery in the mouse, but all it offers is an ability to pair with a second device.

**Comment by doctor64** [comment]
Unfortunately, i found what exist (at least) two different hardware under M185 Mouse name.
Old one (buy this few years ago), P/N: 810-003496
`
./solaar show
Unifying Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:c52f
  Serial       : 6D0342C5
    Firmware   : 30.00.B0009
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: (none)

  1: Wireless Mouse
     Codename     : Wireless Mouse
     Kind         : mouse
     Wireless PID : 4055
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 6D0342C5
          Firmware: RQM 65.00.B0003
     The power switch is located on the base.
     Supports 22 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: RESET                  {0020}   
         5: BATTERY STATUS         {1000}   
         6: unknown:1810           {1810}   internal, hidden
         7: unknown:1830           {1830}   internal, hidden
         8: unknown:1802           {1802}   internal, hidden
         9: unknown:1862           {1862}   internal, hidden
        10: unknown:1890           {1890}   internal, hidden
        11: unknown:18A0           {18A0}   internal, hidden
        12: unknown:18B1           {18B1}   internal, hidden
        13: REPROG CONTROLS V4     {1B04}   
        14: WIRELESS DEVICE STATUS {1D4B}   
        15: unknown:1DF0           {1DF0}   hidden
        16: unknown:1DF3           {1DF3}   internal, hidden
        17: unknown:1E00           {1E00}   hidden
        18: unknown:1EB0           {1EB0}   internal, hidden
        19: unknown:1F03           {1F03}   internal, hidden
        20: LOWRES WHEEL           {2130}   
        21: POINTER SPEED          {2205}   
     Has 3 reprogrammable keys:
         0: LEFT CLICK                 => LeftClick                     divertable, mse
         1: RIGHT CLICK                => RightClick                    divertable, mse
         2: MIDDLE BUTTON              => MiddleMouseButton             divertable, mse, reprogrammable
     Battery: 5%, discharging.
`
and new one, just few months old, P/N: 810-005238
`
./solaar show
Unifying Receiver
Device path  : /dev/hidraw3
  USB id       : 046d:c534
  Serial       : 0
    Firmware   : 29.01.B0016
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: (none)

  2: Wireless Mouse M185
     Codename     : M185
     Kind         : mouse
     Wireless PID : 4054
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 1377ED51
          Firmware: RQM 64.00.B0008
     The power switch is located on the base.
     Supports 20 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: RESET                  {0020}   
         5: REPROG CONTROLS V4     {1B04}   
         6: WIRELESS DEVICE STATUS {1D4B}   
         7: LOWRES WHEEL           {2130}   
         8: POINTER SPEED          {2205}   
         9: unknown:1802           {1802}   internal, hidden
        10: unknown:1810           {1810}   internal, hidden
        11: unknown:1830           {1830}   internal, hidden
        12: unknown:1850           {1850}   internal, hidden
        13: unknown:1869           {1869}   internal, hidden
        14: unknown:1890           {1890}   internal, hidden
        15: unknown:18B1           {18B1}   internal, hidden
        16: unknown:1DF3           {1DF3}   internal, hidden
        17: unknown:1E00           {1E00}   hidden
        18: unknown:1F03           {1F03}   internal, hidden
        19: unknown:1E80           {1E80}   internal, hidden
     Has 3 reprogrammable keys:
         0: LEFT CLICK                 => LeftClick                     mse, reprogrammable
         1: RIGHT CLICK                => RightClick                    mse, reprogrammable
         2: MIDDLE BUTTON              => MiddleMouseButton             divertable, mse, reprogrammable
     Battery status unavailable.
`
Unfortunately, new one does not report battery status, even in Windows software.

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
