### ISSUE TITLE
Battery unknown for k780 and MX Master

### ISSUE THREAD

**Issue by dannietjoh** [pwr-Solaar/Solaar#336]
Hi,

I'm using solaar 0.9.2 with a k780 and MX master on Ubuntu 16.04 and it works fine except for the battery status for both devices. The status worked right after initial setup/pairing but now (after reboot i guess) it is unknown.
here is the output from solaar-cli:
Unifying Receiver
   Device path  : /dev/hidraw0
   USB id       : 046d:c52b
   Serial       : C63E9FA7
     Firmware   : 12.03.B0025
     Bootloader : 02.15
     Other      : AA.AA
   Has 2 paired device(s) out of a maximum of 6 .
   Notifications: 0x000900 = wireless, software present
   Device activity counters: 1=72, 2=8

1: K780 Multi-Device Keyboard
   Codename     : K780
   Kind         : keyboard
   Wireless PID : 405B
   Protocol     : HID++ 4.5
   Polling rate : 20 ms
   Serial number: 6B0CF981
      Bootloader: BOT 25.00.B0005
        Firmware: MPK 01.01.B0019
           Other: 
   The power switch is located on the edge of top right corner.
   Supports 31 HID++ 2.0 features:
       0: ROOT                   {0000}   
       1: FEATURE SET            {0001}   
       2: DEVICE FW VERSION      {0003}   
       3: DEVICE NAME            {0005}   
       4: WIRELESS DEVICE STATUS {1D4B}   
       5: unknown:0020           {0020}   
       6: unknown:0007           {0007}   
       7: BATTERY STATUS         {1000}   
       8: unknown:1814           {1814}   
       9: unknown:1815           {1815}   
      10: unknown:1B04           {1B04}   
      11: unknown:1C00           {1C00}   
      12: NEW FN INVERSION       {40A2}   
      13: ENCRYPTION             {4100}   
      14: unknown:4521           {4521}   
      15: unknown:4531           {4531}   
      16: unknown:4220           {4220}   
      17: unknown:00C2           {00C2}   
      18: unknown:1803           {1803}   internal, hidden
      19: unknown:1806           {1806}   internal, hidden
      20: unknown:1805           {1805}   internal, hidden
      21: unknown:1813           {1813}   internal, hidden
      22: unknown:1830           {1830}   internal, hidden
      23: unknown:1861           {1861}   internal, hidden
      24: unknown:1890           {1890}   internal, hidden
      25: unknown:1891           {1891}   internal, hidden
      26: unknown:18A1           {18A1}   internal, hidden
      27: unknown:1DF3           {1DF3}   internal, hidden
      28: unknown:1E00           {1E00}   hidden
      29: unknown:1EB0           {1EB0}   internal, hidden
      30: unknown:18B0           {18B0}   internal, hidden
   Battery status unavailable.

2: Wireless Mouse MX Master
   Codename     : MX Master
   Kind         : mouse
   Wireless PID : 4060
   Protocol     : HID++ 4.5
   Polling rate : 8 ms
   Serial number: 7D286791
      Bootloader: BOT 18.04.B0017
        Firmware: MPM 11.04.B0017
        Firmware: MPM 11.04.B0017
           Other: 
   The power switch is located on the base.
   Supports 31 HID++ 2.0 features:
       0: ROOT                   {0000}   
       1: FEATURE SET            {0001}   
       2: DEVICE FW VERSION      {0003}   
       3: DEVICE NAME            {0005}   
       4: WIRELESS DEVICE STATUS {1D4B}   
       5: unknown:0020           {0020}   
       6: BATTERY STATUS         {1000}   
       7: unknown:1806           {1806}   internal, hidden
       8: unknown:1814           {1814}   
       9: unknown:1B04           {1B04}   
      10: unknown:2201           {2201}   
      11: VERTICAL SCROLLING     {2100}   
      12: unknown:2110           {2110}   
      13: unknown:2121           {2121}   
      14: unknown:6501           {6501}   
      15: unknown:00C1           {00C1}   
      16: unknown:1813           {1813}   internal, hidden
      17: unknown:1830           {1830}   internal, hidden
      18: unknown:1890           {1890}   internal, hidden
      19: unknown:1891           {1891}   internal, hidden
      20: unknown:18A1           {18A1}   internal, hidden
      21: unknown:18C0           {18C0}   internal, hidden
      22: unknown:1DF3           {1DF3}   internal, hidden
      23: unknown:1E00           {1E00}   hidden
      24: unknown:1EB0           {1EB0}   internal, hidden
      25: unknown:1803           {1803}   internal, hidden
      26: unknown:1861           {1861}   internal, hidden
      27: unknown:9000           {9000}   internal, hidden
      28: unknown:9200           {9200}   internal, hidden
      29: unknown:9240           {9240}   internal, hidden
      30: unknown:1805           {1805}   internal, hidden
   Battery status unavailable.

**Comment by doctor64** [comment]
Can you please provide output of 'solaar -dd show' ?

**Comment by dannietjoh** [comment]
Hi, sorry for the late reply;

solaar -dd show
/usr/share/solaar/lib/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)

**Comment by doctor64** [comment]
Ah, you using older version of solaar. Can you provide output of solaar-cli -dd show and, if it possible, try to use code from master branch of this repo?

**Comment by netzwerch** [comment]
I just now tried with the latest version from git, and I can confirm that I can see the the battery status of my MX Master when I unplug the cable: _Battery: 90%, discharging._. When the cable is attached it (solaar show) shows _Battery: 0%, full._

**Comment by AlexWayfer** [comment]
> I just now tried with the latest version from git, and I can confirm that I can see the the battery status of my MX Master when I unplug the cable: Battery: 90%, discharging.. When the cable is attached it (solaar show) shows Battery: 0%, full.

The same for MX Master 2S.

For 0% while charging: #265

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
