### ISSUE TITLE
Configuring thumb button MX Master

### ISSUE THREAD

**Issue by jfkpdq** [pwr-Solaar/Solaar#338]
Hi,

I struggle to understand how the thumb button works (Mint 18.1). Here is the `xev` log (from pressing two times):

> 

    KeyPress event, serial 37, synthetic NO, window 0x6400001, root 0xf5, subw 0x0, time 20443872, (-455,-283), root:(1367,722), state 0x10, keycode 37 (keysym 0xffe3, Control_L), same_screen YES, XLookupString gives 0 bytes: XmbLookupString gives 0 bytes: XFilterEvent returns: False

    KeyPress event, serial 37, synthetic NO, window 0x6400001, root 0xf5, subw 0x0, time 20443880, (-455,-283), root:(1367,722), state 0x14, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES, XLookupString gives 0 bytes: XmbLookupString gives 0 bytes: XFilterEvent returns: False

    FocusOut event, serial 37, synthetic NO, window 0x6400001, mode NotifyGrab, detail NotifyAncestor

    FocusOut event, serial 37, synthetic NO, window 0x6400001, mode NotifyWhileGrabbed, detail NotifyNonlinear

    PropertyNotify event, serial 37, synthetic NO, window 0x6400001, atom 0x16b (_NET_WM_STATE), time 20443950, state PropertyNewValue

    FocusIn event, serial 37, synthetic NO, window 0x6400001, mode NotifyWhileGrabbed, detail NotifyNonlinear

    KeymapNotify event, serial 37, synthetic NO, window 0x0, keys: 0 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

    FocusIn event, serial 37, synthetic NO, window 0x6400001, mode NotifyUngrab, detail NotifyNonlinear

    KeymapNotify event, serial 37, synthetic NO, window 0x0, keys: 3 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

    KeyRelease event, serial 37, synthetic NO, window 0x6400001, root 0xf5, subw 0x0, time 20445256, (-455,-283), root:(1367,722), state 0x14, keycode 37 (keysym 0xffe3, Control_L), same_screen YES, XLookupString gives 0 bytes: XFilterEvent returns: False

    PropertyNotify event, serial 37, synthetic NO, window 0x6400001, atom 0x16b (_NET_WM_STATE), time 20445283, state PropertyNewValue

The shortcuts setting tells me the action of the button is read "CTRL + ALT + TAB" but the TAB is somehow removed at some point as the log shows. As a result it's not a true "CTR + ALT + TAB" and this is proved by the action that I got in Mint: a movement back and forth ad infinitum from the window I'm on to the last one displayed - and not a selection of all open applications. 

So my question is: does Solaar play a role in this reaction?

**Comment by doctor64** [comment]
I'm not the expert, but, basically, solaar only configure device, and does not interact with device events (except connection/battery events). At least i didn't see such things in sources.
Did you try evtest? It should work on lower level and give some info on keys received by HID.

**Comment by jfkpdq** [comment]
Thanks, yes I try `evtest` it shows a `CTR + ALT + TAB` sequence as in the shortcuts setting. 

But it's getting clearer. There is an issue between `CTR + ALT + TAB` and `xbindkeys`. If I open `dconf-editor` I have those command and shortcuts (under: org/cinnamon/desktop/keybindings/wm): 

- switch-panel: `CTR + ALT + TAB`
- switch-windows: `ALT + TAB`

For a reason that I don't understand, and that probably one of you does, my modification in dconf has not impact on the system. I tried to remove the value of "switch-panel", but it did not change anything. As soon as I remove this, I'll be free to use the combination in `xbindkeys`. 

Any idea on how to do that?

**Comment by doctor64** [comment]
Did you check key bindings in Mate tweak tool? I'm think it is tool to configure keyboard shortcuts in MATE environment. Maybe it processed by MATE before `xbindkeys`. Sorry, i use xfce and can't check it by myself.
