### ISSUE TITLE
MX Master: DPI value resets to 1000 after turning off mouse / mouse wake

### ISSUE THREAD

**Issue by oryband** [pwr-Solaar/Solaar#356]
```bash
$ solaar config 1 dpi 800
# dpi
dpi = NamedInt(800, '800')

# turn mouse off and on
$ solaar config 1 dpi
# dpi
#   possible values: one of [ 400, 600, 800, 1000, 1200, 1400, 1600 ], or higher/lower/highest/max/lowest/min
dpi = NamedInt(1000, '1000')

$ cat .config/solaar/config.json
{
  "4060:54420744": {
    "_name": "Wireless Mouse MX Master",
    "dpi": "800",  # unquoting this doesn't help
    "smart-shift": 50
  },
  "_version": "0.9.2"
}
```
Tried also to unquote the DPI value in `config.json` as suggested in #328 to no avail.

Any idea what's going on?

```
$ solaar show
Unifying Receiver
  Device path  : /dev/hidraw4
  USB id       : 046d:c52b
  Serial       : 5562921B
    Firmware   : 24.01.B0023
    Bootloader : 01.08
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=201

  1: Wireless Mouse MX Master
     Codename     : MX Master
     Kind         : mouse
     Wireless PID : 4060
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 54420744
        Bootloader: BOT 18.05.B0018
          Firmware: MPM 11.05.B0018
          Firmware: MPM 11.05.B0018
             Other: 
     The power switch is located on the base.
     Supports 31 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
         7: unknown:1806           {1806}   internal, hidden
         8: CHANGE HOST            {1814}   
         9: REPROG CONTROLS V4     {1B04}   
        10: ADJUSTABLE DPI         {2201}   
        11: VERTICAL SCROLLING     {2100}   
        12: SMART SHIFT            {2110}   
        13: HIRES WHEEL            {2121}   
        14: GESTURE 2              {6501}   
        15: DFUCONTROL 2           {00C1}   
        16: unknown:1813           {1813}   internal, hidden
        17: unknown:1830           {1830}   internal, hidden
        18: unknown:1890           {1890}   internal, hidden
        19: unknown:1891           {1891}   internal, hidden
        20: unknown:18A1           {18A1}   internal, hidden
        21: unknown:18C0           {18C0}   internal, hidden
        22: unknown:1DF3           {1DF3}   internal, hidden
        23: unknown:1E00           {1E00}   hidden
        24: unknown:1EB0           {1EB0}   internal, hidden
        25: unknown:1803           {1803}   internal, hidden
        26: unknown:1861           {1861}   internal, hidden
        27: unknown:9000           {9000}   internal, hidden
        28: unknown:9200           {9200}   internal, hidden
        29: unknown:9240           {9240}   internal, hidden
        30: unknown:1805           {1805}   internal, hidden
     Battery: 90%, discharging.
```

**Comment by doctor64** [comment]
Hmm, i just check with my M185 - configuration successfully applied after power on. Please, can you test with latest version from git and, if problem still present, perform next steps:
run ./solaar -dd
turn off mouse, wait few seconds, turn it on again
and provide output?

**Comment by oryband** [comment]
@doctor64 apparently the issue disappears when Solaar is running in the background. I thought Solaar is a foreground cli tool only, and wasn't aware that it needed to be run in the background. It's not written in frontpage README at all. What am I missing here?

**Comment by wjdp** [comment]
I have an MX Master 2S and am having this issue even with solaar running in the background.

Running latest from git `0.9.2-216-g8c0cf9f`

**Comment by blyork** [comment]
How does solaar auto start in Ubuntu 16.04? It appears that is does not create, load, or save changes to the config in ~/.config/solaar/config.json unless you kill the process and load it into the foreground by typing "solaar" in the terminal.

**Comment by guygma** [comment]
I also see this issue running on Arch with the solaar-git PKGBUILD from the AUR. The configuration file is actually created just fine, but it seems that that those settings are not reloaded upon the mouse waking from sleep.

**Comment by euri10** [comment]
I also have the issue, when I switch off/on the mouse dpi is reseted to 1000, and the gtk app pops

```
➜  ~ solaar config 1 dpi 1600
# dpi
dpi = NamedInt(1600, '1600')
➜  ~ solaar config 1
Wireless Mouse MX Master (MX Master) [4071:74530C8A]

# High Resolution Wheel Invert
# High-sensitivity wheel invert mode for vertical scroll.
#   possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
hires-smooth-invert = False

# Wheel Resolution
# High-sensitivity mode for vertical scroll with the wheel.
#   possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
hires-smooth-resolution = False

# dpi
#   possible values: one of [ 400, 600, 800, 1000, 1200, 1400, 1600 ], or higher/lower/highest/max/lowest/min
dpi = NamedInt(1600, '1600')

# Smart Shift
# Automatically switch the mouse wheel between ratchet and freespin mode. The mouse wheel is always free at 0, and always locked at 50
smart-shift = 16
➜  ~ solaar config 1
Wireless Mouse MX Master (MX Master) [4071:74530C8A]

# High Resolution Wheel Invert
# High-sensitivity wheel invert mode for vertical scroll.
#   possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
hires-smooth-invert = False

# Wheel Resolution
# High-sensitivity mode for vertical scroll with the wheel.
#   possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
hires-smooth-resolution = False

# dpi
#   possible values: one of [ 400, 600, 800, 1000, 1200, 1400, 1600 ], or higher/lower/highest/max/lowest/min
dpi = NamedInt(1000, '1000')

# Smart Shift
# Automatically switch the mouse wheel between ratchet and freespin mode. The mouse wheel is always free at 0, and always locked at 50
smart-shift = 16
```

**Comment by mvu** [comment]
I also had this issue for a while, so today I decided to debug the code. And I found out that one reason was this part in solaar/listener.py:

```
# a device notification
                assert n.devnumber > 0 and n.devnumber <= self.receiver.max_devices
                already_known = n.devnumber in self.receiver
                already_known = false
                if n.sub_id == 0x41:

                        dev = self.receiver.register_new_device(n.devnumber, n)
                else:
                        dev = self.receiver[n.devnumber]
```

Whenever my mouse turned off it (oddly) triggered a notification with `sub_id=0x41` which is used for registering new devices. The notification handler tried to register the device but of course failed since it never received a notification to unregister:

```
18:11:18,008  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4060,MX Master)>: unrecognized Notification(1,02,00,0005E00000005900000000) for feature DEVICE FW VERSION (index 02)
18:11:22,037    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (12) => r[10 01 4104 726040]
18:11:22,037    ERROR [ReceiverListener:hidraw0] logitech_receiver.listener: processing Notification(1,41,04,726040)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/usr/lib/python3.6/site-packages/solaar/listener.py", line 189, in _notifications_handler
    dev = self.receiver.register_new_device(n.devnumber, n)
  File "/usr/lib/python3.6/site-packages/logitech_receiver/receiver.py", line 407, in register_new_device
    raise IndexError("%s: device number %d already registered" % (self, number))
IndexError: <UnifyingReceiver(/dev/hidraw0,12)>: device number 1 already registered
18:11:22,039    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (12) => r[20 01 4201 0000000000000000000000]
18:11:22,039  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,4060,MX Master)>: unrecognized Notification(1,42,01,0000000000000000000000)
18:11:26,077    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (12) => r[10 01 4104 B26040]
18:11:26,077    ERROR [ReceiverListener:hidraw0] logitech_receiver.listener: processing Notification(1,41,04,B26040)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/usr/lib/python3.6/site-packages/solaar/listener.py", line 189, in _notifications_handler
    dev = self.receiver.register_new_device(n.devnumber, n)
  File "/usr/lib/python3.6/site-packages/logitech_receiver/receiver.py", line 407, in register_new_device
    raise IndexError("%s: device number %d already registered" % (self, number))
IndexError: <UnifyingReceiver(/dev/hidraw0,12)>: device number 1 already registered
18:11:26,079    DEBUG [ReceiverListener:hidraw0] logitech_receiver.base: (12) => r[20 01 4200 0000000000000000000000]
```

The same happened when I turned the mouse back on. So I changed that code to:

```
# a device notification
                assert n.devnumber > 0 and n.devnumber <= self.receiver.max_devices
                already_known = n.devnumber in self.receiver

                if n.sub_id == 0x41 and not already_known:
                        dev = self.receiver.register_new_device(n.devnumber, n)
                else:
                        dev = self.receiver[n.devnumber]
```

and now it works!

**Comment by oryband** [comment]
@mvu Awesome! Care to submit a PR? I would also like to enjoy the fruits of your labor :)

**Comment by mvu** [comment]
After taking a closer look to the logs of @euri10 it seems like my workaround would not solve his problem since he gets different error messages. Hence I will be waiting until submitting a PR. I would appreciate if you want to try it and report back if it works for you. I edited my last post with the corresponding such that the change is just commenting out two lines. It makes the program re-register the mouse whenever it is turned on or off instead of just throwing an exception.

**Comment by oryband** [comment]
OK I've found a completely different workaround for this problem: Resetting the DPI whenever the mouse wakes up.

I'm using [udev](https://wiki.archlinux.org/index.php/udev) rules for this, but it's not that much work.

1. Execute `udevadm monitor` and turn your mouse off and on. It will show you the event that the OS is seeing upon connection. In my case it was:
```
KERNEL[18817.205572] change   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.3/1-2.3:1.2/0003:046D:C52B.0008/0003:046D:4060.0009/power_supply/hidpp_battery_0 (power_supply)
UDEV  [18817.217753] change   /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.3/1-2.3:1.2/0003:046D:C52B.0008/0003:046D:4060.0009/power_supply/hidpp_battery_0 (power_supply)
```

2. Create the following file:
```
# /etc/udev/rules.d/mouse.rules
# mouse.rules is just a name i chose, just have it end with `.rules`
ACTION=="change", SUBSYSTEM=="power_supply", KERNEL=="hidpp_battery_0", RUN+="/usr/bin/solaar config 1 dpi 600"
```
Notice the variable arguments depend on the result I got from `udevadm monitor`. You'll probably have to edit this according to what you see on your machine.

3. Reload udev by executing `sudo udevadm control --reload` (older udev versions used `--reload-rules` parameter instead of `--reload`)

4. Not  turn your mouse off and on again and see if works. Use `journalctl -fxe` for debugging if something doesn't work.

Hope that helps. Please lemme know if this has worked for you.

**Comment by oryband** [comment]
Btw you can use this truck to execute any other commands when the mouse connects / disconnects. Just call a different command / script.

**Comment by oryband** [comment]
UPDATE: I've updated the udev rule to `KERNEL=="hidpp_battery_*"` since after a long suspend (like when a day has passed) sometimes the mouse is shown with a different `hidpp_batery_X` battery index i.e. X = 0,1,2. The wildcard `_*` catches them all for the rule.

**Comment by mvu** [comment]
Thanks, I have considered this workaround, but this does not allow you to change the DPI on the fly anymore. Since I don't need to change my DPI I will use that until a fix is found :)

**Comment by mvu** [comment]
Btw, if you want a more precise udev rule, you can just filter by `idProduct` and `idVendor`:
1. Execute `udevadm info -a -p /sys/class/power_supply/hidpp_battery_0/`
2. Find the first entries for `idProduct` and `idVendor` (in my case it's `ATTRS{idProduct}=="c52b"` and `ATTRS{idVendor}=="046d"`)
3. Put them into the rules file:
`ACTION=="change", SUBSYSTEM=="power_supply", ATTRS{idVendor}=="046d", ATTRS{idProduct}=="c52b", ATTR{online}=="1", RUN+="/usr/bin/solaar config 1 dpi 1600"`

`ATTR{online}=="1"` makes sure it only executes solaar when I turn the mouse on and not when turning off.

**Comment by bittylicious** [comment]
I confirm this is also an issue with my MX Master 2.

**Comment by arigit** [comment]
I am having this issue as well with the latest release. 
I believe the PR mentioned above (RE  #452) does not fix this problem. This is also with MX Master 2S

**Comment by lopsided98** [comment]
I think there are still problems with Solaar applying settings after the computer wakes from sleep, but I believe #452 fixes the original issue, which was that Solaar did not apply settings after the mouse woke from sleep. Have you tried the `--restart-on-wake-up` option? According to https://github.com/pwr/Solaar/issues/443#issuecomment-412917841 this may fix the issue.

**Comment by lopsided98** [comment]
Is 1000 the default DPI? If you turn the mouse off and on after resume, does the DPI get applied correctly?

I think I am experiencing a similar issue with the smooth scroll option on my M705 after my computer wakes up, so I'll try to fix my issue and maybe it will fix your problem as well. I don't know exactly how `--restart-on-wake-up` works: maybe it doesn't apply the settings correctly. I probably won't get a chance look into it until at least next week because I have finals this week.

**Comment by arigit** [comment]
@lopsided98 thanks for looking into this.
Just upgraded to the latest master as of today
I did the test: With the Solaar GUI, I set DPI=1500, smartshift = 10; then I quit solaar, then I turn off the mouse. Then I turning it on, with solaar NOT running; here's what I see (querying with solaar config (CLI) and also confirming by observing the mouse response): DPI = 1000, smart-shift=10.
So the smart-shift setting survives (without solaar's help) but DPI doesn't.
Starting solaar (with or without restart-on-wake-up) immediately corrects the DPI to the last one set in the GUI. The version I was using before didn't have this behavior, there were a few PR's merged after it so guess that explains.

Now a new problem I did not observe before: #444 - after a few minutes the GUI no longer detects the receiver, it's weird. Will continue the discussion there

**Comment by kdickerson** [comment]
I'm seeing the same behavior as @arigit; also MX Master 2S.  Mint 19 / Ubuntu 18.04.

Additionally the correctly stored config value for dpi is not set on the mouse during system boot though Solaar is running when I log in.  This occurs if the mouse is not awake before Solaar starts.  If I move the mouse before logging in (which wakes it up) then the correct config gets set upon login when Solaar starts.

**Comment by jvetulani** [comment]
Hi, I'm still having this issue on Ubuntu 20.04 with solaar 1.0.4 and an MX Master 2S.
Not only does the DPI change by itself but so does the Scroll Wheel Resolution.

Tho the Solaar UI doesn't register the change and I need to click to a different DPI and then back to my chosen one, and cycle through the scroll setting.

**Comment by pfps** [comment]
Version 1.0.4 still has a version of this problem.  A commit on 22 November 2020 fixes it.   Currently you need to clone Solaar from this repository.   Version 1.0.5 should be coming out in a week or so, but a pre-release version is available via pip.  See also #1061
