### ISSUE TITLE
Does not work under True Linux Centos or Redhat 

### ISSUE THREAD

**Issue by Necronn99** [pwr-Solaar/Solaar#358]
I really wish they stop calling Ubuntu linux it is not. IT is dabien and CENTOS FEDORA REDHAT is Linux. morons.

**Comment by dfgg12** [comment]
In my case Solaar works flawlessly under Arch Linux, which is absolutely not Redhat Linux derivative nor Debian.

What's your issue with Solaar? Any logs?

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
