### ISSUE TITLE
enable wake up from keyboard but not from mouse with single unifying receiver

### ISSUE THREAD

**Issue by Bercio** [pwr-Solaar/Solaar#361]
How can I disable the logitech wireless mouse from waking up the suspended computer while allowing the logitech wireless keyboard to wake it up if they're both connected to the same unifying receiver?

**Comment by dennisyv** [comment]
+1

**Comment by jrbenito** [comment]
Hi,

This is not a solaar feature but Linux kernel´s one. [This link](https://askubuntu.com/questions/848698/wake-up-from-suspend-using-wireless-usb-keyboard-or-mouse-for-any-linux-distro) shall clarify ways to control it.

To summarize, modify your udev rules to only allow wakeup for keyboard device. Did not test so I don´t know if it works for mouse/keyboard paired with same receiver.
