### ISSUE TITLE
Logitech G403 not compatible?

### ISSUE THREAD

**Issue by ghost** [pwr-Solaar/Solaar#362]
Do you take requests? The G series of Logitech it's pretty popular, I was wondering if you plan to add support for it eventually in the future (I'm looking for a way to show battery percentage on linux).
Here's the mouse: http://gaming.logitech.com/en-us/product/g403-prodigy-wireless-gaming-mouse

Here's the terminal output for the device:
```
$ lsusb -d 046d:
Bus 001 Device 006: ID 046d:c082 Logitech, Inc. 
Bus 001 Device 002: ID 046d:c539 Logitech, Inc. 
```

**Comment by jrbenito** [comment]
@hhiru ,

I don´t have one of these in hands to try. Are you wheeling to help? If yes we can work together and try, I can send patches and you need to test them. Let me know.

regards,
Benito.

**Comment by hhiru** [comment]
Tell me what to do and I'll gladly help you ;)

**Comment by jrbenito** [comment]
Nice!
According to Logitech, this mouse uses 

> Wireless technology: Custom 2.4GHz

which is not Unifying and probably not the Quad Protocol... So, first of all, I need to know which one of the devices you listed is the receiver. I presume it is C539 right?

If so, please, download latest master repo by doing:

`$ git clone https://github.com/pwr/Solaar.git`

Find the file `Solaar/rules.d/42-logitech-unify-permissions.rules` and `https://github.com/pwr/Solaar/blob/master/packaging/debian/solaar.udev` - they are pretty much the same. You need to add your receiver (`c539`) to the "other nano receivers" section and use the `install.sh` (rules.d directory) to install it in your system. 

Now, find file `Solaar/lib/logitech_receiver/base_usb.py` and add the receiver to there as:

```
[...]
NANO_RECEIVER_C52e        = _nano_receiver(0xc52e)
NANO_RECEIVER_C531        = _nano_receiver(0xc531)
NANO_RECEIVER_C539        = _nano_receiver(0xc539)
[...]
ALL = (
[...]
                NANO_RECEIVER_C52e,
		NANO_RECEIVER_C531,
               NANO_RECEIVER_C539,
	)
```

Now, run solaar from this source:

```
$ cd Solaar
$ bin/solaar show
```
Post results here. Then run again with debug active and post here too.

If you need references on how to implement these changes look PR #337 for files above. And don´t hesitate to contact me.

Regards,
Benito.

**Comment by hhiru** [comment]
You told me to find the file `https://github.com/pwr/Solaar/blob/master/packaging/debian/solaar.udev` but there is no file like that in my solaar folder. do I have to download and place it somewhere? Also I think I had two results in my first post because at the moment I had the receiver in a port and the mouse linked via cable in another port, using it wirelessly only shows the receiver that's the one you guessed right.

**Comment by jrbenito** [comment]
Did you install solaar by package manager of you distro?

**Comment by hhiru** [comment]
My bad, now I edited the file. This is the output:

> Solaar: missing required package 'python-pyudev'

**Comment by jrbenito** [comment]
you have to install python-pyudev

you can try it by package manager (i.e `sudo apt-get ...`) or pip (`pip install pyudev`)

**Comment by hhiru** [comment]
So, after I used solaar show it opened solaar (there's the icon in the topbar) and nothing in the terminal

**Comment by jrbenito** [comment]
Are you sure you run solaar from the downloaded directory instead of system wide? The behavior you described is more like the old solaar that use to have solaar for GUI and solaar-cli for the terminal. The latest code in this repo, if should display information regarding devices on the terminal if "show" parameter is passed on execution.

**Comment by hhiru** [comment]
You are right sorry my bad. This is the actual output:

> solaar: error: Logitech receiver not found

**Comment by jrbenito** [comment]
Ok, this means one of two possibilities:

1. changes to solaar had no effect
2. changes to udev rules were not installed 

I bet on the second. If you probably have a file in `/etc/udev/rules.d` called `42-logitech-unify-permissions.rules` (42 can be any number, this is just a ordering number). Please, find it and edit just like you did to `Solaar/rules.d/42-logitech-unify-permissions.rules` and `[...]/debian/solaar.udev`.

After that reboot your PC and run `solaar show` again.

**Comment by hhiru** [comment]
Same error after reboot 

> solaar: error: Logitech receiver not found

**Comment by jrbenito** [comment]
Please use debug while running solar show

Em 18 de mai de 2017 18:13, "hiru" <notifications@github.com> escreveu:

**Comment by hhiru** [comment]
> $ bin/solaar -d show
> solaar: error: Logitech receiver not found
>

**Comment by jrbenito** [comment]
@hhiru ,

Sorry for late reply. 

For the result you post, Solaar still not able to locate your receiver. Please, post you `/etc/udev/rules.d/42-logitech-unify-permissions.rules` and other files you changed so we can inspect. If you forked the repo under your user, point me URL and I can check files there.

Thanks,
Benito.

**Comment by gyaru** [comment]
Hi, I have the same mouse and I'd love solaar support for it too.

I've followed the instructions you wrote to hhiru and this is my result.

This is my [commit](https://github.com/gyaru/Solaar/commit/26d68f4710eb59f3e70713f484fe7cc9889b5d61) with the suggested changes.

`~/projects/Solaar/bin ±master☀ > ./solaar show`

```
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/gyaru/projects/Solaar/lib/logitech_receiver/receiver.py", line 364, in __del__
    self.close()
  File "/home/gyaru/projects/Solaar/lib/logitech_receiver/receiver.py", line 360, in close
    self._devices.clear()
AttributeError: 'Receiver' object has no attribute '_devices'
solaar: error: Logitech receiver not found
```

**Comment by jp-roy** [comment]
Hello !

I have a 403 wireless as well and wheeling to help as well if needed :)

**Comment by bcurtiswx** [comment]
(solaar:18687): GLib-GIO-CRITICAL **: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <object repr() failed> ignored

G403 Logitech

**Comment by ViktorPegy** [comment]
Debug solaar output:
```
20:39:36,275     INFO [MainThread] root: language ru_RU (UTF-8), translations path None
20:39:36,367     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
20:39:36,440     INFO [MainThread] solaar.listener: starting receiver listening threads
20:39:36,459     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path=u'/dev/hidraw1', vendor_id=u'046d', product_id=u'c539', serial=u'\nMODALIAS=hid:b0003g0001v0000046Dp0000C539', release='3901', manufacturer='Logitech', product='USB Receiver', interface=1, driver=u'hid-generic')
20:39:36,459    ERROR [MainThread] logitech_receiver.base: write failed, assuming handle 13 no longer available
20:39:36,459    ERROR [MainThread] logitech_receiver.receiver: open DeviceInfo(path=u'/dev/hidraw1', vendor_id=u'046d', product_id=u'c539', serial=u'\nMODALIAS=hid:b0003g0001v0000046Dp0000C539', release='3901', manufacturer='Logitech', product='USB Receiver', interface=1, driver=u'hid-generic')
Traceback (most recent call last):
  File "/tmp/Solaar/lib/logitech_receiver/receiver.py", line 529, in open
    return Receiver(handle, device_info)
  File "/tmp/Solaar/lib/logitech_receiver/receiver.py", line 340, in __init__
    serial_reply = self.read_register(_R.receiver_info, 0x03)
  File "/tmp/Solaar/lib/logitech_receiver/hidpp10.py", line 142, in read_register
    return device.request(request_id, *params)
  File "/tmp/Solaar/lib/logitech_receiver/receiver.py", line 442, in request
    return _base.request(self.handle, 0xFF, request_id, *params)
  File "/tmp/Solaar/lib/logitech_receiver/base.py", line 340, in request
    write(ihandle, devnumber, request_data)
  File "/tmp/Solaar/lib/logitech_receiver/base.py", line 171, in write
    raise NoReceiver(reason=reason)
NoReceiver: {'reason': OSError(32, '\xd0\x9e\xd0\xb1\xd1\x80\xd1\x8b\xd0\xb2 \xd0\xba\xd0\xb0\xd0\xbd\xd0\xb0\xd0\xbb\xd0\xb0')}
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <object repr() failed> ignored
20:39:36,460  WARNING [MainThread] solaar.listener: failed to open DeviceInfo(path=u'/dev/hidraw1', vendor_id=u'046d', product_id=u'c539', serial=u'\nMODALIAS=hid:b0003g0001v0000046Dp0000C539', release='3901', manufacturer='Logitech', product='USB Receiver', interface=1, driver=u'hid-generic')

(solaar:21108): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

**Comment by ViktorPegy** [comment]
@jrbenito, can u help?

**Comment by FFY00** [comment]
Fixed by https://github.com/pwr/Solaar/pull/530

**Comment by pfps** [comment]
Did PR #530 solve the issue?

**Comment by pfps** [comment]
Closing due to no response from original poster.
