### ISSUE TITLE
Logitech M720

### ISSUE THREAD

**Issue by mksglu** [pwr-Solaar/Solaar#364]
I'm an Manjaro user. How do I change the functions of the buttons on the Logitech M720 model mouse?

**Comment by pfps** [comment]
Solaar does not (yet) have the ability to reprogram buttons and keys.

**Comment by mksglu** [comment]
> Solaar does not (yet) have the ability to reprogram buttons and keys.

I have.
https://www.mkoseoglu.com/linux-mouse-konfigurasyonu
