### ISSUE TITLE
Linux Mint System Tray Issue

### ISSUE THREAD

**Issue by npat3** [pwr-Solaar/Solaar#369]
I am currently on Linux Mint 18.2 Cinnamon and am having issues with Solaar inconsistently showing up in the System Tray. When I reboot, sometimes the icon is visible and sometimes it is invisible (if I click over the area, "Unifying Receiver" applet options show up, but not the tray icon).

In addition, I have a paired mouse and keyboard, which always function appropriately. However, when I open Solaar, sometimes it may indicate 1 or 0 paired devices and the left window pane may show "Unifying Receiver" without any devices shown below.

I am new to Linux so any help would be greatly appreciated.

![solaar_002](https://user-images.githubusercontent.com/30001391/27985473-6edabf78-63b9-11e7-8c11-ce52dec8bfc8.png)

**Comment by rbbernardino** [comment]
Hello! I'm not sure where is the problem, but for the app GnomePie the same thing happens, I have even seen some issues on their github page, worth checking!

**Comment by npat3** [comment]
Thanks for the suggestion. Unfortunately, I could not find a solution that would apply to this situation.

**Comment by SerafDosSantos** [comment]
For the icon on the system tray, it seems to be a problem with Cinnamon, the desktop environment. Even though I'm on Mint 18.2 also, I don't have a problem with Solaar.

**Comment by npat3** [comment]
Ok, that makes sense. Thanks.

**Comment by Martina-Neumayer** [comment]
With Mate in Mint 18.3 is that same thing. No icon, strange icon, etc, etc..
This app needs ASAP some art of big-fixing or some new "repair" release.

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by npat3** [comment]
Thank you for letting me know. I installed Solaar through the Linux Mint Software Manager. Is it still better to download from the github repository?

**Comment by pfps** [comment]
If you are not experiencing any problems with your distribution's version of Solaar there is no need to download the version from this repository.  If you are experiencing problems, however, it may be that they are fixed in the version of Solaar here, which might not yet be available through your distribution.

**Comment by npat3** [comment]
Ok, thank you very much for your help.

**Comment by pfps** [comment]
OK, closing.
