### ISSUE TITLE
New PyPi release and more expansive docs?

### ISSUE THREAD

**Issue by AndreasBackx** [pwr-Solaar/Solaar#370]
I'm currently trying to get solaar to work on Arch Linux and have to build from the master branch to get it to work at all since the AUR and PyPi versions do not work. They result in the following error:

```
Solaar: missing required package 'python-gi'
```

But `python-gi` is not easily installable on Arch with custom Python versions already installed with `pyenv` for example. Is `python-gi` installable from PyPi perhaps? Could instructions be added on how to setup solaar with pip and other manual installation? Why are the gtk bindings required when using the cli in the first place? I'd simply like to install solaar itself and set it to run in the background myself so I know that it works. Could this also be more thoroughly documented? #356 seems to show that solaar can run itself in the background with the `-dd` parameters? Unfortunately this also requires the `python-gi` package. I don't see why the daemon would want gtk bindings though.

Installing solaar from the master branch allows me to use the show and config commands which is what I wanted so could solaar more regularly get released on PyPi?

**Comment by cben** [comment]
Fedora and Debian still package 0.9.2 which is from 2013.
Presumably tagging a new release would help all the new goodness :clap: eventually trickle downstream...

(I do work at Red Hat; I'm not involved with packaging but feel free to ping me to push something along or just to test things on fedora)

**Comment by cben** [comment]
Corrections:
debian experimental has `0.9.2+git20170921+dfsg-1`.
fedora rawhide has `solaar-0.9.2-4.20150528gitcf27328` (git commit cf27328 is indeed from 2015).
Still, that's several years old, e.g. my K270 receiver was not supported then and is now :-)

**Comment by jasontibbitts** [comment]
Yes, Fedora has been waiting for things to at least close to something called a release before updating.  I would certainly work on getting an update out if a new release was tagged.  Or even if someone said that what's in git at some particular point in time could reasonably be pushed out.  It's just not been clear to me at all that things are in that state.  Sure, it may have more hardware support but we certainly don't want to break people for whom it does currently work.  Personally I can only really test the MX Master.

That said I have done test builds of newer git snapshots for people before in the hope of getting more testing but I didn't really get much in the way of useful feedback.

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response.
