### ISSUE TITLE
Fix home page link to provide the 9.3 .tar.gz file

### ISSUE THREAD

**Issue by MagicFab** [pwr-Solaar/Solaar#373]
The home page still proposes the 9.2 version tar.gz source file for download.
Please fix to reflect the current stable version - which to my understanding is 9.3.

**Comment by Lekensteyn** [comment]
There is still no new public release, the latest tagged version is 0.9.2. After all these changes it might make sense to open a new release though (the master branch is currently recommended for use due to fixes and new features)

**Comment by mkyral** [comment]
+1 for a new release. Btw, version in git sources is set to 0.9.2. Would be nice to have there something to identify "live" version, like 0.9.2-git.

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by skitt** [comment]
@pfps this request has been addressed, since releases have been made; this issie should be closed.

**Comment by pfps** [comment]
Ok, closing this issue.
