### ISSUE TITLE
Unable see devices on restart - Fedora 26

### ISSUE THREAD

**Issue by hhakeem** [pwr-Solaar/Solaar#374]
I'm having problem in which, I've installed 0.9.3 from git, as I have a MX Master, every time I reboot, the logitech keyboard or mouse is not showing up, and I have unplug and re-plug in the micro dongle once or twice for the devices to show up in solaar. 

[ dev]$ solaar show
Unifying Receiver
  Device path  : /dev/hidraw7
  USB id       : 046d:c52b
  Serial       : 06769E65
    Firmware   : 12.07.B0029
    Bootloader : 02.14
    Other      : AA.AA
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=147, 2=49

  1: Wireless Keyboard K360
     Codename     : K360
     Kind         : keyboard
     Wireless PID : 4004
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: ADAF30BD
          Firmware: RQK 36.00.B0007
     The power switch is located on the top case.
     Supports 13 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: BATTERY STATUS         {1000}   
         5: unknown:1820           {1820}   hidden
         6: REPROG CONTROLS        {1B00}   
         7: WIRELESS DEVICE STATUS {1D4B}   
         8: unknown:1DF0           {1DF0}   hidden
         9: unknown:1DF3           {1DF3}   hidden
        10: FN INVERSION           {40A0}   
        11: ENCRYPTION             {4100}   
        12: KEYBOARD LAYOUT        {4520}   
     Has 18 reprogrammable keys:
         0: MY HOME                    => HomePage                      is FN, FN sensitive, reprogrammable
         1: Mail                       => Email                         is FN, FN sensitive, reprogrammable
         2: SEARCH                     => Search                        is FN, FN sensitive, reprogrammable
         3: MEDIA PLAYER               => Music                         is FN, FN sensitive, reprogrammable
         4: Application Switcher       => Application Switcher          is FN, FN sensitive, reprogrammable
         5: SHOW DESKTOP               => ShowDesktop                   is FN, FN sensitive, reprogrammable
         6: MINIMIZE AS WIN M          => WindowsMinimize               is FN, FN sensitive, reprogrammable
         7: MAXIMIZE AS WIN SHIFT M    => WindowsRestore                is FN, FN sensitive, reprogrammable
         8: MY COMPUTER AS WIN E       => My Computer                   is FN, FN sensitive, reprogrammable
         9: Lock PC                    => WindowsLock                   is FN, FN sensitive, reprogrammable
        10: SLEEP                      => Sleep                         is FN, FN sensitive, reprogrammable
        11: Calculator                 => Calculator                    is FN, FN sensitive, reprogrammable
        12: Previous                   => Previous                      nonstandard
        13: Play/Pause                 => Play/Pause                    nonstandard
        14: Next                       => Next                          nonstandard
        15: Mute                       => Mute                          nonstandard
        16: Volume Down                => Volume Down                   nonstandard
        17: Volume Up                  => Volume Up                     nonstandard
     Battery: 90%, discharging.

  2: Wireless Mouse MX Master
     Codename     : MX Master
     Kind         : mouse
     Wireless PID : 4060
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 588F2AD4
        Bootloader: BOT 18.05.B0018
          Firmware: MPM 11.05.B0018
          Firmware: MPM 11.05.B0018
             Other: 
     The power switch is located on the base.
     Supports 31 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
         7: unknown:1806           {1806}   internal, hidden
         8: CHANGE HOST            {1814}   
         9: REPROG CONTROLS V4     {1B04}   
        10: ADJUSTABLE DPI         {2201}   
        11: VERTICAL SCROLLING     {2100}   
        12: SMART SHIFT            {2110}   
        13: HIRES WHEEL            {2121}   
        14: GESTURE 2              {6501}   
        15: DFUCONTROL 2           {00C1}   
        16: unknown:1813           {1813}   internal, hidden
        17: unknown:1830           {1830}   internal, hidden
        18: unknown:1890           {1890}   internal, hidden
        19: unknown:1891           {1891}   internal, hidden
        20: unknown:18A1           {18A1}   internal, hidden
        21: unknown:18C0           {18C0}   internal, hidden
        22: unknown:1DF3           {1DF3}   internal, hidden
        23: unknown:1E00           {1E00}   hidden
        24: unknown:1EB0           {1EB0}   internal, hidden
        25: unknown:1803           {1803}   internal, hidden
        26: unknown:1861           {1861}   internal, hidden
        27: unknown:9000           {9000}   internal, hidden
        28: unknown:9200           {9200}   internal, hidden
        29: unknown:9240           {9240}   internal, hidden
        30: unknown:1805           {1805}   internal, hidden
     Has 8 reprogrammable keys:
         0: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
             mse, pos:0, group:1, gmask:1
         1: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
             mse, pos:0, group:1, gmask:1
         2: MIDDLE BUTTON             , default: MiddleMouseButton           => MIDDLE BUTTON             
             divertable, mse, reprogrammable, pos:0, group:3, gmask:7
         3: BACK AS BUTTON 4          , default: BackEx                      => BACK AS BUTTON 4          
             divertable, mse, reprogrammable, pos:0, group:2, gmask:3
         4: FORWARD AS BUTTON 5       , default: BrowserForwardEx            => FORWARD AS BUTTON 5       
             divertable, mse, reprogrammable, pos:0, group:2, gmask:3
         5: unknown:00C3              , default: unknown:00A9                => unknown:00C3              
             divertable, mse, reprogrammable, pos:0, group:3, gmask:7
         6: unknown:00C4              , default: unknown:009D                => unknown:00C4              
             divertable, mse, reprogrammable, pos:0, group:3, gmask:7
         7: unknown:00D7              , default: unknown:00B4                => unknown:00D7              
             divertable, virtual, pos:0, group:4, gmask:0
     Battery: 50%, discharging.

[dev]$ ls -al | grep hidraw
crw-------.  1 root    root      247,   0 Aug 11 17:17 hidraw0
crw-rw----+  1 root    hhakeem   247,   7 Aug 11 17:20 hidraw7
crw-rw----+  1 root    root      247,   8 Aug 11 17:20 hidraw8
crw-rw----+  1 root    root      247,   9 Aug 11 17:20 hidraw9

[hhakeem@hh-linux-t20 rules.d]$ ls -al | grep logitech
-rw-r--r--. 1 root root 2028 Aug 11 16:13 42-logitech-unify-permissions.rules

**Comment by alisonken1** [comment]
Just upgraded to Fedora KDE 26 and I have to stop/restart Solaar at least 3 times after logging in before Solaar sees the Logitech Unified Device as well as the keyboard (K350) and mouse (M570).

solaar show
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 93C2932B
    Firmware   : 12.01.B0019
    Bootloader : 02.14
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=40, 2=47

  1: Wireless Trackball M570
     Codename     : M570
     Kind         : mouse
     Wireless PID : 1028
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: 8FF777D0
          Firmware: 26.00.B0003
        Bootloader: 02.06
             Other: 00.01
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Battery: 80%, discharging.

  2: Wireless Wave Keyboard K350
     Codename     : K350
     Kind         : keyboard
     Wireless PID : 200A
     Protocol     : HID++ 1.0
     Polling rate : 20 ms (50Hz)
     Serial number: A3011C6E
          Firmware: 65.00.B0003
             Other: 00.01
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Battery: full, discharging.

**Comment by jrbenito** [comment]
This is fixed by #382

**Comment by wpaule** [comment]
Does the new version of Solaar no longer haave the gui for paring devices? I am running Solaar with a new Fedora 26 build, and the show and pair commands work, but if I just type solaar, the gui that I get with the Ubuntu versions does not come up. I get the following:

/usr/lib/python2.7/site-packages/solaar/gtk.py:34: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
/usr/lib/python2.7/site-packages/solaar/ui/notify.py:33: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/site-packages/solaar/ui/tray.py:148: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3

(solaar:15541): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Thanks in advance.

**Comment by wpaule** [comment]
Okay, now the gui window comes up, but the unifying receiver is not detected. even though it shows up in lsusb. When solaar is run from the command line now, I get the following:

/usr/lib/python2.7/site-packages/solaar/gtk.py:34: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
/usr/lib/python2.7/site-packages/solaar/ui/notify.py:33: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/site-packages/solaar/ui/tray.py:148: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3

Thanks in advance.

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original poster.
