### ISSUE TITLE
Strange behavior M705 mouse and crashing

### ISSUE THREAD

**Issue by neural-oD** [pwr-Solaar/Solaar#377]
Hi, thanks for solaar it's generally great. Just at the moment, I'm having an issue. I have a MK700/710 keyboard and M705 mouse. 
I'm running fedora 25 with the latest solaar.
All of a sudden, the mouse has been giving strange issues, like moving to different tabs etc, while on a browser. 
Also I've never been able to "click" on the solar icon, it keeps crashing.
I ran a debug so hopefully someone here could figure out what's going on. 
Please see the debug file attached.
I was particularily concerned with the warning....unrecognized Notification
If someone could please have a look at this, it would be much appreciated.
[solaar_bug1.txt](https://github.com/pwr/Solaar/files/1225288/solaar_bug1.txt)

**Comment by ckol** [comment]
I am working with the same combination, also experiencing random issues when I play around with the Smooth Scrolling and Side Scrolling toggles. With Side Scrolling ON, any left/right-clicks stopped working.

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original poster.
