### ISSUE TITLE
Manjaro 17.02, Solar not in Top Panel or System Tray

### ISSUE THREAD

**Issue by WashuHanb** [pwr-Solaar/Solaar#379]
I don't get Solaar in Top Panel or System tray in Manjaro - Gmome.

Looking the respositories I didn't find SOLAAR.  In AUR  found solaar 0.9.2 and solaar-git r934.684afa8-1.  Both don't show up in the GNOME3  desktop in the Top Panel or System Tray.

I would think that because its not a "solaar-gnome3"  version.   Can "Solaar-Gnome3" be ported to the AUR so it work with Manjaro and Arch running the Gnome3 Desktop?

**Comment by Lekensteyn** [comment]
Can you try with solaar-git? Maybe due to recent changes it works again. maybe also related: #223

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
