### ISSUE TITLE
Logitech M238: Logitech receiver not found

### ISSUE THREAD

**Issue by yermulnik** [pwr-Solaar/Solaar#394]
I've bought Logitech M238 which I guess should be almost similar to M235 which I used to use before, but solaar can't determine its receiver:
```
$> solaar-cli -V
solaar-cli 0.9.2
$> solaar-cli show
solaar-cli: error: Logitech receiver not found
$> lsusb -d 046d:
Bus 003 Device 024: ID 046d:c534 Logitech, Inc. Unifying Receiver
```
Solaar is installed from `ppa:daniel.pavel/solaar`.
How can I manage to connect this receiver with solaar?

**Comment by jrbenito** [comment]
Hi @yermulnik 

First, please, try run the latest code in this repo master branch. Version 0.9.2 is too old. 

thanks

**Comment by yermulnik** [comment]
It works with latest code from repo master branch.
Thanks.

**Comment by yermulnik** [comment]
Though doesn't report battery status on this mice model =(
```Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c534
  Serial       : 0
    Firmware   : 29.01.B0016
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)

  2: Wireless Mouse M185 new
     Codename     : M185n
     Kind         : mouse
     Wireless PID : 4054
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 00000000
          Firmware: RQM 64.00.B0008
     The power switch is located on the base.
     Supports 20 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: RESET                  {0020}   
         5: REPROG CONTROLS V4     {1B04}   
         6: WIRELESS DEVICE STATUS {1D4B}   
         7: LOWRES WHEEL           {2130}   
         8: POINTER SPEED          {2205}   
         9: unknown:1802           {1802}   internal, hidden
        10: unknown:1810           {1810}   internal, hidden
        11: unknown:1830           {1830}   internal, hidden
        12: unknown:1850           {1850}   internal, hidden
        13: unknown:1869           {1869}   internal, hidden
        14: unknown:1890           {1890}   internal, hidden
        15: unknown:18B1           {18B1}   internal, hidden
        16: unknown:1DF3           {1DF3}   internal, hidden
        17: unknown:1E00           {1E00}   hidden
        18: unknown:1F03           {1F03}   internal, hidden
        19: unknown:1E80           {1E80}   internal, hidden
     Has 3 reprogrammable keys:
         0: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
             mse, reprogrammable, pos:0, group:1, gmask:1
         1: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
             mse, reprogrammable, pos:0, group:1, gmask:1
         2: MIDDLE BUTTON             , default: MiddleMouseButton           => MIDDLE BUTTON             
             divertable, mse, reprogrammable, pos:0, group:2, gmask:3
     Battery status unavailable.

```

**Comment by doctor64** [comment]
@yermulnik Looks like this mouse have same ID as M185 (new version) and does not support reporting battery level. Please, can you verify this using windows logitech software?

**Comment by yermulnik** [comment]
Unfortunately, I don't have windows workstation at the moment =(

**Comment by frsauvage** [comment]
Exactly same problem ! Any suggestion  ??

**Comment by brothermechanic** [comment]
solaar-cli: error: Logitech receiver not found on 0.9.2
solaar: error: Logitech receiver not found on git build

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by drmclean** [comment]
For the possible benefit of others:

The Ubuntu Software Centre will install Solaar 0.9.3
```
drmclean:~$ solaar -V
solaar 0.9.2
```

Installing from the github gets you the latest version _but_ I also found that Solaar cannot find the USB receivers unless it is running as root:

```
drmclean:git$ Solaar/bin/solaar -V
solaar 1.0.3

drmclean:git$ Solaar/bin/solaar show
Solaar: error: [Errno 13] Permission denied: '/dev/hidraw2'

drmclean:git$ sudo Solaar/bin/solaar show
Nano Receiver
  Device path  : /dev/hidraw2
  USB id       : 046d:c534
  Serial       : None
    Firmware   : 29.01.B0016
  Has 2 paired device(s) out of a maximum of 2.
  Has 18 successful pairing(s) remaining.
  Notifications: (none)

  1: Wireless Keyboard MK270
     Codename     : MK270
     Kind         : keyboard
     Wireless PID : 4023
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: 00000000
     Battery: unknown (device is offline).

  2: Wireless Mouse M185 new
     Codename     : M185n
     Kind         : mouse
     Wireless PID : 4054
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 00000000
     The power switch is located on the base.
     Battery: unknown (device is offline).
```

This is pretty obvious if you're running from the command line as above, but a lot less obvious if you're running the GUI, which will run as non-root but just won't find anything and won't tell you why.

`drmclean:git$ Solaar/bin/solaar`
![image](https://user-images.githubusercontent.com/8614203/89769752-9df2d000-daf5-11ea-9a4d-81f5f8634313.png)

`drmclean:git$ sudo Solaar/bin/solaar`
![image](https://user-images.githubusercontent.com/8614203/89769692-7ef43e00-daf5-11ea-89af-4d57aa4f9269.png)

Don't know if this is a quirk of my setup or a reproducible issue. 

Once I ran Solaar v1.0.3  as root everything worked very smoothly.

**Comment by pfps** [comment]
When installing Solaar from this repository or via PyPI you need to install Solaar's udev rule.   This is documented in https://pwr-solaar.github.io/Solaar/installation
