### ISSUE TITLE
Back-light settings/timeouts for k830 and k800

### ISSUE THREAD

**Issue by scottfree1** [pwr-Solaar/Solaar#395]
I'd like my k830 to:

First, always use the brightest back-light setting (I've tried put tape over the light sensor but pressing the light  key over rides it, I'd light the light key to just toggle brightest setting on/off)

Second, increase the back-light time out, ideally at least 30 sec. when unplugged and 30min. when =plugged in..

Third, I'd like be able toggle on/off the left click on the top corner, and the touchpad, both are good for more accidental inputs than intentional, and I use this with a g700s mouse so I couls do without mouse functionality all together..

Lastly, I assume using this from a live cd is no problem, but do the the changes commit to the keyboard and persist across various Os's or are they stored in an external file??

Thanks..

**Comment by decibyte** [comment]
Are these requested features something that's available in the official software from Logitech? Especially the control of the backlight timer sound to me like something that might not be possible due to lack of support for it in the hardware, but I might be wrong.

**Comment by t541hoo** [comment]
Putting tape over your sensor puts the backlight to dimmed instead of the by you desired bright. You better glue a permanent lit led to the sensor or bridge it internally with an adequate resistor

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original poster.

**Comment by peter-kehl** [comment]
Yes, setting a light timeout is a Logitech-supported feature: https://support.logi.com/hc/en-us/articles/360023396093-Customizing-my-K800-keyboard-with-Logitech-SetPoint-Software.

**Comment by pfps** [comment]
For Solaar to support this feature, we'll need the output of `solaar show` for the keyboard to see what interfaces the keyboard supports.

**Comment by peter-kehl** [comment]
FYI: SetPoint is older software from Logitech. "Options" is supposedly newer:
- https://support.logi.com/hc/en-sg/articles/360025141274-SetPoint for Windows 10/11 6.70.55 Last Update: 2021-02-01
- https://support.logi.com/hc/en-us/articles/360025297893 for Windows 10  9.40.86 Last Update: 2021-09-28
Both are self-extracting EXE's. If you open them (from Firefox) on (Manjaro) Linux, it opens them in an archive extractor app.

However, neither runs with WINE, nor with Phoenicis/PlayOnLinux (out of the box as they come for current Manjaro 5.16.0-1). Two other people reported that they couldn't run SetPoint in WINE (years ago). So you most likely need to test with Windows.

**Comment by pfps** [comment]
The Logitech software includes Windows low-level drivers and is thus likely not to run on Linux without a lot of work.

The way to start to get backlight working for K830 under Solaar is for someone with the keyboard to install a recent version of Solaar, ideally the one in this repository, and run `solaar show`.

**Comment by peter-kehl** [comment]
From GIT master. (I have it paired with two K800 keyboards, one at my girlfriend's house).
```
Solaar version 1.1.1

Unifying Receiver
  Device path  : /dev/hidraw2
  USB id       : 046d:C52B
  Serial       : 90479C9A
    Firmware   : 12.11.B0032
    Bootloader : 04.16
    Other      : AA.AA
  Has 3 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 3=235, 4=120

  2: Wireless Illuminated Keyboard K800 new
     Device path  : /dev/hidraw3
     WPID         : 406E
     Codename     : K800 new
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Polling rate : 20 ms (50Hz)
     Serial number: 313FBE10
     The power switch is located on the top right corner.
     Battery: unknown (device is offline).

  3: Wireless Illuminated Keyboard K800 new
     Device path  : /dev/hidraw4
     WPID         : 406E
     Codename     : K800 new
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Polling rate : 20 ms (50Hz)
     Serial number: 55BC980D
     Model ID:      406E00000000
     Unit ID:       0EB87B3B
        Bootloader: BOT 60.00.B0002
          Firmware: RQK 68.01.B0009
     The power switch is located on the top right corner.
     Supports 25 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 60.00.B0002 406ED4E7454501
            Firmware: Firmware RQK 68.01.B0009 406ED4E7454501
            Unit ID: 0EB87B3B  Model ID: 406E00000000  Transport IDs: {'wpid': '406E'}
         3: DEVICE NAME            {0005}   
            Name: Wireless Illuminated Keyboard K800
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
            Battery: 50%, discharging, next level 20%.
         7: BACKLIGHT3             {1983}   
         8: REPROG CONTROLS V4     {1B04}   
            Key/Button Diversion (saved): {'1': 0, '10': 0, '14': 0, '2': 0, '226': 0, '227': 0, '3': 0, '34': 0, '4': 0, '40': 0, '5': 0, '6': 0, '62': 0, '64': 0, '8': 0}
            Key/Button Diversion        : {'34': 0, '14': 0, '62': 0, '8': 0, '226': 0, '227': 0, '64': 0, '40': 0, '6': 0, '4': 0, '5': 0, '1': 0, '2': 0, '3': 0, '10': 0}
         9: FN INVERSION           {40A0}   
            Swap Fx function (saved): False
            Swap Fx function        : False
        10: ENCRYPTION             {4100}   
        11: KEYBOARD DISABLE KEYS  {4521}   
            Disable keys (saved): {'1': False, '16': False, '2': False, '4': False, '8': False}
            Disable keys        : {'1': False, '2': False, '4': False, '8': False, '16': False}
        12: DFUCONTROL SIGNED      {00C2}   
        13: unknown:1803           {1803}   internal, hidden
        14: CONFIG DEVICE PROPS    {1806}   internal, hidden
        15: unknown:1811           {1811}   internal, hidden
        16: unknown:1830           {1830}   internal, hidden
        17: unknown:1890           {1890}   internal, hidden
        18: unknown:18A1           {18A1}   internal, hidden
        19: unknown:1DF3           {1DF3}   internal, hidden
        20: unknown:1E00           {1E00}   hidden
        21: unknown:1EB0           {1EB0}   internal, hidden
        22: unknown:1861           {1861}   internal, hidden
        23: unknown:1A20           {1A20}   internal, hidden
        24: unknown:18B0           {18B0}   internal, hidden
     Has 15 reprogrammable keys:
         0: My Home                   , default: HomePage                    => HomePage                  
             is FN, FN sensitive, reprogrammable, divertable, pos:1, group:0, group mask:empty
             reporting: default
         1: Mail                      , default: Email                       => Email                     
             is FN, FN sensitive, reprogrammable, divertable, pos:2, group:0, group mask:empty
             reporting: default
         2: Search                    , default: Search Files                => Search Files              
             is FN, FN sensitive, reprogrammable, divertable, pos:3, group:0, group mask:empty
             reporting: default
         3: Application Switcher      , default: Application Switcher        => Application Switcher      
             is FN, FN sensitive, reprogrammable, divertable, pos:4, group:0, group mask:empty
             reporting: default
         4: Backlight Down            , default: Backlight Down              => Backlight Down            
             is FN, FN sensitive, divertable, pos:5, group:0, group mask:empty
             reporting: default
         5: Backlight Up              , default: Backlight Up                => Backlight Up              
             is FN, FN sensitive, divertable, pos:6, group:0, group mask:empty
             reporting: default
         6: Sleep                     , default: Sleep                       => Sleep                     
             is FN, FN sensitive, reprogrammable, divertable, pos:8, group:0, group mask:empty
             reporting: default
         7: Media Player              , default: Music                       => Music                     
             is FN, FN sensitive, reprogrammable, divertable, pos:9, group:0, group mask:empty
             reporting: default
         8: Previous                  , default: Previous                    => Previous                  
             is FN, FN sensitive, divertable, pos:10, group:0, group mask:empty
             reporting: default
         9: Play/Pause                , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, divertable, pos:11, group:0, group mask:empty
             reporting: default
        10: Next                      , default: Next                        => Next                      
             is FN, FN sensitive, divertable, pos:12, group:0, group mask:empty
             reporting: default
        11: Volume Up                 , default: Volume Up                   => Volume Up                 
             nonstandard, divertable, pos:0, group:0, group mask:empty
             reporting: default
        12: Volume Down               , default: Volume Down                 => Volume Down               
             nonstandard, divertable, pos:0, group:0, group mask:empty
             reporting: default
        13: Mute                      , default: Mute                        => Mute                      
             nonstandard, divertable, pos:0, group:0, group mask:empty
             reporting: default
        14: Calculator                , default: Calculator                  => Calculator                
             nonstandard, reprogrammable, divertable, pos:0, group:0, group mask:empty
             reporting: default
     Battery: 50%, discharging, next level 20%.

  4: Wireless Mouse M325
  ...
```

**Comment by pfps** [comment]
Thanks.   I'll try to find documentation of the feature BACKLIGHT3  {1983}.

**Comment by Ayoitswiz** [comment]
You guys think it would be possible to use something like AutoHotKey, or Java, or Python to write a script to press a key at a set interval? Or even a touch of the touchpad to keep the backlight on or prevent the kb from sleeping?

**Comment by pfps** [comment]
@peter-kehl PR #1476 should add the ability to set a timeout for the backlight on keyboards with the BACKLIGHT3 feature.  Please try it out.   You will need to kill any running instances of Solaar.  Then run Solaar as `bin/solaar -ddd` and start it up and then try to change the time for the backlight setting.  If there are any problems post the output you get from Solaar here.  This is untested code, and Solaar now keeps track of settings that caused problems so if there is a bug in the code then the next time Solaar runs it won't even try the setting.


To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1476, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1476/head:pull_1476
git checkout pull_1476
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_1476
git fetch origin pull/1476/head
git reset --hard FETCH_HEAD
```

**Comment by Free-Rider1** [comment]
Vous voulez la solution gratuite et sans prise de tête ? ça concerne uniquement pour le maintient du rétroéclairage
je pense que le sujet est trop vieux
