### ISSUE TITLE
Solaar Cli Show crashes

### ISSUE THREAD

**Issue by EliasKotlyar** [pwr-Solaar/Solaar#396]
eko@eko-GE62VR-6RF:~$ solaar-cli  show 
Traceback (most recent call last):
  File "/usr/bin/solaar-cli", line 42, in <module>
    solaar.cli.main()
  File "/usr/share/solaar/lib/solaar/cli.py", line 430, in main
    receiver = _receiver(args.hidraw_path)
  File "/usr/share/solaar/lib/solaar/cli.py", line 53, in _receiver
    for dev_info in receivers():
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 86, in receivers
    for d in _hid.enumerate(*receiver_usb_id):
  File "/usr/share/solaar/lib/hidapi/udev.py", line 199, in enumerate
    dev_info = _match('add', dev, vendor_id, product_id, interface_number, hid_driver)
  File "/usr/share/solaar/lib/hidapi/udev.py", line 87, in _match
    if not ((vendor_id is None or vendor_id == int(vid, 16)) and
TypeError: int() can't convert non-string with explicit base

**Comment by jasontibbitts** [comment]
More information with a more recent git checkout was recently submitted as  https://bugzilla.redhat.com/show_bug.cgi?id=1630395

**Comment by mattfellenz** [comment]
Getting the same error.

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
