### ISSUE TITLE
M570 and MX Ergo documentation updates

### ISSUE THREAD

**Issue by khaytsus** [pwr-Solaar/Solaar#397]
Hey, I wanted to let you know that the MX Ergo seems to work just fine with Solaar.  It shows the battery and link (encrypted).  I don't see any settings available, but that's okay.  I don't know if there's anything that can be adjusted via the computer anyway, but I don't use Windows so not sure.

Also, the M570 in the documentation is there but blank..  It also reads the battery percent and link (not encrypted :( ) but I haven't tried any settings etc on it.

If there's any more info I can provide let me know!

**Comment by AodaliyaRen** [comment]
Regarding MX Ergo , there's something peculiar going on : when the device is being charged, the percentage shown doesn't go higher than 90% even when the LED becomes steady green (meaning fully charged) . Then after a while MX Ergo's "battery status" in Solaar changes to "unknown" : 
![screenshot at 2018-01-12 00-11-27](https://user-images.githubusercontent.com/35336609/34827536-a6212324-f72e-11e7-8258-321a6096e9d2.png)
Switching the trackball off and on again shows the LED steady green (fully charged) but Solaar indicator remains "unknown" . Strange...

**Comment by khaytsus** [comment]
Yep, charging is unknown, full is 90, then 50, then 20.  I don't know if this is a Solaar issue or the device reporting.

**Comment by doctor64** [comment]
@khaytsus Please, can you provide some information?
Did you use latest version from git?
Can you provide logs of solaar -dd show with different charge level, especially when battery status is unknown?

**Comment by khaytsus** [comment]
@doctor64 I'm using 0.9.2, I offhand don't see anything in git that would change this but I'll be happy to build it if that's needed.

Attaching logs of unplugged (at 50%) and plugged.
[plugged.txt](https://github.com/pwr/Solaar/files/1623786/plugged.txt)
[unplugged.txt](https://github.com/pwr/Solaar/files/1623787/unplugged.txt)

**Comment by khaytsus** [comment]
@doctor64 I went ahead and rebuilt the RPM for Fedora and installed it, so it's the latest git.  Same output as far as I can tell, but does look like you're detecting more things than the older version that was in Fedora (20150528gitcf27328)

[plugged.txt](https://github.com/pwr/Solaar/files/1624067/plugged.txt)
[unplugged.txt](https://github.com/pwr/Solaar/files/1624068/unplugged.txt)

**Comment by cement-head** [comment]
Where is the RPM?  I'll try making a *.deb using alien for Ubuntu 16.04.

Or rather how does one make a deb from git?

**Comment by khaytsus** [comment]
@cement-head there is a debian build script in the github repo under packaging, but I don't have any debian based systems so I haven't tried it.  Probably better than alien'ing my rpm; I know what terrible things alien does deb->rpm ;)

**Comment by cement-head** [comment]
The debian script doesn't work

**Comment by doctor64** [comment]
@khaytsus Thank you. Unfortunately, i didn't see anything suspicious in provided logs regarding battery status. 
Can you please make a log then battery status is unknown, like in second comment?

**Comment by doctor64** [comment]
@cement-head Never use debian script. Can you try to just clone from git and use manual installation as described in https://pwr.github.io/Solaar/installation.html ?

**Comment by khaytsus** [comment]
@doctor64 Hmm, maybe it only shows Unknown in the GUI.  It shows 0% in the CLI.  For some reason the GUI isn't working for me, I'm only seeing the Unifying Receiver, it's not showing anything else.  solaar show, however, shows it just fine.  Attaching log file in case you're interested in that.  Sorry, this is becoming a bit of a mudball issue ;)

[gui.txt](https://github.com/pwr/Solaar/files/1624238/gui.txt)

**Comment by doctor64** [comment]
@khaytsus Sorry, i'm fear i can't help here. I'm not a GUI guy and don't like Fedora :)
May be PR #382 can fix this?

**Comment by pfps** [comment]
Is this still a problem with the version of Solaar from this repository?

**Comment by khaytsus** [comment]
> Is this still a problem with the version of Solaar from this repository?

What problem in specific?  This issue was about a few documentation issues, it..  migrated over time ;)

**Comment by pfps** [comment]
Any part - I've been going through old Solaar issues to see if they are still active.

**Comment by khaytsus** [comment]
> Any part - I've been going through old Solaar issues to see if they are still active.

Gotcha!  The documentation as originally logged looks okay, the devices were added to the table. 

I think the battery percent values should be logged as a separate issue, if they are in fact an issue.  Solaar does still show "unknown" while the device is charging.

And another separate issue really, I still don't see my MX Ergo in the Solaar GUI.  It shows up fine in solaar show, which is what I use to script to alert me of low battery etc, but not sure why the GUI doesn't show it.  

So if you like, we can close this one and I could optionally open two new ones ;)

**Comment by pfps** [comment]
Let's go that way, so that each problem has its own issue.
For the charging issue, provide output from `solaar show`.
For the the not-showing-in-gui issue, provide output from `solaar -dd`.
Thanks.

**Comment by khaytsus** [comment]
> Let's go that way, so that each problem has its own issue.
> For the charging issue, provide output from `solaar show`.
> For the the not-showing-in-gui issue, provide output from `solaar -dd`.
> Thanks.

Will do, thank you for the help!
