### ISSUE TITLE
package for Ubuntu Artful

### ISSUE THREAD

**Issue by ghost** [pwr-Solaar/Solaar#400]
Hi, 
Is it possible to update [your ppa](https://launchpad.net/~daniel.pavel/+archive/ubuntu/solaar) to provide a package for Ubuntu Artful?
Thanks in advance.

**Comment by pfps** [comment]
Is this still a problem?

**Comment by Klap-in** [comment]
See https://github.com/pwr-Solaar/Solaar#pre-built-packages for different ppa’s that are available at the moment. Or depending on your Ubuntu version you can also use the universe repository for a quite recent version of solaar.
