### ISSUE TITLE
Start on KDE Neon (unplug & plug)

### ISSUE THREAD

**Issue by jolugaju** [pwr-Solaar/Solaar#401]
My System: KDE Neon 5.11.3
My keyboard: Logitech K800
My mouse: Logitech M235
Every time I start my system I have to unplug and plug again the USB receiver. Only then it works.
I have tried to install Solaar from KDE Discover, from Bash (repository and tar.gz v0.9.2).
I have tried to install Solaar after install git and download everything with git clone ...
Nothing seems to work.
Any idea?
Some important things ... I know very little about Linux, my English is not very good, I've looked for solutions and I have found nothing useful ... or nothing I've understood.
Thanks in advance!!

**Comment by jolugaju** [comment]
It seems the main problem is my dual boot configuration.
Unifying always works in Windows and always fails in Linux if the last session was Windows.
The Logitech driver in Windows does something that Solaar doesn't "like" in Linux.

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md
