### ISSUE TITLE
usage on a raspberry pi

### ISSUE THREAD

**Issue by nex86** [pwr-Solaar/Solaar#402]
I'm planning to use this on a raspberry pi because I want to built the receiver into a closed case along with the pi, 
does this work flawlessly? .deb can be installed for raspbian?
I'm completely new to compiling stuff myself, this is why I ask.

**Comment by pfps** [comment]
I haven't tried solaar on a PI.  If you still want to use solaar on a Pi, let me know and I'll see if I can get it to work on my Pi.

**Comment by pfps** [comment]
Closing due to no response from original poster.
