### ISSUE TITLE
Logitech K400+ - no Fn switch

### ISSUE THREAD

**Issue by positron96** [pwr-Solaar/Solaar#404]
![screenshot_2017-05-17_23-10-05](https://user-images.githubusercontent.com/2095278/33524614-ba49641a-d852-11e7-95cf-d951c50dd88a.png)

The screenshot shows that there is no Fn switching for Logitech K400+ keyboard+touchpad. Is it supported?

**Comment by AlexYeCu** [comment]
Confirming this.
There is an issue 282 with the advise to use master, but that'll be nice to watch this fix in binary packages too.

**Comment by cement-head** [comment]
When & where are binaries being made available?

**Comment by AlexYeCu** [comment]
>When & where are binaries being made available?

Deb repo. deb package for Raspbian, v. 0.9.2.

**Comment by cement-head** [comment]
Thanks!  Is there an UBUNTU repo?  I know/see that the PPA for UBUNTU hasn't been updated for a while: https://launchpad.net/~daniel.pavel/+archive/ubuntu/solaar

**Comment by augcampos** [comment]
No PPA for Ubuntu 17.10 (artful)

**Comment by AlexYeCu** [comment]
Hm, looks like 0.9.2 is the latest version, and version from master works the same way: no fn switching at k400+ keyboard.

**Comment by positron96** [comment]
I installed from official ubuntu repos (for 16.04), is there a possibility that it will be updted to latest version?

**Comment by wisedevman** [comment]
I'm interested in fn switching for k400+ on ubuntu. It will came?

**Comment by rijnhard** [comment]
since Ubuntu 18.04 is out it would be nice to get an update on the ppa.

**Comment by cement-head** [comment]
I don't think that PPA has been updated since Trusty (14.04).  I usually build from GitHub myself and then pin the package so that the repos don't upgrade/overwrite it.

**Comment by scorbin** [comment]
scorbin@xps7:/etc/udev/rules.d$ solaar-cli show -v
Unifying Receiver
   Device path  : /dev/hidraw34
   USB id       : 046d:c52b
   Serial       : A49893AF
     Firmware   : 24.07.B0030
     Bootloader : 02.09
     Other      : AA.AC
   Has 1 paired device(s) out of a maximum of 6 .
   Notifications: 0x000100 = wireless
   Device activity counters: 1=43

1: Wireless Touch Keyboard K400 Plus
   Codename     : K400 Plus
   Kind         : keyboard
   Wireless PID : 404D
   Protocol     : HID++ 4.1
   Polling rate : 8 ms
   Serial number: 9A5D512E
      Bootloader: BOT 22.02.B0002
        Firmware: RQK 63.02.B0016
           Other: 
   The power switch is located on the top edge.
   Supports 24 HID++ 2.0 features:
       0: ROOT                   {0000}   
       1: FEATURE SET            {0001}   
       2: DEVICE FW VERSION      {0003}   
       3: DEVICE NAME            {0005}   
       4: WIRELESS DEVICE STATUS {1D4B}   
       5: unknown:0020           {0020}   
       6: BATTERY STATUS         {1000}   
       7: unknown:1B04           {1B04}   
       8: unknown:2005           {2005}   
       9: NEW FN INVERSION       {40A2}   
      10: ENCRYPTION             {4100}   
      11: unknown:4521           {4521}   
      12: TOUCHPAD RAW XY        {6100}   
      13: unknown:6501           {6501}   
      14: unknown:00C1           {00C1}   
      15: unknown:1811           {1811}   internal, hidden
      16: unknown:1830           {1830}   internal, hidden
      17: unknown:1890           {1890}   internal, hidden
      18: unknown:1DF3           {1DF3}   internal, hidden
      19: unknown:1E00           {1E00}   hidden
      20: unknown:1EB0           {1EB0}   internal, hidden
      21: unknown:1861           {1861}   internal, hidden
      22: unknown:18B0           {18B0}   internal, hidden
      23: unknown:1F11           {1F11}   internal, hidden
   Battery status unavailable.

**Comment by scorbin** [comment]
Is there a way to set this   9: NEW FN INVERSION       {40A2}

**Comment by rijnhard** [comment]
@scorbin I took a peak at the code and it looks like it is handled correctly, 40A2 is specifically handled.
So I'm not sure why it doesn't work.

**Comment by cll0ud** [comment]
Any updates on this?

**Comment by pfps** [comment]
The version of solaar in this repository works for me on my K400+

> bin/solaar config 1
Wireless Touch Keyboard K400 Plus (K400 Plus) [404D:132A9261]

# Swap Fx function
# When set, the F1..F12 keys will activate their special function, and you must hold the FN key to activate their standard function.  When unset, the F1..F12 keys will activate their standard function, and you must hold the FN key to activate their special function.
#   possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
fn-swap = False

If you try the current version and it doesn't work for you, please reopen this issue.
