### ISSUE TITLE
Why is the keyboard display as offline when it is on?

### ISSUE THREAD

**Issue by JulianLai** [pwr-Solaar/Solaar#405]
![deepin _20171207150100](https://user-images.githubusercontent.com/20014762/33702646-83f5b16a-db5f-11e7-97f8-ae091a57cf73.png)

**Comment by ckol** [comment]
Same here with the MK700 Keyboard. Screenshot attached:
![solaar-0 9 2-bug_mk700_keyboard_always_inactive](https://user-images.githubusercontent.com/12452042/36302594-489e5306-1309-11e8-96d5-4a2a73f9e780.png)

**Comment by pfps** [comment]
Have the  merged changes fixed your  problem?

**Comment by pfps** [comment]
Closing due to no response from original poster.
