### ISSUE TITLE
[Feature request] allow to work without udev, maybe by manually specifing hidraw device

### ISSUE THREAD

**Issue by slashbeast** [pwr-Solaar/Solaar#417]
Right now it's impossible to use Solaar without udev.

the `ltunify` for example poke the hidraw devices to find reciever, perhaps adding such logic, or letting user choose the device would be a solution here? Right now it just stacktrace on me

```
# solaar-cli --debug show
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.5/solaar-cli", line 42, in <module>
    solaar.cli.main()
  File "/usr/lib64/python3.5/site-packages/solaar/cli.py", line 430, in main
    receiver = _receiver(args.hidraw_path)
  File "/usr/lib64/python3.5/site-packages/solaar/cli.py", line 53, in _receiver
    for dev_info in receivers():
  File "/usr/lib64/python3.5/site-packages/logitech_receiver/base.py", line 86, in receivers
    for d in _hid.enumerate(*receiver_usb_id):
  File "/usr/lib64/python3.5/site-packages/hidapi/udev.py", line 199, in enumerate
    dev_info = _match('add', dev, vendor_id, product_id, interface_number, hid_driver)
  File "/usr/lib64/python3.5/site-packages/hidapi/udev.py", line 87, in _match
    if not ((vendor_id is None or vendor_id == int(vid, 16)) and
TypeError: int() can't convert non-string with explicit base
```

**Comment by Lekensteyn** [comment]
What system are you using that does not have a proper udev setup?

**Comment by slashbeast** [comment]
A Gentoo system that I removed udev from and replaced with simple device nodes handling via busybox's mdev. Udev since merging with systemd is a pain to be around, unless you do run systemd, which I do on none of my systems.

**Comment by slashbeast** [comment]
eudev is udev implementation so all it's interfaces are preserved.

**Comment by pfps** [comment]
Solaar uses udev to set up an access control list for the receiver's hidraw file entry that lets the seated user read from and write to it.  I think other ways of doing this would require super-user privileges for Solaar.  I'm closing this issue as out of scope.  If you have a method of setting up the required permissions that works generally feel free to re-open this issue and provide details on the method.

**Comment by FFY00** [comment]
The issue is not permissions, but rather not being able to find the path of the device. But I consider this out of scope for now.

**Comment by WhyNotHugo** [comment]
> Solaar uses udev to set up an access control list for the receiver's hidraw file entry that lets the seated user read from and write to it.

This is perfectly doable without udev. I.e.: you can configure mdev or mdevd to recognise Logitech devices and change their ownership to the `plugdev` group, much like to 42-logitech-unify-permissions.rules.

The documentation is here https://git.busybox.net/busybox/plain/docs/mdev.txt (mdevd uses the same configuration format as mdev).

Once permissions are updated, solaar works fine.

**Comment by pfps** [comment]
Solaar's udev rule doesn't set up permissions for plugdev, as that mechanism is not recommended.

**Comment by WhyNotHugo** [comment]
Right, I see that the `plugdev` part is commented upstream and patched to be uncommented downstream on Alpine. Alpine doesn't use systemd, so doesn't rely on udev tags + acl for device access.

That doesn't make any practical difference and my point still stands: you can use mdev/mdevd to assign to `plugdev`, apply ACL rules, or any other mechanism that you like.

**Comment by pfps** [comment]
Solaar uses udev.  If Alpine doesn't then the Solaar distribution there should use something that works there.

**Comment by WhyNotHugo** [comment]
Sorry, I don’t understand what you’re trying to say.

**Comment by pfps** [comment]
It is up to the people who create distributions for Solaar to make sure that what they do works.  Solaar needs to have permissions on hidraw nodes for Logitech devices.  The udev rule is supplied as a way to do that.  If Alpine can't use this then someone has to set up Solaar to work on Alpine.
