### ISSUE TITLE
solaar (CLI) doesn't persist settings on K400+

### ISSUE THREAD

**Issue by rhester72** [pwr-Solaar/Solaar#418]
If I use solaar from master to toggle the Fn state on my K400+, it works, up until keyboard inactivity causes the keyboard to sleep - and once I wake it with a keypress, the setting is lost until I manually re-run solaar to set it again.

Is there any way to have solaar run in some sort of daemon mode where it will do this automatically, short of cronning it (and likely causing it to never sleep, which would 'fix' the problem at the expense of much-reduced battery life)?

**Comment by pfps** [comment]
PR #452 should have fixed this problem.  To check, use the version of Solaar in this repository.  If your problem is still active, let us know.

**Comment by pfps** [comment]
Closing due to no response from original poster.
