### ISSUE TITLE
Support for custom thumb wheel actions

### ISSUE THREAD

**Issue by abmantis** [pwr-Solaar/Solaar#422]
It would be great if we could map the thumb wheel events to actions, like on Windows. I would love to have the thumb wheel set to changing tabs, since I never use horizontal scrolling.

**Comment by pfps** [comment]
This may have something to do with reporting thumb wheel actions via HID++, which is not part of Linux, AFAIK.

**Comment by pfps** [comment]
Closing due to no response from submitter.

**Comment by abmantis** [comment]
@pfps I didn't knew that you were waiting for a response, since there was no question. What do you need from me?
By the way, the whell currently works for horizontal scrolling.

**Comment by pfps** [comment]
Oops, a bit of miscommunication.
What version of Solaar are you running (`solaar --version`) and what device do you have (`solaar show`)?
What happens on Windows that Solaar doesn't do?

**Comment by abmantis** [comment]
Sorry, I currently don't have the unifying dongle with me so I'm using bluetooth.

Anyway, on windows I can set a custom action (like a keyboard shortcut) for each side of the thumb scroll wheel. In linux, it simply works forhorizontal scrolling.
The mouse is a MX Master 2S.

**Comment by pfps** [comment]
I'm pretty sure that this is done using an input layer, i.e., not something that Solaar is set up to do.

**Comment by FFY00** [comment]
Yes, this does not belong in Solaar unless you want to remap the physical keys, and for that the hardware needs to support it.

**Comment by abmantis** [comment]
Right. You're right. Closing this then.

**Comment by AnkushMalaker** [comment]
@abmantis  Old issue, but this is (SORT OF) possible to do on MX Master 3 if we enable Thumb Wheel Diversion followed by a "thumb_wheel_up" test, followed by `control_l + Tab` key press. The same for thumb_wheel_down and control shift tab. 

The SPEED at which the tabs change is too much, and for that we need either some delay between key press or reducing scroll [speed](https://github.com/pwr-Solaar/Solaar/issues/411). 
Could you give me some direction on how either of those are possible or if it even is possible via solaar @pfps ? 
Thanks for the awesome utility.

**Comment by pfps** [comment]
I don't think that what you want is doable directly in Solaar as the rules are 1-1 with thumb wheel reports.  You would have to write a helper program that would total up the thumb wheel movements and emit the key press at suitable times.

**Comment by a1ad** [comment]
@AnkushMalaker did you ever find a solution? I have the same question.

**Comment by ringc95** [comment]
Not sure if this counts as 'custom' but can the thumb wheel be used for volume adjustment?

**Comment by pfps** [comment]
You can write a Solaar rule that responds to diverted thumb wheel movements and simulates volume up and down keystrokes.  It's not a great solution, though.
