### ISSUE TITLE
Upgrading Ubuntu installation to the latest release

### ISSUE THREAD

**Issue by voddan** [pwr-Solaar/Solaar#423]
Hi, I installed the 0.9.2 package with `apt-get install solaar-gnome3`, but it doesn't detect my Logitech MX master 2S.

How do I upgrade to the latest stable version of the app from the repo? I couldn't figure it out from the docs. Please instruct.

**Comment by pfps** [comment]
The documentation in the repo should be better now.  Try cloning the current version and following https://pwr-solaar.github.io/Solaar/installation

**Comment by pfps** [comment]
Closing due to no response from original poster.
