### ISSUE TITLE
PyGIWarning warning on startup

### ISSUE THREAD

**Issue by axel-h** [pwr-Solaar/Solaar#424]
On Mint 18.3 I'm getting these warning on startup. Would be nice if you could set some minimum versio here to avoid them

    /usr/share/solaar/lib/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
      __import__(module)
    /usr/share/solaar/lib/solaar/ui/notify.py:33: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
      from gi.repository import Notify
    /usr/share/solaar/lib/solaar/ui/tray.py:72: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
      from gi.repository import AppIndicator3

**Comment by Poccket** [comment]
This is happening to me on Ubuntu 16.04 after installing solaar-gnome3. Exact same error message and it just idles after that doing absolutely nothing

**Comment by davidmoshal** [comment]
happens on raspberry pi

**Comment by pfps** [comment]
This should not be a problem with the version of Solaar in this repository.  If you are still experiencing this problem with the current version please provide details here.

**Comment by pfps** [comment]
Closing due to no response.
