### ISSUE TITLE
device listing formatting in GUI seem broken

### ISSUE THREAD

**Issue by axel-h** [pwr-Solaar/Solaar#425]
I'm getting this warning sometimes and then some devices are missing in the GUI:

    (solaar:6655): Gtk-WARNING **: Failed to set text '<b>M310' from markup due to error parsing markup: Error on line 1 char 24: Element 'markup' was closed, but the currently open element is 'b'

**Comment by pfps** [comment]
Are you still seeing this warning?

**Comment by pfps** [comment]
Closing due to no response from original poster.
