### ISSUE TITLE
Unplugging receiver as suggested by application causes kernel panic: CemtOS 7

### ISSUE THREAD

**Issue by biofool** [pwr-Solaar/Solaar#426]
```
uname -a
Linux localhost.localdomain 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

Steps to reproduce:
Install CentOS on Dell Laptop
Download https://github.com/pwr/Solaar
run Solaar/bin/solaar
When prompted unplug and replug reciever
Examine frozen display, hit Ctl-C, Ctl-Alt-Del, ESC, Alt-F2-Alt-F7 (nothing happens)
(Hold down the power button for 5 seconds as the system is non responsive).
Attempt to reproduce by runing solaar command line again
Fail to reproduce

**Comment by pfps** [comment]
Is this still a problem?  If so, please try Solaar from this repository.

**Comment by FFY00** [comment]
Either way, Linux 3.10.0 is really old and we don't have the means to support it.

**Comment by pfps** [comment]
Closing due to no response from submitter.
