### ISSUE TITLE
MK270 receiver not recognized - missing udev rule?

### ISSUE THREAD

**Issue by lagerspetz** [pwr-Solaar/Solaar#431]
I have a Logitech MK270 keyboard + mouse, and they don't show up in Solaar. I installed the current master (built a deb package for Ubuntu then installed it) to check.
The usb id is: `046d:c534` exactly as in the PR for MK270. However, Solaar complains about no access to the hidraw device that was inserted, and asks me to remove and plug it in again, which doesn't help. I added this to the udev rules file:
```
# MK270
ATTRS{idVendor}=="046d", ATTRS{idProduct}=="c534", GOTO="solaar_apply"
```
And now it shows up in solaar as a "unifying receiver" which I am not sure is correct, but at least it shows up.

I would like to know what I can do with Solaar and this receiver. 
I also have The Anywhere mouse MX with receiver `046d:c52b`, I would like to cross-connect the keyboard from MK270 with that mouse if it's possible, but I'm not able to to that at the moment in Solaar (device / receiver not compatible ). I also cannot change any settings on the keyboard or mouse.

**Comment by pfps** [comment]
The c534 is not currently handled completely correctly.  It is a Nano receiver and you can only pair some devices with it.  If you are still having some problems with it please try solaar from this repo and describe what is still going wrong.

**Comment by pfps** [comment]
Closing due to no response from reporter.
