### ISSUE TITLE
Solaar is missing FN key status and battery indication after startup

### ISSUE THREAD

**Issue by joe1970** [pwr-Solaar/Solaar#434]
Hi,
I am using Solaar on Ubuntu 18.04, Wayland, Gnome 3. All pretty much a standard installation of Ubuntu.
Solaar is manually installed from master branch and it basically works well with a K830 including FN-Swap and Battery indication.
The issue is, that it works well when I manually start Solaar. If I let the system automatically start Solaar at system start, it seems to recognize the keyboard, but it shows the default icon rather than battery symbol and also the FN-swap does not work. If I quit solaar and start it manually through command line or gnome desktop. All is working well again. So the problem is only happening if I let gnome start it automatically. However the problem persists until I manually quit and restart solaar.
Is there some kind of race condition and gnome tries to start it too early?
If I install solaar from ppa and add the files needed for the K830 support manually, I get the same behavior. 
I have seen this behavior since quite a while. If I remember correctly, it started with Ubuntu 17.10 and the change from Unity to Gnome 3. I see this issue on two different systems and also using X instead of Wayland makes mo difference.

Please advice how I can help solving this.

best regards, Jörg

**Comment by joe1970** [comment]
Hi again,

I tried to delay the automated start of Solaar by letting Gnome autostart execute
bash -c "sleep 20 && solaar &"
This starts solaar long after the desktop has come up, but the problem remains. So it seems to be not just a simple race condition.  

best regards, Jörg

**Comment by arigit** [comment]
did you ever find the fix to this issue?

**Comment by arigit** [comment]
My workaround was to remove solaar's own autostart (/etc/xdg/autostart/solaar.desktop) and then create an autostart desktop file that calls an script after login:



```
#!/bin/bash
sleep 5
solaar &
sleep 1
killall solaar
sleep 1
solaar &
```

This seems to work consistently. Looks like a timing issue when the first launch occurs.

**Comment by joe1970** [comment]
Hi Ari,
No, I did not find the time to look further into this issue. I will try your solution later. Thanks for sharing.
best regards, Jörg

**Comment by joe1970** [comment]
Hi Ari,
I tried your solution yesterday and it seems to work. After a reboot it did start with a little delay but it started with all functionality and since yesterday it is stable. 
Thanks again for sharing the workaround.
best regards, Jörg

**Comment by pfps** [comment]
@joe1970 Is there still a problem here?  If not, please close the issue.

**Comment by pfps** [comment]
Closing due to no response from original poster.
