### ISSUE TITLE
MX Master 2S low in power notification

### ISSUE THREAD

**Issue by AlexWayfer** [pwr-Solaar/Solaar#435]
Hello!

I've received notification about 10% of MX Master 2S mouse power, but in GUI I see 20%.

Something is incorrect.

![image](https://user-images.githubusercontent.com/6510020/40536748-ce144708-6015-11e8-8bc0-6dad7e7612a3.png)

**Comment by DanieLoche** [comment]
Hello,

I have a similar issue : on the right image you send, for me I have on the left pane "20%" but on the right pane (where yours shows a red battery icon), I have 50% ! There's a sync issue around there...

**Comment by sheepdestroyer** [comment]
Same kind of problem here with my MX Master 2S on Fedora 28.
I juste updated solaar today to last commit from git to see if the problem was resolved but still the same. 

Whatever the battery level, it is always reported as 50%, never any other number : 

````
Path         : /dev/hidraw1
USB id       : 046d:c52b
Serial       : 76D29CD5
  Firmware   : 12.07.B0029
  Bootloader : 02.15
  Other      : AA.AA
Notifications: wireless
               software present
````

````
Index        : 1
Wireless PID : 4069
Protocol     : HID++ 4.5
Polling rate : 8 ms (125Hz)
Serial       : 0A1D9739
  Bootloader : BOT 56.00.B0003
  Firmware   : MPM 12.00.B0003
  Firmware   : MPM 12.00.B0003
  Other      : 
````

![image](https://user-images.githubusercontent.com/1377479/44438460-240c6800-a5fa-11e8-8725-aee227c5efe7.png)

**Comment by pfps** [comment]
Is this still a problem?

**Comment by AlexWayfer** [comment]
> Is this still a problem?

My mouse with 50% battery right now, let's wait and check.

**Comment by AlexWayfer** [comment]
Also, I have installed `1.0.1` version. It's newer than this issue report, but there are 40+ commits in `master` after the release. If I should check it on `master` — please, inform.

**Comment by AlexWayfer** [comment]
Also, I have installed `1.0.1` version. It's newer than this issue report, but there are 40+ commits in `master` after the release. If I should check it on `master` — please, inform.

**Comment by pfps** [comment]
It probably wouldn't hurt to use the current (development) version, but if you aren't experiencing any problems there is probably no need to do so.

**Comment by AlexWayfer** [comment]
The same: the notification if from GNOME Settings, and it looks like 10% there, but Solaar detects it like 20%:

![image](https://user-images.githubusercontent.com/6510020/73181345-167cdb00-4128-11ea-9d2e-1f9a51a11e67.png)

**Comment by FFY00** [comment]
Can you post the output of `solaar show`?

**Comment by AlexWayfer** [comment]
> Can you post the output of `solaar show`?

Yep:

```
> solaar show
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 93E690D5
    Firmware   : 24.01.B0023
    Bootloader : 01.08
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=1

  1: Wireless Mouse MX Master 2S
     Codename     : MX Master 2S
     Kind         : mouse
     Wireless PID : 4069
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 2C4E3274
        Bootloader: BOT 56.00.B0003
          Firmware: MPM 12.00.B0003
          Firmware: MPM 12.00.B0003
             Other: 
     The power switch is located on the base.
     Supports 32 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
         7: unknown:1806           {1806}   internal, hidden
         8: CHANGE HOST            {1814}   
         9: REPROG CONTROLS V4     {1B04}   
        10: ADJUSTABLE DPI         {2201}   
        11: VERTICAL SCROLLING     {2100}   
            Roller type: 3G
            Ratchet per turn: 24
            Scroll lines: 0
        12: SMART SHIFT            {2110}   
        13: HIRES WHEEL            {2121}   
            Multiplier: 8
            Has invert
              Normal wheel motion
            Has ratchet switch
              Normal wheel mode
            High resolution mode
            HID notification
        14: GESTURE 2              {6501}   
        15: DFUCONTROL 2           {00C1}   
        16: unknown:00C2           {00C2}   
        17: unknown:1813           {1813}   internal, hidden
        18: unknown:1830           {1830}   internal, hidden
        19: unknown:1890           {1890}   internal, hidden
        20: unknown:1891           {1891}   internal, hidden
        21: unknown:18A1           {18A1}   internal, hidden
        22: unknown:18C0           {18C0}   internal, hidden
        23: unknown:1DF3           {1DF3}   internal, hidden
        24: unknown:1E00           {1E00}   hidden
        25: unknown:1EB0           {1EB0}   internal, hidden
        26: unknown:1803           {1803}   internal, hidden
        27: unknown:1861           {1861}   internal, hidden
        28: unknown:9001           {9001}   internal, hidden
        29: unknown:9200           {9200}   internal, hidden
        30: unknown:9240           {9240}   internal, hidden
        31: unknown:1805           {1805}   internal, hidden
     Has 8 reprogrammable keys:
         0: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
             mse, pos:0, group:1, gmask:1
         1: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
             mse, pos:0, group:1, gmask:1
         2: MIDDLE BUTTON             , default: MiddleMouseButton           => MIDDLE BUTTON             
             mse, reprogrammable, divertable, pos:0, group:3, gmask:7
         3: BACK AS BUTTON 4          , default: BackEx                      => BACK AS BUTTON 4          
             mse, reprogrammable, divertable, pos:0, group:2, gmask:3
         4: FORWARD AS BUTTON 5       , default: BrowserForwardEx            => FORWARD AS BUTTON 5       
             mse, reprogrammable, divertable, pos:0, group:2, gmask:3
         5: unknown:00C3              , default: unknown:00A9                => unknown:00C3              
             mse, reprogrammable, divertable, pos:0, group:3, gmask:7
         6: unknown:00C4              , default: unknown:009D                => unknown:00C4              
             mse, reprogrammable, divertable, pos:0, group:3, gmask:7
         7: unknown:00D7              , default: unknown:00B4                => unknown:00D7              
             divertable, virtual, pos:0, group:4, gmask:0
     Battery: 20%, discharging.
```

Maybe there is some other tool/info for GNOME Settings?

**Comment by FFY00** [comment]
Yes, it should pick up the battery status from upower. I'll look into it.

**Comment by AlexWayfer** [comment]
> Yes, it should pick up the battery status from upower. I'll look into it.

If it can help:

```
> upower -d
Device: /org/freedesktop/UPower/devices/mouse_hidpp_battery_0
  native-path:          hidpp_battery_0
  model:                Wireless Mouse MX Master 2S
  serial:               4069-2c-4e-32-74
  power supply:         no
  updated:              Mon 27 Jan 2020 17:24:50 MSK (30 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       low
    battery-level:       low
    percentage:          10% (should be ignored)
    icon-name:          'battery-caution-symbolic'

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         no
  updated:              Mon 27 Jan 2020 12:32:47 MSK (17553 seconds ago)
  has history:          no
  has statistics:       no
  unknown
    warning-level:       none
    icon-name:          'battery-missing-symbolic'

Daemon:
  daemon-version:  0.99.11
  on-battery:      no
  lid-is-closed:   no
  lid-is-present:  no
  critical-action: PowerOff
``

**Comment by AlexWayfer** [comment]
Maybe related: mouse is fully charged (3 non-blinking indicators of 3), there is 100% in System Settings and 90% somewhy in Solaar:

![image](https://user-images.githubusercontent.com/6510020/73656906-29505c00-46a2-11ea-84e5-7b8e43239626.png)

**Comment by pfps** [comment]
Solaar generally only parrots the information it receives from the mouse, which can be inaccurate or granular.  It looks as if here the mouse is reporting 90%.   
To check try `solaar show` and see what is reported for Battery.

**Comment by AlexWayfer** [comment]
I personally don't have MX Master mouse anymore, sorry.

**Comment by pfps** [comment]
OK, closing for now as likely either not a problem or solved by recent updates.
I anyone is experiencing this problem with the current version of Solaar, just comment here and the issue can be reopened.

**Comment by janez33** [comment]
Hello @pfps  I have the same issue with MX Master 2S mouse on ubuntu and elementaryOS with the latest version of Solaar. Here is my output.
`Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:C52B
  Serial       : 9A8192FB
    Firmware   : 12.10.B0032
    Bootloader : 02.15
    Other      : AA.AA
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=74

  1: Wireless Mouse MX Master 2S
     Device path  : /dev/hidraw2
     WPID         : 4069
     Codename     : MX Master 2S
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 383EFC17
     Model ID:      B01940690000
     Unit ID:       E137D5CA
        Bootloader: BOT 56.00.B0003
          Firmware: MPM 12.00.B0003
          Firmware: MPM 12.00.B0003
             Other: 
     The power switch is located on the base.
     Supports 32 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 56.00.B0003 4069D22DCF4D01
            Firmware: Firmware MPM 12.00.B0003 B019D22DCF4D01
            Firmware: Firmware MPM 12.00.B0003 4069D22DCF4D01
            Firmware: Other   
            Unit ID: E137D5CA  Model ID: B01940690000  Transport IDs: {'btleid': 'B019', 'wpid': '4069'}
         3: DEVICE NAME            {0005}   
            Name: Wireless Mouse MX Master 2S
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
            Battery: 20%, discharging, next level 5%.
         7: CONFIG DEVICE PROPS    {1806}   internal, hidden
         8: CHANGE HOST            {1814}   
            Change Host: 1:janezk
         9: REPROG CONTROLS V4     {1B04}   
            Key/Button Actions: {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '195': 195, '196': 196}
            Key/Button Diversion: {'82': 0, '83': 0, '86': 0, '195': 0, '196': 0, '215': 0}
        10: ADJUSTABLE DPI         {2201}   
            Sensitivity (DPI): 1000
        11: VERTICAL SCROLLING     {2100}   
            Roller type: 3G
            Ratchet per turn: 24
            Scroll lines: 0
        12: SMART SHIFT            {2110}   
            Scroll Wheel Rachet: 30
        13: HIRES WHEEL            {2121}   
            Multiplier: 8
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            High resolution mode
            HID notification
            Scroll Wheel Direction: False
            Scroll Wheel Resolution: True
        14: GESTURE 2              {6501}   
            Gestures: {'46': True, '45': True}
        15: DFUCONTROL UNSIGNED    {00C1}   
        16: DFUCONTROL SIGNED      {00C2}   
        17: unknown:1813           {1813}   internal, hidden
        18: unknown:1830           {1830}   internal, hidden
        19: unknown:1890           {1890}   internal, hidden
        20: unknown:1891           {1891}   internal, hidden
        21: unknown:18A1           {18A1}   internal, hidden
        22: unknown:18C0           {18C0}   internal, hidden
        23: unknown:1DF3           {1DF3}   internal, hidden
        24: unknown:1E00           {1E00}   hidden
        25: unknown:1EB0           {1EB0}   internal, hidden
        26: unknown:1803           {1803}   internal, hidden
        27: unknown:1861           {1861}   internal, hidden
        28: unknown:9001           {9001}   internal, hidden
        29: unknown:9200           {9200}   internal, hidden
        30: unknown:9240           {9240}   internal, hidden
        31: OOBSTATE               {1805}   internal, hidden
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: App Switch Gesture        , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Has 2 gesture(s), 0 param(s) and 4 spec(s):
        Thumbwheel                 Enabled (   0): True
        NaturalScrolling           Enabled (   1): True
        period unit                Spec    (   3): 800
        DVI field width            Spec    (   1): 8
        field widths               Spec    (   2): 8
        resolution                 Spec    (   4): 2048
     Battery: 20%, discharging, next level 5%.

  3: Wireless Keyboard K360
     Device path  : /dev/hidraw3
     WPID         : 4004
     Codename     : K360
     Kind         : keyboard
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: 3C87ECB3
     The power switch is located on the top case.
     Battery: unknown (device is offline).
`

**Comment by pfps** [comment]
Your MX Master 2S is reporting 20% battery.    Is Solaar claiming something else in the GUI?

**Comment by janez33** [comment]
Yes
![Screenshot from 2020-11-14 16-59-27](https://user-images.githubusercontent.com/4009092/99151367-f7d9d780-269a-11eb-9c2b-c27e27398c07.png)

**Comment by janez33** [comment]
If I switch off and on it's showing its 20% but the notitication comes in with warning for 10%.
![Screenshot from 2020-11-14 17-04-31](https://user-images.githubusercontent.com/4009092/99151453-9e25dd00-269b-11eb-92cd-648c7afceae1.png)

**Comment by pfps** [comment]
Your device battery appears to be near exhaustion.  Sometimes it is reporting 20% and sometimes 5%.  So Solaar is sometimes is showing 20% and a low battery and sometimes 5% and a critical battery.  The device only reports certain battery levels, and there is no level between 20% and 5%.  I don't see anything wrong here.

The 10% number is coming from some other piece of software, as far as I can tell.  It is somehow coming up with a battery percentage that that device does not report.
