### ISSUE TITLE
M185 Won't pair

### ISSUE THREAD

**Issue by GWTRC** [pwr-Solaar/Solaar#436]
I lost the nano-transceiver to my M185 mouse, but I managed to scrounge a working unifying transceiver from a dead M215 I had laying around. Every time I try to pair it, Solaar reports: A new device was detected, but it is not compatible with this reciever. Is this fixable?

**Comment by pfps** [comment]
The two devices are not compatible, unfortunately.   M185 mice will only pair with some receivers.
Documentation on this is very bad.

**Comment by FFY00** [comment]
Seems right. You should try to get other one of the original receivers.
