### ISSUE TITLE
Logitech Craft - no Fn switch 

### ISSUE THREAD

**Issue by jinmingjian** [pwr-Solaar/Solaar#439]
arch linux, solaar git master. We have basic info but no Fn switch. The screenshot is like that shown in #404 

Will we have (interests for ) it supported? Let me know if you want to see more infos...

**Comment by jinmingjian** [comment]
Craft even has an official [sdk](https://github.com/Logitech/logi_craft_sdk) but not Linux-friendly...

**Comment by asava** [comment]
I also have a Logitech Craft, and indeed I cannot find a way to switch Fn-Keys. Not via Solaar nor via any other method. Any information about this?

**Comment by spaced** [comment]
If you press the FN key and ESC at the same time, the keyboard will change the default behavior.
however, i have a local WIP branch with a initial support for craft, i will push it soon.

**Comment by wurmli** [comment]
@spaced Has anything happened regarding "initial support for craft"? I just got such a keyboard and even if it looks and feels nice, not being able to switch desktops with Ctrl-Fn renders it second class. That's the first time for me with a Logitech product that I as a Linux user get screwed.

**Comment by wurmli** [comment]
@spaced Has anything happened regarding "initial support for craft"? I just got such a keyboard and even if it looks and feels nice, not being able to switch desktops with Ctrl-Fn renders it second class. That's the first time for me with a Logitech product that I as a Linux user get screwed.

**Comment by wurmli** [comment]
@spaced I got your advice now: press the "Function Key" fn and esc, which toggles the way F1 to F12 send scan codes, i.e. Ctrl-F1 for example switches to Desktop 1.

Thank you for your advice.

**Comment by doctor64** [comment]
Can you please provide output from _solaar show_ for this device?

**Comment by fiddur** [comment]
This one?
```
$ solaar-cli show
Unifying Receiver [/dev/hidraw4:43CC86FA] with 2 devices
1: Craft Advanced Keyboard [Craft:B924F1B3] 
…
```
(using 0.9.2 from debian)

**Comment by spaced** [comment]
should now work with #587

**Comment by FFY00** [comment]
Can I get some conformation #587 works?

**Comment by spaced** [comment]
@FFY00 confirmed with my own craft keyboard. works as expected.

**Comment by spaced** [comment]
@FFY00 works as expected, confirmed with my own craft keyboard. BUT: if you use the way pressing  `FN`-`ESC` together on the keyboard, then the toggle in solaar has no effect anymore.

**Comment by FFY00** [comment]
That seems like a firmware issue, if it's an issue at all.
