### ISSUE TITLE
Doesn't work in Debian Stretch

### ISSUE THREAD

**Issue by wisemagic777** [pwr-Solaar/Solaar#442]
After upgrading to Debian Stretch, Solaar is buggy. Usually fails altogether. I have a K800 Logitech keyboard and M705 Mouse. Worked great under Wheezy and Jessie. 

This isn't a major issue though. Google Chrome has a Logitech Unifying app, and it works perfectly.

**Comment by Jeansen** [comment]
Oh great, I tried the Google Chrome app. Works perfectly. I was not able to use solaar because it tells me  no unifying found.

**Comment by MagicFab** [comment]
Package in Stretch work for me, although they're old (9.2).

For Debian packages updates, see #288 . tl;dr: there aren't any at the moment.

**Comment by Jeansen** [comment]
> Package in Stretch work for me, although they're old (9.2).
> 
> For Debian packages updates, see #288 . tl;dr: there aren't any at the moment.

Jap, same here. Old, but works - so far.
