### ISSUE TITLE
Not showing the connected mouse and fails to pair although mouse is working fine. 

### ISSUE THREAD

**Issue by RustyRaptor** [pwr-Solaar/Solaar#445]
First of all. Thank you everyone involved in this project. I had just bought this T620 and when I realized it doesn't work on linux I thought I was done for. I will try to contribute what I can here. 

https://i.imgur.com/m4eNi0Y.png

Here is the screenshot of what I see. It also doesn't show the correct model I think. However this is also from a live USB so I will go ahead and finish installing then see how it works when everything is installed locally. This post is mostly just to say thanks.

**Comment by pfps** [comment]
Did PR #452 fix your problem?

**Comment by RustyRaptor** [comment]
Well this was so long ago I don't even have the mouse anymore. Considering I have memories of using that mouse a lot I think it must have. Or something did? I'll say yes until someone else says otherwise :)

**Comment by RustyRaptor** [comment]
Oh wait my issue says the mouse itself was working fine so I guess I can't really confirm :(

**Comment by pfps** [comment]
If you aren't having the problem (for whatever reason!) there isn't much that can be done to diagnose it, so I'm going to close this issue.  If someone else has the problem they can open a new issue and refer to this one.
