### ISSUE TITLE
Version 0.9.2 does not show notification or GUI on Xubuntu 16.04 although M510v2 works

### ISSUE THREAD

**Issue by jwkokc** [pwr-Solaar/Solaar#446]
The title tells it; using "solaar show" at the command line gives a full display of capabilities for my M510v2, but clicking the icon on the GUI's panel does nothing at all, nor does any notification appear when logging in. This installation was installed from solaar-master.zip, downloaded May 24.

Hovering on the panel icon displays the description tool-tip, but that's all I get.

Meanwhile the mouse is working properly, but it would be nice to be able to adjust pointer speed...

**Comment by KvalheimRacing** [comment]
Same problem here, ubuntu 18.04, GUI is blank, but Solaar works:

> blablabla@ubuntu:~$ lsusb | grep Logitech
> Bus 003 Device 020: ID 046d:c52b Logitech, Inc. Unifying Receiver

> blablabla@ubuntu:~$ dmesg | grep Logitech
> [    2.344466] input: ImPS/2 Logitech Wheel Mouse as /devices/platform/i8042/serio1/input/input4
> [1780465.439823] usb 3-6: Manufacturer: Logitech
> [1780465.501896] logitech-djreceiver 0003:046D:C52B.0004: hiddev0,hidraw1: USB HID v1.11 Device > [Logitech USB Receiver] on usb-0000:00:14.0-6/input2
> [1780465.636904] input: Logitech MX Master 2S as /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.2/0003:046D:C52B.0004/0003:046D:4069.0005/input/input16
> [1780465.637412] logitech-hidpp-device 0003:046D:4069.0005: input,hidraw2: USB HID v1.11 >Keyboard [Logitech MX Master 2S] on usb-0000:00:14.0-6:1
> [1976931.908452] usb 3-6: Manufacturer: Logitech
> [1976931.915103] logitech-djreceiver 0003:046D:C52B.0009: hiddev0,hidraw2: USB HID v1.11 Device > [Logitech USB Receiver] on usb-0000:00:14.0-6/input2
> [1976932.042160] input: Logitech MX Master 2S as /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.2/0003:046D:C52B.0009/0003:046D:4069.000A/input/input17
> [1976932.042543] logitech-hidpp-device 0003:046D:4069.000A: input,hidraw3: USB HID v1.11 Keyboard [Logitech MX Master 2S] on usb-0000:00:14.0-6:1

> blablabla@ubuntu:~$ solaar-cli show
> Unifying Receiver [/dev/hidraw2:25909483] with 1 devices
> 1: Wireless Mouse MX Master 2S [MX Master 2S:71757647] 

> blablabla@ubuntu:~$ solaar
> /usr/share/solaar/lib/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. > Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>   __import__(module)
> solaar: error: already running

Anyone know a quick fix to get the gui working?

**Comment by KvalheimRacing** [comment]
On a later note, the GUI works, when I run 
> $ solaar-cli config 1
I get
> solaar-cli: error: no settings for Wireless Mouse MX Master 2S
hmm..

**Comment by jwkokc** [comment]
And the attached screenshot shows what I get here...

-- 
Jim

**Comment by jwkokc** [comment]
[textfile.txt](https://github.com/pwr/Solaar/files/2353194/textfile.txt)
The problem persists, and I finally learned how to capture debug information. The attached file captures the first few seconds of an attempt to troubleshoot thiis problem: obviously the listener program has become confused on this system. The next problem is "Why, and how to fix?"

**Comment by pfps** [comment]
There have been several changes to solaar over the past couple of years so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original poster.
