### ISSUE TITLE
Both K780 and M720 options not showing

### ISSUE THREAD

**Issue by ghost** [pwr-Solaar/Solaar#451]
![5592420_sa](https://user-images.githubusercontent.com/26362558/43786060-c2eaf584-9a35-11e8-95ce-6ba585d1aa2b.jpg)
![m720-triathlon-mouse](https://user-images.githubusercontent.com/26362558/43786059-c2d95a18-9a35-11e8-87f4-828a43ea6d2f.png)
I want to be able to FN swap on the K780 multi device keyboard along with setting up the gesture button on the M720 multi device mouse. The gesture button can be set to do a long of things, in my case I just want it to open up a program when I press, at least the screenshot tool I love using.

I am using Deepin OS 15.6

**Comment by pfps** [comment]
Solaar does not currently handle reprogramming keys.  If this reprogramming is something that is supported in the device itself, Solaar might be extended to do this reprogramming.  Otherwise, this is out of the scope of Solaar.

**Comment by pfps** [comment]
Closing as probably out of scope, and no response from submitter.
