### ISSUE TITLE
k750 Keyboard not being detected as online

### ISSUE THREAD

**Issue by mxlan** [pwr-Solaar/Solaar#459]
Installed latest from master branch: b8529030e6e44995758f614c3a4227c23ff14282

Detects MX Master and M310 Mice fine and both can be used in tandem, the k750 only rarely works and is mostly detected as offline.

[debug.txt](https://github.com/pwr/Solaar/files/2342030/debug.txt)
more verbose
[debug_2.txt](https://github.com/pwr/Solaar/files/2342043/debug_2.txt)

Firmware as reported in windows via Logitech Unifying Software:
Mouse M310/M310t: 040.001.00017
Mouse Mx Master: 011.005.00018
Keyboards K750: 033.000.00015

---
did I perhaps run the installation incorrectly?

rules.d/install.sh
... unplug and re-plug the receiver
setup.py install

**Comment by nightsky30** [comment]
Mine reports as being online, at least for a little while as I'm typing.  If I don't type for a minute or so, then Solaar reports it as offline.

Solaar v0.9.2

K750
Battery:             100%
Wireless Link:   encrypted
Lighting:            11 - 538 lux
  Firmware:        RQK 33.00.B0015
  Bootloader:      DFU 00.02.B0003

Logitech Unifying Receiver
  VendorId:         USB:0x046D
  USB id:            046d:c52b
  Version:           RQR24.07_B0030
  VersionBootloader:    BOT03.02_B0009

My M510 mouse appears as perpetually offline...

**Comment by dfht684** [comment]
I have a similar issue with my K750. Running "solaar show" lists my K750, but the Solaar app doesn't even list the keyboard. Here's the output of "show":

` Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 
    Firmware   : 12.07.B0029
    Bootloader : 02.15
    Other      : AA.AA
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=122, 2=216

  1: Wireless Solar Keyboard K750
     Codename     : K750
     Kind         : keyboard
     Wireless PID : 4002
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: 
          Firmware: RQK 33.00.B0015
        Bootloader: DFU 00.02.B0003
     The power switch is located on the edge of top right corner.
     Supports 11 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: REPROG CONTROLS        {1B00}   
         5: WIRELESS DEVICE STATUS {1D4B}   
         6: unknown:1DF3           {1DF3}   hidden
         7: FN INVERSION           {40A0}   
         8: ENCRYPTION             {4100}   
         9: SOLAR DASHBOARD        {4301}   
        10: KEYBOARD LAYOUT        {4520}   
     Has 12 reprogrammable keys:
         0: MY HOME                    => HomePage                      is FN, FN sensitive, reprogrammable
         1: Mail                       => Email                         is FN, FN sensitive, reprogrammable
         2: SEARCH                     => Search                        is FN, FN sensitive, reprogrammable
         3: Calculator                 => Calculator                    is FN, FN sensitive, reprogrammable
         4: MEDIA PLAYER               => Music                         is FN, FN sensitive, reprogrammable
         5: Previous                   => Previous                      is FN, FN sensitive
         6: Play/Pause                 => Play/Pause                    is FN, FN sensitive
         7: Next                       => Next                          is FN, FN sensitive
         8: Mute                       => Mute                          is FN, FN sensitive
         9: Volume Down                => Volume Down                   is FN, FN sensitive
        10: Volume Up                  => Volume Up                     is FN, FN sensitive
        11: SLEEP                      => Sleep                         is FN, FN sensitive, reprogrammable
     Battery status unavailable.

  2: Performance Mouse MX
     Codename     : Performance MX
     Kind         : mouse
     Wireless PID : 101A
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: 
          Firmware: 15.01.B0062
        Bootloader: 02.11
             Other: 00.09
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Battery: critical, discharging.
`

I'm running this on Ubuntu 19.10. Strangely, the system power settings recognizes the battery level:
- performance mx ~ 5%
- K750 = 100%

**Comment by nightsky30** [comment]
I recently retested by building from master (1.0.1), and it seemed to help with listing devices.  With 0.9.2 the keyboard or mouse would sometimes disappear.  I don't recall my mouse going inactive this time.  The keyboard can still appear inactive after a while (greyed out), but at least it is listed.  And the pressing of keys seems to reactivate it.  Not perfect, but seems improved.

**Comment by pfps** [comment]
Is there anything else that should be done on this issue?

**Comment by nightsky30** [comment]
Not sure.  The keyboard still sleeps, but it may be just the way the hardware functions to save battery life.  I'm okay with it sleeping as long as it remains listed and wakes when it should.  It seems to be doing that with the latest  version.

**Comment by pfps** [comment]
OK, I'll close this for now.
