### ISSUE TITLE
Solar AUR Package Listed has been deleted

### ISSUE THREAD

**Issue by scoronado12** [pwr-Solaar/Solaar#461]
You may need to change the following AUR link
https://aur.archlinux.org/packages/solaar

to this
https://aur.archlinux.org/packages/solaar-git

**Comment by scoronado12** [comment]
My mistake, Solaar has been moved to community.

https://www.archlinux.org/packages/community/any/solaar/

**Comment by pfps** [comment]
The repo has the community link as well as the older link.  Should the older link be removed?

**Comment by scoronado12** [comment]
It probably should be if it is 404'ing

**Comment by pfps** [comment]
It's not 404-ing but it does point to a package for an old version of Solaar.

**Comment by pfps** [comment]
I think that this pointer is no longer in the current Solaar documentation.
