### ISSUE TITLE
Settings missing 18.04.1 + 0.9.2 + mx master 2s

### ISSUE THREAD

**Issue by andrewdmcleod** [pwr-Solaar/Solaar#463]
Using master or package from universe on ubuntu 18.04.1, there are no settings (Battery percentage, Wireless link only) in the GUI.

#:solaar-cli show
Unifying Receiver [/dev/hidraw1:63AE9750] with 1 devices
1: Wireless Mouse MX Master 2S [MX Master 2S:BF901387] 
#:solaar-cli config 1
solaar-cli: error: no settings for Wireless Mouse MX Master 2S

**Comment by hrvoj3e** [comment]
Same thing on Arch.

At first there were settings but I only got an exclamation mark icon with tooltip that it could not write settings.

**Comment by taylorthurlow** [comment]
I'm also having this issue on Ubuntu 18.04. Obviously we don't have the `solaar-git` package but I looked up the PKGBUILD for it and replicated what it was doing - but it still hasn't solved the problem.

**Comment by lejurassien** [comment]
Hello, a few days ago I was using the mx revolution which on manjaro and ubuntu 18.04 and the setting of the DPI was very present and since my mouse change for a mx master 2s the setting has completely disappeared on manjaro ubuntu and debian which I repeat worked very well, I tried a clean reinstallation but still no trace of dpi setting and it is quite painful because the mouse keeps in memory a speed that I can not even adjust in so-called normal settings

<a href="https://imgur.com/iwLHIIn"><img src="https://i.imgur.com/iwLHIIn.png" title="source: imgur.com" /></a>
Translated with www.DeepL.com/Translator

**Comment by toverux** [comment]
@taylorthurlow, did you find a solution?

**Comment by taylorthurlow** [comment]
> Hello @taylorthurlow, have you managed to get those settings in the end?

@toverux Unfortunately, no, sorry.

**Comment by hoemon** [comment]
Any updates about this? I also have an mx master and no settings are available.

**Comment by nbelavic** [comment]
Please try to fix this. Just got MX Master 2S, and i have no settings (just battery and link). Ubuntu 18.04.2 LTS.

**Comment by MacedoRAC** [comment]
+1 Using Linux Mint 19 and the Logitech MX Master 2S. Just seeing the battery status and link. It would be really nice to be able to adjust the DPI and scroll settings. 

Also does anyone know how to change this configurations using the command line? Is it even possible? And change the buttons bindings, is it possible in any way?

**Comment by rockerbacon** [comment]
Same problem here

**Comment by hoemon** [comment]
building it from the source helps, the recent version works when its built from the source

**Comment by hoemon** [comment]
Ah, but the settings are not saved so each restart it should be re-set (DPI)

**Comment by MacariDev** [comment]
I'm on Elementary OS and I have the same problem. If someone finds the fix please let me know

**Comment by emilianox** [comment]
same error on elementary juno

**Comment by Rknegt** [comment]
I had the same issue but when I build solaar from source I got the options. I am running Ubuntu 18.04.3 LTS.

![Screenshot from 2019-12-03 15-34-35](https://user-images.githubusercontent.com/51092169/70060273-81a3a880-15e2-11ea-8642-f58986e3b2c7.png)

**Comment by pfps** [comment]
Is anyone seeing this problem with the version of Solaar in the repo?

**Comment by KindarConrath** [comment]
I just downloaded source and followed the install instructions.
after that
I had to unplug, plug back in (for permissions) then unpair and pair my mouse, but after pairing my mouse again, all the settings showed up.

**Comment by pfps** [comment]
OK, so this issue appears to be solved.  Closing.
