### ISSUE TITLE
Snap Package

### ISSUE THREAD

**Issue by benyanke** [pwr-Solaar/Solaar#464]
Any thoughts on creating a snapcraft package? It would be great to be able to try it there, and in particular, if integrated with a travis build, users could run the master branch....

**Comment by rijnhard** [comment]
This would be amazing

**Comment by FFY00** [comment]
Snap is not really a good solutions but I understand is necessary in distributions like ubuntu where software is usually very outdated. I would suggest you to move to a distribution that actually updates your packages but that is not really a feasible solution for some users. If anyone wants to do this work, feel free. I have no problem in merging it as long as someone is willing to maintain it.

**Comment by pfps** [comment]
Using pip to install from PyPI is probably a good solution.  I've just updated Solaar in PyPI to 1.0.1.  I'll also stick the next RC there (1.0.2rc1 has a problem in it so I'm not uploading that release).
So you can (will) be able to just do `pip install --user solaar` or `sudo pip install solaar`.

**Comment by pfps** [comment]
There is also two ppa packages for Solaar, one for the most recent release and one for the current git version.   I think that with the pip install, a snap package is not needed.  Of course, anyone is free to set up a snap package for Solaar.
