### ISSUE TITLE
M325

### ISSUE THREAD

**Issue by johnjasonj** [pwr-Solaar/Solaar#469]
I installed 0.9.2 from Xubuntu repositories because I was having problems with two M185 mice, one on my laptop and one on my desktop. I thought the problem might be in the pairing, but neither showed up in Solaar. I read about changes to some Python file to get the M185 to appear, but I'm not a programmer and don't know how to do that. 

But  in the meantime I grabbed an M325 that I was not using and set it up on the desktop, and it immediately appeared in the Solaar GUI, complete with battery information. I just wanted you to know that so you can add that information for the M325 to your Devices page, which currently is blank for it.

**Comment by jwkokc** [comment]
The version in the Xubuntu repository is sadly out of date. I had the 
same problem well over a year ago. Fortunately there's a PPA that can be 
added to your repository list that can bring things up to date -- but if 
the M325 solves the problem for you, no change is really necessary.

-- 
Jim

**Comment by doctor64** [comment]
Support for M185 mouse was added in #337

**Comment by pfps** [comment]
Is this still a problem in the version of Solaar from this repository?
