### ISSUE TITLE
Anywhere MX on ubuntu 18.04 -- scrolls insanely fast (too fast to use)

### ISSUE THREAD

**Issue by arooni** [pwr-Solaar/Solaar#473]
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
[I]  ~/D/Calibre Library  install xserver-xorg-input-evdev
Reading package lists... Done
Building dependency tree
Reading state information... Done
xserver-xorg-input-evdev is already the newest version (1:2.10.5-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
[I]  ~/D/Calibre Library  xinput list-props 18
Device 'Logitech Anywhere MX':
        Device Enabled (141):   1
        Coordinate Transformation Matrix (143): 1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
        libinput Natural Scrolling Enabled (276):       0
        libinput Natural Scrolling Enabled Default (277):       0
        libinput Scroll Methods Available (278):        0, 0, 1
        libinput Scroll Method Enabled (279):   0, 0, 0
        libinput Scroll Method Enabled Default (280):   0, 0, 0
        libinput Button Scrolling Button (281): 2
        libinput Button Scrolling Button Default (282): 2
        libinput Middle Emulation Enabled (283):        0
        libinput Middle Emulation Enabled Default (284):        0
        libinput Accel Speed (285):     -0.165468
        libinput Accel Speed Default (286):     0.000000
        libinput Accel Profiles Available (287):        1, 1
        libinput Accel Profile Enabled (288):   1, 0
        libinput Accel Profile Enabled Default (289):   1, 0
        libinput Left Handed Enabled (290):     0
        libinput Left Handed Enabled Default (291):     0
        libinput Send Events Modes Available (261):     1, 0
        libinput Send Events Mode Enabled (262):        0, 0
        libinput Send Events Mode Enabled Default (263):        0, 0
        Device Node (264):      "/dev/input/event5"
        Device Product ID (265):        1133, 4119
        libinput Drag Lock Buttons (292):       <no items>
        libinput Horizontal Scroll Enabled (293):       1
[I]  ~/D/Calibre Library  cd ../P2P\ Downloads/^C
[I]  ~/D/Calibre Library  xinput set-prop 18 'Evdev Scrolling Distance' 3 1 1
property 'Evdev Scrolling Distance' doesn't exist, you need to specify its type and format
[I]  ✘  ~/D/Calibre Library 

Not sure what to do from here.  Mouse movement works great but scroll speed on mousewheel is way to fast.

**Comment by arooni** [comment]
version 0.9.2

**Comment by pfps** [comment]
There have been several changes to solaar over the past year or so so this issue may have already been addressed.

If you are still using solaar and this issue has not been resolved please download and run the current version from this github repository. If the problem still persists add a new comment here, providing the output of `solaar -V` and `solaar show` and any new information about the issue.

If you are still using solaar you should be able to download and run its current version (in Linux) as follows:

1. Install git on your machine if it is not already installed. This is generally done via `sudo apt install git` or `sudo dnf install git`
2. Change to a directory where you want the code.
3. Download solaar via `git clone https://github.com/pwr-Solaar/Solaar.git`
4. Run solaar via `Solaar/bin/solaar`

For more information on installing solaar from github see https://github.com/pwr-Solaar/Solaar/blob/master/docs/installation.md

**Comment by pfps** [comment]
Closing due to no response from original poster.
