### ISSUE TITLE
FN swap on K400+ in dialog is confusing

### ISSUE THREAD

**Issue by Aydan** [pwr-Solaar/Solaar#474]
I just installed Solaar from git b8529030e6e44995758f614c3a4227c23ff14282 and I can swap the FN-Keys, but the switch seems to work the wrong way:
- When the switch shows On, the function swap is not active
- When the switch shows Off, the function swap is active

The design of the switch is misleading if it shows the state it will go to when clicked, not the state it is currently in.

**Comment by djibux** [comment]
Hello @Aydan 
Where do you find that option?  I have version `0.9.2+dfsg-8` on Debian, and the option is not available.
`solaar-cli config 1` replies `solaar-cli: error: no settings for Wireless Touch Keyboard K400 Plus`

**Comment by Aydan** [comment]
I built from git, as referenced in https://github.com/pwr/Solaar/issues/474#issue-380384625

**Comment by pfps** [comment]
I just checked with my K400+.  When the Swap Fx function is on, the keyboard reports the special keycodes (e.g. F5 produces XF86Search.  When the Swap Fx Function is off, the keyboard reports the Fn keycodes.
Please check with solaar from this repository.  If you are experiencing something different, please provide output from `solaar config 1` (replace 1 with the connection number of your K400+) and describe what output you get from your function keys.

**Comment by pfps** [comment]
Closed due to no reponse.
