### ISSUE TITLE
K400+ always shows 90% battery

### ISSUE THREAD

**Issue by Aydan** [pwr-Solaar/Solaar#475]
My K400+ always shows 90% battery no matter if I put an almost dead or a new battery in.

**Comment by doctor64** [comment]
Can you please run _solaar -ddd show_ with old and new battery and provide logs? I assume you run latest solaar version from repository master.

**Comment by Aydan** [comment]
Here's the two dumps, one with an almost dead battery, and one with a fresh one:
[low-bat.txt](https://github.com/pwr/Solaar/files/2605148/low-bat.txt)
[new-bat.txt](https://github.com/pwr/Solaar/files/2605149/new-bat.txt)
I hope this helps.

**Comment by Aydan** [comment]
Here are the logs:
[low-bat.txt](https://github.com/pwr/Solaar/files/2605217/low-bat.txt)
[new-bat.txt](https://github.com/pwr/Solaar/files/2605218/new-bat.txt)

**Comment by doctor64** [comment]
I'm sorry, in both logs I see line logitech_receiver.base: (3) => r[11 01 060B 5A320000000000000000000000000000]
which means what hardware reports battery status: battery charge 0x5a=90 %, next reporting level 0x32=50%, battery status = 0x0 - discharging
So, you have good battery, or faulty hardware :) In both cases, solaar correctly report status.
Take into account what different Logitech devices have different capabilities to report battery status - some can report with granularity of 5% like M515 mouse, if i remember correctly, some, like M185 can report only 90%, 70%, 5% charge.

**Comment by pfps** [comment]
It appears that Solaar is working as well as it can, given the reports from the device so I'm closing this issue.
