### ISSUE TITLE
Solaar connected keyboard can't wake the system after supsending to RAM

### ISSUE THREAD

**Issue by danbohea** [pwr-Solaar/Solaar#478]
Also, once I've successfully woken the system by another means (power button or a second wired keyboard) the input on the Solaar connected keyboard appears to have been recognised as I can see character entries in the login password field.

- KDE Neon 5.14
- Solaar 0.9.2
- Logitech K750 keyboard

**Comment by pfps** [comment]
I don't think that this is in the capabilities of a system like Solaar.  You may have to adjust how your system responds to input on the USB port that the receiver is in.
