### ISSUE TITLE
Take a look on official ChromeApp

### ISSUE THREAD

**Issue by Grogdunn** [pwr-Solaar/Solaar#481]
Hi,
surfing on internet I've found this: https://chrome.google.com/webstore/detail/logitech-unifying-for-chr/agpmgihmmmfkbhckmciedmhincdggomo/related

Tested with my m570 trackball and it works.

Grogdunn

**Comment by doctor64** [comment]
Hi,
I test it. It works, sort of. Does not detect Nano receiver from M185 and provide only basic functionality like pairing and battery status for Unifying receiver and M325.
