### ISSUE TITLE
Ui keeps coming to front everytime I reach to my keyboard

### ISSUE THREAD

**Issue by gerroon** [pwr-Solaar/Solaar#488]
Hi

I keep Solaar in the tray, it works very well but everytime I reach to my keyboard (logitech k400r) the ui keeps coming to front. It is not a big issue but an annoyance. I am not sure if it is trying to warn me about battery or something.

Any way to disable it that behavior?

**Comment by lisaak1** [comment]
I have the same experience. I think it's connected with some power management of the devices. After a while I do not touch mouse (or keyboard), probably after wake up of the device, the Solaar window comes up (and is on top, which is the most annoying thing). 

My setup is: 
Debian Buster, 
KDE Plasma, 
Dell E7240
1st Unifying receiver connected to notebook
- mouse M560
- numpad N305 (usually switched off)
2nd Unifying receiver connected to docking station
- keyboard K520

BR,
Stepan.

**Comment by gerroon** [comment]
I solved my issue by using AllTray. I just put that into tray with AllTray and never shows up, at least not able to show up anymore

**Comment by pfps** [comment]
Is this still a problem with the version of Solaar from the repo?

**Comment by pfps** [comment]
Closing due to no response from original poster.
