### ISSUE TITLE
Availability of Unifying Receiver with another usb vid:pid

### ISSUE THREAD

**Issue by Ashark** [pwr-Solaar/Solaar#491]
Hi,
I want to connect two unifying receivers to one pc and to be able to passthrough one of them via usb to virtual machine.
Some Logitech devices have Easy-Switch technolody (multi device), which simply mean you can pair them with another bluetooth/unifying receiver and switch between them in a press of a button. I have such keyboard and mouse.
But the problem is that to pass through only one receiver, it should have different usb vid:pid.

Grepping unifying in this http://www.linux-usb.org/usb.ids document gives this:
```
	c52b  Unifying Receiver
	c52f  Unifying Receiver
	c531  C-U0007 [Unifying Receiver]
	c532  Unifying Receiver
	c534  Unifying Receiver
```

In this repository there is a file docs/usb-ids.txt

```
Unifying receiver:
	046d:c52b		interface: 2		driver: logitech-djreceiver
	046d:c532		interface: 2		driver: logitech-djreceiver

Nano receiver, Advanced/Unifying ready:
	046d:c52f		interface: 1		driver: hid-generic

Nano receiver:
	046d:c51a		interface: 1		driver: hid-generic
	046d:c526		interface: 1		driver: hid-generic
	046d:c52e		interface: 1		driver: hid-generic
	046d:c531		interface: 1		driver: hid-generic
```
All my unifying receivers have 046d:c52b id. I know that usb devices can change their id on the fly. I was wondering if that c532 device is some different from mine or it is the same receiver? Lenovo support refused to give me some information on that.

In case it is different device, then how can I visually differentiate it from devices like mine? Isn't there any other way of inserting it to pc and running lsusb? I am asking because ebay sellers do not provide such information in description.

As I understand correctly (please tell me if I am mistaken), all nano receivers including that "unifying ready" one cannot pair keyboards, so they won't solve my problem.

What is that c534 listed? Is it unifying or nano receiver?

Another options:
Passthrough the whole second usb controller (devices connected to it will be seen by vm) - good solution, but I have problems with it.
Get a bluetooth dongle with hid proxy capability (to be able to control vm while os is not yet loaded) - maybe, but I have read that it is hard to find such
Modify receiver's firmware (to allow it to appear as other pid, but bind the same driver) - I saw Bastille security team was doing modifications, but I did not explored it deeply.

**Comment by xurubin** [comment]
FYI I encountered the same issue and managed to change the pid by patching the firmware https://github.com/xurubin/logitech_unifying_pid_patch

**Comment by robertjsandor** [comment]
Thank you Rubin, I will try to learn enough from your fine work to
understand how to do what you suggested. Many thanks,
Bob

**Comment by pfps** [comment]
Solaar uses the USB id to determine some of the characteristics of the receiver.  Other characteristics are determined based on querying the receiver.  Solaar tries to do as much as possible the latter way.
So changing the USB id to another one that looks and acts the same way is possible but might cause problems.

Without any guarantee, the safest changes would be ones that use the same setup in base_usb.py, i.e., c52b to c532 or c517 to c526.

**Comment by pfps** [comment]
Closing as somewhat out of scope and no response from submitter.

**Comment by Ashark** [comment]
pfps, thanks for the information.
