### ISSUE TITLE
Ubuntu 18.04 Solaar (0.9.2) loosing/forgetting device

### ISSUE THREAD

**Issue by zetheroo** [pwr-Solaar/Solaar#493]
1. The mouse (Performance MX) always works.
2. Solaar sometimes appears in the tray as the battery icon (good) but mostly as the gear icon (bad)
3. Even when Solaar shows the battery icon, and the device connected, at some point (not sure what causes it) the icon will switch to the gear, and the device is lost/forgotten by the GUI/software.
4. Without Solaar remembering the device I have no idea if the battery is getting low or not.

**Comment by chriswyatt** [comment]
Happens to me to, with my MX Ergo and 046d:c52b unifying receiver. What unifying receiver are you using?

If you run Solaar from a terminal like this, you can collect a log:
```
solaar 2> solaar.log
```

Make sure other instances of Solaar are already closed, and keep the terminal window open.

**Comment by chriswyatt** [comment]
Might be the same issue as this one: https://github.com/pwr/Solaar/issues/444

**Comment by zetheroo** [comment]
Well this is odd - I received emails telling me that you @chriswyatt had commented 3 times on this ticket, but here I see only one of the comments ...

Anyhow ... to answer the invisible comments:

> Happens to me to, with my MX Ergo and 046d:c52b unifying receiver. What unifying receiver are you using?
> If you run Solaar from a terminal like this, you can collect a log:
> solaar 2> solaar.log
> Make sure other instances of Solaar are already closed, and keep the terminal window open.

solaar.log:
```
/usr/share/solaar/lib/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
/usr/share/solaar/lib/solaar/ui/notify.py:33: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify

(solaar:11829): Gdk-CRITICAL **: 09:41:23.191: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

```

> Also, when you say device, which device? With me, it's forgetting the unifying receiver itself. That's worth mentioning in your report as well.

Solaar says: No Logitech receiver found
So device = Logitech receiver
Bus 003 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver

**Comment by chriswyatt** [comment]
Deleted them, as it occurred to me that 0.9.2 is quite an old version, and #444 is potentially a duplicate, so I thought I'd let an experience developer come along and decide whether it's worth collecting logs and stuff. I'm just a user of this tool.

**Comment by zetheroo** [comment]
Is there a newer version?

**Comment by chriswyatt** [comment]
Not yet: https://github.com/pwr/Solaar/milestone/10

**Comment by Vladimyr0** [comment]
probably I found the clue... 
when solaar has got a broken channel, the command `sudo systemctl start fwupd.service` brings it back to work.

**Comment by Vladimyr0** [comment]
"saving of the drowning people is the duty of the drowning themselves" ©
so, I created a small script by Python to show state of the batteries in systray. 
as it's said, it can show two icons simultaneously for both keyboard and mouse. 
please have a look: https://github.com/Vladimyr0/batterindicator

**Comment by arooni** [comment]
Have had this occur on latest release (1.something)  ; by purging and reinstalling solaar seemed to fix it

**Comment by pfps** [comment]
I suspect that this problem is no longer active in the version of Solaar currently in this repository.  If you are experiencing problems with Solaar not showing connected receivers please clone this repository and run solaar from it.

**Comment by pfps** [comment]
Closing due to no response from submitter.
