### ISSUE TITLE
CLI pairing error: _find_receiver() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by lsuchocki** [pwr-Solaar/Solaar#494]
CLI pairing doesn't work:

~]$ solaar pair 725B901B
solaar: error: _find_receiver() takes exactly 2 arguments (1 given)
~]$ solaar -V
solaar 0.9.2

lib/solaar/cli/pair.py, line 38:
receiver = find_receiver(receiver_name)
should become:
receiver = find_receiver(receivers, receiver_name)

**Comment by pfps** [comment]
Version 0.9.2 is very outdated.   If this is still a problem in 1.0.1 please so indicate.

**Comment by pfps** [comment]
I'm closing this issue due to a lack of response.  If you are experiencing the problem in the current version of Solaar please reopen the issue.
