### ISSUE TITLE
no battery status on M510 mouse

### ISSUE THREAD

**Issue by pwr** [pwr-Solaar/Solaar#5]

**Comment by mattacc** [comment]
I'm still experiencing this issue with Solaar and the M510. My Solaar version is 0.9.2

**Comment by Lekensteyn** [comment]
@mattacc  does `upower -d` show the battery status for you?

**Comment by mattacc** [comment]
mouse
    present:             yes
    rechargeable:        yes
    state:               unknown
    warning-level:       none
    percentage:          0%
    icon-name:          'battery-missing-symbolic'
