### ISSUE TITLE
include support for h800 headset with nano receiver 046d:0a29

### ISSUE THREAD

**Issue by sourceofentropy** [pwr-Solaar/Solaar#502]
Any possibility of providing support for the H800 Wireless headset Nano receivers?

```DRIVER=hid-generic  
HID_ID=0003:0000046D:00000A29  
HID_NAME=Logitech Logitech Wireless Headset  
HID_PHYS=usb-0000:00:14.0-2/input3  
HID_UNIQ=88C62685FD90  
MODALIAS=hid:b0003g0001v0000046Dp00000A29```

Simply adding the id to the source doesn't work for me. 

I could be doing something wrong but I'm guessing the H800 is using a protocol that isn't supported.

If it should work let me know and I'll revisit my changes and provide examples of the modifications in progress. 

Via google you can find quite a few people fed up with Logitech for not updating their Nano Receiver pairing software to be compatible with windows 8, 10, or Mac or Linux. Myself included. 

There's definitely some demand for it for anyone that's had trouble replacing their Nano Receiver.

**Comment by sourceofentropy** [comment]
Although no major details are provided here this does appear to be a related issue https://github.com/pwr/Solaar/issues/419

**Comment by doctor64** [comment]
I don't have working H800 headset at hand, but as far as I remember, it's not have any Windows software and unable to report information like battery status to PC. Do you have any control software for Windows?

**Comment by sourceofentropy** [comment]
I've never run it with extra software beyond the drivers used when you plug the dongle in. 
I've never tried the "media track control center" you can find here:
[](https://support.logitech.com/en_us/product/wireless-headset-h800/downloads#windowsPnlBar
)
I have tried the pairing utility with no success on windows 10 regardless of compatibility settings, no success in windows vista or xp either. 

This headset does not relay battery status.
I have used the headset on windows 10, Fedora, and Ubuntu regularly. 
In Ubuntu over Bluetooth the volume +/- buttons and next/prev track buttons, play/pause on the right earpiece do work. The mute button probably does as well. 

I'm pretty sure in Fedora over bluetooth it would show up as an H600 and will have no volume control but I don't have a copy handy right now to check.
 
However most days I prefer to use the dongle for a variety of reasons and would love to see it supported in Solaar.

**Comment by doctor64** [comment]
I fear what H800 use its own protocol, incompatible with solaar. I think it's dongle work as standard HID device, not a HID++ protocol which can be controlled by solaar.  If I was able to fix my H800 i will try this media control center, but don't held high hopes.

**Comment by pfps** [comment]
I suggest this report be closed.

**Comment by FFY00** [comment]
Yes, in case you confirm H800 uses the HID++ protocol please re-open.
