### ISSUE TITLE
Logitech craft dead keycombination Shift_R+Caps_Lock+ISO_Left_Tab

### ISSUE THREAD

**Issue by fiddur** [pwr-Solaar/Solaar#505]
When holding Shift_R and Caps_Lock, the ISO_Left_Tab is never sent (or shown by xev).

Since I have my Caps_Lock as Ctrl, this is my normal way of switching tabs backwards in a browser...

Using Shift_L works as intended, but is a really weird thing to do with the hand in place :D

**Comment by fiddur** [comment]
There are more dead key combinations.

Holdigng caps-lock + cmd/alt and pressing `p` is not detected by xev, while `n` (and most other keys) is.

I have my X set to the keyboard model Logitech (generic), have tried a few different setting, seems to make no difference in regards to dead key combinations...

**Comment by pfps** [comment]
I don't think this is something that solaar has any control over.  It looks more like a problem with the Linux input driver's handling of the key events generated by the keyboard.

**Comment by FFY00** [comment]
Can you run it through evemu instead of xev? xev shows what comes out after X is done with the device.

```
sudo evemu-record
```

**Comment by pfps** [comment]
Closing due to no response from submitter.
