### ISSUE TITLE
Error launching solaar 0.9.2 opensuse

### ISSUE THREAD

**Issue by m47ik** [pwr-Solaar/Solaar#511]
Solaar application failed to launch with error.

solaar: error: GObject.__init__() takes exactly 0 arguments (4 given)
solar version : solaar 0.9.2
OS:
name="openSUSE Tumbleweed"
VERSION="20190314"
ID="opensuse-tumbleweed"
VERSION_ID="20190314"
Desktop : KDE
Python versions installed: 2.7,3.6,3.7

**Comment by Lekensteyn** [comment]
Could yoi retry it with the latest release? Thanks!

**Comment by Cerule** [comment]
Works for me
solaar-1.0.1-1.1.noarch
OS:
Description:    openSUSE Tumbleweed
Release:        20190824
python3-3.7.3-1.2.x86_64
python-2.7.16-3.1.x86_64
