### ISSUE TITLE
M560 Always show battery: 70% (invalid battery)

### ISSUE THREAD

**Issue by priv** [pwr-Solaar/Solaar#512]
Ubuntu 18.10 prebuilt package from "apt install solaar"

I have two M560 and changed battery to verify the results.  I don't think there's any problem with the battery.  It shows "good" on windows, and I think it worked fine on 18.04.

So please help check what's wrong with the status.

hipp_battery uevent:
```
alvin@alvin-BM1AF:/sys/class/power_supply/hidpp_battery_5$ cat /sys/class/power_supply/hidpp_battery_5/uevent 
POWER_SUPPLY_NAME=hidpp_battery_5
POWER_SUPPLY_ONLINE=1
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_SCOPE=Device
POWER_SUPPLY_MODEL_NAME=Wireless Mouse M560
POWER_SUPPLY_MANUFACTURER=Logitech
POWER_SUPPLY_SERIAL_NUMBER=402d-e4-3c-53-0a
POWER_SUPPLY_CAPACITY_LEVEL=Normal

```
Also attach solaar -dd messages.
[debug.txt](https://github.com/pwr/Solaar/files/2986355/debug.txt)

**Comment by doctor64** [comment]
Can you please provide output of solaar -dd? Must be fixed with PR#476

**Comment by doctor64** [comment]
Should be fixed with PR#476

**Comment by BlackZork** [comment]
I have the same issue, version 1.0.1 built from sources on Arch Linux.
M310 mouse.

**Comment by pfps** [comment]
Please update to Solaar from this repository and provide output from `solaar show`

**Comment by pfps** [comment]
Closing due to no response from submitter.
