### ISSUE TITLE
HOWTO build from source on 18.04?

### ISSUE THREAD

**Issue by cement-head** [pwr-Solaar/Solaar#513]
Hi,

  I'd like to build solaar from source for 18.04, and I'm using Unity 7.  When I run the build script I get the following:

> $ ./build_deb.sh 
> /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
>   warnings.warn(msg)
> /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
>   warnings.warn(msg)
> /home/andor/Downloads/Solaar-master/po/zh_TW.po:7: nplurals = 1...
> /home/andor/Downloads/Solaar-master/po/zh_TW.po:203: ...but some messages have 2 plural forms
> /usr/bin/msgfmt: found 1 fatal error

What am I doing wrong?

**Comment by cement-head** [comment]
Um, don't understand what that meant/means - should I re-pull and try again?

**Comment by cement-head** [comment]
Hi,

  What am I doing incorrectly to build from source?  Can someone PLEASE give me some instructions?

Thanks!

**Comment by compuguy** [comment]
@cement-head Up until 18.04, I was able to build Debian packages with minor tweaks. With 18.04, I'm getting the same error as you are.

**Comment by Rknegt** [comment]
I got it runnig when changing Solaar/setup.py Line 4, from :

`from distutils.core import setup`

To:

`from from setuptools import setup`
