### ISSUE TITLE
K780 and prev/next keys

### ISSUE THREAD

**Issue by pprw** [pwr-Solaar/Solaar#522]
I am not 100% this is the correct place to report this (sorry if it is not).

I have a new K780 keyboard. The multimedia keys "prev" and "next" are not working not matter to what I bind them (mpc next/prev, quodlibet --next/previous, firefox, etc). Sometimes, when I reboot, next/prev are working and play-pause doesn't.

I have the same keyboard but older for another computer. Everything works with this one.

The new keyboard has firmware 001.005.00029 when older has  001.004.00028 version.

I am running Debian Sid with 4.19.0-4-amd64 kernel.

I tried Solaar Debian version and also the git master one. With the git version, I can change the Fn keys behavior (nice!) but my bug stays the same.

**Comment by FFY00** [comment]
Can you run `xev -event keyboard` to see what key events are being actually sent to the computer?

**Comment by pprw** [comment]
Here is what I obtain when pressing prev/next/toggle keys:

```
KeymapNotify event, serial 29, synthetic NO, window 0x0,
    keys:  1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeymapNotify event, serial 29, synthetic NO, window 0x0,
    keys:  1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeymapNotify event, serial 29, synthetic NO, window 0x0,
    keys:  1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeymapNotify event, serial 29, synthetic NO, window 0x0,
    keys:  1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

```

**Comment by pfps** [comment]
That indicates that the keypresses are being grabbed by something.  So it is that something that needs to be changed somehow.  
As an example that's what I see for the volume up and down keys on my keypad, which are wired up to run a special command. My window manager is XFCE and I have Keyboard Application Shortcuts that run pulsaudio commands when these keys are pressed.
Different window managers have different methods for showing and setting these commands.  You will have to figure out how to set this up for your window manager.

So not a problem for Solaar, as far as I can determine.
