### ISSUE TITLE
Mostly does not detect new style reciever?

### ISSUE THREAD

**Issue by forteller** [pwr-Solaar/Solaar#524]
Thank you for an amazing application! It's a real life saver. I'm truly thankful to everyone involved!

I have a strange bug to report. I didn't think it was very strange until just now. Let me explain:

I've used Solaar with two types of recievers:
![proxy duckduckgo com](https://user-images.githubusercontent.com/343561/57162968-26ad9700-6df0-11e9-9256-2c36175b358e.jpeg)
The one on the top right I've used the most. More than five different ones, and I've never had any issues except when I also have the same issue with Logitechs official software on Windows (so probably hardware failure).

The one on the bottom left I've only tried two of, and both have almost never worked. One of them might have not worked with the Logitech software either (I'll have to wait til I'm back at the office to check), so let's concentrate on the other.

The other I just got when buying a new M705 a few days ago. The official Logitech software has no problem detecting it, but no matter how many times I restart Solaar, it does not detect it. Or so I thought until now. While writing this bug report Solaar was running in the background and I opend it from the tray. To my bewilderment it actually showed the reciever, and I was able to add a keyboard and a mouse. The instant I had added the mouse, though, it dissappeard again. When I closed the window confirming the pairing Solaar was again blank, like it's always been when I use this reciever:

![Screenshot from 2019-05-03 22-24-12](https://user-images.githubusercontent.com/343561/57163700-34641c00-6df2-11e9-9d20-13c876c8c2f1.png)

But the paired devices still works.

I don't know anything about coding, but this seems a bit strange to me :) I really hope this info helps, so that you might be able to fix the issue. Here's my debug, let me know if there's anything else I can do to help. Thanks again!

`$ solaar -d
/usr/share/solaar/lib/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
22:06:36,143     INFO [MainThread] root: language en_US (UTF-8), translations path None
22:06:36,186     INFO [MainThread] solaar.ui: application /io/github/pwr/solaar, registered True
/usr/share/solaar/lib/solaar/ui/notify.py:33: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
22:06:36,241     INFO [MainThread] solaar.ui.tray: using StatusIcon
22:06:36,242     INFO [MainThread] solaar.ui.notify: starting desktop notifications
22:06:36,298     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
22:06:36,301     INFO [MainThread] solaar.listener: starting receiver listening threads
22:06:36,304     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path=u'/dev/hidraw1', vendor_id=u'046d', product_id=u'c52b', serial=u'', release='1209', manufacturer='Logitech', product='USB Receiver', interface=2, driver=u'logitech-djreceiver')
22:06:36,308     INFO [ReceiverListener:hidraw1] logitech_receiver.listener: started with <UnifyingReceiver(/dev/hidraw1,12)> (12)
22:06:36,309     INFO [ReceiverListener:hidraw1] solaar.listener: <UnifyingReceiver(/dev/hidraw1,12)>: notifications listener has started (12)
22:06:36,312     INFO [ReceiverListener:hidraw1] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,12)>: receiver notifications enabled => ('wireless', 'software present')
22:06:36,318     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw1,12)>: present, No paired devices. (0) 
22:06:36,320     INFO [ReceiverListener:hidraw1] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,12)>: found new device 1 (406D)
22:06:36,320     INFO [ReceiverListener:hidraw1] solaar.listener: Notification(1,41,04,526D40) triggered new device <PairedDevice(1,406D,M705)> (mouse)
22:06:36,323     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw1,12)>: present, 1 paired device. (0) 
22:06:36,323     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <PairedDevice(1,406D,M705)>: paired offline,  (0) 
22:06:36,326     INFO [ReceiverListener:hidraw1] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,12)>: found new device 2 (2011)
22:06:36,326     INFO [ReceiverListener:hidraw1] solaar.listener: Notification(2,41,04,711120) triggered new device <PairedDevice(2,2011,K520)> (keyboard)
22:06:36,330     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw1,12)>: present, 2 paired devices. (0) 
22:06:36,331     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <PairedDevice(2,2011,K520)>: paired offline,  (0) 
22:09:56,503     INFO [ReceiverListener:hidraw1] logitech_receiver.notifications: <UnifyingReceiver(/dev/hidraw1,12)>: pairing lock is open
22:09:56,503     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw1,12)>: present, 2 paired devices. (1) pairing lock is open
22:09:58,454     INFO [ReceiverListener:hidraw1] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,12)>: found new device 3 (4004)
22:09:58,454     INFO [ReceiverListener:hidraw1] solaar.listener: Notification(3,41,04,710440) triggered new device <PairedDevice(3,4004,K360)> (keyboard)
22:09:58,468     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw1,12)>: present, 3 paired devices. (0) 
22:09:58,469     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <PairedDevice(3,4004,K360)>: paired offline,  (0) 
22:09:58,470     INFO [ReceiverListener:hidraw1] solaar.listener: <UnifyingReceiver(/dev/hidraw1,12)>: pairing detected new device
22:09:58,471  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,42,01,0000000000000000000000)
22:09:58,471  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: 1: connection notification with unknown protocol 01: Notification(1,41,01,6D40040000000000000000)
22:09:58,471  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: 2: connection notification with unknown protocol 01: Notification(2,41,01,11201A4000000000000000)
22:09:58,471  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: 3: connection notification with unknown protocol 01: Notification(3,41,01,04401A4000000000000000)
22:09:58,471    ERROR [ReceiverListener:hidraw1] logitech_receiver.listener: processing Notification(0,41,02,0000000000000000000000)
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/usr/share/solaar/lib/solaar/listener.py", line 184, in _notifications_handler
    assert n.devnumber > 0 and n.devnumber <= self.receiver.max_devices
AssertionError
22:09:58,474     INFO [ReceiverListener:hidraw1] logitech_receiver.notifications: <UnifyingReceiver(/dev/hidraw1,12)>: pairing lock is closed
22:09:58,474     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw1,12)>: present, 3 paired devices. (1) pairing lock is closed
22:09:58,477     INFO [ReceiverListener:hidraw1] solaar.configuration: saved {u'4055:B5C9DC70': {u'_name': u'Unknown device 4055'}, u'2011:27737C8D': {u'_name': u'K520'}, u'4002:394EC6D1': {u'fn-swap': False, u'_name': u'Wireless Solar Keyboard K750'}, u'2011:2379CDF6': {u'_name': u'K520'}, u'101B:633D3EAA': {u'side-scroll': True, u'smooth-scroll': False, u'_name': u'Marathon Mouse M705'}, u'_version': u'0.9.2', u'2011:018873C3': {u'_name': u'K520'}, u'2011:428F56A2': {u'_name': u'K520'}, u'406D:7CDF8FA1': {u'_name': u'Marathon Mouse M705'}, u'101B:67048533': {u'side-scroll': True, u'smooth-scroll': False, u'_name': u'Marathon Mouse M705'}, u'4008:03E8C0B4': {u'_name': u'Wireless Mouse M185'}, u'4055:521D9828': {u'_name': u'Wireless Mouse'}, u'4004:D1282823': {u'fn-swap': False, u'_name': u'Wireless Keyboard K360'}, u'4008:E97B4490': {u'_name': u'Wireless Mouse M185'}} to /home/artig/.config/solaar/config.json
22:09:58,782     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <PairedDevice(3,4004,K360)>: paired online, Battery: 90% (discharging) (0) 
22:09:58,783     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <PairedDevice(3,4004,K360)>: paired online, Battery: 90% (discharging) (0) 
22:09:58,784  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,42,00,0000000000000000000000)
22:09:58,822     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <PairedDevice(3,4004,K360)>: paired online, Battery: 90% (discharging) (1) powered on
22:09:58,823     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <PairedDevice(3,4004,K360)>: paired online, Battery: 90% (0) 
22:10:01,340  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,2A00000000000000000000) for feature FEATURE SET (index 01)
22:10:01,768  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,2A49000000000000000000) for feature FEATURE SET (index 01)
22:10:01,788  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,2A492E0000000000000000) for feature FEATURE SET (index 01)
22:10:01,828  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,2A492E4500000000000000) for feature FEATURE SET (index 01)
22:10:01,848  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,492E450000000000000000) for feature FEATURE SET (index 01)
22:10:01,868  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,4945000000000000000000) for feature FEATURE SET (index 01)
22:10:01,910  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,4900000000000000000000) for feature FEATURE SET (index 01)
22:10:02,234  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,492A000000000000000000) for feature FEATURE SET (index 01)
22:10:02,356  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,2A00000000000000000000) for feature FEATURE SET (index 01)
22:10:02,480  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,0000000000000000000000) for feature FEATURE SET (index 01)
22:10:02,620  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,4900000000000000000000) for feature FEATURE SET (index 01)
22:10:02,738  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,0000000000000000000000) for feature FEATURE SET (index 01)
22:10:05,960  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unknown BATTERY Notification(3,04,10,0400E003000000000000000000000000)
22:10:06,684  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unknown BATTERY Notification(3,04,10,0400E003000000000000000000000000)
22:10:06,784  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,0000000000000000000000) for feature FEATURE SET (index 01)
22:10:07,518  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,0000000000000000000000) for feature FEATURE SET (index 01)
22:10:09,836  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,2900000000000000000000) for feature FEATURE SET (index 01)
22:10:09,936  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,01,00,0000000000000000000000) for feature FEATURE SET (index 01)
22:10:15,396     INFO [ReceiverListener:hidraw1] logitech_receiver.notifications: <UnifyingReceiver(/dev/hidraw1,12)>: pairing lock is open
22:10:15,396     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw1,12)>: present, 3 paired devices. (1) pairing lock is open
22:10:20,375     INFO [ReceiverListener:hidraw1] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw1,12)>: found new device 4 (101B)
22:10:20,375     INFO [ReceiverListener:hidraw1] solaar.listener: Notification(4,41,04,521B10) triggered new device <PairedDevice(4,101B,M705)> (mouse)
22:10:20,391     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw1,12)>: present, 4 paired devices. (0) 
22:10:20,391     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <PairedDevice(4,101B,M705)>: paired offline,  (0) 
22:10:20,392     INFO [ReceiverListener:hidraw1] solaar.listener: <UnifyingReceiver(/dev/hidraw1,12)>: pairing detected new device
22:10:20,392  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(4,101B,M705)>: unrecognized Notification(4,42,01,0000000000000000000000)
22:10:20,393  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: 1: connection notification with unknown protocol 01: Notification(1,41,01,6D40040000000000000000)
22:10:20,393  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: 2: connection notification with unknown protocol 01: Notification(2,41,01,11201A4000000000000000)
22:10:20,393  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: 3: connection notification with unknown protocol 01: Notification(3,41,01,04401A4000000000000000)
22:10:20,393  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: 4: connection notification with unknown protocol 01: Notification(4,41,01,1B10040000000000000000)
22:10:20,394    ERROR [ReceiverListener:hidraw1] logitech_receiver.listener: processing Notification(0,41,02,0000000000000000000000)
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/usr/share/solaar/lib/solaar/listener.py", line 184, in _notifications_handler
    assert n.devnumber > 0 and n.devnumber <= self.receiver.max_devices
AssertionError
22:10:20,395     INFO [ReceiverListener:hidraw1] logitech_receiver.notifications: <UnifyingReceiver(/dev/hidraw1,12)>: pairing lock is closed
22:10:20,395     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw1,12)>: present, 4 paired devices. (1) pairing lock is closed
22:10:20,611     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <PairedDevice(3,4004,K360)>: paired online, Battery: 90% (0) 
22:10:20,613  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: <PairedDevice(3,4004,K360)>: unrecognized Notification(3,42,00,0000000000000000000000)
22:10:21,593    ERROR [ReceiverListener:hidraw1] logitech_receiver.base: write failed, assuming handle 12 no longer available
22:10:21,593    ERROR [ReceiverListener:hidraw1] logitech_receiver.listener: processing Notification(4,41,04,921B10)
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/usr/share/solaar/lib/solaar/listener.py", line 207, in _notifications_handler
    _notifications.process(dev, n)
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 54, in process
    return _process_device_notification(device, status, notification)
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 97, in _process_device_notification
    return _process_hidpp10_notification(device, status, n)
  File "/usr/share/solaar/lib/logitech_receiver/notifications.py", line 174, in _process_hidpp10_notification
    status.changed(active=link_established)
  File "/usr/share/solaar/lib/logitech_receiver/status.py", line 255, in changed
    self[KEYS.NOTIFICATION_FLAGS] = d.enable_notifications()
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 270, in enable_notifications
    ok = _hidpp10.set_notification_flags(self, set_flag_bits)
  File "/usr/share/solaar/lib/logitech_receiver/hidpp10.py", line 328, in set_notification_flags
    result = write_register(device, REGISTERS.notifications, _int2bytes(flag_bits, 3))
  File "/usr/share/solaar/lib/logitech_receiver/hidpp10.py", line 149, in write_register
    return device.request(request_id, *value)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 281, in request
    return _base.request(self.receiver.handle, self.number, request_id, *params)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 340, in request
    write(ihandle, devnumber, request_data)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 171, in write
    raise NoReceiver(reason=reason)
NoReceiver: {'reason': OSError(32, 'Broken pipe')}
22:10:21,597    ERROR [ReceiverListener:hidraw1] logitech_receiver.base: read failed, assuming handle 12 no longer available
22:10:21,597  WARNING [ReceiverListener:hidraw1] logitech_receiver.listener: receiver disconnected
22:10:21,598     INFO [ReceiverListener:hidraw1] solaar.listener: <UnifyingReceiver(/dev/hidraw1,12)>: notifications listener has stopped
Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/ui/pair_window.py", line 120, in _finish
    receiver.status.new_device = None
AttributeError: 'unicode' object has no attribute 'new_device'`

**Comment by FFY00** [comment]
It looks like Solaar's GUI is throwing an error. Can you try `solaar show` from the terminal?

**Comment by forteller** [comment]
> $ solaar show
/usr/share/solaar/lib/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
usage: solaar [-h] [-d] [-V]
solaar: error: unrecognized arguments: show

**Comment by FFY00** [comment]
Oh sorry, I missed that. Which version are you running? That seems severally outdated. If you don't want to update you can try `solaar-cli show`.

**Comment by forteller** [comment]
Thanks for trying to help me! :)

I'm running 0.9.2, which seems to be the latest version?

**Comment by forteller** [comment]
> $ solaar-cli show
Unifying Receiver [/dev/hidraw1:5B6697E5] with 5 devices
1: Marathon Mouse M705 [M705:7CDF8FA1] offline
2: K520 [K520:018873C3] offline
3: Wireless Keyboard K360 [K360:D1282823] 
4: Marathon Mouse M705 [M705:67048533] 
5: K520 [K520:2379CDF6] offline

BTW: That last K520 I tried to pair earlier today, and I only got an error message I haven't seen before. And it did not work. I just tried it again now that I saw it on the list, and now it works, without me doing anything new to get it to work!

**Comment by FFY00** [comment]
Yeah, the latest version is from 2013 😅.

**Comment by forteller** [comment]
It is, right? I'm not missing anything here? Is there any chance these issues will be fixed?

**Comment by FFY00** [comment]
Yes, once we migrate to a new repo (since @pwr has been inactive since 2013) a new release should created.

**Comment by fcastilloec** [comment]
I'm running solaar from git and I have the same errors:
```
ERROR [ReceiverListener:hidraw0] logitech_receiver.listener: processing Notification(1,02,00,0004E0FF00005B00000000)
Traceback (most recent call last):
  File "/home/felipe/.git_apps/Solaar/lib/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/home/felipe/.git_apps/Solaar/lib/solaar/listener.py", line 219, in _notifications_handler
    assert dev.status is not None
AttributeError: 'PairedDevice' object has no attribute 'status'
```
 Here's the output to `solaar show`:
```
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 4C479646
    Firmware   : 24.07.B0030
    Bootloader : 02.09
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=233

  1: MX Vertical Advanced Ergonomic Mouse
     Codename     : MX Vertical
     Kind         : mouse
     Wireless PID : 407B
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 50173AE6
        Bootloader: BOT 78.00.B0009
          Firmware: MPM 16.00.B0009
             Other: 
     Supports 34 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: unknown:0021           {0021}   
         7: unknown:0007           {0007}   
         8: BATTERY STATUS         {1000}   
         9: unknown:1002           {1002}   
        10: REPROG CONTROLS V4     {1B04}   
        11: unknown:1C00           {1C00}   
        12: CHANGE HOST            {1814}   
        13: unknown:1815           {1815}   
        14: unknown:2250           {2250}   
        15: unknown:18B1           {18B1}   internal, hidden
        16: VERTICAL SCROLLING     {2100}   
            Roller type: standard
            Ratchet per turn: 24
            Scroll lines: 0
        17: LOWRES WHEEL           {2130}   
            Wheel Reports: HID
        18: ADJUSTABLE DPI         {2201}   
        19: unknown:1802           {1802}   internal, hidden
        20: unknown:1803           {1803}   internal, hidden
        21: unknown:1806           {1806}   internal, hidden
        22: unknown:1813           {1813}   internal, hidden
        23: unknown:1805           {1805}   internal, hidden
        24: unknown:1830           {1830}   internal, hidden
        25: unknown:1890           {1890}   internal, hidden
        26: unknown:1891           {1891}   internal, hidden
        27: unknown:18A1           {18A1}   internal, hidden
        28: unknown:1DF3           {1DF3}   internal, hidden
        29: unknown:1E00           {1E00}   hidden
        30: unknown:1EB0           {1EB0}   internal, hidden
        31: unknown:1E22           {1E22}   internal, hidden
        32: unknown:1861           {1861}   internal, hidden
        33: unknown:18C0           {18C0}   internal, hidden
     Has 7 reprogrammable keys:
         0: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
             mse, reprogrammable, pos:0, group:1, gmask:1
         1: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
             mse, reprogrammable, pos:0, group:1, gmask:1
         2: MIDDLE BUTTON             , default: MiddleMouseButton           => MIDDLE BUTTON             
             divertable, mse, persistently divertable, reprogrammable, pos:0, group:2, gmask:3
         3: BACK AS BUTTON 4          , default: BackEx                      => BACK AS BUTTON 4          
             divertable, mse, persistently divertable, reprogrammable, pos:0, group:2, gmask:3
         4: FORWARD AS BUTTON 5       , default: BrowserForwardEx            => FORWARD AS BUTTON 5       
             divertable, mse, persistently divertable, reprogrammable, pos:0, group:2, gmask:3
         5: unknown:00FD              , default: unknown:00D2                => unknown:00FD              
             divertable, mse, persistently divertable, reprogrammable, pos:0, group:2, gmask:3
         6: unknown:00D7              , default: unknown:00B4                => unknown:00D7              
             divertable, virtual, pos:0, group:3, gmask:0
     Battery: 20%, discharging.
```

**Comment by FFY00** [comment]
Could you try with the latest release?

**Comment by fcastilloec** [comment]
I tried v1.0.1 from git and I still can't start Solaar. Here's the output when running `solaar -d`:

```
10:55:39,645     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
10:55:39,696     INFO [MainThread] solaar.listener: starting receiver listening threads
10:55:39,697     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path=u'/dev/hidraw2', vendor_id=u'046d', product_id=u'c52b', serial=u'', release='2407', manufacturer='Logitech', product='USB Receiver', interface=2, driver=u'logitech-djreceiver')
10:55:39,701     INFO [ReceiverListener:hidraw2] logitech_receiver.listener: started with <UnifyingReceiver(/dev/hidraw2,13)> (13)
10:55:39,701     INFO [ReceiverListener:hidraw2] solaar.listener: <UnifyingReceiver(/dev/hidraw2,13)>: notifications listener has started (13)
10:55:39,705     INFO [ReceiverListener:hidraw2] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw2,13)>: receiver notifications enabled => ('wireless', 'software present')
10:55:39,709     INFO [ReceiverListener:hidraw2] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw2,13)>: present, No paired devices. (0) 
10:55:39,711     INFO [ReceiverListener:hidraw2] logitech_receiver.receiver: <UnifyingReceiver(/dev/hidraw2,13)>: found new device 1 (407B)
10:55:39,711     INFO [ReceiverListener:hidraw2] solaar.listener: Notification(1,41,04,327B40) triggered new device <PairedDevice(1,407B,MX Vertical)> (mouse)
10:55:39,941    ERROR [ReceiverListener:hidraw2] logitech_receiver.listener: processing Notification(1,41,04,327B40)
Traceback (most recent call last):
  File "/home/felipe/.git_apps/Solaar/lib/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/home/felipe/.git_apps/Solaar/lib/solaar/listener.py", line 213, in _notifications_handler
    configuration.attach_to(dev)
  File "/home/felipe/.git_apps/Solaar/lib/solaar/configuration.py", line 130, in attach_to
    for s in device.settings:
  File "/home/felipe/.git_apps/Solaar/lib/logitech_receiver/receiver.py", line 254, in settings
    _check_feature_settings(self, self._settings)
  File "/home/felipe/.git_apps/Solaar/lib/logitech_receiver/settings_templates.py", line 385, in check_feature_settings
    check_feature(_LOW_RES_SCROLL[0], _F.LOWRES_WHEEL)
  File "/home/felipe/.git_apps/Solaar/lib/logitech_receiver/settings_templates.py", line 381, in check_feature
    feature = getattr(FeatureSettings, field_name)()
AttributeError: '_SETTINGS_LIST' object has no attribute 'low_res_scroll'
10:55:39,942    ERROR [ReceiverListener:hidraw2] logitech_receiver.listener: processing Notification(1,08,00,32140000000000000000000000000000)
Traceback (most recent call last):
  File "/home/felipe/.git_apps/Solaar/lib/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/home/felipe/.git_apps/Solaar/lib/solaar/listener.py", line 219, in _notifications_handler
    assert dev.status is not None
AttributeError: 'PairedDevice' object has no attribute 'status'
10:55:39,942    ERROR [ReceiverListener:hidraw2] logitech_receiver.listener: processing Notification(1,08,10,0404C096050000000000000000000000)
Traceback (most recent call last):
  File "/home/felipe/.git_apps/Solaar/lib/logitech_receiver/listener.py", line 185, in run
    self._notifications_callback(n)
  File "/home/felipe/.git_apps/Solaar/lib/solaar/listener.py", line 219, in _notifications_handler
    assert dev.status is not None
AttributeError: 'PairedDevice' object has no attribute 'status'
```

**Comment by FFY00** [comment]
I will check this on monday.

**Comment by pfps** [comment]
@fcastilloec Sorry for the long delay in responding.  There have been some changes to Solaar over the last few months so if possible could you clone solaar from this repository and try with bin/solaar from the download directory?

**Comment by fcastilloec** [comment]
@pfps I've been following the changes on this repo, and I've switched to your Solaar git PPA. Everything is working fine now. Thanks!

**Comment by pfps** [comment]
OK, if @forteller has the same experience, this issue can be closed.

**Comment by pfps** [comment]
Closing due to no response from original poster.

**Comment by forteller** [comment]
Sorry, I didn't get the chance to test before now. It now works, so thank you so much for your work! <3
