### ISSUE TITLE
Mouse settings are missing (MX MASTER 2)

### ISSUE THREAD

**Issue by hoemon** [pwr-Solaar/Solaar#526]
I've installed solar using `sudo apt install solar` however the mouse settings on the interface are missing. The only option is, unpair.

Is there any fix for this? I've cheked releases page but looks like the last release was at 2013..

**Comment by alfonsoler** [comment]
You should read the past issues, since everybody have had this problem. A quick search will give you the answer (although probably not a definitive solution)

**Comment by hoemon** [comment]
Already commented on past issues - then realized, making a new one is maybe better.

**Comment by alfonsoler** [comment]
good luck! It looks that you tried already everything possible.

**Comment by hoemon** [comment]
:woman_facepalming:

**Comment by hoemon** [comment]
For future reference:

I solved the issue by recompiling after replacing some parts with an earlier release. As far as I can see from past issues in this repo, there is no similar answer (maybe other solutions worked for other people? Not sure.).

As it's too long to write every step here, if anyone wants to know the details feel free to contact.

**Comment by Rombusevil** [comment]
Hey @hoemon I'm having this issue. Would you mind sharing some details?

**Comment by Rombusevil** [comment]
Oh just removing the repos version and running the git version is enough to get some more options

**Comment by rockerbacon** [comment]
@hoemon I'm looking for a solution to this as well. If there's too much stuff which needs to be done maybe put them somewhere else and just link here.

**Comment by KindarConrath** [comment]
If a bunch of people are having these issues, maybe someone should write a short "this is how to build from master" tutorial. I'd do it, but sadly, I'm not that skilled at Linux stuff. (As I came here for a similar reason. (MX Master 2 settings in Ubuntu) I tried to build it myself, but I can't figure out how :P (I'm running 18.04 LTS)

**Comment by barolo** [comment]
@KindarConrath 
If someone still needs this.
Download latest release, extract and in extracted folder:
```
python ./setup.py build
sudo python ./setup install
```

go to rules.d folder and do:
```
sudo ./install.sh
```

Done

**Comment by KindarConrath** [comment]
TY, TY that worked almost flawlessly! You have a single mistake in your commands, but I realized it almost immediately when it wouldn't run.

sudo python ./setup install
should be
sudo python ./setup.py install

otherwise, working just fine now (though first run you do have to actually run solaar :P )

**Comment by pfps** [comment]
Is this still a problem?

**Comment by barolo** [comment]
@pfps Can't confirm it with 2S, all options are there

**Comment by pfps** [comment]
That sounds like things are now working for the 2S.
