### ISSUE TITLE
How can I view the date and time that a device was paired/unpaired?

### ISSUE THREAD

**Issue by jamieweb** [pwr-Solaar/Solaar#527]
I would like to see the exact date and time that a device was paired/unpaired. Is this logged anywhere within Solaar? I can't find a log in common locations, e.g. `/var/log/solaar.log`.

Using `solaar -d show` will show the exact time if I perform an pairing action right now, but it doesn't show historic actions.

Is there a way to find this information?

**Comment by Lekensteyn** [comment]
This information is not recorded by Solaar unless you have debug logs enabled. You could try querying your kernel logs. On recent kernels, you might see messages like this:
```
usb 1-3: new full-speed USB device number 6 using xhci_hcd
usb 1-3: New USB device found, idVendor=046d, idProduct=c534, bcdDevice=29.01
usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
usb 1-3: Product: USB Receiver
usb 1-3: Manufacturer: Logitech
input: Logitech USB Receiver as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/0003:046D:C534.0003/input/input78
hid-generic 0003:046D:C534.0003: input,hidraw0: USB HID v1.11 Keyboard [Logitech USB Receiver] on usb-0000:00:14.0-3/input0
input: Logitech USB Receiver Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.1/0003:046D:C534.0004/input/input79
input: Logitech USB Receiver Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.1/0003:046D:C534.0004/input/input80
input: Logitech USB Receiver System Control as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.1/0003:046D:C534.0004/input/input81
hid-generic 0003:046D:C534.0004: input,hiddev0,hidraw1: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-0000:00:14.0-3/input1
```

Note that this points out when the receiver was connected, it does not point out when it was connected. For Unifying receivers, search for `hid-logitech` instead.

**Comment by pfps** [comment]
AFAICT solaar does not record this information.  It does not appear to be recorded in the HID++1.0 protocol.
