### ISSUE TITLE
Solaar 1.0.1 installation instructions

### ISSUE THREAD

**Issue by heynnema** [pwr-Solaar/Solaar#542]
The latest README.md and docs/installation.md, don't really show how to install Solaar. setup.py (which still shows version 0.9.2) doesn't appear like it'll do it.

Also, should I manually uninstall the original 0.9.2 first?

**Comment by jonas-jonas** [comment]
So, I'm not affiliated with the project, but had the same question. This is how it worked for me (Ubuntu 19.04):

- Clone the repository (`$ git clone git@github.com:pwr-Solaar/Solaar.git`) and change to it (`$ cd Solaar`)
- Run `setup.py` with the `--install` flag (`$ sudo ./setup.py --install`)
  - Note on `sudo`: You can also use the `--user` flag. This seems to install it to the current user's home directory, though I have not tested this.
- You _could_ run it now, but it will not open. To see what's wrong open a terminal and look at the system logs (`$ journalctl -f -n 300` - _This will show the last 300 lines of the system log and any new output will be shown directly, as long as the command is active_).
  - For me the package `python-pyudev` was missing - I installed it using `$ sudo apt install python-pyudev`. See [1].
- Restart/Logout & Login again to let Solaar access the Logitech receiver.
- Optionally add it to the autostarted apps of your system to run it on every login

[1]: 
```
Aug 02 12:20:33 jonasx390 solaar.desktop[2392]: Solaar: missing required package 'python-pyudev'
```

**Comment by barolo** [comment]
@jonas-jonas is it normal that it still builds 9.2 version?

**Comment by spartako** [comment]
Thanks Jonas.
In addition to installing `python-pydev`, I also had to run `rules.d/install.sh` as per the instructions [here](https://pwr-solaar.github.io/Solaar/installation) to make it work.

**Comment by FFY00** [comment]
Feel free to open a PR with this changes.

**Comment by pfps** [comment]
I've made some documentation changes that are waiting to be pulled.
https://github.com/pwr-Solaar/Solaar/pull/605
(Hopefully this pointer will cause notification of people watching this issue to be notified when the changes are pulled.)

**Comment by pfps** [comment]
Is this still a problem with the documentation changes from #605

**Comment by pfps** [comment]
Closing due to no response from original poster.
