### ISSUE TITLE
Unifying Receiver not recognized in Ubuntu 18.04

### ISSUE THREAD

**Issue by hemulin** [pwr-Solaar/Solaar#554]
Running on Ubuntu 18.04.3 (lubuntu but makes no difference in this regard)

While the M570 mouse dongle is recognized (`Bus 001 Device 011: ID 046d:c52b Logitech, Inc. Unifying Receiver`)

The MK270 dongle isn't (`Bus 001 Device 010: ID 046d:c534 Logitech, Inc. Unifying Receiver`)
`solaar-cli: error: Logitech receiver not found`

In addition, the M570 dongle is not able to pair with the keyboard of MK270 (`A new device was detected, but it is not compatible with this receiver`)

Any ideas how to solve that?

**Comment by lckarssen** [comment]
Which version of solaar are you using? I am using v1.0.1 (Ubuntu 19.10) and there it says that `solaar-cli` is deprecated and `solaar` should be used instead. Could you update to v1.0.1 and try again?

**Comment by pfps** [comment]
Solaar 1.0.1 recognizes the c534 receiver but doesn't do a good job of handling it. 

I suggest this bug be closed.

**Comment by hemulin** [comment]
@pfps 
Haven't verified but take your word for it.

Thanks for the update. Closing.
