### ISSUE TITLE
Solaar Crashes after keyboard input, after KVM switch

### ISSUE THREAD

**Issue by benhbell** [pwr-Solaar/Solaar#556]
I've got a KVM switch with a Logitech Unifying Receiver plugged in. 
The receiver has a KB800 and Performance MX mouse paired with it. 

Every time I KVM switch back to ubuntu, and type a key, Both devices become unresponsive. After 20secs or so, solaar restarts and everything works again. 

Solar version: 0.9.2
Ubuntu: 16.04

**Comment by pfps** [comment]
Version 0.9.2 is very old.
Please try with the version from this repo and report your experience.

**Comment by pfps** [comment]
Closing due to no response from original poster.
