### ISSUE TITLE
GTK Errors on startup in Kubuntu disco

### ISSUE THREAD

**Issue by Hapeck** [pwr-Solaar/Solaar#559]
When I start solaar with activated terminal output, I see the following error message:

```
/usr/share/solaar/lib/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
__import__(module)
(solaar:29501): Gtk-WARNING **: 16:28:42.307: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
(solaar:29501): Gtk-WARNING **: 16:28:42.307: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
(solaar:29501): Gtk-WARNING **: 16:28:42.308: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
/usr/share/solaar/lib/solaar/ui/notify.py:33: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
from gi.repository import Notify
/usr/share/solaar/lib/solaar/ui/tray.py:72: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that theright version gets loaded.
from gi.repository import AppIndicator3
```
uname -a
Linux rigel 5.0.0-27-generic #28-Ubuntu SMP Tue Aug 20 19:53:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Could this be a reason for occasional crash of the plasmashell?

**Comment by pfps** [comment]
Is this with version 0.9.2?  If so, please try downloading the current version from this repo and trying it.

**Comment by Hapeck** [comment]
No, it's 1.0.1+dfsg- (eoan) from the UBUNTU sources. The errors are no longer shown, but the GUI shows the count of 2 devices but only shows my keyboard while the solaar show command shows the information on both devices:

`solaar show
Unifying Receiver
Device path  : /dev/hidraw0
USB id       : 046d:c52b
Serial       : 9A1A9760
Firmware   : 12.00.B0017
Bootloader : 00.12
Has 2 paired device(s) out of a maximum of 6.
Notifications: wireless, software present (0x000900)
Device activity counters: 1=50, 3=64
1: Wireless Compact Keyboard K340
Codename     : K340
Kind         : keyboard
Wireless PID : 2007
Protocol     : HID++ 1.0
Polling rate : 20 ms (50Hz)
Serial number: 1DFDF9C2
Firmware: 12.00.B0032
Bootloader: 02.03
Other: 00.01
The power switch is located on the edge of top right corner.
Notifications: battery status (0x100000).
Battery: full, discharging.
3: MX Ergo Multi-Device Trackball 
Codename     : MX Ergo
Kind         : trackball
Wireless PID : 406F
Protocol     : HID++ 4.5
Polling rate : 8 ms (125Hz)
Serial number: C3126F35
Bootloader: BOT 49.00.B0001
Firmware: MPM 06.02.B0018
Other: 
The power switch is located on the base.
Supports 36 HID++ 2.0 features:
0: ROOT                   {0000}   
1: FEATURE SET            {0001}   
2: DEVICE FW VERSION      {0003}   
3: DEVICE NAME            {0005}   
4: WIRELESS DEVICE STATUS {1D4B}   
5: unknown:0007           {0007}   
6: RESET                  {0020}   
7: unknown:0021           {0021}   
8: BATTERY STATUS         {1000}   
9: LED CONTROL            {1300}   
10: REPROG CONTROLS V4     {1B04}   
11: unknown:1C00           {1C00}   
12: unknown:2006           {2006}   
13: POINTER SPEED          {2205}   
Pointer Speed: 1.0
14: VERTICAL SCROLLING     {2100}   
Roller type: standard
Ratchet per turn: 18
Scroll lines: 0
15: unknown:00C2           {00C2}   
16: unknown:1802           {1802}   internal, hidden
17: unknown:1803           {1803}   internal, hidden
18: unknown:1806           {1806}   internal, hidden
19: unknown:1805           {1805}   internal, hidden
20: unknown:1813           {1813}   internal, hidden
21: CHANGE HOST            {1814}   
22: unknown:1815           {1815}   
23: unknown:1830           {1830}   internal, hidden
24: unknown:1861           {1861}   internal, hidden
25: unknown:1890           {1890}   internal, hidden
26: unknown:1891           {1891}   internal, hidden
27: unknown:18A1           {18A1}   internal, hidden
28: unknown:1DF3           {1DF3}   internal, hidden
29: unknown:1E00           {1E00}   hidden
30: unknown:1EB0           {1EB0}   internal, hidden
31: unknown:18B1           {18B1}   internal, hidden
32: unknown:1850           {1850}   internal, hidden
33: unknown:1F03           {1F03}   internal, hidden
34: unknown:18C0           {18C0}   internal, hidden
35: LOWRES WHEEL           {2130}   
Wheel Reports: HID
Has 9 reprogrammable keys:
0: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
mse, reprogrammable, pos:0, group:1, gmask:1
1: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
mse, reprogrammable, pos:0, group:1, gmask:1
2: MIDDLE BUTTON             , default: MiddleMouseButton           => MIDDLE BUTTON             
divertable, mse, persistently divertable, reprogrammable, pos:0, group:2, gmask:3
3: BACK AS BUTTON 4          , default: BackEx                      => BACK AS BUTTON 4          
divertable, mse, persistently divertable, reprogrammable, pos:0, group:2, gmask:3
4: FORWARD AS BUTTON 5       , default: BrowserForwardEx            => FORWARD AS BUTTON 5       
divertable, mse, persistently divertable, reprogrammable, pos:0, group:2, gmask:3
5: unknown:00ED              , default: unknown:00C4                => unknown:00ED              
divertable, mse, persistently divertable, reprogrammable, pos:0, group:2, gmask:3
6: LEFT SCROLL AS AC PAN     , default: HorzScrollLeftSet           => LEFT SCROLL AS AC PAN     
divertable, mse, persistently divertable, reprogrammable, pos:0, group:2, gmask:3
7: RIGHT SCROLL AS AC PAN    , default: HorzScrollRightSet          => RIGHT SCROLL AS AC PAN    
divertable, mse, persistently divertable, reprogrammable, pos:0, group:2, gmask:3
8: unknown:00D7              , default: unknown:00B4                => unknown:00D7              
divertable, virtual, pos:0, group:3, gmask:0
Battery: 50%, discharging.
`

**Comment by pfps** [comment]
Weird.  Unfortunately I don't have a trackball so I can't see just what might be happening here. If you could attach a screenshot of the Solaar window that might help further investigation

**Comment by pfps** [comment]
If your trackball is still not showing up please provide a screenshot.  Also run `solaar -dd` and attach the output produced until the main Solaar window is stable.

**Comment by Hapeck** [comment]
Hello Michael,

thank you for your kind support. Please find attached screenshot and the 
requested debugging output.



Kind regards

Hans-Peter Eck

---
Eck-DV
Hans-Peter Eck

Neue Fruchtstr. 2
47057 Duisburg

Tel: 0203-3630602
Mobil: 0177-3081737
Fax: 0203-3630603

USt-IdNr.: DE238235309
-------------------------------------------------

Am 21.02.20 um 04:05 schrieb Peter F. Patel-Schneider:

**Comment by pfps** [comment]
It looks as if email attachments don't go through to github so you have to comment in the issue itself, I think.

**Comment by pfps** [comment]
Also, if  you have cloned Solaar from this repository update your cloned version.

**Comment by Hapeck** [comment]
Hello Michael,


thank you for yur support.

Npw I have reinstalled it from the solaar git ppa and it looks to be 
working fine.

**Comment by pfps** [comment]
OK, so I'm going to close this issue.
