### ISSUE TITLE
M215 pairing error 1: device timeout

### ISSUE THREAD

**Issue by jmeinke** [pwr-Solaar/Solaar#560]
Hey everyone,
my M215 behaves strangely in the last month. While being paired, sometimes the mouse pointer just does not move anymore while it was working perfectly well for 1 hour or more before. Now, I tried to unpair it and pair it again. However, unfortunately, pairing fails.

```
% solaar show
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 00000000
    Firmware   : 24.01.B0023
    Bootloader : 01.08
    Other      : AA.AC
  Has 0 paired device(s) out of a maximum of 0.
  Notifications: wireless, software present (0x000900)
  Device activity counters: (empty)
```
Please have a look at the `maximum of 0` devices that can be paired. This seems strange to me as it has the effect that the Solaar GUI disables the "Pair a new device" button for the receiver.

```
% solaar -d pair
20:28:58,890     INFO [MainThread] logitech_receiver.notifications: <NanoReceiver(/dev/hidraw0,3)>: pairing lock is open
Pairing: turn your new device on (timing out in 20 seconds).
20:29:04,904     INFO [MainThread] logitech_receiver.notifications: <NanoReceiver(/dev/hidraw0,3)>: pairing lock is closed
20:29:04,905  WARNING [MainThread] logitech_receiver.notifications: pairing error 1: device timeout
solaar: error: pairing failed: device timeout
```

**Comment by jmeinke** [comment]
Here's also the output of `ltunify` related commands:
```
% ltunify -d /dev/hidraw0 list                                                                                                                                                                                 
Devices count: 0
Connected devices:
```

```
% ltunify receiver-info
Serial number: 00000000
Firmware version: 024.001.00023
Bootloader version: BL.001.008
```

```
% ltunify pair
Please turn your wireless device off and on to start pairing.
Pairing result: Timeout (1)
```

Is my mouse broken?

**Comment by jmeinke** [comment]
Maybe related to #235

**Comment by Lekensteyn** [comment]
It could be either a software or hardware issue. Have you tried using the receiver with another computer? Could there be any wireless interference, for example a nearby microwave?

Has there been any hardware/software changes?

Sometimes I do notice the mouse being erratic, requiring shaking it for a few seconds before it works again. In that case I disable runtime power management (e.g. `sudo powertop`, then select the Logitech Unifying receiver, and press Enter to turn it into "bad"). "bad" means no power saving (about 1W), but it should keep the receiver more stable.

**Comment by pfps** [comment]
No response from submitter, so closing.

**Comment by Mxas** [comment]
Hello,

I have a very similar error with solaar-cli. After I turn-on mouse I get `solaar-cli: error: device timeout`

there is full debug output: 

`~$ solaar-cli -d pair
12:11:49,879    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 1 of <NanoReceiver(/dev/hidraw2,3)>
12:11:49,879    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 1, 'receiver': <NanoReceiver(/dev/hidraw2,3)>}
12:11:49,879  WARNING logitech_receiver.receiver: <NanoReceiver(/dev/hidraw2,3)>: looked for device 1, not found
12:11:49,883    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 2 of <NanoReceiver(/dev/hidraw2,3)>
12:11:49,883    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 2, 'receiver': <NanoReceiver(/dev/hidraw2,3)>}
12:11:49,883  WARNING logitech_receiver.receiver: <NanoReceiver(/dev/hidraw2,3)>: looked for device 2, not found
12:11:49,886    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 3 of <NanoReceiver(/dev/hidraw2,3)>
12:11:49,886    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 3, 'receiver': <NanoReceiver(/dev/hidraw2,3)>}
12:11:49,886  WARNING logitech_receiver.receiver: <NanoReceiver(/dev/hidraw2,3)>: looked for device 3, not found
12:11:49,890    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 4 of <NanoReceiver(/dev/hidraw2,3)>
12:11:49,890    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 4, 'receiver': <NanoReceiver(/dev/hidraw2,3)>}
12:11:49,891  WARNING logitech_receiver.receiver: <NanoReceiver(/dev/hidraw2,3)>: looked for device 4, not found
12:11:49,894    ERROR logitech_receiver.receiver: failed to read Nano wpid for device 5 of <NanoReceiver(/dev/hidraw2,3)>
12:11:49,894    ERROR logitech_receiver.receiver: register_new_device
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 409, in register_new_device
    dev = PairedDevice(self, number, notification)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 103, in __init__
    raise _base.NoSuchDevice(number=number, receiver=receiver, error="read Nano wpid")
NoSuchDevice: {'error': u'read Nano wpid', 'number': 5, 'receiver': <NanoReceiver(/dev/hidraw2,3)>}
12:11:49,895  WARNING logitech_receiver.receiver: <NanoReceiver(/dev/hidraw2,3)>: looked for device 5, not found
12:11:49,899     INFO logitech_receiver.notifications: <NanoReceiver(/dev/hidraw2,3)>: pairing lock is open
Pairing: turn your new device on (timing out in 20 seconds).
12:12:03,801     INFO logitech_receiver.notifications: <NanoReceiver(/dev/hidraw2,3)>: pairing lock is closed
12:12:03,801  WARNING logitech_receiver.notifications: pairing error 1: device timeout
solaar-cli: error: device timeout
`

**Comment by pfps** [comment]
Given that you are reporting output from solaar-cli it appears that you are running an old version of solaar.   Try running `solaar --version` or `solaar-cli --version`.   If the version reported is less than 1.0.1 please upgrade to a newer version of Solaar, ideally by cloning this repository and running Solaar from there.  For more details see https://pwr-solaar.github.io/Solaar/installation  
Because you have already installed and run Solaar, it is likely that you can just run `bin/solaar pair` from your clone of this repository.
