### ISSUE TITLE
Triathlon M720 not recognized

### ISSUE THREAD

**Issue by shalastra** [pwr-Solaar/Solaar#561]
Hey, I own Logitech triahlon M720. I see that you are supporting older version. Can you explain how to extend your project so I could be able to add this model?

**Comment by sodeon** [comment]
Try version 1.0.1. I've tested M720 on version 1.0.1 and works well.

**Comment by FFY00** [comment]
Same, my M720 works fine. Can you make sure you are running the latest version and test again?

**Comment by pfps** [comment]
@shalastra Are you having this problem in the current version?

**Comment by pfps** [comment]
Closing due to no response from the original submitter.
