### ISSUE TITLE
Missing usage documentation

### ISSUE THREAD

**Issue by digulla** [pwr-Solaar/Solaar#562]
I managed but I'd really like some basic usage instructions somewhere. How do I get started?

For Ubuntu, mention that you need to install `solaar-gnome3` or you won't see anything in the tray, too.

Give some examples how to use the CLI.

**Comment by Troyhy** [comment]
Ubuntu launcher -> solaar worked for me!

**Comment by FFY00** [comment]
```
solaar --help
```

**Comment by digulla** [comment]
With basic usage, I mean:

- Does it automatically find everything or do I need to do something?
- How do I add a device?
- How do I remove a device?
- What can I do when it says "No Logitec receiver found"? (Hit: Restart the software; for some reason, it sometimes forgets).

**Comment by pfps** [comment]
Is https://pwr-solaar.github.io/Solaar/ adequate?  If not, please suggest text to add.

**Comment by pfps** [comment]
Closing due to changes in documentation and no response from submitter.

**Comment by digulla** [comment]
Sorry for the long delay. Can you please add a series of screenshots and explanations how to pair and unpair a device?

It's probably obvious to you but for me, it feels like flying blind :-)

**Comment by pfps** [comment]
How about https://github.com/pfps/Solaar/blob/usage/docs/usage.md

**Comment by digulla** [comment]
Nice. Some comments:

"Here is an example of the Solaar icon": Which of the icons is the one from Solaar? Just add a red rectangle or gray the other icons out.

I've created a PR with some additional headlines to make it easier to find important info.

**Comment by pfps** [comment]
I don't see a PR for this yet.
If you are going to make a PR could you fix up the icon issue you mention above?

**Comment by pfps** [comment]
The PR you created is against my clone of Solaar.  Could you make a PR against this repository?

Also could you fix up the icon issue you mention above?

**Comment by pfps** [comment]
PR #796 adresses the "which icon" issue.
