### ISSUE TITLE
MX Master 3 Mouse pairing fails

### ISSUE THREAD

**Issue by henrikekblad** [pwr-Solaar/Solaar#563]
Just bought an MX master 3 mouse and MX keyboard. Each product contains an unified receiver. 

I would like to pair the mouse to the keyboard receiver. I'm starting the pairing process but it times out without finding the mouse.

Are there any steps I can take to tweak the software to make it recognized? 

Using the latest software cloned from github.

Plugging in the MX Keys unified receiver gives:
> Path         : /dev/hidraw2
> USB id       : 046d:c52b
> Serial       : C60EAD1B
>   Firmware   : 24.07.B0030
>   Bootloader : 02.09
>   Other      : AA.AC
> Notifications: wireless
>                software present
`

The Mx Master 3 mouse doesn't show up in Solaar UI when both unified receivers is plugged in:
![image](https://user-images.githubusercontent.com/5717075/65491123-bd1d4a80-deae-11e9-822a-3cf339375437.png)

> Unifying Receiver
>   Device path  : /dev/hidraw0
>   USB id       : 046d:c52b
>   Serial       : 4DFF96AB
>     Firmware   : 12.09.B0030
>     Bootloader : 04.16
>     Other      : AA.AA
>   Has 1 paired device(s) out of a maximum of 6.
>   Notifications: wireless, software present (0x000900)
>   Device activity counters: 1=59
> 
>   1: Wireless Mouse MX Master 3
>      Codename     : MX Master 3
>      Kind         : mouse
>      Wireless PID : 4082
>      Protocol     : HID++ 4.5
>      Polling rate : 8 ms (125Hz)
>      Serial number: 5CF2AB0E
>         Bootloader: BOT 95.00.B0013
>           Firmware: MPM 19.00.B0013
>              Other: 
>      The power switch is located on the base.
>      Supports 34 HID++ 2.0 features:
>          0: ROOT                   {0000}   
>          1: FEATURE SET            {0001}   
>          2: DEVICE FW VERSION      {0003}   
>          3: DEVICE NAME            {0005}   
>          4: WIRELESS DEVICE STATUS {1D4B}   
>          5: RESET                  {0020}   
>          6: unknown:0021           {0021}   
>          7: BATTERY STATUS         {1000}   
>          8: REPROG CONTROLS V4     {1B04}   
>          9: CHANGE HOST            {1814}   
>         10: unknown:2250           {2250}   
>         11: ADJUSTABLE DPI         {2201}   
>         12: SMART SHIFT            {2110}   
>         13: HIRES WHEEL            {2121}   
>             Multiplier: 15
>             Has invert
>               Normal wheel motion
>             Has ratchet switch
>               Free wheel mode
>             Low resolution mode
>             HID notification
>         14: unknown:2150           {2150}   
>         15: unknown:2251           {2251}   
>         16: unknown:00C2           {00C2}   
>         17: unknown:1802           {1802}   internal, hidden
>         18: unknown:1803           {1803}   internal, hidden
>         19: unknown:1806           {1806}   internal, hidden
>         20: unknown:1813           {1813}   internal, hidden
>         21: unknown:1805           {1805}   internal, hidden
>         22: unknown:1830           {1830}   internal, hidden
>         23: unknown:1890           {1890}   internal, hidden
>         24: unknown:1891           {1891}   internal, hidden
>         25: unknown:18A1           {18A1}   internal, hidden
>         26: unknown:1DF3           {1DF3}   internal, hidden
>         27: unknown:1E00           {1E00}   hidden
>         28: unknown:1EB0           {1EB0}   internal, hidden
>         29: unknown:1861           {1861}   internal, hidden
>         30: unknown:9001           {9001}   internal, hidden
>         31: unknown:9203           {9203}   internal, hidden
>         32: unknown:9205           {9205}   internal, hidden
>         33: unknown:9300           {9300}   internal, hidden
>      Has 8 reprogrammable keys:
>          0: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
>              mse, pos:0, group:1, gmask:1
>          1: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
>              mse, pos:0, group:1, gmask:1
>          2: MIDDLE BUTTON             , default: MiddleMouseButton           => MIDDLE BUTTON             
>              divertable, mse, reprogrammable, pos:0, group:3, gmask:7
>          3: BACK AS BUTTON 4          , default: BackEx                      => BACK AS BUTTON 4          
>              divertable, mse, reprogrammable, pos:0, group:2, gmask:3
>          4: FORWARD AS BUTTON 5       , default: BrowserForwardEx            => FORWARD AS BUTTON 5       
>              divertable, mse, reprogrammable, pos:0, group:2, gmask:3
>          5: unknown:00C3              , default: unknown:00A9                => unknown:00C3              
>              divertable, mse, reprogrammable, pos:0, group:3, gmask:7
>          6: unknown:00C4              , default: unknown:009D                => unknown:00C4              
>              divertable, mse, reprogrammable, pos:0, group:3, gmask:7
>          7: unknown:00D7              , default: unknown:00B4                => unknown:00D7              
>              divertable, virtual, pos:0, group:4, gmask:0
>      Battery: 100%, discharging.
> 
> Unifying Receiver
>   Device path  : /dev/hidraw3
>   USB id       : 046d:c52b
>   Serial       : C60EAD1B
>     Firmware   : 24.07.B0030
>     Bootloader : 02.09
>     Other      : AA.AC
>   Has 1 paired device(s) out of a maximum of 6.
>   Notifications: wireless, software present (0x000900)
>   Device activity counters: 1=129
> 
>   1: MX Keys Wireless Keyboard
>      Codename     : MX Keys
>      Kind         : keyboard
>      Wireless PID : 408A
>      Protocol     : HID++ 4.5
>      Polling rate : 20 ms (50Hz)
>      Serial number: 6ADC6CBE
>         Bootloader: BL1 08.00.B0011
>           Firmware: MPK 12.00.B0011
>              Other: 
>      The power switch is located on the edge of top right corner.
>      Supports 33 HID++ 2.0 features:
>          0: ROOT                   {0000}   
>          1: FEATURE SET            {0001}   
>          2: DEVICE FW VERSION      {0003}   
>          3: DEVICE NAME            {0005}   
>          4: WIRELESS DEVICE STATUS {1D4B}   
>          5: RESET                  {0020}   
>          6: unknown:0007           {0007}   
>          7: BATTERY STATUS         {1000}   
>          8: REPROG CONTROLS V4     {1B04}   
>          9: CHANGE HOST            {1814}   
>         10: unknown:1815           {1815}   
>         11: unknown:1982           {1982}   
>         12: K375S FN INVERSION     {40A3}   
>         13: ENCRYPTION             {4100}   
>         14: LOCK KEY STATE         {4220}   
>         15: KEYBOARD DISABLE       {4521}   
>         16: unknown:4531           {4531}   
>         17: unknown:00C2           {00C2}   
>         18: unknown:1802           {1802}   internal, hidden
>         19: unknown:1803           {1803}   internal, hidden
>         20: unknown:1806           {1806}   internal, hidden
>         21: unknown:1813           {1813}   internal, hidden
>         22: unknown:1805           {1805}   internal, hidden
>         23: unknown:1830           {1830}   internal, hidden
>         24: unknown:1890           {1890}   internal, hidden
>         25: unknown:1891           {1891}   internal, hidden
>         26: unknown:18A1           {18A1}   internal, hidden
>         27: unknown:1DF3           {1DF3}   internal, hidden
>         28: unknown:1E00           {1E00}   hidden
>         29: unknown:1EB0           {1EB0}   internal, hidden
>         30: unknown:1861           {1861}   internal, hidden
>         31: unknown:1A20           {1A20}   internal, hidden
>         32: unknown:18B0           {18B0}   internal, hidden
>      Has 24 reprogrammable keys:
>          0: unknown:00D1              , default: unknown:00AE                => unknown:00D1              
>              divertable, nonstandard, persistently divertable, pos:0, group:0, gmask:0
>          1: unknown:00D2              , default: unknown:00AF                => unknown:00D2              
>              divertable, nonstandard, persistently divertable, pos:0, group:0, gmask:0
>          2: unknown:00D3              , default: unknown:00B0                => unknown:00D3              
>              divertable, nonstandard, persistently divertable, pos:0, group:0, gmask:0
>          3: unknown:00C7              , default: unknown:00A3                => unknown:00C7              
>              divertable, is FN, FN sensitive, persistently divertable, reprogrammable, pos:1, group:0, gmask:0
>          4: unknown:00C8              , default: unknown:00A4                => unknown:00C8              
>              divertable, is FN, FN sensitive, persistently divertable, reprogrammable, pos:2, group:0, gmask:0
>          5: unknown:00E0              , default: unknown:00BF                => unknown:00E0              
>              divertable, is FN, FN sensitive, persistently divertable, reprogrammable, pos:3, group:0, gmask:0
>          6: unknown:00E1              , default: unknown:00C0                => unknown:00E1              
>              divertable, is FN, FN sensitive, persistently divertable, reprogrammable, pos:4, group:0, gmask:0
>          7: SHOW DESKTOP              , default: ShowDesktop                 => SHOW DESKTOP              
>              divertable, is FN, FN sensitive, persistently divertable, reprogrammable, pos:5, group:0, gmask:0
>          8: unknown:00E2              , default: unknown:00C1                => unknown:00E2              
>              divertable, is FN, FN sensitive, persistently divertable, reprogrammable, pos:6, group:0, gmask:0
>          9: unknown:00E3              , default: unknown:00C2                => unknown:00E3              
>              divertable, is FN, FN sensitive, persistently divertable, reprogrammable, pos:7, group:0, gmask:0
>         10: unknown:00E4              , default: Previous                    => unknown:00E4              
>              divertable, is FN, FN sensitive, persistently divertable, reprogrammable, pos:8, group:0, gmask:0
>         11: unknown:00E5              , default: Play/Pause                  => unknown:00E5              
>              divertable, is FN, FN sensitive, persistently divertable, reprogrammable, pos:9, group:0, gmask:0
>         12: unknown:00E6              , default: Next                        => unknown:00E6              
>              divertable, is FN, FN sensitive, persistently divertable, reprogrammable, pos:10, group:0, gmask:0
>         13: unknown:00E7              , default: Mute                        => unknown:00E7              
>              divertable, is FN, FN sensitive, persistently divertable, reprogrammable, pos:11, group:0, gmask:0
>         14: unknown:00E8              , default: Volume Down                 => unknown:00E8              
>              divertable, is FN, FN sensitive, persistently divertable, reprogrammable, pos:12, group:0, gmask:0
>         15: unknown:00E9              , default: Volume Up                   => unknown:00E9              
>              divertable, nonstandard, persistently divertable, reprogrammable, pos:0, group:0, gmask:0
>         16: Calculator                , default: Calculator                  => Calculator                
>              divertable, nonstandard, persistently divertable, reprogrammable, pos:0, group:0, gmask:0
>         17: unknown:00BF              , default: unknown:009B                => unknown:00BF              
>              divertable, nonstandard, persistently divertable, reprogrammable, pos:0, group:0, gmask:0
>         18: unknown:00EA              , default: unknown:00C3                => unknown:00EA              
>              divertable, nonstandard, persistently divertable, reprogrammable, pos:0, group:0, gmask:0
>         19: Lock PC                   , default: WindowsLock                 => Lock PC                   
>              divertable, nonstandard, persistently divertable, reprogrammable, pos:0, group:0, gmask:0
>         20: unknown:00EC              , default: unknown:00B8                => unknown:00EC              
>              divertable, nonstandard, persistently divertable, pos:0, group:0, gmask:0
>         21: unknown:00EB              , default: unknown:00B6                => unknown:00EB              
>              divertable, nonstandard, persistently divertable, pos:0, group:0, gmask:0
>         22: unknown:00DE              , default: Do Nothing One              => unknown:00DE              
>              is FN, pos:0, group:0, gmask:0
>         23: unknown:0034              , default: Do Nothing One              => unknown:0034              
>              nonstandard, pos:0, group:0, gmask:0
>      Battery: 100%, discharging.
>

**Comment by Frederick888** [comment]
I just tested it under Arch Linux and it worked just fine.

Not sure which distro/package you're using but try
```
udevadm control --reload
udevadm trigger
```
...and check whether the related `/dev/hidraw`s have the right permissions.

**Comment by arigit** [comment]
@Frederick888 are you able to configure DPI and smartshift of the Mx Master 3? also is solaar able to read the mx3 battery status?

**Comment by Frederick888** [comment]
@arigit Smart Shift configuration works for me. Battery status I'm not sure. I only charged my mouse once when I got it (so approx 2 weeks ago) and it's now still 100% in Solaar. But it's the same reading in my KDE Plasma system tray so I've got no choice but to believe it lol.

**Comment by FFY00** [comment]
How are you pairing the mouse? What is the distance from the receiver during pairing?

**Comment by pfps** [comment]
Closing due to no response from the original submitter.
