### ISSUE TITLE
MX Master - Unable to change DPI- and scroll wheel-settings

### ISSUE THREAD

**Issue by ErikSteiner** [pwr-Solaar/Solaar#565]
I am on Ubuntu 19.04 and installed Solaar from Software Center 0.9.2+dfsg-9.
If I open Solaar it shows my MX Master with left battery and that the Wireless Link is encrypted. That's all.

**Comment by alvgalrus** [comment]
Update to a newer version, 0.9.2 is outdated.

**Comment by ErikSteiner** [comment]
Thank you. I downloaded 1.0.1 deb package and it's working now!
