### ISSUE TITLE
Allow running without the indicator

### ISSUE THREAD

**Issue by felagund** [pwr-Solaar/Solaar#566]
Running solaar fixes a weird issue when my Logitech Illuminated K800 keyboard would lag and miss keypresses after booting up my machine. An alternative workaround was unplugging and replugging the receiver but nto having to do anything is more pleasant. However, I don't actually need solaar for any of its functionality (especially since it does not seem to read the battery status of my keyboard) - could there be a preference somewhere to just run it in the background without any presence in the indicator area?

**Comment by pfps** [comment]
That would be possible, but I don't think there would be much incentive to do any work on that feature. 
(But I don't see how solaar is affecting the situation.)
If you are willing and able, you could write the changes yourself and submit a pull request.

**Comment by felagund** [comment]
Unfortunately, I am not able. I do not know how it changes the situation but it definitely improved it, I can tell if my keyboard works or not:-).

**Comment by pfps** [comment]
PR #666 allows running without the tray if you do `solaar --window=only`.  Is this sufficient for your needs?

**Comment by felagund** [comment]
Yes, I think so, thank you!

**Comment by pfps** [comment]
OK, closing.
