### ISSUE TITLE
Disable Tray/GUI in Mint?

### ISSUE THREAD

**Issue by S3NTYN3L** [pwr-Solaar/Solaar#571]
I'm running Linux Mint and find the Notifications and Tray Icon super annoying.
I would like to disable these features completely.
How can this be accomplished? Is there a config file somewhere?
EDIT: I suppose what I'm really asking is; How can I disable the GUI in favor of the CLI version ONLY?

**Comment by doctor64** [comment]
@S3NTYN3L Sorry if i understand your request incorrectly, but if you don't needed GUI you can just not start it. GUI and CLI version works independently. Just remove `solaar.desktop` from `/etc/xdg/autostart/` or use your WM's autostart manager (sorry, I'm not familiar with Mint).
