### ISSUE TITLE
m705 Battery warning at 85%

### ISSUE THREAD

**Issue by Dreded** [pwr-Solaar/Solaar#575]
the solaar tray icon is always a red low battery icon, when I open the app it shows a warning symbol on a low battery thats at 85% is this correct? to me 85% isnt warning level low in fact for some batteries that might be full.

```
1: Marathon Mouse M705 (M-R0009)
     Codename     : M705 (M-R0009)
     Kind         : mouse
     Wireless PID : 101B
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: 15737173
          Firmware: 17.01.B0017
        Bootloader: 02.06
             Other: 00.04
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Battery: 85%, discharging.
````

**Comment by imrel** [comment]
same, 
tray icon show empty red battery
so does both m705 mouse and k270 keyboard menu items when right clicking on try icon. 

UI itself shows 70%+ for both

**Comment by vbelloir** [comment]
Same here, with a M705 Logitech mouse.
Displaying red empty icon, with 85%.

**Comment by pfps** [comment]
This should be fixed in the version of solaar on github.  Can you clone this version and run solaar directly from the bin directory in the download tree?

**Comment by pfps** [comment]
Closing due to no response from original posters.
