### ISSUE TITLE
Microsoft Precision Mouse Wheel Resolution

### ISSUE THREAD

**Issue by Hedronmx** [pwr-Solaar/Solaar#577]
Hello, this might be out of scope but I am having problems with the scroll speed of the wheel on my microsoft precision mouse after upgrading to kernel 5.0.  Could it be possible to force the Wheel Resolution to on using this software?

Thank you, and sorry if this is way out of scope.

**Comment by FFY00** [comment]
No, that is not possible. But you should be able to change the wheel resolution multiplier in libinput.

**Comment by Lekensteyn** [comment]
That is correct, libinput is the device-independent way to do this. See also https://wayland.freedesktop.org/libinput/doc/latest/faqs.html#my-mouse-moves-too-fast-even-at-the-slowest-setting

Solaar would provide a mechanism to control this setting on the hardware level, but that is only possible for Logitech devices.
