### ISSUE TITLE
Not recognizing Logitech Receiver 046d:c534

### ISSUE THREAD

**Issue by drillsar** [pwr-Solaar/Solaar#579]
I am on Gentoo and installed Solaar and no devices listed.

lsusb | grep Logitech
Bus 001 Device 003: ID 046d:c534 Logitech, Inc. Unifying Receiver

dmesg | grep Logitech
[    0.998374] usb 1-1.2: Manufacturer: Logitech
[    1.001158] input: Logitech USB Receiver as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2:1.0/0003:046D:C534.0001/input/input7
[    1.044169] hid-generic 0003:046D:C534.0001: input,hidraw0: USB HID v1.11 Keyboard [Logitech USB Receiver] on usb-0000:00:1a.0-1.2/input0
[    1.048402] input: Logitech USB Receiver Mouse as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2:1.1/0003:046D:C534.0002/input/input8
[    1.050244] input: Logitech USB Receiver Consumer Control as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2:1.1/0003:046D:C534.0002/input/input9
[    1.104125] input: Logitech USB Receiver System Control as /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2:1.1/0003:046D:C534.0002/input/input10
[    1.105862] hid-generic 0003:046D:C534.0002: input,hiddev96,hidraw1: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-0000:00:1a.0-1.2/input1

**Comment by FFY00** [comment]
With which device did that receiver come?

**Comment by doctor64** [comment]
@drillsar Do solaar detect receiver? Can you provide output of `solaar -dd show`? May be rights problem - can you try as root, ie `sudo solaar -dd show`?

**Comment by FFY00** [comment]
@drillsar can you give an update on this? Could you make sure you are on Solaar 1.0.1? The receiver is already specified in the code.

**Comment by rnestler** [comment]
I have the same receiver (or at least the same USB ID). `solaar show` outputs:
```
Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c534
  Serial       : 0
    Firmware   : 29.01.B0016
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: (none)

  1: Wireless Keyboard MK270
     Codename     : MK270
     Kind         : keyboard
     Wireless PID : 4023
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: 00000000
          Firmware: RQK 49.00.B0029
     Supports 18 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: BATTERY STATUS         {1000}   
         5: REPROG CONTROLS        {1B00}   
         6: WIRELESS DEVICE STATUS {1D4B}   
         7: FN INVERSION           {40A0}   
         8: ENCRYPTION             {4100}   
         9: KEYBOARD LAYOUT        {4520}   
        10: unknown:1810           {1810}   internal, hidden
        11: unknown:1830           {1830}   internal, hidden
        12: unknown:1890           {1890}   internal, hidden
        13: unknown:18A0           {18A0}   internal, hidden
        14: unknown:18B0           {18B0}   internal, hidden
        15: unknown:1DF3           {1DF3}   internal, hidden
        16: unknown:1E00           {1E00}   hidden
        17: unknown:1868           {1868}   internal, hidden
     Has 11 reprogrammable keys:
         0: MY HOME                    => HomePage                      is FN, FN sensitive, reprogrammable
         1: Mail                       => Email                         is FN, FN sensitive, reprogrammable
         2: SEARCH                     => Search                        is FN, FN sensitive, reprogrammable
         3: Calculator                 => Calculator                    is FN, FN sensitive, reprogrammable
         4: MEDIA PLAYER               => Music                         is FN, FN sensitive, reprogrammable
         5: Previous                   => Previous                      is FN, FN sensitive
         6: Play/Pause                 => Play/Pause                    is FN, FN sensitive
         7: Next                       => Next                          is FN, FN sensitive
         8: Mute                       => Mute                          is FN, FN sensitive
         9: Volume Down                => Volume Down                   is FN, FN sensitive
        10: Volume Up                  => Volume Up                     is FN, FN sensitive
     Battery: 30%, discharging.

  2: Wireless Mouse M185 new
     Codename     : M185n
     Kind         : mouse
     Wireless PID : 4054
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 00000000
     The power switch is located on the base.
     Battery: unknown (device is offline).
```

**Comment by pfps** [comment]
I am running on Fedora, Solaar version 1.0.1, and this receiver is recognized.  There are problems with how it is modelled - I'll open another bug report for that.
I suggest this bug report be closed.

**Comment by pfps** [comment]
I have patches to solaar for this receiver that work for me.   I'm waiting for my documentation changes to be pulled (as I didn't do these changes on a separate branch).

**Comment by pfps** [comment]
As the current version of Solaar handles c534 (but not as well as it should, perhaps) I suggest that this issue be closed.
