### ISSUE TITLE
Re-do UI

### ISSUE THREAD

**Issue by FFY00** [pwr-Solaar/Solaar#592]
The current UI does not work for in some cases. We need to rethink it and come up with a better solution.

**Comment by doctor64** [comment]
I wish to discuss UI for re programmable buttons feature. It's pretty easy from hardware point of view (at least with REPROG CONTROL V4), but i have difficulties to implement it in UI.
Lets start with simple example - here is output from M185:
` Has 3 reprogrammable keys:
         0: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
             divertable, mse, pos:0, group:1, gmask:1
         1: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
             divertable, mse, pos:0, group:1, gmask:1
         2: MIDDLE BUTTON             , default: MiddleMouseButton           => MIDDLE BUTTON             
             divertable, mse, reprogrammable, pos:0, group:2, gmask:3
`
Not going deeply into details, this mean what device have two groups of buttons:

1. Left and Right button. Can be programmed to any value in this group, ie Left or Right
2. Middle button. can be programmed to any value from groups 1 and 2, ie Left/Right/Middle

So, we need in GUI have two lists (may be drop-down lists?) there first contain list of physical keys which can be programmed, and second list contain values to which key can be programmed. Then item in first list changed, second list should be updated with new values.

Is it ok?

**Comment by pfps** [comment]
Hmm.  That's a tough UI decision.  
I would be tempted to have  two-column box that has the physical keys in the left column and the key's output in the right column.  Clicking on the right column would pop up a selection box with all the possibilities (maybe with possibilities that are not the current mapping of any key emphasized).   This gives the state of all the reprogrammable keys at a glance but if there are a lot of reprogrammable keys then the box would either get rather large or would have to be scrollable.
The problem with just showing one key at a time is that it would be easy to loose track of what the current state of all the keys are.

**Comment by doctor64** [comment]
@pfps You are right, but problem is what accordingly to Logitech docs different keys can be programmed to different sets. For example, Key A can be assigned to A-C, but Key E can be assigned only to E or F. I am not sure it is real problem, i don't have devices with such functionality, but still it is possible accordingly to documentation.
Easier approach may be something like column of reprogrammable keys on left, each key on specific line, and drop down list of variants for each key on the right. Sorry if description sounds silly :)
But, this variant can take lots of screen space, especially for keyboard devices, with 20+ reprogrammable keys.

**Comment by doctor64** [comment]
@pfps Ah, sorry, we describe same UI just with different wording :)
Something like drop-down lists in excel table like: https://www.contextures.com/images/datavalidation/createdropdown15.png

**Comment by pfps** [comment]
Yes precisely.

Here is what I think that this would look like for a keyboard with 5 reprogrammable keys where the first three can only be programmed in their group but the last two can be reprogrammed to any of the five.

The window would have five rows, one per key.  Each row would have two parts - the key or button name and a drop-down menu showing the current function of the key.

So the default setup would look like the following (but with the columns aligned)

Key or Button	Function
MY HOME 	HomePage
Mail 		Email
SEARCH 		Search
Calculator 	Calculator
MEDIA PLAYER 	Music

The first three drop-down menus would have entries for HomePage, Email, and Search.
The first two would also have entries for Calculator and Music.
Ideally, all the menus would have unused functions emphasized in some way, but that might require rebuilding them all whenever a key is reprogrammed.

For your M185 mouse there would only be one row

Key or Button	Function
MIDDLE BUTTON	MiddleMouseButton

The menu would have entiries for LeftClick, RightClick, and MiddleMouseButton

My M185 (WPID 4054) has all three buttons reprogrammable.  I think that the side buttons can only be reprogrammed to each other.  So the window would look like

Key or Button	Function
LEFT CLICK	LeftClick
RIGHT CLICK	RightClick
MIDDLE BUTTON	MiddleMouseButton

The top two drop-downs would only have LeftClick and RightClick while the bottom one would have all three functions.


One thing that I don't understand is the relationship between the key names and the function names.  Perhaps the first is the appearance on the keyboard and the second is a Windows name for the keycode that is sent?

**Comment by doctor64** [comment]
@pfps Yes, something like that. But what about, for example, K800 (new) keyboard with 15-8=7 reprogrammable keys, where each key can have 15 settings? I fear what this UI will be cluttered and not very usable.

> One thing that I don't understand is the relationship between the key names and the function names. 
You mean "MIDDLE BUTTON             , default: MiddleMouseButton" in solaar show output? 
As far as I understand Logitech document https://lekensteyn.nl/files/logitech/x1b04_specialkeysmsebuttons.html first item point to physical location of control, second - information about default action assigned to this control.

**Comment by pfps** [comment]
For K800 there would be (only!) 7 rows, one for each reprogrammable key.  The drop-down menus would have 15 entries if all the targets are valid, but they wouldn't show up unless the user is making a choice.  So this would look like https://www.contextures.com/images/datavalidation/createdropdown15.png with only two columns.
I wouldn't put the reprogramming box in the main Solaar window, but instead have a button to initiate key reprogramming, like the pairing button, and a separate window that does the reprogramming.
I think that the problem with having only one row and being able to have the row show any reprogrammable key is that the user would end up confused as to the overall state of the device.

**Comment by doctor64** [comment]
@pfps Ok, this looks reasonable. I was trying to fit reprogramming information into main window. Unfortunately, I'm not a gui/gtk expert, but i try to implement something.

**Comment by mickleby** [comment]
I've done various GUI/UI, tho not gtk specifically. I'll read this thread.

Perhaps already discussed, should we implement/debug the CLI before moving on to GUI?

**Comment by pfps** [comment]
As far as I can see there are several aspects to doing key reprogramming nicely:
1/ Figure out how much to support
2/ Determine how to represent both the saved and the internal state
3/ Save to and restore from the saved state
4/ Change key mappings in the CLI
5/ Change key mappings in the GUI
There is already an internal state for key reprogramming in hidpp20.py - KeysArray.  I'm not sure that that is quite correct, though.  Is there a document that shows the details of the various HID++ 2.0 functions?
My view is that it is fine to just support simple key reprogramming. I think that is what @doctor64 is proposing to do.  For this, I think that the saved state is just a mapping from keys to their reprogrammed key.

**Comment by doctor64** [comment]
@pfps Exactly. I propose to support only reprogrammable keys. I play with this a little, and feature works as defined in documentation  https://lekensteyn.nl/files/logitech/x1b04_specialkeysmsebuttons.html Then I have a little time (sorry, currently under heavy load from my daily job) I will try to add some simple support to solaar cli. after that we can discuss how to implement this in gui. Is it Ok?

**Comment by mickleby** [comment]
everything you type sounds right to me.

I'm gonna track down how the fn-swap state is stored. Perhaps we follow suit. Then I'll review https://lekensteyn.nl/files/logitech/x1b04_specialkeysmsebuttons.html

**Comment by pfps** [comment]
As far as I know (and I've just been looking through this code to fix a couple of bugs) the configuration code indeed does store and restore state, but just what state should that be?   To correctly know which keys a key can be reprogrammed to, you need to know the groups that keys are in and which group the key to be reprogrammed can be reprogrammed to.  But that information can be obtained from the device and doesn't need to be stored in the config.json file.  I think the only information that needs to be stored there is the mapping from a key to its reprogrammed key.
It's like the situation for ranged feature values.  The code needs to know the range limits but only the current value needs to be stored in config.json.

**Comment by mickleby** [comment]
@pfps  `solaar show K830` seems to return the current state. I'm off to see if this is from a hard-coded table or retrieved via device query.

I'm still pondering "the current value needs to be stored in config.json." If we can quickly query state there may be no need to store values. Surely we DO NOT wish a situation where config.json is recording state that has changed. PERHAPS we might want values in config.json to be set when solaar launches, but I doubt this. Again, if solaar can quickly query the device I imagine something like this:
>`solaar config K830` returns current state of programmable
>`solaar config K830 Kn Sn` sets the programmable Kn to state Sn, and returns current state

**Comment by doctor64** [comment]
@mickleby You are right, `solaar show` have code to display current state of remapping from hardware. You can even manually create commfyl in `hidconsole` and see changes in output of `solaar show`.
My plan was like: (for gui)
1. Device updated (like startup or new device connects)
2. Create list of key can be programmed
3. For each such key create list of values to which keys it can be programmed
4. If exist get pre-defined mapping from config.json
5. perform programming
6. display in GUI
7. If in GUI mapping changes update device and config.json
but I was stuck in GUI part :(

**Comment by mickleby** [comment]
@doctor64 I'm curious re "stuck in GUI part" Perhaps you'd like to point to an example. What is "commfyl"?

**Comment by pfps** [comment]
@mickleby config.json is used to store device state between runs of solaar. Otherwise switching left and right mouse buttons will unswitch after the mouse is turned off and on again.  (That is unless key reprogrammings persist in the mouse - I don't know if they do, but other settings do not.)

**Comment by doctor64** [comment]
@mickleby Sorry, I mean 'command'. About GUI part - currently in Solaar functions which set some device properties automatically works both in CLI and GUI. But existing framework expect what function set some boolean value, numeric value or list. I try to implement support for dual lists, but failed. Actually code which will set remapping is simple, but GUI implementation is complex for me.

**Comment by mickleby** [comment]
@pfps I'm surprised to read re-mappings do not persist on the device. So then, ... Is the protocol like this: ? read and set param on first launch? Suppose I open the widget window? Which state is valid? The device or the config? What if I connect a device after solaar is running: ? Is the protocol to notice the device connect msg and push settings? What if I pair a device for which there exist settings? ?Does solaar push config settings to each and every K830 that connects? by some uinique ID? what about device index?

@doctor64 probably I'll discover the relevant GUI file; feel free to point me to the file, function, line number -- probably I can help.
@doctor64 what is a dual list? Is this like a [combobox](https://en.wikipedia.org/wiki/Combo_box) on the left that sets up a combobox on the right when an item is selected in the left combo?

**Comment by pfps** [comment]
@mickleby Solaar tries to push changed settings to devices whenever they appear as devices do not remember (at least some) changed settings.  See #642 and several other issues that are about a bug in this resetting but in general it appears to work reasonably well.  Take a look in ~/.config/solaar/config.json to see what solaar remembers and notice that it identifies devices by a combination of WPID and serial number.   (There is a lurking problem here.  I have two K270 keyboards that Solaar thinks have serial number 00000000.   I haven't run them both on the same system to see what happens.)

That said, maybe key reprogrammings are remembered - I haven't checked.

PS:  Here is a bit of my config.json with some serial numbers removed 

{
  "1025:AAAAAAAA": {
    "_name": "Wireless Mouse M510",
    "side-scroll": true,
    "smooth-scroll": false
  },
  "1025:BBBBBBBB": {
    "_name": "Wireless Mouse M510"
  },
  "4023:00000000": {
    "_name": "Wireless Keyboard MK270",
    "fn-swap": false
  },

**Comment by mickleby** [comment]
@pfps re issue #642 , yes that is just the sort of logic bug I would expect. I'm thinking I must set aside this #592 and look into that. Seems you suggest Serial Number is known (expected) to be a static hardware ID. Where do I find documentation?

@doctor64 can you supply an example of using CLI to program something via hidconsole? This is the first I've heard of hidconsole. I don't see search results demonstrating its use. Also what hid devices do you have? I'm using K830, though I do have a dust magnet K400

**Comment by pfps** [comment]
@mickleby #642 should be fixed by PR #649 so hopefully there is nothing for you to do there (fingers crossed).  Serial number documentation - solaar appears to get serial numbers correctly even though documentation for both HID++ versions 1.0 and 2.0 is a bit scarce.  It would be nice to know if some devices (e.g., keyboard MK270 WPID 4023 and mouse WPID 4022) have their serial numbers elsewhere.

@FFY00 It appears that some receivers store device serial numbers in register 0xB5 address 0X1n instead of 0X3n.  At least that is what I'm seeing with my c534 receivers.   Is there any way to confirm this?

**Comment by mickleby** [comment]
@pfps I confirm:
> - K830 power cycle resets default fn-swap config (i.e. devices goes to '1' when it's turned on)
> - solaar pushes config somewhere after startup.

I'm now going to search what triggers the push. As I understand, these #592 will leverage the same push routines. I should write a doc to expose the project architecture.

BTW I find `/docs/devices/k830.txt` Why nothing for K400? How are these files used?

**Comment by pfps** [comment]
@mickleby 
Changing a device while the Solaar GUI is running is definitely not a good idea.  If you change a value using the CLI then GUI Solaar doesn't notice the change (as far as I know).  I suppose the GUI could monitor writes (if this is possible) and look for changes.  
The GUI does see notifications, including device connects and disconnects.  The connect notification has a 0x41 in it.  There is code in Solaar to look for these notifications and push saved values to the device.  The push also happens when Solaar starts up, as far as I know.
The code that starts work is the initialization of devices.  The code that does the pushes is write in settings.py, but it uses code in settings templates to determine what to write to the device.
I've done some minor changes to this code recently (to fix up bugs related to auto-discovery of features so be sure to grab the newest version.

**Comment by FFY00** [comment]
@pfps we should use feature `0x0004` which exports an UUID. I think you just call it without any arguments and it returns the UUID, which might even be the same as the serial.

**Comment by FFY00** [comment]
Hum, there's also `0x0021` which seems to be more common.

**Comment by mickleby** [comment]
@FFY00  I guess you mean `DEVICE_UNIT_ID=0x0004,` from lib/logitech_receiver/hidpp20.py. Where can I find `0x0021`?

**Comment by FFY00** [comment]
Yes, `CRYPTO_ID` is a really bad name. `0x0021` will export a device UUID.

**Comment by pfps** [comment]
OK, if it turns out that this is needed, I'll work on it, but it may be that the receivers just hadn't set up the keyboards completely.  I'm now seeing a real serial number for a keyboard that had zeros.  This may be an aspect of the c534 receiver.

**Comment by mickleby** [comment]
@pfps Is it assumed there will be only a single instance of any device? Was looking through code, seems like solaar just goes with the first device name match, ignoring the serial number.

What specifically are you discussing re serial/uid?

Does someone itemize the changes to gui somewhere? Like "current UI does not work for in some cases" isn't suggestive. I can mock up something if useful, but I'd like better understanding of what is to be fixed/changed.

Also, still reading as to why there cannot be multiple instances of solaar. Is there an id collision when subsequent instances register to receive notifications? Like just guessing, does solaar register with dbus as 'solaar' rather than 'solaar[uid]'?

**Comment by pfps** [comment]
@mickleby I have several MK270 keyboards that showed up in Solaar with 00000000 as their serial number.  If that was all that Solaar could find out about them then there would only be one record in config.json and settings from one would be put on the other.  However, at least one of them is now showing up with a real serial number so I'm not sure whether there is a need to get their serial number from a different source.

**Comment by pfps** [comment]
@mickleby I've been opening bugs about problems with Solaar as I find them, and fixing most of the bugs I've found.   This hasn't yet ended up with any significant changes to the GUI.  I do have some changes that are almost ready and these changes will affect how c534 receivers act in the GUI.  I'll be making documentation changes to along with these code changes.

**Comment by pfps** [comment]
@mickleby [I'm splitting my replies in the hope that it will make it easier for others to read.]  My understanding is that if there are multiple instances of Solaar running and one makes changes to a device then these changes might not be picked up by the other instances.  So there could be a mismatch between the actual state of the device and what Solaar thinks the state is.  I haven't poked Solaar enough to make a complete determination of whether this is the case, though.

**Comment by pfps** [comment]
@mickleby As far as I can tell Solaar handles situations with multiple similar receivers and devices correctly.    Right now I'm running with two c52b  Unifying receivers and they both show up correctly.  I even have the exact same mouse paired with both of them.  The mouse is only on-line with one receiver, which seems correct.  There is one potential problem though - there might be two copies of the saved state for that mouse in Solaar.  But I can't see how to make the mouse online with the other receiver without first unpairing it so I don't think that this situation can cause problems with saved state.

**Comment by pfps** [comment]
The UI and interface for settings has been reworked considerably so I think this issue can be closed.
