### ISSUE TITLE
App UI blank after updating to Ubuntu 19.10 & Solaar 1.0.1+dfsg-1

### ISSUE THREAD

**Issue by dfht684** [pwr-Solaar/Solaar#607]
As the title states, the UI portion of the app is blank when open it on Ubuntu 19.10 running Solaar 1.0.1+dfsg-1.

The app is not completely broken, however. Running it in command-line with actions works fine. Screenshot:
![solaar](https://user-images.githubusercontent.com/10049341/71220332-fdf1e900-227c-11ea-9f9a-2291765b678e.png)

**Comment by FFY00** [comment]
Can you please paste the output of `solaar show`?

**Comment by dfht684** [comment]
Hi @FFY00 , here's the output:
`DMSO:~$ solaar show
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 6B799313
    Firmware   : 12.07.B0029
    Bootloader : 02.15
    Other      : AA.AA
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=188, 2=159

  1: Wireless Solar Keyboard K750
     Codename     : K750
     Kind         : keyboard
     Wireless PID : 4002
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: BC7AD4F3
          Firmware: RQK 33.00.B0015
        Bootloader: DFU 00.02.B0003
     The power switch is located on the edge of top right corner.
     Supports 11 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: REPROG CONTROLS        {1B00}   
         5: WIRELESS DEVICE STATUS {1D4B}   
         6: unknown:1DF3           {1DF3}   hidden
         7: FN INVERSION           {40A0}   
         8: ENCRYPTION             {4100}   
         9: SOLAR DASHBOARD        {4301}   
        10: KEYBOARD LAYOUT        {4520}   
     Has 12 reprogrammable keys:
         0: MY HOME                    => HomePage                      is FN, FN sensitive, reprogrammable
         1: Mail                       => Email                         is FN, FN sensitive, reprogrammable
         2: SEARCH                     => Search                        is FN, FN sensitive, reprogrammable
         3: Calculator                 => Calculator                    is FN, FN sensitive, reprogrammable
         4: MEDIA PLAYER               => Music                         is FN, FN sensitive, reprogrammable
         5: Previous                   => Previous                      is FN, FN sensitive
         6: Play/Pause                 => Play/Pause                    is FN, FN sensitive
         7: Next                       => Next                          is FN, FN sensitive
         8: Mute                       => Mute                          is FN, FN sensitive
         9: Volume Down                => Volume Down                   is FN, FN sensitive
        10: Volume Up                  => Volume Up                     is FN, FN sensitive
        11: SLEEP                      => Sleep                         is FN, FN sensitive, reprogrammable
     Battery status unavailable.

  2: Performance Mouse MX
     Codename     : Performance MX
     Kind         : mouse
     Wireless PID : 101A
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: C4C5FC4A
          Firmware: 15.01.B0062
        Bootloader: 02.11
             Other: 00.09
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Battery: critical, discharging.
`

**Comment by dfht684** [comment]
Looks like it was due to Ubuntu 19.10 itself. Still running 1.0.1+dsfg-1 but had some incremental updates for 19.10 since I first posted the bug. Now the UI renders fine.

Since I didn't post last time the system versions last time, here it is now:
> Package: solaar
> Version: 1.0.1+dfsg-1

> Operating System: Ubuntu 19.10
> Kernel: Linux 5.3.0-24-generic
