### ISSUE TITLE
debugging -dd produces misleading messages for reports from devices

### ISSUE THREAD

**Issue by pfps** [pwr-Solaar/Solaar#621]
**Information**

- Solaar version:  1.0.1
- Distribution: github

**Describe the bug**
With -dd debug level solaar produces messages like:
```
09:06:25,316    DEBUG [ReceiverListener:hidraw3] logitech_receiver.base: (14) => r[02 0000FFEFFF0000] ignoring unknown report
```
for reports from the devices.
These messages aren't really unknown, they are just the usual messages from devices.

So something else should be done for these messages.  My suggestion is to not produce them at all, but at the minimum the message should be changed to say something like "ignoring device report", and the debug level for them made higher.  As it is they just clutter up the debug log.

**Comment by FFY00** [comment]
Yes, these are regular HID messages. They report things like mouse movement, button clicks, etc. We probably should ignore anything that doesn't have an expected report ID.

**Comment by pfps** [comment]
OK.  I'll put in a PR that doesn't produce this debug log information for any report number under 0x10 on the basis that these should all be normal reports.  This is precisely the reports that generate the "unknown" messages.

**Comment by FFY00** [comment]
You should just whitelist `0x10`, `0x11` and `0x12`.

**Comment by pfps** [comment]
Hmm.  Right now any report greater than 0x0F is logged and passed back and any report less than 0x10 is logged and not passed back.  The change I made just doesn't log for reports less than 0x10.  Are you sure that not passing back other reports greater than 0x0F isn't going to change something?
