### ISSUE TITLE
better documentation (devices.md document)

### ISSUE THREAD

**Issue by pfps** [pwr-Solaar/Solaar#638]
In the issues I've looked at I've seen a number of requests for features that Solaar just isn't built for.  Partly in response to these issues, I've modified the devices.md document (which is attached).  

The first part of the document discusses what Solaar can do.  I added a section on how HID++ works.  The second part of the document lists the devices that Solaar can work with.  I added a few devices and added the identifying information for each of these devices.  I also added  a section on supported receivers.

I think this is better than the current document, but I'm not completely happy with it.  Maybe the document should be split into two documents, and the main Solaar document updated accordingly.

Comments on what to do next are welcome.

Note that I had to change the extension of the file so that I can attach it here.
[devices.md.txt](https://github.com/pwr-Solaar/Solaar/files/4055908/devices.md.txt)

**Comment by Klap-in** [comment]
Nice explanation! Thanks!
For me it also feel logically if you make two pages from this document. One about what Solaar can do, and the other with the lists of actual supported receivers and devices. That way, the pages are also easier to navigate.
