### ISSUE TITLE
too many messages in debugging output

### ISSUE THREAD

**Issue by pfps** [pwr-Solaar/Solaar#640]
- Solaar version: current version in github

**Describe the bug**
Turning on debugging (any level) results in messages like
11:37:46,458  WARNING [ReceiverListener:hidraw0] logitech_receiver.notifications: <PairedDevice(1,1025,M510)>: unrecognized Notification(1,02,00,0000F0FF00000000000000)
for move movements and other normal HID messages.

**To Reproduce**
1. solaar -d
2. Move mouse

These should not be reported as WARNINGs.   They probably should not be reported at all, or only reported from solaar -ddddddddd.

**Comment by pfps** [comment]
I was digging around in the code to find out the reason for so many unrecognized notifications.
The culprit may be make_notification in base.py, or may be elsewhere.
Is there documentation on just what a message like 
20 01 0200 ....
is supposed to be?

**Comment by pfps** [comment]
Messages with report id 20 and sub id 01 or 02 are keyboard and mouse reports.   Not making them into notifications is the right thing to do - I did this and it cut down immensely on the false warnings and debug reports.
Messages with report id 20 and sub id 41 appear to be connection notifications, and they appear to be handled correctly.
There are messages with report id 20 and sub id 42.  How can I find out what they are?

**Comment by pfps** [comment]
Aah, Unifying_receiver_DJ_collection_specification_draft.pdf has the information.  These are connection messages.
But there are HIP++1.0 messages that carry roughly the same information.  Is it ever useful to do something with these messages?

**Comment by mickleby** [comment]
@pfps you seem to prefer suppressing mouse movement notifications entirely. Why not change them from "WARNING" to "INFO" and require at least `-dd` for them to print?

**Comment by pfps** [comment]
@mickleby Yes, I think that a merged commit from a while ago did that.   The previous processing was to turn DJ mouse movement reports into Solaar notifications which then were reported as unrecognizable.  My PR #646 changes the creation of notifications so that DJ mouse movement reports don't create notifications.  
At least that's what I am seeing.  You might want to download and try the version of Solaar for PF #646 and check how it works for you.

**Comment by mickleby** [comment]
@pfps I'm happy to test any code. In this case, can you point me to how to check your changes? 

"a merged commit from a while ago did that" What is [that]? Changed from Warn-to-Info and requires -dd?

**Comment by pfps** [comment]
@mickleby It was #623

**Comment by mickleby** [comment]
> @mickleby It was #623

@pfps how does one git checkout a pull request before it is merged? Also, isn't PR623 already merged and being "tested" when I pull from master?

**Comment by pfps** [comment]
@mickleby #623 is already in.  If you want to see the more substantive changes that I've proposed I think that you have to clone my repository https://github.com/pfps/Solaar and checkout and run from one of the branches there.  The branch that changes the reporting of messages is the notify branch.  The relevant PR is #646

**Comment by mickleby** [comment]
@pfps I thought it should be possible to checkout the pull request, together with the archive at the time the pr was submitted. I can manually gather what is needed. But doing such in a systematic way, using a tool for example, would avoid any mistakes. I do see your archive and the tags therein. Thanks

**Comment by pfps** [comment]
Closed by PR #646
