### ISSUE TITLE
support duolink

### ISSUE THREAD

**Issue by casperdcl** [pwr-Solaar/Solaar#650]
Support https://www.logitech.com/en-us/product/options#duolink

- provide the option to modify mouse behaviour if `fn` is pressed on the keyboard (e.g. `fn`+`middle click` = `play/pause`)
- similar to how `<Alt>` tends to alter left/right/mid mouse buttons (https://askubuntu.com/questions/1105641/how-do-i-change-super-middle-mouse-button-shortcut)

I think modifying mouse key behaviour when a keyboard key is pressed should be fairly doable. However adding gestures (e.g. `fn` + `mouse move down` = `minimise`, `fn`+`mouse move left` = `pan left`) might be more tricky.

**Comment by doctor64** [comment]
@casperdcl I'm not sure that this is possible in Solaar. Solaar currently only configure hardware support in Logitech mice/keyboard, and from description looks like this feature actually works in input stack of OS, not in hardware. Do you have some hardware where this feature works in windows?

**Comment by FFY00** [comment]
That is all implemented in software. Solaar exists to configure hardware, not this. Solaar could go as far as provide some Logitech specific software functionality but this is not Logitech specific. https://github.com/whot/ggkbdd, for example, would be a better place for this feature.
