### ISSUE TITLE
Support for Unifying receiver c52b broken

### ISSUE THREAD

**Issue by doctor64** [pwr-Solaar/Solaar#652]
**Information**
- Solaar version: 1.0.1, git commit id commit 77e21a0b630d2b086af47827b9fd6197ebd0a389
- Distribution: Ubuntu 19.10
- Kernel version (ex. `uname -srmo`): `Linux 5.3.0-26-generic x86_64 GNU/Linux`
- Output of `solaar show`:
```
bin/solaar show
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <bound method Receiver.__del__ of <UnifyingReceiver(/dev/hidraw3,3)>> ignored
solaar: error: Logitech receiver not found
```

**Describe the bug**
Current version from git stop recognize receiver 046d:c52b. See attached logs

**To Reproduce**
1. start solaar, both cli or gui
2. See error in cli, gui version starts but doesn't display receiver

**Additional context**
```
lsusb
Bus 002 Device 003: ID 05e3:0616 Genesys Logic, Inc. hub
Bus 002 Device 002: ID 174c:3074 ASMedia Technology Inc. ASM1074 SuperSpeed hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 008: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 001 Device 006: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 005: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 023: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 004: ID 174c:2074 ASMedia Technology Inc. ASM1074 High-Speed hub
Bus 001 Device 003: ID 1415:2000 Nam Tai E&E Products Ltd. or OmniVision Technologies, Inc. Sony Playstation Eye
Bus 001 Device 010: ID 09da:9090 A4Tech Co., Ltd. XL-730K / XL-750BK / XL-755BK Mice
Bus 001 Device 009: ID 1415:2000 Nam Tai E&E Products Ltd. or OmniVision Technologies, Inc. Sony Playstation Eye
Bus 001 Device 007: ID 8086:0808 Intel Corp. USB PnP Sound Device
Bus 001 Device 002: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
```
bin/solaar -dd show
21:53:15,101    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 030000]
21:53:15,102    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 FF 83B5 034A8A9C110A06090000000000000000]
21:53:15,103    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 80B2 000000]
21:53:15,103    ERROR [MainThread] logitech_receiver.base: write failed, assuming handle 3 no longer available
21:53:15,103    ERROR [MainThread] logitech_receiver.receiver: open DeviceInfo(path=u'/dev/hidraw3', vendor_id=u'046d', product_id=u'c52b', serial=u'', release='1207', manufacturer='Logitech', product='USB Receiver', interface=2, driver=u'logitech-djreceiver')
Traceback (most recent call last):
  File "/home/doctor64/Projects/Solaar/lib/logitech_receiver/receiver.py", line 531, in open
    return Receiver(handle, device_info)
  File "/home/doctor64/Projects/Solaar/lib/logitech_receiver/receiver.py", line 359, in __init__
    self.may_unpair = self.write_register(_R.receiver_pairing) is None
  File "/home/doctor64/Projects/Solaar/lib/logitech_receiver/hidpp10.py", line 149, in write_register
    return device.request(request_id, *value)
  File "/home/doctor64/Projects/Solaar/lib/logitech_receiver/receiver.py", line 444, in request
    return _base.request(self.handle, 0xFF, request_id, *params)
  File "/home/doctor64/Projects/Solaar/lib/logitech_receiver/base.py", line 341, in request
    write(ihandle, devnumber, request_data)
  File "/home/doctor64/Projects/Solaar/lib/logitech_receiver/base.py", line 171, in write
    raise NoReceiver(reason=reason)
NoReceiver: {'reason': OSError(32, 'Broken pipe')}
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <bound method Receiver.__del__ of <UnifyingReceiver(/dev/hidraw3,3)>> ignored
21:53:15,103    DEBUG [MainThread] solaar.cli: [/dev/hidraw3] => None
solaar: error: Logitech receiver not found
```

**Comment by pfps** [comment]
Hmm.   The recent commits are mine, so I guess I'm on the hook for this.
Is this the entire output from solaar -dd?  My guess is that it is as it looks like what I see when I start up solaar -dd

**Comment by Klap-in** [comment]
I have here similar errors. 
```
user@Plaat:~$ solaar -dd config 1
21:11:37,734    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 030000]
21:11:37,736    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 FF 83B5 039928905C0406080000000000000000]
21:11:37,736    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 80B2 000000]
21:11:37,736    ERROR [MainThread] logitech_receiver.base: write failed, assuming handle 3 no longer available
21:11:37,736    ERROR [MainThread] logitech_receiver.receiver: open DeviceInfo(path=u'/dev/hidraw1', vendor_id=u'046d', product_id=u'c52b', serial=u'', release='1209', manufacturer='Logitech', product='USB Receiver', interface=2, driver=u'logitech-djreceiver')
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 531, in open
    return Receiver(handle, device_info)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 359, in __init__
    self.may_unpair = self.write_register(_R.receiver_pairing) is None
  File "/usr/share/solaar/lib/logitech_receiver/hidpp10.py", line 149, in write_register
    return device.request(request_id, *value)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 444, in request
    return _base.request(self.handle, 0xFF, request_id, *params)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 341, in request
    write(ihandle, devnumber, request_data)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 171, in write
    raise NoReceiver(reason=reason)
NoReceiver: {'reason': OSError(32, 'Gebroken pijp')}
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <bound method Receiver.__del__ of <UnifyingReceiver(/dev/hidraw1,3)>> ignored
21:11:37,737    DEBUG [MainThread] solaar.cli: [/dev/hidraw1] => None
solaar: error: Logitech receiver not found

user@Plaat:~$ solaar -dd
21:13:49,754     INFO [MainThread] root: language nl_NL (UTF-8), translations path None
21:13:49,798    DEBUG [MainThread] solaar.ui.tray: using AppIndicator3
21:13:49,803     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events
21:13:49,824    DEBUG [MainThread] solaar.ui: startup registered=True, remote=False
21:13:49,824    DEBUG [AsyncUI] solaar.tasks: started
21:13:49,827    DEBUG [MainThread] solaar.ui.icons: sys.path[0] = /usr/share/solaar/lib
21:13:49,828    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
21:13:49,828    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/share/solaar/icons
21:13:49,828    DEBUG [MainThread] solaar.ui.icons: looking for icons in /home/gerrit/.local/share/solaar/icons
21:13:49,828    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/share/solaar/icons
21:13:49,828    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/ubuntu/solaar/icons
21:13:49,828    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/local/share/solaar/icons
21:13:49,828    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
21:13:49,828    DEBUG [MainThread] solaar.ui.icons: looking for icons in /var/lib/snapd/desktop/solaar/icons
21:13:49,828    DEBUG [MainThread] solaar.ui.icons: icon theme paths: ['/usr/share/solaar/icons', '/usr/share/solaar/icons', '/home/gerrit/.local/share/icons', '/home/gerrit/.icons', '/usr/share/ubuntu/icons', '/usr/local/share/icons', '/usr/share/icons', '/var/lib/snapd/desktop/icons', '/usr/share/ubuntu/pixmaps', '/usr/local/share/pixmaps', '/usr/share/pixmaps', '/var/lib/snapd/desktop/pixmaps']
21:13:49,839    DEBUG [MainThread] solaar.ui.icons: detected icon sets: Mint True, gpm True, oxygen False, gnome True, elementary False
21:13:49,849     INFO [MainThread] solaar.listener: starting receiver listening threads
21:13:49,851     INFO [MainThread] solaar.listener: receiver event add DeviceInfo(path=u'/dev/hidraw1', vendor_id=u'046d', product_id=u'c52b', serial=u'', release='1209', manufacturer='Logitech', product='USB Receiver', interface=2, driver=u'logitech-djreceiver')
21:13:49,851    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 FF 83B5 030000]
21:13:49,853    DEBUG [MainThread] logitech_receiver.base: (13) => r[11 FF 83B5 039928905C0406080000000000000000]
21:13:49,853    DEBUG [MainThread] logitech_receiver.base: (13) <= w[10 FF 80B2 000000]
21:13:49,854    ERROR [MainThread] logitech_receiver.base: write failed, assuming handle 13 no longer available
21:13:49,854    ERROR [MainThread] logitech_receiver.receiver: open DeviceInfo(path=u'/dev/hidraw1', vendor_id=u'046d', product_id=u'c52b', serial=u'', release='1209', manufacturer='Logitech', product='USB Receiver', interface=2, driver=u'logitech-djreceiver')
Traceback (most recent call last):
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 531, in open
    return Receiver(handle, device_info)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 359, in __init__
    self.may_unpair = self.write_register(_R.receiver_pairing) is None
  File "/usr/share/solaar/lib/logitech_receiver/hidpp10.py", line 149, in write_register
    return device.request(request_id, *value)
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 444, in request
    return _base.request(self.handle, 0xFF, request_id, *params)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 341, in request
    write(ihandle, devnumber, request_data)
  File "/usr/share/solaar/lib/logitech_receiver/base.py", line 171, in write
    raise NoReceiver(reason=reason)
NoReceiver: {'reason': OSError(32, 'Gebroken pijp')}
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <bound method Receiver.__del__ of <UnifyingReceiver(/dev/hidraw1,13)>> ignored
21:13:49,854  WARNING [MainThread] solaar.listener: failed to open DeviceInfo(path=u'/dev/hidraw1', vendor_id=u'046d', product_id=u'c52b', serial=u'', release='1209', manufacturer='Logitech', product='USB Receiver', interface=2, driver=u'logitech-djreceiver')
21:13:49,875    DEBUG [MainThread] solaar.ui: activate
```

**Comment by doctor64** [comment]
@pfps Yes, its all output with c52b receiver. Nano receiver c52f works without problem.

**Comment by pfps** [comment]
That's weird.  I have a c52b receiver and things are working for me.  I'll check with a newly cloned solaar to ensure that I'm running the exact same code.

**Comment by doctor64** [comment]
@pfps Commenting out line 359 in receiver.py `self.may_unpair = self.write_register(_R.receiver_pairing) is None' fix exeption

**Comment by doctor64** [comment]
@pfps Hmm, this line 7 years old. May be something changed in exception processing?

**Comment by pfps** [comment]
Yes, but that's not from a recent commit.  In fact that code dates back to 2013.

What I see is 
idefix Solaar> bin/solaar -dd show
15:25:45,531    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 83B5 030000]
15:25:45,533    DEBUG [MainThread] logitech_receiver.base: (4) => r[11 FF 83B5 03965E9E171506350000000000000000]
15:25:45,533    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 80B2 000000]
15:25:45,535    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8F80 B20300]
15:25:45,535    DEBUG [MainThread] logitech_receiver.base: (4) device 0xFF error on request {80B2}: 3 = invalid value
15:25:45,535    DEBUG [MainThread] solaar.cli: [/dev/hidraw0] => <UnifyingReceiver(/dev/hidraw0,4)>
15:25:45,754    DEBUG [MainThread] logitech_receiver.base: (4) <= w[10 FF 8102 000000]
15:25:45,755    DEBUG [MainThread] logitech_receiver.base: (4) => r[10 FF 8102 000500]
Which is as expected.  Well, I'm not actually sure what that code is supposed to be doing as may_unpair is modified later.

**Comment by pfps** [comment]
There are changes to the processing of notifications that are in the most recent commit, but not in what you are running.   Can you try checking out the previous two commits and see if the error occurs there as well?

**Comment by pfps** [comment]
@doctor64 What's the output with the other receiver?  (All that is needed is the first few interactions with the receiver.)

**Comment by doctor64** [comment]
@pfps I go back as far as commit from Jan 2018 - same error. May be, some OS or python dependency?

**Comment by doctor64** [comment]
@pfps Yes! This error occurs in python2. in python3 output is:
```
python3 bin/solaar -dd show
22:39:37,520    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 030000]
22:39:37,521    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 FF 83B5 034A8A9C110A06090000000000000000]
22:39:37,521    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 80B2 000000]
22:39:37,622    DEBUG [MainThread] logitech_receiver.base: (3) => r[20 00 4102 0000000000000000000000]
22:39:37,622    DEBUG [MainThread] logitech_receiver.base: (3) => r[20 01 4101 0A40040000000000000000]
22:39:37,623    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F80 B20300]
22:39:37,624    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {80B2}: 3 = invalid value
22:39:37,624    DEBUG [MainThread] solaar.cli: [/dev/hidraw3] => <UnifyingReceiver(/dev/hidraw3,3)>
22:39:37,661    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 8102 000000]
22:39:37,663    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8102 000100]
Unifying Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:c52b
  Serial       : 4A8A9C11
```

**Comment by pfps** [comment]
@doctor64 But why is it breaking in python2?  And why so far back?

**Comment by doctor64** [comment]
@pfps Sorry, i have no idea. Not a python guru, I'm mostly into embedded software :)

**Comment by doctor64** [comment]
@Klap-in Just to be sure - can you confirm what using python3 fix exception on your system?

**Comment by FFY00** [comment]
@pfps @doctor64 python 2 is dead. We don't want to support it.

**Comment by pfps** [comment]
#564 may also be related to this

**Comment by pfps** [comment]
@FF00 Agreed.  There probably should be something to this effect in the bug template.

**Comment by FFY00** [comment]
@pfps sure, feel free to open a PR :)

**Comment by doctor64** [comment]
@FFY00 I understand this approach, but at very least must be note in documentation what python 3 is required. But I personally can't agree - where is lot's of linux installations with python2 as default. Damn, just few month ago I worked (not for long, fortunately) with solution based on kernel 2.6.28 and requiring ubuntu 12.04 :) So if this can be fixed without big changes, I'm think it should be fixed.

**Comment by FFY00** [comment]
I understand your position, however, I have to keep the decision. We are already barely able to maintain the project. Maintaining a language that is EOL is not something that we really want to do.

> where is lot's of linux installations with python2 as default

Well, that doesn't really matter. What matters is that python3 is available :grinning: 

> Damn, just few month ago I worked (not for long, fortunately) with solution based on kernel 2.6.28 and requiring ubuntu 12.04 :)

Ubuntu 12.04 has been EOL since 2017. But still, python 3 is available.

> So if this can be fixed without big changes, I'm think it should be fixed.

Well, sure. This argument makes perfect sense, but I think it could be a slippery slope. If you manage to fix it in a way that works both on python 2 and python 3, is clean and doesn't introduce unneeded logic, feel free to submit a PR.

**Comment by Klap-in** [comment]
I’m at the moment not behind that machine. Yesterday I had the issue as well. But then, or I have switch off all occupancies of Solaar. Or I switched between the version direct from git or from the ppa that created from git.

**Comment by Klap-in** [comment]
If I run the version from the git ppa ( `1.0.1+dfsg-1+git864-91bcfa2-202001220517~ubuntu18.04.1`) then the first time it works. If I close it next with the close button in the tray menu, and restart solaar I got this error again.

If I run it directly from the git repo, I can select the python which is used. (I guess default it is using python 2.7)
with `bin/solaar` It runs again the first time, after that it only fails. Same for `python2 bin/solaar`, first time fine, next attempts fail.
If I use `python3 bin/solaar` it keep working, also after more times closing-starting.

**Comment by FFY00** [comment]
Can you confirm everything is working fine with python 3 now that you installed the missing dependency?

**Comment by Klap-in** [comment]
If I use `python3 bin/solaar` to run it directly from git, it works fine so far.

But the version, installed via the Ubuntu git ppa, is not yet working. I guess now because it is still using python2.7.

**Comment by mickleby** [comment]
@Klap-in I think you can test the ppa version by 
```
python3 `which solaar`
```
or by simply changing the first line in solaar
```
#!/usr/bin/python3
```
@FFY00 @pfps @doctor64  given "python2 is dead, Jim" why don't we make this explicit (as above) or add a "disclaimer" like "IF python < python3 THEN print_pyversion_disclaimer"? There is a wealth of version-checking ideas here for inspiration https://stackoverflow.com/questions/6141581/detect-python-version-in-shell-script/22104476

**Comment by pfps** [comment]
@mickleby I'm not sure what the best solution is.  I think only some people have problems with python2.7.  But I guess it is time to just absolutely require python3 for everyone.  PR #653 did part of that but maybe there is more that should be done.

**Comment by mickleby** [comment]
@pfps maybe it is already clear; if not: I would say the pr for #653 created bugs. I say this because l look at the first line of "bin/solaar" and read `#!/usr/bin/env python`, interpreting this to mean "python version agnostic."

However, I'm not familiar with the issues that lead to preventing python2 support. I'm just saying, as a newb who comes along and opens the source, the first line tells me python2 is appropriate. And to be just a bit didactic, the sort of deliberate choices I'm suggesting are "self documenting" and reduce the need for a "spaghetti code" of documentation that must be continually revised. (Such docs almost never receive enough love and quickly lose sync with the projects.)

**Comment by pfps** [comment]
@mickleby Yeah, let's make bin/solaar require python3.  What's the best way to do that?

**Comment by mickleby** [comment]
@pfps in my post above I supply like 10 examples https://github.com/pwr-Solaar/Solaar/issues/652#issuecomment-580762195

One way is to change bin/solaar line 1 to read
```
#!/usr/bin/python3
```
but if the goal is only to prevent python2, I would add a python version check routine as I say: IF pyVe<3 THEN complain and exit 1.

Now the question of setup.py is raised. A solution here could be to set a static global variable used by both solaar and setup.py. And for this setup.py could actually modify solaar, thus one change in setup.py will propagate. I haven't looked at setup.py yet. Why is it needed?

**Comment by Dmitriusan** [comment]
I have the same unifying receiver and the same problem
```
Bus 002 Device 010: ID 046d:c52b Logitech, Inc. Unifying Receiver
```
Using Linux Mint  19.3 (based on Ubuntu 18.04). Have python2.7 manually installed because it's required for various legacy scripts. 
**Can confirm that the following workaround works for me**:
* Replace the first line of `/usr/bin/solaar` with `#!/usr/bin/env python3`
* Manually install `python3-pyudev`

**Comment by pfps** [comment]
@mickleby setup.py is what is used to install Solaar.   There might be lots of things that should be changed there.
@FFY00 What do you think would be the best thing to do to require using python3 for Solaar?  I'm leaning towards the very simple change of the #! line.

**Comment by FFY00** [comment]
Yes, just change the shebang to python 3.

**Comment by pfps** [comment]
OK, done for both bin/solaar and setup.py.
PR #665

**Comment by pfps** [comment]
PR #664 should have fixed this problem.

**Comment by pfps** [comment]
The changes to use python3 should have fixed this issue.
