### ISSUE TITLE
better identification of Solaar versions

### ISSUE THREAD

**Issue by pfps** [pwr-Solaar/Solaar#669]
`git describe` produces
0.9.2-339-g39791be
Instead it should produce something based on 1.0.1
`git describe --tags` produces
1.0.1-58-g39791be
which is much better.

I think that all that is required is to upgrade the 1.0.1 tag that already exists.

**Comment by Klap-in** [comment]
Is that maybe the difference between a lightweight tag and an annotated tag?

https://git-scm.com/docs/git-describe
https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by pfps** [comment]
I think so.  There is even a page on how to change a lightweight tag to an annotated one.
https://sartak.org/2011/01/replace-a-lightweight-git-tag-with-an-annotated-tag.html
@FFY00 is probably the right person to do this.

**Comment by FFY00** [comment]
I can change the tags but we should change the command either way.
