### ISSUE TITLE
possible problem when turning off a device

### ISSUE THREAD

**Issue by pfps** [pwr-Solaar/Solaar#689]
Version 1.0.1-90-g66a90ef

Looking through the Solaar code I found something puzzling relating to the message emitted when a connected device is turned off.

These messages were emitted by two different receivers when a mouse was turned off.
The 52 in the messages contains 0x40 which means "link not established".
```
07:57:01,742    DEBUG [ReceiverListener:hidraw2] logitech_receiver.base: (14) => r[10 02 410A 525440]
08:11:00,614    DEBUG [ReceiverListener:hidraw5] logitech_receiver.base: (16) => r[10 01 4104 522510]
```

Code in listener.py appears to treat this as a connection of a new device
```
07:57:01,742     INFO [ReceiverListener:hidraw2] solaar.listener: Notification(2,41,0A,525440) triggered new device <PairedDevice(2,4054,M185n,6FAD17D5)> (mouse)
08:11:00,614     INFO [ReceiverListener:hidraw5] solaar.listener: Notification(1,41,04,522510) triggered new device <PairedDevice(1,1025,M510,93E8527F)> (mouse)
```

I don't know if this is a problem.  I'm creating this issue to keep track of this finding.

**Comment by FFY00** [comment]
Please use block code tags (```) when posing logs like this, I edited the issue but please keep in mind for the future.
