### ISSUE TITLE
debian packaging needs tweaks

### ISSUE THREAD

**Issue by pfps** [pwr-Solaar/Solaar#696]
The person responsible for the ubuntu package reported to me that the current version of Solaar doesn't build because of a problem with the name of python.  I have a branch with a fix but I'm waiting for confirmation that it works as I don't know how to invoke the debian packaging build system.

**Comment by FFY00** [comment]
What is the issue exactly? It works just fine for me?

The only problem I see is that the autostart file is being installed to `/etc` which should definitely not happen.

**Comment by pfps** [comment]
The maintainer pointed me to https://code.launchpad.net/%7Esolaar-unifying/+recipe/solaar-unifying-git  which leads to https://launchpadlibrarian.net/466013384/buildlog.txt.gz which has an error at the end.

**Comment by FFY00** [comment]
I am not sure we even want to have packaging rules in the repo. I don't have enough time to maintain them.

I don't really understand the error there and I don't really understand the debian packaging system.

In Achlinux this is simply enough to build the `solaar` package, without needing to have anything in the repository.
```bash
_pkgname=Solaar
pkgname=solaar
pkgver=1.0.1
pkgrel=1
pkgdesc='Linux device manager for a wide range of Logitech devices'
url='https://pwr-solaar.github.io/Solaar/'
license=('GPL2')
arch=('any')
depends=('gtk3' 'libnotify' 'python-dbus' 'python-gobject' 'python-pyudev')
source=("$pkgname-$pkgver.tar.gz::https://github.com/pwr-Solaar/$_pkgname/archive/$pkgver.tar.gz")
sha512sums=('e0b2bbfd97d9650d94f1a4b47e4e70f09c75f684e7e1d3e67d2cf6dd197109084e941b98333e173fb205d5c9464dd07e17390d9c2d5b46393fee2efdb20429ac')

build() {
  cd $_pkgname-$pkgver

  python setup.py build
}

package() {
  cd $_pkgname-$pkgver

  python setup.py install --root="$pkgdir" --optimize=1 --skip-build

  install -Dm 644 rules.d/42-logitech-unify-permissions.rules "$pkgdir"/usr/lib/udev/rules.d/42-logitech-unify-permissions.rules


  install -vDm 644 {ChangeLog,README.md} -t "$pkgdir"/usr/share/doc/$pkgname
}
```

@skitt could you clarify what debian needs to build the package? And what it would mean if we removed `packaging/` from the repo?

**Comment by skitt** [comment]
> @skitt could you clarify what debian needs to build the package? And what it would mean if we removed `packaging/` from the repo?

The Debian package (as in, the package available from the Debian and Ubuntu repositories) needs https://salsa.debian.org/debian/solaar/tree/master/debian to build; it doesn’t use anything in `packaging/`. As far as I’m concerned you can remove `packaging/debian`, it won’t make any difference to me ;-).

Presumably it will break the Launchpad PPAs which ship Solaar (or try to) using the `packaging/` contents...

**Comment by rijnhard** [comment]
I think the Launchpad PPA is still useful for testing installs, but that said for testing itself you dont need anymore than a clone of the repo. 

I do think that we should maybe pull in the changes from upstream (@skitt), there are some added configs specific to ubuntu at the moment, but their value is questionable.

**Comment by rijnhard** [comment]
also while we are at it @skitt is there a reason to have `solaar-gnome3`? because we couldn't find one anymore.

**Comment by skitt** [comment]
> also while we are at it @skitt is there a reason to have `solaar-gnome3`? because we couldn't find one anymore.

Right, it does seem rather useless now — I might as well make `solaar` depend on everything `solaar-gnome3` depends on (other than GNOME Shell and Unity).

Regarding the Ubuntu configuration variant, I got rid of it [a while ago](https://salsa.debian.org/debian/solaar/-/commit/cab6a4c5ecfb079ddd9f3eeb9d7fd826134fb019) (and [then the icon theme dependencies too](https://salsa.debian.org/debian/solaar/-/commit/639cc339869dc7ed0cf31241cb612ecd7938273c)).

**Comment by muzena** [comment]
Hi.
I fix PPA builds, and [remove gnome3/unity](https://github.com/muzena/Solaar/blob/python3-new/packaging/debian/control) integration package.

@skitt I reuse your debian folder and modify to Ubuntu.
I found one problem in your debian packaging
Debian build use old udev rule file in /debian/solaar.udev instead of file in /rules.d/42-logitech-unify-permissions.rules so I removed /debian/solaar.udev and add to [rules file override_dh_auto_install](https://github.com/muzena/Solaar/blob/python3-new/packaging/debian/rules)

@rijnhard 
Can you add to code these two patch from debian [restore-requirements.patch](https://github.com/muzena/Solaar/blob/python3-new/packaging/debian/patches/restore-requirements.patch) and [translation-pt.patch](https://github.com/muzena/Solaar/blob/python3-new/packaging/debian/patches/translation-pt.patch)
It failed to build with pybuild without restore-requirements.patch

**Comment by pfps** [comment]
@muzena So now the PPA package has some modifications of the files in packaging, right?

@FFY00 My suggestion on how to proceed is to leave the packaging directory as part of solaar, update it to what the PPA uses, and then change the README file there to indicate that everything is just samples/guidelines.

**Comment by skitt** [comment]
> @skitt I reuse your debian packaging folder and modify to Ubuntu.
> I found one problem in your debian packaging
> Debian build use old udev rule file in /debian/solaar.udev instead of file in /rules.d/42-logitech-unify-permissions.rules so I removed /debian/solaar.udev and add to [rules file override_dh_auto_install](https://github.com/muzena/Solaar/blob/python3-new/packaging/debian/rules)

Thanks for the info, I’ve updated the Debian package with a slightly different fix.

**Comment by pfps** [comment]
Closing as fixed.   The packaging directory in Solaar no longer has current information and is going away.
