### ISSUE TITLE
Ubuntu PPA not working and not building

### ISSUE THREAD

**Issue by mfraser** [pwr-Solaar/Solaar#697]
Installed solaar from the PPA on Kubuntu 18.04 and up until recently it has been working fine, but now the icon is greyed out and running solaar show:
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <object repr() failed> ignored
solaar: error: Logitech receiver not found

solaar -V
solaar 1.0.1

Bus 006 Device 004: ID 046d:c52b Logitech, Inc. Unifying Receiver

**Comment by mfraser** [comment]
If I run the version downloaded using git, it works fine.

**Comment by mfraser** [comment]
diff -y bin/solaar /usr/bin/solaar
#!/usr/bin/env python3                                        | #!/usr/bin/python
# -*- python-mode -*-                                           # -*- python-mode -*-
# -*- coding: UTF-8 -*-                                         # -*- coding: UTF-8 -*-

Edited /usr/bin/solaar to use python3 instead of python 2.7 and it works again.

**Comment by pfps** [comment]
Thanks for the report.   Some recent versions of Solaar required python3 but did not completely enforce its use, which is what you experienced.  The current packaging file used for the Ubuntu PPA is producing an error so the Ubuntu PPA is not being updated.
Help would be appreciated in fixing the packaging file packaging/debian/control

**Comment by Klap-in** [comment]
See also #696

**Comment by pfps** [comment]
A fix should be in the works.

**Comment by muzena** [comment]
@pfps 
I fixed building in PPA, remove gnome3/unity integration and tested on Ubuntu 20.04 and Linux Mint 19.3 Cinnamon, it works without any error/Issues.

Except, I noticed in a new Solaar version that is now listed old Logitech S 510 Cordless Keyboard.
Only it has battery status and instead of keyboard name it showing wireless network pid.
I don't now is this issue or is noramal

**Comment by Klap-in** [comment]
Today I removed the installed git-ppa version of solaar, which give errors. Next I installed the latest again from the git [ppa](https://launchpad.net/~solaar-unifying/+archive/ubuntu/ppa) (version 1.0.1+dfsg-3+git919-af26870-202003142132~ubuntu18.04.1). (just an upgrade was not working). 

It works now for me without issues. Thanks for the improvements.

**Comment by pfps** [comment]
@Klap-in Thanks to @muzena from me as well.

**Comment by pfps** [comment]
@muzena Feel free to start a new issue for what you noticed in your previous comment.  I don't have the hardware in question so I can't tell for sure whether there is a problem there without more information.

I'm closing this issue as resolved.
