### ISSUE TITLE
FTBFS: dh_install: error: missing files, aborting

### ISSUE THREAD

**Issue by jean-christophe-manciot** [pwr-Solaar/Solaar#699]
Ubuntu 20.04 focal or Debian 11.0 bullseye
solaar 1.0.1-99-g955df30

Building with:
```
cd packaging
echo ------------------------------
echo Changing DPKG_BUILPACKAGE_OPTS
echo ------------------------------
sed -Ei "s|DPKG_BUILPACKAGE_OPTS=\"-b -us -uc\"|DPKG_BUILPACKAGE_OPTS=\"-i -I --no-sign --build=binary>'\"|g" build_deb.sh

echo ---------------------------------------
echo Forcing debchange to accept our version
echo ---------------------------------------
sed -Ei "s|/usr/bin/debchange|/usr/bin/debchange -b|g" build_deb.sh

echo --------
echo Building
echo --------
./build_deb.sh
```
leads to:
```
...
   dh_install
dh_install: warning: Cannot find (any matches for) "usr/bin/" (tried in ., debian/tmp)

dh_install: warning: solaar missing files: usr/bin/
dh_install: warning: Cannot find (any matches for) "usr/share/solaar/" (tried in ., debian/tmp)

dh_install: warning: solaar missing files: usr/share/solaar/
dh_install: warning: Cannot find (any matches for) "usr/share/locale/" (tried in ., debian/tmp)

dh_install: warning: solaar missing files: usr/share/locale/
dh_install: warning: Cannot find (any matches for) "usr/share/icons/hicolor/scalable/apps/" (tried in ., debian/tmp)

dh_install: warning: solaar missing files: usr/share/icons/hicolor/scalable/apps/
dh_install: warning: Cannot find (any matches for) "usr/share/applications/" (tried in ., debian/tmp)

dh_install: warning: solaar missing files: usr/share/applications/
dh_install: warning: Cannot find (any matches for) "usr/share/applications/solaar.desktop" (tried in ., debian/tmp)

dh_install: warning: solaar missing files: usr/share/applications/solaar.desktop
dh_install: error: missing files, aborting
make: *** [debian/rules:12: binary] Error 25
```

**Comment by pfps** [comment]
How did you initiate the build?  I don't see that control file anywhere in the solaar repository.   Did this used to work?  If so, when was the last time it worked?   
There were some changes made to the Solaar packaging files in an attempt to force usage of python3.  It may be that these changes introduced your problem, but as I don't run a debian system so I don't think I can do the build to determine whether this is the case.

**Comment by jean-christophe-manciot** [comment]
> How did you initiate the build? I don't see that control file anywhere in the solaar repository. 

What control file?

> Did this used to work? If so, when was the last time it worked?

It used to work fine. The last time was with commit 11465f2 (20200218).

**Comment by FFY00** [comment]
This will be removed either way, you can always install Solaar with pip.

**Comment by jean-christophe-manciot** [comment]
```
# pip3 install solaar
Collecting solaar
  Downloading solaar-0.9.2.tar.gz (95 kB)
     |████████████████████████████████| 95 kB 3.6 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vrqos4wi/solaar/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vrqos4wi/solaar/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-vrqos4wi/solaar/pip-egg-info
         cwd: /tmp/pip-install-vrqos4wi/solaar/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vrqos4wi/solaar/setup.py", line 11, in <module>
        from solaar import NAME, __version__
    ModuleNotFoundError: No module named 'solaar'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by FFY00** [comment]
Oh, so you just want to install Solaar? I thought that you wanted to install from the latest master from the git repo.

If you want to install on Debian or Ubuntu there are some packages. If they aren't available in your version you may install Solaar with pip but from the git repo. We don't have access to pypi and 0.9.2 is incredible outdated.

**Comment by pfps** [comment]
This problem occurs because the Solaar in PyPI is very old.  The owner of the PyPI package is no longer active in maintaining Solaar.   I don't know how to obtain control of the package to update it.  If anyone knows how to do this, please comment here.

**Comment by pfps** [comment]
I guess I still don't understand just what you want to do.   You appear to be making some changes to the build process (the sed stuff) and then starting a build.   Why the changes?   Does the build process work without the changes?

Maybe @rijnhard can shed more light on this problem.

**Comment by pfps** [comment]
Closing due to no response from submitter.  If this is still a problem, please comment here.
