### ISSUE TITLE
Show the battery percent in the systray icon

### ISSUE THREAD

**Issue by pwr** [pwr-Solaar/Solaar#70]
From #69:

To have an option that shows in the tray icon the battery percent and not just the battery icon and how much battery it has. This would save the user from having to click on the Solaar icon, then on the specific mouse option to see the percent.

**Comment by pfps** [comment]
Isn't this already handled?  Solaar shows a battery icon for the device with the lowest batter.

**Comment by pfps** [comment]
The system tray shows icons - to also show percent would require some method to add that information to the icons in a way that takes into account the theme background colour.  This is too much effort unless someone steps up to do it.

**Comment by allanlaal** [comment]
@pfps what about letting the user set the foreground+background color or just have black/white and white/black there. this is an UX feature - it needs not be pretty

**Comment by pfps** [comment]
If someone wants to code this, it shouldn't be a problem.
