### ISSUE TITLE
Running solaar does not open solaar

### ISSUE THREAD

**Issue by WhyNotHugo** [pwr-Solaar/Solaar#701]
```
➜ solaar --version
solaar 1.0.1
```
**What happens**
When running `solaar`, it does not open the application itself. It _does_ add a try icon with a battery indicator or whatever.
Running `solaar` a second time _does_ open the application windo.

**Expected result**
Running an application should open the application (that's pretty much as obvious as it gets). I shouldn't need to run it twice.
If anyone wants just the try icon, something like `solaar --tray-icon` would probably work.

**Other notes**
I no longer have a tray bar set up on my desktop. So right now, running solaar once is a no-op. Running it twice actually opens the application.

**Comment by pfps** [comment]
This has been the behaviour of Solaar for a long time.
The version of Solaar in this repository has a new option to control startup - `solaar --window=only` opens the main window at startup and doesn't use a tray icon at all.

**Comment by WhyNotHugo** [comment]
> This has been the behaviour of Solaar for a long time.

Yes, that's correct.

>  The version of Solaar in this repository has a new option to control startup - solaar --window=only opens the main window at startup and doesn't use a tray icon at all.

I don't think this is a very sane default. Out of the box right now, running `solaar` does not open the application. This is very unintuitive (for any other application, running it opens it in foreground).

I've nothing against supporting a "run only in the background" scenario, but I don't think it should be the default for a desktop application.

**Comment by pfps** [comment]
@FFY00 Should the default behaviour of Solaar be changed so that without any arguments it starts with the main window open?  This would require fiddling with the installation process so that the autostart behaviour of Solaar doesn't change.

**Comment by FFY00** [comment]
I think so. Just bring back `solaar-autostart.desktop`.

**Comment by pfps** [comment]
OK.  I'll get this set up.  I'll probably also add something to the documentation.

**Comment by WhyNotHugo** [comment]
That was quick! Many thanks for looking into this! :)

**Comment by pfps** [comment]
I think that PR #711 makes solaar work the way you suggest, but please try it out by cloning this repository and running bin/solaar from it.
