### ISSUE TITLE
solaar: error: Logitech receiver not found

### ISSUE THREAD

**Issue by SuperShadowPlay** [pwr-Solaar/Solaar#705]
**Information**

- Solaar version: 1.0.1
- Distribution: Ubuntu 16.04
- Kernel version: Linux 4.4.0-174-generic x86_64 GNU/Linux
- `solaar show` output:
```
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <object repr() failed> ignored
solaar: error: Logitech receiver not found
```

**Describe the bug**
My receiver is plugged in (I'm using the connected keyboard to type this) but solaar does not detect it.

**To Reproduce**
1. Open solaar
2. Be disappointed

**Screenshots**
![solaar_did_oof](https://user-images.githubusercontent.com/42284150/76146869-c10be600-6064-11ea-82b9-90b391431fd5.png)

**Additional context**
I've restarted, updated, reinstalled, opened from terminal and gui, and used other usb ports. 

~I am using the version from the Ubuntu repo so maybe this is fixed in a new update?~ Before posting this I looked around a bit more, and tried running ./bin/solaar from a git clone. For this it says I don't have python-udev installed, even though I do have it installed. 

Opening solaar from the terminal also gives this warning:
```
** (solaar:9888): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-wCPa8vYmEi: Connection refused
Exception AttributeError: "'Receiver' object has no attribute '_devices'" in <object repr() failed> ignored
```
Help is much appreciated!

**Comment by pfps** [comment]
Which logitech receiver do you have?  To find out run `lsusb`.  Respond with the output.  Solaar doesn't handle all Logitech receivers.
Then Solaar needs to be able to read from the hidraw device for the receiver, but that doesn't appear to be the problem here.

**Comment by danielhultman** [comment]
+1 to this.

I also get this error on Ubuntu 18.04. I get the exact same error message when running `solaar show`.

Output for my unifying receiver when running `lsub`: _Bus 002 Device 008: ID 046d:c52b Logitech, Inc. Unifying Receiver_

I had some problems with permissions to access the usb device. But ran the shell script included and it seems like it solved it.

**Comment by pfps** [comment]
That receiver should be handled. 

Solaar now requires python3, but the dependencies might not be set up correctly for old distributions like Ubuntu 16.04.  There are some versions of Solaar that had problems with systems where the default python was python 2.7.  One thing to try is to explicitly use python3 as in `python3 bin/solaar`.

If you cloned the Solaar repository and are running from your copy, please provide `git describe --tags`.  
If you can't run from your copy of the repository, please provide the output of `bin/solaar -dd show`.

**Comment by SuperShadowPlay** [comment]
Okay so, this receiver has worked before, I updated my distro recently and that could be the cause of it.

- `python3 bin/solaar -dd show` gives [this huge output](https://pastebin.com/Zj3ufL6f)

- `python3 bin/solaar` outputs `Solaar: missing required package 'python-gi'`
I have looked for this package in pip and my package manager, but no luck.

- `bin/solaar` outputs `Solaar: missing required package 'python-pyudev'`
I'm assuming this is because it is being defaulted to python2.7 but figured it was worth putting in here.

- `git describe --tags` outputs `1.0.1-100-ga9acdbe`

- `lsusb` outputs
```
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 005: ID 0bda:58c2 Realtek Semiconductor Corp. 
Bus 001 Device 004: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
Bus 001 Device 006: ID 0cf3:0036 Atheros Communications, Inc. 
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Sorry for taking so long to respond, and thanks for the help!

**Comment by pfps** [comment]
Those missing package messages come from some Solaar code (in gtk.py) and might be slightly misleading.  One thing to make sure is that all the required packages from the installation directions have been installed, in their python3 versions.  (Use pip3 to install if python3 is not the default python on your system.)

bin/solaar should be running python3 because of the #! line, which should be #!/usr/bin/env python3

I might be able to set up a fresh Ubuntu 18.04 to checkout Solaar installation, but I won't be able to do this for a couple of days.

**Comment by SuperShadowPlay** [comment]
So I messed around with installing solaar on my machine, but no dice. Desperate troubleshooting has led to me installing solaar on an MX Linux 19.1 live usb I had lying around. [It worked completely fine](https://imgur.com/ksh7FfF.png) on the same hardware. I have a feeling that 4 years of distro development (Ubuntu 16.04 released April 2016, MX Linux 19.1 released last month) and me still using my first distro (I have done many questionable changes to it) might be why it worked on MX Linux but not my current set-up.

I'm going to chalk my issue up to me running an old distro, after having done this testing. I'm upgrading soon so I won't need to worry about it very long, so I'm going to close the issue. If @pfps, you think that this bug is worth looking into you can reopen the issue, but don't worry about it too much for my sake.

**Comment by pfps** [comment]
Yes, 16.04 is probably too old to worry much about.
If @danielhultman is still having problems, I will investigate further.

**Comment by danielhultman** [comment]
@pfps 

Got i working after a installing python3 and redid everything from the start, following the installation guide.

Thanks alot!
