### ISSUE TITLE
ltunify pairing error with K360: device timeout (1)

### ISSUE THREAD

**Issue by jj148719** [pwr-Solaar/Solaar#708]
Hi All,

I've been having some troubles with the pairing of my K360. 
Unfortunately, when pairing the keyboard - I receive the following as result:
```
ltunify pair
Please turn your wireless device off and on to start pairing.
Pairing result: Timeout (1)

```
Same result is achieved then the timeout is increased to the max value (255):
```
ltunify pair 255
Please turn your wireless device off and on to start pairing.
Pairing result: Timeout (1)

```
However, pairing is successful for other devices. 
Current ltunify output is as follows:
```
ltunify list
Devices count: 2
Connected devices:
idx=1	Mouse	Performance MX
idx=2	Mouse	MX Anywhere 2

```
```
ltunify receiver-info
Serial number: 7FF29D09
Firmware version: 012.009.00030
Bootloader version: BL.004.016
```

Any advice what to do next? How to debug this situation?
I'm suspecting a hardware issue, but the keyboard worked find on another Receiver until recently. But now, the keyboard seems stuck. 

Thanks in advance

**Comment by pfps** [comment]
This is the repository for `solaar`, which I understand to be somewhat of a successor to `ltunify`.  
If you want some help in getting `ltunify` to work you will have to find its current repository or other place to open an issue against it, but it may be that no one is maintaining `ltunify`.
My suggestion is to see whether `solaar` can do the pairing.  If it cannot, you can create a new issue here but please do include the requested information.

Closing as not being about `solaar`.
