### ISSUE TITLE
Update solaar in PyPI

### ISSUE THREAD

**Issue by pfps** [pwr-Solaar/Solaar#713]
PyPI is a lightweight way to install python packages and solaar is in it, at https://pypi.org/project/solaar/ so it should be possible to install solaar via `pip3 install --user solaar` (so long as the required system packages are installed).
However PyPI has solaar 0.9.2

Either solaar should be updated in or removed from PyPI.  My preference is to update.  @FFY00 Comments?
Edit:  I'm not sure if anyone can actually transfer ownership of this project so that it can be kept up to date.

See also Issue #370 and #699

**Comment by pfps** [comment]
I tried to contact Daniel Pavel directly, but have not received a response.
I am now trying other indirect methods.
If my attempts fail I will try to have the PyPI Solaar project transferred to me as an abandoned project.

**Comment by Lekensteyn** [comment]
@pfps Daniel was contacted by @FFY00 before, but unfortunately Daniel did not create the pypi entry. The maintainer is Thomas Grainger but he did not reply to the email sent on 22 March 2020.

**Comment by pfps** [comment]
Aah, the "owner" on the PyPI project just comes from the setup.py.  OK, I'll try to contact Thomas directly.

**Comment by pfps** [comment]
I just received a response from Thomas.  I've asked him whether he can transfer ownership.  I expect not, but I think I have to try before the PyPI people will transfer ownership to me.

**Comment by pfps** [comment]
@graingert  This is the issue about updating solaar on PyPI.

**Comment by graingert** [comment]
Hello, which PyPI account should I add? Or does one of you want to setup GitHub actions with `__token__`?

**Comment by pfps** [comment]
I'm pfps on PyPI.  I don't think token actions are needed at this time.

**Comment by FFY00** [comment]
You can also add me: `FFY00`

**Comment by graingert** [comment]
@pfps you should be able to upload now

**Comment by pfps** [comment]
Here's what I've done so far:
Checkout tag 1.0.1
Update the version numbers (they were 0.9.2)
Remove Daniel's email from setup.py
Create a source package
  python3 setup.py sdist
Upload to the test PyPI repository (using a token that I set up)
    python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
Delete all files that solaar installs
Install package globally
  sudo pip install -i https://test.pypi.org/simple/ solaar==1.0.1.1
Check that solaar works
Delete all files that solaar installs
Install package locally
  pip install -i https://test.pypi.org/simple/ solaar==1.0.1.1 --user
Check that solaar works

Everything looks OK so I'll try uploading to the real PyPI

**Comment by graingert** [comment]
Any chance of a wheel

**Comment by pfps** [comment]
Not for 1.0.1.   
setup.py in 1.0.1 uses disttools, not setuptools
(I could have fixed that up, I guess, but I just uploaded 1.0.1 to PyPI.)

The current verison of Solaar does use setuptools so wheel will work there.

**Comment by pfps** [comment]
OK, 1.0.1 is on PyPI.  Please see if it works for you.

The upload process is simple.  You have to have installed twine (and for current versions setuptools and wheel).  Then
1. Make sure that everything works - only one upload per release.
2. Prepare the distribution `python3 setup.py sdist`.
For current versions wheel should be done as well via `python3 setup.py sdist bdist_wheel`.
3. Upload to PyPI via `python3 -m twine upload dist/*`

Then installation can be done via `pip install solaar --user` or `sudo pip install solaar`.

**Comment by pfps** [comment]
Closing as completed.

Thanks, Thomas for your quick responses.

**Comment by pfps** [comment]
I uploaded a test version of solaar to the testing PyPI repository.   It has a wheel.

You can install it via `pip install -i https://test.pypi.org/simple/ solaar --user`
