### ISSUE TITLE
Keep records of battery charge per device

### ISSUE THREAD

**Issue by pwr** [pwr-Solaar/Solaar#72]
From #69:

Have the ability to check how long the batteries lasted. This can be accomplished by resetting a timer that only starts when it detects the battery at 100%. When the percent is at 100% the timer starts and it will only reset itself when the percent makes a huge jump, for example, changing from 50% battery to 100% which would only mean I changed to new batteries or the mouse was charged. This would at least give an estimate of how long the batteries lasted and can give the user an idea to benchmark 2 things: How good a Logitech mouse uses certain batteries and how long certain batteries last.

**Comment by pfps** [comment]
Closing due to no action and mostly out of scope.
