### ISSUE TITLE
"Battery Good" = low battery icon ?

### ISSUE THREAD

**Issue by AndKe** [pwr-Solaar/Solaar#723]
**Information**

- Output of `solaar show`:
```
sudo solaar show
[sudo] password for andre: 
Unifying Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:c52b
  Serial       : CD0A94D5
    Firmware   : 12.10.B0032
    Bootloader : 02.14
    Other      : AA.AA
  Has 3 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=131, 2=96

  1: Performance Mouse MX
     Codename     : Performance MX
     Kind         : mouse
     Wireless PID : 101A
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: 01396843
          Firmware: 15.01.B0062
        Bootloader: 02.11
             Other: 00.09
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Battery: full, discharging.

  2: Wireless Solar Keyboard K750
     Codename     : K750
     Kind         : keyboard
     Wireless PID : 4002
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: 72D5DF87
          Firmware: RQK 33.00.B0015
        Bootloader: DFU 00.02.B0003
     The power switch is located on the edge of top right corner.
     Supports 11 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: REPROG CONTROLS        {1B00}   
         5: WIRELESS DEVICE STATUS {1D4B}   
         6: unknown:1DF3           {1DF3}   hidden
         7: FN INVERSION           {40A0}   
         8: ENCRYPTION             {4100}   
         9: SOLAR DASHBOARD        {4301}   
        10: KEYBOARD LAYOUT        {4520}   
     Has 12 reprogrammable keys:
         0: MY HOME                    => HomePage                      is FN, FN sensitive, reprogrammable
         1: Mail                       => Email                         is FN, FN sensitive, reprogrammable
         2: SEARCH                     => Search                        is FN, FN sensitive, reprogrammable
         3: Calculator                 => Calculator                    is FN, FN sensitive, reprogrammable
         4: MEDIA PLAYER               => Music                         is FN, FN sensitive, reprogrammable
         5: Previous                   => Previous                      is FN, FN sensitive
         6: Play/Pause                 => Play/Pause                    is FN, FN sensitive
         7: Next                       => Next                          is FN, FN sensitive
         8: Mute                       => Mute                          is FN, FN sensitive
         9: Volume Down                => Volume Down                   is FN, FN sensitive
        10: Volume Up                  => Volume Up                     is FN, FN sensitive
        11: SLEEP                      => Sleep                         is FN, FN sensitive, reprogrammable
     Battery status unavailable.

  4: Wireless Solar Keyboard K750
     Codename     : K750
     Kind         : keyboard
     Wireless PID : 4002
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: A92EA88D
     The power switch is located on the edge of top right corner.
     Battery: unknown (device is offline).

Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c525
  Serial       : 0C0D3AA5
    Firmware   : 02.00.B0020
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: (none)

  1: MX Revolution
     Codename     : MX Revolution
     Kind         : mouse
     Wireless PID : 100C
     Protocol     : HID++ 1.0
     Serial number: 0C0D3AA5
     The power switch is located on the (unknown).
     Battery: unknown (device is offline).


```

**Describe the bug**
Observe that the screenshot below, says "good", yet the battery symbol is low, the LEDs on the mouse indicate good battery too.

**Screenshots**
![Screenshot from 2020-03-20 11-57-28](https://user-images.githubusercontent.com/1468842/77157807-629e2900-6aa2-11ea-8fb3-6fd52763bdaf.png)
![Screenshot from 2020-03-20 10-53-04](https://user-images.githubusercontent.com/1468842/77157815-65008300-6aa2-11ea-87a6-36aad6a28cb7.png)

**Additional context**
Thank you for Solaar

**Comment by pfps** [comment]
This probably the same problem as #608.  That issue was resolved by upgrading to the current version of Solaar from this repository.  Pease clone this repository and run bin/solaar from there to see if the battery icon problem persists.
Note that the version of Solaar in this repository currently has a bug that prevents unpairing in the GUI.

**Comment by pfps** [comment]
Closing due to no response from the submitter.

**Comment by AndKe** [comment]
Sorry for late feedback.
Yes, 1.0.2-rc1 works great.

**Comment by AndKe** [comment]
Correction: 
Please reopen this issue.
Solaar 1.0.2-rc1 having low battery alarm and the mouse, showing two of three LED's:

![20200413_003147](https://user-images.githubusercontent.com/1468842/79596158-59739c80-80e0-11ea-9053-d59dce040b7a.jpg)

**Comment by pfps** [comment]
Please provide output from `solaar show -dd`.

**Comment by AndKe** [comment]
"-dd" is not accepted:
andre@loke:~$ solaar show -dd
usage: solaar {show,probe,config,pair,unpair} ...
solaar: error: unrecognized arguments: -dd


sudo solaar show 
[sudo] password for andre: 
Unifying Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:c52b
  Serial       : CD0A94D5
    Firmware   : 12.10.B0032
    Bootloader : 02.14
    Other      : AA.AA
  Has 3 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=84, 2=117

  1: Performance Mouse MX
     Codename     : Performance MX
     Kind         : mouse
     Wireless PID : 101A
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: 01396843
          Firmware: 15.01.B0062
        Bootloader: 02.11
             Other: 00.09
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Battery: low, discharging.

  2: Wireless Solar Keyboard K750
     Codename     : K750
     Kind         : keyboard
     Wireless PID : 4002
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: 72D5DF87
          Firmware: RQK 33.00.B0015
        Bootloader: DFU 00.02.B0003
     The power switch is located on the edge of top right corner.
     Supports 11 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: REPROG CONTROLS        {1B00}   
         5: WIRELESS DEVICE STATUS {1D4B}   
         6: unknown:1DF3           {1DF3}   hidden
         7: FN INVERSION           {40A0}   
         8: ENCRYPTION             {4100}   
         9: SOLAR DASHBOARD        {4301}   
        10: KEYBOARD LAYOUT        {4520}   
     Has 12 reprogrammable keys:
         0: MY HOME                    => HomePage                      is FN, FN sensitive, reprogrammable
         1: Mail                       => Email                         is FN, FN sensitive, reprogrammable
         2: SEARCH                     => Search                        is FN, FN sensitive, reprogrammable
         3: Calculator                 => Calculator                    is FN, FN sensitive, reprogrammable
         4: MEDIA PLAYER               => Music                         is FN, FN sensitive, reprogrammable
         5: Previous                   => Previous                      is FN, FN sensitive
         6: Play/Pause                 => Play/Pause                    is FN, FN sensitive
         7: Next                       => Next                          is FN, FN sensitive
         8: Mute                       => Mute                          is FN, FN sensitive
         9: Volume Down                => Volume Down                   is FN, FN sensitive
        10: Volume Up                  => Volume Up                     is FN, FN sensitive
        11: SLEEP                      => Sleep                         is FN, FN sensitive, reprogrammable
     Battery status unavailable.

  4: Wireless Solar Keyboard K750
     Codename     : K750
     Kind         : keyboard
     Wireless PID : 4002
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: A92EA88D
     The power switch is located on the edge of top right corner.
     Battery: unknown (device is offline).

Nano Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c525
  Serial       : 0C0D3AA5
    Firmware   : 02.00.B0020
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: (none)

  1: MX Revolution
     Codename     : MX Revolution
     Kind         : mouse
     Wireless PID : 100C
     Protocol     : HID++ 1.0
     Serial number: 0C0D3AA5
     The power switch is located on the (unknown).
     Battery: unknown (device is offline).

**Comment by pfps** [comment]
Oops, it's `solaar -dd show`  Sorry.

**Comment by AndKe** [comment]
no problem, thanks for looking into this.
please see https://gist.github.com/AndKe/9d941444ba0f85ed1fba1a40b709c60f

**Comment by pfps** [comment]
OK that log is useful.  Here is the relevant part
```
20:17:44,805    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 01 8107 030000]
Battery: low, discharging.
```
The problem in solaar is that low is turned into 20% and then to the caution icon.  I'll see if something better can be done.

**Comment by pfps** [comment]
OK, PR #739 should fix your problem.

Please test this out by cloning my repository and running from branch icons.  This should be possible via
```
git clone https://github.com/pfps/Solaar.git
cd Solaar
git checkout icons
bin/solaar
```
The icon for your mouse should no longer be the caution icon.

Note that your mouse was reporting low battery so expect the icon to reflect that.

**Comment by AndKe** [comment]
Yes, it turned orange now.  Earlier this evening, I charged it for a while, so I wanted to check if the LEDs indicated something suitable for orange, and toggled the power switch of the mouse, that made the icon update to "full" and all three LEDs were lit (so it is most likely about full.)

I can provide more feedback about the experience of the indicated level next time it gets close to low.

Visualizing battery level can be tricky, I have a laptop with an extended battery, Ubuntu (19.10) display a red battery icon when somewhere below 40% ... which translates to about three hours estimate. :)

Thank you.
