### ISSUE TITLE
1.0.2-rc1 shows 1.0.1 as version in About dialog

### ISSUE THREAD

**Issue by rathann** [pwr-Solaar/Solaar#725]
**Information**
- Solaar version (`git describe --tags` if cloned from Solaar repository): `1.0.2-rc1`
- Distribution: Fedora 31
- Kernel version (ex. `uname -srmo`): `5.5.10-200.fc31.x86_64`
- Output of `solaar show`: N/A

**Describe the bug**
Solaar **1.0.2-rc1** still shows **1.0.1** as the version in **About Solaar** GUI dialog.

**To Reproduce**
1. Right-click on the tray icon
2. Click on 'About Solaar'
3. See 1.0.1 instead of 1.0.2

**Additional context**
Indeed, it's still 1.0.1 at https://github.com/pwr-Solaar/Solaar/blob/master/lib/solaar/__init__.py#L22 .
Maybe tie the version to https://github.com/pwr-Solaar/Solaar/blob/master/setup.py#L15 (or vice-versa) even for releases so that it's not forgotten when making a release.

**Comment by pfps** [comment]
Hmm, yes.  I'm not sure what to do to fix up rc1.  Maybe just get this working right and go to rc2?

I just did a quick check for 1.0.1 in the code, and the only place that I could find was in __init__.py

**Comment by FFY00** [comment]
Yes, we just push a fix and release a -rc2 soon.
