### ISSUE TITLE
Solaar not respecting GNOME notification preferences

### ISSUE THREAD

**Issue by ricvelozo** [pwr-Solaar/Solaar#734]
**Information**

- Solaar version (`git describe --tags` if cloned from Solaar repository): 1.0.2-rc1
- Distribution: Fedora 31
- Kernel version (ex. `uname -srmo`): `5.5.13-200.fc31.x86_64`
- Output of `solaar show`:
```
Unifying Receiver
  Device path  : /dev/hidraw2
  USB id       : 046d:c52b
  Serial       : 7EC6952A
    Firmware   : 24.11.B0036
    Bootloader : 03.09
    Other      : AA.AD
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=169

  1: Wireless Mobile Mouse MX Anywhere 2S
     Codename     : MX Anywhere 2S
     Kind         : mouse
     Wireless PID : 406A
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 49256CFF
        Bootloader: BOT 57.00.B0003
          Firmware: MPM 13.00.B0003
          Firmware: MPM 13.00.B0003
             Other: 
     The power switch is located on the base.
     Supports 28 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
         7: CONFIG DEVICE PROPS    {1806}   internal, hidden
         8: CHANGE HOST            {1814}   
         9: REPROG CONTROLS V4     {1B04}   
        10: ADJUSTABLE DPI         {2201}   
        11: VERTICAL SCROLLING     {2100}   
            Roller type: 3G
            Ratchet per turn: 24
            Scroll lines: 0
        12: HIRES WHEEL            {2121}   
            Multiplier: 8
            Has invert
              Normal wheel motion
            Has ratchet switch
              Normal wheel mode
            High resolution mode
            HID notification
        13: DFUCONTROL UNSIGNED    {00C1}   
        14: DFUCONTROL SIGNED      {00C2}   
        15: unknown:1813           {1813}   internal, hidden
        16: unknown:1830           {1830}   internal, hidden
        17: unknown:1890           {1890}   internal, hidden
        18: unknown:1891           {1891}   internal, hidden
        19: unknown:18A1           {18A1}   internal, hidden
        20: unknown:18C0           {18C0}   internal, hidden
        21: unknown:1DF3           {1DF3}   internal, hidden
        22: unknown:1E00           {1E00}   hidden
        23: unknown:1EB0           {1EB0}   internal, hidden
        24: unknown:1803           {1803}   internal, hidden
        25: unknown:1861           {1861}   internal, hidden
        26: unknown:9001           {9001}   internal, hidden
        27: OOBSTATE               {1805}   internal, hidden
     Has 8 reprogrammable keys:
         0: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
             mse, pos:0, group:1, gmask:1
         1: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
             mse, pos:0, group:1, gmask:1
         2: MIDDLE BUTTON             , default: unknown:00A9                => MIDDLE BUTTON             
             mse, reprogrammable, divertable, pos:0, group:2, gmask:11
         3: BACK AS BUTTON 4          , default: BackEx                      => BACK AS BUTTON 4          
             mse, reprogrammable, divertable, pos:0, group:3, gmask:15
         4: FORWARD AS BUTTON 5       , default: BrowserForwardEx            => FORWARD AS BUTTON 5       
             mse, reprogrammable, divertable, pos:0, group:3, gmask:15
         5: LEFT SCROLL AS AC PAN     , default: HorzScrollLeftSet           => LEFT SCROLL AS AC PAN     
             mse, reprogrammable, divertable, pos:0, group:3, gmask:15
         6: RIGHT SCROLL AS AC PAN    , default: HorzScrollRightSet          => RIGHT SCROLL AS AC PAN    
             mse, reprogrammable, divertable, pos:0, group:3, gmask:15
         7: unknown:00D7              , default: unknown:00B4                => unknown:00D7              
             divertable, virtual, pos:0, group:4, gmask:0
     Battery: 50%, discharging.

```

**Describe the bug**
Solaar not respecting GNOME notification preferences. I get notifications of wake-up events.

**To Reproduce**
1. Go to GNOME Settings
2. Click on Notifications
3. Click on Solaar
4. Disable notifications
5. Let the mouse go to stand-by

**Screenshots**
![Captura de tela de 2020-04-07 17-34-22](https://user-images.githubusercontent.com/1834764/78716886-17837300-78f6-11ea-9c9e-54453999c381.png)

**Comment by pfps** [comment]
I'm running XFCE in Fedora.  When I turn off notifications for Solaar using the Notifications setting I no longer see notifications from Solaar.  
The code for Solaar notifications is in notify.py and it uses the GTK Notify gi interface.  I don't see anything wrong in the code.
So it should be possible to turn off Solaar notifications in GNOME if GNOME abides by the same standards that GTK uses for notifications.  If someone knows of any difference between XFCE and GNOME in this respect please speak up.

**Comment by FFY00** [comment]
Yes, this does not look like your bug. We just send the notification, the way it is handled by the notification daemon is not up to us.

**Comment by ricvelozo** [comment]
Tested now, turning off and on:

![Captura de tela de 2020-04-07 19-53-44](https://user-images.githubusercontent.com/1834764/78726969-bebdd580-7909-11ea-8bcb-74848dd77e4c.png)

**Comment by pfps** [comment]
So that appears to be a notification from Solaar.  If you have turned off notifications from Solaar in GNOME and this still appears, it appears that GNOME is not doing the right thing.  You should be able to turn on logging of notifications - in XFCE this is part of the Notification applet.  The application is part of the notification so you should be able to see whether you have blocked notifications from Solaar by examining the log.  As I don't use GNOME I don't know the details of how to log and view notifications.

**Comment by roshanshariff** [comment]
It looks like GNOME expects a "desktop-entry" hint to be set on the notification so that it knows which application the notification came from. See https://wiki.gnome.org/Initiatives/GnomeGoals/NotificationSource.

**Comment by pfps** [comment]
Solaar already sets the application name, which should sufficient to filter by application - it is in XFCE.
But if GNOME actually can filter on this hint I can add it.  Please provide information on the application that GNOME uses for this, not just a design document.

**Comment by roshanshariff** [comment]
With the change in this pull request, disabling notifications for Solaar in the GNOME settings indeed prevents the notifications appearing. I'm not entirely sure which component of GNOME actually parses this hint, but it is definitely part of the [standard](https://developer.gnome.org/notification-spec/#hints).

**Comment by pfps** [comment]
OK, if GNOME settings can filter out Solaar notifications with this change then that's what I was looking for.  But I still don't understand why GNOME is using something other than the app name, which is already part of the standard (not the GNOME standard, the Notification standard).   But this is mostly just my silly grousing - GNOME is what it is.

**Comment by roshanshariff** [comment]
Yeah, pretty much :) It appears GNOME wants notification settings to be
associated with the actual .desktop file that was used to launch the app,
which it also uses to populate the list of apps in the settings panel. I
guess this sort of makes sense, otherwise it would have to remember the app
names of all the notifications it has ever shown to allow users to disable
them (and you wouldn't be able to disable notifications until the app had
shown at least one notification).
