### ISSUE TITLE
M350 Pebble Mouse battery level reported as empty

### ISSUE THREAD

**Issue by sk8geek** [pwr-Solaar/Solaar#755]
**Information**

- Solaar version 1.0.1:
- Distribution: Fedora 31
- Kernel version: `Linux 5.6.6-200.fc31.x86_64 x86_64 GNU/Linux`
```
  2: Wireless Mouse M350
     Codename     : M350
     Kind         : mouse
     Wireless PID : 4080
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 2B442F40
     The power switch is located on the base.
     Battery status unavailable.
```

**Describe the bug**

The mouse battery is reported as empty. (reporting as requested in the devices readme file).

**Comment by pfps** [comment]
OK, I'll add this WPID to the file.
