### ISSUE TITLE
Solaar won't start without icon tray

### ISSUE THREAD

**Issue by lapega** [pwr-Solaar/Solaar#785]
When starting solaar in gnome terminal, using **--window=only**, gives this error:

> usage: solaar [-h] [-d] [-D PATH] [--restart-on-wake-up] [-V] [--help-actions] ...
> solaar: error: unrecognized arguments: --window=only

Wich is the correct argument?

Thanks!

-----------------------------------------
Solaar version 1.0.1
Ubuntu 20.04
Kernel 5.4

**Comment by pfps** [comment]
It appears that you are using a version of Solaar that does not have this option, which was only added on Feb 2 of this year.   If `solaar --help` does not list a --window option then to use this option you need a newer version of Solaar.

You can currently install and run a very recent version of Solaar via
```
pip install --user solaar==1.0.2rc3
~/.local/bin/solaar
```

**Comment by lapega** [comment]
Ok, I'm trying it now, seems to work.

I followed the instructions from github:

> Solaar's GUI normally uses an icon in the system tray and starts with its main window hidden. If Solaar is invoked with the --window=show option (the default) Solaar starts with its main window visible. If Solaar is invoked with the --window=hide option Solaar starts with its main window hidden. If solaar is invoked with the --window=only option Solaar does not set up an icon in the system tray and also starts with its main window showing.

**Comment by lapega** [comment]
Rebooted and now I got this:

> 
> Permissions error
> Found a Logitech Receiver (/dev/hidraw3), but did not have permission to open it.
> If you've just installed Solaar, try removing the receiver and plugging it back in.

This error didn't happen when using Solaar 1.0.1 installed using apt get.

**Comment by pfps** [comment]
The information in github is for the version of Solaar in github.  Older versions of Solaar will not have all the features of this most-recent version.

**Comment by pfps** [comment]
It looks as if you uninstalled Solaar using apt before using pip.

In this case you can install Solaar globally (including the udev rule and autostart file) and run via
```
sudo pip install solaar
/usr/local/bin/solaar
```
You should first uninstall Solaar via
```
pip uninstall solaar
```
For more information see the installation documentation for Solaar at https://pwr-solaar.github.io/Solaar/installation (the most relevant part is at the very end).
