### ISSUE TITLE
v1.0.2 Unifying Receiver window on start

### ISSUE THREAD

**Issue by heynnema** [pwr-Solaar/Solaar#791]
**Information**
Solaar 1.0.2
Ubuntu 20.04

When starting Solaar, a "Unifying Receiver" window opens each time. There doesn't seem to be a pref to change this behavior. This window shouldn't open unless requested from the Solaar menu.

**Comment by pfps** [comment]
This is indeed a behaviour change.   To not have the window show use `--window=hide` as described in the documentation.
