### ISSUE TITLE
Raspberry Pi 4 Issue

### ISSUE THREAD

**Issue by etatmirtna** [pwr-Solaar/Solaar#797]
I did a standard apt-get for the Solaar package install.  However, the M510 mouse is not working and the UI for it seems a bit jacked.  Also smooth scrolling and side scrolling toggles have warning triangles that have the popup "Read/Write operation failed".  The toggle buttons do not function either.  There's no recognition of the scroll wheel in any window.

**Comment by pfps** [comment]
What version of Solaar did you get (`solaar --version`)?   You may be installing an old version.  Please provide the information that is asked for when you create a bug report issue.

I was going to check out Solaar on my Pi 4, but didn't get around to it and now I won't be where my Pi is for a few months.

**Comment by etatmirtna** [comment]
Sorry...I checked the version and it is 0.9.2 - apparently that is the current distribution???  
I get the following also when I check the version:  /usr/share/solaar/lib/solaar/gtk.py:33: PyGIWarning:  Gtk was imported without specifying a version first.  Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.

I don't know anything about the version info it's presenting to me since I didn't build a custom copy of it.
__import__(module)
solaar 0.9.2

**Comment by etatmirtna** [comment]
Ok...so looking at the format for putting forth an issue I see that I'm putting forth the issue for 0.9.2 and that risk excoriation for doing so...why am I getting that with a package install from the Debian distro???

**Comment by etatmirtna** [comment]
The kernel version is 5.4.42-v7l+

**Comment by pfps** [comment]
The packaging of Solaar for distributions is handled by people who know about their distribution, but this means that the version of Solaar in a distribution might be quite a bit behind the current version.  Ubuntu, in particular, is often very behind, in general, not just for Solaar.   I thought that there might be something more recent for Debian, but maybe not, or maybe Raspbian isn't getting the most up-to-date Debian repositories.

There are several ways of installing a more recent version of Solaar.   Probably the easiest for you is to use pip.  Don't remove Debian install, as that presumably also installed the Solaar prerequisites.  You should be able to just do `sudo pip install solaar` to have the Solaar code and other files installed.  Then you can just run solaar (as long as you have /usr/local/bin in your path).

This will leave you in a slightly non-standard state, where uninstalling the Debian Solaar could remove some of the system stuff that Solaar depends on, making your pip install not work correctly.

For more information on installing Solaar, see `https://pwr-solaar.github.io/Solaar/installation`

**Comment by pfps** [comment]
> The kernel version is 5.4.42-v7l+

This should be OK for Solaar.
