### ISSUE TITLE
Incorrect packaging of the `/etc` directory

### ISSUE THREAD

**Issue by FFY00** [pwr-Solaar/Solaar#798]
**Information**

- Solaar version (`git describe --tags` if cloned from Solaar repository): `master`

**Describe the bug**
A Solaar wheel contains the following.
```tree
.install-cache/pkg/
├── etc
│   ├── udev
│   │   └── rules.d
│   │       └── 42-logitech-unify-permissions.rules
│   └── xdg
│       └── autostart
│           └── solaar.desktop
├── hidapi
│   ├── hidconsole.py
│   ├── __init__.py
│   └── udev.py
├── logitech_receiver
│   ├── base.py
│   ├── base_usb.py
│   ├── common.py
│   ├── descriptors.py
│   ├── hidpp10.py
│   ├── hidpp20.py
│   ├── i18n.py
│   ├── __init__.py
│   ├── listener.py
│   ├── notifications.py
│   ├── receiver.py
│   ├── settings.py
│   ├── settings_templates.py
│   ├── special_keys.py
│   └── status.py
├── solaar
│   ├── cli
│   │   ├── config.py
│   │   ├── __init__.py
│   │   ├── pair.py
│   │   ├── probe.py
│   │   ├── show.py
│   │   └── unpair.py
│   ├── configuration.py
│   ├── gtk.py
│   ├── i18n.py
│   ├── __init__.py
│   ├── listener.py
│   ├── tasks.py
│   ├── ui
│   │   ├── about.py
│   │   ├── action.py
│   │   ├── config_panel.py
│   │   ├── icons.py
│   │   ├── __init__.py
│   │   ├── notify.py
│   │   ├── pair_window.py
│   │   ├── tray.py
│   │   └── window.py
│   └── upower.py
├── solaar-1.0.2.data
│   ├── data
│   │   └── share
│   │       ├── applications
│   │       │   └── solaar.desktop
│   │       ├── icons
│   │       │   └── hicolor
│   │       │       └── scalable
│   │       │           └── apps
│   │       │               └── solaar.svg
│   │       └── solaar
│   │           └── icons
│   │               ├── light_000.png
│   │               ├── light_020.png
│   │               ├── light_040.png
│   │               ├── light_060.png
│   │               ├── light_080.png
│   │               ├── light_100.png
│   │               ├── light_unknown.png
│   │               ├── solaar-attention.svg
│   │               ├── solaar-init.svg
│   │               └── solaar.svg
│   └── scripts
│       ├── solaar
│       └── solaar-cli
└── solaar-1.0.2.dist-info
    ├── COPYING
    ├── METADATA
    ├── RECORD
    ├── top_level.txt
    └── WHEEL

22 directories, 61 files
```

`/etc` is wrongfully present at the top level, it shouldn't be there. Using a correct (follows the spec) installer, it would result in the file being installed to the python modules directory. Unfortunately, [PEP427](https://www.python.org/dev/peps/pep-0427/) does not specify any way of installing to `sysconfdir`, we should put it under `data` and copy it at runtime if not present.

Another thing, I don't think we should be shipping `hidapi` and `logitech_receiver` as top-level modules.

**To Reproduce**
`python setup.py bdist_wheel`

**Comment by pfps** [comment]
Solaar needs /etc/udev/rules.d/42-logitech-unify-pemissions.rules for proper operation, and /etc/xdg/autostart/solaar.desktop for autostart.  How should they be distributed?

I agree that hidapi and logitech_receiver should be dropped.

**Comment by pfps** [comment]
Also, it is probably time to drop bin/solaar-cli, as it has been deprecated since 2013.

How about trying for a 1.1 release with these changes?

**Comment by pfps** [comment]
Copying the udev file at runtime would require root access for solaar.
Copying the autostart file won't acheive the desired effect.

**Comment by FFY00** [comment]
> Also, it is probably time to drop bin/solaar-cli, as it has been deprecated since 2013.

Agreed.

> How about trying for a 1.1 release with these changes?

Why `1.1` instead of `1.0.3`?

> Copying the udev file at runtime would require root access for solaar.

You can use polkit to ask permission to the user. But you can also just install to `~/.local` instead.

Most people will be installing via package manager either way so they shouldn't run into this issue.

> Copying the autostart file won't acheive the desired effect.

How so?

**Comment by pfps** [comment]
1.1 because it removes something that is currently possible, and so probably should not be in a dot-dot release.

I don't think that udev will read files in ~/.local.  The file might better go in /lib/udev, but I don't think that this helps.  The autostart file needs to be in place before Solaar starts.  

It would be possible to just remove these files from setup.py and have them installed via package managers only.  This would mean that `sudo pip install solaar` would not install the files, but that might be OK.

**Comment by pfps** [comment]
If this is done, then Solaar should probably check for at least the udev file and complain if it is not present.

**Comment by pfps** [comment]
PR #799 has the changes, except the other top-level modules.
