### ISSUE TITLE
Remember DPI value

### ISSUE THREAD

**Issue by aleho** [pwr-Solaar/Solaar#80]
Every time I startup the system I have to reset the DPI value of my performance MX (it defaults to 900 it seems). Are you planning on implementing a setting for that or should that already be there and is broken here?

Back when I reverse engineered the DPI protocol I noticed that whenever the device went to sleep I had to reset the desired value after waking it up.

I haven't looked at the protocol, but is there a way to get a notification once the device is changing its state so the previously set DPI value can be applied? Or are you already doing that as well?

**Comment by oryband** [comment]
This is still an issue as of today with MX Master. DPI value not saved after turning mouse off and on again.

**Comment by jrbenito** [comment]
@oryband 

Did you test on git latest version?

thanks.

**Comment by oryband** [comment]
@jrbenito i think so, i'm using arch linux and I've installed this package:  https://aur.archlinux.org/packages/solaar-git/

**Comment by oryband** [comment]
opened #356 for this
