### ISSUE TITLE
No autostart in 1.0.2-1

### ISSUE THREAD

**Issue by Hotteterre** [pwr-Solaar/Solaar#805]
**Information**

- Solaar version: 1.0.2-1
- Manjaro Linux
- Kernel version (ex. `uname -srmo`): `Linux 5.7.0-3-MANJARO x86_64 GNU/Linux`
```
**Describe the bug**
Hello, in the stable version installed from Manjaro repository the autostart is no longer working.
Excuse me if I couldn't provide the complete infos, but in order to resolve the issue I now removed the package and installed the unstable version (solaar-git), that works effortlessly.
Thank you for the great work!

**Comment by pfps** [comment]
This should be reported to whoever is maintaining the Manjaro repository for Solaar.
It's not a problem that can be solved by changing Solaar itself.

**Comment by Hotteterre** [comment]
Thank you, I'lll report the issue to the Manjaro community.
Have a nice day!
