### ISSUE TITLE
MX Keys Spanish layout keys 49 and 94 interchanged

### ISSUE THREAD

**Issue by tcrossland** [pwr-Solaar/Solaar#809]
**Information**

- Solaar version 1.0.2
- Distribution: Arch Linux
- Kernel version (ex. `uname -srmo`): `Linux 5.7.2-arch1-1 x86_64 GNU/Linux`
- Output of `solaar show`:
```
Unifying Receiver
  Device path  : /dev/hidraw2
  USB id       : 046d:c52b
  Serial       : 730ED5EB
    Firmware   : 24.11.B0036
    Bootloader : 02.09
    Other      : AA.AC
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=44, 2=201

  1: MX Keys Wireless Keyboard
     Codename     : MX Keys
     Kind         : keyboard
     Wireless PID : 408A
     Protocol     : HID++ 4.5
     Polling rate : 20 ms (50Hz)
     Serial number: 8562413C
        Bootloader: BL1 08.00.B0011
          Firmware: MPK 12.00.B0011
             Other: 
     The power switch is located on the edge of top right corner.
     Supports 33 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: DEVICE FRIENDLY NAME   {0007}   
         7: BATTERY STATUS         {1000}   
         8: REPROG CONTROLS V4     {1B04}   
         9: CHANGE HOST            {1814}   
        10: HOSTS INFO             {1815}   
        11: BACKLIGHT2             {1982}   
        12: K375S FN INVERSION     {40A3}   
        13: ENCRYPTION             {4100}   
        14: LOCK KEY STATE         {4220}   
        15: KEYBOARD DISABLE       {4521}   
        16: MULTIPLATFORM          {4531}   
        17: DFUCONTROL SIGNED      {00C2}   
        18: DEVICE RESET           {1802}   internal, hidden
        19: unknown:1803           {1803}   internal, hidden
        20: CONFIG DEVICE PROPS    {1806}   internal, hidden
        21: unknown:1813           {1813}   internal, hidden
        22: OOBSTATE               {1805}   internal, hidden
        23: unknown:1830           {1830}   internal, hidden
        24: unknown:1890           {1890}   internal, hidden
        25: unknown:1891           {1891}   internal, hidden
        26: unknown:18A1           {18A1}   internal, hidden
        27: unknown:1DF3           {1DF3}   internal, hidden
        28: unknown:1E00           {1E00}   hidden
        29: unknown:1EB0           {1EB0}   internal, hidden
        30: unknown:1861           {1861}   internal, hidden
        31: unknown:1A20           {1A20}   internal, hidden
        32: unknown:18B0           {18B0}   internal, hidden
     Has 24 reprogrammable keys:
         0: unknown:00D1              , default: unknown:00AE                => unknown:00D1              
             nonstandard, divertable, persistently divertable, pos:0, group:0, gmask:0
         1: unknown:00D2              , default: unknown:00AF                => unknown:00D2              
             nonstandard, divertable, persistently divertable, pos:0, group:0, gmask:0
         2: unknown:00D3              , default: unknown:00B0                => unknown:00D3              
             nonstandard, divertable, persistently divertable, pos:0, group:0, gmask:0
         3: unknown:00C7              , default: unknown:00A3                => unknown:00C7              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:1, group:0, gmask:0
         4: unknown:00C8              , default: unknown:00A4                => unknown:00C8              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:2, group:0, gmask:0
         5: unknown:00E0              , default: unknown:00BF                => unknown:00E0              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:3, group:0, gmask:0
         6: unknown:00E1              , default: unknown:00C0                => unknown:00E1              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:4, group:0, gmask:0
         7: SHOW DESKTOP              , default: ShowDesktop                 => SHOW DESKTOP              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:5, group:0, gmask:0
         8: unknown:00E2              , default: unknown:00C1                => unknown:00E2              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:6, group:0, gmask:0
         9: unknown:00E3              , default: unknown:00C2                => unknown:00E3              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:7, group:0, gmask:0
        10: unknown:00E4              , default: Previous                    => unknown:00E4              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:8, group:0, gmask:0
        11: unknown:00E5              , default: Play/Pause                  => unknown:00E5              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:9, group:0, gmask:0
        12: unknown:00E6              , default: Next                        => unknown:00E6              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:10, group:0, gmask:0
        13: unknown:00E7              , default: Mute                        => unknown:00E7              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:11, group:0, gmask:0
        14: unknown:00E8              , default: Volume Down                 => unknown:00E8              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, pos:12, group:0, gmask:0
        15: unknown:00E9              , default: Volume Up                   => unknown:00E9              
             nonstandard, reprogrammable, divertable, persistently divertable, pos:0, group:0, gmask:0
        16: Calculator                , default: Calculator                  => Calculator                
             nonstandard, reprogrammable, divertable, persistently divertable, pos:0, group:0, gmask:0
        17: unknown:00BF              , default: unknown:009B                => unknown:00BF              
             nonstandard, reprogrammable, divertable, persistently divertable, pos:0, group:0, gmask:0
        18: unknown:00EA              , default: unknown:00C3                => unknown:00EA              
             nonstandard, reprogrammable, divertable, persistently divertable, pos:0, group:0, gmask:0
        19: Lock PC                   , default: WindowsLock                 => Lock PC                   
             nonstandard, reprogrammable, divertable, persistently divertable, pos:0, group:0, gmask:0
        20: unknown:00EC              , default: unknown:00B8                => unknown:00EC              
             nonstandard, divertable, persistently divertable, pos:0, group:0, gmask:0
        21: unknown:00EB              , default: unknown:00B6                => unknown:00EB              
             nonstandard, divertable, persistently divertable, pos:0, group:0, gmask:0
        22: unknown:00DE              , default: Do Nothing One              => unknown:00DE              
             is FN, pos:0, group:0, gmask:0
        23: unknown:0034              , default: Do Nothing One              => unknown:0034              
             nonstandard, pos:0, group:0, gmask:0
     Battery: N/A, full.

  2: Wireless Mouse MX Master
    ...
```

**Describe the bug**
When using the Logitech MX Keys (spanish layout) keyboard via the Unifying receiver using Solaar, key codes 94 and 49 are interchanged. The issue does not occur if I pair the keyboard with an onboard Intel AC-8265 bluetooth controller, although that has other issues.

I'm not sure whether this is an issue with Solaar, the unifying receiver, some hid module (possibly `hid_logitech_hidpp`), or something else.

**To Reproduce**
1. Pair MX Keys (spanish layout) with unifying receiver
2. Start xev
3. Press < (`less`) key
4. The following output is obtained:

```
KeyPress event, serial 34, synthetic NO, window 0x1000001,
    root 0x39e, subw 0x0, time 4882072, (-750,790), root:(1220,877),
    state 0x0, keycode 49 (keysym 0xba, masculine), same_screen YES,
    XLookupString gives 2 bytes: (c2 ba) "º"
    XmbLookupString gives 2 bytes: (c2 ba) "º"
    XFilterEvent returns: False
```

**Additional context**

I've also seen this issue which seems related:

 * https://askubuntu.com/questions/843590/key-keycode-49-and-key-keycode-94-are-inverted-on-macbookpro-keyboar

**Comment by pfps** [comment]
I expect that your keyboard is generating key codes (the actual bits sent from the keyboard - I'm not exactly sure what these are called in Linux) based on a different keyboard layout than you are expecting.   This does not look like a problem with Solaar, but a solution is likely to involve the MULTIPLATFORM {4531} feature.  If we get documentation on this feature it should be easy to add this feature to Solaar and then you can switch between layouts.  (Of course, I am guessing that the multi-platform feature does this.)

See also #784

**Comment by pfps** [comment]
I was just looking at the your output from ` solaar show` and your reprogrammable key information doesn't look like the documentation for that feature.   As I have just implemented reprogrammable keys I decided to try to handle the MX Keys as well, making a guess as to what being in group 0 means.

Could you please check this out by (after first quitting Solaar)
```
git clone https://github.com/pfps/Solaar
cd Solaar
git checkout keys-mx
bin/solaar
```
In the main window with the MX Keys selected you should see a new line with "Actions" and two selection boxes.  I expect that the left box will be showing something like "unknown:00D1" and the right box will be blank.  Click on the right box and select something that is not the first entry.  What should happen is that you have reprogrammed one key on your keyboard to the action of another.   (Don't worry,  this reprogramming will go away when you turn off the keyboard.)  Then open ~/.config/solaar/config.json.  You should see a line with "reprogrammable-keys" and one of the following lines should have two non-zero numbers (on the others the second number should be 0).  Please copy this line into a reply here.

You can then go back to using your regular Solaar and turn off and turn on your keyboard to remove the reprogramming.

I'm trying to get information on what all the unknown values are, but that might take a while.

**Comment by tcrossland** [comment]
@pfps thanks peter. I eventually managed to solve this issue by repairing the MX Keys with the Unifying receiver plugged into the linux machine. I think it had been paired previously while the receiver was plugged into a MacBook Pro. Feel free to close this issue and apologies if I've wasted your time.

I like the idea of being able to manage programmable keys in Solaar. I mapped action `unknown:00C7` to `unknown:00A3` and get the following entry in the `reprogrammable-keys` object in `config.json`:

`"199": 199`

Let me know if I can help with anything.

**Comment by sk8geek** [comment]
@tcrossland I'd be interested to know if, when using your MX Keys with Linux,the backlight comes on every (typically) 11 seconds even when your hands aren't near it. I'm pretty much it's not Solaar related. I've started to investigate USB traffic. I find it a little annoying when working late in a dark environment. Thanks

**Comment by tcrossland** [comment]
@sk8geek I've just tested this in a dark environment and it seems to work fine both with Linux via the unifying receiver and with the Macbook via bluetooth (the backlight remains off until my hands approach the keyboard). It also works fine in a not-so-dark environment.

**Comment by sk8geek** [comment]
Thanks @tcrossland - the environment doesn't affect the keyboard - it happens all of the time - I just find it more annoying in the dark :-) What Linux you running please? I'm Fedora 32 and the unifying receiver that also has a mouse paired with it. It doesn't happen when I BT to my phone, so I don't think it's the keyboard, probably a linux thing.

**Comment by pfps** [comment]
Reclassifying as an enhancement - implement multiplatform?

**Comment by tcrossland** [comment]
> Thanks @tcrossland - the environment doesn't affect the keyboard - it happens all of the time - I just find it more annoying in the dark :-) What Linux you running please?

Arch Linux, kernel 5.7.2. I also have an LTS kernel 4.16 which I’ll test when I have a chance.

**Comment by pfps** [comment]
I don't think that this issue is something that Solaar can help with.
My guess what Multiplatform was involved is wrong - multiplatform is for switching between windows and macs.
It would seem reasonable that one could change language layouts on these keyboards, but I don't see a feature for that.  I do see that Android has a method for switching languages, and some variants of Linux do as well, I believe, but that's not handled by the keyboard.
So I'm going to close this issue for now.
