### ISSUE TITLE
Works with MK345

### ISSUE THREAD

**Issue by DFF-fred** [pwr-Solaar/Solaar#816]
**Information**
- Solaar version: 1.0.1
- Distribution: Fedora (32)
- Kernel version (ex. `uname -srmo`): Linux 5.6.18-300.fc32.x86_64 x86_64 GNU/Linux
- Output of `solaar show`:
```
Nano Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c534
  Serial       : None
    Firmware   : 29.01.B0016
  Has 2 paired device(s) out of a maximum of 2.
  Has 18 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)

  1: Wireless Keyboard MK270
     Codename     : MK270
     Kind         : keyboard
     Wireless PID : 4023
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: 00000000
          Firmware: RQK 49.00.B0029
     Supports 18 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: BATTERY STATUS         {1000}   
         5: REPROG CONTROLS        {1B00}   
         6: WIRELESS DEVICE STATUS {1D4B}   
         7: FN INVERSION           {40A0}   
         8: ENCRYPTION             {4100}   
         9: KEYBOARD LAYOUT        {4520}   
        10: unknown:1810           {1810}   internal, hidden
        11: unknown:1830           {1830}   internal, hidden
        12: unknown:1890           {1890}   internal, hidden
        13: unknown:18A0           {18A0}   internal, hidden
        14: unknown:18B0           {18B0}   internal, hidden
        15: unknown:1DF3           {1DF3}   internal, hidden
        16: unknown:1E00           {1E00}   hidden
        17: unknown:1868           {1868}   internal, hidden
     Has 11 reprogrammable keys:
         0: MY HOME                    => HomePage                      is FN, FN sensitive, reprogrammable
         1: Mail                       => Email                         is FN, FN sensitive, reprogrammable
         2: SEARCH                     => Search                        is FN, FN sensitive, reprogrammable
         3: Calculator                 => Calculator                    is FN, FN sensitive, reprogrammable
         4: MEDIA PLAYER               => Music                         is FN, FN sensitive, reprogrammable
         5: Previous                   => Previous                      is FN, FN sensitive
         6: Play/Pause                 => Play/Pause                    is FN, FN sensitive
         7: Next                       => Next                          is FN, FN sensitive
         8: Mute                       => Mute                          is FN, FN sensitive
         9: Volume Down                => Volume Down                   is FN, FN sensitive
        10: Volume Up                  => Volume Up                     is FN, FN sensitive
     Battery: 30%, discharging.

  2: Wireless Mouse 
     Codename     : Wireless Mouse
     Kind         : mouse
     Wireless PID : 4058
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 00000000
          Firmware: RQM 57.03.B0009
     Supports 22 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: RESET                  {0020}   
         5: BATTERY STATUS         {1000}   
         6: unknown:1810           {1810}   internal, hidden
         7: unknown:1830           {1830}   internal, hidden
         8: DEVICE RESET           {1802}   internal, hidden
         9: unknown:1862           {1862}   internal, hidden
        10: unknown:1890           {1890}   internal, hidden
        11: unknown:18A0           {18A0}   internal, hidden
        12: unknown:18B1           {18B1}   internal, hidden
        13: REPROG CONTROLS V4     {1B04}   
        14: WIRELESS DEVICE STATUS {1D4B}   
        15: REMAINING PAIRING      {1DF0}   hidden
        16: unknown:1DF3           {1DF3}   internal, hidden
        17: unknown:1E00           {1E00}   hidden
        18: unknown:1E22           {1E22}   internal, hidden
        19: unknown:1EB0           {1EB0}   internal, hidden
        20: LOWRES WHEEL           {2130}   
            Wheel Reports: HID
        21: POINTER SPEED          {2205}   
            Pointer Speed: 1.34765625
     Has 3 reprogrammable keys:
         0: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
             mse, divertable, pos:0, group:1, gmask:1
         1: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
             mse, divertable, pos:0, group:1, gmask:1
         2: MIDDLE BUTTON             , default: MiddleMouseButton           => MIDDLE BUTTON             
             mse, reprogrammable, divertable, pos:0, group:2, gmask:3
     Battery: 70%, discharging.
```

**Describe the bug**
euh.. everything  works great ;-) but it's a MK345 which is not listed in supported devices and recognized as a MK270 in Solaar

**To Reproduce**
1. Use it :-)

Supported device said to open a bug, so here it is.

I should add that the Media Player key is launching the Settings panel under GNOME and the Fn+F12 keys does a print-screen while it seems to be a camera photo on it (keyboard already has a print-screen key so that's why I am wondering).
I didn't try:
         5: Previous                   => Previous                      is FN, FN sensitive
         6: Play/Pause                 => Play/Pause                    is FN, FN sensitive
         7: Next                       => Next                          is FN, FN sensitive

Thank you.

**Comment by pfps** [comment]
Thanks for the info.  

It's actually the WPID that determines what the device can do.  I'll add the MK345 to the devices documentation.

**Comment by DFF-fred** [comment]
For information the play/pause, backward and forward buttons work as expected. Any idea if it's possible to reprogram the 2 keys I'd like to do something else?

**Comment by pfps** [comment]
If you are asking whether it is possible to reprogram the keys on your keyboard the answer is probably not with Solaar as it currently is set up.   Making these keys do something else involves handling input events and turning them into something else.   At least that's my understanding - the documentation for this is hard to understand.

**Comment by DFF-fred** [comment]
I see. Well i'll leave without, I wasn't even expecting to have 10 keys doing all those fancy (not that useful though) things. So overall I am happy with my new toy! Thank you very much for your prompt help.

**Comment by DFF-fred** [comment]
and a small update related to functionalities . Looking at your supported device document the MK345 also support FN swap (it works). But then what is reprog keys?
Adding screenshots below for convenience.
![Screenshot from 2020-06-22 17-21-48](https://user-images.githubusercontent.com/5652441/85277249-48168a00-b4ad-11ea-97ae-0766748c8893.png)
![Screenshot from 2020-06-22 17-21-54](https://user-images.githubusercontent.com/5652441/85277255-4a78e400-b4ad-11ea-80da-44673e00ac71.png)

**Comment by pfps** [comment]
Reprogrammable keys is the ability to get one key to something different from what it usually does.  But some of that functionality requires support from the input driver.  Your keyboard has only that part of reprogrammable keys (and for a feature that has only that part) so Solaar can't actually reprogram any of your keys.  `solaar show` helpfully outputs the feature structuure, which even has a flag for the key to be reprogrammable, but all that really does (as far as I know) is to signal to Logitech software to show the key to users as being reprogrammable.
