### ISSUE TITLE
Solaar does not show an icon in Cinnamon system tray

### ISSUE THREAD

**Issue by rpellew** [pwr-Solaar/Solaar#843]
Hi

I just upgraded my system Linux Mint 20 with Cinnamon 4.6.6 desktop.

Solaar 1.0.2 does not show an icon in the system tray. There is a blank space which I can click on, so it is running and working, it just is not showing any icon.

It used to show an icon with Linux Mint 19.

**Comment by pfps** [comment]
There are a couple of things that could be going wrong.
Solaar could not be finding any icons.  To check this, look for battery icons in Solaar's main window.
The icon that Solaar is using might not be easily visible in the system tray.  The code for most system trays is old and is missing features.  So if you are using a dark theme the icon might be dark on dark.  For more information see https://pwr-solaar.github.io/Solaar/capabilities 
You can check the latter problem by starting Solaar with no Logitech devices turned on so that Solaar uses the Logitech icon instead of a battery icon.

**Comment by rpellew** [comment]
Hi pfps, thanks for your help.

It looks like Solaar is finding icons. 
You were right, I was using a dark theme, but I have just tried the light themes and it is the same.
It is very strange as it was working in the last release.

The space inbetween the green tick and the white shield icon is where Solaar is:
![Screenshot from 2020-07-10 15-26-54](https://user-images.githubusercontent.com/40216467/87165379-f9952800-c2c1-11ea-8c85-38254148da58.png)

![Screenshot from 2020-07-10 15-23-08](https://user-images.githubusercontent.com/40216467/87165364-f437dd80-c2c1-11ea-9a70-b20d0c8695fe.png)

**Comment by rpellew** [comment]
Hmm. When I unplug and plug my Logitech Unifying receiver, the Solaar icon appears briefly before disappearing. 
I wonder if there is one particular icon that is missing from my install (from the Ubuntu package)?

**Comment by pfps** [comment]
So Solaar is finding a battery icon - in the main window.  As you only have one device the same icon should show up in the tray.

Try running Solaar with --battery-icons=symbolic although that should make things worse.

Also, running with -dd and look for any warnings about icons, but you shouldn't see any.   

If nothing seems to be wrong, extract all the icon messages and post here.

**Comment by rpellew** [comment]
I tried with --battery-icons=symbolic, same missing icon.

I can't see anything out of the ordinary with -dd
[solaar log.txt](https://github.com/pwr-Solaar/Solaar/files/4906723/solaar.log.txt)

**Comment by pfps** [comment]
I don't see anything wrong either.  Solaar appears to be doing everything right but the icon does not show up.

The only possibility that I can see is that you are running in a directory that has one or more files called 
battery-*.  This seems to confuse something in icon handling.  (It may also be that having a file with the same name as the incon in the search path or in a parent or child directory confuses icon handling.)

**Comment by pfps** [comment]
If you are willing to do some testing, I can produce a version of Solar with debugging output so see more about what is going on here.

**Comment by TomasPech** [comment]
Hi,
I can only confirm. I updated to Linux Mint 20 and there is not battery icon in tray. 
When is computer fresh after rebooted I can see Solaar icon in tray but when I connect mouse with receiver by mouse move then is icon change to blank place.

Thanks to whole dev. team for work on Solaar 

added -dd Log:
[Solaar.log](https://github.com/pwr-Solaar/Solaar/files/4954768/Solaar.log)

**Comment by pfps** [comment]
Solaar selects icons by name.  It looks as if it is doing the right thing, selecting battery-low.   

One thing to try is to unpair your devices and see whether Solaar switches to a yellow Logitech logo.  But only do this if you have another mouse available!

I'll think about how to write a bit of debugging code to try to see more of what is going on.

**Comment by TomasPech** [comment]
After mouse unpair I can see "dummy" icon ![After_unpaor](https://user-images.githubusercontent.com/44266722/88096878-a6f81d80-cb97-11ea-8935-fd21d1f2058a.png) and few second latter is icon change to Solaar icon  ![FewSecondLatter](https://user-images.githubusercontent.com/44266722/88096951-c42cec00-cb97-11ea-95f0-ceddbc73e9fe.png)

Do you need also some -dd log recorded during this process ?

**Comment by pfps** [comment]
Hmm.  There might be two problems.

Can you run gtk3-icon-browser and search for 'battery'?  Then click on 'battery-low' and make sure that the icon looks correct in all the sizes displayed.  If this all looks good, then try for the other battery icons.  Post whether you found any problems.

It looks as if the solaar icon is available but not the solaar-attention icon.  Can you do:
```
find /usr -name 'solaar*svg' -ls
```
Post the result here.

**Comment by TomasPech** [comment]
There are low batteries icons:
![obrazek](https://user-images.githubusercontent.com/44266722/88098454-1838d000-cb9a-11ea-8fb4-e31733324345.png)


There is terminal output:
```
$ find /usr -name 'solaar*svg' -ls
 14180511     24 -rw-r--r--   1 root     root        23953 čen  6  2018 /usr/share/icons/Mint-X/apps/96/solaar.svg
 14549132      4 -rw-r--r--   1 root     root         3314 čec 21 11:47 /usr/share/icons/hicolor/scalable/apps/solaar.svg
 15208978      4 -rw-r--r--   1 root     root         3548 čec 21 11:47 /usr/share/solaar/icons/solaar-attention.svg
 15208980      4 -rw-r--r--   1 root     root         3314 čec 21 11:47 /usr/share/solaar/icons/solaar.svg
 15208979      4 -rw-r--r--   1 root     root         3329 čec 21 11:47 /usr/share/solaar/icons/solaar-init.svg
 12981483      4 -rw-r--r--   1 root     root         3314 zář  9  2015 /usr/share/app-install/icons/solaar.svg
 12854963      4 -rw-rw-r--   1 root     root         3314 kvě 22 02:43 /usr/local/share/icons/hicolor/scalable/apps/solaar.svg
 12854953      4 -rw-rw-r--   1 root     root         3548 kvě 22 02:43 /usr/local/share/solaar/icons/solaar-attention.svg
 12854954      4 -rw-rw-r--   1 root     root         3314 kvě 22 02:43 /usr/local/share/solaar/icons/solaar.svg
 12854955      4 -rw-rw-r--   1 root     root         3329 kvě 22 02:43 /usr/local/share/solaar/icons/solaar-init.svg
```

Hope that is helpful for you ...

**Comment by pfps** [comment]
Aha!  It looks as if those icons may not show up on a black background.  Many libraries that put an icon in the system tray area do not correctly adjust monochrome icons to a black background.  To check, change to an icon theme that uses colorful battery icons.  I think Mist is one of these.

**Comment by TomasPech** [comment]
I will try find some way how I can change icon style in tray but I can't see it now. 
Anyway, I guess that tray can handle symbolic icons well because there is one icon of full battery in tray 
![obrazek](https://user-images.githubusercontent.com/44266722/88101372-2983db80-cb9e-11ea-88f0-6d6e3179b6dd.png)

**Comment by pfps** [comment]
Then I'm stumped.  My best guess is that AppIndicator3 changed somehow and Solaar doesn't work with this version, but I don't have any way to check this.

The only other possibility is that you need to reboot (or at least log out and log in) for the changes in your theme to affect the system tray.  Or maybe you didn't kill and restart Solaar.

**Comment by TomasPech** [comment]
Yes, after icon change I rebooted PC even I was sure that restart will not help to flush right icon into tray because other icons were changed instantly after change icon set to Mint-Y.

**Comment by pfps** [comment]
Then I'm completely stumped.   I'm running Fedora and Solaar uses AppIndicator3 here as well, but the icons show up fine.

There are multiple ways to put icons into the System Tray so it may be other programs are using something besides AppIndicator3.

There is one last thing that might be worthwhile to try.   If you can install the Ayatana version of app indicator, Solaar with use it.  On Debian this is gir1.2-ayatanaappindicator3-0.1

**Comment by Klap-in** [comment]
Is there maybe a way to get in contact with a gnome and/or mint developer who know about the details of the indicators? This feels a bit like discovering something that should already possible.

**Comment by pfps** [comment]
The status of the system tray and app indicators is unclear.   I think Gnome has removed (or is removing) both of them.  So the answer may be:  "That's deprecated.  Use something else."  Also, a system developer is likely to want to have a cut-down program that exhibits the problematic behaviour, and Solaar certainly doesn't qualify!

**Comment by TomasPech** [comment]
Yes, maybe there is problem because also Signal(Electron app) had some [problems](https://github.com/signalapp/Signal-Desktop/issues/4132) with tray Icon in Cinnamon  . Seems that is something to do with "xapp-status-applet". Tomorrow I can try install gir1.2-ayatanaappindicator3-0.1 ...

**Comment by rpellew** [comment]
A strange thing has happened. I've been away for a few days, just did some updates and the icon has now suddenly started working.

It looks like it is possibly/probably a bug in Cinnamon, rather than solaar. 

linuxmint/cinnamon#9436

**Comment by pfps** [comment]
Good to know.

@TomasPech Are you still experiencing problems.?

**Comment by chris-aeviator** [comment]
for me the issue was that I ran solaar with sudo, after `chown myLinuxUsername /dev/hidraw3` and thus not needing to run solaar with sudo anymore the icon perfectly fine appears

**Comment by pfps** [comment]
Instead of chowning the hidraw device you should set up the udev rule as described in https://pwr-solaar.github.io/Solaar/installation

**Comment by jeblad** [comment]
Perhaps related, not sure, but sometimes the Gnome UI dies. I have not figured out why. In my case I suspect it is triggered by a USB/Bluetooth issue.

**Comment by pfps** [comment]
Closing as this appears to be fixed.

**Comment by Moilleadoir** [comment]
Not fixed! But probably a Cinnamon problem.
