### ISSUE TITLE
Fontconfig warning: "/etc/fonts/conf.d/65-droid-sans-fonts.conf" when launched from command line

### ISSUE THREAD

**Issue by MagicFab** [pwr-Solaar/Solaar#85]
These messages show up when solaar is launched from command line:

Fontconfig warning: "/etc/fonts/conf.d/65-droid-sans-fonts.conf", line 103: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/65-droid-sans-fonts.conf", line 138: Having multiple values in <test> isn't supported and may not work as expected

They seem to be only cosmetic, though.

**Comment by rakeshvarma146** [comment]
go to options--->remove selection of always start video.
now your problem will be solved.
