### ISSUE TITLE
Cannot unpair Unknown device from Unifying/Nano Receiver aka C-U0010

### ISSUE THREAD

**Issue by addas** [pwr-Solaar/Solaar#861]
Hello there!

I bought a Logitech Nano Receiver from AliExpress as I lost mine, it has

USB ID **_046d:c52f_** 
Firmware **_22.01.B0006_**
Notification: **_wireless software present_**

I am afraid it got MouseJack/SpyWare - Currently I am running **_Ubuntu_** dual-boot with Win10 but I am not worried from MouseJack vulnerability as 100m is within a safe zone of known people.

I cannot pair it with anything as I think the seller hacked it to limit 1 device and he already paired up with something which is:

_**Unknown device 4014
Battery "Unknown"
Wireless Link "Offline"
Index: 1
Wireless PID: 4014
Protocol: Unknown
Polling rate: 8ms (126KHz)
Serial: 8F24******_

Whenever I try to pair new legit Logitech Mouse/Keyboard I get error "Device not supported" which looks like the same issue with official Logitech Windows Software

**_20:15:28,220     INFO [MainThread] logitech_receiver.notifications: <NanoReceiver(/dev/hidraw9,3)>: pairing lock is closed
20:15:28,220  WARNING [MainThread] logitech_receiver.notifications: pairing error 2: device not supported
20:15:28,220     INFO [MainThread] logitech_receiver.notifications: <NanoReceiver(/dev/hidraw9,3)>: pairing lock is closed
20:15:28,220  WARNING [MainThread] logitech_receiver.notifications: pairing error 2: device not supported_**

So I think the solution is to unpair this shady Unknown Device with Wireless PID 4014 but it always fail!

**_20:18:42,130     INFO [MainThread] logitech_receiver.receiver: <NanoReceiver(/dev/hidraw9,3)>: found new device 1 (4014)
20:18:42,130    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 300000]
20:18:42,134    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 FF 83B5 308F2485B60400000001000000000000]
20:18:42,134    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 80B2 030100]
20:18:42,138    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F80 B20300]
20:18:42,138    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {80B2}: 3 = invalid value
20:18:42,138    ERROR [MainThread] logitech_receiver.receiver: <NanoReceiver(/dev/hidraw9,3)> failed to unpair device <PairedDevice(1,4014,?)>
solaar: error: failed to unpair device Unknown device 4014: 1_**

Any help would be appreciated :)

Note: I think the seller has hacked this Unifying receiver to sell it to me as single device Nano receiver.

**Comment by pfps** [comment]
First, which version of Solaar are you running (`solaar --version`)?

I doubt that the seller hacked the device.  Different receivers act in different ways.  I haven't run across the c52f receiver, but the Solaar code treats it somewhat specially.  I put in some changes for Nano receivers that may have affected how Solaar treats this receiver.

I think that all Nano receivers come paired with some device.  Many Nano receivers can only pair with certain devices, so you may be out of luck.

Your trace strongly indicates that your receiver is a typical Nano receiver that does not unpair.  Instead pairing replaces one device with another.  But you can't pair your new device, so either your receiver can't pair with that kind of device or it has exceeded its number of repairing attempts.

Anyway, please download the current version of Solaar, cd to the download directory, and post outputs of:

```
bin/solaar show
bin/solaar --dd unpair 1
bin/solaar -dd pair
```

**Comment by addas** [comment]
Hey pfps

Sorry for delay but I had some kind of holiday/festival.

After buying a genuine M171 Logitech Mouse with C-U0010 Receiver I noticed that the firmware that should come with the C-U0010 should be **_USB ID Unifiying: 046d:c534 Firmware: 29.01.B0016_** <--- This is my genuine C-U0010 Specs

Looks like the one I bought from AliExpress is 3rd party made and is not genuine Logitech.

Moreover I think they flashed **_USB ID 046d:c52f Firmware 22.01.B0006_** which is not made for this device which make sense why it is not working.

I can confirm that these Unifying models (or we should call them Nano) cannot unpair as you said and there should be a device in the firmware (Like the unknown device 4014) to be replaced later when pairing with the new mouse/keyboard as I also was unable to unpair the genuine C-U0010.

Solaar is working perfectly in the genuine C-U0010

I was running Solaar 1.0.1 for Ubuntu Universe but later updated using **"sudo add-apt-repository ppa:solaar-unifying/stable"** to the latest (I guess?) 1.0.2 as of 2nd of August 2020.




Please if you can advice me on how to flash genuine USB ID/firmware to the Chinese knockoff C-U0010 or if I can clone my genuine C-U0010 to the fake one with the wrong USB ID/firmware.

I can confirm that Solaar is working in my genuine devices!



Thank you very much for your hard work in development to bring Logitech to the Linux communuity!!! :smiley:

**Comment by addas** [comment]
These are the output of the latest Solaar --show (GitHub version), I cannot show -dd unpair as it is not compatible as you mentioned and I think it got deprecated!


                                                                                                                                                                                                                                                                               Modified  
Nano Receiver
  Device path  : /dev/hidraw10
  USB id       : 046d:c52f
  Serial       : B*****3A
    Firmware   : 22.01.B0006
  Has 1 paired device(s) out of a maximum of 1.
  Has 39 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)

  1: Unknown device 4014
     Codename     :
     Kind         : mouse
     Wireless PID : 4014
     Protocol     : unknown (device is offline)
     Polling rate : 8 ms (125Hz)
     Serial number: 8F*****6
     The power switch is located on the base.
     Battery: unknown (device is offline).

Nano Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:c534
  Serial       : None
    Firmware   : 29.01.B0016
  Has 2 paired device(s) out of a maximum of 2.
  Has 14 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)

  1: Wireless Keyboard MK270
     Codename     : MK270
     Kind         : keyboard
     Wireless PID : 4023
     Protocol     : HID++ 2.0
     Polling rate : 20 ms (50Hz)
     Serial number: 78DF12B5
          Firmware: RQK 49.00.B0029
     Supports 18 HID++ 2.0 features:
         0: ROOT                   {0000}
         1: FEATURE SET            {0001}
         2: DEVICE FW VERSION      {0003}
         3: DEVICE NAME            {0005}
         4: BATTERY STATUS         {1000}
         5: REPROG CONTROLS        {1B00}
         6: WIRELESS DEVICE STATUS {1D4B}
         7: FN INVERSION           {40A0}
            Swap Fx function: False
         8: ENCRYPTION             {4100}
         9: KEYBOARD LAYOUT        {4520}
        10: unknown:1810           {1810}   internal, hidden
        11: unknown:1830           {1830}   internal, hidden
        12: unknown:1890           {1890}   internal, hidden
        13: unknown:18A0           {18A0}   internal, hidden
        14: unknown:18B0           {18B0}   internal, hidden
        15: unknown:1DF3           {1DF3}   internal, hidden
        16: unknown:1E00           {1E00}   hidden
        17: unknown:1868           {1868}   internal, hidden
     Has 11 reprogrammable keys:
         0: MY HOME                    => HomePage                      is FN, FN sensitive, reprogrammable
         1: Mail                       => Email                         is FN, FN sensitive, reprogrammable
         2: Search                     => Search                        is FN, FN sensitive, reprogrammable
         3: Calculator                 => Calculator                    is FN, FN sensitive, reprogrammable
         4: MEDIA PLAYER               => Music                         is FN, FN sensitive, reprogrammable
         5: Previous                   => Previous                      is FN, FN sensitive
         6: Play/Pause                 => Play/Pause                    is FN, FN sensitive
         7: Next                       => Next                          is FN, FN sensitive
         8: Mute                       => Mute                          is FN, FN sensitive
         9: Volume Down                => Volume Down                   is FN, FN sensitive
        10: Volume Up                  => Volume Up                     is FN, FN sensitive
     Battery: 30%, discharging, next level 5%.

  2: Wireless Mouse M185 new
     Codename     : M185n
     Kind         : mouse
     Wireless PID : 4054
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 0*****B4
          Firmware: RQM 64.00.B0008
     Supports 20 HID++ 2.0 features:
         0: ROOT                   {0000}
         1: FEATURE SET            {0001}
         2: DEVICE FW VERSION      {0003}
         3: DEVICE NAME            {0005}
         4: RESET                  {0020}
         5: REPROG CONTROLS V4     {1B04}
            Actions: {'80': 80, '81': 81, '82': 82}
         6: WIRELESS DEVICE STATUS {1D4B}
         7: LOWRES WHEEL           {2130}
            Wheel Reports: HID
            HID++ Scrolling: False
         8: POINTER SPEED          {2205}
            Pointer Speed: 1.0
            Sensitivity (Pointer Speed): 256
         9: DEVICE RESET           {1802}   internal, hidden
        10: unknown:1810           {1810}   internal, hidden
        11: unknown:1830           {1830}   internal, hidden
        12: unknown:1850           {1850}   internal, hidden
        13: unknown:1869           {1869}   internal, hidden
        14: unknown:1890           {1890}   internal, hidden
        15: unknown:18B1           {18B1}   internal, hidden
        16: unknown:1DF3           {1DF3}   internal, hidden
        17: unknown:1E00           {1E00}   hidden
        18: unknown:1F03           {1F03}   internal, hidden
        19: unknown:1E80           {1E80}   internal, hidden
     Has 3 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Button
             mse, reprogrammable, pos:0, group:1, gmask:1
         1: Right Button              , default: Right Click                 => Right Button
             mse, reprogrammable, pos:0, group:1, gmask:1
         2: Middle Button             , default: Mouse Middle Button         => Middle Button
             mse, reprogrammable, divertable, pos:0, group:2, gmask:3
     Battery status unavailable.

**Comment by pfps** [comment]
Logitech receivers come with various looks.  The ones with the Unifying Logo should be able to pair with any Logitech device that also has the Unifying Logo.  Receivers without the Unifying Logo can only pair with certain Logitech devices.

Your Nano Receiver 046d:c534 is a receiver that does not unpair, and can only pair with MK270 (WPID 4023) keyboards and M185 (WPID 4054) mice.  Pairing in this receiver replaces a previously paired device.  These receivers also only have a limited number of pairings and then cannot pair at all. 

Your receiver 046d:c52f is also a nano receiver that might only be able to  pair with certain devices, but there is a report that it can pair with M185 mice with WPID 4055 as well as the mouse with WPID 4104 that yours is paired with.  It is very unlikely that this receiver will pair with either the MK270 keyboard or the M185 (WPID 4054) mouse.

Flashing Updating the firmware on these devices may stop them completely from working.  I have not updated firmware myself.   A particular release of firmware might only be suitable for particular receivers.

**Comment by pfps** [comment]
With the setup above the command to unpair the unknown device is 
```
solaar -D /dev/hidraw10 unpair 1
```
The -D flag selects the receiver and the last argument is the device number for the receiver.

You could try that to ensure that your receiver does not unpair.

**Comment by addas** [comment]
Dear pfps

I can confirm the case with these nano receivers as they cannot unpair and pair with new devices only as you mentioned previously.

I got this error:

**_solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/unpair.py", line 36, in run
    dev.receiver._unpair_device(number, True)  # force an unpair
  File "/usr/share/solaar/lib/logitech_receiver/receiver.py", line 556, in _unpair_device
    raise IndexError(key)
IndexError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 175, in run
    m.run(c, args, _find_receiver, _find_device)
  File "/usr/share/solaar/lib/solaar/cli/unpair.py", line 39, in run
    raise Exception('failed to unpair device %s: %s' % (dev.name, e))
Exception: failed to unpair device Unknown device 4014: 1_**

This issue is related to firmware and compatibility and that means your software is working perfectly.

You can close the issue now!

Thanks for your amazing help! :smile:
