### ISSUE TITLE
Complete support for mice Logitech M720 Triathlon

### ISSUE THREAD

**Issue by raspher** [pwr-Solaar/Solaar#867]
**Information**

- Solaar version (`solaar --version` and `git describe --tags`): 1.0.2
- Distribution: Fedora 32, KDE
- Kernel version (ex. `uname -srmo`): Linux 5.7.10-201.fc32.x86_64 x86_64 GNU/Linux
- Output of `solaar show` for the target device (if applicable):
```
[root@localhost raspher]# solaar show
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 972A9D0E
    Firmware   : 12.11.B0032
    Bootloader : 04.16
    Other      : AA.AA
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=172

  1: M720 Triathlon Multi-Device Mouse
     Codename     : M720 Triathlon
     Kind         : mouse
     Wireless PID : 405E
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: C2006356
        Bootloader: BOT 34.01.B0005
          Firmware: MPM 04.10.B0013
             Other: 
     The power switch is located on the base.
     Supports 36 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: CRYPTO ID              {0021}   
         7: DEVICE FRIENDLY NAME   {0007}   
         8: BATTERY STATUS         {1000}   
         9: CHANGE HOST            {1814}   
        10: HOSTS INFO             {1815}   
        11: REPROG CONTROLS V4     {1B04}   
        12: PERSISTENT REMAPPABLE ACTION {1C00}   
        13: POINTER SPEED          {2205}   
            Pointer Speed: 1.0
        14: VERTICAL SCROLLING     {2100}   
            Roller type: 3G
            Ratchet per turn: 24
            Scroll lines: 0
        15: DFUCONTROL UNSIGNED    {00C1}   
        16: DFUCONTROL SIGNED      {00C2}   
        17: DEVICE RESET           {1802}   internal, hidden
        18: unknown:1803           {1803}   internal, hidden
        19: CONFIG DEVICE PROPS    {1806}   internal, hidden
        20: OOBSTATE               {1805}   internal, hidden
        21: unknown:1813           {1813}   internal, hidden
        22: unknown:1830           {1830}   internal, hidden
        23: unknown:1861           {1861}   internal, hidden
        24: unknown:1890           {1890}   internal, hidden
        25: unknown:1891           {1891}   internal, hidden
        26: unknown:18A1           {18A1}   internal, hidden
        27: unknown:1DF3           {1DF3}   internal, hidden
        28: unknown:1E00           {1E00}   hidden
        29: unknown:1EB0           {1EB0}   internal, hidden
        30: unknown:18B1           {18B1}   internal, hidden
        31: unknown:1850           {1850}   internal, hidden
        32: unknown:1E22           {1E22}   
        33: unknown:1F03           {1F03}   internal, hidden
        34: unknown:18C0           {18C0}   internal, hidden
        35: HIRES WHEEL            {2121}   
            Multiplier: 8
            Has invert
              Normal wheel motion
            Has ratchet switch
              Normal wheel mode
            High resolution mode
            HID notification
     Has 9 reprogrammable keys:
         0: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
             mse, reprogrammable, pos:0, group:1, gmask:1
         1: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
             mse, reprogrammable, pos:0, group:1, gmask:1
         2: MIDDLE BUTTON             , default: MiddleMouseButton           => MIDDLE BUTTON             
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         3: BACK AS BUTTON 4          , default: BackEx                      => BACK AS BUTTON 4          
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         4: FORWARD AS BUTTON 5       , default: BrowserForwardEx            => FORWARD AS BUTTON 5       
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         5: LEFT SCROLL AS AC PAN     , default: HorzScrollLeftSet           => LEFT SCROLL AS AC PAN     
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         6: RIGHT SCROLL AS AC PAN    , default: HorzScrollRightSet          => RIGHT SCROLL AS AC PAN    
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         7: unknown:00D0              , default: unknown:00AD                => unknown:00D0              
             mse, reprogrammable, divertable, persistently divertable, pos:0, group:2, gmask:3
         8: unknown:00D7              , default: unknown:00B4                => unknown:00D7              
             divertable, virtual, pos:0, group:3, gmask:0
     Battery: 90%, discharging.

[root@localhost raspher]# 
```

**Is your feature request related to a problem? Please describe.**
Make it possible to reprogramm keys in GUI

**Describe the solution you'd like**
I don't have any solution ATM

**Additional context**
Key number 7 is probably the hidden one, below key 3 and 4, under the thumb - still don't know what it does
Key number 8 is probably for switching between paired devices.

**Also it would be nice to see that my mouse, Logitech M720 is supported by Solaar. **

**What works:**
 -  pointer speed
 -  Wheel invert
 -  it says that connection is encrypted
 -  notifications of baterry
 -  mouse wakes up by just moving, there is no need to click any button

**What does not work:**
 -  Wheel resolution (cannot see sensitivity slider of wheel)

**Questionable:**
 -  Battery is new, i am not sure it should be 90 or 100%. I am using the mouse for 0 days, since today.
 -  Device pairing - cannot see my phone and i don't have any other devices from Logitech.

**Comment by pfps** [comment]
The  battery levels from the device are approximate so starting at 90% (or even 70%) is expected.

The current version of Solaar supports reprogramming the keys on your mouse.  The easiest way to install a version of Solaar that has support for reprogramming keys is currently via `pip install --user solaar==1.0.3rc1` (because I just added the current version to PyPI).  This version also has names for the last two buttons and their actions.

I don't think that scroll wheel sensitivity can be adjusted except for changing between fast and slow.

**Comment by raspher** [comment]
@pfps Thanks for fast response! It's good to hear that those features are implemented in 1.0.3rc1, however i will wait for a stable release and then test it. It's all from my side, thank You!

Future TODO, after releasing 1.0.3:
- [ ] I don't see M720 on supported devices list

**Comment by pfps** [comment]
1.0.3 is likely to be just 1.0.3rc1

**Comment by pfps** [comment]
M720 added to supported devices list.

**Comment by bochen87** [comment]
Hi, is it possible to add Wheel resolution for this mouse?

**Comment by pfps** [comment]
Recent versions of Solaar (since 1.0.2 at least) should have the Scroll Wheel Resolution setting for your mouse.  Check in the main Solaar window.  If this setting is not there, post output of `solaar show`.  The relevant part is the HIRES WHEEL feature, as shown above.

Using this setting is not recommended in many situations as some Linux drivers also use and modify it, with the result that scrolling can be too slow or too fast.  Solaar can be told to ignore the setting to get around this problem.

**Comment by bochen87** [comment]
> Recent versions of Solaar (since 1.0.2 at least) should have the Scroll Wheel Resolution setting for your mouse. Check in the main Solaar window. If this setting is not there, post output of `solaar show`. The relevant part is the HIRES WHEEL feature, as shown above.
> 
> Using this setting is not recommended in many situations as some Linux drivers also use and modify it, with the result that scrolling can be too slow or too fast. Solaar can be told to ignore the setting to get around this problem.

thanks for the blazing fast reply!

Yeah, this setting exists and i have activated it. however on a 4k display, the scroll speed is just too slow. So i was looking for an option to adjust that. I ended up now using the `imwheel` application for that.

**Comment by pfps** [comment]
That is likely because of the interaction with the device driver.  Make the setting ignored to get around this interaction.  Solaar largely just fiddles with feature settings on the device so there are some things that it does not do.  (Solaar rules can go beyond this for some things, but not for the scroll wheel.)
