### ISSUE TITLE
Outdated python3-gobject on Ubuntu 19.10

### ISSUE THREAD

**Issue by jeblad** [pwr-Solaar/Solaar#872]
**Information**

Cloned the Github repo and tried to run it but found that it requested `python3-gobject`. I followed the description from [Manual installation](https://pwr-solaar.github.io/Solaar/installation).

```
john@hydra:~/spaces/solaar1$ ./bin/solaar
Solaar: missing required system package python3-gi or python3-gobject
```

Made a few attempts on workarounds, but they failed. This is on a Ubuntu 19.10 install, but checking it seems like the culprit is `python3-gobject`which existed in 14.04 LTS.

Note that 1.0.3rc1 installs properly.

This is on Ubuntu 19.10 (end of life), and I doubt there are any changes to Ubuntu 20.04, but I will check it out later.

```
john@hydra:~/spaces/solaar1$ uname -srmo
Linux 5.3.0-64-generic x86_64 GNU/Linux
```

**Comment by pfps** [comment]
Where did you get 1.0.3rc1 from?  It is essentially the same as the version here so I'm wondering why the difference.

**Comment by pfps** [comment]
Can you search for 'python3-gi*' and 'python3-gobject*' packages on your system, both installed and uninstalled?  It think that on Ubuntu this is done by
```
apt-cache search python3-gi
```
and
```
apt-cache search python3-gobject
```

**Comment by pfps** [comment]
OK, I'm taking the bug flag off this issue but I'll leave it open for a while.

**Comment by pfps** [comment]
Closing as almost certainly not a problem with Solaar.

**Comment by AI-medicine** [comment]
don't know if this is still helpful for you but I had the same problem I think, that it said:

"Solaar: missing required system package python3-gi or python3-gobject" after entering "solaar" in the terminal.

I tried sudo solaar in the terminal and it worked xD.

Hope that helps!

**Comment by pfps** [comment]
It is weird that using sudo fixed this problem.  Either the system packages are installed or not.

**Comment by kwonminki** [comment]
I had the same problem.
"Solaar: missing required system package python3-gi or python3-gobject" after entering "solaar" in the terminal.

When I tried "sudo solaar", it said : [Solaar: missing required package 'python-gi']

I tried to get packages but python3-gobject is not available.

> sudo apt-get install -y python3-gobject
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python3-gobject is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'python3-gobject' has no installation candidate

And also I already got python-gi & python3-gi
> sudo apt-get install -y python-gi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-gi is already the newest version (3.26.1-2ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 87 not upgraded.

> sudo apt-get install -y python3-gi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-gi is already the newest version (3.26.1-2ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 87 not upgraded.

What Can I do?

**Comment by pfps** [comment]
It looks as if you have several versions of Solaar on your system.  Current versions of Solaar require python3, and they explicitly ask for python3 versions of the gi packages.  So I think the first thing to do is to remove the old version of Solaar - the one you are running when you do `sudo solaar`.

Then you should find out which version of Solaar you are running when you run as `solaar`.  If this is not 1.0.6 you should update, probably using the stable Solaar ppa as descriped in https://github.com/pwr-Solaar/Solaar.  Then try running Solaar again.

The error message that you are seeing is ambiguous.  You don't need both  python3-gi and python3-gobject, just one of them.   So it is a bit puzzling that you are even getting this error as you have python3-gi installed.   It may be some interference between python-gi and python3-gi so I suggest trying to uninstall python-gi *if that doesn't interfere with other software you have loaded*.

You could also try to install using pip.

**Comment by kwonminki** [comment]
I am sure that "several versions of Solaar" is not the reason. Because I got same error msg at my first try.

1. I try to install solaar with : "pip install solaar".
2. Error msg (same with above)
3. I tried many different ways to solve problem.

I tried to get solaar by ubuntu software market? but it doesnt work.

And here is my way to solve it.

sudo add-apt-repository ppa:solaar-unifying/ppa
sudo apt-get update
sudo apt install solaar
sudo solaar

I think It is very ambiguous.

I hope my case is useful for your debugging.

**Comment by pfps** [comment]
Glad to hear that it is working for you.

I'll update the error message soon.

**Comment by pfps** [comment]
Error message fixed in PR #1195

**Comment by lephnut** [comment]
I install solaar based on the following link, and I try to install the latest version '1.1.3rc3'.
[There is no option for MX Anywhere 3 and uknown battery #1385](https://github.com/pwr-Solaar/Solaar/issues/1385)
I got the same error message when execute command 'solaar'
> $ solaar 
> Solaar: missing required system package python3-gi (in Ubuntu) or python3-gobject (in Fedora)

**Comment by lephnut** [comment]
> I install solaar based on the following link, and I try to install the latest version '1.1.3rc3'. [There is no option for MX Anywhere 3 and uknown battery #1385](https://github.com/pwr-Solaar/Solaar/issues/1385) I got the same error message when execute command 'solaar'.
> 
> > $ solaar
> > Solaar: missing required system package python3-gi (in Ubuntu) or python3-gobject (in Fedora)
> > $ sudo apt install python3-gi
> > Reading package lists... Done
> > Building dependency tree
> > Reading state information... Done
> > python3-gi is already the newest version (3.26.1-2ubuntu1).
> > 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Fixed, according to https://stackoverflow.com/questions/71369726/no-module-named-gi
