### ISSUE TITLE
Translations are not installed

### ISSUE THREAD

**Issue by lukasmichel** [pwr-Solaar/Solaar#873]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): `1.0.3rc1-4-gc1b6bf9`
- Distribution: Arch Linux 
- Kernel version (ex. `uname -srmo`): `Linux 5.7.9-arch1-1 x86_64 GNU/Linux`

**Describe the bug**
When installing solaar via pip as described in `docs/installation.md`, the translations from `po/*` are not installed.
`setup.py` yields paths in `share/locale/*/LC_MESSAGES/solaar.mo` as translations (`setup.py:22`), but those do not exist. They are only created by running `tools/po-compile.sh` but ignored by the gitignore file and thus not contained in this repository. 
When running `tools/po-compile.sh` before installing solaar from the repository via pip, the translations are correctly installed.

**To Reproduce**
1. Clone solaar
2. install solaar from the repository `pip install --user .`
3. run `LANGUAGE=de solaar`
4. Expected Behaviour: Text in solaar is in German. Actual Behaviour: Text is in English.
5. uninstall solaar `pip uninstall solaar`
6. run `tools/po-compile.sh`
7. `pip install --user .`
8. run `LANGUAGE=de solaar`
9. Now, solaar uses the German translations.

**Possible Solutions**
1. Keep the compiled translation files in the repository
or
2. Add a section to `installation.md` that explains how to install the translations together with solaar .
or
3. Make `setup.py` create the compiled translation files itself. However, I do not know if this is possible.

**Comment by pfps** [comment]
@FFY00 Which solution do you think is best?
I'm leaning towards adding just adding an instruction in `installation.md` to install the translations.

**Comment by pfps** [comment]
PR #874 adds a section to installation.md that should be adequate for solution 2.

**Comment by lukasmichel** [comment]
I think the section is good, but it won't help people who want to install solaar via pip from pypi. They would have to get the translation files from the repository and install them to the appropriate location manually. (Sorry for the late response, but I only thought of that now)

**Comment by pfps** [comment]
The PyPI version of Solaar has the translations included, at least for the recent versions, so all should be fine there.

**Comment by lukasmichel** [comment]
I didn't know that, thanks for the info. Then I think the section installation.md is the best solution.

**Comment by FFY00** [comment]
Can't we do this in `setup.py`?

See https://davesteele.github.io/development/2015/12/11/add-i18n-to-setup-py/
