### ISSUE TITLE
Translation string contains two unnamed arguments

### ISSUE THREAD

**Issue by jeblad** [pwr-Solaar/Solaar#881]
Two unnamed arguments that should be named. Only use unnamed arguments when it can't be confused, that is the string contains only a single argument.

The rationale for this is to be order agnostic, as some languages swap the order in some sentences. This can be tricky to get around for translators, but it is strictly speaking not a traditional bug. It is just extremely annoying.

- lib/solaar/listener.py:189

**Comment by pfps** [comment]
Yeah, I can see that this is a problem.
What's the best solution?    Is it using `format`?  Or do format strings work?

**Comment by pfps** [comment]
There are also some displayed strings that are constructed from pieces.  Should these be transformed into formatted strings?

**Comment by pfps** [comment]
This string was in a log message so it should not have been translatable.  The fix is thus easy.

**Comment by jeblad** [comment]
I don't know what's the best approach code-wise, I just know this to be a reoccurring issue during translation. English and Norwegian tend to swap the order of clauses in a sentence, and with positional arguments this will fail. Usually it is possible to rephrase, but people often complain it sounds “nenglish”. ;)
