### ISSUE TITLE
Translation string contains counted items

### ISSUE THREAD

**Issue by jeblad** [pwr-Solaar/Solaar#882]
Counted items may trigger shifts from singular to plural. Some languages have agreements between terms, and that can be difficult to handle in a single translate string.

If such changes are not handled properly the strings will become weird, and the translators will attempt to handle the multiple cases with parenthesis or other solutions. This can be tricky to get around for translators, but it is strictly speaking not a traditional bug. It is just extremely annoying.

- lib/solaar/ui/pair_window.py:140
- lib/solaar/ui/pair_window.py:208
- lib/solaar/ui/window.py:613

**Comment by pfps** [comment]
What's the best solution for this problem?  Making an if-then-else with separate branches for one and not-one?  What if the language considers zero to be singular?  (I don't know if there any such languages.)

**Comment by pfps** [comment]
Aah, it looks as if ngettext is the right solution.  I'll put in a PR with these changes.

**Comment by jeblad** [comment]
There are several [grammatical number systems](https://en.wikipedia.org/wiki/Grammatical_number). Usually it is possible to get away with just singular and plural.

**Comment by pfps** [comment]
Fixed by #883

**Comment by SlySven** [comment]
A more concise summery is hard-coded in the Qt I18n/L10n system, you might like to also take a look at: https://doc.qt.io/qt-5/i18n-plural-rules.html
