### ISSUE TITLE
locale.Error: unsupported locale setting exception when glibc locale files are not present

### ISSUE THREAD

**Issue by rathann** [pwr-Solaar/Solaar#905]
**Information**
- Solaar version: 1.0.3
- Distribution: Fedora
- Kernel version (ex. `uname -srmo`): `Linux 5.7.11-200.fc32.x86_64 x86_64 GNU/Linux`
- Output of `solaar show`: N/A

**Describe the bug**
Any solaar invocation is failing with a traceback when locale.setlocale() call fails, e.g. due to missing glibc locale files for the currently set locale.

**To Reproduce**
```
$ sudo dnf remove glibc-langpack-de
$ export LC_ALL=de_CH.UTF-8
$ export LANG=de_CH.UTF-8
$ solaar --help
Traceback (most recent call last):
  File "/usr/bin/solaar", line 59, in <module>
    import solaar.gtk
  File "/usr/lib/python3.8/site-packages/solaar/gtk.py", line 29, in <module>
    import solaar.i18n as _i18n
  File "/usr/lib/python3.8/site-packages/solaar/i18n.py", line 50, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib64/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
$ 
```

**Additional context**
Looks like #190 is still unfixed. Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1811313 .

**Comment by pfps** [comment]
The bugzilla bug report is restricted so I cannot see it.

**Comment by rathann** [comment]
Ah, sorry. It is indeed. I won't make it public without reporter's consent as it may contain sensitive data. It doesn't contain any useful information beyond what I posted here, though. This is 100% reproducible, just set locale to something not supported by current glibc install.

**Comment by pfps** [comment]
It seems to me that this is not a Solaar problem.   Googling the error results in several threads stating that the correct remedy is to set up your locale settings correctly.
One such thread is https://stackoverflow.com/questions/14547631/python-locale-error-unsupported-locale-setting/14548156

@FFY00 Any comments?

**Comment by rathann** [comment]
In principle, you are correct. However, this issue keeps cropping up in various places. In case of GUI, the user won't even see the error. If the user is clueless, they will be at a loss why solaar didn't launch. Maybe it should at least try to catch the exception and display a pop-up telling the user to install missing locale definition?

**Comment by FFY00** [comment]
I think Solaar should default to `C` if no locale is provided.

**Comment by pfps** [comment]
What happens in the GUI in this situation?  If something decent happens, then I don't think that anything is wrong in the Solaar GUI.

**Comment by pfps** [comment]
@FFY00  How does one fall back to the C locale?

**Comment by pfps** [comment]
I don't have that langpack installed but when I set LC_ALL and LANG as suggested I do not get an error with `solaar show` `solaar -dd` or `solaar --help`.  It looks as if there is something else going wrong in the user's system.

**Comment by rathann** [comment]
@pfps If you have `glibc-all-langpacks` installed then you do have it. Uninstall both.

**Comment by pfps** [comment]
Aaah.  That produces the error.

It looks as if ignoring exceptions from the setlocale statement ends up with the correct behaviour.  I'll put in a PR for that, but it will need to be tested.

**Comment by pfps** [comment]
@rathann  Could you get the reporter to test PR #907?

**Comment by pfps** [comment]
@rathann  I would like to have the PR (#907) that fixes the bug tested.

**Comment by rathann** [comment]
@pfps I tested this myself (since I can reproduce the issue) and #907 fixes it for me, thank you.

**Comment by pfps** [comment]
Thanks.
