### ISSUE TITLE
Support of Unifying Receiver behind a KVM switch

### ISSUE THREAD

**Issue by olaf-rogalsky** [pwr-Solaar/Solaar#908]
I have a "MX Master 3" mouse - paired to an unifying receiver - plugged into a keyboard-video-mouse switch (KVM). The receiver is not directly "passed through". Instead the KVM acts as an USB hub and pretends, that the connected mouse and keyboard are a "Microsoft Wired Keyboard 600" device with interfaces for keyboard and mouse.

Is it possible to make Solaar work with this kind of configuration?

Without really understanding, what I am doing, I tried so by adding the vendor and product ID of the "Microsoft Wired Keyboard 600" to base_usb.py and updateing "42-logitech-unify-permissions.rules" - with no success.

**Comment by pfps** [comment]
I know little about the underlying HID drivers but I don't think that this can work.  Solaar sends and receives messages using Logitech-specific extensions to the HID protocol that need to be sent to or come from a Logitech receiver.   I doubt that the faked-up device will do the right thing for these messages.

But maybe @FFY00 knows more about whether this can work.

**Comment by FFY00** [comment]
Well, it would if the KVM switch was properly implemented, which doesn't sound like. I recommend using a software solution like https://github.com/debauchee/barrier.

**Comment by pfps** [comment]
So this KVM switch  doesn't seem to allow Solaar to work.
I'm closing this issue   Feel free to reopen if there is something else that might be done.

**Comment by olaf-rogalsky** [comment]
Thanks, I already was expecting, that this won't work ...
