### ISSUE TITLE
Button assigments (reprogrammable keys)

### ISSUE THREAD

**Issue by pwr** [pwr-Solaar/Solaar#91]
Or better yet, use something already existing, like xbindkeys.

**Comment by Klap-in** [comment]
What is difference between this ‘general changing of button assignments’ and REPROG_CONTROLS as mentioned in #31 ?

If this general remapping should not be in Solaar, as being a not Logitech-specific feature, then I recommend adding good pointers to helpful tutorials of the other existing tools. My impression is that it is a regular ask question.

**Comment by pfps** [comment]
See #31 for information on a preliminary implementation of reprogrammable keys and buttons.

**Comment by pfps** [comment]
@Klap-in The Logitech REPROG_CONTROLS feature allows some keys or buttons to not do their normal thing but instead to what some other key or button does.  Only some keys or buttons can be reprogrammed and only as some other keys or buttons.  `solaar show` gives information on which keys or buttons can be reprogrammed (only those with reprogrammable in the output) and what they can be reprogrammed as (those whose group is in the gmask bit string - gmask bit string 3 allows groups 1 and 2).
There are lots of ways to retask input sequences in Linus. xbindkeys is one.  The description at https://wiki.archlinux.org/index.php/Xbindkeys is decent.  Most window managers have a similar functionality, which may be easier to use.
There are also ways in Linux to modify how the keyboard and mouse keystrokes are turned into input characters.  xmodmap and udev are tools to use here.   I'm not aware of good tutorials on these tools.

**Comment by pfps** [comment]
Closed by PR #810
