### ISSUE TITLE
Logitech receiver not found/Unpairable peripherals

### ISSUE THREAD

**Issue by codexcody** [pwr-Solaar/Solaar#910]
- Solaar version : 1.0.2
- Distribution: Kali Linux
- Kernel version (ex. `uname -srmo`): Linux 5.5.0-kali2-amd64 x86_64 GNU/Linux
- Output of `solaar show`: 
```
OUTPUT HERE
```
 solaar: error: Logitech receiver not found

**Describe the bug**
I'm using a Logitech G915TKL Keyboard along with it's Lightspeed USB receiver. Solaar  doesn't seem to be realizing the G915TKL's receiver other than to allow direct connection from the keyboard (non-bluetooth). I also have unifying and nano receivers. They are recognized by solaar, but won't pick up any other devices than the ones that are connected to each respective receiver by default. If there's a way that I can drop a log please let me know because I'd love to pair my Logitech peripherals.

**To Reproduce**
1. Go to Solaar icon
2. Click on the Solaar icon
3. It says no Logitech receiver found

**Comment by pfps** [comment]
It is entirely possible that Solaar does not know about this receiver.  Can you provide output of `lsusb`?  

To find out whether Solaar can handle this receiver directory, clone Solaar and edit lib/logitech_receiver/base_usb.py, adding the usb ID for the receiver.  Two lines need to be added - see the C539 receiver for an example.   Then run Solaar as root with debugging turned on (`sudo bin/solaar -dd`) and see whether the receiver shows up. 

To complete the implementation of this receiver you also need to edit rules/42-logitech-unify-permissions.rules, adding your receiver, and install the rule file - see "Installing Solaar’s udev rule" in https://pwr-solaar.github.io/Solaar/installation for more information.

**Comment by codexcody** [comment]
**C:\lib\logitech_receiver>** lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 258a:6a99 HK-ZYYK-US-A1-02-00 USB KEYBOARD
Bus 001 Device 003: ID 8087:0a2a Intel Corp. 
Bus 001 Device 016: ID 046d:c545 Logitech, Inc. USB Receiver
Bus 001 Device 002: ID 0079:18d6 DragonRise Inc. Mouse for Windows
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by codexcody** [comment]
**C:\home\...\Solaar\lib\logitech_receiver>** sudo solaar -dd
09:21:48,469     INFO [MainThread] root: language en_US (UTF-8), translations path None
09:21:48,556    DEBUG [MainThread] solaar.ui.tray: using Ayatana AppIndicator3
09:21:48,582     INFO [MainThread] solaar.upower: connected to system dbus, watching for suspend/resume events

(solaar:6001): Gtk-WARNING **: 09:21:48.608: Theme parsing error: gtk.css:2794:15: Not using units is deprecated. Assuming 'px'.
09:21:48,623    DEBUG [MainThread] solaar.ui: startup registered=True, remote=False
09:21:48,625    DEBUG [AsyncUI] solaar.tasks: started
09:21:48,625     INFO [MainThread] solaar.ui.notify: starting desktop notifications
09:21:48,632    DEBUG [MainThread] solaar.ui.icons: sys.path[0] = /usr/share/solaar/lib
09:21:48,633    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
09:21:48,633    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/share/solaar/icons
09:21:48,633    DEBUG [MainThread] solaar.ui.icons: looking for icons in /root/.local/share/solaar/icons
09:21:48,633    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/lib/share/solaar/icons
09:21:48,633    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/share/solaar/icons
09:21:48,633    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/local/share/solaar/icons
09:21:48,633    DEBUG [MainThread] solaar.ui.icons: looking for icons in /usr/share/solaar/icons
09:21:48,634    DEBUG [MainThread] solaar.ui.icons: icon theme paths: ['/usr/share/solaar/icons', '/usr/share/solaar/icons', '/root/.local/share/icons', '/root/.icons', '/usr/local/share/icons', '/usr/share/icons', '/usr/local/share/pixmaps', '/usr/share/pixmaps']
09:21:48,707     INFO [MainThread] solaar.listener: starting receiver listening threads
09:21:48,787    DEBUG [MainThread] solaar.ui: activate

(solaar:6001): Gdk-CRITICAL **: 09:21:48.959: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

**Comment by pfps** [comment]
This is a receiver that is not implemented in Solaar yet.  I have created PR #910 to fix this.  You need to test the fix to make sure that it works.


To download and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #910, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/910/head:pull_910
git checkout pull_910
```
To download a new version of the pull request, pull it into your branch for the request, as in:
```
git checkout pull_910
git pull origin pull/910/head:pull_910
```

If something is still not working, run `bin/solaar -dd` and paste the output here.

**Comment by pfps** [comment]
So is Solaar working with your receiver with your changes?

**Comment by codexcody** [comment]
It is not, I've changed the code in the base_usb.py to reflect the following:

**LIGHTSPEED_RECEIVER_C545 = _lightspeed_receiver(0xc545)**

**Comment by pfps** [comment]
You also have to add this receiver to ALL.

PR #910 has these changes.

**Comment by codexcody** [comment]
Got this error after trying to pull:
fatal: couldn't find remote ref pull/910/head

**Comment by codexcody** [comment]
I fixed that one now it's this:

error: pathspec 'pull_910' did not match any file(s) known to git

**Comment by codexcody** [comment]
It  says merging is blocked

**Comment by pfps** [comment]
Sorry, I gave you the wrong number - the PR is #911 so use 911 instead of 910.

**Comment by codexcody** [comment]
![Screenshot_2020-08-09_10-14-06](https://user-images.githubusercontent.com/26265284/89735580-2c4d5000-da29-11ea-85c7-86cca112b1c6.png)

**Comment by codexcody** [comment]
It finally recognizes the lighspeed adapter but it won't recognize a bluetooth mouse I want to pair. Like if I turn it off and back on, it still won't pick up the connection.

**Comment by pfps** [comment]
Logitech receivers, at least the ones I know about,  don't pair with bluetooth devices.   So you can't do what you want to do, as far as I know.

Further, Lightspeed receivers generally only pair with the exact kind of device they come with and only one device.
