### ISSUE TITLE
Solaar missing from system tray

### ISSUE THREAD

**Issue by apelly** [pwr-Solaar/Solaar#918]
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

1.0.3-25-g5d744ce
Linux 5.4.0-43-generic x86_64 GNU/Linux

No sign of a  Solaar icon in a system tray area these days. Perhaps since upgrading to 20.04.

Not even sure what the "system tray" is bloody called these days. But you know what I mean... There's no quick access icon anywhere when Solaar is running.

Happy to do whatever research is required to give you whatever info you need to look into this. No idea what that might be at the moment though.

**Comment by apelly** [comment]
I just rebooted for an unrelated reason. When I logged in I saw the icon on the top right for a bit, then there was some kind of refresh and it went missing.

**Comment by pfps** [comment]
Is there an "empty" spot in the system tray?  Does clicking on that spot open the Solaar menu?  

Your report of the momentary icon indicates that there is a spot for Solaar in the system tray but that the battery icons are not showing up correctly.

This might the be same problem as #843 or it might be a problem with displaying monochrome icons in dark themes.

**Comment by apelly** [comment]
Ha! Bloody icon's a battery. Shame on me. :flushed:

Sorry for the noise.
