### ISSUE TITLE
Logitech VX revolution is not recognized

### ISSUE THREAD

**Issue by ddarwish** [pwr-Solaar/Solaar#921]
- Solaar version: 1.0.1
- Distribution: Ubuntu 20.04.1 LTS
- Kernel version: Linux 5.4.0-42-generic x86_64 GNU/Linux
- Output of `solaar show`:
$ solaar show
Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c518
  Serial       : 5F29CD09
    Firmware   : 42.04.B0044
  Has 1 paired device(s) out of a maximum of 0.
  Notifications: wireless (0x000100)

**Describe the bug**
Logitech VX revolution is not recognized

**To Reproduce**
Solaar always reports that "No device paired"

**Comment by pfps** [comment]
It looks as if the problem is that Solaar does not correctly support your receiver.  Have you used Solaar successfully in the past?  I think that the fix is very easy, so expect a PR for you to test soon.

**Comment by pfps** [comment]
PR #922 should fix your problem.


To download and work with Solar
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #922, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/922/head:pull_922
git checkout pull_922
```
To download a new version of the pull request, fetch it and then set your pull branch
to the new fetch, as in:
```
git checkout pull_922
git fetch origin pull/922/head
git reset --hard FETCH_HEAD
```

**Comment by ddarwish** [comment]
Hello
This is output of PR #922

$ ./solaar show
Nano Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c518
  Serial       : 5F29CD09
    Firmware   : 42.04.B0044
  Has 1 paired device(s) out of a maximum of 1.
  Notifications: wireless (0x000100)

  1: ? (0612)
     Codename     : ? (0612)
     Kind         : ?
     Wireless PID : 0612
     Protocol     : unknown (device is offline)
     Serial number: 5F29CD09
     The power switch is located on the (unknown).
     Battery: unknown (device is offline).

**Comment by pfps** [comment]
Well, that's better, but not ideal.  Please provide output of `./solaar -dd show`.

Was your mouse offline when you did `./solaar show`?  If so, make sure it is online for testing.

**Comment by pfps** [comment]
@ddarwish Also, what happens in the GUI (`./solaar`).

**Comment by ddarwish** [comment]
I use my mouse so I guess it is not offline.
I added  0612 to descriptors.py and rebuild app and than I get following output 

$ ./build/scripts-3.8/solaar -dd show
14:30:48,898    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 030000]
14:30:48,919    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 FF 83B5 035F29CD091900000000000000000000]
14:30:48,919    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 80B2 000000]
14:30:48,927    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 80B2 000000]
14:30:48,927    DEBUG [MainThread] solaar.cli: [/dev/hidraw1] => <NanoReceiver(/dev/hidraw1,3)>
14:30:48,973    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 8102 000000]
14:30:48,975    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8102 000100]
Nano Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c518
  Serial       : 5F29CD09
14:30:48,975    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 81F1 010000]
14:30:48,983    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 81F1 014204]
14:30:48,983    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 81F1 020000]
14:30:48,991    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 81F1 020044]
14:30:48,992    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 81F1 040000]
14:30:48,999    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F81 F10300]
14:30:48,999    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {81F1}: 3 = invalid value
14:30:48,999    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 81F1 030000]
14:30:49,007    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F81 F10300]
14:30:49,007    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {81F1}: 3 = invalid value
    Firmware   : 42.04.B0044
  Has 1 paired device(s) out of a maximum of 1.
14:30:49,007    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 8102 000000]
14:30:49,015    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8102 000100]
14:30:49,015    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 8100 000000]
14:30:49,023    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8100 000100]
  Notifications: wireless (0x000100)
14:30:49,023    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B3 000000]
14:30:49,031    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F83 B30200]
14:30:49,031    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {83B3}: 2 = invalid address
14:30:49,031    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 8102 000000]
14:30:49,039    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8102 000100]
14:30:49,039    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 200000]
14:30:49,047    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
14:30:49,047    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
14:30:49,047    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 040000]
14:30:49,071    DEBUG [MainThread] logitech_receiver.base: (3) => r[11 FF 83B5 0408100612480000000BB80000387800]
14:30:49,071     INFO [MainThread] logitech_receiver.receiver: <NanoReceiver(/dev/hidraw1,3)>: found new device 1 (0612)

14:30:49,071    DEBUG [MainThread] logitech_receiver.base: (3) pinging device 1
14:30:49,071    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 01 001D 0000FB]
14:30:49,079    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 01 8F00 1D0200]
14:30:57,084  WARNING [MainThread] logitech_receiver.base: (3) timeout (8.01/8.00) on device 1 ping
  1: VX Revolution
     Codename     : VX Revolution
     Kind         : mouse
     Wireless PID : 0612
     Protocol     : HID++ 1.0
14:30:57,085    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 200000]
14:30:57,087    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
14:30:57,087    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
14:30:57,088    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83B5 300000]
14:30:57,095    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F83 B50300]
14:30:57,095    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {83B5}: 3 = invalid value
14:30:57,095    DEBUG [MainThread] logitech_receiver.base: (3) <= w[10 FF 83D5 000000]
14:30:57,103    DEBUG [MainThread] logitech_receiver.base: (3) => r[10 FF 8F83 D50200]
14:30:57,103    DEBUG [MainThread] logitech_receiver.base: (3) device 0xFF error on request {83D5}: 2 = invalid address
     Serial number: 5F29CD09
     The power switch is located on the (unknown).
     Battery: unknown (device is offline).

**Comment by ddarwish** [comment]
![20200824_144005](https://user-images.githubusercontent.com/82774/91041094-17bbab00-e618-11ea-9b51-586a010b295d.jpg)

**Comment by pfps** [comment]
OK, so the GUI is looking reasonable.   But `./solaar show` shouldn't be saying that the device is offline.  Try `./solaar show again` and see whether it still shows as offline.

**Comment by ddarwish** [comment]
> Try `./solaar show again` and see whether it still shows as offline.

The same as previously :(

**Comment by pfps** [comment]
What is happening is that your receiver does not implement the protocol that Solaar expects.   There are attempts in Solaar to make allowances for some receivers, but this depends on figuring out just how that receiver differs from the published protocol.  The divergence here is that your receiver does not implement the part of the protocol that Solaar uses to determine whether a device is online, so Solaar thinks the device is offline.  Without some information on how your receiver works there isn't much that can be done.

So `solaar show` isn't going to work completely correctly.  As the Solaar GUI appears to be working correctly that shouldn't be too much of a problem for you, I think.

**Comment by pfps** [comment]
I added 0612 for the LX Revolution.  I'm going to merge the changes into Solaar so you won't have to run from the PR to have things most working.
