### ISSUE TITLE
UX: "next 50%" is not clear

### ISSUE THREAD

**Issue by rugk** [pwr-Solaar/Solaar#924]
I have a M720 and see this:
![grafik](https://user-images.githubusercontent.com/11966684/90924746-4f480e80-e3f0-11ea-8cc6-2a6840c3a028.png)

So the battery icon is not clear to me at all.
90% of course is self-explaining, but what does the small "(next 50%)" mean??

(image copied from libratbag, https://github.com/libratbag/libratbag/issues/1046)

**Comment by daalla** [comment]
just my 2 cents, I think it is still unclear at the moment, since I had to google and get into this issue to understand that text. perhaps there could be a clearer message? or maybe a question mark icon that explain what does it mean. thanks!

**Comment by pfps** [comment]
In the current version of Solaar there is a tooltip on "Battery Level" or "Battery Voltage" that should be adequate.
