### ISSUE TITLE
FN key lock dont work with numkeys

### ISSUE THREAD

**Issue by survivor303** [pwr-Solaar/Solaar#935]
I'm not sure if this is just a Solaar issue or something different but when I put FN lock on with Solaar gui, it works with function keys but not with any other keybinding scenario.

With my K780 keyboard, it needs FN key to be included combo shift+home/end/pageup/pagedown.. if I want select content with it. Somehow it dosnt want recognize those numkeys with shift, it needs then use FN key and if not, then shift just bypass numkey toggle (and turns numkey on).

Perhaps this is something what Solaar can manage by offering some fixed keybinding config from its gui?

**Comment by pfps** [comment]
All that Solaar is doing is telling the keyboard to do whatever it does for the Fn swap feature.   If that doesn't change the keyboard's behaviour the way you want, there is nothing Solaar can do more.

**Comment by survivor303** [comment]
Yes, sure but this was "feature request". and it isnt about me.

Solaar can do "fn lock" but i dont know why it not work like it should and perhaps there are people who has knowledge to solve this.

**Comment by pfps** [comment]
The bottom line is that Solaar can't do more here - if Fn swap only changes the behaviour of the Function keys then that all that it does.  Solaar doesn't have the capability of making arbitrary changes to key presses.  (Well, not with this feature.  If there is a different feature on the device than can make the change you want then Solaar could be enhanced to support that feature.  But I don't know of features that can change modifiers in arbitrary ways.)
