### ISSUE TITLE
Question to mouse tweaks outside of Solaar

### ISSUE THREAD

**Issue by ErikSteiner** [pwr-Solaar/Solaar#945]
So far I used Solaar on Manjaro from the official repository 1.0.3.
I added some tweaks via `/etc/X11/xorg.conf.d/` and a `mouse-tweaks.sh` via autostart (gnome).

I recently removed Solaar from autostart and I noticed an interesting thing. Even if I have those tweaks in place, the mouse behaves differently. Until now, I thought that with Solaar I only set the DPI to 1600, but it seems like it also changes the mouse movement.

So I would be happy to get some light on this thing..

/etc/X11/xorg.conf.d/50-mouse-acceleration.conf
```
Section "InputClass"
	Identifier "MX Master"
	Driver "libinput"
	MatchIsPointer "yes"
	MatchProduct "Logitech MX Master"
	Option "AccelProfile" "flat"
	Option "AccelSpeed" "-0.5"
	Option "AccelerationNumerator" "1"
	Option "AccelerationDenominator" "1"
	Option "AccelerationThreshold" "0"
EndSection
```
mouse-tweaks.sh
```
#!/bin/sh
xset m 0 0
xinput --set-prop 18 'libinput Accel Speed' -0.5                         
xinput --set-prop 18 'Coordinate Transformation Matrix' 1.800000, 0.000000, 0.000000, 0.000000, 1.800000, 0.000000, 0.000000, 0.000000, 1.000000
```

**Comment by pfps** [comment]
I don't think I can provide any help on how X11 processes mouse input.

**Comment by ErikSteiner** [comment]
Is it possible to get the information, which settings are applied to the mouse (before and after Solaar is launched), or which config file is used for the mouse (maybe it switches when launching Solaar)?

**Comment by pfps** [comment]
The settings Solaar pushes to devices are stored in ~/.config/solaar/config.json

**Comment by ErikSteiner** [comment]
Is the DPI setting somehow translated into X11, or other values? The DPI is the only thing that could matter, if only these settings are pushed to the device.

**Comment by pfps** [comment]
The Solaar DPI setting is only used to change the behaviour of the mouse, and only by Solaar. 
If Solaar is not running, nothing you did in Solaar should change the behaviour of the mouse (although Solaar might be enhanced at some time to make changes to permanent settings for the mouse).

So if Solaar is not running and you turn your mouse off and on, nothing that Solaar did should be affecting the mouse's behaviour.

Is it possible that Solaar is autostarted for you?  (Look for a process running solaar to check.)

**Comment by ErikSteiner** [comment]
I re-added Solaar to autostart, now it hides correctly. In the past I had an issue with Solaar, because it autostarted as `--window=show`.

From your answers I assume that the mouse is handled with a default DPI, until Solaar is executed. That would explain my observation. I guess all my questions were answered. Thank you.
