### ISSUE TITLE
Solaar insists on opening a window at login

### ISSUE THREAD

**Issue by electriceccentric** [pwr-Solaar/Solaar#946]
**Information**
- Solaar version: 1.0.3
- Distribution: Debian 10 (Buster), Gnome
- Kernel version: Linux 4.19.0-10-amd64 x86_64 GNU/Linux

Hello, I'm on Debian running version 1.0.3 and for some reason although I know Solaar is suppose to start with the window hidden it doesn't. I was previously running version 1.0.1 and didn't have this problem, it ran in the background with a icon in the top panel of Gnome like it should. I even tried multiple times to invoke the --window=hidden flag but it still opens the window at login. Am I missing a step to fix this?

**Comment by pfps** [comment]
`solaar --window=hide` works correctly for me as an autostart application under XFCE.

The default for Solaar is to show the window so you need to have the above flag in your autostart command.


```
> solaar --help
usage: solaar [-h] [-d] [-D PATH] [--restart-on-wake-up] [-w {show,hide,only}] [-b {regular,symbolic}] [-V] [--help-actions]
              ...

positional arguments:
  {show,probe,config,pair,unpair}
                        optional actions to perform

optional arguments:
  -h, --help            show this help message and exit
  -d, --debug           print logging messages, for debugging purposes (may be repeated for extra verbosity)
  -D PATH, --hidraw PATH
                        unifying receiver to use; the first detected receiver if unspecified. Example: /dev/hidraw2
  --restart-on-wake-up  restart Solaar on sleep wake-up (experimental)
  -w {show,hide,only}, --window {show,hide,only}
                        start with window showing / hidden / only (no tray icon)
  -b {regular,symbolic}, --battery-icons {regular,symbolic}
                        prefer regular / symbolic icons
  -V, --version         show program's version number and exit
  --help-actions        print help for the optional actions
```

**Comment by electriceccentric** [comment]
Can I ask which file I should be adding this flag to? Because maybe I'm putting this in the wrong place.

**Comment by pfps** [comment]
That depends on your window manager or distribution.  It could be /etc/xdg/autostart/solaar.desktop which should have 
```
Exec=solaar --window=hide
```
Look for files named solaar.desktop   If there is one without the `--window=hide` flag in an autostart directory then something should be changed.

**Comment by electriceccentric** [comment]
Thank you that worked perfectly! I was mistakenly editing the other .desktop.
