### ISSUE TITLE
The Solaar window opens each time I open my session

### ISSUE THREAD

**Issue by nclm** [pwr-Solaar/Solaar#947]
Each time I open my computer, I am greeted by this window:

![everytime](https://user-images.githubusercontent.com/923008/92990084-4f13ce00-f4d9-11ea-9fc7-a238e96887f0.png)

And it’s not that I don’t like Solaar – I do very much – but maybe I would appreciate having it being a little more discreet at start-up. Be there, but only as the icon, without opening the window each single time. I seem to remember that it was like this before… is there a way, an option somewhere, to have Solaar start minimised?

Thanks!

**Information**
- Solaar version: 1.0.2.1
- Distribution: Ubuntu 20.04
- Kernel version: 5.4.0-47-generic x86_64
- Output of `solaar show`:
```
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 6CDA9F0D
    Firmware   : 24.10.B0036
    Bootloader : 01.08
    Other      : AA.AD
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless (0x000100)
  Device activity counters: 1=127

  1: Wireless Mobile Mouse MX Anywhere 2
[… info omitted]

  2: Wireless Multi-Device Keyboard K780
[… info omitted]
```

**Comment by pfps** [comment]
Yes, indeed.  The autostart desktop file you are using does not have the `--window=hide` flag to start up Solaar without the main window showing.  This desktop file could be coming from your distribution of Solaar.

```
idefix stories> solaar --help
usage: solaar [-h] [-d] [-D PATH] [--restart-on-wake-up] [-w {show,hide,only}] [-b {regular,symbolic}] [-V]
              [--help-actions]
              ...

positional arguments:
  {show,probe,config,pair,unpair}
                        optional actions to perform

optional arguments:
  -h, --help            show this help message and exit
  -d, --debug           print logging messages, for debugging purposes (may be repeated for extra verbosity)
  -D PATH, --hidraw PATH
                        unifying receiver to use; the first detected receiver if unspecified. Example: /dev/hidraw2
  --restart-on-wake-up  restart Solaar on sleep wake-up (experimental)
  -w {show,hide,only}, --window {show,hide,only}
                        start with window showing / hidden / only (no tray icon)
  -b {regular,symbolic}, --battery-icons {regular,symbolic}
                        prefer regular / symbolic icons
  -V, --version         show program's version number and exit
  --help-actions        print help for the optional actions
```

**Comment by pfps** [comment]
I'm closing this issue as the response above describes the solution.

**Comment by nclm** [comment]
Hi, thanks for your reply.
I just checked, it seems to have it though:
![solaar](https://user-images.githubusercontent.com/923008/92994756-4fbe5b80-f4fd-11ea-9dab-f6b7898d8027.png)
Could it be something else?

**Comment by nclm** [comment]
Ok, forget about it, it seems I had several conflicting Solaar instances since #782. I removed everything and starting anew with one installed through `pip3 install --user solaar`. Now it does not show the window, not even the icon! But it seems to work.

**Comment by pfps** [comment]
The pip install doesn't install an autostart desktop slide so you need to do that yourself.
