### ISSUE TITLE
system tray icon not appearing

### ISSUE THREAD

**Issue by pfps** [pwr-Solaar/Solaar#957]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): 1.0.3-94-g0e1fb3b
- Distribution: Fedora 32
- Kernel version (ex. `uname -srmo`): `5.8.10

**Describe the bug**
Sometimes the system tray icon does not appear.
No errors are reported from Solaar or on the system log.
The problem occurs in bursts.
The problem is less frequent or non-existent with `--window=hide`.
Killing solaar, waiting for a few minutes, and then restarting solaar generally results in the tray icon appearing correctly.

**Additional context**
This appears to be a bug in the window tray implemenation, not in Solaar.

**Comment by prnsml** [comment]
Hi, are you using gnome, which version? And which extension do you use to have sytem tray icons?

I'm using this one and it seems to work correctly: 
https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by pfps** [comment]
I run XFCE in Fedora.  When I am writing new code for Solaar I often kill and restart the Solaar GUI multiple times in quick succession.  Once in a while I see no Solaar icon in the system tray.  But only once in a while.  It's quite mystifying.

**Comment by pfps** [comment]
As I haven't seen the problem in a few weeks I'm going to close this issue for now.
