### ISSUE TITLE
Solaar window opens after login to KDE

### ISSUE THREAD

**Issue by msdobrescu** [pwr-Solaar/Solaar#964]
**Information**

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository): solaar 1.0.3rc1
- Distribution: Sabayon
Operating System: Gentoo Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.0
Kernel Version: 5.7.0-sabayon
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7 CPU 920 @ 2.67GHz
Memory: 23,5 GiB of RAM
Graphics Processor: GeForce GTX 1060 6GB/PCIe/SSE2
- Kernel version (ex. `uname -srmo`): Linux 5.7.0-sabayon x86_64 GNU/Linux
- Output of `solaar show`:
```
Unifying Receiver
  Device path  : /dev/hidraw0
  USB id       : 046d:c52b
  Serial       : 77099BBB
    Firmware   : 12.03.B0025
    Bootloader : 02.15
    Other      : AA.AA
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=80, 2=132

  1: Marathon Mouse M705 (M-R0009)
     Codename     : M705 (M-R0009)
     Kind         : mouse
     Wireless PID : 101B
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: 7C44B18E
          Firmware: 17.01.B0017
        Bootloader: 02.06
             Other: 00.04
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Features: special buttons, scroll accel (0x420000)
     Battery: 55%, discharging.

  2: Wireless Illuminated Keyboard K800
     Codename     : K800
     Kind         : keyboard
     Wireless PID : 2010
     Protocol     : HID++ 1.0
     Polling rate : 20 ms (50Hz)
     Serial number: FFC65665
          Firmware: 22.01.B0019
        Bootloader: 02.01
             Other: 00.07
     The power switch is located on the top right corner.
     Notifications: keyboard illumination, battery status (0x100200).
     Features: (none)
     Battery: low, discharging.
```

**Describe the bug**
Upgrading the system, upgraded KDE too. As effect, everytime the system starts, after login, Solaar window opens.
This was never before, it opened in the system tray at that step. Please make it open in the tray from the start again.

**To Reproduce**
1. Login to KDE
2. Solaar window opens

**Screenshots**

**Additional context**

**Comment by pfps** [comment]
For a while now, Solaar opens its main window if not given any flag to do otherwise.  From the Solaar documentation:

```
Solaar's GUI normally uses an icon in the system tray and starts with its main window visible. The GUI can be started in several ways

    --window=show (the default) starts with its main window visible,
    --window=hide starts with its main window hidden,
    --window=only do not use the system tray, and start with main window visible.
```

To achieve the behaviour you want you have to add the `--window=hide` option.

**Comment by msdobrescu** [comment]
Thanks, should I file a bug to my distro's maintainers? Or to KDE? I presume the reason is the system tray integration.

**Comment by pfps** [comment]
If the desktop file that is starting up Solaar at login comes from your distribution then whoever packages Solaar for your distribution should update that file.   If you created that desktop file (even if it was quite a long time ago) then all that is needed is that it be updated.  The file is most likely `/etc/xdg/autostart/solaar.desktop`.

The reason for the change is that people were starting Solaar themselves and wondering what happened.

**Comment by msdobrescu** [comment]
It is opened from here, after installation:

![image](https://user-images.githubusercontent.com/7279637/94917915-2d937a00-04ba-11eb-9005-9d6925b044e8.png)

I have no /etc/xdg/autostart/solaar.desktop file.

**Comment by pfps** [comment]
I don't use KDE so I don't know where it stores its autostart files.   One thing to do, if you can, is to search for solaar.desktop files via `sudo find / -name solaar.desktop`.   If that doesn't work, you'll have to dig further.
