### ISSUE TITLE
Problem pairing keyboard K with mouse M170

### ISSUE THREAD

**Issue by pascencio** [pwr-Solaar/Solaar#967]
**Information**
- Solaar version 1.0.3
- Distribution: Manjaro Linux
- Kernel version (ex. `uname -srmo`): `Linux 5.8.6-1-MANJARO x86_64 GNU/Linux`
- Output of `solaar show`:
```
Nano Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c534
  Serial       : None
    Firmware   : 29.01.B0016
  Has 1 paired device(s) out of a maximum of 2.
  Has 19 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)

  2: Wireless Mouse M185 new
     Codename     : M185n
     Kind         : mouse
     Wireless PID : 4054
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 00000000
          Firmware: RQM 64.00.B0008
     The power switch is located on the base.
     Supports 20 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: RESET                  {0020}   
         5: REPROG CONTROLS V4     {1B04}   
            Actions: {'80': 80, '81': 81, '82': 82}
         6: WIRELESS DEVICE STATUS {1D4B}   
         7: LOWRES WHEEL           {2130}   
            Wheel Reports: HID
            HID++ Scrolling: False
         8: POINTER SPEED          {2205}   
            Pointer Speed: 1.0
            Sensitivity (Pointer Speed): 256
         9: DEVICE RESET           {1802}   internal, hidden
        10: unknown:1810           {1810}   internal, hidden
        11: unknown:1830           {1830}   internal, hidden
        12: unknown:1850           {1850}   internal, hidden
        13: unknown:1869           {1869}   internal, hidden
        14: unknown:1890           {1890}   internal, hidden
        15: unknown:18B1           {18B1}   internal, hidden
        16: unknown:1DF3           {1DF3}   internal, hidden
        17: unknown:1E00           {1E00}   hidden
        18: unknown:1F03           {1F03}   internal, hidden
        19: unknown:1E80           {1E80}   internal, hidden
     Has 3 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Button               
             mse, reprogrammable, pos:0, group:1, gmask:1
         1: Right Button              , default: Right Click                 => Right Button              
             mse, reprogrammable, pos:0, group:1, gmask:1
         2: Middle Button             , default: Mouse Middle Button         => Middle Button             
             mse, reprogrammable, divertable, pos:0, group:2, gmask:3
     Battery status unavailable.
```

**Describe the bug**
I trying to pairing my keyboard with my mouse receiver M170. When solaar detect my keyboard K230. I get this error: 
Pairing failed: device not supported.
A new device was detected, but it is not compatible with this receiver.

**To Reproduce**
1. Open Sonnar
2. Connect the mouse receiver
3. Pair a new device

**Screenshots**
![image](https://user-images.githubusercontent.com/9783678/95005231-ef867b00-05cb-11eb-89c1-1ad04d895fa8.png)

![image](https://user-images.githubusercontent.com/9783678/95005288-feb9f880-05cc-11eb-9c65-70e3ea7867d6.png)

![image](https://user-images.githubusercontent.com/9783678/95005294-0e394180-05cd-11eb-884a-ef3833050a17.png)

**Additional context**
For some reason, solaar show me a wrong mouse version: 
1. Expected M170
2. I Get M185
The error says "device not supported", but in the solaar page I see that my keyboard is supported.
https://pwr-solaar.github.io/Solaar/devices

**Comment by pfps** [comment]
Solaar usually determines the name and codename (here M185n) for devices from a binary identifier (the Wireless PID, here 4054).  But this doesn't always work correctly, as some low-end devices share the same Wireless PID.   To check that this is the case please provide the output of `solaar probe` when both your devices are connected, which dumps the information that receiver is storing.

The error message is derived from information provided by your receiver.  There are several different kinds of receivers that Solaar support, but Solaar best supports Unifying receivers.  Your receiver is a Nano receiver.  Some Nano receivers act slightly differently from Unifying receivers and Solaar interpreted the message the receiver returned as saying that the receiver cannot pair with the device.  The message is slightly confusing, I agree.  

It appears that your Nano receiver can only pair with devices a limited number of times.  (But it is also possible that Solaar is misinterpreting the information provided by the receiver.)  If the number in the remaining pairings line decreases whenever you pair, you should realize that it is possible that your receiver will no longer be able to pair with a device when that number reaches zero.

**Comment by pascencio** [comment]
> Solaar usually determines the name and codename (here M185n) for devices from a binary identifier (the Wireless PID, here 4054). But this doesn't always work correctly, as some low-end devices share the same Wireless PID. To check that this is the case please provide the output of `solaar probe` when both your devices are connected, which dumps the information that receiver is storing.
> 
> The error message is derived from information provided by your receiver. There are several different kinds of receivers that Solaar support, but Solaar best supports Unifying receivers. Your receiver is a Nano receiver. Some Nano receivers act slightly differently from Unifying receivers and Solaar interpreted the message the receiver returned as saying that the receiver cannot pair with the device. The first part of the message is slightly confusing, I agree, but that is the Logitech wording for that error code in the Logitech documentation.
> 
> It appears that your Nano receiver can only pair with devices a limited number of times. (But it is also possible that Solaar is misinterpreting the information provided by the receiver.) If the number in the remaining pairings line decreases whenever you pair, you should realize that it is possible that your receiver will no longer be able to pair with a device when that number reaches zero.

OK, @pfps I will try your suggestion

**Comment by pfps** [comment]
You have the same Nano receiver that I have.  These receivers can definitely run out of re-pairings and then new devices cannot be paired with them.  
Your mouse reports the same information that my mouse reports.  This information was usually associated with a mouse that says M185 on its bottom.   The name isn't used for anything so I'm not too motivated to update the information for this product.

**Comment by pfps** [comment]
To see a bit more about your keyboard, please provide output of `solaar show` when the keyboard is active.

**Comment by pascencio** [comment]
> To see a bit more about your keyboard, please provide output of `solaar show` when the keyboard is active.

Hi @pfps,

My keyboard receiver is broken, so I am using solaar to use my keyboard with my mouse receiver.

This is the output for `solar show` command:

```shell
Nano Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c534
  Serial       : None
    Firmware   : 29.01.B0016
  Has 1 paired device(s) out of a maximum of 2.
  Has 19 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)

  2: Wireless Mouse M185 new
     Codename     : M185n
     Kind         : mouse
     Wireless PID : 4054
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 00000000
          Firmware: RQM 64.00.B0008
     The power switch is located on the base.
     Supports 20 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: RESET                  {0020}   
         5: REPROG CONTROLS V4     {1B04}   
            Actions: {'80': 80, '81': 81, '82': 82}
         6: WIRELESS DEVICE STATUS {1D4B}   
         7: LOWRES WHEEL           {2130}   
            Wheel Reports: HID
            HID++ Scrolling: False
         8: POINTER SPEED          {2205}   
            Pointer Speed: 1.0
            Sensitivity (Pointer Speed): 256
         9: DEVICE RESET           {1802}   internal, hidden
        10: unknown:1810           {1810}   internal, hidden
        11: unknown:1830           {1830}   internal, hidden
        12: unknown:1850           {1850}   internal, hidden
        13: unknown:1869           {1869}   internal, hidden
        14: unknown:1890           {1890}   internal, hidden
        15: unknown:18B1           {18B1}   internal, hidden
        16: unknown:1DF3           {1DF3}   internal, hidden
        17: unknown:1E00           {1E00}   hidden
        18: unknown:1F03           {1F03}   internal, hidden
        19: unknown:1E80           {1E80}   internal, hidden
     Has 3 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Button               
             mse, reprogrammable, pos:0, group:1, gmask:1
         1: Right Button              , default: Right Click                 => Right Button              
             mse, reprogrammable, pos:0, group:1, gmask:1
         2: Middle Button             , default: Mouse Middle Button         => Middle Button             
             mse, reprogrammable, divertable, pos:0, group:2, gmask:3
     Battery status unavailable.
```

**Comment by pfps** [comment]
This is the output when the keyboard is active and connected?  If so there is something that needs to be fixed.  Could you provide the output of `bin/solaar probe`?  This shows all the information that the receiver has.

**Comment by pascencio** [comment]
> This is the output when the keyboard is active and connected? If so there is something that needs to be fixed. Could you provide the output of `bin/solaar probe`? This shows all the information that the receiver has.

Yep! The keyboard is active and connected.Tomorrow I will give you the output that you ask me.

Good night!

**Comment by pascencio** [comment]
Here is the output @pfps:
 
```shell
sudo solaar probe
Nano Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c534
  Serial       : None
    Firmware   : 29.01.B0016
  Has 1 paired device(s) out of a maximum of 2.
  Has 19 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)
  Register Dump
    Notification Register 0x00: 0x000900
    Connection State      0x02: 0x000118
    Device Activity       0xb3: None
    Pairing Register 0xb5 0x00: None
    Pairing Register 0xb5 0x10: None
    Pairing Register 0xb5 0x20: None
    Pairing Register 0xb5 0x30: 0x30000000001A00000000000000000000
    Pairing Name     0xb5 0x40: b'Unknown name'
    Pairing Register 0xb5 0x01: None
    Pairing Register 0xb5 0x11: 0x118434B6111402000900000000000000
    Pairing Register 0xb5 0x21: 0x21A40840540A00020000000000000000
    Pairing Register 0xb5 0x31: 0x31000000000400000001000000000000
    Pairing Name     0xb5 0x41: b'Wireless Mouse'
    Pairing Register 0xb5 0x02: 0x0229010016880C0A0000000000000000
    Pairing Register 0xb5 0x12: None
    Pairing Register 0xb5 0x22: None
    Pairing Register 0xb5 0x32: None
    Pairing Name     0xb5 0x42: None
    Pairing Register 0xb5 0x03: None
    Pairing Register 0xb5 0x13: None
    Pairing Register 0xb5 0x23: None
    Pairing Register 0xb5 0x33: None
    Pairing Name     0xb5 0x43: None
    Pairing Register 0xb5 0x04: None
    Pairing Register 0xb5 0x14: None
    Pairing Register 0xb5 0x24: None
    Pairing Register 0xb5 0x34: None
    Pairing Name     0xb5 0x44: None
    Pairing Register 0xb5 0x05: None
    Pairing Register 0xb5 0x15: None
    Pairing Register 0xb5 0x25: None
    Pairing Register 0xb5 0x35: None
    Pairing Name     0xb5 0x45: None
    Firmware         0xf1 0x00: None
    Firmware         0xf1 0x01: 0x012901
    Firmware         0xf1 0x02: 0x020016
    Firmware         0xf1 0x03: None
    Firmware         0xf1 0x04: None
```
If you need anything else let me know.

Thanks again.

**Comment by pfps** [comment]
That output says to me that only one device is paired with this receiver.   Does the Solaar GUI indicate otherwise?  If so, what is shown in the extra-info box (click on the "i" to show this box) for each device?

**Comment by pascencio** [comment]
> That output says to me that only one device is paired with this receiver. Does the Solaar GUI indicate otherwise? If so, what is shown in the extra-info box (click on the "i" to show this box) for each device?

Sorry @pfps , my mistake. This is the output with 2 devices:

```
sudo solaar probe
[sudo] password for patricio: 
Nano Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c534
  Serial       : None
    Firmware   : 29.01.B0016
  Has 1 paired device(s) out of a maximum of 2.
  Has 19 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)
  Register Dump
    Notification Register 0x00: 0x000900
    Connection State      0x02: 0x000118
    Device Activity       0xb3: None
    Pairing Register 0xb5 0x00: None
    Pairing Register 0xb5 0x10: None
    Pairing Register 0xb5 0x20: None
    Pairing Register 0xb5 0x30: 0x30000000001A00000000000000000000
    Pairing Name     0xb5 0x40: b'Unknown name'
    Pairing Register 0xb5 0x01: None
    Pairing Register 0xb5 0x11: 0x118434B6111402000900000000000000
    Pairing Register 0xb5 0x21: 0x21A40840540A00020000000000000000
    Pairing Register 0xb5 0x31: 0x31000000000400000001000000000000
    Pairing Name     0xb5 0x41: b'Wireless Mouse'
    Pairing Register 0xb5 0x02: 0x0229010016880C0A0000000000000000
    Pairing Register 0xb5 0x12: None
    Pairing Register 0xb5 0x22: None
    Pairing Register 0xb5 0x32: None
    Pairing Name     0xb5 0x42: None
    Pairing Register 0xb5 0x03: None
    Pairing Register 0xb5 0x13: None
    Pairing Register 0xb5 0x23: None
    Pairing Register 0xb5 0x33: None
    Pairing Name     0xb5 0x43: None
    Pairing Register 0xb5 0x04: None
    Pairing Register 0xb5 0x14: None
    Pairing Register 0xb5 0x24: None
    Pairing Register 0xb5 0x34: None
    Pairing Name     0xb5 0x44: None
    Pairing Register 0xb5 0x05: None
    Pairing Register 0xb5 0x15: None
    Pairing Register 0xb5 0x25: None
    Pairing Register 0xb5 0x35: None
    Pairing Name     0xb5 0x45: None
    Firmware         0xf1 0x00: None
    Firmware         0xf1 0x01: 0x012901
    Firmware         0xf1 0x02: 0x020016
    Firmware         0xf1 0x03: None
    Firmware         0xf1 0x04: None

```

**Comment by pfps** [comment]
That output is only showing one connected device, at least as far as I can tell.   If there were other connected devices then there would be values for Pairing Register 0xb5 0x2N for N other than 1.  One other thing to try is to download Solaar from this repository and run probe, which has been updates to dump all registers, not just the ones whose purpose is known.

**Comment by pascencio** [comment]
> That output is only showing one connected device, at least as far as I can tell. If there were other connected devices then there would be values for Pairing Register 0xb5 0x2N for N other than 1. One other thing to try is to download Solaar from this repository and run `bin/solaar probe`, which has been updated to dump all registers, not just the ones whose purpose is known.

Ok @pfps, I will try that. Thanks!

**Comment by pascencio** [comment]
Hi @pfps 

This is the output

```shekk
[sudo] password for patricio: 
Nano Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:C534
  Serial       : None
    Firmware   : 29.01.B0016
  Has 1 paired device(s) out of a maximum of 2.
  Has 19 successful pairing(s) remaining.
  Notifications: wireless, software present (0x000900)

  Register Dump
    Notifications         0x00: 0x000900
    Connection State      0x02: 0x000118
    Device Activity       0xb3: None
    Pairing Register 0xb5 0x00: None
    Pairing Register 0xb5 0x01: None
    Pairing Register 0xb5 0x02: 0x0229010016880C0A0000000000000000
    Pairing Register 0xb5 0x03: None
    Pairing Register 0xb5 0x04: None
    Pairing Register 0xb5 0x05: None
    Pairing Register 0xb5 0x10: None
    Pairing Register 0xb5 0x20: None
    Pairing Register 0xb5 0x30: 0x30000000001A00000000000000000000
    Pairing Name     0xb5 0x40: b'Unknown name'
    Pairing Register 0xb5 0x11: 0x118434B6110A02000900000000000000
    Pairing Register 0xb5 0x21: 0x21A40840540A00020000000000000000
    Pairing Register 0xb5 0x31: 0x31000000000400000001000000000000
    Pairing Name     0xb5 0x41: b'Wireless Mouse'
    Pairing Register 0xb5 0x12: None
    Pairing Register 0xb5 0x22: None
    Pairing Register 0xb5 0x32: None
    Pairing Name     0xb5 0x42: None
    Pairing Register 0xb5 0x13: None
    Pairing Register 0xb5 0x23: None
    Pairing Register 0xb5 0x33: None
    Pairing Name     0xb5 0x43: None
    Pairing Register 0xb5 0x14: None
    Pairing Register 0xb5 0x24: None
    Pairing Register 0xb5 0x34: None
    Pairing Name     0xb5 0x44: None
    Pairing Register 0xb5 0x15: None
    Pairing Register 0xb5 0x25: None
    Pairing Register 0xb5 0x35: None
    Pairing Name     0xb5 0x45: None
    Firmware         0xf1 0x00: None
    Firmware         0xf1 0x01: 0x012901
    Firmware         0xf1 0x02: 0x020016
    Firmware         0xf1 0x03: None
    Firmware         0xf1 0x04: None

    Register Short   0x00 0x00: 0x000900
    Register Short   0x02 0x00: 0x000118
    Register Long    0xb5 0x02: 0x0229010016880C0A0000000000000000
solaar: assertion failed: Solaar/lib/logitech_receiver/common.py line 220
```

**Comment by pfps** [comment]
Thanks.  Unfortunately there is a bug in `bin/solaar probe`.  I think I have it fixed (but my C534 receiver doesn't exhibit the problem) so please update your clone of solaar and run `bin/solaar probe` again.

But looking into the information your receiver is reporting that it has only one connected device.  What is the GUI showing?

**Comment by pascencio** [comment]
@pfps the GUI show me 2 devices (like the screenshot attached in my issue).

**Comment by pfps** [comment]
Then the GUI is showing something that is not coming from show or probe.

If you have only one receiver then I'm stumped.  The only thing left to do is to run probe again with the current version of Solaar from this repository.

**Comment by pfps** [comment]
Also, click on the i button in the GUI and provide the contents of the part of the window on the bottom left.   Do this for the receiver and both devices.

**Comment by pfps** [comment]
Is this still an active problem?

**Comment by pfps** [comment]
Closed due to no response from submitter.
