### ISSUE TITLE
[SOLVED] Logitech K400 Plus trackpad settings

### ISSUE THREAD

**Issue by tjbrn** [pwr-Solaar/Solaar#972]
# Currently, there is no way to configure K400 Plus trackpad on Solaar
![image](https://user-images.githubusercontent.com/10359351/95528632-0c95c200-09af-11eb-81c9-020e44b206aa.png)

# Is expected some sort of configuration option for the integrated keyboard trackpad, like this:
![image](https://user-images.githubusercontent.com/10359351/95528778-744c0d00-09af-11eb-89ad-f4c8c152ba64.png)

# So, would be a usefull feature the possibility to change trackpad configuration (e.g. invert scroll, sensibility, disable gesture zoom...)

Actually, idk a way to configure K400 trackpad

**Comment by pfps** [comment]
Which version of Solaar are you running?

**Comment by tjbrn** [comment]
Arch Linux
Solaar 1.0.3

**Comment by pfps** [comment]
Solaar has only an incomplete implementation of device features, but it is improving.  If you clone and use Solaar from this site you should see more options for the K400+, including gestures.

**Comment by tjbrn** [comment]
### Installed solaar-git package from AUR and now there is more options, thanks!
![image](https://user-images.githubusercontent.com/10359351/95592082-86b15f80-0a1e-11eb-8ce8-41ee356e6ab2.png)
