### ISSUE TITLE
Allow unpriveleged user to choose autostart behavior.

### ISSUE THREAD

**Issue by mattld** [pwr-Solaar/Solaar#98]
Currently a solaar.desktop file is placed in /etc/xdg/autostart at install. This requires root for the user to choose autostart behavior. Solaar.desktop should instead be placed in ~/.config/autostart so that root is not required to change autostart behavior.

**Comment by acidg** [comment]
I see no possibility to disable the startup using the UI of Gnome 3.30.2. Even gnome-tweak-tools doesn't list the app as autostart. Only way for me was to copy the `/etc/xdg/autostart/solaar.desktop` to `~.config/autostart/solaar.desktop` and set `Hidden=true` in the .desktop file.
Would be nice to have a checkbox in Solaar, which does this for me.

**Comment by pfps** [comment]
Any window manager system that uses /etc/xdg/autostart should have a way of turning off the entries there for individual users.  Xfce has a Session and Startup setting that does this.
The --window flag for Solaar allows users to write desktop files with different behaviour. 

Closing as addressed by the window manager system.
