### ISSUE TITLE
Incorrect Vendor ID's in Documentation

### ISSUE THREAD

**Issue by dlintott** [pwr-Solaar/Solaar#984]
It would appear that some of the vendor ID's in the documentation are incorrect (https://pwr-solaar.github.io/Solaar/devices.html) shows a number of receivers with a vendor ID of 064d. I have two Logitech receivers (one unifying, one lightspeed), both of which have a vendor ID of 046d.

```
Bus 002 Device 010: ID 046d:c539 Logitech, Inc. 
Bus 002 Device 006: ID 046d:c52b Logitech, Inc. Unifying Receiver
```
Checking here: https://usb-ids.gowdy.us/read/UD/046d <- 046d is Logitech Vendor ID whereas 064d is for TriTech MicroElectronics (https://usb-ids.gowdy.us/read/UD/064d)

I am happy to open a pull request if you would like

**Comment by pfps** [comment]
Argh, a tyop!  They all should be the Logitech Vendor ID.  This will be fixed soon.

**Comment by pfps** [comment]
Should be fixed now. Thanks for picking this up.

**Comment by pfps** [comment]
Sorry for duplicating your work in the PR.  And thanks again.
